SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
create view [dbo].[V_CNTR] (
  [NUM],
  [VERSION],
  [VENDOR],
  [SIGNDATE],
  [BEGINDATE],
  [ENDDATE],
  [REALENDDATE],
  [VDRSIGNER],
  [DEPT],
  [SIGNER],
  [STAT],
  [NOTE],
  [FILETEXT],
  [PRNTIME]
) as
SELECT
	NUM, VERSION, VENDOR, SIGNDATE, BEGINDATE, ENDDATE, REALENDDATE, VDRSIGNER, DEPT, SIGNER, 
	STAT, NOTE, FILETEXT, PRNTIME
FROM CTCNTR
WHERE DEPT IN (SELECT SETTLEDEPTEMP.CODE
	FROM SETTLEDEPTEMP INNER JOIN EMPLOYEE ON SETTLEDEPTEMP.EMPGID = EMPLOYEE.GID
	WHERE EMPLOYEE.CODE = SUBSTRING(SUSER_SNAME(), CHARINDEX('_', SUSER_SNAME()) + 1, 20))
GO
