SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create view [dbo].[V_CNTRPAYCASH] (
  [NUM],
  [SETTLENO],
  [FILLER],
  [FILDATE],
  [VDRGID],
  [TRANSACTOR],
  [NOTE],
  [STAT],
  [PRNTIME],
  [PAYTOTAL],
  [SALETOTAL],
  [FEETOTAL],
  [PREPAYTOTAL],
  [SETTLEACCOUNTNO],
  [LSTUPDTIME],
  [PLANDATE],
  [FROMDATE],
  [TODATE],
  [CHECKER],
  [CHKFLAG],
  [PSR],
  [DEPT],
  [I_INV_AMT],
  [F_INV_AMT],
  [SUM_IN_AMT],
  [SUM_OUT_AMT],
  [SUM_PAY_AMT],
  [I_OS_BAL],
  [F_OS_BAL],
  [IN_AMT],
  [OUT_AMT],
  [OUT_COST],
  [SH_SALE_AMT],
  [SH_FEE_AMT],
  [PREPAY_AMT],
  [PAYED_AMT],
  [CYCLE],
  [BTYPE],
  [CHKDATE],
  [PGFTOTAL],
  [SH_PGF_AMT]
) as
SELECT NUM, SETTLENO, FILLER, FILDATE, VDRGID, TRANSACTOR, NOTE, STAT, PRNTIME, PAYTOTAL,
  SALETOTAL, FEETOTAL, PREPAYTOTAL, SETTLEACCOUNTNO, LSTUPDTIME, PLANDATE, FROMDATE, TODATE,
  CHECKER, CHKFLAG, PSR, DEPT, I_INV_AMT, F_INV_AMT, SUM_IN_AMT, SUM_OUT_AMT, SUM_PAY_AMT,
  I_OS_BAL, F_OS_BAL, IN_AMT, OUT_AMT, OUT_COST, SH_SALE_AMT, SH_FEE_AMT, PREPAY_AMT, PAYED_AMT,
  CYCLE, BTYPE, CHKDATE, PGFTOTAL, SH_PGF_AMT
FROM CNTRPAYCASH
WHERE DEPT IN (SELECT SETTLEDEPTEMP.CODE 
                FROM SETTLEDEPTEMP INNER JOIN EMPLOYEE ON SETTLEDEPTEMP.EMPGID = EMPLOYEE.GID
                WHERE EMPLOYEE.CODE = SUBSTRING(SUSER_SNAME(), CHARINDEX('_', SUSER_SNAME()) + 1, 20))
GO
