SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
create view [dbo].[CRMCARDSORTSCORE] (
  [CARDNUM],
  [SCORESORT],
  [SCORE]
) as
SELECT CRMCARDSCORE.CARDNUM CARDNUM,   CRMCARDSCORE.SCORESORT SCORESORT,
  SUM(CRMCARDSCORE.SCORE * CRMSCORESUBJECT.DIRECT) SCORE
FROM CRMCARDSCORE, CRMSCORESUBJECT
WHERE CRMCARDSCORE.SCORESUBJECT = CRMSCORESUBJECT.CODE
GROUP BY CRMCARDSCORE.CARDNUM ,CRMCARDSCORE.SCORESORT
GO
