SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
create view [dbo].[V_CNTRDPTBILL] (
  [NUM],
  [CLS],
  [VENDOR],
  [TOTAL],
  [STAT],
  [OPER],
  [FILLER],
  [FILDATE],
  [CHECKER],
  [NOTE],
  [DEPT],
  [PSR],
  [PAYER]
) as
SELECT
	NUM, CLS, VENDOR, TOTAL, STAT, OPER, FILLER, FILDATE, CHECKER, NOTE, DEPT, PSR, PAYER
FROM CNTRDPTBILL
WHERE DEPT IN (SELECT SETTLEDEPTEMP.CODE   
	FROM SETTLEDEPTEMP INNER JOIN EMPLOYEE ON SETTLEDEPTEMP.EMPGID = EMPLOYEE.GID  
 	WHERE EMPLOYEE.CODE = SUBSTRING(SUSER_SNAME(), CHARINDEX('_', SUSER_SNAME()) + 1, 20))
GO
