SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create view [dbo].[V_QPCGDSTORE] (
  [STOREGID],
  [GDGID],
  [BILLTO],
  [SALE],
  [RTLPRC],
  [INPRC],
  [LOWINV],
  [HIGHINV],
  [PROMOTE],
  [GFT],
  [LWTRTLPRC],
  [MBRPRC],
  [DXPRC],
  [PAYRATE],
  [ISLTD],
  [CNTINPRC],
  [BQTYPRC],
  [ALC],
  [TopRtlPrc],
  [ALCQTY],
  [INVLOWBOUND],
  [INVHIGHBOUND],
  [SUGGESTEDQTYLOWBOUND],
  [SUGGESTEDQTYHIGHBOUND],
  [SUGGESTEDQTY],
  [ORDQTYMIN],
  [QPCQPC],
  [QPCQPCSTR],
  [QPCRTLPRC],
  [QPCMBRPRC],
  [QPCLWTRTLPRC],
  [QPCTOPRTLPRC],
  [QPCBQTYPRC],
  [QPCPROMOTE],
  [SALCQTY],
  [SALCQSTART]
) as
SELECT G.STOREGID, G.GDGID, G.BILLTO, G.SALE, G.RTLPRC, G.INPRC, G.LOWINV, G.HIGHINV, G.PROMOTE, G.GFT,
  G.LWTRTLPRC, G.MBRPRC, G.DXPRC, G.PAYRATE, G.ISLTD, G.CNTINPRC, G.BQTYPRC, G.ALC, G.TopRtlPrc, G.ALCQTY,
  G.INVLOWBOUND, G.INVHIGHBOUND, G.SUGGESTEDQTYLOWBOUND, G.SUGGESTEDQTYHIGHBOUND, G.SUGGESTEDQTY, G.ORDQTYMIN,
  Q.QPC QPCQPC, Q.QPCSTR QPCQPCSTR, Q.RTLPRC QPCRTLPRC,
  Q.MBRPRC QPCMBRPRC, Q.LWTRTLPRC QPCLWTRTLPRC,
  Q.TOPRTLPRC QPCTOPRTLPRC, Q.BQTYPRC QPCBQTYPRC, Q.PROMOTE QPCPROMOTE, G.SALCQTY SALCQTY, G.SALCQSTART SALCQSTART
FROM GDSTORE G, GDQPCSTORE Q
WHERE G.GDGID = Q.GDGID AND G.STOREGID = Q.STOREGID
GO
