SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create view [dbo].[V_VDRBRAND] (
  [VENDOR],
  [VDRCODE],
  [VDRNAME],
  [BRAND],
  [BRNDNAME]
) as
SELECT DISTINCT V.GID VENDOR, V.CODE VDRCODE, V.NAME VDRNAME, B.CODE BRAND, B.NAME BRNDNAME
FROM GOODS G(NOLOCK), VENDOR V(NOLOCK), BRAND B(NOLOCK)
WHERE G.BILLTO = V.GID AND G.BRAND = B.CODE
GO
