SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create view [dbo].[CHECKINDTL] (
  [STORENO],
  [THEDATE],
  [CASHIER],
  [FROMDATE],
  [CURRENCY],
  [AMOUNT],
  [REALAMOUNT]
) as
SELECT	STORENO, CASHIER, THEDATE, FROMDATE, CURRENCY, AMOUNT, REALAMOUNT
	FROM	CHECKINDTLS
GO
