SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_GOODSAPP_CANNOTVIEW](NUM) AS
SELECT DISTINCT(GA.NUM) FROM GOODSAPPDTL DTL(NOLOCK) , GOODSAPP GA(NOLOCK) 
WHERE RTRIM(GA.APPMODE)<>'新增' AND GA.NUM = DTL.NUM 
AND DTL.GID NOT IN ( SELECT GID FROM V_GOODSH )
GO
