SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_YSTOREPLAN](YEAR, STORE, TOTAL, GP, GPRATE) AS				--年门店销售计划
	SELECT YEAR, STORE, SUM(TOTAL), SUM(GP), SUM(GP)/SUM(TOTAL)			
	FROM MSTOREPLAN			
	GROUP BY YEAR, STORE			
GO
