SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create view [dbo].[CHECKINDTLPOOL] (
  [ID],
  [STORENO],
  [THEDATE],
  [CASHIER],
  [FROMDATE],
  [CURRENCY],
  [AMOUNT],
  [REALAMOUNT]
) as
SELECT ID, STORENO, CASHIER, THEDATE, FROMDATE, CURRENCY, AMOUNT, REALAMOUNT
	FROM CHECKINDTLPOOLS
GO
