SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create view [dbo].[V_DPTVDR] (
  [DEPT],
  [DEPTNAME],
  [VENDOR],
  [VDRCODE],
  [VDRNAME]
) as
SELECT DISTINCT D.CODE DEPT, D.NAME DEPTNAME, V.GID VENDOR, V.CODE VDRCODE, V.NAME VDRNAME
FROM GOODS G(NOLOCK), DEPT D(NOLOCK), VENDOR V(NOLOCK)
WHERE G.F1 = D.CODE AND G.BILLTO = V.GID
GO
