SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
create view [dbo].[V_CNTRPREPAY] (
  [NUM],
  [VENDOR],
  [STAT],
  [PAYER],
  [VDRRCVER],
  [OCRDATE],
  [NOTE],
  [DEPT],
  [PSR],
  [FILLER],
  [FILDATE],
  [CHECKER],
  [TOTAL],
  [TOTALOFF],
  [CHKFLAG]
) as
SELECT
                NUM, VENDOR, STAT, PAYER, VDRRCVER, OCRDATE, NOTE, DEPT, PSR, FILLER, FILDATE, CHECKER, TOTAL, TOTALOFF, CHKFLAG
FROM CNTRPREPAY
WHERE DEPT IN (SELECT SETTLEDEPTEMP.CODE 
                FROM SETTLEDEPTEMP INNER JOIN EMPLOYEE ON SETTLEDEPTEMP.EMPGID = EMPLOYEE.GID
                WHERE EMPLOYEE.CODE = SUBSTRING(SUSER_SNAME(), CHARINDEX('_', SUSER_SNAME()) + 1, 20))
GO
