SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE view [dbo].[V_GOODSH] as        --YANG 2015.03.10
  select * FROM GOODSH(NOLOCK)
WHERE  left(F1,7) IN (SELECT DEPT FROM V_USERDEPT)       --YANG 2015.03.10
GO
