SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create view [dbo].[V_V_CNTRDPTINUNPAY] (
  [NUM],
  [VENDOR],
  [DEPT],
  [PAYEDAMT],
  [UNPAYAMT],
  [CANPAYAMT]
) as
SELECT A.NUM, A.VENDOR, A.DEPT, A.TOTALOFF PAYEDAMT, A.TOTAL - A.TOTALOFF UNPAYAMT, 
  CASE WHEN B.TOTAL < A.TOTAL - A.TOTALOFF THEN B.TOTAL ELSE A.TOTAL - A.TOTALOFF END CANPAYAMT 
FROM CNTRDPTBILL A, CNTRDPT B 
WHERE A.CLS = '收' AND A.STAT = 1800 AND A.VENDOR = B.VENDOR 
  AND A.NUM NOT IN 
    (SELECT B.IVCCODE FROM CNTRPAYCASH A, CNTRPAYCASHDTL B WHERE A.NUM = B.NUM AND A.STAT NOT IN (110, 900, 300) AND B.CHGTYPE = '压库金额收款单')
  AND A.NUM NOT IN 
    (SELECT B.SRCNUM FROM CNTRDPTBILL A, CNTRDPTOUTSRCDTL B WHERE A.NUM = B.NUM AND A.CLS = '付' AND A.STAT <> 900 AND B.SRCCLS = 'DSPIN')
  AND A.DEPT IN (SELECT SETTLEDEPTEMP.CODE FROM SETTLEDEPTEMP, EMPLOYEE WHERE SETTLEDEPTEMP.EMPGID = EMPLOYEE.GID  
    AND EMPLOYEE.CODE = SUBSTRING(SUSER_SNAME(), CHARINDEX('_', SUSER_SNAME()) + 1, 20))
GO
