SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
create view [dbo].[CRMCARDSORTSCOREH] (
  [CARDNUM],
  [CARRIER],
  [SCORESORT],
  [SCORE]
) as
SELECT CRMCARDSCORE.CARDNUM CARDNUM, CRMCARDSCORE.CARRIER,  CRMCARDSCORE.SCORESORT SCORESORT,
  SUM(CRMCARDSCORE.SCORE * CRMSCORESUBJECT.DIRECT) SCORE
FROM CRMCARDSCOREH CRMCARDSCORE(NOLOCK), CRMSCORESUBJECT(NOLOCK)
WHERE CRMCARDSCORE.SCORESUBJECT = CRMSCORESUBJECT.CODE
GROUP BY CRMCARDSCORE.CARDNUM, CRMCARDSCORE.CARRIER, CRMCARDSCORE.SCORESORT
GO
