SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
create view [dbo].[CRMCARDINVDTL] (
  [CARDNUM],
  [BYTIME],
  [CARDTYPE],
  [CARRIER],
  [STAT],
  [LSTUPDTIME],
  [VERSION],
  [MAKETIME],
  [SNDTIME],
  [INVSTAT]
) as
SELECT CRMCARD.*, CRMCARDINV.STAT INVSTAT
FROM CRMCARD, CRMCARDINV
WHERE CRMCARD.CARDNUM = CRMCARDINV.CARDNUM
GO
