SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create view [dbo].[V_CHGBOOK] (
  [NUM],
  [VENDOR],
  [CNTRNUM],
  [CHGCODE],
  [CalcTotal],
  [CalcRate],
  [SHOULDAMT],
  [REALAMT],
  [OCRDATE],
  [SIGNDATE],
  [SIGNER],
  [FILDATE],
  [FILLER],
  [CHKDATE],
  [CHECKER],
  [SETTLENO],
  [STAT],
  [NOTE],
  [CALCBEGIN],
  [CALCEND],
  [FIXNOTE],
  [BTYPE],
  [SRCNUM],
  [SRCCLS],
  [PRNTIME],
  [MODNUM],
  [LSTUPDTIME],
  [BILLTO],
  [GATHERINGMODE],
  [ACCOUNTTERM],
  [PAYTOTAL],
  [DEPT],
  [PAYDIRECT],
  [PAYDATE],
  [PSR],
  [GENDATE],
  [PAYUNIT]
) as
SELECT 
	 NUM, VENDOR, CNTRNUM, CHGCODE, CALCTOTAL, CALCRATE, SHOULDAMT, REALAMT, OCRDATE, SIGNDATE, SIGNER, FILDATE, 
	 FILLER, CHKDATE, CHECKER, SETTLENO, STAT, NOTE, CALCBEGIN, CALCEND, FIXNOTE, BTYPE, SRCNUM, SRCCLS, 
	 PRNTIME, MODNUM, LSTUPDTIME, BILLTO, GATHERINGMODE, ACCOUNTTERM, PAYTOTAL, DEPT, PAYDIRECT, PAYDATE, PSR, GENDATE, PAYUNIT
FROM 
	CHGBOOK
WHERE DEPT IN (SELECT SETTLEDEPTEMP.CODE
	FROM SETTLEDEPTEMP INNER JOIN EMPLOYEE ON SETTLEDEPTEMP.EMPGID = EMPLOYEE.GID
	WHERE EMPLOYEE.CODE = SUBSTRING(SUSER_SNAME(), CHARINDEX('_', SUSER_SNAME()) + 1, 20))
GO
