SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create view [dbo].[CHECKIN] (
  [FILLTIME],
  [OPERATOR],
  [CASHIER],
  [STORENO],
  [THEDATE],
  [FROMDATE],
  [AMOUNT],
  [REALAMOUNT],
  [RETAILAMT],
  [MILKAMT],
  [PUCAMT],
  [BILLCOUNT]
) as
SELECT FILLTIME, OPERATOR, CASHIER, STORENO, THEDATE, FROMDATE, AMOUNT, RETAILAMT, RETAILAMT, MILKAMT, PUCAMT, BILLCOUNT
	FROM CHECKINS
GO
