SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_YDEPTPLAN] (YEAR, DEPT, TOTAL, GP, GPRATE) AS				--年部门销售计划
	SELECT YEAR, DEPT, SUM(TOTAL), SUM(GP), SUM(GP)/SUM(TOTAL)			
	FROM MDEPTPLAN			
	GROUP BY YEAR, DEPT			
GO
