SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create view [dbo].[FASYSTEM] (
  [CARDGID],
  [USERID],
  [DIRMODE],
  [CFMBYSELF],
  [OUTPRCMODE],
  [ZBGID],
  [BILLTYPE],
  [HDSYSCODE],
  [COLLATETIME],
  [USERCODE],
  [USERNAME],
  [ENGLISHNAME],
  [INSTALLDATE],
  [EMPGID],
  [EMPGRPGID],
  [GDGID],
  [VDRGID],
  [CLNGID],
  [WRHGID],
  [USERGID],
  [RTL],
  [UPD],
  [USERPROPERTY],
  [NETBILLID],
  [ALEN],
  [BLEN],
  [CLEN],
  [DLEN],
  [AUTORTL],
  [RSTWRH],
  [INPRCTAX],
  [STOREGID],
  [MANYLINES],
  [BNUMCANBENULL],
  [DFTWRH],
  [SINGLEVDR],
  [DSP],
  [TAXNO],
  [ADDR],
  [TELE],
  [BANK],
  [ACCOUNTNO],
  [ALCWRH],
  [DIRALCWRH],
  [OUTINPRCMODE],
  [BATCHFLAG],
  [SWINVFLAG],
  [SUBWRHGID],
  [STAMPMENU],
  [PAYFLAG],
  [VERSION],
  [ENTERPRISENAME]
) as
SELECT
CARDGID ,USERID
,DIRMODE ,CFMBYSELF
,OUTPRCMODE ,ZBGID ,BILLTYPE
,HDSYSCODE ,COLLATETIME
,USERCODE ,USERNAME ,ENGLISHNAME
,INSTALLDATE
,EMPGID
,EMPGRPGID
,GDGID ,VDRGID ,CLNGID ,WRHGID ,USERGID
,RTL ,UPD ,USERPROPERTY
,NETBILLID
,ALEN ,BLEN ,CLEN ,DLEN
,AUTORTL
,RSTWRH ,INPRCTAX ,STOREGID
,MANYLINES
,BNUMCANBENULL
,DFTWRH
,SINGLEVDR
,DSP
,TAXNO
,ADDR ,TELE ,BANK ,ACCOUNTNO
,ALCWRH ,DIRALCWRH
,OUTINPRCMODE
,BATCHFLAG
,SWINVFLAG
,SUBWRHGID
,STAMPMENU ,PAYFLAG ,VERSION,
ENTERPRISENAME
FROM SYSTEM
GO
