SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO

CREATE VIEW [dbo].[GOODS_DEPT] AS 
SELECT * FROM GOODS_DEPT_MONTH53 UNION ALL SELECT * FROM GOODS_DEPT_MONTH54 UNION ALL
SELECT * FROM GOODS_DEPT_MONTH55 UNION ALL SELECT * FROM GOODS_DEPT_MONTH56 UNION ALL 
SELECT * FROM GOODS_DEPT_MONTH57 UNION ALL SELECT * FROM GOODS_DEPT_MONTH58 UNION ALL 
SELECT * FROM GOODS_DEPT_MONTH59 UNION ALL SELECT * FROM GOODS_DEPT_MONTH60 UNION ALL 
SELECT * FROM GOODS_DEPT_MONTH61 UNION ALL SELECT * FROM GOODS_DEPT_MONTH62 UNION ALL 
SELECT * FROM GOODS_DEPT_MONTH63 UNION ALL SELECT * FROM GOODS_DEPT_MONTH64 UNION ALL
SELECT * FROM GOODS_DEPT_MONTH65 UNION ALL SELECT * FROM GOODS_DEPT_MONTH66 UNION ALL
SELECT * FROM GOODS_DEPT_MONTH67 UNION ALL SELECT * FROM GOODS_DEPT_MONTH68 UNION ALL 
SELECT * FROM GOODS_DEPT_MONTH69 UNION ALL SELECT * FROM GOODS_DEPT_MONTH70 UNION ALL
SELECT * FROM GOODS_DEPT_MONTH71 UNION ALL SELECT * FROM GOODS_DEPT_MONTH72 UNION ALL
SELECT * FROM GOODS_DEPT_MONTH73 UNION ALL SELECT * FROM GOODS_DEPT_MONTH74 UNION ALL
SELECT * FROM GOODS_DEPT_MONTH75 UNION ALL SELECT * FROM GOODS_DEPT_MONTH76 UNION ALL
SELECT * FROM GOODS_DEPT_MONTH77 UNION ALL SELECT * FROM GOODS_DEPT_MONTH78 UNION ALL
SELECT * FROM GOODS_DEPT_MONTH79 UNION ALL SELECT * FROM GOODS_DEPT_MONTH80 UNION ALL 
SELECT * FROM GOODS_DEPT_MONTH81 UNION ALL SELECT * FROM GOODS_DEPT_MONTH82 UNION ALL
SELECT * FROM GOODS_DEPT_MONTH83 UNION ALL SELECT * FROM GOODS_DEPT_MONTH84 UNION ALL 
SELECT * FROM GOODS_DEPT_MONTH85 UNION ALL SELECT * FROM GOODS_DEPT_MONTH86 UNION ALL 
SELECT * FROM GOODS_DEPT_MONTH87 UNION ALL SELECT * FROM GOODS_DEPT_MONTH88 UNION ALL 
SELECT * FROM GOODS_DEPT_MONTH89
GO
