SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create view [dbo].[V_BCKDMD_CANVIEW] (
  [NUM]
) as
SELECT DISTINCT(DTL.NUM) NUM FROM BCKDMDDTL DTL(NOLOCK), V_GOODSH GD
WHERE GD.GID = DTL.GDGID
GROUP BY DTL.NUM
HAVING COUNT(1) = (SELECT RECCNT FROM BCKDMD MST(NOLOCK) WHERE MST.NUM = DTL.NUM)
GO
