SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_INDRPTI] AS			
  SELECT ASTORE, ASETTLENO, ADATE, BGDGID, BWRH,			
    SUM(CQ1) CQ1, SUM(CQ2) CQ2, SUM(CQ3) CQ3, SUM(CQ4) CQ4,			
    SUM(CT1) CT1, SUM(CT2) CT2, SUM(CT3) CT3, SUM(CT4) CT4,			
    SUM(CI1) CI1, SUM(CI2) CI2, SUM(CI3) CI3, SUM(CI4) CI4,			
    SUM(CR1) CR1, SUM(CR2) CR2, SUM(CR3) CR3, SUM(CR4) CR4			
  FROM INDRPTI			
  GROUP BY ASTORE, ASETTLENO, ADATE, BGDGID, BWRH			

GO
