SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create view [dbo].[V_ALCINV] (
  [STORE],
  [WRH],
  [GDGID],
  [AVLQTY],
  [RSVALCQTY],
  [TOTAL]
) as
SELECT STORE, WRH, GDGID, QTY - RSVALCQTY AVLQTY, RSVALCQTY, TOTAL
    FROM INV(NOLOCK)
GO
