SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[VdrBckDmdCHK]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS	 CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
	DECLARE @VRET INT
	DECLARE @VSTAT INT
	DECLARE @VACTNAME CHAR(40)
	DECLARE @VSTATNAME CHAR(40)
	DECLARE @EXP DATETIME
	DECLARE @LKNUM VARCHAR(13)
    DECLARE @line int;
    	SET @VRET = 0;

	SELECT @VSTAT = STAT FROM VdrBckDmd
	WHERE NUM = @NUM
	IF @@ROWCOUNT = 0
	BEGIN
		SET @MSG = '单据' + @NUM + '不存在'
		RETURN 1
	END
	IF @TOSTAT IN (401,1600,500)
	BEGIN
	  SELECT @EXP = EXPDATE FROM VdrBckDmd WHERE NUM = @NUM
	  IF (@EXP IS NOT NULL) AND (@EXP <= GETDATE()-1)
	  BEGIN
	    SET @MSG = '单据' + @NUM + '已经超过到效日期'
	    RETURN 1
	  END
	END

    -- zhourong
    IF EXISTS (SELECT 1 FROM Vendor, VdrBckDmd WHERE BckLmt = 1 AND Gid = Vendor)
    BEGIN
        SET @msg = '供应商已经被限制退货。';
        RETURN 1;
    END;

    SET @line = NULL
    SELECT TOP 1 @line = d.Line FROM VdrBckDmdDtl d, VdrBckDmd m, Goods g
    WHERE m.Num = d.Num AND d.GDGid = g.Gid AND g.IsLtd & 32 = 32
    IF @line IS NOT NULL
    BEGIN
        SET @msg = '单据第 ' + CONVERT(varchar(8), @line) + ' 行的商品是限制向供应商退货商品。';
        RETURN 1;
    END
    -- End

	IF @VSTAT = 0 AND @TOSTAT = 401  --请求总部批准
	BEGIN
	  EXEC @VRET = CHKVDRBCKDMD_0TO401 @NUM, @OPER, @CLS, @TOSTAT, @MSG OUTPUT
          RETURN @VRET
        END
	IF @VSTAT = 401 AND @TOSTAT = 1600  --预审
	BEGIN
	  EXEC @VRET = CHKVDRBCKDMD_401TO1600 @NUM, @OPER, @CLS, @TOSTAT, @MSG OUTPUT
          RETURN @VRET
        END
	IF @VSTAT IN (401,1600) AND @TOSTAT = 500  --审核
	BEGIN
	  EXEC @VRET = CHKVDRBCKDMD_40XTO500 @NUM, @OPER, @CLS, @TOSTAT, @MSG OUTPUT
          RETURN @VRET
        END
	IF (@VSTAT IN (401,1600)) AND @TOSTAT = 411  --作废
	BEGIN
	  EXEC @VRET = CHKVDRBCKDMD_40XTO411 @NUM, @OPER, @CLS, @TOSTAT, @MSG OUTPUT
          RETURN @VRET
	END
	IF (@VSTAT IN (401,1600,500)) AND @TOSTAT = 1400  --终止
	BEGIN
	  EXEC @VRET = CHKVDRBCKDMD_TO1400 @NUM, @OPER, @CLS, @TOSTAT, @MSG OUTPUT
          RETURN @VRET
	END
	IF (@VSTAT IN (500)) AND @TOSTAT = 300  --完成
	BEGIN
	  EXEC @VRET = CHKVDRBCKDMD_500TO300 @NUM, @OPER, @CLS, @TOSTAT, @MSG OUTPUT
          RETURN @VRET
        END
       	IF @VSTAT = 300 AND @TOSTAT = 300  --进退单据复核时触发
       	BEGIN
       	    RETURN 0
       	END

        --Added by pengke2004.11.01 申请后作废
        IF @VSTAT = 500 AND @TOSTAT = 410
        BEGIN
          EXEC @VRET = CHKVDRBCKDMD_500TO410 @NUM, @OPER, @CLS, @TOSTAT, @MSG OUTPUT
          RETURN @VRET
        END

	SELECT @VACTNAME = ACTNAME FROM MODULESTAT(NOLOCK) WHERE NO = @TOSTAT
	SELECT @VSTATNAME = STATNAME FROM MODULESTAT(NOLOCK) WHERE NO = @VSTAT
    SET @MSG = '不能' + @VACTNAME + '状态为' + @VSTATNAME + '的退货申请单'
    RETURN 1
END
GO
