SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[XFFIFOCHK]
	@PI_NUM CHAR(10),
	@PI_LINE INT,
	@PI_WRH INT,
	@PI_GDGID INT,
	@PI_QTY MONEY,
	@PI_TOTAL MONEY,
	@PI_COST MONEY OUTPUT,
	@PI_ERRMSG VARCHAR(200) OUTPUT
AS
BEGIN
	DECLARE @AMT MONEY,@NEWSUBWRH INT
		,@SUBWRH INT
	DECLARE @SPECIALWRH INT

	SELECT @SPECIALWRH = -100

	DECLARE @RETURN_STATUS INT

	IF @PI_QTY < 0
	BEGIN
		SELECT @PI_ERRMSG = '不允许为负数'
		RETURN 1005

	END

	EXEC CLEARTEMPSUBWRH @PI_GDGID,@PI_WRH

	IF EXISTS(SELECT 1 FROM XFDTL2 WHERE NUM = @PI_NUM AND LINE = @PI_LINE)
	BEGIN
		SELECT @PI_ERRMSG = '先进先出方式下内部调拨单不能指定批次调出。'
		RETURN -1
	END

	EXEC @RETURN_STATUS = UNLOADSUBWRH_2 @PI_GDGID,@PI_WRH,@PI_QTY,@PI_COST OUTPUT

	IF @RETURN_STATUS <> 0 RETURN @RETURN_STATUS
	
        DELETE FROM XFDTL2 WHERE NUM = @PI_NUM AND LINE = @PI_LINE
	INSERT INTO XFDTL2(NUM,LINE,SUBWRH,WRH,GDGID,QTY,COST,FROMTO)
		SELECT @PI_NUM,@PI_LINE,SUBWRH,WRH,GDGID,QTY,COST,-1 FROM TEMPSUBWRH
			WHERE SPID = @@SPID AND GDGID = @PI_GDGID AND WRH = @PI_WRH


	SELECT @NEWSUBWRH= MIN(SUBWRH) FROM TEMPSUBWRH WHERE SPID = @@SPID AND WRH = @PI_WRH AND GDGID = @PI_GDGID
	


	UPDATE XFDTL SET COST = @PI_COST,FROMSUBWRH = @NEWSUBWRH
		WHERE NUM = @PI_NUM AND LINE = @PI_LINE

	EXEC CLEARTEMPSUBWRH @PI_GDGID,@PI_WRH
	--将调出的商品生成到WRH为 -100 的仓位中
	EXEC CLEARTEMPSUBWRH @PI_GDGID,@SPECIALWRH

	INSERT INTO TEMPSUBWRH(SPID,SUBWRH,WRH,GDGID,QTY,COST)
		SELECT @@SPID,SUBWRH,@SPECIALWRH,GDGID,QTY,COST FROM XFDTL2 WHERE NUM = @PI_NUM AND LINE = @PI_LINE AND FROMTO = -1

	EXEC @RETURN_STATUS = LOADINSUBWRH_2 @PI_GDGID,@SPECIALWRH,@PI_QTY,@PI_COST
	
	IF @RETURN_STATUS <> 0 RETURN @RETURN_STATUS
	
	EXEC CLEARTEMPSUBWRH @PI_GDGID,@SPECIALWRH

	RETURN 0

END
GO
