SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[INPRCADJNOTIFY_SENDONESTORE](
  @NUM	CHAR(14),
  @OPER	CHAR(30),
  @CLS	CHAR(10),
  @TOSTAT	INT, --该字段由门店处理时回写
  @STORE	INT,
  @MSG	VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE
    @ID INT,
    @RCV INT,
    @SRC INT

  EXECUTE GETNETBILLID @ID OUTPUT
  SELECT @SRC = USERGID FROM SYSTEM(NOLOCK)

  DELETE NINPRCADJNOTIFYDTL
  FROM NINPRCADJNOTIFY M(NOLOCK)
  WHERE M.ID = NINPRCADJNOTIFYDTL.ID AND M.SRC= NINPRCADJNOTIFYDTL.SRC
  AND M.RCV = @STORE AND M.SRC = @SRC AND M.NUM = @NUM

  DELETE NINPRCADJNOTIFYBCKDTL
  FROM NINPRCADJNOTIFY M(NOLOCK)
  WHERE M.ID = NINPRCADJNOTIFYBCKDTL.ID AND M.SRC= NINPRCADJNOTIFYBCKDTL.SRC
  AND M.RCV = @STORE AND M.SRC = @SRC AND M.NUM = @NUM

  DELETE FROM NINPRCADJNOTIFY WHERE RCV = @STORE AND SRC = @SRC AND NUM = @NUM

  INSERT INTO NINPRCADJNOTIFY(NUM, SRCSTORE, STAT, BGNTIME, ENDTIME, SUBTIME, SUBEMP, SUBJECT,
    EXESTAT, MODIFIER, LSTUPDTIME, LSTRPLYTIME, SNDDATE, PRNTIME, NOTE, SRCNUM, SRCCLS,
    GENBILL, GENNUM, GENCLS, VENDOR, ADJMETHOD, CANPAY, DIFFPROCMETHOD, RCVFRCCHK,
    WAITFORFIN, FINEXP, ID, SRC, RCV, RCVTIME, NTYPE, NSTAT, NNOTE, FINISHED, FILLER, FILDATE, SETTLENO)
  SELECT NUM, SRCSTORE, STAT, BGNTIME, ENDTIME, SUBTIME, SUBEMP, SUBJECT,
    EXESTAT, MODIFIER, LSTUPDTIME, LSTRPLYTIME, SNDDATE, PRNTIME, NOTE, SRCNUM, SRCCLS,
    GENBILL, GENNUM, GENCLS, VENDOR, ADJMETHOD, CANPAY, DIFFPROCMETHOD, RCVFRCCHK,
    WAITFORFIN, FINEXP, @ID, @SRC, @STORE, NULL, 0, 0, NULL, FINISHED, FILLER, FILDATE, SETTLENO
  FROM INPRCADJNOTIFY(NOLOCK)
  WHERE NUM = @NUM

  IF @@ERROR <> 0
  BEGIN
      SET @MSG = '发送' + @NUM + '门店' + @STORE + '单据失败'
      RETURN 1
  END

  INSERT INTO NINPRCADJNOTIFYDTL (NUM, LINE, GDGID, DEFPRC, DIFFPRC, PLANQTY, NOTE, SRC, ID, OLDINPRC, OLDRTLPRC, OLDCNTINPRC)
  SELECT NUM, LINE, GDGID, DEFPRC, DIFFPRC, PLANQTY, NOTE, @SRC, @ID, OLDINPRC, OLDRTLPRC, OLDCNTINPRC
  FROM INPRCADJNOTIFYDTL(NOLOCK)
  WHERE NUM = @NUM

  IF @@ERROR <> 0
    BEGIN
      SET @MSG = '发送' + @NUM + '门店' + @STORE + '单据失败'
      RETURN 2
  END

  IF EXISTS(SELECT 1 FROM SYSTEM(NOLOCK) WHERE USERGID <> ZBGID) --门店发送
    INSERT INTO NINPRCADJNOTIFYBCKDTL (NUM, LINE, STOREGID, GDGID, DEFPRC, DIFFPRC, PLANQTY,
      QTY, OLDPRC, NEWPRC, NOTE, SRC, ID, STAT, AMT, CNTAMT, CNTPRC, LACTIME)
    SELECT NUM, LINE, STOREGID, GDGID, DEFPRC, DIFFPRC, PLANQTY,
      QTY, OLDPRC, NEWPRC, NOTE, @SRC, @ID, STAT, AMT, CNTAMT, CNTPRC, LACTIME
    FROM INPRCADJNOTIFYBCKDTL(NOLOCK)
    WHERE NUM = @NUM
  ELSE
    INSERT INTO NINPRCADJNOTIFYBCKDTL (NUM, LINE, STOREGID, GDGID, DEFPRC, DIFFPRC, PLANQTY,
      QTY, OLDPRC, NEWPRC, NOTE, SRC, ID, STAT, AMT, CNTAMT, CNTPRC, LACTIME)
    SELECT NUM, LINE, STOREGID, GDGID, DEFPRC, DIFFPRC, PLANQTY,
      QTY, OLDPRC, NEWPRC, NOTE, @SRC, @ID, @TOSTAT, AMT, CNTAMT, CNTPRC, LACTIME
    FROM INPRCADJNOTIFYBCKDTL(NOLOCK)
    WHERE NUM = @NUM AND STOREGID = @STORE

  IF @@ERROR <> 0
    BEGIN
      SET @MSG = '发送' + @NUM + '门店' + @STORE + '单据失败'
      RETURN 3
  END

  RETURN 0
END
GO
