SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create procedure [dbo].[MXFDMD_CHKWITHSCHEME]
(
  @Num varchar(14),
  @Oper varchar(20),
  @Msg varchar(255) output
) as
begin
  declare
    @STOREGID INT,
    @GDGID INT,
    @VGDGID VARCHAR(100), --记录过滤商品GID
    @MONTHSETTLENO INT,
    @EMPLOYEECODE CHAR(10),
    @EMPLOYEENAME CHAR(20),
    @CONTENT VARCHAR(255)

  --取到调入门店
  SELECT @STOREGID = TOSTORE FROM MXFDMD WHERE NUM = @Num
  SET @VGDGID = ''
  --几个用于记日志的字段
  SELECT @MONTHSETTLENO = MAX(NO) FROM MONTHSETTLE
  select @EMPLOYEECODE = SUBSTRING(@Oper, (CHARINDEX('[', @Oper) +1), (CHARINDEX(']', @Oper) - CHARINDEX('[', @Oper) - 1))  
  select @EMPLOYEENAME = SUBSTRING(@Oper, 1, CHARINDEX('[', @Oper) - 1)

  DECLARE C_CURGD CURSOR FOR
    SELECT GDGID
      FROM MXFDMDDTL WHERE NUM = @Num
  OPEN C_CURGD
  FETCH NEXT FROM C_CURGD INTO @GDGID
  WHILE @@FETCH_STATUS = 0
  BEGIN
    IF NOT EXISTS(SELECT 1 FROM CURSTOREOPERSCHEME WHERE GDGID = @GDGID 
      AND STOREGID = @STOREGID AND ISOPER = 1)
    BEGIN
      IF @VGDGID <> ''
        SET @VGDGID = @VGDGID + ',' + STR(@GDGID)
    END

    FETCH NEXT FROM C_CURGD INTO @GDGID
  END
  CLOSE C_CURGD
  DEALLOCATE C_CURGD

  IF @VGDGID <> ''
  BEGIN
    --删除过滤掉的商品
    DELETE FROM MXFDMDDTL WHERE NUM = @Num AND GDGID IN (@VGDGID)
    --将过滤的商品记录日志备查
    SET @CONTENT = '门店调拨单明细中存在商品不属于调入门店经营方案,已自动删除:(' + @VGDGID + ')'
    INSERT INTO LOG(TIME, MONTHSETTLENO, EMPLOYEECODE, EMPLOYEENAME, WORKSTATIONNO, MODULENAME, TYPE, CONTENT)
    VALUES(getdate(), @MONTHSETTLENO, @EMPLOYEECODE, @EMPLOYEENAME, '未知', '门店调拨申请单', 303, @CONTENT)
  END

  RETURN(0)
end
GO
