SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CHKBCKDMDTO411]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS	 CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
	DECLARE @LmtOperForNotSplitMDBill int,
	        @USERGID INT,         @SRCNUM CHAR(14),
	        @SRC INT
	EXEC OPTREADINT 518,'LmtOperForNotSplitMDBill',0,@LmtOperForNotSplitMDBill OUTPUT
	SELECT @USERGID = USERGID FROM SYSTEM
	SELECT @SRCNUM = SRCNUM, @SRC = SRC FROM BCKDMD WHERE NUM = @NUM
	IF @LmtOperForNotSplitMDBill = 1 AND @SRC <> @USERGID
	  AND (@SRCNUM IS NULL OR RTRIM(@SRCNUM) = '')
	BEGIN
		SET @MSG ='单据是门店单据但未经过拆分不能审批。'
		RETURN 1
	END
	UPDATE BCKDMD SET
		STAT = 411,
		CACLDATE = GETDATE(),
		CANCELER = @OPER,
		LSTUPDTIME = GETDATE()
	WHERE NUM = @NUM
	EXEC BCKDMDADDLOG @NUM, 411, '', @OPER
	RETURN 0
END
GO
