SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[DELNPROMB]
(
	@SRC	INT,
	@ID	INT
)
AS
BEGIN
	DELETE FROM NPROMB WHERE SRC = @SRC AND ID = @ID
	DELETE FROM NPROMBGOODS WHERE SRC = @SRC AND ID = @ID		
	DELETE FROM NPROMBDIS WHERE SRC = @SRC AND ID = @ID	
END
GO
