SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE PROCEDURE [dbo].[CHKCNTRPREPAYTO600]
(
	@NUM		VARCHAR(14),
	@OPER		VARCHAR(50),
	@MSG	VARCHAR(255) OUTPUT
)
AS
BEGIN
	--PIOPER为对方收款人
	UPDATE CNTRPREPAY SET STAT = 600,VDRRCVER = @OPER WHERE NUM = @NUM
  	RETURN 0 
END 
GO
