SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create procedure [dbo].[CHQSNDORD](
	@NUM VARCHAR(14),
	@CLS VARCHAR(10),
	@OPERGID INT,
	@MSG VARCHAR(255) OUTPUT
) as
begin
  declare @GROUPID INT,     @NTYPE SMALLINT,    @NNOTE varchar(100),
          @EXTIME DATETIME, @RHQUUID CHAR(32),  @NSTAT SMALLINT
  --exec OPTREADINT 0, '...', 0, @optvalue output
  if not exists(select 1 from ORD where num = @num and STAT = 1)
  begin
    set @msg = '不能定位已经审核的定单'+@num
    return 1
  end  
  
  exec @GROUPID = SeqNextValue 'CHQBASIC'
  set @RHQUUID = '1'
  set @NTYPE = 0
  set @NNOTE = ''
  set @NSTAT = 0
  set @EXTIME = Getdate()
  insert into CQNORD(GROUPID, RHQUUID, NTYPE, NSTAT, NNOTE, EXTIME, 
      NUM, SETTLENO, VENDOR, TOTAL, TAX, NOTE, FILDATE, PAYDATE, 
      PREPAY, FILLER, CHECKER, STAT, MODNUM, WRH, RECCNT, SRC, 
      SRCNUM, SNDTIME, RECEIVER, PSR, PRNTIME, FINISHED, EXPDATE, 
      ALCCLS, PRECHECKER, PRECHKDATE, DLVBDATE, DLVEDATE, IMPFLAG, 
      ALCGID)
    select @GROUPID, @RHQUUID, @NTYPE, @NSTAT, @NNOTE, @EXTIME, 
      NUM, SETTLENO, VENDOR, TOTAL, TAX, NOTE, FILDATE, PAYDATE, 
      PREPAY, FILLER, CHECKER, STAT, MODNUM, WRH, RECCNT, SRC, 
      SRCNUM, SNDTIME, RECEIVER, PSR, PRNTIME, FINISHED, EXPDATE, 
      ALCCLS, PRECHECKER, PRECHKDATE, DLVBDATE, DLVEDATE, IMPFLAG, 
      ALCGID
    from ORD(nolock)
    where NUM = @NUM
    
  insert into CQNORDDTL(GROUPID, RHQUUID, NTYPE, NSTAT, NNOTE, EXTIME,
      SETTLENO, NUM, LINE, GDGID, CASES, QTY, PRICE, TOTAL, TAX, 
      VALIDDATE, WRH, INVQTY, ARVQTY, ASNQTY, ALLINVQTY, NOTE, 
      FROMGID, FLAG, INUSE, LOCKNUM, LOCKCLS, SUBWRH)
    select @GROUPID, @RHQUUID, @NTYPE, @NSTAT, @NNOTE, @EXTIME, 
      SETTLENO, NUM, LINE, GDGID, CASES, QTY, PRICE, TOTAL, TAX, 
      VALIDDATE, WRH, INVQTY, ARVQTY, ASNQTY, ALLINVQTY, NOTE, 
      FROMGID, FLAG, INUSE, LOCKNUM, LOCKCLS, SUBWRH
    from ORDDTL(nolock)
    where NUM = @NUM
end;
GO
