SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[GoodsAppApplyUpd]
(
  @NUM CHAR(14),
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
	DECLARE @STAT INT, @I INT, @SSQL VARCHAR(255), @USERGID INT, @USERPROPERTY INT, @APPMODE VARCHAR(20)
	DECLARE @FIELDNAME VARCHAR(30)
	DECLARE @GDGID VARCHAR(30), @GDCODE VARCHAR(20)

	SELECT @USERGID = USERGID FROM SYSTEM
	SELECT @USERPROPERTY = PROPERTY FROM STORE WHERE GID = @USERGID
	SELECT @AppMode = AppMode FROM GoodsApp WHERE Num = @num;

	IF @APPMODE<>'修改'
	BEGIN
		SET @MSG = '单据更新模式不是修改'
		RAISERROR('单据更新模式不是修改',16,1)
		RETURN(-1)
	END

	-- 检查商品第二代码是否重复
	DECLARE @name varchar(30), @code varchar(13), @line int, @errorMsg varchar(256)
	SELECT @name = RTRIM(g.Name), @code = RTRIM(g.Code), @line = a.Line FROM Goods g, GoodsAppDtl a, [GOODSAPPFIELD] f
 	WHERE g.Code2 = a.Code2 AND a.Num = @num AND a.NUM = f.NUM AND f.FIELDNAME = 'Code2'
	IF @@ROWCOUNT <> 0
	BEGIN
	      SET @ErrorMsg = '第 ' + CONVERT(VARCHAR(50), @Line) + ' 行商品 ' + @Name + '[' + @Code + '] 的第二代码已经在总部存在，不能插入。'
		RAISERROR(@ErrorMsg, 16, 1)
		RETURN(-1)
	END

	--IF NOT EXISTS(SELECT 1 FROM GOODSAPPLAC WHERE STOREGID = @USERGID)
    	IF @USERPROPERTY & 16 <> 16
    	BEGIN
     	   SET @MSG = '只有总部才能更新'
     	   RAISERROR('只有总部才能更新',16,1)
     	   RETURN(0)
    	END
	DECLARE C_C CURSOR FOR
		SELECT FIELDNAME FROM GOODSAPPFIELD WHERE NUM = @NUM
	OPEN C_C
	FETCH NEXT FROM C_C INTO @FIELDNAME
	WHILE @@FETCH_STATUS=0
	BEGIN
		SET @SSQL = 'UPDATE GOODS SET ' + @FIELDNAME + ' = DTL.' + @FIELDNAME
			+ ' FROM GOODSAPPDTL DTL WHERE DTL.RATFLAG = 1 AND GOODS.CODE = DTL.CODE AND NUM = ''' + @NUM + ''''
		EXEC(@SSQL)
		IF @@ERROR <> 0
		BEGIN
            		SET @MSG = @MSG + '从单据'+@num+'更新字段['+@FIELDNAME+']时发生错误。'
            		CLOSE C_C
			DEALLOCATE C_C
			RAISERROR(@MSG,16,1)
			RETURN(-1)
		END
		FETCH NEXT FROM C_C INTO @FIELDNAME
	END
	CLOSE C_C
	DEALLOCATE C_C
	RETURN 0
END
GO
