SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[MKTPRC_RCV]
(
  @BILL_ID INT,
  @SRC_ID INT,
  @OPER CHAR(30),
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE
    @CUR_SETTLENO INT, @NET_NUM CHAR(14),
    @RCV_GID INT, @NET_STAT SMALLINT,
    @NET_TYPE SMALLINT

  SELECT @CUR_SETTLENO = MAX(NO) FROM MONTHSETTLE(NOLOCK)

  SELECT @RCV_GID = RCV, @NET_STAT = STAT, @NET_TYPE = NTYPE, @NET_NUM = NUM
  FROM NMKTPRC(NOLOCK) WHERE ID = @BILL_ID AND SRC = @SRC_ID
  IF @@ROWCOUNT = 0 OR @NET_NUM IS NULL
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '不存在'
    RETURN 1
  END

  IF EXISTS(SELECT 1 FROM MKTPRC(NOLOCK) WHERE NUM = @NET_NUM AND STAT = @NET_STAT)
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '已经被接收'
    RETURN 2
  END

  IF (SELECT MAX(USERGID) FROM SYSTEM(NOLOCK)) <>  @RCV_GID
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '接收单位不是本单位'
    RETURN 3
  END

  IF @NET_TYPE <> 1
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '不在接收缓冲区中'
    RETURN 4
  END

  DELETE FROM MKTPRC WHERE NUM = @NET_NUM
  DELETE FROM MKTPRCDTL WHERE NUM = @NET_NUM

  INSERT INTO MKTPRC(NUM, SETTLENO, STAT, STOREGID, SCHEMENUM, INVSTER, INVSTDATE, FILLER,
    FILDATE, CHECKER, CHKDATE, CANCELER, CACLDATE, LSTUPDTIME, SNDTIME, RECCNT, PRNTIME,
    INVSTOBJ, INVSTPLACE, NOTE)
  SELECT NUM, @CUR_SETTLENO, STAT, STOREGID, SCHEMENUM, INVSTER, INVSTDATE, FILLER,
    FILDATE, CHECKER, CHKDATE, CANCELER, CACLDATE, LSTUPDTIME, SNDTIME, RECCNT, PRNTIME,
    INVSTOBJ, INVSTPLACE, NOTE
  FROM NMKTPRC(NOLOCK)
  WHERE SRC = @SRC_ID AND ID = @BILL_ID

  IF @@ERROR <> 0
  BEGIN
    SET @MSG = '[接收]接收' + @NET_NUM + '单据失败'
    RETURN 5
  END

  INSERT INTO MKTPRCDTL(NUM, LINE, GDGID, GDQPCSTR, GDQPC, RTLPRC,
    CNTINPRC, WHSPRC, MBRPRC, PROMOTEPRICE, PROMOTEINPRC, PROMOTEMBRPRC, NOTE,
    LRTLPRC, LCNTINPRC, LWHSPRC, LMBRPRC, LPROMOTEPRICE, LPROMOTEINPRC, LPROMOTEMBRPRC)
  SELECT NUM, LINE, GDGID, GDQPCSTR, GDQPC, RTLPRC,
    CNTINPRC, WHSPRC, MBRPRC, PROMOTEPRICE, PROMOTEINPRC, PROMOTEMBRPRC, NOTE,
    LRTLPRC, LCNTINPRC, LWHSPRC, LMBRPRC, LPROMOTEPRICE, LPROMOTEINPRC, LPROMOTEMBRPRC
  FROM NMKTPRCDTL(NOLOCK)
  WHERE SRC = @SRC_ID AND ID = @BILL_ID

  IF @@ERROR <> 0
  BEGIN
    SET @MSG = '[接收]接收' + @NET_NUM + '单据失败'
    RETURN 6
  END

  UPDATE MKTPRCSCHEMESTOREDTL SET STAT = 1 WHERE NUM =
    (SELECT SCHEMENUM FROM NMKTPRC(NOLOCK) WHERE ID = @BILL_ID AND SRC = @SRC_ID)
    AND STOREGID = @SRC_ID AND STAT = 0

  DELETE FROM NMKTPRC WHERE ID = @BILL_ID AND SRC = @SRC_ID
  DELETE FROM NMKTPRCDTL WHERE ID = @BILL_ID AND SRC = @SRC_ID

  SET @MSG = '单据：' + @NET_NUM + '接收成功' + @MSG

  RETURN 0
END
GO
