SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[NPS3SPECGDSCORE_REMOVE]
(
  @SRC INT,
  @ID  INT
)
AS
BEGIN
  DELETE FROM NPS3SPECGDSCORE WHERE SRC = @SRC AND ID = @ID
  DELETE FROM NPS3SPECGDSCOREDTL WHERE SRC = @SRC AND ID = @ID
  DELETE FROM NPS3SPECGDSCOREPROMSUBJOUTDTL WHERE SRC = @SRC AND ID = @ID
END
GO
