SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[WRITEBATGOODSLOG]
(
  @GDNAME VARCHAR(65),
  @EMPNAME VARCHAR(50),
  @NOTE VARCHAR(256)
)
AS
BEGIN
  INSERT INTO BATCHINGOODSLOG(GDNAME, EMPNAME, CREATETIME, NOTE)
  VALUES(@GDNAME, @EMPNAME, GETDATE(), @NOTE)

  RETURN 0
END

GO
