SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[GDINVCHGNOTIFY_CHECK_0TO100]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE
    @RET INT, @LAUNCH DATETIME, @OPTAUTOSND INT,
    @SRC INT, @USERGID INT, @EXDIRECT INT

  SELECT @LAUNCH = LAUNCH, @SRC = SRC, @EXDIRECT = EXDIRECT FROM GDINVCHGNOTIFY(NOLOCK) WHERE NUM = @NUM
  
  IF @EXDIRECT = 1 
  BEGIN
    EXEC @RET = GDINVCHGNOTIFY_DOCHECK @NUM, @MSG OUTPUT
    IF @RET <> 0 RETURN @RET    
  END
  
  EXEC OPTREADINT 723, 'AUTOSNDONCHK', 1, @OPTAUTOSND OUTPUT
  
  SELECT @USERGID = USERGID FROM FASYSTEM(NOLOCK)

  UPDATE GDINVCHGNOTIFY SET
  STAT = 100, CHKDATE = GETDATE(), CHECKER = @OPER, LSTUPDTIME = GETDATE()
  WHERE NUM = @NUM

  EXEC @RET = GDINVCHGNOTIFY_ADDLOG @NUM, '转换单', @TOSTAT, '审核', @OPER
  IF @RET <> 0 RETURN @RET

  IF @OPTAUTOSND = 1 AND @SRC = @USERGID --避免门店接收时审核发送
  BEGIN
    EXEC @RET = GDINVCHGNOTIFY_SEND @NUM, @OPER, @CLS, @TOSTAT, @MSG OUTPUT
    IF @RET <> 0 RETURN @RET
  END

  IF (@LAUNCH IS NULL) OR (@LAUNCH <= GETDATE())
  BEGIN
    EXEC @RET = GDINVCHGNOTIFY_CHECK_OCR @NUM, @OPER, @CLS, 800, @MSG OUTPUT
    IF @RET <> 0 RETURN @RET
  END

  SET @MSG = '单据：' + @NUM + '审核成功'

  RETURN 0
END
GO
