SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[VDRPAYRTNSEND]
(
  @CLS CHAR(20),
  @NUM CHAR(14),
  @OPER CHAR(30),
  @TOSTAT INT,
  @MSG VARCHAR(255)	OUTPUT
)
AS
BEGIN
  DECLARE @SRC INT
  DECLARE @USERGID INT
  DECLARE @ID INT
  DECLARE @VRET INT
  DECLARE @VDRPAYNUM VARCHAR(14)
  DECLARE @STAT INT
  DECLARE @CHGNUM VARCHAR(14)
  
  SELECT @USERGID = USERGID FROM FASYSTEM(NOLOCK)
  SELECT @STAT = STAT, @VDRPAYNUM = VDRPAYNUM FROM CTVDRPAYRTN(NOLOCK) WHERE NUM = @NUM
  SET @SRC = NULL
  SELECT @SRC = G.SRC FROM VDRPAYDTL V(NOLOCK), CHGBOOK G(NOLOCK) WHERE V.NUM = @VDRPAYNUM AND V.CHGNUM = G.NUM
  
  IF @SRC IS NULL OR @SRC = @USERGID
  BEGIN
    SET @MSG = '发送动作无效，本单不需要发送'
    RETURN -1
  END
  
  UPDATE CTVDRPAYRTN SET SNDTIME = GETDATE() WHERE NUM = @NUM
  
  EXECUTE GETNETBILLID @ID OUTPUT
  INSERT INTO NCTVDRPAYRTN (NUM, VENDOR, STAT, FILLER, FILDATE, CHECKER, CHKDATE, OCRDATE, DEPT, 
    TOTAL, VDRPAYNUM, NOTE, LSTUPDTIME, LASTMODIFIER, SNDTIME, SRC, 
    ID, RCV, RCVTIME, NTYPE, NSTAT, NNOTE)
  SELECT NUM, VENDOR, STAT, FILLER, FILDATE, CHECKER, CHKDATE, OCRDATE, DEPT, 
    TOTAL, VDRPAYNUM, NOTE, LSTUPDTIME, LASTMODIFIER, SNDTIME, @USERGID, 
    @ID, @SRC, NULL, 0, 0, NULL
  FROM CTVDRPAYRTN(NOLOCK)
  WHERE NUM = @NUM

  RETURN 0
END
GO
