SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CHKICPAYTO110]
(
  @NUM VARCHAR(14),
  @OPER VARCHAR(30),
  @CLS	 VARCHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
	UPDATE ICPAY SET STAT = 110, MODIFIER = @OPER, LSTUPDTIME = GETDATE() 
	WHERE NUM = @NUM
    RETURN 0
END
GO
