SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[XFFIFORECEIVE]
	@PI_NUM CHAR(10),
	@PI_LINE INT,
	@PI_WRH INT,
	@PI_GDGID INT,
	@PI_QTY MONEY,
	@PI_TOTAL MONEY OUTPUT,
	@PI_ERRMSG VARCHAR(200) OUTPUT
AS
BEGIN
	DECLARE @AMT MONEY,@NEWSUBWRH INT
		,@SUBWRH INT
	DECLARE @SPECIALWRH INT
	
	DECLARE @COST MONEY

	SELECT @SPECIALWRH = -100

	DECLARE @RETURN_STATUS INT

	IF @PI_QTY < 0
	BEGIN
		SELECT @PI_ERRMSG = '不允许为负数'
		RETURN 1005

	END

	EXEC CLEARTEMPSUBWRH @PI_GDGID,@PI_WRH

	IF EXISTS(SELECT 1 FROM XFDTL2 WHERE NUM = @PI_NUM AND LINE = @PI_LINE AND FROMTO = 1)
	BEGIN
		SELECT @PI_ERRMSG = '先进先出方式下内部调拨单不能指定批次调入。'
		RETURN -1
	END
	IF NOT EXISTS(SELECT 1 FROM XFDTL2 WHERE NUM = @PI_NUM AND LINE = @PI_LINE AND FROMTO = -1)
	BEGIN
		SELECT @PI_ERRMSG = '先进先出方式下内部调拨单没有指定调出批次，不能进行调入操作。'
		RETURN -1
	END

	INSERT INTO TEMPSUBWRH(SPID,SUBWRH,WRH,GDGID,QTY,COST)
		SELECT @@SPID,SUBWRH,@PI_WRH,GDGID,QTY,COST FROM XFDTL2 WHERE NUM = @PI_NUM AND LINE = @PI_LINE AND FROMTO = -1
	
	EXEC @RETURN_STATUS = LOADINSUBWRH_2 @PI_GDGID,@PI_WRH,@PI_QTY,@PI_TOTAL

	IF @RETURN_STATUS <> 0 RETURN @RETURN_STATUS
	

	INSERT INTO XFDTL2(NUM,LINE,SUBWRH,WRH,GDGID,QTY,COST,COSTADJ,FROMTO)
		SELECT @PI_NUM,@PI_LINE,SUBWRH,WRH,GDGID,QTY,COST,COSTADJ,1 FROM TEMPSUBWRH
			WHERE SPID = @@SPID AND GDGID = @PI_GDGID AND WRH = @PI_WRH


	SELECT @NEWSUBWRH= MIN(SUBWRH),@PI_TOTAL = SUM(COST) FROM TEMPSUBWRH WHERE SPID = @@SPID AND WRH = @PI_WRH AND GDGID = @PI_GDGID
	


	UPDATE XFDTL SET TOSUBWRH = @NEWSUBWRH
		WHERE NUM = @PI_NUM AND LINE = @PI_LINE

	EXEC CLEARTEMPSUBWRH @PI_GDGID,@PI_WRH
	--将调入的商品从到WRH为 -100 的仓位中删除
	EXEC CLEARTEMPSUBWRH @PI_GDGID,@SPECIALWRH

	INSERT INTO TEMPSUBWRH(SPID,SUBWRH,WRH,GDGID,QTY,COST)
		SELECT @@SPID,SUBWRH,@SPECIALWRH,GDGID,QTY,COST FROM XFDTL2 WHERE NUM = @PI_NUM AND LINE = @PI_LINE AND FROMTO = 1

	EXEC @RETURN_STATUS = UNLOADSUBWRH_2 @PI_GDGID,@SPECIALWRH,@PI_QTY,@COST OUTPUT
	
	IF @RETURN_STATUS <> 0 RETURN @RETURN_STATUS
	
	EXEC CLEARTEMPSUBWRH @PI_GDGID,@SPECIALWRH

	RETURN 0

END
GO
