SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO

CREATE Procedure [dbo].[TA_stkinbck]
	@WHERE_CLAUSE VARCHAR(255)
As
declare @BeginDate char(10)
        ,@EndDate char(10)

declare @I int

select @I=charIndex(',',@WhERE_CLAUSE)

Select @BeginDate=SubString(@WHERE_CLAUSE,1,@I-1)
Select @EndDate=SubString(@WHERE_CLAUSE,@I+1,100)

EXEC ('DECLARE CUR_GETVOUCHER CURSOR GLOBAL FOR 
	SELECT RTRIM(VENDOR.CODE) A,
        RTRIM(vendor.name) B,
        ''供应商'' C,
	CONVERT(VARCHAR(100),CONVERT(DEC(20,2),SUM(STKINBCKDTL.QTY*STKINBCKDTL.INPRC/(1+GOODSH.TAXRATE/100)))) D, 
	CONVERT(VARCHAR(100),CONVERT(DEC(20,2),SUM(STKINBCKDTL.QTY*STKINBCKDTL.INPRC))-CONVERT(DEC(20,2),SUM(STKINBCKDTL.QTY*STKINBCKDTL.INPRC/(1+GOODSH.TAXRATE/100)))) E, 
	CONVERT(VARCHAR(100),CONVERT(DEC(20,2),SUM(STKINBCKDTL.TOTAL))) F,
	V_GDSORTA.SORT G,
	V_GDSORTA.NAME H,
	''RMB'' I,
	''1'' J,
	''部门'' K,
	''00'' L,
	''海滨配送中心'' M,
	''商品大类'' N,
	convert(int,GOODSH.TAXRATE) O
	FROM STKINBCKDTL STKINBCKDTL(NOLOCK), STKINBCK STKINBCK(NOLOCK), 
	VENDOR VENDOR(NOLOCK),GOODSH GOODSH(NOLOCK),v_gdsorta v_gdsorta(nolock) -- ,EMPLOYEEH EMPLOYEEH(NOLOCK)
	WHERE STKINBCK.NUM = STKINBCKDTL.NUM
	and  STKINBCK.CLS = STKINBCKDTL.CLS
        and  STKINBCK.CLS =''自营''
	and  VENDOR.GID = STKINBCK.VENDOR
	and  (STKINBCK.STAT<>0)
        and  STKINBCKDTL.GDGID = GOODSH.GID
        and  STKINBCKDTL.GDGID = V_GDSORTA.GID
        and  (GOODSH.SALE = 2 OR GOODSH.SALE=3)
--        and  STKINBCK.PSR = EMPLOYEEH.GID
       AND CONVERT(VARCHAR(10),STKINBCK.FILDATE,102) BETWEEN '''+@BEGINDATE+''' AND '''+ @ENDDATE+''' ' +  
	' GROUP BY VENDOR.CODE,vendor.name,V_GDSORTA.SORT, V_GDSORTA.NAME,GOODSH.TAXRATE')

RETURN 0




GO
