SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[LTDADJUNOCR]
AS
BEGIN
  DECLARE @FINISHDATE DATETIME
  DECLARE @OLDFINISHDATE DATETIME
  DECLARE @GDGID INT
  DECLARE @NEWVALUE INT
  DECLARE @OLDVALUE INT
  DECLARE @NEWVALUENUM CHAR(14)
  DECLARE @OLDSALE INT
  DECLARE @NEWSALE INT
  DECLARE @UPDATEKEEYPTYPE VARCHAR(10)
  DECLARE @UPDATELTD VARCHAR(10)
  DECLARE @KEEPTYPE INT
  DECLARE @LTD INT
  DECLARE @OptRd VARCHAR(100)

  EXEC OPTREADSTR 0, '限制业务调整途径', '1111', @OptRd OUTPUT
  IF SUBSTRING(@OPTRD, 4, 1) = '1'
  BEGIN
    DECLARE C_FINISH CURSOR FOR
      SELECT GDGID, OLDVALUE, NEWVALUE, FINISHDATE
        FROM GDLTD
      WHERE FINISHDATE <= getdate()
    OPEN C_FINISH
    FETCH NEXT FROM C_FINISH INTO @GDGID, @OLDVALUE, @NEWVALUE, @FINISHDATE
    WHILE @@FETCH_STATUS = 0
    BEGIN
      DELETE FROM GDLTD
      WHERE GDGID = @GDGID
        AND FINISHDATE = @FINISHDATE

      IF NOT EXISTS (SELECT TOP 1 * FROM GDLTD WHERE GDGID = @GDGID ORDER BY FINISHDATE)
        UPDATE GOODS SET ISLTD = @OLDVALUE, LSTUPDTIME = GETDATE(), MODIFIER = 1
        WHERE GID = @GDGID
      ELSE
        UPDATE GOODS SET ISLTD = (SELECT TOP 1 NEWVALUE FROM GDLTD WHERE GDGID = @GDGID ORDER BY FINISHDATE), LSTUPDTIME = GETDATE(), MODIFIER = 1
        WHERE GID = @GDGID

      FETCH NEXT FROM C_FINISH INTO @GDGID, @NEWVALUE, @FINISHDATE
    END
    CLOSE C_FINISH
    DEALLOCATE C_FINISH

    --由经营属性调整生成
    DECLARE C_FINISH CURSOR FOR
      SELECT D.GDGID, D.OLDSALE, D.NEWSALE
        FROM LTDADJ M(NOLOCK), LTDADJDTL D(NOLOCK)
      WHERE M.NUM = D.NUM AND M.STAT = 800 AND M.EON = 1 AND M.KEEPATYPE > 0 AND D.FINISHDATE <= GETDATE()
    OPEN C_FINISH
    FETCH NEXT FROM C_FINISH INTO @GDGID, @OLDSALE, @NEWSALE
    WHILE @@FETCH_STATUS = 0
    BEGIN
      IF NOT EXISTS (SELECT TOP 1 * FROM LTDADJ M(NOLOCK), LTDADJDTL D(NOLOCK)
        WHERE M.NUM = D.NUM AND M.STAT = 800 AND M.EON = 1 AND M.KEEPATYPE > 0 AND D.GDGID = @GDGID ORDER BY D.FINISHDATE)
        UPDATE GOODS SET KEEPTYPE = @OLDSALE, LSTUPDTIME = GETDATE(), MODIFIER = 1
        WHERE GID = @GDGID
      ELSE
        UPDATE GOODS SET KEEPTYPE = (SELECT TOP 1 D.NEWSALE FROM LTDADJ M(NOLOCK), LTDADJDTL D(NOLOCK)
          WHERE M.NUM = D.NUM AND M.STAT = 800 AND M.EON = 1 AND M.KEEPATYPE > 0 AND D.GDGID = @GDGID ORDER BY D.FINISHDATE),
          LSTUPDTIME = GETDATE(), MODIFIER = 1
        WHERE GID = @GDGID

      SELECT @KEEPTYPE = KEEPTYPE, @LTD = ISLTD FROM GOODS(NOLOCK) WHERE GID = @GDGID

      --预淘汰
      IF (@OLDSALE & 16 <> 16) AND (@NEWSALE & 16 = 16)
      BEGIN
        EXEC OPTREADSTR 510, 'PREELIMINATEKEEYPTYPE', '3333333', @UPDATEKEEYPTYPE OUTPUT
        EXEC OPTREADSTR 510, 'PREELIMINATELTD', '333333', @UPDATELTD OUTPUT
      END

      --缺品
      IF (@OLDSALE & 32 <> 32) AND (@NEWSALE & 32 = 32)
      BEGIN
        EXEC OPTREADSTR 510, 'LACKKEEYPTYPE', '3333333', @UPDATEKEEYPTYPE OUTPUT
        EXEC OPTREADSTR 510, 'LACKLTD', '333333', @UPDATELTD OUTPUT
      END

      --买断
      IF (@OLDSALE & 64 <> 64) AND (@NEWSALE & 64 = 64)
      BEGIN
        EXEC OPTREADSTR 510, 'BUYALLKEEYPTYPE', '3333333', @UPDATEKEEYPTYPE OUTPUT
        EXEC OPTREADSTR 510, 'BUYALLLTD', '333333', @UPDATELTD OUTPUT
      END

      IF SUBSTRING(@UPDATEKEEYPTYPE, 1, 1) = '1'
        SET @KEEPTYPE = @KEEPTYPE | 1
      ELSE IF SUBSTRING(@UPDATEKEEYPTYPE, 1, 1) = '2'
        SET @KEEPTYPE = @KEEPTYPE & (~1)

      IF SUBSTRING(@UPDATEKEEYPTYPE, 2, 1) = '1'
        SET @KEEPTYPE = @KEEPTYPE | 2
      ELSE IF SUBSTRING(@UPDATEKEEYPTYPE, 2, 1) = '2'
        SET @KEEPTYPE = @KEEPTYPE & (~2)

      IF SUBSTRING(@UPDATEKEEYPTYPE, 3, 1) = '1'
        SET @KEEPTYPE = @KEEPTYPE | 4
      ELSE IF SUBSTRING(@UPDATEKEEYPTYPE, 3, 1) = '2'
        SET @KEEPTYPE = @KEEPTYPE & (~4)

      IF SUBSTRING(@UPDATEKEEYPTYPE, 4, 1) = '1'
        SET @KEEPTYPE = @KEEPTYPE | 8
      ELSE IF SUBSTRING(@UPDATEKEEYPTYPE, 4, 1) = '2'
        SET @KEEPTYPE = @KEEPTYPE & (~8)

      IF SUBSTRING(@UPDATEKEEYPTYPE, 5, 1) = '1'
        SET @KEEPTYPE = @KEEPTYPE | 16
      ELSE IF SUBSTRING(@UPDATEKEEYPTYPE, 5, 1) = '2'
        SET @KEEPTYPE = @KEEPTYPE & (~16)

      IF SUBSTRING(@UPDATEKEEYPTYPE, 6, 1) = '1'
        SET @KEEPTYPE = @KEEPTYPE | 32
      ELSE IF SUBSTRING(@UPDATEKEEYPTYPE, 6, 1) = '2'
        SET @KEEPTYPE = @KEEPTYPE & (~32)

      IF SUBSTRING(@UPDATEKEEYPTYPE, 7, 1) = '1'
        SET @KEEPTYPE = @KEEPTYPE | 64
      ELSE IF SUBSTRING(@UPDATEKEEYPTYPE, 7, 1) = '2'
        SET @KEEPTYPE = @KEEPTYPE & (~64)

      IF SUBSTRING(@UPDATELTD, 1, 1) = '1'
        SET @LTD = @LTD | 1
      ELSE IF SUBSTRING(@UPDATELTD, 1, 1) = '2'
        SET @LTD = @LTD & (~1)

      IF SUBSTRING(@UPDATELTD, 2, 1) = '1'
        SET @LTD = @LTD | 2
      ELSE IF SUBSTRING(@UPDATELTD, 2, 1) = '2'
        SET @LTD = @LTD & (~2)

      IF SUBSTRING(@UPDATELTD, 3, 1) = '1'
        SET @LTD = @LTD | 4
      ELSE IF SUBSTRING(@UPDATELTD, 3, 1) = '2'
        SET @LTD = @LTD & (~4)

      IF SUBSTRING(@UPDATELTD, 4, 1) = '1'
        SET @LTD = @LTD | 8
      ELSE IF SUBSTRING(@UPDATELTD, 4, 1) = '2'
        SET @LTD = @LTD & (~8)

      IF SUBSTRING(@UPDATELTD, 5, 1) = '1'
        SET @LTD = @LTD | 16
      ELSE IF SUBSTRING(@UPDATELTD, 5, 1) = '2'
        SET @LTD = @LTD & (~16)

      IF SUBSTRING(@UPDATELTD, 6, 1) = '1'
        SET @LTD = @LTD | 32
      ELSE IF SUBSTRING(@UPDATELTD, 6, 1) = '2'
        SET @LTD = @LTD & (~32)

      FETCH NEXT FROM C_FINISH INTO @GDGID, @OLDSALE, @NEWSALE
    END
    CLOSE C_FINISH
    DEALLOCATE C_FINISH
  END
END
GO
