SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[MKTPRC_GENFROMSCHEME]
(
  @SCHEMENUM CHAR(14),
  @OPER CHAR(30),
  @GENNUM CHAR(14) OUTPUT
)
AS
BEGIN
  DECLARE @SETTLENO INT, @STOREGID INT
  EXEC GENNEXTBILLNUMEX NULL, 'MKTPRC', @GENNUM OUTPUT
  SELECT @SETTLENO = MAX(NO) FROM MONTHSETTLE(NOLOCK)
  SELECT @STOREGID = USERGID FROM SYSTEM(NOLOCK)

  INSERT INTO MKTPRC(NUM, SETTLENO, STAT, STOREGID, SCHEMENUM, FILLER, FILDATE, LSTUPDTIME, RECCNT)
  VALUES(@GENNUM, @SETTLENO, 0, @STOREGID, @SCHEMENUM, @OPER, GETDATE(), GETDATE(), 0)

  INSERT INTO MKTPRCDTL(NUM, LINE, GDGID, GDQPCSTR, GDQPC)
  SELECT @GENNUM, LINE, GDGID, GDQPCSTR, GDQPC
  FROM MKTPRCSCHEMEGDDTL(NOLOCK)
  WHERE NUM = @SCHEMENUM
END
GO
