SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
create procedure [dbo].[NOAUTOORDERREASONRCV](
	@p_teamid	int
) as
begin
  delete NOAUTOORDERREASON from NNOAUTOORDERREASON
  where NNOAUTOORDERREASON.TEAMID = @p_teamid
    and NOAUTOORDERREASON.REASONCODE = NNOAUTOORDERREASON.REASONCODE
  insert into NOAUTOORDERREASON(REASONCODE, REASONNAME)
  select REASONCODE, REASONNAME
  from NNOAUTOORDERREASON
  where TEAMID = @p_teamid
  return 0
end
GO
