SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE PROCEDURE [dbo].[GENNEXTSETTLENO]
AS
BEGIN
	DECLARE @SETTLENO	INT
	SELECT @SETTLENO = MAX(NO) FROM MONTHSETTLE(NOLOCK)
	RETURN @SETTLENO
END
GO
