SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SALEDIFFDEL] (
  @NUM	CHAR(14),
  @OPER	INT = 1
) AS
BEGIN
  DECLARE @STAT INT, @FINISHED INT
  SELECT @STAT = STAT, @FINISHED = FINISHED FROM SALEDIF WHERE NUM = @NUM
  IF @@ROWCOUNT = 0
  BEGIN
    RAISERROR('单据%s不存在', 16, 1, @NUM);
    RETURN 1
  END
  IF @STAT <> 0
  BEGIN
  	RAISERROR('单据%s不是未审核单据，不能删除', 16, 1, @NUM)
  	RETURN 1
  END ELSE IF @FINISHED = 1
  BEGIN
    RAISERROR('单据%s已结束，不能删除', 16, 1, @NUM)
    RETURN 1
  END ELSE
  BEGIN
  	DELETE FROM SALEDIFDTL WHERE NUM = @NUM
  	DELETE FROM SALEDIF WHERE NUM = @NUM
  END
  
  RETURN 0
END
GO
