SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SENDONEPRMRTNPNTAGM]
(
  @NUM VARCHAR(14),
  @SRC INT,
  @RCV INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE
    @ID INT
  EXECUTE GETNETBILLID @ID OUTPUT

  INSERT INTO NPRMRTNPNTAGM(SRC, ID, NUM, SETTLENO, STAT, RECCNT, FILDATE, FILLER,
    VENDOR, BEGINTIME, ENDTIME, AUTOGEN, GENTIME, RTNSTAT, LSTUPDTIME, LSTUPDOPER,
    CHKTIME, CHECKER, SNDTIME, PRNTIME, NOTE, RCV, RCVTIME, TYPE, NSTAT, NNOTE)
  SELECT @SRC, @ID, NUM, SETTLENO, STAT, RECCNT, FILDATE, FILLER,
    VENDOR, BEGINTIME, ENDTIME, AUTOGEN, GENTIME, RTNSTAT, LSTUPDTIME, LSTUPDOPER,
    CHKTIME, CHECKER, GETDATE(), PRNTIME, NOTE, @RCV, NULL, 0, 0, ''
  FROM PRMRTNPNTAGM(NOLOCK)
  WHERE NUM = @NUM

  INSERT INTO NPRMRTNPNTAGMDTL(SRC, ID, NUM, LINE, DEPT, BRAND, NOTE)
  SELECT @SRC, @ID, NUM, LINE, DEPT, BRAND, NOTE
  FROM PRMRTNPNTAGMDTL(NOLOCK)
  WHERE NUM = @NUM

  INSERT INTO NPRMRTNPNTAGMEXGDDTL(SRC, ID, NUM, LINE, GDGID)
  SELECT @SRC, @ID, NUM, LINE, GDGID
  FROM PRMRTNPNTAGMEXGDDTL(NOLOCK)
  WHERE NUM = @NUM

  INSERT INTO NPRMRTNPNTAGMRATEDTL(SRC, ID, NUM, LINE, LOWAMT, HIGHAMT, RATE)
  SELECT @SRC, @ID, NUM, LINE, LOWAMT, HIGHAMT, RATE
  FROM PRMRTNPNTAGMRATEDTL(NOLOCK)
  WHERE NUM = @NUM

  RETURN 0
END
GO
