SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[POLYLTDADJ_OCR]
(
  @NUM CHAR(14),
  @OPER VARCHAR(30),
  @MSG VARCHAR(255) OUTPUT
) AS
BEGIN
  DECLARE
    @ATYPE INT,
    @DEPT CHAR(10),
    @VENDOR INT,
    @BRAND VARCHAR(10),
    @LTDVALUE INT,
    @RETURN_STATUS INT

  UPDATE POLYLTDADJ SET STAT = 800 WHERE NUM = @NUM
  SELECT @ATYPE = ATYPE FROM POLYLTDADJ(NOLOCK) WHERE NUM = @NUM
  IF @ATYPE <= 0 RETURN 0

  SET @RETURN_STATUS = 0
  DECLARE C_LTDADJ CURSOR FOR
    SELECT DEPT, VENDOR, BRAND, LTDVALUE FROM POLYLTDADJDTL(NOLOCK)
      WHERE NUM = @NUM
      ORDER BY DEPT, VENDOR, BRAND ASC
  /*NULL是最小的。这样排列的目的是为了将范围大的先生效，避免范围重叠时小范围的值被大范围的值覆盖*/
  OPEN C_LTDADJ
  FETCH NEXT FROM C_LTDADJ INTO @DEPT, @VENDOR, @BRAND, @LTDVALUE
  WHILE @@FETCH_STATUS = 0
  BEGIN
    EXEC @RETURN_STATUS = POLYLTDADJ_OCR_UPDGOODS @ATYPE, @DEPT, @VENDOR, @BRAND, @LTDVALUE, @OPER, @MSG OUTPUT
    IF @RETURN_STATUS <> 0 BREAK
    FETCH NEXT FROM C_LTDADJ INTO @DEPT, @VENDOR, @BRAND, @LTDVALUE
  END
  CLOSE C_LTDADJ
  DEALLOCATE C_LTDADJ
  IF @RETURN_STATUS <> 0 RETURN @RETURN_STATUS
  RETURN(0)
END
GO
