SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CHECKLASTSELLVOUCHER]
(
    @CURVOUCHERNUM  VARCHAR(32),          --当前购物券代码
    @LSTVOUCHERNUM  VARCHAR(32)   OUTPUT, --最后发售购物券代码
    @OPER           VARCHAR(100),         --操作人
    @MSG            VARCHAR(255)  OUTPUT  --错误信息
  )
AS
BEGIN
  DECLARE  @VRET  INT
  DECLARE  @NXTVOUCHERNUM  VARCHAR(32)

  SET @VRET = 0;
  SET @LSTVOUCHERNUM = NULL;
  SELECT TOP 1 @LSTVOUCHERNUM = NUM FROM VOUCHERLOG (NOLOCK) WHERE FROMSTATE = 1 AND TOSTATE = 4 AND CREATOR = @OPER ORDER BY Num DESC;
  IF @LSTVOUCHERNUM IS NULL    --没发售记录
  BEGIN
    RETURN(@VRET);
  END ELSE                      --检查当前发售购物券代码
  BEGIN
    SET @NXTVOUCHERNUM = NULL;
    EXEC VoucherGetNextExistNum @LSTVOUCHERNUM, @NXTVOUCHERNUM OUTPUT;
    IF @NXTVOUCHERNUM IS NULL 
    BEGIN
      SET @VRET = 1;
    END ELSE 
    BEGIN
      IF @CURVOUCHERNUM = @NXTVOUCHERNUM 
      BEGIN
        SET @VRET = 0;
      END ELSE
      BEGIN
        SET @VRET = 1;
      END;
    END;
  END; 
  RETURN(@VRET);   
END
GO
