SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[GoodsAppSnd]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS	 CHAR(10),
  @TOSTAT INT,
  @FRCCHK INT,
  @TOSTORE INT, --IF = -1 THEN TO ALL LAC STORE
  @MSG VARCHAR(255) OUTPUT
) with encryption
AS
BEGIN
  	DECLARE
   		@SRC INT,		@RATIFIER INT,
   		@STAT SMALLINT,	@ID INT,
		@LOCALGID INT,	@RCVSTORE INT,
		@VRET INT,		@APPMODE VARCHAR(20)
    DECLARE @EXP DATETIME
    DECLARE
    	@SendInputCode INT, @SendVendor INT,
    	@STOREGID INT,     	@GDGID INT,
    	@GDCODE VARCHAR(13),	@USERGID INT
    SET @FRCCHK = 0  --NO USE NOW
    SET @VRET = -1
   	SELECT @STAT = STAT, @SRC = SRC, @RATIFIER = RATIFIER, @EXP = DEADDATE, @APPMODE = APPMODE
   		FROM GOODSAPP WHERE  NUM = @NUM
	EXEC OPTREADINT 10 ,'SendInputCode',0, @SendInputCode OUTPUT  -- GOODSSND
	EXEC OPTREADINT 10 ,'SendVendor',0, @SendVendor OUTPUT
	SELECT @USERGID = USERGID FROM SYSTEM

	SELECT @LOCALGID = USERGID FROM SYSTEM
   	if @stat <> 401 and @stat <> 400  and @stat <> 411
	begin
      SET @MSG = '发送的单据不是请求总部批准、总部批准或申请作废'
      return(1)
   	end
	if '大总部生成' = (select BOCLS from GOODSAPP(nolock) where num = @num)
	begin
      SET @MSG = '发送的单据是大总部的单据，不能发送'
      return(1)
	end
	IF (@EXP IS NOT NULL) AND (@EXP <= CONVERT(DATETIME, CONVERT(CHAR(10),GETDATE(),102)) )
	BEGIN
	  SET @MSG = '单据' + @NUM + '已经超过到效日期'
	  RETURN 1
	END

	IF @STAT = 401
	BEGIN
      IF @SRC <> @LOCALGID
 	  BEGIN
         	SET @MSG = '发送的单据不是本单位生成的'
         	RETURN(1)
	  END
          IF @RATIFIER = @LOCALGID
 	  BEGIN
         	SET @MSG = '本单位批准的单据无需发送'
         	RETURN(1)
	  END
	  EXECUTE GETNETBILLID @ID OUTPUT
		INSERT INTO NGoodsApp (ID,  RCV, RCVTIME, TYPE, NSTAT, NNOTE, FRCCHK,
				       SRC, NUM, STAT, RATIFIER, PSR, FILDATE, FILLER,
				       CHECKER, CHKDATE, RATOPER, RATDATE, DEADDATE,
				       LSTUPDTIME, PRNTIME, SNDTIME, SETTLENO, NOTE, GOODSCLS, APPMODE, RECCNT
				       )
          	SELECT  @ID, @RATIFIER, NULL, 0, 0, NULL, @FRCCHK,
          		@SRC,  NUM, STAT, RATIFIER, PSR, FILDATE, FILLER,
			CHECKER, CHKDATE, RATOPER, RATDATE, DEADDATE,
			LSTUPDTIME, PRNTIME, GETDATE(), SETTLENO, NOTE, GOODSCLS, APPMODE, RECCNT
          	from GoodsApp
		where NUM = @NUM

   		INSERT INTO NGOODSAPPDTL
   		(SRC, ID,  NUM, LINE, FLAG, RATFLAG, NOTE, GID, CODE, NAME, SPEC, SORT, RTLPRC, INPRC, TAXRATE, PROMOTE, PRCTYPE, SALE, LSTINPRC, LWTRTLPRC, WHSPRC, WRH, ACNT, PAYTODTL, PAYRATE, MUNIT, GFT, QPC, TM, MANUFACTOR, MCODE, GPR, VALIDPERIOD, MEMO, CHKVD, DXPRC, BILLTO, AUTOORD, ORIGIN, GRADE, MBRPRC, SALETAX, PSR, F1, F2, F3, ALC, CODE2, MKTINPRC, MKTRTLPRC, CNTINPRC, ALCQTY, BRAND, BQTYPRC, KEEPTYPE, NENDTIME, NCANPAY, SSSTART, SSEND, SEASON, HQCONTROL, ORDCYCLE, ALCCTR, ISDISP)
          	SELECT
          	@SRC, @ID, NUM, LINE, FLAG, RATFLAG, NOTE, GID, CODE, NAME, SPEC, SORT, RTLPRC, INPRC, TAXRATE, PROMOTE, PRCTYPE, SALE, LSTINPRC, LWTRTLPRC, WHSPRC, WRH, ACNT, PAYTODTL, PAYRATE, MUNIT, GFT, QPC, TM, MANUFACTOR, MCODE, GPR, VALIDPERIOD, MEMO, CHKVD, DXPRC, BILLTO, AUTOORD, ORIGIN, GRADE, MBRPRC, SALETAX, PSR, F1, F2, F3, ALC, CODE2, MKTINPRC, MKTRTLPRC, CNTINPRC, ALCQTY, BRAND, BQTYPRC, KEEPTYPE, NENDTIME, NCANPAY, SSSTART, SSEND, SEASON, HQCONTROL, ORDCYCLE, ALCCTR, ISDISP
          	FROM GOODSAPPDTL
		WHERE NUM = @NUM

		INSERT INTO NGoodsAppField(SRC, ID, NUM, LINE, FIELDNAME)
		SELECT @SRC, @ID, NUM, LINE, FIELDNAME FROM GoodsAppField WHERE NUM = @NUM

		INSERT INTO NGoodsAppLac(SRC, ID, NUM, STOREGID)
   		SELECT @SRC, @ID, NUM, STOREGID FROM GoodsAppLac WHERE NUM = @NUM
		IF @@ERROR <> 0
		BEGIN
			SET @MSG = '发送'+@NUM+'单据失败'
			RETURN(1)
		END
   		UPDATE GOODSAPP
		SET SNDTIME = GETDATE()
		WHERE NUM = @NUM
	END
	ELSE
	BEGIN
      IF @RATIFIER <> @LOCALGID
 	  BEGIN
         	SET @MSG = '发送的单据不是本单位批准的'
         	RETURN(1)
	  END
	  IF @TOSTORE >= 0
	  BEGIN
	  	EXECUTE GETNETBILLID @ID OUTPUT
		INSERT INTO NGoodsApp (ID,  RCV, RCVTIME, TYPE, NSTAT, NNOTE, FRCCHK,
				       SRC, NUM, STAT, RATIFIER, PSR, FILDATE, FILLER,
				       CHECKER, CHKDATE, RATOPER, RATDATE, DEADDATE,
				       LSTUPDTIME, PRNTIME, SNDTIME, SETTLENO, NOTE, GOODSCLS, APPMODE, RECCNT
				       )
          	select  @ID, @TOSTORE, NULL, 0, 0, NULL, @FRCCHK,
          		@SRC,  NUM, STAT, RATIFIER, PSR, FILDATE, FILLER,
			CHECKER, CHKDATE, RATOPER, RATDATE, DEADDATE,
			LSTUPDTIME, PRNTIME, GETDATE(), SETTLENO, NOTE, GOODSCLS, APPMODE, RECCNT
          	from GoodsApp
		WHERE NUM = @NUM

   		if @@error <> 0
		BEGIN
			SET @MSG = '发送'+@NUM+'单据失败'
			return(1)
		END

   		INSERT INTO NGOODSAPPDTL
   		(SRC, ID,  NUM, LINE, FLAG, RATFLAG, NOTE, GID, CODE, NAME, SPEC, SORT, RTLPRC, INPRC, TAXRATE, PROMOTE, PRCTYPE, SALE, LSTINPRC, LWTRTLPRC, WHSPRC, WRH, ACNT, PAYTODTL, PAYRATE, MUNIT, GFT, QPC, TM, MANUFACTOR, MCODE, GPR, VALIDPERIOD, MEMO, CHKVD, DXPRC, BILLTO, AUTOORD, ORIGIN, GRADE, MBRPRC, SALETAX, PSR, F1, F2, F3, ALC, CODE2, MKTINPRC, MKTRTLPRC, CNTINPRC, ALCQTY, BRAND, BQTYPRC, KEEPTYPE, NENDTIME, NCANPAY, SSSTART, SSEND, SEASON, HQCONTROL, ORDCYCLE, ALCCTR, ISDISP)
          	SELECT
          	@SRC, @ID, NUM, LINE, FLAG, RATFLAG, NOTE, GID, CODE, NAME, SPEC, SORT, RTLPRC, INPRC, TAXRATE, PROMOTE, PRCTYPE, SALE, LSTINPRC, LWTRTLPRC, WHSPRC, WRH, ACNT, PAYTODTL, PAYRATE, MUNIT, GFT, QPC, TM, MANUFACTOR, MCODE, GPR, VALIDPERIOD, MEMO, CHKVD, DXPRC, BILLTO, AUTOORD, ORIGIN, GRADE, MBRPRC, SALETAX, PSR, F1, F2, F3, ALC, CODE2, MKTINPRC, MKTRTLPRC, CNTINPRC, ALCQTY, BRAND, BQTYPRC, KEEPTYPE, NENDTIME, NCANPAY, SSSTART, SSEND, SEASON, HQCONTROL, ORDCYCLE, ALCCTR, ISDISP
          	FROM GOODSAPPDTL
		WHERE NUM = @NUM

   		IF @@ERROR <> 0
		BEGIN
			SET @MSG = '发送'+@NUM+'单据失败'
			RETURN(1)
		END
		INSERT INTO NGoodsAppField(SRC, ID, NUM, LINE, FIELDNAME)
		SELECT @SRC, @ID, NUM, LINE, FIELDNAME FROM GoodsAppField WHERE NUM = @NUM

		INSERT INTO NGoodsAppLac(SRC, ID, NUM, STOREGID)
   		SELECT @SRC, @ID, NUM, STOREGID FROM GoodsAppLac WHERE NUM = @NUM
		IF @@ERROR <> 0
		BEGIN
			SET @MSG = '发送'+@NUM+'单据失败'
			return(1)
		END
		--GOODSSND
		IF (@APPMODE <> '删除') AND (@STAT = 400)
		BEGIN
			IF OBJECT_ID('C_GOODS') IS NOT NULL DEALLOCATE C_GOODS
			DECLARE C_GOODS CURSOR FOR
				SELECT @TOSTORE, CODE FROM GOODSAPPDTL DTL
				WHERE DTL.RATFLAG = 1 AND DTL.NUM = @NUM AND @TOSTORE <> @USERGID
			OPEN C_GOODS
			FETCH NEXT FROM C_GOODS INTO @STOREGID, @GDCODE
			WHILE @@FETCH_STATUS = 0
			BEGIN
				SELECT @GDGID = GID FROM GOODS WHERE CODE = @GDCODE
				EXEC @VRET = GOODSSND @GDGID, @STOREGID, 1, @SendInputCode, @SendVendor
				IF @VRET <> 0
				BEGIN
		            SET @MSG = @MSG + '发送商品错误。'
			        CLOSE C_GOODS
		        	DEALLOCATE C_GOODS
					RAISERROR('发送商品时发生错误。',16,1)
					RETURN(1)
				END
				FETCH NEXT FROM C_GOODS INTO @STOREGID, @GDCODE
			END
			CLOSE C_GOODS
			DEALLOCATE C_GOODS
		END
	  END --IF @TOSTORE > 0

	  ELSE IF @TOSTORE < 0 -- 发送所有生效门店
	  BEGIN
	   	DECLARE C_C CURSOR FOR
	   		SELECT STOREGID FROM GOODSAPPLAC WHERE NUM = @NUM AND STOREGID <> @LOCALGID
	   	OPEN C_C
	   	FETCH NEXT FROM C_C INTO @RCVSTORE
	   	WHILE @@FETCH_STATUS=0
	   	BEGIN
		   	EXECUTE GETNETBILLID @ID OUTPUT
			INSERT INTO NGoodsApp (ID,  RCV, RCVTIME, TYPE, NSTAT, NNOTE, FRCCHK,
					       SRC, NUM, STAT, RATIFIER, PSR, FILDATE, FILLER,
					       CHECKER, CHKDATE, RATOPER, RATDATE, DEADDATE,
					       LSTUPDTIME, PRNTIME, SNDTIME, SETTLENO, NOTE, GOODSCLS, APPMODE, RECCNT
					       )
	          	select  @ID, @RCVSTORE, NULL, 0, 0, NULL, @FRCCHK,
	          		@SRC,  NUM, STAT, RATIFIER, PSR, FILDATE, FILLER,
				CHECKER, CHKDATE, RATOPER, RATDATE, DEADDATE,
				LSTUPDTIME, PRNTIME, GETDATE(), SETTLENO, NOTE, GOODSCLS, APPMODE, RECCNT
	          	from GoodsApp
			where NUM = @NUM

	   		insert into NGoodsAppDTL
	   		(SRC, ID,  NUM, LINE, FLAG, RATFLAG, NOTE, GID, CODE, NAME, SPEC, SORT, RTLPRC, INPRC, TAXRATE, PROMOTE, PRCTYPE, SALE, LSTINPRC, LWTRTLPRC, WHSPRC, WRH, ACNT, PAYTODTL, PAYRATE, MUNIT, GFT, QPC, TM, MANUFACTOR, MCODE, GPR, VALIDPERIOD, MEMO, CHKVD, DXPRC, BILLTO, AUTOORD, ORIGIN, GRADE, MBRPRC, SALETAX, PSR, F1, F2, F3, ALC, CODE2, MKTINPRC, MKTRTLPRC, CNTINPRC, ALCQTY, BRAND, BQTYPRC, KEEPTYPE, NEndTime, NCanPay, SSStart, SSEnd, Season, HQControl, ORDCYCLE, ALCCTR, ISDISP)
	          	select
	          	@SRC, @ID, NUM, LINE, FLAG, RATFLAG, NOTE, GID, CODE, NAME, SPEC, SORT, RTLPRC, INPRC, TAXRATE, PROMOTE, PRCTYPE, SALE, LSTINPRC, LWTRTLPRC, WHSPRC, WRH, ACNT, PAYTODTL, PAYRATE, MUNIT, GFT, QPC, TM, MANUFACTOR, MCODE, GPR, VALIDPERIOD, MEMO, CHKVD, DXPRC, BILLTO, AUTOORD, ORIGIN, GRADE, MBRPRC, SALETAX, PSR, F1, F2, F3, ALC, CODE2, MKTINPRC, MKTRTLPRC, CNTINPRC, ALCQTY, BRAND, BQTYPRC, KEEPTYPE, NEndTime, NCanPay, SSStart, SSEnd, Season, HQControl, ORDCYCLE, ALCCTR, ISDISP
	          	from GoodsAppDTL
			where NUM = @Num

			INSERT INTO NGoodsAppField(SRC, ID, NUM, LINE, FIELDNAME)
			SELECT @SRC, @ID, NUM, LINE, FIELDNAME
			FROM GoodsAppField WHERE NUM = @NUM

			INSERT INTO NGoodsAppLac(SRC, ID, NUM, STOREGID)
	   		SELECT @SRC, @ID, NUM, STOREGID FROM GoodsAppLac WHERE NUM = @NUM
			IF @@ERROR <> 0
			BEGIN
				SET @MSG = '发送'+@NUM+'单据失败'
				return(1)
			END
			FETCH NEXT FROM C_C INTO @RCVSTORE
		END
        CLOSE C_C
        DEALLOCATE C_C
		IF (@APPMODE <> '删除') AND (@STAT = 400)
		BEGIN
			--SEND
			IF OBJECT_ID('C_GOODS') IS NOT NULL DEALLOCATE C_GOODS
			DECLARE C_GOODS CURSOR FOR
				SELECT STOREGID, CODE FROM GOODSAPPDTL DTL, GOODSAPPLAC LAC
				WHERE DTL.RATFLAG = 1 AND DTL.NUM = LAC.NUM AND DTL.NUM = @NUM AND STOREGID <> @USERGID
			OPEN C_GOODS
			FETCH NEXT FROM C_GOODS INTO @STOREGID, @GDCODE
			WHILE @@FETCH_STATUS = 0
			BEGIN
				SELECT @GDGID = GID FROM GOODS WHERE CODE = @GDCODE
				EXEC @VRET = GOODSSND @GDGID, @STOREGID, 1, @SendInputCode, @SendVendor
				IF @VRET <> 0
				BEGIN
		            SET @MSG = @MSG + '发送商品错误。'
			        CLOSE C_GOODS
		        	DEALLOCATE C_GOODS
					RAISERROR('发送商品时发生错误。',16,1)
					RETURN(1)
				END
				FETCH NEXT FROM C_GOODS INTO @STOREGID, @GDCODE
			END
			CLOSE C_GOODS
			DEALLOCATE C_GOODS
		END --IF @APPMODE <> '删除'
	  END
	  UPDATE GOODSAPP
	  SET SNDTIME = GETDATE()
	  WHERE NUM = @NUM
	END
	EXEC GOODSAPPADDLOG @NUM,@STAT,'发送',@OPER
	insert into LOG(TIME, EMPLOYEECODE, WORKSTATIONNO, MODULENAME,
    TYPE, CONTENT)
    values (getdate(), substring(@OPER, CHARINDEX('[', @OPER)+1, CHARINDEX(']',@OPER) - CHARINDEX('[',@OPER)-1), '',
    'GOODSAPP', 304, '发送商品资料申请单:['+@NUM+']' )
END
GO
