SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CNTRGETPAYDATE]
(
	@PIVDRGID	INT,
	@PIOCRDATE	DATETIME,
	@PIFILDATE	DATETIME,
	@POPAYDATE		DATETIME OUTPUT
)
AS
BEGIN
	DECLARE
	@VPAYTERMS	INT
	,@VPAYCLS	SMALLINT
--	,@VCALCBASE	VARCHAR(20) 
	,@VPAYDATE	DATETIME
	,@VOCRDATE	DATETIME 
	,@VADDMONTH	INT 
	,@VADDDAY		INT 

	IF @PIOCRDATE IS NULL  
		SELECT @VOCRDATE = CONVERT(DATETIME,CONVERT(CHAR(10),@PIFILDATE,102))  
	ELSE
		SELECT @VOCRDATE = @PIOCRDATE  

	
    	SELECT @VPAYTERMS = PAYTERM, @VPAYCLS = PAYCLS  
    	  FROM VENDOR 
         WHERE GID = @PIVDRGID 

	IF @@ROWCOUNT = 0
	BEGIN
		SELECT @VPAYTERMS = 0 
		SELECT @VPAYCLS = 2 
	END 

	IF @VPAYCLS = 0 
	BEGIN
		SELECT @VPAYDATE = CONVERT(DATETIME,CONVERT(CHAR(10),DATEADD(MM,1,BEGINDATE),102)) - 1
		  FROM MONTHSETTLE WHERE NO = (SELECT MAX(NO) FROM MONTHSETTLE)--?????
		  
		SELECT @VPAYDATE = @VPAYDATE + @VPAYTERMS 
	END
	ELSE 
	BEGIN
		IF @VPAYCLS = 2 
		BEGIN
			SELECT @VPAYDATE = @PIFILDATE + @VPAYTERMS 
		END


		IF @VPAYCLS= '1' 
		BEGIN
			--分段 
/*			IF TRUNC(SYSDATE) <= TRUNC(SYSDATE, 'MONTH') + 15 THEN
				SELECT TRUNC(SYSDATE, 'MONTH') + 15 INTO VPAYDATE FROM DUAL 
			ELSE
				SELECT TRUNC(ADD_MONTHS(SYSDATE, 1), 'MONTH') INTO VPAYDATE FROM DUAL 
			END IF 
*/
			IF DAY(GETDATE()) <= 16 
			BEGIN
				SELECT @VPAYDATE = GETDATE() + 15 - DAY(GETDATE())
			END
			ELSE
			BEGIN
				SELECT @VPAYDATE = DATEADD(MM,1,GETDATE()) + 1 - DAY(GETDATE())
			END

			SELECT @VPAYDATE = @VPAYDATE + @VPAYTERMS - 1 
		END
	    
	END
	IF @VPAYDATE IS NULL SELECT  @VPAYDATE = GETDATE()
	
	SELECT @POPAYDATE = @VPAYDATE

  	RETURN 0 
END 
GO
