SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[NETLTDADJDEL] (
  @SRC	INT,
  @ID	INT,
  @OPER	INT
) AS
BEGIN
  DELETE FROM NLTDADJDTL WHERE SRC = @SRC AND ID = @ID
  DELETE FROM NLTDADJ WHERE SRC = @SRC AND ID = @ID
  DELETE FROM NLTDADJLACDTL WHERE SRC = @SRC AND ID = @ID
  RETURN 0
END
GO
