SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[RTLSND]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @RCV INT,
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE
    @SRC INT,	@STAT SMALLINT,
    @ID INT,	@USERGID INT,
    @FROMSRC INT

    SELECT @USERGID = USERGID FROM SYSTEM
    SELECT @STAT = STAT, @SRC = isnull(SRC ,@USERGID)
    FROM RTL WHERE  NUM = @NUM

  IF @STAT = 0
	BEGIN
         	SET @MSG = '未审核单据不能发送！'
         	RETURN(1)
  END

  IF @SRC <> @USERGID
    BEGIN
      SET @MSG = '非本单位生成的单据不能发送！'
      return(1)
    END
  SET @FROMSRC = @SRC

  EXECUTE GETNETBILLID @ID OUTPUT

  INSERT INTO NRTL (ID, SRC, RCV, PRNTIME, NUM, SETTLENO, FILDATE,
                    STAT, TOTAL, TAX, CHANGE, FILLER, UNDERTAKER, WARRANTOR, WRH, DSPUNIT,
                    DSPWRH, PROVIDER, MODNUM, INVNO, NOTE, RECCNT, SENDER, CHECKER, ASSISTANT, PAYSTAT,
                    SNDDATE, RCVTIME, NTYPE, NSTAT, NNOTE, SRCNUM)
  SELECT @ID, @SRC, @RCV, PRNTIME, NUM, SETTLENO, FILDATE,
                    STAT, TOTAL, TAX, CHANGE, FILLER, UNDERTAKER, WARRANTOR, WRH, DSPUNIT,
                    DSPWRH, PROVIDER, MODNUM, INVNO, NOTE, RECCNT, SENDER, CHECKER, ASSISTANT, PAYSTAT,
                    GETDATE(), NULL, 0, 0, NULL, SRCNUM
  FROM RTL
  WHERE NUM = @NUM
  IF @@ERROR <> 0
  BEGIN
    SET @MSG = '发送'+@NUM+'单据失败'
    RETURN(1)
  END
  --开始发送明细
  INSERT INTO NRTLDTL (SRC, ID, NUM, LINE, SETTLENO, GDGID, CASES, QTY, PRICE, DISCOUNT, INPRICE, ALCPRC, AMOUNT,
	               RTLPRC, INPRC, SUBWRH, DSPSUBWRH, TAX, LXGDNAME, LXGDSPEC, LXGDMUNIT, LXGDTM, INVAMT, COST, RedCardCost, BlueCardCost, VouAmt)
  SELECT @SRC, @ID, NUM, LINE, SETTLENO, GDGID, CASES, QTY, PRICE, DISCOUNT, INPRICE, ALCPRC, AMOUNT,
      	               RTLPRC, INPRC, SUBWRH, DSPSUBWRH, TAX, LXGDNAME, LXGDSPEC, LXGDMUNIT, LXGDTM, INVAMT, COST, RedCardCost, BlueCardCost, VouAmt
  FROM RTLDTL
  WHERE NUM = @NUM
  IF @@ERROR <> 0
  BEGIN
    SET @MSG = '发送'+@NUM+'单据失败'
    RETURN(1)
  END
  --开始发送付款明细
  INSERT INTO NRTLCURDTL (ID, NUM, ITEMNO, CURRENCY, AMOUNT, CARDNUM)
  SELECT @ID, NUM, ITEMNO, CURRENCY, AMOUNT, CARDNUM
  FROM RTLCURDTL
  WHERE NUM = @NUM
  IF @@ERROR <> 0
  BEGIN
    SET @MSG = '发送'+@NUM+'单据失败'
    RETURN(1)
  END
END
GO
