SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ALCADJ_CHECK_OCR]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE
    @STOREGID INT,
    @RET INT

  DECLARE C_ALCADJ CURSOR FOR
  SELECT STOREGID FROM ALCADJLACDTL(NOLOCK) WHERE NUM = @NUM
  OPEN C_ALCADJ
  FETCH NEXT FROM C_ALCADJ INTO @STOREGID
  WHILE @@FETCH_STATUS = 0
  BEGIN
    IF (SELECT USERGID FROM SYSTEM(NOLOCK)) = @STOREGID
    BEGIN
      UPDATE GOODS SET GOODS.ALC = D.NEWVALUE
      FROM ALCADJDTL D(NOLOCK)
      WHERE D.NUM = @NUM AND D.GDGID = GOODS.GID
    END ELSE BEGIN
      UPDATE GDSTORE SET GDSTORE.ALC = D.NEWVALUE
      FROM ALCADJDTL D(NOLOCK)
      WHERE D.NUM = @NUM AND D.GDGID = GDSTORE.GDGID AND GDSTORE.STOREGID = @STOREGID
    END

    FETCH NEXT FROM C_ALCADJ INTO @STOREGID
  END
  CLOSE C_ALCADJ
  DEALLOCATE C_ALCADJ

  EXEC @RET = ALCADJ_ADDLOG @NUM, '配货方式', @TOSTAT, '生效', @OPER
  IF @RET <> 0 RETURN @RET

  SET @MSG = '单据：' + @NUM + '生效成功'

  RETURN 0
END
GO
