SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO

CREATE Procedure [dbo].[TA_CKLOSS]
	@WHERE_CLAUSE VARCHAR(255)
As
declare @BeginDate char(10)
        ,@EndDate char(10)

declare @I int

select @I=charIndex(',',@WhERE_CLAUSE)


Select @BeginDate=SubString(@WHERE_CLAUSE,1,@I-1)
Select @EndDate=SubString(@WHERE_CLAUSE,@I+1,100)

EXEC ('DECLARE CUR_GETVOUCHER CURSOR GLOBAL FOR 
	SELECT STORE.CODE A,
        STORE.NAME B,
        ''部门'' C,
	CONVERT(VARCHAR(100),SUM(INVCHGDRPT.DI2)) D, 
	V_GDSORTA.SORT	E,
	V_GDSORTA.NAME	F, 
	''商品大类'' G,
        CONVERT(VARCHAR(2),SUM(0)) H,
	''RMB'' I,
	''1'' J,
	CONVERT(VARCHAR(2),SUM(0)) K,
	CONVERT(VARCHAR(2),SUM(0)) L,
	CONVERT(VARCHAR(2),SUM(0)) M,
	CONVERT(VARCHAR(2),SUM(0)) N,
	CONVERT(VARCHAR(2),SUM(0)) O
      FROM INVCHGDRPT INVCHGDRPT(NOLOCK), GOODSH GOODSH(NOLOCK), V_GDSORTA V_GDSORTA(NOLOCK), 
           STORE STORE(NOLOCK)
      WHERE INVCHGDRPT.ASTORE = STORE.GID
      and INVCHGDRPT.BGDGID = V_GDSORTA.GID
      and INVCHGDRPT.BGDGID = GOODSH.GID
      and INVCHGDRPT.DI2 < 0 
--      and GOODSH.SALE =2
      AND CONVERT(VARCHAR(10),INVCHGDRPT.ADATE,102) BETWEEN '''+@BEGINDATE+''' AND '''+ @ENDDATE+''' ' +  
	 'GROUP BY STORE.NAME, STORE.CODE, V_GDSORTA.SORT, V_GDSORTA.NAME')


RETURN 0





GO
