SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PGFBOOKUPD]
(
  @NUM  CHAR(14),
  @OPER CHAR(30),
  @CLS  CHAR(10),  /* IS NULL 表示发送；IS NOT NULL 表示不发送 */
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE @VVDRGID INT
  DECLARE @VSTAT INT
  DECLARE @VOLDREALAMT MONEY
  DECLARE @VMODNUM CHAR(14)
  DECLARE @VRET INT
  DECLARE @VGATHERINGMODE CHAR(10)
  DECLARE @VLEFTAMT MONEY
  DECLARE @SNDTIME DATETIME
     
  SELECT 
    @VVDRGID = BILLTO, 
    @VMODNUM = MODNUM,
    @VGATHERINGMODE = GATHERINGMODE,
    @VLEFTAMT = REALAMT - PAYTOTAL,
    @SNDTIME = SNDTIME    
  FROM PGFBOOK WHERE NUM = @NUM
  SELECT @VSTAT = STAT 
  FROM PGFBOOK WHERE NUM = @VMODNUM
  IF @VSTAT <> 500
  BEGIN
    SET @MSG = '非已审核状态的单据不许修正'
    RETURN 1
  END
  IF @VLEFTAMT < 0
  BEGIN
    SET @MSG = '实交金额不能小于已交金额'
    RETURN 1
  END
  IF @SNDTIME IS NOT NULL 
  BEGIN
      SET @MSG = '单据已经发送，不能修正.'
      RETURN 1
  END
  
  
  SELECT @VOLDREALAMT = REALAMT
  FROM PGFBOOK WHERE NUM = @VMODNUM

  --修改所有引用当前抵扣货款单的付款单的记录
  UPDATE CNTRPAYCASHDTL SET IVCCODE = @NUM
  WHERE IVCCODE = @VMODNUM AND CHGTYPE = '抵扣货款单'
  --修改所有引用当前抵扣货款单的交款单的记录
  UPDATE VDRPAYDTL SET CHGNUM = @NUM
  WHERE CHGNUM = @VMODNUM

  --修改被修正单据状态     
  UPDATE PGFBOOK SET STAT = 530, LSTUPDTIME = GETDATE()
  WHERE NUM = @VMODNUM
  --Fanduoyi 1298
  INSERT INTO PGFBOOKLOG(num, stat, modifier, time)
    VALUES(@VMODNUM, 530, @oper, getdate())
  
  EXEC @VRET = CHKPGFBOOKTO500 @NUM, @OPER, 'NOSEND', @MSG OUTPUT
  IF @VRET <> 0 RETURN @VRET
  --Fanduoyi 1298
  INSERT INTO PGFBOOKLOG(num, stat, modifier, time)
    VALUES(@num, 500, @oper, getdate())
  
  /*  
  IF @CLS IS NULL OR @CLS = ''
  BEGIN
      EXEC @VRET = CHKCHGBOOK_SEND @NUM, @OPER, @MSG OUTPUT
    IF @VRET <= 0 SET @VRET = 0
  END
  RETURN @VRET*/
END
GO
