SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[GENFLOWCODEEX]
(
  @CURCODE VARCHAR(20) OUTPUT,
  @TABLENAME VARCHAR(20)
)
AS
BEGIN
  DECLARE
    @CODELEN INT,
    @CODESTYLE VARCHAR(20),
    @MCODE VARCHAR(20),
    @S NVARCHAR(255),
    @SUBFLOWCODE VARCHAR(20),
    @ERRMSG VARCHAR(255),
    @INTUPPER INT


    EXEC OPTREADINT 10, 'FLOWCODELENGTH', 0, @CODELEN OUTPUT
    EXEC OPTREADSTR 10, 'CHKCODESTYLE', 'EAN-8', @CODESTYLE OUTPUT

    IF @CODELEN = 0
      SET @S = 'SELECT @MCODE = MAX(CODE) FROM ' + @TABLENAME + ' WHERE CODE LIKE ''' + @CURCODE + '%'''
    ELSE BEGIN
      IF @CODESTYLE <> '（空）'
      BEGIN
        IF @CODELEN <= 8 SET @INTUPPER = 8
        ELSE SET @INTUPPER = 13
        SET @S = 'SELECT @MCODE = MAX(SUBSTRING(CODE, 1, ' + STR(@CODELEN) + ')) '
               + ' FROM ' + @TABLENAME
               + ' WHERE CODE LIKE ''' + @CURCODE + '%'''
               + ' AND DATALENGTH(LTRIM(RTRIM(CODE))) BETWEEN ' + STR(@CODELEN)
               + ' AND ' + STR(@INTUPPER)
      END ELSE
        SET @S = 'SELECT @MCODE = MAX(CODE) FROM ' + @TABLENAME + ' WHERE CODE LIKE ''' + @CURCODE + '%'''
          + ' AND DATALENGTH(LTRIM(RTRIM(CODE))) = ' + STR(@CODELEN)
    END

    EXECUTE SP_EXECUTESQL @S, N'@MCODE VARCHAR(20) OUTPUT ', @MCODE OUTPUT
    SET @MCODE = LTRIM(RTRIM(@MCODE))
    IF @MCODE IS NULL SET @MCODE = ''
    IF @MCODE = ''
    BEGIN
      IF @CODELEN = 0 SET @CURCODE = @CURCODE
      ELSE
        IF LEN(@CURCODE) < @CODELEN
          SET @CURCODE = @CURCODE + REPLICATE('0', @CODELEN - LEN(@CURCODE) - 1) + '1'
        ELSE
          SET @CURCODE = @CURCODE
    END
    ELSE
    BEGIN
      SET @SUBFLOWCODE = SUBSTRING(@MCODE, LEN(@CURCODE) + 1, 8000)
      EXEC INCREASEASCIISTRING @SUBFLOWCODE OUTPUT
      IF LEN(@SUBFLOWCODE) = LEN(@MCODE) - LEN(@CURCODE)
        SET @CURCODE = @CURCODE + @SUBFLOWCODE
      ELSE BEGIN
        SET @ERRMSG = '流水码超出范围。当前的最大码值是' + @MCODE
        RAISERROR(@ERRMSG, 16, 1)
      END
    END
END
GO
