SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE PROCEDURE [dbo].[CNTRGETDATE] (
    @SDATE DATETIME,
    @DDATE DATETIME OUTPUT
)
AS
BEGIN
  SELECT @DDATE = CAST(CONVERT(VARCHAR(10),@SDATE,101) AS DATETIME)
  RETURN 0
END
GO
