SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PGFBookChk]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS   CHAR(10),  /* IS NULL 表示发送；IS NOT NULL 表示不发送 */
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE @VRET INT
  DECLARE @VSTAT INT
  DECLARE @VACTNAME CHAR(40)
  DECLARE @VSTATNAME CHAR(40)
    SET @VRET = 0;  
    
  SELECT @VSTAT = STAT FROM PGFBOOK 
  WHERE NUM = @NUM
  IF @@ROWCOUNT = 0
  BEGIN
    SET @MSG = '单据' + @NUM + '不存在'
    RETURN 1
  END
  
  IF @VSTAT = 0 AND @TOSTAT IN (300,500)
  BEGIN
    EXEC @VRET = CHKPGFBOOKTO500 @NUM, @OPER, @CLS, @MSG OUTPUT
        IF @VRET <> 0 RETURN @VRET
        IF @TOSTAT = 500  
  BEGIN
  --Fanduoyi 1298
    INSERT INTO PGFBOOKLOG(num, stat, modifier, time)
    VALUES(@num, @tostat, @oper, getdate())
    RETURN 0  
  END

    END
    
  SELECT @VACTNAME = ACTNAME FROM MODULESTAT(NOLOCK) WHERE NO = @TOSTAT
  SELECT @VSTATNAME = STATNAME FROM MODULESTAT(NOLOCK) WHERE NO = @VSTAT
    SET @MSG = '不能' + @VACTNAME + '状态为' + @VSTATNAME + '的应付扣款单'
    RETURN 1
END
GO
