SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PCT_CNTR_RCV](
  @BILL_ID INT,
  @SRC_ID INT,
  @OPER VARCHAR(50),
  @MSG VARCHAR(255) OUTPUT
) AS
BEGIN
  DECLARE @RCV_GID INT
  DECLARE @NET_STAT INT
  DECLARE @NET_NUM VARCHAR(14)
  DECLARE @NET_TYPE INT
  DECLARE @NET_VERSION INT
  DECLARE @VRET INT
  DECLARE @OPERGID INT

  SELECT @RCV_GID = RCV, @NET_STAT = STAT, @NET_TYPE = NTYPE, @NET_NUM = NUM, @NET_VERSION = VERSION
  FROM NCTCNTR(NOLOCK) WHERE ID = @BILL_ID AND SRC = @SRC_ID
  IF @@ROWCOUNT = 0 OR @NET_NUM IS NULL
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '不存在'
    RETURN 1
  END

  IF EXISTS(SELECT 1 FROM CTCNTR(NOLOCK) WHERE NUM = @NET_NUM AND VERSION
 = @NET_VERSION AND STAT = @NET_STAT)
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '已经被接收'
    RETURN 2
  END

  IF (SELECT MAX(USERGID) FROM FASYSTEM(NOLOCK)) <>  @RCV_GID
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '接收单位不是本单位'
    RETURN 3
  END

  IF @NET_TYPE <> 1
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '不在接收缓冲区中'
    RETURN 4
  END

  IF @NET_STAT = 500
  BEGIN
    DELETE FROM CTCNTR WHERE NUM = @NET_NUM AND VERSION = @NET_VERSION
    DELETE FROM CTCNTRDTL WHERE NUM = @NET_NUM AND VERSION = @NET_VERSION
    DELETE FROM CTCNTRDTLDATASRC WHERE NUM = @NET_NUM AND VERSION = @NET_VERSION
    DELETE FROM CTCNTRFIXDTL WHERE NUM = @NET_NUM AND VERSION = @NET_VERSION
    DELETE FROM CTCNTRFIXSTORE WHERE NUM = @NET_NUM AND VERSION = @NET_VERSION
    DELETE FROM CTCNTRFIXDATE WHERE NUM = @NET_NUM AND VERSION = @NET_VERSION
    DELETE FROM CTCNTRRATEDTL WHERE NUM = @NET_NUM AND VERSION = @NET_VERSION
    DELETE FROM CTCNTRRATEDISC WHERE NUM = @NET_NUM AND VERSION = @NET_VERSION
    DELETE FROM CTCNTRRATESTORE WHERE NUM = @NET_NUM AND VERSION = @NET_VERSION
    DELETE FROM CTCNTRRATEGOODS WHERE NUM = @NET_NUM AND VERSION = @NET_VERSION
    DELETE FROM CTCNTRRATESTOREGD WHERE NUM = @NET_NUM AND VERSION = @NET_VERSION
    DELETE FROM CTCNTRRATESTOREGDDISC WHERE NUM = @NET_NUM AND VERSION = @NET_VERSION
    DELETE FROM CTCNTRRATEGUARDDISC WHERE NUM = @NET_NUM AND VERSION = @NET_VERSION
    DELETE FROM CTCNTRRATEGUARDCHG WHERE NUM = @NET_NUM AND VERSION = @NET_VERSION
    DELETE FROM CTCNTRRATEBYMONTHDISC WHERE NUM = @NET_NUM AND VERSION = @NET_VERSION
    DELETE FROM CTCNTRRATEBYMONTHSTOREGDDISC WHERE NUM = @NET_NUM AND VERSION = @NET_VERSION
    DELETE FROM CTCNTRRATECONDPLAN WHERE NUM = @NET_NUM AND VERSION = @NET_VERSION--zz 090508
    DELETE FROM CTCNTRBRAND WHERE NUM = @NET_NUM AND VERSION = @NET_VERSION--zhujieD
    DELETE FROM GROUPCNTR WHERE NUM = @NET_NUM AND VERSION = @NET_VERSION

    UPDATE CTCNTR SET TAG = 0 WHERE NUM = @NET_NUM AND VERSION < @NET_VERSION

    INSERT INTO CTSCOPE(CATEGORY, CODE, SQLCOND, SQLTEXT, NOTE)
    SELECT CATEGORY, CODE, SQLCOND, SQLTEXT, NOTE
    FROM NCTSCOPE(NOLOCK)
    WHERE SRC = @SRC_ID AND ID = @BILL_ID
      AND (CATEGORY + '||' + CODE) NOT IN (SELECT CATEGORY + '||' + CODE FROM CTSCOPE(NOLOCK))

    INSERT INTO CTCHGDEF(CODE, NAME, NOTE, CHGCLS, MODALTYPE, AUTOCALC, WHENGEN, GENMETHOD,
      GENUNIT, GENCYCLE, GENDAYOFFSET, PAYDIRECT, GATHERINGMODE, TOPAYMETHOD, PAYLIMIT,
      FINCODE, FINNAME, STOPPED, PAYUNIT, DESIGNCYCLE)
    SELECT CODE, NAME, NOTE, CHGCLS, MODALTYPE, AUTOCALC, WHENGEN, GENMETHOD,
      GENUNIT, GENCYCLE, GENDAYOFFSET, PAYDIRECT, GATHERINGMODE, TOPAYMETHOD, PAYLIMIT,
      FINCODE, FINNAME, STOPPED, PAYUNIT, DESIGNCYCLE
    FROM NCTCHGDEF(NOLOCK)
    WHERE SRC = @SRC_ID AND ID = @BILL_ID
      AND CODE NOT IN (SELECT CODE FROM CTCHGDEF(NOLOCK))

    INSERT INTO CTCHGDEFFIX(CODE, FIXMETHOD, AMOUNT, FEETOSTORE)
    SELECT CODE, FIXMETHOD, AMOUNT, FEETOSTORE
    FROM NCTCHGDEFFIX(NOLOCK)
    WHERE SRC = @SRC_ID AND ID = @BILL_ID
      AND CODE NOT IN (SELECT CODE FROM CTCHGDEFFIX(NOLOCK))

    INSERT INTO CTCHGDEFRATE(CODE, DATASRCCLS, FEEUNIT, FEECYCLE, FEEDAYOFFSET, FIXCOST, RATEMODE,
      CALCMODE, FEEPREC, ROUNDTYPE, AHEADDAYS, DISCOUNTRATE, FEETOSTORE, GUARDMODE)
    SELECT CODE, DATASRCCLS, FEEUNIT, FEECYCLE, FEEDAYOFFSET, FIXCOST, RATEMODE,
      CALCMODE, FEEPREC, ROUNDTYPE, AHEADDAYS, DISCOUNTRATE, FEETOSTORE, GUARDMODE
    FROM NCTCHGDEFRATE(NOLOCK)
    WHERE SRC = @SRC_ID AND ID = @BILL_ID
      AND CODE NOT IN (SELECT CODE FROM CTCHGDEFRATE(NOLOCK))

    INSERT INTO CTDATASRC(CODE, NAME, CLS, FLAG, HDPOSVER, NOTE, MODALTYPE)
    SELECT CODE, NAME, CLS, FLAG, HDPOSVER, NOTE, MODALTYPE
    FROM NCTDATASRC(NOLOCK)
    WHERE SRC = @SRC_ID AND ID = @BILL_ID
      AND CODE NOT IN (SELECT CODE FROM CTDATASRC(NOLOCK))

    INSERT INTO CTCHGDATASRC(CODE, DSCODE)
    SELECT CODE, DSCODE
    FROM NCTCHGDATASRC(NOLOCK)
    WHERE SRC = @SRC_ID AND ID = @BILL_ID
      AND (CODE + '||' + DSCODE) NOT IN (SELECT CODE + '||' + DSCODE FROM CTCHGDATASRC(NOLOCK))

    INSERT INTO CTCNTR(NUM, VERSION, STAT, VENDOR, SIGNDATE, BEGINDATE, ENDDATE, REALENDDATE,
      VDRSIGNER, DEPT, SIGNER, CNTRNO, FILETEXT, MODIFIER, LSTUPDTIME, PRNTIME, TAG, NOTE,
      SALECLS, GUARDAMT, UPGUARDRATE, GUARDRATE, RENT, PAYBILLCLS, PAYBILLTAXRATE, CUSTOMDEF,
      EXSTORE, AGENTMODE, SALESQ, CALCCENTER, SNDTIME, SORT)
    SELECT NUM, VERSION, 0, VENDOR, SIGNDATE, BEGINDATE, ENDDATE, REALENDDATE,
      VDRSIGNER, DEPT, SIGNER, CNTRNO, FILETEXT, MODIFIER, LSTUPDTIME, PRNTIME, TAG, NOTE,
      SALECLS, GUARDAMT, UPGUARDRATE, GUARDRATE, RENT, PAYBILLCLS, PAYBILLTAXRATE, CUSTOMDEF,
      EXSTORE, AGENTMODE, SALESQ, CALCCENTER, SNDTIME, SORT
    FROM NCTCNTR(NOLOCK)
    WHERE SRC = @SRC_ID AND ID = @BILL_ID

    INSERT INTO CTCNTRDTL(NUM, VERSION, LINE, CHGCODE, GENUNIT, GENCYCLE, GENDAYOFFSET, FSTGENDATE,
      NEXTGENDATE, GATHERINGMODE, MEMO, PAYUNIT)
    SELECT NUM, VERSION, LINE, CHGCODE, GENUNIT, GENCYCLE, GENDAYOFFSET, FSTGENDATE,
      NEXTGENDATE, GATHERINGMODE, MEMO, PAYUNIT
    FROM NCTCNTRDTL(NOLOCK)
    WHERE SRC = @SRC_ID AND ID = @BILL_ID

    INSERT INTO CTCNTRDTLDATASRC(NUM, VERSION, LINE, DSCODE)
    SELECT NUM, VERSION, LINE, DSCODE
    FROM NCTCNTRDTLDATASRC(NOLOCK)
    WHERE SRC = @SRC_ID AND ID = @BILL_ID

    INSERT INTO CTCNTRFIXDTL(NUM, VERSION, LINE, FEEUNIT, FEECYCLE, FSTFEEDATE,
      NEXTBEGINDATE, NEXTENDDATE, AMOUNT)
    SELECT NUM, VERSION, LINE, FEEUNIT, FEECYCLE, FSTFEEDATE,
      NEXTBEGINDATE, NEXTENDDATE, AMOUNT
    FROM NCTCNTRFIXDTL(NOLOCK)
    WHERE SRC = @SRC_ID AND ID = @BILL_ID

    INSERT INTO CTCNTRFIXSTORE(NUM, VERSION, LINE, ITEMNO, STORESCOPE, TOTAL, NOTE)
    SELECT NUM, VERSION, LINE, ITEMNO, STORESCOPE, TOTAL, NOTE
    FROM NCTCNTRFIXSTORE(NOLOCK)
    WHERE SRC = @SRC_ID AND ID = @BILL_ID

    INSERT INTO CTCNTRFIXDATE(NUM, VERSION, LINE, ITEMNO, GENDATE, TOTAL, CHGBOOKNUM, NOTE)
    SELECT NUM, VERSION, LINE, ITEMNO, GENDATE, TOTAL, CHGBOOKNUM, NOTE
    FROM NCTCNTRFIXDATE(NOLOCK)
    WHERE SRC = @SRC_ID AND ID = @BILL_ID

    INSERT INTO CTCNTRRATEDTL(NUM, VERSION, LINE, FEEUNIT, FEECYCLE, FEEDAYOFFSET, FSTFEEDATE,
      NEXTBEGINDATE, NEXTENDDATE, FIXCOST, RATEMODE, CALCMODE, FEEPREC, ROUNDTYPE, STORESCOPE,
      GDSCOPE, GDSCOPESQL, GDSCOPETEXT, AHEADDAYS, DISCOUNTRATE)
    SELECT NUM, VERSION, LINE, FEEUNIT, FEECYCLE, FEEDAYOFFSET, FSTFEEDATE,
      NEXTBEGINDATE, NEXTENDDATE, FIXCOST, RATEMODE, CALCMODE, FEEPREC, ROUNDTYPE, STORESCOPE,
      GDSCOPE, GDSCOPESQL, GDSCOPETEXT, AHEADDAYS, DISCOUNTRATE
    FROM NCTCNTRRATEDTL(NOLOCK)
    WHERE SRC = @SRC_ID AND ID = @BILL_ID

    INSERT INTO CTCNTRRATEDISC(NUM, VERSION, LINE, ITEMNO, RATE, LOWAMT, HIGHAMT, QBASE)
    SELECT NUM, VERSION, LINE, ITEMNO, RATE, LOWAMT, HIGHAMT, QBASE
    FROM NCTCNTRRATEDISC(NOLOCK)
    WHERE SRC = @SRC_ID AND ID = @BILL_ID

    INSERT INTO CTCNTRRATESTORE(NUM, VERSION, LINE, ITEMNO, STOREGID)
    SELECT NUM, VERSION, LINE, ITEMNO, STOREGID
    FROM NCTCNTRRATESTORE(NOLOCK)
    WHERE SRC = @SRC_ID AND ID = @BILL_ID

    INSERT INTO CTCNTRRATEGOODS(NUM, VERSION, LINE, ITEMNO, GDGID)
    SELECT NUM, VERSION, LINE, ITEMNO, GDGID
    FROM NCTCNTRRATEGOODS(NOLOCK)
    WHERE SRC = @SRC_ID AND ID = @BILL_ID

    INSERT INTO CTCNTRRATESTOREGD(NUM, VERSION, LINE, ITEMNO, STORESCOPE, GDSCOPESQL,
      GDSCOPETEXT, NOTE)
    SELECT NUM, VERSION, LINE, ITEMNO, STORESCOPE, GDSCOPESQL,
      GDSCOPETEXT, NOTE
    FROM NCTCNTRRATESTOREGD(NOLOCK)
    WHERE SRC = @SRC_ID AND ID = @BILL_ID

    INSERT INTO CTCNTRRATESTOREGDDISC(NUM, VERSION, LINE, ITEMNO, ROWNO, RATE,
      LOWAMT, HIGHAMT, QBASE)
    SELECT NUM, VERSION, LINE, ITEMNO, ROWNO, RATE,
      LOWAMT, HIGHAMT, QBASE
    FROM NCTCNTRRATESTOREGDDISC(NOLOCK)
    WHERE SRC = @SRC_ID AND ID = @BILL_ID

    INSERT INTO CTCNTRRATEGUARDDISC(NUM, VERSION, LINE, ITEMNO, RATE, LOWAMT, HIGHAMT, QBASE)
    SELECT NUM, VERSION, LINE, ITEMNO, RATE, LOWAMT, HIGHAMT, QBASE
    FROM NCTCNTRRATEGUARDDISC(NOLOCK)
    WHERE SRC = @SRC_ID AND ID = @BILL_ID

    INSERT INTO CTCNTRRATEGUARDCHG(NUM, VERSION, LINE, ITEMNO, OTHERCNTRNUM, OTHERCHGCODE)
    SELECT NUM, VERSION, LINE, ITEMNO, OTHERCNTRNUM, OTHERCHGCODE
    FROM NCTCNTRRATEGUARDCHG(NOLOCK)
    WHERE SRC = @SRC_ID AND ID = @BILL_ID

    INSERT INTO CTCNTRRATEBYMONTHDISC(NUM, VERSION, LINE, ITEMNO, RATE, LOWDATE, HIGHDATE, GAMT)
    SELECT NUM, VERSION, LINE, ITEMNO, RATE, LOWDATE, HIGHDATE, GAMT
    FROM NCTCNTRRATEBYMONTHDISC(NOLOCK)
    WHERE SRC = @SRC_ID AND ID = @BILL_ID

    INSERT INTO CTCNTRRATEBYMONTHSTOREGDDISC(NUM, VERSION, LINE, ITEMNO, ROWNO, RATE, LOWDATE,
      HIGHDATE, GAMT)
    SELECT NUM, VERSION, LINE, ITEMNO, ROWNO, RATE, LOWDATE,
      HIGHDATE, GAMT
    FROM NCTCNTRRATEBYMONTHSTOREGDDISC(NOLOCK)
    WHERE SRC = @SRC_ID AND ID = @BILL_ID
    --zz 090508
    INSERT INTO CTCNTRRATECONDPLAN(NUM, VERSION, LINE, VENDOR, DEPT, BEGINDATE, ENDDATE, EXPAMT,
        ADDRATE, EXESTAT, EXEBILLINFO, NOTE)
    SELECT NUM, VERSION, LINE, VENDOR, DEPT, BEGINDATE, ENDDATE, EXPAMT, ADDRATE, EXESTAT,
        EXEBILLINFO, NOTE
    FROM NCTCNTRRATECONDPLAN(NOLOCK)
    WHERE SRC = @SRC_ID AND ID = @BILL_ID
    
    --zhujieD
    INSERT INTO CTCNTRBRAND(NUM, VERSION, ITEMNO, CODE, TYPE, STATUS, BEGINDATE, ENDDATE, NOTE)
    SELECT NUM, VERSION, ITEMNO, CODE, TYPE, STATUS, BEGINDATE, ENDDATE, NOTE
    FROM NCTCNTRBRAND(NOLOCK)
    WHERE SRC = @SRC_ID AND ID = @BILL_ID

    INSERT INTO CNTRGROUP(NUM, VERSION, VENDOR, BEGINDATE, ENDDATE, REALENDDATE, LSTUPDOPER,
      LSTUPDTIME, CHECKER, CHKDATE, STAT, TAG, NOTE)
    SELECT NUM, VERSION, VENDOR, BEGINDATE, ENDDATE, REALENDDATE, LSTUPDOPER,
      LSTUPDTIME, CHECKER, CHKDATE, STAT, TAG, NOTE
    FROM NCNTRGROUP(NOLOCK)
    WHERE SRC = @SRC_ID AND ID = @BILL_ID
      AND (NUM + '||' + RTRIM(LTRIM(STR(VERSION)))) NOT IN (SELECT NUM + '||' + RTRIM(LTRIM(STR(VERSION))) FROM CNTRGROUP(NOLOCK))

    INSERT INTO GROUPCNTR(NUM, VERSION, CNTRNUM, CNTRVERSION)
    SELECT NUM, VERSION, CNTRNUM, CNTRVERSION
    FROM NGROUPCNTR(NOLOCK)
    WHERE SRC = @SRC_ID AND ID = @BILL_ID
      AND (NUM + '||' + RTRIM(LTRIM(STR(VERSION))) + CNTRNUM + '||' + RTRIM(LTRIM(STR(CNTRVERSION)))) NOT IN (SELECT NUM + '||' + RTRIM(LTRIM(STR(VERSION))) + CNTRNUM + '||' + RTRIM(LTRIM(STR(CNTRVERSION))) FROM GROUPCNTR(NOLOCK))
  END

  EXEC @VRET = PCT_CNTR_NETDELETE @BILL_ID, @SRC_ID, @OPER, @MSG OUTPUT
  IF @VRET <> 0 RETURN @VRET

  SET @OPERGID = 1
  SELECT @OPERGID = GID FROM EMPLOYEE(NOLOCK) WHERE @OPER = RTRIM(NAME) + '[' + RTRIM(CODE) + ']'
  EXEC @VRET = PCT_CNTR_ON_MODIFY @NET_NUM, @NET_VERSION, @NET_STAT, @OPERGID, @MSG OUTPUT
  IF @VRET <> 0 RETURN @VRET

  SET @MSG = '单据：' + @NET_NUM + '接收成功' + @MSG

  RETURN 0
END

GO
