SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
Create Procedure [dbo].[PURCHASEORDER_CHECK_100TO3200]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
with Encryption
as
begin
  DECLARE
    @SRCNUM CHAR(14),
    @VRET INT

  SELECT @SRCNUM = SRCNUM FROM PURCHASEORDER(NOLOCK) WHERE NUM = @NUM AND CLS = @CLS

  update PURCHASEORDER SET STAT = 300, LSTUPDTIME = getdate(), FINISHEDDATE = getdate()
  WHERE NUM = @SRCNUM AND CLS = '销售定货'

  EXEC PURCHASEORDADDLOG @SRCNUM, '销售定货', 300, '已完成', @OPER

  EXEC @VRET = SENDPOORD @SRCNUM, @OPER, '销售定货', 0, @MSG
  if @VRET <> 0 RETURN @VRET

  --IF (SELECT OPTIONVALUE FROM HDOPTION WHERE OPTIONCAPTION = 'AutoSndOnChk' AND MODULENO = 665) = 1
  --begin
    --declare @ORDNUM char(14)
    --SELECT @ORDNUM = SRCNUM FROM PURCHASEORDER(NOLOCK) WHERE NUM = @NUM AND CLS = @CLS
    --EXEC SENDPOORD @ORDNUM, @OPER, '销售定货', 0, ''
  --end

  UPDATE PURCHASEORDER SET Stat = @ToStat, LSTUPDTIME = getdate() where num = @NUM and cls = @CLS
  EXEC PURCHASEORDERADDLOG @NUM, @CLS, 3200, '确认', @OPER
end
GO
