SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[MKTIVGTCHK400TO1200]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS	 CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE @VSTAT INT
  SELECT @VSTAT = STAT FROM PSMKTIVGT WHERE NUM = @NUM;
  IF @VSTAT <> 400
  BEGIN
    SET @MSG = @NUM + '非总部批准状态不能提交！'
    RETURN(1)
  END
  UPDATE PSMktIvgt 
  SET STAT = 1200, CHKDATE = GETDATE(),CHECKER = @OPER, LSTUPDTIME = GETDATE()
  WHERE NUM = @NUM
  EXEC MktIvgtADDLOG @NUM, 1200, '', @OPER
  RETURN 0
END
GO
