SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create procedure [dbo].[CHQSNDGOODS](
	@GID INT,
	@OPERGID INT,
	@MSG VARCHAR(255) OUTPUT
) as
begin
  declare @GROUPID INT,     @NTYPE SMALLINT,    @NNOTE varchar(100),
          @EXTIME DATETIME, @RHQUUID CHAR(32),  @NSTAT SMALLINT
  /*if not exists(select 1 from GOODS where gid = @gid and UPCTRL = 1)
  begin
    set @msg = '不能定位已经审核的定单'+@num
    return 1
  end  */

  --exec OPTREADINT 0, '...', 0, @optvalue output
  exec @GROUPID = SeqNextValue 'CHQBASIC'
  set @RHQUUID = '1'
  set @NTYPE = 0
  set @NNOTE = ''
  set @NSTAT = 0
  set @EXTIME = Getdate()
  insert into CQNGOODS(GROUPID, RHQUUID, NTYPE, NSTAT, NNOTE, EXTIME, 
      GID, CODE, NAME, SPEC, SORT, RTLPRC, INPRC, TAXRATE, PROMOTE, PRCTYPE, 
      SALE, LSTINPRC, INVPRC, OLDINVPRC, LWTRTLPRC, WHSPRC, WRH, ACNT, 
      PAYTODTL, PAYRATE, MUNIT, ISPKG, GFT, QPC, TM, MANUFACTOR, MCODE, GPR, 
      LOWINV, HIGHINV, VALIDPERIOD, CREATEDATE, MEMO, CHKVD, SRC, SNDTIME, 
      LSTUPDTIME, DXPRC, BILLTO, AUTOORD, ORIGIN, GRADE, MBRPRC, SALETAX, 
      PSR, F1, F2, F3, FILLER, MODIFIER, ALC, CODE2, MKTINPRC, MKTRTLPRC, CNTINPRC, 
      ALCQTY, ISBIND, BRAND, ISLTD, INVCOST, BQTYPRC, KEEPTYPE, NEndTime, NCanPay, 
      SSStart, SSEnd, Season, HQControl, ORDCYCLE, ALCCTR, isdisp, TOPRTLPRC, 
      LSTUPDTIME2,UPCTRL)
    select @GROUPID, @RHQUUID, @NTYPE, @NSTAT, @NNOTE, @EXTIME, 
      GID, CODE, NAME, SPEC, SORT, RTLPRC, INPRC, TAXRATE, PROMOTE, PRCTYPE, 
      SALE, LSTINPRC, INVPRC, OLDINVPRC, LWTRTLPRC, WHSPRC, WRH, ACNT, 
      PAYTODTL, PAYRATE, MUNIT, ISPKG, GFT, QPC, TM, MANUFACTOR, MCODE, GPR, 
      LOWINV, HIGHINV, VALIDPERIOD, CREATEDATE, MEMO, CHKVD, SRC, SNDTIME, 
      LSTUPDTIME, DXPRC, BILLTO, AUTOORD, ORIGIN, GRADE, MBRPRC, SALETAX, 
      PSR, F1, F2, F3, FILLER, MODIFIER, ALC, CODE2, MKTINPRC, MKTRTLPRC, CNTINPRC, 
      ALCQTY, ISBIND, BRAND, ISLTD, INVCOST, BQTYPRC, KEEPTYPE, NEndTime, NCanPay, 
      SSStart, SSEnd, Season, HQControl, ORDCYCLE, ALCCTR, isdisp, TOPRTLPRC, 
      LSTUPDTIME2,UPCTRL
    from GOODS(nolock)
    where GID = @GID
  insert into CQNGDINPUT(GROUPID,RHQUUID,NTYPE,NSTAT,NNOTE,EXTIME,CODE,CODETYPE,GID,FLAGS)
    select @GROUPID,@RHQUUID,@NTYPE,@NSTAT,@NNOTE,@EXTIME,CODE,CODETYPE,GID,FLAGS
    from GDINPUT
    where gid = @GID
  insert into CQNPKG(GROUPID,RHQUUID,NTYPE,NSTAT,NNOTE,EXTIME,EGID,PGID,QTY)
    select @GROUPID,@RHQUUID,@NTYPE,@NSTAT,@NNOTE,@EXTIME,EGID,PGID,QTY
    from PKG
    where PGID = @GID 
  insert into CQNVDRGD(GROUPID,RHQUUID,NTYPE,NSTAT,NNOTE,EXTIME,VDRGID,GDGID,WRH)
    select @GROUPID,@RHQUUID,@NTYPE,@NSTAT,@NNOTE,@EXTIME,VDRGID, GDGID, WRH
    from VDRGD
    where GDGID = @GID
end;
GO
