SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CLEARTEMPSUBWRH]
	@PI_GDGID INT,
	@PI_WRH INT
AS
BEGIN
	DELETE FROM TEMPSUBWRH WHERE SPID = @@SPID AND GDGID = @PI_GDGID AND WRH = @PI_WRH
END
GO
