SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[STKOUTBCKFIFOCHK]
	@PI_CLS CHAR(10),
	@PI_NUM CHAR(10),
	@PI_LINE INT,
	@PI_WRH INT,
	@PI_GDGID INT,
	@PI_QTY MONEY,
	@PI_COSTPRC MONEY OUTPUT,
	@PI_COST MONEY OUTPUT,
	@PI_ERRMSG VARCHAR(200) OUTPUT
AS
BEGIN
	DECLARE @COST MONEY,@AMT MONEY,@NEWSUBWRH INT
	DECLARE @RETURN_STATUS INT

	IF @PI_QTY < 0 
	BEGIN
		SELECT @PI_ERRMSG = '先进先出不能负数退货'
		RETURN 1014
	END
	IF (@PI_CLS <> '批发') AND (@PI_CLS <> '配货')
	BEGIN
		SELECT @PI_ERRMSG = '非批发或配货业务不能进行先进先出处理！'
		RETURN -1
	END

	EXEC CLEARTEMPSUBWRH @PI_GDGID,@PI_WRH
	
	SELECT @COST = 0,@AMT = 0

	IF @PI_CLS = '批发' 
	BEGIN
		SELECT @RETURN_STATUS = 0
		SELECT @COST = ROUND(@PI_QTY * @PI_COSTPRC,2)
	END ELSE IF @PI_CLS = '配货' 
	BEGIN

		IF NOT EXISTS(SELECT 1 FROM STKOUTBCKDTL2 WHERE CLS = @PI_CLS AND NUM = @PI_NUM AND LINE = @PI_LINE)
		BEGIN
			EXEC GETFIFODEFINPRC @PI_GDGID,@PI_COSTPRC

			SELECT @COST = ROUND(@PI_QTY * @PI_COSTPRC,2)

		END
		ELSE
		BEGIN
			INSERT INTO TEMPSUBWRH(SPID,SUBWRH,WRH,GDGID,QTY,COST)
				SELECT @@SPID,SUBWRH,WRH,GDGID,QTY,COST 
					FROM STKOUTBCKDTL2 WHERE CLS=@PI_CLS AND NUM = @PI_NUM AND LINE = @PI_LINE

		END
	END

	EXEC @RETURN_STATUS = LOADINSUBWRH_2 @PI_GDGID,@PI_WRH,@PI_QTY,@COST
	
	IF @RETURN_STATUS <> 0 RETURN @RETURN_STATUS
	
	DELETE FROM STKOUTBCKDTL2 WHERE CLS = @PI_CLS AND NUM = @PI_NUM AND LINE = @PI_LINE

	INSERT INTO STKOUTBCKDTL2(CLS,NUM,LINE,SUBWRH,WRH,GDGID,QTY,COST,COSTADJ)
		SELECT @PI_CLS,@PI_NUM,@PI_LINE,SUBWRH,WRH,GDGID,QTY,COST,COSTADJ FROM TEMPSUBWRH 
			WHERE SPID = @@SPID AND GDGID = @PI_GDGID AND WRH = @PI_WRH

	SELECT @NEWSUBWRH= MIN(SUBWRH), @COST= SUM(COST) FROM TEMPSUBWRH WHERE SPID = @@SPID AND WRH = @PI_WRH AND GDGID = @PI_GDGID

	IF @PI_CLS = '批发'
	BEGIN
		UPDATE STKOUTBCKDTL SET SUBWRH = @NEWSUBWRH,COST = @COST
			WHERE CLS = @PI_CLS AND NUM = @PI_NUM AND LINE = @PI_LINE
	END
	ELSE
	BEGIN
		UPDATE STKOUTBCKDTL SET SUBWRH = @NEWSUBWRH,COST = @COST,COSTPRC = @COST/@PI_QTY
			WHERE CLS = @PI_CLS AND NUM = @PI_NUM AND LINE = @PI_LINE
	END

	SELECT @PI_COST = @COST

	EXEC CLEARTEMPSUBWRH @PI_GDGID,@PI_WRH
	RETURN 0

END
GO
