SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CHKBLPreOrd_TO1400]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS	 CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
	UPDATE BLPreOrd SET
		STAT = 1400,
		CHKDATE = GETDATE(),
		CHECKER = @OPER,
		LSTUPDTIME = GETDATE()
	WHERE NUM = @NUM
	UPDATE BLPreOrdDTL SET FLAG = 4 WHERE NUM = @NUM
	EXEC BLPreOrdADDLOG @NUM,1400,'',@OPER
	RETURN 0
END
GO
