SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE Procedure [dbo].[TA_OVERFLOW]
	@WHERE_CLAUSE VARCHAR(255)
As

EXEC ('DECLARE CUR_GETVOUCHER CURSOR FOR 
	SELECT Dept.code a,dept.name b,
	CONVERT(VARCHAR(100),SUM(OVFDTL.AMTOVF)) c, 
	CONVERT(VARCHAR(2),SUM(0)) D,
	CONVERT(VARCHAR(2),SUM(0)) E,
	CONVERT(VARCHAR(2),SUM(0)) F,
	CONVERT(VARCHAR(2),SUM(0)) G,
	CONVERT(VARCHAR(2),SUM(0)) H,
	CONVERT(VARCHAR(2),SUM(0)) I,
	CONVERT(VARCHAR(2),SUM(0)) J,
	CONVERT(VARCHAR(2),SUM(0)) K,
	CONVERT(VARCHAR(2),SUM(0)) L,
	CONVERT(VARCHAR(2),SUM(0)) M,
	CONVERT(VARCHAR(2),SUM(0)) N,
	CONVERT(VARCHAR(2),SUM(0)) O
	FROM OVFDTL OVFDTL(NOLOCK), OVF OVF(NOLOCK), 
	Goodsh GoodSH(NOLOCK), Dept (nolock) 
	WHERE OVF.NUM = OVFDTL.NUM
	and OVFDTL.GDGID = Goodsh.GID
        and Goodsh.F1=Dept.Code
	and '+ @WHERE_CLAUSE +  
	' GROUP BY dept.code,dept.name')

RETURN 0









GO
