SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRMRTNPNTAGM_DOREMOVE]
(
  @NUM VARCHAR(14),         --单号
  @MSG VARCHAR(255) OUTPUT  --错误信息
)
AS
BEGIN
  DELETE FROM PRMRTNPNTAGM WHERE NUM = @NUM
  DELETE FROM PRMRTNPNTAGMDTL WHERE NUM = @NUM
  DELETE FROM PRMRTNPNTAGMEXGDDTL WHERE NUM = @NUM
  DELETE FROM PRMRTNPNTAGMRATEDTL WHERE NUM = @NUM
  DELETE FROM PRMRTNPNTAGMLACSTORE WHERE NUM = @NUM
  SET @MSG = ''
  RETURN(0)
END
GO
