SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[MKTPRC_GENFROMMKTPRC]
(
  @MKTPRCNUM CHAR(14),
  @OPER CHAR(30),
  @GENNUM CHAR(14) OUTPUT
)
AS
BEGIN
  DECLARE @SETTLENO INT, @STOREGID INT
  EXEC GENNEXTBILLNUMEX NULL, 'MKTPRC', @GENNUM OUTPUT
  SELECT @SETTLENO = MAX(NO) FROM MONTHSETTLE(NOLOCK)
  SELECT @STOREGID = USERGID FROM SYSTEM(NOLOCK)

  INSERT INTO MKTPRC(NUM, SETTLENO, STAT, STOREGID, SCHEMENUM, INVSTER, INVSTDATE, FILLER, FILDATE, LSTUPDTIME, RECCNT, NOTE, INVSTOBJ, INVSTPLACE)
  SELECT @GENNUM, @SETTLENO, 0, @STOREGID, SCHEMENUM, INVSTER, INVSTDATE, @OPER, GETDATE(), GETDATE(), RECCNT, NOTE, INVSTOBJ, INVSTPLACE
  FROM MKTPRC(NOLOCK)
  WHERE NUM = @MKTPRCNUM

  INSERT INTO MKTPRCDTL(NUM, LINE, GDGID, GDQPCSTR, GDQPC, RTLPRC, CNTINPRC, WHSPRC, MBRPRC, PROMOTEPRICE, PROMOTEINPRC, PROMOTEMBRPRC, NOTE,
  	LRTLPRC, LCNTINPRC, LWHSPRC, LMBRPRC, LPROMOTEPRICE, LPROMOTEINPRC, LPROMOTEMBRPRC) --2006.11.22 added by zhanglong,市场价格单明细增加保存历史本店价格信息
  SELECT @GENNUM, LINE, GDGID, GDQPCSTR, GDQPC, RTLPRC, CNTINPRC, WHSPRC, MBRPRC, PROMOTEPRICE, PROMOTEINPRC, PROMOTEMBRPRC, NOTE,
  	LRTLPRC, LCNTINPRC, LWHSPRC, LMBRPRC, LPROMOTEPRICE, LPROMOTEINPRC, LPROMOTEMBRPRC  --2006.11.22 added by zhanglong
  FROM MKTPRCDTL(NOLOCK)
  WHERE NUM = @MKTPRCNUM
END
GO
