SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE  [dbo].[LOADPROMDTLTO50]
(
  @PICLS         VARCHAR(10),
  @PINUM         VARCHAR(14),
  @PISTOREGID    INT,
  @PIPSETTLENO   INT,
  @PIASTART      DATETIME,
  @PIAFINISH     DATETIME,
  @PICYCLE       DATETIME,
  @PICSTART      DATETIME,
  @PICFINISH     DATETIME,
  @PICSPEC       VARCHAR(255),
  @PIFLAG        INT,
  @PILINE        INT,
  @PIGDGID       INT,
  @PIGDCODE      CHAR(13),
  @PIFIXRATIO    DECIMAL(24, 4),
  @PIGFTRATIO    DECIMAL(24, 4),
  @PIHASCOND     INT,
  @POERR_MSG     VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE
    @VRET     INT,
    @VQPC     DECIMAL(24,4),
    @VIQPCSTR VARCHAR(20),
    @VOCRTIME DATETIME,
    @PExprom  INT,
    @Code     CHAR(13),
    @OPT_ADDSUBDEPT INT,
    @SUBCODE  VARCHAR(64),
    @VDLTPRICEPROM SMALLINT,
    @PRIORITY INT --优先级

  SET @VRET = 0
  UPDATE GOODS SET LSTUPDTIME = GETDATE() WHERE GID = @PIGDGID

  SELECT @VOCRTIME = OCRTIME, @PExprom = EXPROM, @VDLTPRICEPROM = DLTPRICEPROM, @PRIORITY = PRIORITY
  FROM PROM WHERE NUM = @PINUM AND CLS = @PICLS

  SELECT @VQPC = ISNULL(QPC, 1), @VIQPCSTR = ISNULL(QPCSTR, '1*1') FROM GDINPUT WHERE GID = @PIGDGID AND CODE = @PIGDCODE
  SET @VQPC = ISNULL(@VQPC, 1)
  SET @VIQPCSTR = ISNULL(@VIQPCSTR, '1*1')

  EXEC OPTREADINT 0, 'ADDSUBDEPT', 0, @OPT_ADDSUBDEPT OUTPUT

    /*IF @PIFLAG = 4 AND @OPT_ADDSUBDEPT = 1 --部门
    BEGIN
        EXEC GetSubDept @PIGDCODE
        DECLARE C CURSOR FOR
           SELECT B.CODE FROM SUBDEPTBYCODE A(NOLOCK), DEPT B(NOLOCK) WHERE A.SPID = @@SPID AND A.CODE = B.CODE
        OPEN C
        FETCH NEXT FROM C INTO @SUBCODE
        WHILE @@FETCH_STATUS = 0
        BEGIN
            INSERT INTO PROMOTE (STORE,CLS,GDGID,GDCODE,
                ASTART,AFINISH,CYCLE,CSTART,CFINISH,CSPEC,
                OCRTIME,BILLNUM,PSETTLENO,BILLLINE,QTY,FIXRATIO,GFTRATIO,FLAG,HASCOND,EXPROM,QPC,PREC,ROUNDTYPE)

            SELECT  @PISTOREGID,@PICLS,@PIGDGID,@SUBCODE,
                @PIASTART,@PIAFINISH,@PICYCLE,@PICSTART,@PICFINISH,@PICSPEC,
                @VOCRTIME,@PINUM,@PIPSETTLENO,@PILINE,QTY,@PIFIXRATIO,@PIGFTRATIO,FLAG,@PIHASCOND,@PExprom, ISNULL(@VQPC, 1),PREC,ROUNDTYPE
            FROM PROMGOODS
            WHERE NUM = @PINUM AND CLS = @PICLS AND LINE = @PILINE AND FLAG = @PIFLAG

            FETCH NEXT FROM C INTO @SUBCODE
        END
        CLOSE C
        DEALLOCATE C
    END ELSE BEGIN*/
    INSERT INTO PROMOTE (STORE,CLS,GDGID,GDCODE,
        ASTART,AFINISH,CYCLE,CSTART,CFINISH,CSPEC,
        OCRTIME,BILLNUM,PSETTLENO,BILLLINE,QTY,FIXRATIO,GFTRATIO,FLAG,HASCOND,EXPROM,QPC,
        DLTPRICEPROM, PRIORITY,PREC,ROUNDTYPE)
    SELECT  @PISTOREGID,@PICLS,@PIGDGID,@PIGDCODE,
        @PIASTART,@PIAFINISH,@PICYCLE,@PICSTART,@PICFINISH,@PICSPEC,
        @VOCRTIME,@PINUM,@PIPSETTLENO,@PILINE,QTY,@PIFIXRATIO,@PIGFTRATIO,FLAG,@PIHASCOND,@PExprom, ISNULL(@VQPC, 1),
        @VDLTPRICEPROM, @PRIORITY,PREC,ROUNDTYPE
    FROM PROMGOODS
    WHERE NUM = @PINUM AND CLS = @PICLS AND LINE = @PILINE AND FLAG = @PIFLAG
    --END

  if @PIGDGID <> -1
  BEGIN
    DECLARE C CURSOR FOR
      SELECT CODE
        FROM GDINPUT
        WHERE GID = @PIGDGID AND CODE <> @PIGDCODE
          AND QPCSTR = @VIQPCSTR AND LEN(CODE) <= 13
    OPEN C
    FETCH NEXT FROM C INTO @CODE
    WHILE @@fetch_status = 0
    BEGIN
        INSERT INTO PROMOTE (STORE,CLS,GDGID,GDCODE,
          ASTART,AFINISH,CYCLE,CSTART,CFINISH,CSPEC,
          OCRTIME,BILLNUM,PSETTLENO,BILLLINE,QTY,FIXRATIO,GFTRATIO,FLAG,HASCOND,QPC,
          DLTPRICEPROM,PRIORITY,PREC,ROUNDTYPE)
        SELECT  @PISTOREGID,@PICLS,@PIGDGID,@CODE,
          @PIASTART,@PIAFINISH,@PICYCLE,@PICSTART,@PICFINISH,@PICSPEC,
            @VOCRTIME,@PINUM,@PIPSETTLENO,@PILINE,QTY,@PIFIXRATIO,@PIGFTRATIO,FLAG,@PIHASCOND,@VQPC,
            @VDLTPRICEPROM, @PRIORITY,PREC,ROUNDTYPE
        FROM PROMGOODS
        WHERE NUM = @PINUM AND CLS = @PICLS AND LINE = @PILINE AND FLAG = @PIFLAG

      FETCH NEXT FROM C INTO @CODE
    END
    CLOSE C
    DEALLOCATE C
  end

  RETURN(0)
END

GO
