SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ALCDIFF_CHECK_401TO400]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS  CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)				-- RETURN ERROR FROM 400
AS
BEGIN
	DECLARE
	  @EMPGID INT, 		@RE INT,
	  @MSG1 VARCHAR(255)

	SELECT @EMPGID = GID FROM EMPLOYEE(NOLOCK) WHERE
	CODE = SUBSTRING(@OPER, CHARINDEX('[',@OPER) + 1, LEN(@OPER) - CHARINDEX('[',@OPER) - 1)
	AND NAME = SUBSTRING(@OPER, 1, CHARINDEX('[',@OPER) - 1)

	UPDATE ALCDIFF SET
	  STAT = 400, CHKDATE = GETDATE(), CHECKER = @EMPGID
	WHERE NUM = @NUM

	EXEC ALCDIFFADDLOG @NUM, 400, '总部批准', @OPER

	IF EXISTS(SELECT 1 FROM ALCDIFF(NOLOCK) WHERE NUM = @NUM AND GENSTAT = 1)
	BEGIN
	  EXEC @RE = ALCDIFFAUTOGENSTKOUTBCK @NUM, '1', @MSG OUTPUT
	  IF @RE <> 0
	  BEGIN
	  	SET @MSG = '单据：' + @NUM + '总部批准失败' + CHAR(10) + CHAR(13) + @MSG
	  	RETURN @RE
	  END
	  EXEC @RE = ALCDIFFAUTOGENSTKOUT @NUM, '1', @MSG1 OUTPUT
	  SET @MSG = @MSG + CHAR(10) + CHAR(13) + @MSG1
	  IF @RE <> 0
	  BEGIN
	  	SET @MSG = '单据：' + @NUM + '总部批准失败' + CHAR(10) + CHAR(13) + @MSG
	  	RETURN @RE
	  END
	END
	ELSE
	BEGIN
	  EXEC @RE = ALCDIFFAUTOGENSTKOUTBCK @NUM, '0', @MSG OUTPUT
	  IF @RE <> 0
	  BEGIN
	  	SET @MSG = '单据：' + @NUM + '总部批准失败' + CHAR(10) + CHAR(13) + @MSG
	  	RETURN @RE
	  END
	  EXEC @RE = ALCDIFFAUTOGENSTKOUT @NUM, '0', @MSG OUTPUT
	  SET @MSG = @MSG + CHAR(10) + CHAR(13) + @MSG1
	  IF @RE <> 0
	  BEGIN
	  	SET @MSG = '单据：' + @NUM + '总部批准失败' + CHAR(10) + CHAR(13) + @MSG
	  	RETURN @RE
	  END
	END
	IF EXISTS(SELECT 1 FROM HDOPTION WHERE MODULENO = 624 AND OPTIONCAPTION = 'SENDONCHECK'
	 	AND OPTIONVALUE = '1') AND EXISTS(SELECT 1 FROM HDOPTION WHERE MODULENO = 0
	 	AND OPTIONCAPTION = 'RUNMODE' AND OPTIONVALUE = 'KD') --2006.10.30 added by zhanglong, Q8102, 配货差异单支持便利模式
	BEGIN
		EXEC @RE = ALCDIFFSND @NUM, @OPER, '0', 0, @MSG1 OUTPUT
		SET @MSG = @MSG + CHAR(10) + CHAR(13) + @MSG1
		IF @RE <> 0
		BEGIN
			SET @MSG = '单据：' + @NUM + '总部批准失败' + CHAR(10) + CHAR(13) + @MSG
			RETURN @RE
		END
	END

	SET @MSG = '单据：' + @NUM + '总部批准成功' + CHAR(10) + CHAR(13) + @MSG

	RETURN 0
END
GO
