SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PS3_GETBRANDCODE]
(
  @NEWCODE VARCHAR(10) OUTPUT,
  @poErrMsg VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE
    @MAXCODE VARCHAR(10),
    @TCODE VARCHAR(10),
    @RET_STATUS INT

  SELECT @MAXCODE = ISNULL(MAX(CODE), '100000') FROM BRAND(NOLOCK)
  EXEC @RET_STATUS = NEXTBN @MAXCODE, @TCODE OUTPUT
  IF @RET_STATUS <> 0
  BEGIN
    SET @poErrMsg = '计算品牌代码出错'
    RETURN 1
  END
  SELECT @NEWCODE = @TCODE

  RETURN 0
END
GO
