SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[TK_TOKENINFOSND] (
	@RCV	INT
)
AS
BEGIN
	DECLARE @USERGID INT
	SELECT @USERGID = USERGID FROM SYSTEM(NOLOCK)
	
	DELETE FROM TK_NTOKENINFO WHERE TYPE = 0 AND RCV = @RCV
	
	INSERT INTO TK_NTOKENINFO(ID, SERIALNO, ATYPE, SECUREKEY, INITTIME, 
		DIFFERENCE, INITTOKENTIME, STATE, LASTTIME, ADTIME, HDDIFF, 
		ERRTIMES, LASTAUTHTIME, TOTALAUTH, TOTALSUCC, SUCCTOKEN, SRC,
		SNDTIME, RCV, RCVTIME, TYPE, NSTAT, NNOTE)
	SELECT ID, SERIALNO, TYPE, SECUREKEY, INITTIME, DIFFERENCE, INITTOKENTIME,
		STATE, LASTTIME, ADTIME, HDDIFF, ERRTIMES, LASTAUTHTIME, TOTALAUTH, 
		TOTALSUCC, SUCCTOKEN, @USERGID, GETDATE(), @RCV, NULL, 0, 0, NULL
	FROM TK_TOKENINFO
	
	RETURN 0
END
GO
