SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CHKVDRBCKDMD_500TO300]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS	 CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
	UPDATE VdrBckDmd SET
		STAT = 300,
		CACLDATE = GETDATE(),
		CANCELER = @OPER,
		LSTUPDTIME = GETDATE()
	WHERE NUM = @NUM
	EXEC VDRBCKDMDADDLOG @NUM, 300, '', @OPER
	RETURN 0
END
GO
