SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[VDRPAYDLT]
(
	@CLS	  CHAR(20),
	@NUM	  CHAR(14),
	@OPER	  CHAR(30),
	@TOSTAT		INT,
	@MSG	VARCHAR(255)	OUTPUT
)
AS
BEGIN
	DECLARE @VNEGNUM	CHAR(14)
	DECLARE @VRET		INT
	DECLARE @VSTAT		INT
	DECLARE @ENDSTAT	INT

	SELECT @VSTAT = STAT FROM VDRPAY WHERE NUM = @NUM
	IF @VSTAT <> 500
	BEGIN
		SELECT @MSG = '状态不是已完成，不许作废'
		RETURN(1);
	END

	EXEC @VRET = GENVDRPAYNEG @NUM, @OPER, @VNEGNUM OUTPUT, @MSG OUTPUT
	IF @VRET <> 0 RETURN @VRET
	EXEC @VRET = LOADVDRPAYDTL @VNEGNUM, -1, @OPER, @MSG OUTPUT
	IF @VRET <> 0 RETURN @VRET
	SELECT @ENDSTAT = @VSTAT + 20
	EXEC VDRPAYADDLOG '', @VNEGNUM, @ENDSTAT, @OPER
	UPDATE VDRPAY SET 
		STAT = STAT + 10, 
		LSTUPDTIME = GETDATE()
	WHERE NUM = @NUM
	SELECT @ENDSTAT = @VSTAT + 10
	EXEC VDRPAYADDLOG '', @NUM, @ENDSTAT, @OPER
	
	IF @CLS IS NULL OR @CLS = ''
	BEGIN
	  EXEC @VRET = VDRPAYSEND @CLS, @NUM, @OPER, 0, @MSG OUTPUT
	  IF @VRET <= 0 SET @VRET = 0
	END
	
	RETURN @VRET
END
GO
