SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[INSSUBWRHBATCH_2]
  @GDGID INT,
  @SUBWRH INT,
  @CODE CHAR(10) OUTPUT,
  @LSTINPRC MONEY OUTPUT,
  @ERRMSG VARCHAR(200) = '' OUTPUT
AS
BEGIN
  /*
  输入: @SUBWRH,货位GID
  改变数据: 新增一个货位
    GID=@SUBWRH,
    CODE的格式为“YYMMDDXXXX”. 前6位通过当前日期得到，后4位流水. NAME中的内容与CODE相同 
  */
  DECLARE @WRH INT
  SELECT @WRH = 1
  DECLARE @DATESTR CHAR(6), @STRING CHAR(20), @MAXSUBWRH CHAR(10),@USERCODE CHAR(4)

  SELECT @CODE = ''
  SELECT @CODE = ISNULL(CODE,''),@LSTINPRC = INPRC FROM SUBWRH WHERE GID = @SUBWRH AND @GDGID = @GDGID

  IF ISNULL(@CODE,'') = ''
  BEGIN
    SELECT @STRING = CONVERT(CHAR(10), GETDATE(), 102)    
    SELECT @DATESTR = SUBSTRING(@STRING,3,2) + SUBSTRING(@STRING,6,2) +	SUBSTRING(@STRING,9,2)
    --增加门店代码
    SELECT @USERCODE = USERCODE FROM SYSTEM(NOLOCK)
    SELECT @DATESTR = SUBSTRING(@USERCODE, 1, 4) + @DATESTR
    SELECT @MAXSUBWRH = ISNULL(
      (SELECT MAX(CODE) FROM SUBWRH WHERE CODE LIKE @DATESTR+'%'), 
      @DATESTR+'0000')
    EXECUTE NEXTBN @MAXSUBWRH, @MAXSUBWRH OUTPUT
  END
  IF NOT EXISTS(SELECT 1 FROM SUBWRH WHERE GID = @SUBWRH)
  BEGIN
	/*按传入的价格记录*/
	INSERT INTO SUBWRH (GID,GDGID, CODE, NAME, WRH,INPRC)
		VALUES (@SUBWRH,@GDGID, @MAXSUBWRH, @MAXSUBWRH, @WRH,@LSTINPRC)
	SELECT @CODE = @MAXSUBWRH


  END
  ELSE
  BEGIN
	--此时，找到了最后一次进价，但没有批次，这种记录是由调价单生成
	IF ISNULL(@CODE ,'') = ''
	BEGIN
		UPDATE SUBWRH SET CODE = @MAXSUBWRH, NAME = @MAXSUBWRH WHERE GID = @SUBWRH AND WRH = @WRH
		SELECT @CODE = @MAXSUBWRH
	END
  END
 
  RETURN 0
END
GO
