SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRCSCHEMEDTLSND]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS	 CHAR(10),
  @TOSTORE INT,
  @MSG VARCHAR(255) OUTPUT
) with encryption
AS
BEGIN
  DECLARE @ID INT
  DECLARE @SRC INT

  EXEC GETNETBILLID @ID OUTPUT
  SELECT @SRC = USERGID FROM SYSTEM(NOLOCK)
  IF @SRC = @TOSTORE
    RETURN(0)
  IF @TOSTORE < 0
    BEGIN
    --2006.5.31, ShenMin, Q6820, 改进调价方案的发送方式
      DELETE NPRCSCHEMEDTL FROM STOREPRCSCHEME
        WHERE NPRCSCHEMEDTL.CODE = @NUM
          AND NPRCSCHEMEDTL.RCV <> @SRC
         -- AND NPRCSCHEMEDTL.PRCCLS = STOREPRCSCHEME.CLS
      INSERT INTO NPRCSCHEMEDTL (ID, CODE, GDGID, GDQPCSTR, PRCCLS, CTRMODE, SRC, RCV, TYPE, NSTAT, SNDTIME)
        SELECT @ID, A.CODE, A.GDGID, A.GDQPCSTR, A.PRCCLS, A.CTRMODE, @SRC, B.STOREGID, 0, 0, GETDATE()
          FROM PRCSCHEMEDTL A(NOLOCK), STOREPRCSCHEME B(NOLOCK), PRCSCHEME C(NOLOCK)
            WHERE A.CODE = @NUM AND A.CODE = B.CODE AND A.CODE = C.CODE AND A.PRCCLS = B.CLS -- AND B.CLS = @CLS
                  AND B.STOREGID <> @SRC
    END
  ELSE
    BEGIN
    --2006.5.31, ShenMin, Q6820, 改进调价方案的发送方式
      DELETE NPRCSCHEMEDTL FROM STOREPRCSCHEME
        WHERE NPRCSCHEMEDTL.CODE = @NUM
          AND NPRCSCHEMEDTL.RCV = @TOSTORE
        --  AND NPRCSCHEMEDTL.PRCCLS = STOREPRCSCHEME.CLS
      INSERT INTO NPRCSCHEMEDTL (ID, CODE, GDGID, GDQPCSTR, PRCCLS, CTRMODE, SRC, RCV, TYPE, NSTAT, SNDTIME)
        SELECT @ID, A.CODE, A.GDGID, A.GDQPCSTR, A.PRCCLS, A.CTRMODE, @SRC, B.STOREGID, 0, 0, GETDATE()
          FROM PRCSCHEMEDTL A(NOLOCK), STOREPRCSCHEME B(NOLOCK), PRCSCHEME C(NOLOCK)
            WHERE A.CODE = @NUM AND A.CODE = B.CODE AND A.CODE = C.CODE AND A.PRCCLS = B.CLS
                 AND B.STOREGID = @TOSTORE
    END
  IF @@ERROR <> 0
  BEGIN
    SET @MSG = '发送调价方案'+@NUM+'失败'
    RETURN(1)
  END
  UPDATE PRCSCHEME SET SNDDATE = GETDATE() WHERE CODE = @NUM
  RETURN(0)
END
GO
