SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[LOGNETOBJSEQ]
(
  @GRPID INT,
  @SRC INT,
  @ID INT,
  @RCV INT,
  @GRPIDFLAG SMALLINT = 0
)
AS
BEGIN
  DECLARE @SEQID INT
  if exists(select 1 from dtspool(nolock) where storegid = @rcv)
  begin
    EXEC @SEQID = SEQNEXTVALUE 'NETOBJSEQ'

    INSERT INTO NETOBJSEQ ( DATATYPE, SENDTIME, DATASOURCETABLE, SRC, ID, NOID, GRPIDFLAG, RCVGID)
    SELECT  ANAME, GETDATE(), SECTION, @SRC, @ID, @GRPID, @GRPIDFLAG, @RCV
      FROM NSQLITEM
    WHERE oid = @GRPID
  end

  RETURN 0
END
GO
