SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[STOREPRCSCHEMESND]
(
  @TOSTORE INT,
  @OPER CHAR(30),
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE @ID INT
  DECLARE @SRC INT
  SELECT @SRC = USERGID FROM SYSTEM(NOLOCK)
  IF @SRC = @TOSTORE
    RETURN(0)
  IF OBJECT_ID('TEMPDB..#PRCTYPE') IS NOT NULL DROP TABLE #PRCTYPE
  CREATE TABLE #PRCTYPE(TNAME VARCHAR(8))
  INSERT INTO #PRCTYPE VALUES ('核算售价')
  INSERT INTO #PRCTYPE VALUES ('会员价')
  INSERT INTO #PRCTYPE VALUES ('批发价')
  INSERT INTO #PRCTYPE VALUES ('最低售价')
  INSERT INTO #PRCTYPE VALUES ('最高售价')
  INSERT INTO #PRCTYPE VALUES ('量贩价')
  INSERT INTO #PRCTYPE VALUES ('定货价')

  EXEC GETNETBILLID @ID OUTPUT
  IF @TOSTORE < 0
    begin
      DELETE FROM NSTOREPRCSCHEME WHERE TYPE = 0 AND NSTAT = 0 AND STOREGID <> @SRC --2006.5.31, ShenMin, Q6820, 改进调价方案的发送方式
      INSERT INTO NSTOREPRCSCHEME (ID,STOREGID, CLS, CODE, SRC, SNDTIME, RCV, TYPE, NSTAT)
        SELECT @ID, B.GID, C.TNAME, ISNULL(A.CODE, '-'), @SRC, GETDATE(), B.GID, 0, 0
          FROM STOREPRCSCHEME A(NOLOCK), STORE B(NOLOCK), #PRCTYPE C
            WHERE A.STOREGID =* B.GID AND A.CLS =* C.TNAME AND B.GID <> @SRC
    end
  ELSE
    BEGIN
      DELETE FROM NSTOREPRCSCHEME WHERE TYPE = 0 AND NSTAT = 0 AND STOREGID = @TOSTORE --2006.5.31, ShenMin, Q6820, 改进调价方案的发送方式
      INSERT INTO NSTOREPRCSCHEME (ID,STOREGID, CLS, CODE, SRC, SNDTIME, RCV, TYPE, NSTAT)
        SELECT @ID, B.GID, C.TNAME, ISNULL(A.CODE, '-'), @SRC, GETDATE(), B.GID, 0, 0
          FROM STOREPRCSCHEME A(NOLOCK), STORE B(NOLOCK), #PRCTYPE C
            WHERE A.STOREGID =* B.GID AND A.CLS =* C.TNAME AND B.GID = @TOSTORE
    END
  IF @@ERROR <> 0
  BEGIN
    SET @MSG = '发送调价方案对照关系失败'
    RETURN(1)
  END
  IF @TOSTORE < 0
    UPDATE STOREPRCSCHEME SET SNDDATE = GETDATE()
  ELSE
    UPDATE STOREPRCSCHEME SET SNDDATE = GETDATE() WHERE STOREGID = @TOSTORE
  RETURN(0)
END
GO
