SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[POLYLTDADJ_ON_MODIFY]
(
  @NUM CHAR(14),            --单号
  @TOSTAT INT,              --目标状态
  @OPER VARCHAR(30),        --操作人
  @MSG VARCHAR(255) OUTPUT  --错误信息
)
AS
BEGIN
  DECLARE
    @VRET INT

  IF @TOSTAT <> 0
  BEGIN
    --状态调度
    IF @TOSTAT = 100
    BEGIN
      EXEC @VRET = POLYLTDADJ_MODIFYTO100 @NUM, @TOSTAT, @OPER, @MSG OUTPUT;
      RETURN(@VRET)
    END
  END
  ELSE BEGIN
    UPDATE POLYLTDADJ SET LSTUPDOPER = @OPER, LSTUPDTIME = GETDATE() WHERE NUM = @NUM
    EXEC POLYLTDADJ_ADD_LOG @NUM, @TOSTAT, '修改', @OPER
    RETURN(0)
  END;
END
GO
