SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SVIGETTAX](
  @TOTAL MONEY,
  @TAXRATE MONEY,
  @TAX MONEY OUTPUT	
)
AS
BEGIN
  DECLARE @AMONT MONEY
  DECLARE @DCMONT decimal(24,2)
  SELECT @AMONT = @TOTAL / ( 1 + @TAXRATE / 100)
  SELECT @DCMONT = CAST(@AMONT AS decimal(24,2))
  SELECT @AMONT = CAST(@DCMONT AS MONEY)
  SELECT @TAX = @TOTAL - @AMONT
  RETURN 0
END
GO
