SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[GoodsAppApplyNew]
(
  @NUM CHAR(14),
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
	DECLARE @STAT INT, @I INT, @SSQL VARCHAR(255), @USERGID INT,
		@USERPROPERTY INT, @APPMODE VARCHAR(20), @GOODSCLS VARCHAR(20),
		@SRC INT, @FILLER INT, @FILLERCODE VARCHAR(20)
	DECLARE @GDGID VARCHAR(30), @GDCODE VARCHAR(20), @LINE INT, @GDNAME VARCHAR(30),
		@WRH INT, @RATFLAG INT, @MEANO INT, @MEANAME VARCHAR(20),
                @CODE VARCHAR(20), @CODE1 VARCHAR(20), @CODE2 VARCHAR(20), @STARTCODE VARCHAR(20),
                @AUTOGENGDCODE INT, @GENCUSTOMFLOWCODE INT
      DECLARE @ErrorMsg varchar(128)
	SET @RATFLAG = 0
	SELECT @USERGID = USERGID FROM SYSTEM
	SELECT @USERPROPERTY = PROPERTY FROM STORE WHERE GID = @USERGID
	SET @FILLERCODE = RTRIM(SUBSTRING(SUSER_SNAME(), CHARINDEX('_', SUSER_SNAME()) + 1, 20))
	SELECT @FILLER = GID FROM EMPLOYEE WHERE CODE LIKE @FILLERCODE
	IF @FILLER IS NULL SET @FILLER = 1 --DEBUG
	SELECT @STAT = STAT, @APPMODE = RTRIM(APPMODE), @SRC = SRC, @GOODSCLS = RTRIM(GOODSCLS)
		FROM GOODSAPP WHERE NUM = @NUM
	IF @APPMODE<>'新增'
	BEGIN
		SET @MSG = '单据更新模式不是新增'
		RAISERROR('单据更新模式不是新增',16,1)
		RETURN(-1)
	END

	EXEC OPTREADINT 563, 'AUTOGENGDCODE', 1, @AUTOGENGDCODE OUTPUT
	IF @AUTOGENGDCODE = 0
	BEGIN
	  IF EXISTS (SELECT 1 FROM GOODSAPPDTL WHERE NUM = @NUM AND RATFLAG = 1 AND RTRIM(ISNULL(CODE,'')) = '')
	  BEGIN
		  SET @MSG = '单据中有新商品的代码为空，不能继续'
		  RAISERROR('单据中有新商品的代码为空，不能继续',16,1)
		  RETURN(-1)
	  END
	END

	--IF NOT EXISTS(SELECT 1 FROM GOODSAPPLAC WHERE NUM = @NUM AND STOREGID = @USERGID)
    	IF @USERPROPERTY & 16 <> 16
    	BEGIN
     	   SET @MSG = '只有总部才能新增'
     	   RAISERROR('只有总部才能新增',16,1)
     	   RETURN(0)
    	END

	DECLARE C_C CURSOR FOR
		SELECT LINE,RATFLAG, SORT FROM GOODSAPPDTL WHERE NUM = @NUM
	OPEN C_C
	FETCH NEXT FROM C_C INTO @LINE,@RATFLAG, @CODE
	WHILE @@FETCH_STATUS=0
	BEGIN
        IF @RATFLAG = 1
        BEGIN
	       	EXEC GETGDGID @GDGID OUTPUT
	       	--SELECT @WRH = WRH FROM GOODSAPPDTL WHERE NUM = @NUM AND LINE = @LINE
	       	--IF @USERGID <> (SELECT SRC FROM GOODSAPP WHERE NUM = @NUM)
			--	IF @GOODSCLS <> '促销赠品'
			--		SET @WRH = 1

			--EXEC GETGDCODE @GDCODE OUTPUT

			--根据总部生成商品码规则生成CODE  by jinlei
			IF @AUTOGENGDCODE = 0
			BEGIN
			  SELECT @CODE = CODE FROM GOODSAPPDTL WHERE NUM = @NUM AND LINE = @LINE
		    END ELSE BEGIN

			  EXEC OPTREADSTR 563, 'STARTCODE', '', @STARTCODE OUTPUT
			  IF @STARTCODE = ''
			  BEGIN
			    SET @CODE = LTRIM(RTRIM(@CODE))
			    SET @CODE = SUBSTRING(@CODE, 1, 2)
			  END ELSE SET @CODE = LTRIM(RTRIM(@STARTCODE))

			  SET @CODE1 = @CODE
			  SET @CODE2 = @CODE

			  EXEC OPTREADINT 10, 'GENCUSTOMFLOWCODE', 0, @GENCUSTOMFLOWCODE OUTPUT

			  IF @GENCUSTOMFLOWCODE = 1
			  BEGIN
			    EXEC GENFLOWCODEEXMIN @CODE1, 'GDINPUT', @CODE1 OUTPUT, @MSG OUTPUT
			    EXEC GENFLOWCODEEXMIN @CODE2, 'GOODSH', @CODE2 OUTPUT, @MSG OUTPUT
			  END ELSE BEGIN
			    EXEC GENFLOWCODEEX @CODE1 OUTPUT, 'GDINPUT'
			    EXEC GENFLOWCODEEX @CODE2 OUTPUT, 'GOODSH'
			  END
			  IF @CODE1 > @CODE2 SET @CODE = @CODE1
		      ELSE SET @CODE = @CODE2
			  EXEC CHECKBARCODEEX @CODE OUTPUT

			END

			IF EXISTS( SELECT 1 FROM GDINPUT WHERE CODE = @CODE)
			BEGIN
				CLOSE C_C
				DEALLOCATE C_C

                        SELECT @gdName = RTRIM(Name) FROM Goods WHERE Code = @code
                        SET @ErrorMsg = '第 ' + CONVERT(VARCHAR(50), @Line) + ' 行商品 ' + @GDName + '[' + @Code + '] 的代码已经存在，不能插入。'
				RAISERROR(@ErrorMsg, 16, 1)
				RETURN(-1)
			END

			INSERT INTO GOODS (GID, CODE, NAME, SPEC, SORT, RTLPRC, INPRC,
			TAXRATE, PRCTYPE, SALE, LWTRTLPRC, WHSPRC, ACNT, PAYTODTL, MUNIT,
			QPC, TM, MANUFACTOR, MCODE, GPR, VALIDPERIOD,
			CHKVD, PAYRATE, BILLTO, DXPRC, MEMO,
			PROMOTE, LSTINPRC, GFT, AUTOORD, ORIGIN, GRADE,
			MBRPRC, SALETAX, PSR, F1, F2, F3, ALC, CODE2,
			MKTINPRC, MKTRTLPRC, CNTINPRC, ALCQTY, BRAND, BQtyPrc, KEEPTYPE,
			NENDTIME, NCANPAY, SSSTART, SSEND, SEASON, HQCONTROL, ORDCYCLE, ALCCTR, ISDISP,
			--NON FIELD
			ISPKG, LOWINV, HIGHINV, OLDINVPRC, SRC, INVPRC, SNDTIME,
			LSTUPDTIME, ISLTD, FILLER, MODIFIER, ISBIND, CREATEDATE,
			--SPEC FIELD
			WRH
			)
			SELECT @GDGID, @CODE, NAME, SPEC, SORT, RTLPRC, INPRC, -- CODE -> @CODE by jinlei
			TAXRATE, PRCTYPE, SALE, LWTRTLPRC, WHSPRC, ACNT, PAYTODTL, MUNIT,
			QPC, TM, MANUFACTOR, MCODE, GPR, VALIDPERIOD,
			CHKVD, PAYRATE, BILLTO, DXPRC, MEMO,
			PROMOTE, LSTINPRC, GFT, AUTOORD, ORIGIN, GRADE,
			MBRPRC, SALETAX, PSR, F1, F2, F3, ALC, CODE2,
			MKTINPRC, MKTRTLPRC, CNTINPRC, ALCQTY, BRAND, BQtyPrc, KEEPTYPE,
			NENDTIME, NCANPAY, SSSTART, SSEND, SEASON, HQCONTROL, ORDCYCLE, ALCCTR, ISDISP,
			0, 0, 0, INPRC, @USERGID, INPRC, NULL,
			GETDATE(), 0, @FILLER, @FILLER, 0, GETDATE(),
			WRH
			FROM GOODSAPPDTL WHERE NUM = @NUM AND LINE = @LINE

			--将新生成的CODE回写GOODSAPPDTL表  by jinlei
			IF @AUTOGENGDCODE = 1
			  UPDATE GOODSAPPDTL SET CODE = @CODE WHERE NUM = @NUM AND LINE = @LINE

			IF (SELECT RTRIM(CODE2) FROM GOODSAPPDTL WHERE NUM = @NUM AND LINE = @LINE)<> ''
	        	                  IF NOT EXISTS( SELECT 1 FROM GDINPUT WHERE CODE = (SELECT CODE2 FROM GOODSAPPDTL WHERE NUM = @NUM AND LINE = @LINE))
			  BEGIN
				INSERT INTO GDINPUT (CODE, GID, CODETYPE)
				SELECT CODE2  , @GDGID, 0 FROM GOODSAPPDTL WHERE NUM = @NUM AND LINE = @LINE
			  END
			  ELSE
			  BEGIN
				CLOSE C_C
				DEALLOCATE C_C
                        SELECT @gdName = RTRIM(Name) FROM Goods WHERE Code = @code
                        SET @ErrorMsg = '第 ' + CONVERT(VARCHAR(50), @Line) + ' 行的商品 ' + @GDName + '[' + @Code + '] 的第二代码在总部已经存在。'
                        RAISERROR(@ErrorMsg, 16, 1)
				RETURN(-1)
			  END

			SELECT @MEANAME = RTRIM(MUNIT) FROM GOODSAPPDTL WHERE NUM = @NUM AND LINE = @LINE
			IF (NOT EXISTS(SELECT 1 FROM MEASUREUNIT WHERE NAME LIKE @MEANAME )) AND (@MEANAME<>'')
			BEGIN
				SELECT @MEANO = MAX(NO) + 1 FROM MEASUREUNIT
				INSERT INTO MEASUREUNIT(NO,NAME) VALUES(@MEANO, @MEANAME)
			END

			--WRITE BACK 2004.12.01 Fanduoyi
			UPDATE GOODSAPPDTL SET GID = @GDGID WHERE NUM = @NUM AND LINE = @LINE  --, CODE = @GDCODE
			/*IF @USERPROPERTY & 16 = 16
			BEGIN
				INSERT INTO GDSTORE ()
				SELECT ... FROM GOODSAPPDTL DTL, GOODSAPPLAC LAC WHERE NUM = @NUM AND LAC.NUM = DTL.NUM
			END*/
		END
		FETCH NEXT FROM C_C INTO @LINE, @RATFLAG, @CODE
		IF @@ERROR <> 0
		BEGIN
            	SET @MSG = @MSG + '插入商品时发生错误。'
	        	CLOSE C_C
        		DEALLOCATE C_C
			RAISERROR('插入商品时发生错误。',16,1)
			RETURN(-1)
		END
	END
	CLOSE C_C
	DEALLOCATE C_C
	--EXEC @VRET = GoodsAppApply @NUM, @MSG OUTPUT
END
GO
