SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ALCDIFFRCV]
(
  @BILL_ID INT,
  @SRC_ID INT,
  @OPER CHAR(30),
  @MSG VARCHAR(255) OUTPUT
) --WITH ENCRYPTION		-- RETURN ERROR FROM 500
AS
BEGIN
	DECLARE
		@CUR_SETTLENO INT,              @NET_NUM CHAR(14),
		@RCV_GID INT,			@NET_STAT SMALLINT,
		@NET_TYPE SMALLINT,		@RE INT,
		@MSG1 VARCHAR(255),             @FILLER INT,
		@REQOPER INT,                   @CHECKER INT,
		@CANCELER INT

	SELECT @CUR_SETTLENO = MAX(NO) FROM MONTHSETTLE(NOLOCK)

	SELECT  @RCV_GID = RCV, @NET_STAT = STAT, @NET_TYPE = TYPE, @NET_NUM = NUM
	FROM NALCDIFF(NOLOCK) WHERE ID = @BILL_ID AND SRC = @SRC_ID
	IF @@ROWCOUNT = 0 OR @NET_NUM IS NULL
	BEGIN
		SET @MSG = '[接收]单据' +  @NET_NUM + '不存在'
		RETURN 501
	END

	IF EXISTS(SELECT 1 FROM ALCDIFF(NOLOCK) WHERE NUM = @NET_NUM AND STAT = @NET_STAT)
	BEGIN
		SET @MSG = '[接收]单据' +  @NET_NUM + '已经被接收'
		RETURN 502
	END

	IF (SELECT MAX(USERGID) FROM SYSTEM(NOLOCK)) <>  @RCV_GID
	BEGIN
		SET @MSG = '[接收]单据' +  @NET_NUM + '接收单位不是本单位'
		RETURN 503
	END

	IF @NET_TYPE <> 1
	BEGIN
		SET @MSG = '[接收]单据' +  @NET_NUM + '不在接收缓冲区中'
		RETURN 504
	END

	IF NOT EXISTS(SELECT 1 FROM EMPLOYEEH(NOLOCK) WHERE GID = @FILLER)
        BEGIN
          IF EXISTS(SELECT LGID FROM EMPXLATE(NOLOCK) WHERE NGID = @FILLER)
            SELECT @FILLER = LGID FROM EMPXLATE(NOLOCK) WHERE NGID = @FILLER
          ELSE
          BEGIN
            UPDATE NALCDIFF SET NSTAT = 1, NNOTE = '本地找不到填单人对应的员工(对照表中也不存在)'
            WHERE SRC = @SRC_ID AND ID = @BILL_ID
            SET @MSG = '本地找不到填单人对应的员工(对照表中也不存在)'
            RETURN 507
          END
        END

        IF NOT EXISTS(SELECT 1 FROM EMPLOYEEH(NOLOCK) WHERE GID = @REQOPER)
        BEGIN
          IF EXISTS(SELECT LGID FROM EMPXLATE(NOLOCK) WHERE NGID = @REQOPER)
            SELECT @REQOPER = LGID FROM EMPXLATE(NOLOCK) WHERE NGID = @REQOPER
          ELSE
          BEGIN
            UPDATE NALCDIFF SET NSTAT = 1, NNOTE = '本地找不到申请人对应的员工(对照表中也不存在)'
            WHERE SRC = @SRC_ID AND ID = @BILL_ID
            SET @MSG = '本地找不到申请人对应的员工(对照表中也不存在)'
            RETURN 508
          END
        END

        IF NOT EXISTS(SELECT 1 FROM EMPLOYEEH(NOLOCK) WHERE GID = @CHECKER)
        BEGIN
          IF EXISTS(SELECT LGID FROM EMPXLATE(NOLOCK) WHERE NGID = @CHECKER)
            SELECT @CHECKER = LGID FROM EMPXLATE(NOLOCK) WHERE NGID = @CHECKER
          ELSE
          BEGIN
            UPDATE NALCDIFF SET NSTAT = 1, NNOTE = '本地找不到审核人对应的员工(对照表中也不存在)'
            WHERE SRC = @SRC_ID AND ID = @BILL_ID
            SET @MSG = '本地找不到审核人对应的员工(对照表中也不存在)'
            RETURN 509
          END
        END

        IF NOT EXISTS(SELECT 1 FROM EMPLOYEEH(NOLOCK) WHERE GID = @CANCELER)
        BEGIN
          IF EXISTS(SELECT LGID FROM EMPXLATE(NOLOCK) WHERE NGID = @CANCELER)
            SELECT @CANCELER = LGID FROM EMPXLATE(NOLOCK) WHERE NGID = @CANCELER
          ELSE
          BEGIN
            UPDATE NALCDIFF SET NSTAT = 1, NNOTE = '本地找不到作废人对应的员工(对照表中也不存在)'
            WHERE SRC = @SRC_ID AND ID = @BILL_ID
            SET @MSG = '本地找不到作废人对应的员工(对照表中也不存在)'
            RETURN 510
          END
        END

	DELETE FROM ALCDIFF WHERE NUM = @NET_NUM
	DELETE FROM ALCDIFFDTL WHERE NUM = @NET_NUM

	INSERT INTO ALCDIFF(NUM, SETTLENO, CLIENT, BILLTO, WRH, FILLER, FILDATE,
          REQOPER, REQDATE, CHECKER, CHKDATE, CANCELER, CACLDATE, LSTUPDTIME, STAT, NOTE,
          RECCNT, SNDTIME, PRNTIME, CAUSE, ATTITUDE, ALCFROM, GENNOTE, GENSTAT)
        SELECT NUM, @CUR_SETTLENO, CLIENT, BILLTO, WRH, @FILLER, FILDATE,
          @REQOPER, REQDATE, @CHECKER, CHKDATE, @CANCELER, CACLDATE, GETDATE(), STAT, NOTE,
          RECCNT, SNDTIME, PRNTIME, CAUSE, ATTITUDE, ALCFROM, GENNOTE, GENSTAT
        FROM NALCDIFF(NOLOCK)
        WHERE SRC = @SRC_ID AND ID = @BILL_ID

	IF @@ERROR <> 0
	BEGIN
		SET @MSG = '[接收]接收' + @NET_NUM + '单据失败'
		RETURN 505
	END

	INSERT INTO ALCDIFFDTL(NUM, LINE, GDGID, SRCNUM, CASES, QTY, WRH, NOTE)
        SELECT NUM, LINE, GDGID, SRCNUM, CASES, QTY, WRH, NOTE
        FROM NALCDIFFDTL(NOLOCK)
        WHERE SRC = @SRC_ID AND ID = @BILL_ID

	IF @@ERROR <> 0
	BEGIN
		SET @MSG = '[接收]接收' + @NET_NUM + '单据失败'
		RETURN 506
	END


        --RECEIVE BILL OVER
	EXEC ALCDIFFADDLOG @NET_NUM, @NET_STAT, '接收', @OPER

	--如果门店接收
	IF EXISTS(SELECT 1 FROM SYSTEM(NOLOCK) WHERE USERGID <> ZBGID)
	BEGIN
	  IF EXISTS(SELECT 1 FROM NALCDIFF(NOLOCK) WHERE SRC = @SRC_ID AND ID = @BILL_ID
	            AND GENSTAT = 1)
	  BEGIN
	    EXEC @RE = ALCDIFFAUTOGENSTKINBCK @BILL_ID, @SRC_ID, '1', @MSG OUTPUT
	    IF @RE <> 0
	    BEGIN
	    	SET @MSG = '单据：' + @NET_NUM + '接收失败' + CHAR(10) + CHAR(13) + @MSG
	    	RETURN @RE
	    END
	  END
	  ELSE
	  BEGIN
	    EXEC @RE = ALCDIFFAUTOGENSTKINBCK @BILL_ID, @SRC_ID, '0', @MSG OUTPUT
	    IF @RE <> 0
	    BEGIN
	    	SET @MSG = '单据：' + @NET_NUM + '接收失败' + CHAR(10) + CHAR(13) + @MSG
	    	RETURN @RE
	    END
	  END

	  UPDATE ALCDIFF SET STAT = 300 WHERE NUM = @NET_NUM

	  DELETE FROM NALCDIFF WHERE ID = @BILL_ID AND SRC = @SRC_ID
	  DELETE FROM NALCDIFFDTL WHERE ID = @BILL_ID AND SRC = @SRC_ID

	  EXEC @RE = ALCDIFFSND @NET_NUM, @OPER, '1', 0, @MSG1 OUTPUT
	  SET @MSG = @MSG + CHAR(10) + CHAR(13) + @MSG1
	  IF @RE <> 0
	  BEGIN
	  	SET @MSG = '单据：' + @NET_NUM + '接收失败' + CHAR(10) + CHAR(13) + @MSG
	  	RETURN @RE
	  END
	END

	DELETE FROM NALCDIFF WHERE ID = @BILL_ID AND SRC = @SRC_ID
	DELETE FROM NALCDIFFDTL WHERE ID = @BILL_ID AND SRC = @SRC_ID

	SET @MSG = '单据：' + @NET_NUM + '接收成功' + @MSG

	RETURN 0
END
GO
