SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO

CREATE PROCEDURE [dbo].[GETEXTRARIGHT](
@EMPLOYEECODE	CHAR(10),
@EXTRARIGHT	VARCHAR(255) OUTPUT
) AS
BEGIN
	DECLARE @EMPGID INT, @ARIGHT INT

	SELECT @EXTRARIGHT = REPLICATE('0', 255)

	SELECT @EMPGID = GID FROM EMPLOYEE WHERE CODE = @EMPLOYEECODE
	IF @@ROWCOUNT = 0
		RETURN(0)

	DECLARE CURSOR1 CURSOR FOR
	SELECT ARIGHT FROM EMPRIGHT WHERE EMPGID = @EMPGID
	OPEN CURSOR1
	FETCH NEXT FROM CURSOR1 INTO @ARIGHT
	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF @ARIGHT <= 255 AND @ARIGHT >= 1
			SELECT @EXTRARIGHT = STUFF(@EXTRARIGHT, @ARIGHT, 1, '1')
		FETCH NEXT FROM CURSOR1 INTO @ARIGHT
	END
	CLOSE CURSOR1
	DEALLOCATE CURSOR1

	DECLARE CURSOR1 CURSOR FOR
	SELECT EMPGRPRIGHT.ARIGHT FROM EMPLOYEERIGHT, EMPGRPRIGHT
	WHERE EMPLOYEERIGHT.EMPLOYEE = @EMPGID
	AND EMPLOYEERIGHT.EMPLOYEEGROUP = EMPGRPRIGHT.EMPGRPGID
	OPEN CURSOR1
	FETCH NEXT FROM CURSOR1 INTO @ARIGHT
	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF @ARIGHT <= 255 AND @ARIGHT >= 1
			SELECT @EXTRARIGHT = STUFF(@EXTRARIGHT, @ARIGHT, 1, '1')
		FETCH NEXT FROM CURSOR1 INTO @ARIGHT
	END
	CLOSE CURSOR1
	DEALLOCATE CURSOR1
end

GO
