SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[DmdGenStore]	
AS
BEGIN
  DECLARE @VCMD VARCHAR(2000)
  DECLARE @NUM VARCHAR(14)
  DECLARE @ST VARCHAR(50)
  DECLARE @AST VARCHAR(50)
  DECLARE @STL VARCHAR(4000)
  DECLARE @EON INT
  DECLARE DMDTMP_CA CURSOR FOR
    SELECT NUM, EON FROM DMDPRM
  SELECT @AST = RTRIM(USERNAME) + '[' + RTRIM(USERCODE) + ']*' FROM SYSTEM
  OPEN DMDTMP_CA
  FETCH NEXT FROM DMDTMP_CA INTO @NUM, @EON
  WHILE @@fetch_status = 0
  BEGIN
    IF @EON = 1
      SELECT @STL = @AST
    ELSE
      SELECT @STL = ''
    SELECT @VCMD = 'DECLARE DMDTMP_CB CURSOR FOR '
      + ' select rtrim(name) + ''['' + rtrim(code) + '']'' from DMDPRMLACDTL,store '
      + ' where storegid=gid AND NUM = ' + '''' + @NUM + ''''
    EXEC(@VCMD)
    OPEN DMDTMP_CB
    FETCH NEXT FROM DMDTMP_CB INTO @ST
    WHILE @@fetch_status = 0 
    BEGIN
      IF @STL = ''
        SELECT @STL = @ST
      ELSE
        SELECT @STL = @STL + ';' + @ST
        
      FETCH NEXT FROM DMDTMP_CB INTO @ST
    END
    CLOSE DMDTMP_CB
    DEALLOCATE DMDTMP_CB
    UPDATE DMDPRM SET EFFECTSTORE = @STL WHERE NUM = @NUM
    FETCH NEXT FROM DMDTMP_CA INTO @NUM, @EON
  END
  CLOSE DMDTMP_CA
  DEALLOCATE DMDTMP_CA
  RETURN 0
END
GO
