SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRCCSTGDADJGRP_CHECK_0TO100]
(
  @NUM	CHAR(14),
  @OPER	CHAR(30),
  @CLS	CHAR(10),
  @TOSTAT	INT,
  @MSG	VARCHAR(255) OUTPUT
)				
AS
BEGIN
	DECLARE 
	  @EMPGID INT,	@RE INT,
	  @STOREGID INT,	@GDGID INT,
	  @NEWPRC MONEY,	@STYLECODE VARCHAR(10)
	  
	SELECT @EMPGID = GID FROM EMPLOYEE(NOLOCK) WHERE 
	CODE = SUBSTRING(@OPER, CHARINDEX('[',@OPER) + 1, LEN(@OPER) - CHARINDEX('[',@OPER) - 1)
	AND NAME = SUBSTRING(@OPER, 1, CHARINDEX('[',@OPER) - 1)
	
	UPDATE PRCCSTGDADJGRP SET
	  STAT = 100, CHKDATE = GETDATE(), CHECKER = @EMPGID
	WHERE NUM = @NUM
	
	DECLARE C_LAC CURSOR FOR
	SELECT STYLECODE FROM PRCCSTGDADJGRPLACDTL(NOLOCK) WHERE NUM = @NUM
	OPEN C_LAC
	FETCH NEXT FROM C_LAC
	INTO @STYLECODE
	WHILE @@FETCH_STATUS = 0
	BEGIN
 	  
 	  DECLARE C_GOODS CURSOR FOR
	  SELECT GDGID, NEWPRC FROM PRCCSTGDADJGRPDTL(NOLOCK) WHERE NUM = @NUM
	  OPEN C_GOODS
	  FETCH NEXT FROM C_GOODS
	  INTO @GDGID, @NEWPRC
	  WHILE @@FETCH_STATUS = 0
	  BEGIN 	  
	  
 	    DECLARE C_STORE CURSOR FOR
	    SELECT GID FROM CLIENT(NOLOCK) WHERE STYLE = @STYLECODE
	    OPEN C_STORE
	    FETCH NEXT FROM C_STORE
	    INTO @STOREGID
	    WHILE @@FETCH_STATUS = 0
	    BEGIN 
 	      IF NOT EXISTS(SELECT 1 FROM CSTGD WHERE CSTGID = @STOREGID AND GDGID = @GDGID)
 	        INSERT INTO CSTGD(CSTGID, GDGID, CSTGDCODE, SALE, ALCQTY, 
 	          ALCPRC, ISLTD, MEMO, LSTUPDTIME, LSTMODIFIER, CODE2, CRTLPRC)
 	        VALUES(@STOREGID, @GDGID, NULL, 1, 1, 
 	          @NEWPRC, 0, '客户组商品价格调整单生成', GETDATE(), @OPER, NULL, 0)
                  FETCH NEXT FROM C_STORE
	      INTO @STOREGID
	    END
	    DEALLOCATE C_STORE
                    	     
 	    FETCH NEXT FROM C_GOODS
	    INTO @GDGID, @NEWPRC
	  END
	  DEALLOCATE C_GOODS
 	  
	  FETCH NEXT FROM C_LAC
	  INTO @STYLECODE
	END
	DEALLOCATE C_LAC
	
	EXEC PRCCSTGDADJGRPADDLOG @NUM, 100, '审核', @OPER
	
	RETURN 0
END
GO
