SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[MKTIVGTCHK100TO110]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS	 CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE @VSTAT INT
  SELECT @VSTAT = STAT FROM PSMKTIVGT WHERE NUM = @NUM;
  IF @VSTAT <> 100
  BEGIN
    SET @MSG = @NUM + '不是已审核单据，不能作废'
    RETURN(1)
  END
  UPDATE PSMKTIVGT 
  SET STAT = 110, LSTUPDTIME = GETDATE() 
  WHERE NUM = @NUM;
  EXEC MktIvgtADDLOG @NUM, 110, '', @OPER
  RETURN 0
 
END
GO
