SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create procedure [dbo].[EMPGROUPSENDAll](
  @RCV int,
  @ErrMsg varchar(255) OUTPUT
) as
BEGIN
  DECLARE
    @EMPGROUPGID INT,
    @RETURN_STATUS INT

  DECLARE C_EMPGRPGID CURSOR FOR
    SELECT GID FROM EMPLOYEEGROUP(NOLOCK)
  OPEN C_EMPGRPGID
  FETCH NEXT FROM C_EMPGRPGID INTO @EMPGROUPGID
  WHILE @@FETCH_STATUS = 0
  BEGIN
    EXECUTE @RETURN_STATUS = EMPGROUPSEND @EMPGROUPGID, @RCV, @ErrMsg OUTPUT
    IF @RETURN_STATUS <> 0
      RETURN @RETURN_STATUS

    FETCH NEXT FROM C_EMPGRPGID INTO @EMPGROUPGID
  END
  CLOSE C_EMPGRPGID
  DEALLOCATE C_EMPGRPGID

  RETURN 0
END

GO
