SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
Create Procedure [dbo].[PURCHASEORDBCK_CHECK_100TO3200]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
with Encryption
AS
BEGIN
  DECLARE
    @VRET INT,
    @SRCNUM CHAR(14),
    @BOOL CHAR(1),
    @GDGID INT,
    @BCKQTY MONEY,
    @XFLOWNO VARCHAR(20),
    @XPOSNO VARCHAR(10)


  SELECT @SRCNUM = SRCNUM FROM PURCHASEORDER(NOLOCK) WHERE NUM = @NUM AND CLS = @CLS
  IF EXISTS(SELECT 1 FROM PURCHASEORDER(NOLOCK) WHERE NUM = @SRCNUM AND CLS = '销售定货' AND STAT = 300)
  BEGIN
    SET @MSG = '来源销售定单状态为已完成, 不能确认'
    RETURN 1
  END

  UPDATE PURCHASEORDER SET CONFIRMER = @OPER, CONFIRMDATE = GETDATE(), STAT = @TOSTAT, LSTUPDTIME = GETDATE()
  WHERE NUM = @NUM AND CLS = @CLS

  SET @BOOL = '1'
  DECLARE C_CURSOR CURSOR FOR
    SELECT D.GDGID, SUM(D.BCKQTY), D.POSNO, D.FLOWNO
    FROM PURCHASEORDERDTL D(NOLOCK), PURCHASEORDER M(NOLOCK)
    WHERE D.CLS = @CLS AND D.NUM = M.NUM AND D.CLS = M.CLS AND M.SRCNUM = @SRCNUM AND M.STAT = 3200
    GROUP BY D.GDGID, D.POSNO, D.FLOWNO
  OPEN C_CURSOR
  FETCH NEXT FROM C_CURSOR INTO @GDGID, @BCKQTY, @XPOSNO, @XFLOWNO
  WHILE @@FETCH_STATUS = 0
  BEGIN
    UPDATE PURCHASEORDERDTL SET BCKQTY = @BCKQTY WHERE NUM = @SRCNUM AND CLS = '销售定货' AND GDGID = @GDGID
      AND POSNO = @XPOSNO AND FLOWNO = @XFLOWNO
    FETCH NEXT FROM C_CURSOR INTO @GDGID, @BCKQTY, @XPOSNO, @XFLOWNO
  END
  CLOSE C_CURSOR
  DEALLOCATE C_CURSOR

  IF EXISTS(SELECT 1
    FROM PURCHASEORDERDTL(NOLOCK)
    WHERE NUM = @SRCNUM AND CLS = '销售定货' AND ORDQTY - ARVQTY <> BCKQTY)
  BEGIN
    SET @BOOL = '0'
  END

  IF @BOOL = '1'
  BEGIN
    UPDATE PURCHASEORDER SET STAT = 300, LSTUPDTIME = GETDATE(), FINISHEDDATE = GETDATE()
    WHERE NUM = @SRCNUM AND CLS = '销售定货'
    EXEC PURCHASEORDADDLOG @SRCNUM, '销售定货', 300, '完成', @OPER
    EXEC @VRET = SENDPOORD @SRCNUM, @OPER, '销售定货', 0, ''
    if @VRET <> 0 RETURN @VRET
  END

  EXEC PURCHASEORDERADDLOG @NUM, @CLS, 3200, '确认', @OPER

  IF (SELECT OPTIONVALUE FROM HDOPTION WHERE MODULENO = 670 AND OPTIONCAPTION = 'AUTOSEND') = '1'
  BEGIN
    EXEC @VRET = PURCHASEORDBCK_SND @NUM, @OPER, @CLS, @TOSTAT, @MSG, 0  --最后个参数0表示不附带发送其他单据
    RETURN @VRET
  END
  RETURN(0)
end
GO
