SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[WritePrcAdjLog]
(
  @CLS VARCHAR(20),           --单据类型
  @NUM VARCHAR(20),           --单号
  @ACT VARCHAR(20)            --动作
)
AS
BEGIN
  DECLARE
    @FILLERCODE VARCHAR(20), 
    @FILLER VARCHAR(20), 
    @FILLERNAME VARCHAR(50)
    
  SET @FILLERCODE = RTRIM(SUBSTRING(SUSER_SNAME(), CHARINDEX('_', SUSER_SNAME()) + 1, 20))
    
  SELECT @FILLER = CODE, @FILLERNAME = NAME 
  FROM EMPLOYEE(NOLOCK)
  WHERE CODE LIKE @FILLERCODE
    
  INSERT INTO PrcAdjLOG (CLS, NUM, MODIFIER, TIME, ACT)
  VALUES (@CLS, @NUM, @FILLERNAME+'['+ @FILLER + ']', GETDATE(), @ACT)
END
GO
