SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CHKBCKDMDTO1600]
(
  @piNUM CHAR(14),
  @piOPER CHAR(30),
  @piCLS CHAR(10),
  @piTOSTAT INT,
  @poMSG VARCHAR(255) OUTPUT
)
AS
BEGIN
	UPDATE BCKDMD SET
		STAT = 1600,
		LSTUPDTIME = GETDATE()
	WHERE NUM = @piNUM
	EXEC BCKDMDADDLOG @piNUM, 1600, '', @piOPER
	RETURN 0
END
GO
