SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[INPRCADJNOTIFY_SEND](
  @NUM	CHAR(14),
  @OPER	CHAR(30),
  @CLS	CHAR(10),
  @TOSTAT	INT, --该字段由门店处理时回写
  @MSG	VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE
    @STOREGID INT,
    @RE INT

  IF (SELECT STAT FROM INPRCADJNOTIFY WHERE NUM = @NUM) = 0 OR (SELECT STAT FROM INPRCADJNOTIFY WHERE NUM = @NUM) = 300
  BEGIN
    SET @MSG = '单据' + @NUM + '状态不可发送'
    RETURN 1
  END

  UPDATE INPRCADJNOTIFY SET SNDDATE = GETDATE() WHERE NUM = @NUM

  IF EXISTS(SELECT 1 FROM SYSTEM(NOLOCK) WHERE USERGID <> ZBGID) --门店发送
  BEGIN
    SELECT @STOREGID = SRCSTORE FROM INPRCADJNOTIFY(NOLOCK) WHERE NUM = @NUM
    EXEC INPRCADJNOTIFY_SENDONESTORE @NUM, @OPER, @CLS, @TOSTAT, @STOREGID, @MSG OUTPUT
  END
  ELSE
  BEGIN
    DECLARE C_LAC CURSOR FOR
    SELECT STOREGID
    FROM INPRCADJNOTIFYLAC(NOLOCK)
    WHERE NUM = @NUM

    OPEN C_LAC
    FETCH NEXT FROM C_LAC INTO
      @STOREGID
    WHILE @@FETCH_STATUS = 0
    BEGIN
      IF NOT EXISTS(SELECT 1 FROM SYSTEM(NOLOCK) WHERE USERGID = @STOREGID)
      BEGIN
        EXEC @RE = INPRCADJNOTIFY_SENDONESTORE @NUM, @OPER, @CLS, @TOSTAT, @STOREGID, @MSG OUTPUT
        IF @RE <> 0 RETURN @RE
      END
      FETCH NEXT FROM C_LAC INTO
        @STOREGID
    END
    CLOSE C_LAC
    DEALLOCATE C_LAC
  END

  EXEC INPRCADJNOTIFY_ADDLOG @NUM, 100, '发送', @OPER

  SET @MSG = '发送' + @NUM+ '单据成功'

  RETURN 0
END
GO
