SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PROMBDLT]  
(  
 @NUM  VARCHAR(14),  
 @CLS  VARCHAR(10),  
 @OPER   VARCHAR(30),  
 @TOSTAT  int,  
 @MSG  VARCHAR(255) OUTPUT  
)  
AS  
BEGIN  
    declare   
 @VRET INT,  
 @VSTAT INT  
  
 select @VRET = 0  
 SELECT @VRET = STAT FROM PROMB(nolock) WHERE NUM = @NUM  
  
 IF @TOSTAT <> 100  -- @VSTAT <> 100   sunya
   BEGIN   
     select @MSG = '目标状态不对' +  CHAR(@TOSTAT); -- CHAR(@VSTAT)   sunya
     RETURN(1)  
   END  
 UPDATE GOODS SET LSTUPDTIME = getdate()  
 WHERE GID IN (SELECT GDGID FROM PRICES(nolock) WHERE BILLNUM = @NUM AND CLS = @CLS)  
   
 DELETE FROM PRICES  
 WHERE BILLNUM = @NUM AND CLS = @CLS  
   
 DELETE FROM PRICEBDIS  
 WHERE BILLNUM = @NUM  
   
 UPDATE PROMB SET STAT = 110, FILDATE = getdate(),  
  LSTUPDTIME = getdate()  
 WHERE NUM = @NUM  
   
 INSERT INTO PROMBLOG (NUM, STAT, FILLER, FILDATE)  
  VALUES(@NUM, 110, @OPER, getdate())  
 EXEC @VRET = PROMBSEND @NUM,@CLS,@OPER,0,@MSG  
 IF @VRET <> 0  RETURN(1)  
   
 RETURN(0)  
END

GO
