SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[NPRMRTNPNTAGM_REMOVE]
(
  @SRC INT,
  @ID INT
)
AS
BEGIN
  DELETE FROM NPRMRTNPNTAGM WHERE SRC = @SRC AND ID = @ID
  DELETE FROM NPRMRTNPNTAGMDTL WHERE SRC = @SRC AND ID = @ID
  DELETE FROM NPRMRTNPNTAGMEXGDDTL WHERE SRC = @SRC AND ID = @ID
  DELETE FROM NPRMRTNPNTAGMRATEDTL WHERE SRC = @SRC AND ID = @ID
END
GO
