SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[MktIvgtSnd]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT   
) 
AS
BEGIN
  DECLARE 
    @VSTAT INT,
    @SRC INT,
    @RCV INT,
    @ID INT,
    @LOCALGID INT,
    @VRET INT
  SET @VRET = 0   
  SELECT @VSTAT = STAT, @SRC = SRC, @RCV = OCRSTORE 
  FROM PSMKTIVGT WHERE  NUM = @NUM      
  SELECT @LOCALGID = USERGID FROM SYSTEM
	
  IF @SRC <> @LOCALGID 
  BEGIN
    SET @MSG = '发送的单据不是本单位生成的'
    RETURN(1)
  END
  
  IF @VSTAT = 100  --发送到总部（审核）
  BEGIN
    SELECT @RCV = ZBGID FROM SYSTEM
    EXEC @VRET = MKTIVGTSNDTO @NUM, @SRC, @RCV, @MSG OUTPUT 
    RETURN @VRET
  END
  IF @VSTAT = 400 -- 发送到门店(批准)
  BEGIN
    EXEC @VRET = MKTIVGTSNDTO @NUM, @SRC, @RCV, @MSG OUTPUT 
    RETURN @VRET
  END

END
GO
