SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CHKVDRBCKDMD_40XTO500]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS	 CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
	DECLARE @CT INT
	DECLARE @LmtOperForNotSplitMDBill int,
	        @USERGID INT,         @SRCNUM CHAR(14),
	        @SRC INT
	EXEC OPTREADINT 569,'LmtOperForNotSplitMDBill',0,@LmtOperForNotSplitMDBill OUTPUT
	SELECT @USERGID = USERGID FROM SYSTEM
	SELECT @SRCNUM = SRCNUM, @SRC = SRC FROM VDRBCKDMD WHERE NUM = @NUM
	SELECT @CT = COUNT(*) FROM VdrBckDmd A,VdrBckDmdDTL B
		WHERE A.NUM = @NUM AND A.NUM = B.NUM AND (B.QTY is NULL OR B.PRICE IS NULL)
	IF @CT > 0
	BEGIN
		SET @MSG = '存在没有设置批准数量或者批准单价的记录!'
		RETURN 1
	END
	IF @LmtOperForNotSplitMDBill = 1 AND @SRC <> @USERGID
	  AND (@SRCNUM IS NULL OR RTRIM(@SRCNUM) = '')
	BEGIN
		SET @MSG ='单据是门店单据但未经过拆分不能审批。'
		RETURN 1
	END
	UPDATE VdrBckDmd SET
		STAT = 500,
		CACLDATE = GETDATE(),
		CANCELER = @OPER,  --审批人
		LSTUPDTIME = GETDATE()
	WHERE NUM = @NUM
	EXEC VDRBCKDMDADDLOG @NUM, 500, '', @OPER
	RETURN 0
END
GO
