SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PURCHASEORDBCK_SND]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT,
  @SNDFLAG SMALLINT = 1  --表示是否附带发送定货和退货单
) --WITH ENCRYPTION
AS
BEGIN
    DECLARE
      @SRC INT,   @ID  INT,
      @RCV INT,   @STAT SMALLINT

    SELECT @STAT = STAT
    FROM PURCHASEORDER(NOLOCK) WHERE NUM = @NUM AND CLS = @CLS

    --CHECK
    IF @STAT <> 3200
    BEGIN
      SET @MSG = '[发送]单据' + @NUM + ':不是已确认状态'
      RETURN 1
    END

    --BEGIN TO SEND
    SELECT @SRC = USERGID FROM SYSTEM(NOLOCK)
    SELECT @RCV = ZBGID FROM SYSTEM(NOLOCK)

    UPDATE PURCHASEORDER SET SNDTIME = GETDATE() WHERE NUM = @NUM AND CLS = @CLS

    EXECUTE GETNETBILLID @ID OUTPUT

    INSERT INTO NPURCHASEORDER(NUM, CLS, SETTLENO, VENDOR, TOTAL, TAX, NOTE, FILDATE,
      FILLER, CHECKER, STAT, WRH, RECCNT, SRC, SRCNUM, SNDTIME, RECEIVER, PSR, PRNTIME,
      PRECHECKER, PRECHKDATE, DEPT, CUSTOMIZETYPE, RCVTYPE, SELLERAPPROVEOPERATOR,
      SELLERREFNUMBER, SELLERAPPROVETIME, SELLERREMARK, BUYERNAME, BUYERREFNUMBER, BUYERADDRESS,
      BUYERTELEPHONE, BUYERORDERTIME, BUYERORDEREXPIRATIONDATE, BUYERORDERTYPE, BUYERFILDATE,
      BUYERSELLOPERATOR, BUYERCUSTMIZEDIMAGE, BUYERINVOICENUMBER, SUPPLIERCODE, SUPPLIERNAME,
      CHKDATE, LSTUPDTIME, ID, NSTAT, RCV, RCVTIME, TYPE, NNOTE, CONFIRMDATE, CONFIRMER, CUSTOMIZEMEMO, BCKCAUSE,
      FINISHED, NearBy, LANE, BUILDING, ROOM, BUYERREGIONDTL, RTLTOTAL, ORDAMT, SELLERCONINFO)
    SELECT NUM, CLS, SETTLENO, VENDOR, TOTAL, TAX, NOTE, FILDATE,
      FILLER, CHECKER, STAT, WRH, RECCNT, @SRC, SRCNUM, SNDTIME, RECEIVER, PSR, PRNTIME,
      PRECHECKER, PRECHKDATE, DEPT, CUSTOMIZETYPE, RCVTYPE, SELLERAPPROVEOPERATOR,
      SELLERREFNUMBER, SELLERAPPROVETIME, SELLERREMARK, BUYERNAME, BUYERREFNUMBER, BUYERADDRESS,
      BUYERTELEPHONE, BUYERORDERTIME, BUYERORDEREXPIRATIONDATE, BUYERORDERTYPE, BUYERFILDATE,
      BUYERSELLOPERATOR, BUYERCUSTMIZEDIMAGE, BUYERINVOICENUMBER, SUPPLIERCODE, SUPPLIERNAME,
      CHECKDATE, LSTUPDTIME, @ID, 0, @RCV, NULL, 0, NULL, CONFIRMDATE, CONFIRMER, CUSTOMIZEMEMO, BCKCAUSE,
      FINISHED, NearBy, LANE, BUILDING, ROOM, BUYERREGIONDTL, RTLTOTAL, ORDAMT, SELLERCONINFO
    FROM PURCHASEORDER(NOLOCK)
    WHERE NUM = @NUM AND CLS = @CLS

    IF @@ERROR <> 0
    BEGIN
        SET @MSG = '发送' + @NUM + '单据失败'
        RETURN 3
    END

    INSERT INTO NPURCHASEORDERDTL (NUM, CLS, LINE, GDGID, ORDQTY, PRICE, TOTAL, TAX, WRH,
      INVQTY, ARVQTY, BCKQTY, NOTE, FLOWNO, POSNO, RTLQTY, RTLBCKQTY, RTLPRC, RTLTOTAL,
      PRNUM, SRC, ID, ORDPRC, ORDAMT)
    SELECT NUM, CLS, LINE, GDGID, ORDQTY, PRICE, TOTAL, TAX, WRH,
      INVQTY, ARVQTY, BCKQTY, NOTE, FLOWNO, POSNO, RTLQTY, RTLBCKQTY, RTLPRC, RTLTOTAL,
      PRNUM, @SRC, @ID, ORDPRC, ORDAMT
    FROM PURCHASEORDERDTL(NOLOCK)
    WHERE NUM = @NUM AND CLS = @CLS

    IF @@ERROR <> 0
    BEGIN
        SET @MSG = '发送' + @NUM+ '单据失败'
        RETURN 4
    END

    EXEC PURCHASEORDERADDLOG @NUM, @CLS, @STAT, '发送', @OPER

    IF @SNDFLAG = 1
    BEGIN
      declare @ORDNUM char(14), @BCKNUM char(14)
      SELECT @ORDNUM = SRCNUM FROM PURCHASEORDER(NOLOCK) WHERE NUM = @NUM AND CLS = @CLS
      EXEC SENDPOORD @ORDNUM, @OPER, '销售定货', 0, ''

      declare c_cursor cursor for
        select num
        from PURCHASEORDER(NOLOCK)
        where CLS = '销售进货' and SRCNUM = @ORDNUM
      open c_cursor
      fetch next from c_cursor into @BCKNUM
      while @@fetch_status = 0
      begin
        EXEC PURCHASESTKIN_SND @BCKNUM, @OPER, '销售进货', 0, '', 0
        fetch next from c_cursor into @BCKNUM
      end
      close c_cursor
      deallocate c_cursor
    END

    SET @MSG = '发送' + @NUM + '单据成功'

    RETURN 0
END
GO
