SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create procedure [dbo].[EMPGROUPSEND](
  @EmpGroupGid INT,
  @RCV INT,
  @ErrMsg varchar(255) OUTPUT
) as
BEGIN
  DECLARE
    @USERGID INT,
    @NO INT,
    @ID INT

  SELECT @USERGID = USERGID FROM SYSTEM(NOLOCK)
  SELECT @NO = NO FROM EMPLOYEEGROUP(NOLOCK) WHERE GID = @EMPGROUPGID
  EXEC @ID = SEQNEXTVALUE 'NEMPLOYEEGROUP'

  --更新发送时间
  UPDATE EMPLOYEEGROUP SET SNDTIME = GETDATE() WHERE GID = @EMPGROUPGID

  --员工组
  INSERT INTO NEMPLOYEEGROUP(ID, GID, NO, NAME, [RIGHT], EXTRARIGHT, MEMO, SRC, SNDTIME, RCV, TYPE, NSTAT)
  SELECT @ID, GID, NO, NAME, [RIGHT], EXTRARIGHT, MEMO, @USERGID, SNDTIME, @RCV, 0, 0
  FROM EMPLOYEEGROUP(NOLOCK) WHERE GID = @EMPGROUPGID
   IF @@ERROR <> 0
    BEGIN
     SET @ERRMSG = '发送员工组' + CONVERT(VARCHAR(6),@NO) + '失败'
     RETURN(@@ERROR)
    END

  --员工组权限
  INSERT INTO NEMPGRPRIGHT(SRC, ID, EMPGRPGID, ARIGHT, ARIGHT2)
  SELECT @USERGID, @ID, EMPGRPGID, ARIGHT, ARIGHT2
  FROM EMPGRPRIGHT(NOLOCK) WHERE EMPGRPGID = @EMPGROUPGID
   IF @@ERROR <> 0
    BEGIN
     SET @ERRMSG = '发送员工组' + CONVERT(VARCHAR(6),@NO) + '失败'
     RETURN(@@ERROR)
    END

  --员工组特殊权限
  INSERT INTO NEMPGROUPSPECRIGHT(SRC, ID, EMPGROUPID, SPECRIGHTNO, RIGHTLEVEL, SPECRIGHTNO2)
  SELECT @USERGID, @ID, EMPGROUPID, SPECRIGHTNO, RIGHTLEVEL, SPECRIGHTNO2
  FROM EMPGROUPSPECRIGHT(NOLOCK) WHERE EMPGROUPID = @EMPGROUPGID
   IF @@ERROR <> 0
    BEGIN
     SET @ERRMSG = '发送员工组' + CONVERT(VARCHAR(6),@NO) + '失败'
     RETURN(@@ERROR)
    END

  RETURN 0
END

GO
