SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[STORERETAILADDLOG]
(
  @NUM	CHAR(14),
  @CLS    CHAR(10),
  @TOSTAT	INT,
  @Act    VarChar(50),
  @OPER	CHAR(30)
)
AS
BEGIN
  IF RTRIM(@OPER) = ''
  BEGIN
  	DECLARE @FILLERCODE VARCHAR(20), @FILLER INT, @FILLERNAME VARCHAR(50)
  	SET @FILLERCODE = RTRIM(SUBSTRING(SUSER_SNAME(), CHARINDEX('_', SUSER_SNAME()) + 1, 20))
  	SELECT @FILLER = GID, @FILLERNAME = NAME FROM EMPLOYEE(NOLOCK) WHERE CODE LIKE @FILLERCODE
  	IF @FILLERNAME IS NULL
  	BEGIN
  		SET @FILLERCODE = '-'
  		SET @FILLERNAME = '未知'
  	END
  	SET @OPER = '['+RTRIM(ISNULL(@FILLERCODE,''))+']' + RTRIM(ISNULL(@FILLERNAME,''))
  END
  IF @ACT = ''
  	SELECT @ACT = ACTNAME FROM MODULESTAT WHERE NO = @TOSTAT
  INSERT INTO STORERETAILLOG (NUM, CLS, STAT, ACT, MODIFIER, TIME)
  VALUES(@NUM, @CLS, @TOSTAT, @ACT, @OPER, GETDATE());
END
GO
