SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[STARTUP_STEP_POLYLTDADJ]
AS
BEGIN
  DECLARE
    @RETURN_STATUS INT,
    @NUM CHAR(14),
    @MSG VARCHAR(255)
  INSERT INTO LOG(TIME, EMPLOYEECODE, WORKSTATIONNO, MODULENAME, TYPE, CONTENT)
    VALUES (GETDATE(), 'STARTUP', 'HDSVC', 'SETTLEDAY', 101, '批量限制业务调整单。' )

  DECLARE C_POLYLTDADJ CURSOR FOR
  SELECT NUM FROM POLYLTDADJ(NOLOCK)
    WHERE STAT = 100 AND OCRTYPE = 1 AND OCRTIME <= GETDATE()
    ORDER BY FILDATE
  OPEN C_POLYLTDADJ
  FETCH NEXT FROM C_POLYLTDADJ INTO @NUM
  WHILE @@FETCH_STATUS = 0
  BEGIN
    EXECUTE @RETURN_STATUS = POLYLTDADJ_OCR @NUM, 'HDSVC', @MSG OUTPUT
    IF @RETURN_STATUS <> 0
    BEGIN
      WAITFOR DELAY '0:0:0.010'
      INSERT INTO LOG(TIME, EMPLOYEECODE, WORKSTATIONNO, MODULENAME, TYPE, CONTENT)
      VALUES (GETDATE(), 'STARTUP', 'HDSVC', 'POLYLTDADJ_OCR', 202, @NUM)
    END
    FETCH NEXT FROM C_POLYLTDADJ INTO @NUM
  END
  CLOSE C_POLYLTDADJ
  DEALLOCATE C_POLYLTDADJ
  RETURN 0
END
GO
