SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CHKVDRBCKDMD_500TO410]
(
  @piNUM CHAR(14),
  @piOPER CHAR(30),
  @piCLS  CHAR(10),
  @piTOSTAT INT,
  @poMSG VARCHAR(255) OUTPUT
)
AS
BEGIN
	--作废生成的退货单
	DECLARE
		@LOCKNUM VARCHAR(14),	@LOCKSTAT INT, @GENCLS VARCHAR(10)
	SET @GENCLS = '直配进退'
	SELECT @LOCKNUM = NUM, @LOCKSTAT = STAT FROM DIRALC(NOLOCK)
	  WHERE CLS = @GENCLS AND NUM =(
	  SELECT LOCKNUM FROM VDRBCKDMD WHERE LOCKCLS = @GENCLS
	    AND STAT in (500) AND NUM = @piNUM)

	IF @LOCKSTAT NOT IN (0, 7) AND @LOCKSTAT IS NOT NULL
	BEGIN
		SET @poMSG = '已经被导入直配进货退货单并审核不能作废['+@piNum+']'
		RETURN 1
	END
	IF @LOCKNUM <> '' AND @LOCKNUM IS NOT NULL AND @LOCKSTAT IN (0, 7)
	  UPDATE DIRALC SET STAT = 13   --作废
	  WHERE CLS = @GENCLS AND NUM = @LOCKNUM AND STAT IN (0, 7)

	SET @GENCLS = '直配出退'
	SELECT @LOCKNUM = NUM, @LOCKSTAT = STAT FROM DIRALC(NOLOCK)
	  WHERE CLS = @GENCLS AND NUM =(
	  SELECT LOCKNUM FROM VDRBCKDMD WHERE LOCKCLS = @GENCLS
	    AND STAT in (500) AND NUM = @piNUM)

	IF @LOCKSTAT NOT IN (0, 7) AND @LOCKSTAT IS NOT NULL
	BEGIN
		SET @poMSG = '已经被导入直配出货退货单并审核不能作废['+@piNum+']'
		RETURN 1
	END
	IF @LOCKNUM <> '' AND @LOCKNUM IS NOT NULL AND @LOCKSTAT IN (0, 7)
	  UPDATE DIRALC SET STAT = 13   --作废
	  WHERE CLS = @GENCLS AND NUM = @LOCKNUM AND STAT IN (0, 7)

	UPDATE VdrBckDmd SET
		STAT = 410, CACLDATE = GETDATE(),
		CANCELER = @piOPER, LSTUPDTIME = GETDATE()
	WHERE NUM = @piNUM
	EXEC VDRBCKDMDADDLOG @piNUM, 410, '', @piOPER
	RETURN 0
END
GO
