SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[GENNEXTSUBJCODE]
  @PICLS  VARCHAR(10),
  @PONEWCODE VARCHAR(14) OUTPUT
AS
BEGIN
  DECLARE
    @V_CMD VARCHAR(255),
    @V_STORECODE CHAR(10),
    @V_STOREGID INT,
    @V_MONTHFLAG VARCHAR(6),
    @V_CODE VARCHAR(14),
    @V_RET INT

  SELECT @V_MONTHFLAG = RTRIM(CONVERT(CHAR(6),GETDATE(), 12))
  SELECT @V_STORECODE = USERCODE, @V_STOREGID = USERGID FROM SYSTEM
  SELECT @V_STORECODE = RIGHT('0000' + LTRIM(RTRIM(@V_STORECODE)), 4)

  IF (@PICLS IS NULL) OR (RTRIM(@PICLS) = '')
    SELECT @V_CMD = 'DECLARE CUR_GENNEXTSUBJCODE CURSOR FOR SELECT MAX(CODE) '
      + ' FROM PS3MBRPROMSUBJ WHERE CODE LIKE ''' + Rtrim(@V_STORECODE) + @V_MONTHFLAG +'%'''
  ELSE
    SELECT @V_CMD = 'DECLARE CUR_GENNEXTSUBJCODE CURSOR FOR SELECT MAX(CODE) '
      + ' FROM PS3MBRPROMSUBJ WHERE CLS = ''' + @PICLS + ''' AND CODE LIKE ''' + Rtrim(@V_STORECODE) + @V_MONTHFLAG +'%'''
  EXEC(@V_CMD)

  OPEN CUR_GENNEXTSUBJCODE
  FETCH NEXT FROM CUR_GENNEXTSUBJCODE INTO @V_CODE
  IF @@FETCH_STATUS = 0
  BEGIN
    IF @V_CODE IS NULL OR SUBSTRING(@V_CODE, 5, 6) <> @V_MONTHFLAG
      SELECT @V_CODE = Rtrim(@V_STORECODE) + @V_MONTHFLAG + '0000'
  END ELSE BEGIN
    SELECT @V_CODE =Rtrim(@V_STORECODE) + @V_MONTHFLAG + '0000'
  END
  CLOSE CUR_GENNEXTSUBJCODE
  DEALLOCATE CUR_GENNEXTSUBJCODE

  EXEC @V_RET = NEXTBN2 @V_CODE, @PONEWCODE OUTPUT
  RETURN(@V_RET)
END
GO
