SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
create procedure [dbo].[PPS_ALCPOOLH_GETFROMTEMP]
(
  @poErrMsg varchar(255) output
) as
begin
  delete ALCPOOLH from ALCPOOLHTEMP a
  where a.GENNUM <> '-'
    and a.STOREGID = ALCPOOLH.STOREGID and a.GDGID = ALCPOOLH.GDGID
    and a.LINE = ALCPOOLH.LINE and a.GENNUM = ALCPOOLH.GENNUM
  insert into ALCPOOLH(STOREGID, GDGID, LINE, QTY, SRCQTY, DMDDATE, SRCGRP, SRCBILL, SRCCLS,
    SRCNUM, SRCLINE, GENNUM, GENTIME, GENCLS, APARTER, ALCER, NOTE)
  select STOREGID, GDGID, LINE, QTY, SRCQTY, DMDDATE, SRCGRP, SRCBILL, SRCCLS,
    SRCNUM, SRCLINE, GENNUM, GENTIME, GENCLS, APARTER, ALCER, NOTE
  from ALCPOOLHTEMP(nolock) where GENNUM <> '-'
  return(0);
end
GO
