SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SENDONEPROM]
(
  @NUM      VARCHAR(14),
  @CLS      VARCHAR(10),
  @SRC      INT,
  @RCV      INT,
  @ERR_MSG  VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE
    @ID INT,
    @STOREVER VARCHAR(10)

  EXECUTE GETNETBILLID @ID OUTPUT

  INSERT INTO NPROM (ID, NO, SRC, NUM, CLS, STAT, FILDATE, FILLER, SNDTIME,
    PRNTIME, LSTUPDTIME, TOPIC, STORESCOPE, NOTE, ASTART, AFINISH,
    CYCLE, CSTART, CFINISH, CSPEC,
    RCV, RCVTIME, TYPE, NSTAT, NNOTE, PSETTLENO, OCRTIME, FIXRATIO, GFTRATIO,
    HASCOND, EXPROM, MONTHSETTLENO, DLTPRICEPROM, OVERWRITERULE, PRIORITY)

  SELECT @ID, 1, @SRC, NUM, CLS, STAT, FILDATE, FILLER, GETDATE(),
    PRNTIME, LSTUPDTIME, TOPIC, replace(STORESCOPE, char(13) + char(10), ''), NOTE, ASTART, AFINISH,
    CYCLE, CSTART, CFINISH, CSPEC,
    @RCV, NULL, 0, 0, '', PSETTLENO, OCRTIME, FIXRATIO, GFTRATIO,
    HASCOND, EXPROM, MONTHSETTLENO, DLTPRICEPROM, OVERWRITERULE, PRIORITY
  FROM PROM(NOLOCK)
  WHERE NUM = @NUM AND CLS = @CLS

  INSERT INTO NPROMGOODS (SRC, ID, NO, NUM, CLS, LINE,GDGID,
    GDCODE, QPC, QPCSTR, RTLPRC, MBRPRC, CNTRINPRC, COST, PRMDIV1, PRMDIV2, PRMDIV3, QTY, FLAG, ISDLT, PREC, ROUNDTYPE)
  SELECT @SRC, @ID, 1, NUM, CLS, LINE, GDGID,
    GDCODE, QPC, QPCSTR, RTLPRC, MBRPRC, CNTRINPRC, COST, PRMDIV1, PRMDIV2, PRMDIV3, QTY, FLAG, ISDLT, PREC, ROUNDTYPE
  FROM PROMGOODS(NOLOCK)
  WHERE NUM = @NUM AND CLS = @CLS

  INSERT INTO NPROMQTY (SRC, ID, NO, NUM, CLS, PRMNO, QTY, PRMTOTAL, IFGFT, GFTQTY, PTOTAL)
  SELECT @SRC, @ID, 1, NUM, CLS, PRMNO, QTY, PRMTOTAL, IFGFT, GFTQTY, PTOTAL
  FROM PROMQTY(NOLOCK)
  WHERE NUM = @NUM AND CLS = @CLS

  INSERT INTO NPROMMONEY (SRC, ID, NO, NUM, CLS, PRMNO, TOTAL, PRMTOTAL, IFGFT, GFTQTY, PTOTAL, ISFULL)
  SELECT @SRC, @ID, 1, NUM, CLS, PRMNO, TOTAL, PRMTOTAL, IFGFT, GFTQTY, PTOTAL, ISFULL
  FROM PROMMONEY(NOLOCK)
  WHERE NUM = @NUM AND CLS = @CLS

  INSERT INTO NPROMGFT (SRC, ID, NO, NUM, CLS, PRMNO, LINE, GFTGID,
    GFTCODE, QPC, QPCSTR, RTLPRC, MBRPRC, CNTRINPRC, COST, PRMDIV1, PRMDIV2, PRMDIV3, QTY, FLAG, ISDLT)
  SELECT @SRC, @ID, 1, NUM, CLS, PRMNO, LINE, GFTGID,
    GFTCODE, QPC, QPCSTR, RTLPRC, MBRPRC, CNTRINPRC, COST, PRMDIV1, PRMDIV2, PRMDIV3, QTY, FLAG, ISDLT
  FROM PROMGFT(NOLOCK)
  WHERE NUM = @NUM AND CLS = @CLS

  --发送促销主题
  exec PRCPRMTOPICSND @RCV, @ID;

  RETURN 0
END

GO
