SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[POLYLTDADJ_DOREMOVE]
(
  @NUM CHAR(14),         --单号
  @MSG VARCHAR(255) OUTPUT  --错误信息
)
AS
BEGIN
  DELETE FROM POLYLTDADJ WHERE NUM = @NUM
  DELETE FROM POLYLTDADJDTL WHERE NUM = @NUM
  DELETE FROM POLYLTDADJLACDTL WHERE NUM = @NUM
  SET @MSG = ''
  RETURN(0)
END
GO
