SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ALCGFTAGM_CHECK_100TO110]
(
  @NUM	CHAR(14),
  @OPER	CHAR(30),
  @CLS	CHAR(10),
  @TOSTAT	INT,
  @MSG	VARCHAR(255) OUTPUT
)				
AS
BEGIN
	DECLARE 
	  @EMPGID INT, 		@RE INT,
	  @STOREGID INT,	@GDGID INT,
	  @NEWPRC MONEY,	@ALCGID INT,
	  @START DATETIME,	@FINISH DATETIME
	  
	SELECT @EMPGID = GID FROM EMPLOYEE(NOLOCK) WHERE 
	CODE = SUBSTRING(@OPER, CHARINDEX('[',@OPER) + 1, LEN(@OPER) - CHARINDEX('[',@OPER) - 1)
	AND NAME = SUBSTRING(@OPER, 1, CHARINDEX('[',@OPER) - 1)
	
	--删除ALCGFT表记录
	DELETE FROM ALCGFT WHERE SRCNUM = @NUM
	DELETE FROM ALCGFTDTL WHERE SRCNUM = @NUM
	
	UPDATE ALCGFTAGM SET
	  STAT = 110, CACLDATE = GETDATE(), CANCELER = @EMPGID
	WHERE NUM = @NUM	
	
	EXEC ALCGFTAGMADDLOG @NUM, 110, '作废', @OPER
	
	RETURN 0
END
GO
