SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[MKTPRCSCHEME_RCV]
(
  @BILL_ID INT,
  @SRC_ID INT,
  @OPER CHAR(30),
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE
    @NET_NUM CHAR(14),
    @RCV_GID INT,
    @NET_STAT SMALLINT,
    @NET_TYPE SMALLINT

  SELECT @RCV_GID = RCV, @NET_STAT = STAT, @NET_TYPE = NTYPE, @NET_NUM = NUM
  FROM NMKTPRCSCHEME(NOLOCK) WHERE ID = @BILL_ID AND SRC = @SRC_ID
  IF @@ROWCOUNT = 0 OR @NET_NUM IS NULL
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '不存在'
    RETURN 1
  END

  IF EXISTS(SELECT 1 FROM MKTPRCSCHEME(NOLOCK) WHERE NUM = @NET_NUM AND STAT = @NET_STAT)
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '已经被接收'
    RETURN 2
  END

  IF (SELECT MAX(USERGID) FROM SYSTEM(NOLOCK)) <>  @RCV_GID
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '接收单位不是本单位'
    RETURN 3
  END

  IF @NET_TYPE <> 1
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '不在接收缓冲区中'
    RETURN 4
  END

  IF EXISTS(SELECT 1 FROM NMKTPRCSCHEMEGDDTL(NOLOCK)
    WHERE SRC = @SRC_ID AND ID = @BILL_ID AND GDGID NOT IN (SELECT GID FROM GOODS(NOLOCK)))
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '商品资料在本地不存在'
    RETURN 5
  END

  DELETE FROM MKTPRCSCHEME WHERE NUM = @NET_NUM
  DELETE FROM MKTPRCSCHEMEGDDTL WHERE NUM = @NET_NUM

  INSERT INTO MKTPRCSCHEME(NUM, NAME, STAT, CREATOR, CREATETIME, CHECKER, CHKDATE, SNDTIME,
    LSTUPDTIME, NOTE)
  SELECT NUM, NAME, STAT, CREATOR, CREATETIME, CHECKER, CHKDATE, SNDTIME,
    LSTUPDTIME, NOTE
  FROM NMKTPRCSCHEME(NOLOCK)
  WHERE SRC = @SRC_ID AND ID = @BILL_ID

  IF @@ERROR <> 0
  BEGIN
    SET @MSG = '[接收]接收' + @NET_NUM + '单据失败'
    RETURN 6
  END

  INSERT INTO MKTPRCSCHEMEGDDTL(NUM, LINE, GDGID, GDQPCSTR, GDQPC, NOTE)
  SELECT NUM, LINE, GDGID, GDQPCSTR, GDQPC, NOTE
  FROM NMKTPRCSCHEMEGDDTL(NOLOCK)
  WHERE SRC = @SRC_ID AND ID = @BILL_ID

  IF @@ERROR <> 0
  BEGIN
    SET @MSG = '[接收]接收' + @NET_NUM + '单据失败'
    RETURN 7
  END

  DELETE FROM NMKTPRCSCHEME WHERE ID = @BILL_ID AND SRC = @SRC_ID
  DELETE FROM NMKTPRCSCHEMEGDDTL WHERE ID = @BILL_ID AND SRC = @SRC_ID

  SET @MSG = '单据：' + @NET_NUM + '接收成功' + @MSG

  RETURN 0
END
GO
