SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[GoodsAppCheckCanDel]
(
	@GDGID	INT,
	@MSG	VARCHAR(100) OUTPUT
)
AS
BEGIN
  --CHECK IF CANBE DELETED -- COPY FROM GD_DTL -
  SET @MSG = ''
  DECLARE @QTY MONEY, @QTYAMT MONEY, @TMSG VARCHAR(100)
  --SELECT @GDGID = GID FROM GOODS(NOLOCK) WHERE CODE LIKE @GDCODE
  IF @GDGID = 1
  BEGIN
    SET @MSG = @MSG + '<不能删除系统设定的记录>'
  END
  IF EXISTS ( SELECT * FROM INV WHERE GDGID = @GDGID
    AND (QTY <> 0 OR TOTAL > 0.01 OR TOTAL < -0.01 ))
  BEGIN
    SELECT @QTY = SUM(QTY), @QTYAMT = SUM(TOTAL) FROM INV WHERE GDGID = @GDGID GROUP BY GDGID
    SET @MSG = @MSG + '尚有库存(额)不能删除，库存：' + CONVERT(VARCHAR,@QTY) + '，库存金额：' + CONVERT(VARCHAR,@QTYAMT) + '. '
  END
/*  2000-1-3 LIQI 商品删除时，对大小包装商品不再删除PKG表，而是报错 */
  IF EXISTS (SELECT 1 FROM PKG WHERE PGID = @GDGID)
  BEGIN
    SET @MSG = @MSG + '是大包装商品, 不能删除. 若要删除，请先取消大小包装.'
  END
  IF EXISTS (SELECT 1 FROM PKG WHERE EGID = @GDGID)
  BEGIN
    SET @MSG = @MSG + '是小包装商品, 不能删除. 若要删除，请先取消大小包装.'
  END
/*
  IF EXISTS (SELECT * FROM V_VDRYRPT, DELETED
    WHERE V_VDRYRPT.BGDGID = DELETED.GID
    AND (NPQTY <> 0 OR NPTL <> 0)
  ) BEGIN
    ('本商品尚未全部结清，不能删除。', 16, 1)
  END
*/
  /* 2000-04-21 */
  IF EXISTS ( SELECT * FROM INV WHERE GDGID = @GDGID
    AND DSPQTY <> 0 )
  BEGIN
    SELECT @QTY = SUM(DSPQTY) FROM INV WHERE GDGID = @GDGID
    SET @MSG = @MSG + '尚有未提数: '+CONVERT(VARCHAR,@QTY)+' ,不能删除.'
  END
  IF EXISTS ( SELECT * FROM INV WHERE GDGID = @GDGID
    AND BCKQTY <> 0 )
  BEGIN
    SELECT @QTY = SUM(BCKQTY) FROM INV WHERE GDGID = @GDGID
    SET @MSG = @MSG + '尚有退货数: ' + CONVERT(VARCHAR,@QTY) + ' ,不能删除.'
  END
  IF @MSG<>'' RETURN 1
  RETURN 0
END
GO
