SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[GDINVCHGNOTIFY_SEND]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE
    @STAT INT, @SRC INT, @STOREGID INT, @ID INT, @SETPKG INT

  SELECT @STAT = STAT, @SETPKG = SETPKG FROM GDINVCHGNOTIFY(NOLOCK) WHERE NUM = @NUM

  IF @STAT <> 100 AND @STAT <> 800
  BEGIN
    SET @MSG = '[发送]单据' + @NUM + '不是已审核状态'
    RETURN 1
  END

  UPDATE GDINVCHGNOTIFY SET SNDTIME = GETDATE() WHERE NUM = @NUM

  SELECT @SRC = USERGID FROM SYSTEM(NOLOCK)

  IF @SETPKG = 1
    DECLARE C_LINE CURSOR FOR
    SELECT GID FROM STORE(NOLOCK) WHERE GID <> @SRC
  ELSE
    DECLARE C_LINE CURSOR FOR
    SELECT STOREGID FROM GDINVCHGNOTIFYLACDTL(NOLOCK) WHERE NUM = @NUM AND STOREGID <> @SRC
  OPEN C_LINE
  FETCH NEXT FROM C_LINE
  INTO @STOREGID
  WHILE @@FETCH_STATUS = 0
  BEGIN
    EXECUTE GETNETBILLID @ID OUTPUT

    INSERT INTO NGDINVCHGNOTIFY(NUM, SETTLENO, FILDATE, FILLER, CHECKER, CHKDATE, STAT, NOTE,
      RECCNT, LAUNCH, SNDTIME, PRNTIME, LSTUPDTIME, EON, SETPKG, SRC, ID, RCV, RCVTIME, NTYPE,
      NSTAT, NNOTE, EXDIRECT)
    SELECT NUM, SETTLENO, FILDATE, FILLER, CHECKER, CHKDATE, STAT, NOTE,
      RECCNT, LAUNCH, SNDTIME, PRNTIME, LSTUPDTIME, EON, SETPKG, @SRC, @ID, @STOREGID, GETDATE(), 0,
      0, NULL, EXDIRECT
    FROM GDINVCHGNOTIFY(NOLOCK)
    WHERE NUM = @NUM

    IF @@ERROR <> 0
    BEGIN
      SET @MSG = '发送' + @NUM + '单据失败'
      RETURN 2
    END
    
    INSERT INTO NGDINVCHGNOTIFYDTL(NUM, LINE, OUTGDGID, INGDGID, RELQTY, NOTE, SRC, ID)
    SELECT NUM, LINE, OUTGDGID, INGDGID, RELQTY, NOTE, @SRC, @ID
    FROM GDINVCHGNOTIFYDTL(NOLOCK)
    WHERE NUM = @NUM

    IF @@ERROR <> 0
    BEGIN
      SET @MSG = '发送' + @NUM + '单据失败'
      RETURN 3
    END

    FETCH NEXT FROM C_LINE INTO @STOREGID
  END
  DEALLOCATE C_LINE

  SET @MSG = '发送' + @NUM + '单据成功'

  RETURN 0
END
GO
