SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SALEDIFFCHK] (
  @NUM	CHAR(14),
  @OPER	INT = 1
) AS
BEGIN
  DECLARE @STAT INT, @FINISHED INT
  
  SELECT @STAT = STAT, @FINISHED = FINISHED FROM SALEDIF WHERE NUM = @NUM
  IF @@ROWCOUNT = 0
  BEGIN
    RAISERROR('单据%s不存在', 16, 1, @NUM);
    RETURN 1
  END ELSE IF @STAT <> 0
  BEGIN
  	RAISERROR('单据%s不是未审核单据', 16, 1, @NUM);
  	RETURN 1
  END ELSE IF @FINISHED = 1
  BEGIN
  	RAISERROR('单据%s已结束，不能审核', 16, 1, @NUM);
  	RETURN 1
  END
  UPDATE SALEDIF SET STAT = 100, CHECKER = @OPER WHERE NUM = @NUM
  
  RETURN 0
END
GO
