SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create procedure [dbo].[RTLADDRESEND](
  @FILLDATE DATETIME
)AS
begin
  DECLARE @DATE DATETIME,
          @FDATE DATETIME,
          @MSETTLENO INT,
          @MSETTLENO1 INT,
          @YSETTLENO INT,
          @YSETTLENO1 INT,
          @Part       INT,
          @I          INT
  SELECT @DATE = convert(datetime, convert(CHAR, getdate(), 102))
  SELECT @FDATE = convert(datetime, convert(CHAR, @FILLDATE, 102))
  SELECT @MSETTLENO = MAX(NO) FROM MONTHSETTLE
  SELECT @MSETTLENO1 = NO FROM MONTHSETTLE WHERE BEGINDATE<= @FILLDATE AND ENDDATE >= @FILLDATE
  SELECT @YSETTLENO = MAX(NO) FROM YEARSETTLE
  SELECT @YSETTLENO1 = NO FROM YEARSETTLE WHERE BEGINDATE>= @FILLDATE AND ENDDATE <= @FILLDATE
  IF @DATE <> @FDATE
  BEGIN
    IF NOT EXISTS(SELECT 1 FROM RPTSNDFLAG WHERE SUBJECT = '出货日报' AND ADATE = @FDATE AND FLAG = 1)
    BEGIN
      DELETE FROM RPTSNDFLAG WHERE SUBJECT = '出货日报' AND ADATE = @FDATE
      INSERT INTO RPTSNDFLAG (SUBJECT, ASETTLENO, ADATE, FLAG) VALUES ('出货日报', @MSETTLENO1, @FDATE, 1)
    END
    set @Part = Cast(@DATE - @FDATE as INT)
    Set @i = 0
    while @Part > 0 and @i < @Part
    begin
      IF NOT EXISTS(SELECT 1 FROM RPTSNDFLAG WHERE SUBJECT = '库存日报' AND ADATE = (@FDATE + @i) AND FLAG = 1)
       BEGIN
         DELETE FROM RPTSNDFLAG WHERE SUBJECT = '库存日报' AND ADATE = (@FDATE + @i)
         INSERT INTO RPTSNDFLAG (SUBJECT, ASETTLENO, ADATE, FLAG) VALUES ('库存日报', @MSETTLENO1, (@FDATE + @i), 1)
       END
      Set @i = @i + 1
    end

    IF NOT EXISTS(SELECT 1 FROM RPTSNDFLAG WHERE SUBJECT = '库存调整日报' AND ADATE = @FDATE AND FLAG = 1)
    BEGIN
      DELETE FROM RPTSNDFLAG WHERE SUBJECT = '库存调整日报' AND ADATE = @FDATE
      INSERT INTO RPTSNDFLAG (SUBJECT, ASETTLENO, ADATE, FLAG) VALUES ('库存调整日报', @MSETTLENO1, @FDATE, 1)
    END
    IF NOT EXISTS(SELECT 1 FROM RPTSNDFLAG WHERE SUBJECT = '供应商帐款日报' AND ADATE = @FDATE AND FLAG = 1)
    BEGIN
      DELETE FROM RPTSNDFLAG WHERE SUBJECT = '供应商帐款日报' AND ADATE = @FDATE
      INSERT INTO RPTSNDFLAG (SUBJECT, ASETTLENO, ADATE, FLAG) VALUES ('供应商帐款日报', @MSETTLENO1, @FDATE, 1)
    END
    IF NOT EXISTS(SELECT 1 FROM RPTSNDFLAG WHERE SUBJECT = '客户帐款日报' AND ADATE = @FDATE AND FLAG = 1)
    BEGIN
      DELETE FROM RPTSNDFLAG WHERE SUBJECT = '客户帐款日报' AND ADATE = @FDATE
      INSERT INTO RPTSNDFLAG (SUBJECT, ASETTLENO, ADATE, FLAG) VALUES ('客户帐款日报', @MSETTLENO1, @FDATE, 1)
    END
    ------月报
    IF @MSETTLENO <> @MSETTLENO1
    BEGIN
      IF NOT EXISTS(SELECT 1 FROM RPTSNDFLAG WHERE SUBJECT = '出货月报' AND ASETTLENO = @MSETTLENO1 AND FLAG = 1)
      BEGIN
        DELETE FROM RPTSNDFLAG WHERE SUBJECT = '出货月报' AND ASETTLENO = @MSETTLENO1
        INSERT INTO RPTSNDFLAG (SUBJECT, ASETTLENO, ADATE, FLAG) VALUES ('出货月报', @MSETTLENO1, @FDATE, 1)
      END
      set @Part = @MSETTLENO - @MSETTLENO1
      Set @i = 0;
      while @Part > 0 and @i < @Part
      begin
        IF NOT EXISTS(SELECT 1 FROM RPTSNDFLAG WHERE SUBJECT = '库存月报' AND ASETTLENO = @MSETTLENO1 + @i AND FLAG = 1)
        BEGIN
          DELETE FROM RPTSNDFLAG WHERE SUBJECT = '库存月报' AND ASETTLENO = @MSETTLENO1 + @i
          INSERT INTO RPTSNDFLAG (SUBJECT, ASETTLENO, ADATE, FLAG) VALUES ('库存月报', @MSETTLENO1 + @i, @FDATE, 1)
        END
        Set @i = @i + 1
      END
      IF NOT EXISTS(SELECT 1 FROM RPTSNDFLAG WHERE SUBJECT = '库存调整月报' AND ASETTLENO = @MSETTLENO1 AND FLAG = 1)
      BEGIN
        DELETE FROM RPTSNDFLAG WHERE SUBJECT = '库存调整月报' AND ASETTLENO = @MSETTLENO1
        INSERT INTO RPTSNDFLAG (SUBJECT, ASETTLENO, ADATE, FLAG) VALUES ('库存调整月报', @MSETTLENO1, @FDATE, 1)
      END
      IF NOT EXISTS(SELECT 1 FROM RPTSNDFLAG WHERE SUBJECT = '供应商帐款月报' AND ASETTLENO = @MSETTLENO1 AND FLAG = 1)
      BEGIN
        DELETE FROM RPTSNDFLAG WHERE SUBJECT = '供应商帐款月报' AND ASETTLENO = @MSETTLENO1
        INSERT INTO RPTSNDFLAG (SUBJECT, ASETTLENO, ADATE, FLAG) VALUES ('供应商帐款月报', @MSETTLENO1, @FDATE, 1)
      END
      IF NOT EXISTS(SELECT 1 FROM RPTSNDFLAG WHERE SUBJECT = '客户帐款月报' AND ASETTLENO = @MSETTLENO1 AND FLAG = 1)
      BEGIN
        DELETE FROM RPTSNDFLAG WHERE SUBJECT = '客户帐款月报' AND ASETTLENO = @MSETTLENO1
        INSERT INTO RPTSNDFLAG (SUBJECT, ASETTLENO, ADATE, FLAG) VALUES ('客户帐款月报', @MSETTLENO1, @FDATE, 1)
      END
    END  -- MONTH NOT EQUAL
    IF @YSETTLENO <> @YSETTLENO1
    BEGIN
      IF NOT EXISTS(SELECT 1 FROM RPTSNDFLAG WHERE SUBJECT = '出货年报' AND ASETTLENO = @YSETTLENO1 AND FLAG = 1)
      BEGIN
        DELETE FROM RPTSNDFLAG WHERE SUBJECT = '出货年报' AND ASETTLENO = @YSETTLENO1
        INSERT INTO RPTSNDFLAG (SUBJECT, ASETTLENO, ADATE, FLAG) VALUES ('出货年报', @YSETTLENO1, @FDATE, 1)
      END
      set @Part = @YSETTLENO - @YSETTLENO1
      Set @i = 0;
      while @Part > 0 and @i < @Part
      begin
        IF NOT EXISTS(SELECT 1 FROM RPTSNDFLAG WHERE SUBJECT = '库存年报' AND ASETTLENO = @YSETTLENO1 + @i AND FLAG = 1)
        BEGIN
          DELETE FROM RPTSNDFLAG WHERE SUBJECT = '库存年报' AND ASETTLENO = @YSETTLENO1 + @i
          INSERT INTO RPTSNDFLAG (SUBJECT, ASETTLENO, ADATE, FLAG) VALUES ('库存年报', @YSETTLENO1 + @i, @FDATE, 1)
        END
        Set @i = @i + 1
      END
      IF NOT EXISTS(SELECT 1 FROM RPTSNDFLAG WHERE SUBJECT = '库存调整年报' AND ASETTLENO = @YSETTLENO1 AND FLAG = 1)
      BEGIN
        DELETE FROM RPTSNDFLAG WHERE SUBJECT = '库存调整年报' AND ASETTLENO = @YSETTLENO1
        INSERT INTO RPTSNDFLAG (SUBJECT, ASETTLENO, ADATE, FLAG) VALUES ('库存调整年报', @YSETTLENO1, @FDATE, 1)
      END
      IF NOT EXISTS(SELECT 1 FROM RPTSNDFLAG WHERE SUBJECT = '供应商帐款年报' AND ASETTLENO = @YSETTLENO1 AND FLAG = 1)
      BEGIN
        DELETE FROM RPTSNDFLAG WHERE SUBJECT = '供应商帐款年报' AND ASETTLENO = @YSETTLENO1
        INSERT INTO RPTSNDFLAG (SUBJECT, ASETTLENO, ADATE, FLAG) VALUES ('供应商帐款年报', @YSETTLENO1, @FDATE, 1)
      END
      IF NOT EXISTS(SELECT 1 FROM RPTSNDFLAG WHERE SUBJECT = '客户帐款年报' AND ASETTLENO = @YSETTLENO1 AND FLAG = 1)
      BEGIN
        DELETE FROM RPTSNDFLAG WHERE SUBJECT = '客户帐款年报' AND ASETTLENO = @YSETTLENO1
        INSERT INTO RPTSNDFLAG (SUBJECT, ASETTLENO, ADATE, FLAG) VALUES ('客户帐款年报', @YSETTLENO1, @FDATE, 1)
      END
    END  -- YEAR NOT EQUAL
  END	-- DATE NOT EQUAL
  RETURN 0
END
GO
