SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[TK_TOKENINFORCV]
AS
BEGIN
	DELETE FROM TK_TOKENINFO
	INSERT INTO TK_TOKENINFO(ID, SERIALNO, TYPE, SECUREKEY, INITTIME, 
		DIFFERENCE, INITTOKENTIME, STATE, LASTTIME, ADTIME, HDDIFF, 
		ERRTIMES, LASTAUTHTIME, TOTALAUTH, TOTALSUCC, SUCCTOKEN)
	SELECT ID, SERIALNO, ATYPE, SECUREKEY, INITTIME, DIFFERENCE, INITTOKENTIME,
		STATE, LASTTIME, ADTIME, HDDIFF, ERRTIMES, LASTAUTHTIME, TOTALAUTH,
		TOTALSUCC, SUCCTOKEN
	FROM TK_NTOKENINFO 
	WHERE TYPE = 1
	DELETE FROM TK_NTOKENINFO WHERE TYPE = 1
	
	RETURN 0
END
GO
