SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create procedure [dbo].[CHQSNDORG](
	@GID INT,
	@OPERGID INT,
	@MSG VARCHAR(255) OUTPUT
) as
begin
  declare @GROUPID INT,     @NTYPE SMALLINT,    @NNOTE varchar(100),
          @EXTIME DATETIME, @RHQUUID CHAR(32),  @NSTAT SMALLINT
  --exec OPTREADINT 0, '...', 0, @optvalue output
  exec @GROUPID = SeqNextValue 'CHQBASIC'
  set @RHQUUID = '1'
  set @NTYPE = 0
  set @NNOTE = ''
  set @NSTAT = 0
  set @EXTIME = Getdate()
  insert into CQNORG(GROUPID, RHQUUID, NTYPE, NSTAT, NNOTE, EXTIME, 
      GID, CODE, NAME, ADDRESS, PHONE, CONTACTOR, UPD, PROPERTY, 
      OUTPRC, SYSPATH, AREA, LASTEXCHANGEDATETIME, LASTEXCHANGETIME, 
      SNDFLAG, SVRNAME, MAINDB, POOLDB, DOMAIN, OSUSERNAME, OSPWD, 
      DBUSERNAME, DBPWD, IPAFLAG, ISLTD, LICENSE, SCOSCHEME, 
      ACCOUNTCLASS, MSD, YSD, COMMPHONE, VERSION, DBMS, 
      E_MAIL, MAILPWD, E_MAILPHONE, Mailacct, E_MAIL2, MAILPWD2, E_MAILPHONE2, mailacct2, 
      POP3, SMTP, POP32, SMTP2, FTPServer, FTPUser, FTPPwd, FTPPortNO, FTPDir)
    select @GROUPID, @RHQUUID, @NTYPE, @NSTAT, @NNOTE, @EXTIME, 
      GID, CODE, NAME, ADDRESS, PHONE, CONTACTOR, UPD, PROPERTY, 
      OUTPRC, SYSPATH, AREA, LASTEXCHANGEDATETIME, LASTEXCHANGETIME, 
      SNDFLAG, SVRNAME, MAINDB, POOLDB, DOMAIN, OSUSERNAME, OSPWD, 
      DBUSERNAME, DBPWD, IPAFLAG, ISLTD, LICENSE, SCOSCHEME, 
      ACCOUNTCLASS, MSD, YSD, COMMPHONE, VERSION, DBMS, 
      E_MAIL, MAILPWD, E_MAILPHONE, Mailacct, E_MAIL2, MAILPWD2, E_MAILPHONE2, mailacct2, 
      POP3, SMTP, POP32, SMTP2, FTPServer, FTPUser, FTPPwd, FTPPortNO, FTPDir
    from STORE(nolock)
    where GID = @GID
end;
GO
