SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[STKOUTCHKFIFO]
  @CLS CHAR(10), @NUM CHAR(10),  
  @LINE INT,  
  @WRH INT,
  @SUBWRH INT,
  @GDGID INT,
  @QTY MONEY,
  @TAXRATE MONEY,
  @PRICE MONEY OUTPUT,
  @TOTAL MONEY OUTPUT,
  @TAX MONEY OUTPUT
AS BEGIN
  DECLARE @RETURN_STATUS INT
  /*ADDED BY HXS 2003.1.27*/
  DECLARE @COST MONEY,@NEWSUBWRH INT
	,@OPTVALUE INT
	,@NEWPRC MONEY,@NEWTOTAL MONEY,@NEWTAX MONEY


	SELECT @SUBWRH = NULL
	  IF @QTY < 0
	  BEGIN
	    RETURN 1005
	  END

	EXEC CLEARTEMPSUBWRH @GDGID,@WRH
	IF EXISTS(SELECT 1 FROM STKOUTDTL2(nolock) WHERE CLS= @CLS AND NUM = @NUM AND LINE = @LINE)
	BEGIN
		INSERT INTO TEMPSUBWRH(SPID,WRH,SUBWRH,GDGID,QTY,COST)
			SELECT @@SPID,WRH,SUBWRH,GDGID,QTY,COST FROM STKOUTDTL2(nolock)
				WHERE CLS = @CLS AND NUM = @NUM AND LINE = @LINE 
	END


	SELECT @RETURN_STATUS = 0

	EXEC @RETURN_STATUS = UNLOADSUBWRH_2 @GDGID,@WRH,@QTY,@COST OUTPUT

	IF @RETURN_STATUS <> 0 RETURN @RETURN_STATUS
	
	DELETE FROM STKOUTDTL2 WHERE  CLS = @CLS AND NUM = @NUM AND LINE = @LINE

	INSERT INTO STKOUTDTL2(CLS,NUM,LINE,SUBWRH,WRH,GDGID,QTY,COST)
		SELECT @CLS,@NUM,@LINE,SUBWRH,WRH,GDGID,QTY,COST FROM TEMPSUBWRH 
			WHERE SPID = @@SPID AND GDGID = @GDGID AND WRH = @WRH

	SELECT @NEWSUBWRH= MIN(SUBWRH) FROM TEMPSUBWRH WHERE SPID = @@SPID AND WRH = @WRH AND GDGID = @GDGID

	EXEC OPTREADINT 0, 'FRCALCOUTPRC', 0, @OPTVALUE OUTPUT  
	IF @OPTVALUE = 1 AND @CLS = '配货' 
	BEGIN
		SELECT @NEWTOTAL = @COST
		SELECT @NEWPRC = @NEWTOTAL / @QTY
		SELECT @NEWTAX = @NEWTOTAL - (@NEWTOTAL)/(1 + @TAXRATE/100)
		UPDATE STKOUTDTL SET PRICE = @NEWPRC,TOTAL = @NEWTOTAL,TAX = @NEWTAX,
			SUBWRH = @NEWSUBWRH,COST = @COST
			WHERE CLS = @CLS AND NUM = @NUM AND LINE = @LINE
		UPDATE STKOUT SET TOTAL = TOTAL + (@NEWTOTAL - @TOTAL),TAX = TAX + (@NEWTAX - @TAX)
			WHERE CLS = @CLS AND NUM = @NUM
		SELECT @PRICE = @NEWPRC,@TOTAL = @NEWTOTAL ,@TAX = @NEWTAX
	END
	ELSE
	BEGIN
		UPDATE STKOUTDTL SET SUBWRH = @NEWSUBWRH,COST = @COST
			WHERE CLS = @CLS AND NUM = @NUM AND LINE = @LINE
	END
	EXEC CLEARTEMPSUBWRH @GDGID,@WRH

  RETURN(@RETURN_STATUS)

END
GO
