SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CRMSTAMPSCORULE_RCV]
(
  @SRC      INT,
  @ID       INT,
  @CLS      VARCHAR(10),
  @OPER     VARCHAR(30),
  @MSG      VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE
    @RET INT,
    @STORE INT,
    @NUM VARCHAR(14),
    @RCV INT,
    @FOUND CHAR(1),
    @cur_settleno int,
    @STAT INT,
    @NSTAT INT

  select @cur_settleno = max(no) from monthsettle
  SET @RET = 0
  SELECT @STORE = USERGID FROM FASYSTEM(NOLOCK)
  
  SELECT @NUM = NUM, @RCV = RCV, @NSTAT = STAT
  FROM NCRMSTAMPSCORULE(NOLOCK) WHERE SRC = @SRC AND ID = @ID
  
  if @@rowcount = 0
  begin
	set @msg = '找不到指定的网络单据'
	return 1
  end 
  
  IF @RCV <> @STORE
  BEGIN
    SET @MSG = '收到接收单位非本单位的' + @CLS + '单；单号=' + @NUM
    EXEC NCRMSTAMPSCORULE_REMOVE @SRC, @ID, @MSG output
    RETURN 0
  END

  SELECT @STAT = STAT FROM CRMSTAMPSCORULE(NOLOCK) WHERE NUM = @NUM
  IF @@ROWCOUNT = 1
    SET @FOUND = '1'
  ELSE
    SET @FOUND = '0'

  IF @FOUND = '1'
  BEGIN
    SET @MSG = '单据' + @NUM + '已经接收过，不再重复接收'
    EXEC NCRMSTAMPSCORULE_REMOVE @SRC, @ID, @MSG output
    RETURN 0
  END   
  
  insert into CRMSTAMPSCORULE(NUM,CLS,STAT,FILDATE,FILLER,SNDTIME,PRNTIME,CHKDATE,CHECKER,ABORTDATE,ABORTER,LSTUPDTIME,LSTUPDOPER,NOTE,SETTLENO,RECCNT)  
  select NUM,CLS,0,FILDATE,FILLER,SNDTIME,PRNTIME,CHKDATE,CHECKER,ABORTDATE,ABORTER,LSTUPDTIME,LSTUPDOPER,NOTE,SETTLENO,RECCNT
  from NCRMSTAMPSCORULE(nolock)
  where SRC = @SRC AND ID = @ID
  
  insert into CRMSTAMPSCORULEDTL(NUM,LINE,CLS,UUID,TOTAL,SCORE,SCOTOP,BEGINDATE,ENDDATE,NOTE)
  select NUM,LINE,CLS,UUID,TOTAL,SCORE,SCOTOP,BEGINDATE,ENDDATE,NOTE
  from NCRMSTAMPSCORULEDTL(nolock)
  where SRC = @SRC AND ID = @ID
  
  insert into CRMSTAMPSCORULEDTL2(NUM,LINE,CLS,GOODS,CODE,NAME,NOTE)
  select NUM,LINE,CLS,GOODS,CODE,NAME,NOTE
  from NCRMSTAMPSCORULEDTL2(nolock)
  where SRC = @SRC AND ID = @ID
  
  insert into CRMSTAMPSCORULELACSTORE(NUM,CLS,STOREGID)   
  select NUM,CLS,STOREGID
  from NCRMSTAMPSCORULELACSTORE(nolock)
  where SRC = @SRC AND ID = @ID 
  
  exec @ret = CRMSTAMPSCORULE_CHECK @NUM, @OPER, 100, @MSG output  
  if @ret <> 0 
  begin  
    UPDATE NCRMSTAMPSCORULE SET NSTAT = 1, NNOTE = '审核失败: ' + @MSG WHERE SRC = @SRC AND ID = @ID   
    return @ret
  end
  
  EXEC NCRMSTAMPSCORULE_REMOVE @SRC, @ID, @MSG output
  RETURN 0  
END
GO
