SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[NETPSINVPRCADJDEL] (
  @SRC INT,
  @ID INT,
  @MSG VARCHAR(255) OUTPUT
) AS
BEGIN
  DELETE FROM NINPRCADJNOTIFYDTL WHERE SRC = @SRC AND ID = @ID
  DELETE FROM NINPRCADJNOTIFYBCKDTL WHERE SRC = @SRC AND ID = @ID
  DELETE FROM NINPRCADJNOTIFY WHERE SRC = @SRC AND ID = @ID
  RETURN 0
END
GO
