SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[NPrmOffsetAgm_REMOVE]
(
  @SRC INT,
  @ID  INT
)
AS
BEGIN
  DELETE FROM NPrmOffsetAgm WHERE SRC = @SRC AND ID = @ID
  DELETE FROM NPrmOffsetAgmDTL WHERE SRC = @SRC AND ID = @ID
END
GO
