SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE  [dbo].[LOADPROMDTLTO50_ONELINEONESTORE]
(
    @PICLS         VARCHAR(10),
    @PINUM         VARCHAR(14),
    @PILINE        INT,
    @PISTOREGID    INT,
    @POERR_MSG     VARCHAR(255) OUTPUT
)
AS
BEGIN
    DECLARE
    @PIPSETTLENO   INT,
    @PIASTART      DATETIME,
    @PIAFINISH     DATETIME,
    @PICYCLE       DATETIME,
    @PICSTART      DATETIME,
    @PICFINISH     DATETIME,
    @PICSPEC       VARCHAR(255),
    @PIFLAG          INT,
    @PIGDGID       INT,
    @PIGDCODE      CHAR(13),
    @PIFIXRATIO    DECIMAL(24, 4),
    @PIGFTRATIO    DECIMAL(24, 4),
    @PIHASCOND     INT

    DECLARE
      @VRET         INT,
      @VQPC       DECIMAL(24,4),
      @VIQPCSTR VARCHAR(20),
      @VOCRTIME DATETIME,
      @PExprom  INT,
      @Code     CHAR(13),
      @OPT_ADDSUBDEPT INT,
      @SUBCODE  VARCHAR(64),
      @VONLYMEMBER INT

  /*
  LOADPROMDTLTO50 @PICLS, @PINUM, @StoreGid, @VPSETTLENO,
                         @VASTART,@VAFINISH,@VCYCLE,@VCSTART,@VCFINISH, @VCSPEC, @flag,
                         @line, @gdgid, @gdcode, @VFIXRATIO, @VGFTRATIO, @VHASCOND, @POERR_MSG
  */

  SELECT @PIFLAG = FLAG,@PIGDGID = GDGID, @PIGDCODE = GDCODE FROM PROMGOODS where num = @PINUM and line = @PILINE and CLS = @PICLS
  if not exists (Select 1 from GOODS G(NOLOCK) where G.GID = @PIGDGID)
    return(0) --如果商品在本地不存在，暂不执行。

  SELECT @PIASTART=ASTART, @PIAFINISH=AFINISH, @PICYCLE=CYCLE, @PICSTART=CSTART, @PICFINISH=CFINISH,
         @PICSPEC=CSPEC, @PIPSETTLENO=PSETTLENO, @PIFIXRATIO=FIXRATIO, @PIGFTRATIO=GFTRATIO, @PIHASCOND=HASCOND
  FROM PROM WHERE NUM = @PINUM AND CLS = @PICLS

    SET @VRET = 0
    UPDATE GOODS SET LSTUPDTIME = GETDATE() WHERE GID = @PIGDGID

    SELECT @VOCRTIME = OCRTIME, @PExprom = EXPROM, @VONLYMEMBER = ONLYMEMBER
    FROM PROM WHERE NUM = @PINUM AND CLS = @PICLS

    SELECT @VQPC = ISNULL(QPC, 1), @VIQPCSTR = ISNULL(QPCSTR, '1*1') FROM GDINPUT WHERE GID = @PIGDGID AND CODE = @PIGDCODE
    SET @VQPC = ISNULL(@VQPC, 1)
    SET @VIQPCSTR = ISNULL(@VIQPCSTR, '1*1')

    EXEC OPTREADINT 0, 'ADDSUBDEPT', 0, @OPT_ADDSUBDEPT OUTPUT

    /*IF @PIFLAG = 4 AND @OPT_ADDSUBDEPT = 1 --部门
    BEGIN
        EXEC GetSubDept @PIGDCODE
        DECLARE C CURSOR FOR
           SELECT B.CODE FROM SUBDEPTBYCODE A(NOLOCK), DEPT B(NOLOCK) WHERE A.SPID = @@SPID AND A.CODE = B.CODE
        OPEN C
        FETCH NEXT FROM C INTO @SUBCODE
        WHILE @@FETCH_STATUS = 0
        BEGIN
            INSERT INTO PROMOTE (STORE,CLS,GDGID,GDCODE,
                ASTART,AFINISH,CYCLE,CSTART,CFINISH,CSPEC,
                OCRTIME,BILLNUM,PSETTLENO,BILLLINE,QTY,FIXRATIO,GFTRATIO,FLAG,HASCOND,EXPROM,QPC)

            SELECT  @PISTOREGID,@PICLS,@PIGDGID,@SUBCODE,
                @PIASTART,@PIAFINISH,@PICYCLE,@PICSTART,@PICFINISH,@PICSPEC,
                @VOCRTIME,@PINUM,@PIPSETTLENO,@PILINE,QTY,@PIFIXRATIO,@PIGFTRATIO,FLAG,@PIHASCOND,@PExprom, ISNULL(@VQPC, 1)
            FROM PROMGOODS
            WHERE NUM = @PINUM AND CLS = @PICLS AND LINE = @PILINE AND FLAG = @PIFLAG

            FETCH NEXT FROM C INTO @SUBCODE
        END
        CLOSE C
        DEALLOCATE C
    END ELSE BEGIN*/
        INSERT INTO PROMOTE (STORE,CLS,GDGID,GDCODE,
            ASTART,AFINISH,CYCLE,CSTART,CFINISH,CSPEC,
            OCRTIME,BILLNUM,PSETTLENO,BILLLINE,QTY,FIXRATIO,GFTRATIO,FLAG,HASCOND,EXPROM,QPC,
            FLAG2,GDCODE2,ONLYMEMBER,PREC,ROUNDTYPE)

        SELECT  @PISTOREGID,@PICLS,@PIGDGID,@PIGDCODE,
            @PIASTART,@PIAFINISH,@PICYCLE,@PICSTART,@PICFINISH,@PICSPEC,
            @VOCRTIME,@PINUM,@PIPSETTLENO,@PILINE,QTY,@PIFIXRATIO,@PIGFTRATIO,FLAG,@PIHASCOND,@PExprom, ISNULL(@VQPC, 1),
            FLAG2,GDCODE2,@VONLYMEMBER,PREC,ROUNDTYPE
        FROM PROMGOODS
        WHERE NUM = @PINUM AND CLS = @PICLS AND LINE = @PILINE AND FLAG = @PIFLAG
    --END

    if @PIGDGID <> -1
      BEGIN
        DECLARE C CURSOR FOR
            SELECT CODE
              FROM GDINPUT
              WHERE GID = @PIGDGID AND CODE <> @PIGDCODE
                AND QPCSTR = @VIQPCSTR AND LEN(CODE) <= 13
            OPEN C
        FETCH NEXT FROM C INTO @CODE
        WHILE @@fetch_status = 0
          BEGIN
              INSERT INTO PROMOTE (STORE,CLS,GDGID,GDCODE,
                ASTART,AFINISH,CYCLE,CSTART,CFINISH,CSPEC,
                OCRTIME,BILLNUM,PSETTLENO,BILLLINE,QTY,FIXRATIO,GFTRATIO,FLAG,HASCOND,EXPROM,QPC,
                FLAG2,GDCODE2,ONLYMEMBER,PREC,ROUNDTYPE)
              SELECT  @PISTOREGID,@PICLS,@PIGDGID,@CODE,
                @PIASTART,@PIAFINISH,@PICYCLE,@PICSTART,@PICFINISH,@PICSPEC,
                  @VOCRTIME,@PINUM,@PIPSETTLENO,@PILINE,QTY,@PIFIXRATIO,@PIGFTRATIO,FLAG,@PIHASCOND,@PExprom, @VQPC,
                  FLAG2,GDCODE2,@VONLYMEMBER,PREC,ROUNDTYPE
              FROM PROMGOODS
              WHERE NUM = @PINUM AND CLS = @PICLS AND LINE = @PILINE AND FLAG = @PIFLAG
              FETCH NEXT FROM C INTO @CODE
            END
          CLOSE C
          DEALLOCATE C
      end
    RETURN(0)
END
GO
