SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CHECKBARCODE]
(
  @BARCODE VARCHAR(20) OUTPUT
)
AS
BEGIN
  DECLARE
    @INTSUM1 INT,
    @INTSUM2 INT,
    @I INT

  IF LEN(@BARCODE) > 8
    IF LEN(@BARCODE) < 13
      SET @BARCODE = REPLICATE('0', 12 - LEN(@BARCODE)) + @BARCODE
    ELSE
      SET @BARCODE = SUBSTRING(@BARCODE, 1, 12)
  ELSE
    IF LEN(@BARCODE) < 8
      SET @BARCODE = REPLICATE('0', 7 - LEN(@BARCODE)) + @BARCODE
    ELSE
      SET @BARCODE = SUBSTRING(@BARCODE, 1, 7)

  SET @BARCODE = '0' + @BARCODE
  SET @INTSUM1 = 0
  SET @INTSUM2 = 0
  SET @I = LEN(@BARCODE)
  WHILE @I >= 2
  BEGIN
    SET @INTSUM2 = @INTSUM2 + ASCII(SUBSTRING(@BARCODE, @I, 1)) - ASCII('0')
    SET @INTSUM1 = @INTSUM1 + ASCII(SUBSTRING(@BARCODE, @I - 1, 1)) - ASCII('0')
    SET @I = @I - 2
  END
  SET @BARCODE = SUBSTRING(@BARCODE, 2, LEN(@BARCODE)) + CHAR(ASCII('0') + (10 - (@INTSUM1 + @INTSUM2 * 3) % 10) % 10)
END
GO
