SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[VdrLeChk] (
  @Num CHAR(14),
  @Oper CHAR(30),
  @ToStat INT,
  @MSG VARCHAR(255) OUTPUT
) AS
BEGIN
  DECLARE
    @VdrGid INT,
    @GenPrcRateAdj INT,
    @return_status INT,
    @OperGid INT

  SELECT @VdrGid = VDRGID FROM VDRLESSEE
   WHERE NUM = @Num

  DELETE FROM VDRLESSORTDINV WHERE VDRGID = @VdrGid
  DELETE FROM VDRLESSORTBRANDINV WHERE VDRGID = @VdrGid
  DELETE FROM VDRLESSEEINV WHERE VDRGID = @VdrGid

  IF @ToStat = 100
  BEGIN
    INSERT INTO VDRLESSORTDINV(VDRGID, SORT, PAYRATE, SHOPNO)
    SELECT VDRGID, DTL.SORT, DTL.PAYRATE, DTL.SHOPNO
      FROM VDRLESSORTD DTL(NOLOCK), VDRLESSEE MST(NOLOCK)
    WHERE DTL.NUM = MST.NUM AND MST.NUM = @Num

    INSERT INTO VDRLESSORTBRANDINV(VdrGid, SORT, BRAND, PAYRATE, SORTCODE, SHOPNO)
    SELECT VDRGID, DTL.SORT, DTL.BRAND, DTL.PAYRATE, DTL.SORTCODE, DTL.SHOPNO
      FROM VDRLESSORTBRAND DTL(NOLOCK), VDRLESSEE MST(NOLOCK)
    WHERE DTL.NUM = MST.NUM AND MST.NUM = @Num

    INSERT INTO VDRLESSEEINV(NUM, VDRGID, PAYRATE, SHOPNO)
    SELECT @Num, VDRGID, PAYRATE, SHOPNO
      FROM VDRLESSEE(NOLOCK)
    WHERE NUM = @Num

    select @GenPrcRateAdj = OPTIONVALUE from HDOPTION where MODULENO = 705 and OPTIONCAPTION = 'GenPrcRateAdjOnChk'
    IF @GenPrcRateAdj = 1
    begin
      exec Utils_GetOperGid @Oper, @OperGid OUTPUT
      exec @return_status = VdrLeGenPrcRateAdj @Num, @OperGid, @Msg output
      if @return_status <> 0
      begin
        return 1
      end
    end

    UPDATE VDRLESSEE
    SET STAT = 1400
      WHERE VDRGID = @VDRGID AND STAT = 100 AND NUM <> @NUM
  END

  UPDATE VDRLESSEE SET
    STAT = @ToStat,
    CHECKER = @Oper,
    CHECKDATE = GETDATE()
  WHERE NUM = @Num

  RETURN 0
END
GO
