SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[RTLCHKFIFO]
  @NUM CHAR(10),
  @LINE INT,
  @WRH INT,
  @GDGID INT,
  @QTY MONEY,
  @COST MONEY OUTPUT
AS BEGIN
  DECLARE @RETURN_STATUS INT
  /*ADDED BY HXS 2003.1.27*/
  DECLARE @NEWSUBWRH INT
	,@OPTVALUE INT
	,@NEWPRC MONEY,@NEWTOTAL MONEY,@NEWTAX MONEY
	,@SUBWRH INT

	  IF @QTY < 0
	  BEGIN
	    RETURN 1005
	  END

	EXEC CLEARTEMPSUBWRH @GDGID,@WRH


	SELECT @RETURN_STATUS = 0

	EXEC @RETURN_STATUS = UNLOADSUBWRH_2 @GDGID,@WRH,@QTY,@COST OUTPUT

	IF @RETURN_STATUS <> 0 RETURN @RETURN_STATUS

	INSERT INTO RTLDTL2(NUM,LINE,SUBWRH,WRH,GDGID,QTY,COST)
		SELECT @NUM,@LINE,SUBWRH,WRH,GDGID,QTY,COST FROM TEMPSUBWRH
			WHERE SPID = @@SPID AND GDGID = @GDGID AND WRH = @WRH

	SELECT @NEWSUBWRH= MIN(SUBWRH) FROM TEMPSUBWRH WHERE SPID = @@SPID AND WRH = @WRH AND GDGID = @GDGID

	UPDATE RTLDTL SET SUBWRH = @NEWSUBWRH,COST = @COST
		WHERE NUM = @NUM AND LINE = @LINE

	EXEC CLEARTEMPSUBWRH @GDGID,@WRH

  RETURN(@RETURN_STATUS)

END
GO
