SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[INPRCADJNOTIFY_CHKTO10](
  @NUM	CHAR(14),
  @OPER	CHAR(30),
  @CLS	CHAR(10),
  @TOSTAT       INT,
  @MSG	VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE
    @BGNTIME DATETIME,
    @DIFFPROCMETHOD INT,
    @RE INT,
    @ENDTIME DATETIME,
    @COUNTALL INT,
    @COUNTTRUE INT,
    @GDGID INT,
    @REALQTY MONEY,
    @REALAMT MONEY,
    @OPT_AUTOSEND INT


  IF EXISTS(SELECT 1 FROM SYSTEM(NOLOCK) WHERE USERGID <> ZBGID) --如果门店
  BEGIN
    UPDATE INPRCADJNOTIFY SET STAT = 100 WHERE NUM = @NUM
    SELECT @BGNTIME = BGNTIME, @DIFFPROCMETHOD = DIFFPROCMETHOD
    FROM INPRCADJNOTIFY(NOLOCK) WHERE NUM = @NUM
    IF @BGNTIME <= GETDATE()
    BEGIN
      IF @DIFFPROCMETHOD = 0 --一次调整
      BEGIN
        --生效
        EXEC @RE = INPRCADJNOTIFY_CHECK @NUM, @OPER, @CLS, 800, @MSG OUTPUT
        IF @RE <> 0 RETURN @RE
        --发送
        EXEC @RE = INPRCADJNOTIFY_SEND @NUM, @OPER, @CLS, 3, @MSG OUTPUT
        IF @RE <> 0 RETURN @RE
      END
    END
  END
  ELSE --如果总部
  BEGIN
    SELECT @ENDTIME = ENDTIME
    FROM INPRCADJNOTIFY(NOLOCK) WHERE NUM = @NUM

    IF @ENDTIME <= GETDATE()
    BEGIN
      SET @MSG = '单据' + @NUM + '结束时间已过期'
      RETURN 1
    END

    UPDATE INPRCADJNOTIFY SET SUBTIME = GETDATE(), SUBEMP = @OPER WHERE NUM = @NUM
    UPDATE INPRCADJNOTIFY SET STAT = 100 WHERE NUM = @NUM

    --本店生效
    IF EXISTS(SELECT 1 FROM SYSTEM A(NOLOCK), INPRCADJNOTIFYLAC B(NOLOCK) WHERE B.NUM = @NUM AND A.USERGID = B.STOREGID)
    BEGIN
      SELECT @BGNTIME = BGNTIME, @DIFFPROCMETHOD = DIFFPROCMETHOD
      FROM INPRCADJNOTIFY(NOLOCK) WHERE NUM = @NUM
      IF @BGNTIME <= GETDATE()
      BEGIN
        IF @DIFFPROCMETHOD = 0 --一次调整
        BEGIN
          --生效
          EXEC @RE = INPRCADJNOTIFY_CHECK @NUM, @OPER, @CLS, 800, @MSG OUTPUT
          IF @RE <> 0 RETURN @RE

          UPDATE INPRCADJNOTIFY SET LSTRPLYTIME = GETDATE() WHERE NUM = @NUM
          UPDATE INPRCADJNOTIFYLAC SET PROCSTAT = 1 FROM SYSTEM A(NOLOCK) WHERE NUM = @NUM AND INPRCADJNOTIFYLAC.STOREGID = A.USERGID
          SELECT @COUNTALL = COUNT(*) FROM INPRCADJNOTIFYLAC(NOLOCK) WHERE NUM = @NUM
          SELECT @COUNTTRUE = COUNT(*) FROM INPRCADJNOTIFYLAC(NOLOCK) WHERE NUM = @NUM AND PROCSTAT = 1
          UPDATE INPRCADJNOTIFY SET EXESTAT = @COUNTTRUE / @COUNTALL WHERE NUM = @NUM

          IF (SELECT EXESTAT FROM INPRCADJNOTIFY(NOLOCK) WHERE NUM = @NUM) = 1
          BEGIN
            UPDATE INPRCADJNOTIFY SET STAT = 300 WHERE NUM = @NUM

            DECLARE C_LAC CURSOR FOR
            SELECT GDGID
            FROM INPRCADJNOTIFYDTL(NOLOCK)
            WHERE NUM = @NUM
            ORDER BY LINE

            OPEN C_LAC
            FETCH NEXT FROM C_LAC INTO @GDGID
            WHILE @@FETCH_STATUS = 0
            BEGIN
              SELECT @REALQTY = SUM(B.QTY), @REALAMT = SUM(B.AMT)
              FROM INPRCADJNOTIFYBCKDTL B(NOLOCK)
              WHERE B.NUM = @NUM AND B.GDGID = @GDGID

              UPDATE INPRCADJNOTIFYDTL SET REALQTY = @REALQTY, REALAMT = @REALAMT
              WHERE NUM = @NUM AND GDGID = @GDGID

              FETCH NEXT FROM C_LAC INTO @GDGID
            END
            CLOSE C_LAC
            DEALLOCATE C_LAC
          END
        END
      END
    END

    IF (SELECT STAT FROM INPRCADJNOTIFY WHERE NUM = @NUM) <> 300
    BEGIN
      EXEC OPTREADINT 649, 'AUTOSENDAFTERCHK', 0, @OPT_AUTOSEND OUTPUT
      IF @OPT_AUTOSEND = 1
      BEGIN
        EXEC @RE = INPRCADJNOTIFY_SEND @NUM, @OPER, @CLS, 0, @MSG OUTPUT
        IF @RE <> 0 RETURN @RE
      END
    END

  END

  EXEC INPRCADJNOTIFY_ADDLOG @NUM, @TOSTAT, '审核', @OPER

  SET @MSG = '单据：' + @NUM + '审核成功'

  RETURN 0
END
GO
