SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ALCDIFF_CHECK_401TO210]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS	 CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)				-- RETURN ERROR FROM 300
AS
BEGIN
	DECLARE
	  @EMPGID INT, 		@RE INT

	SELECT @EMPGID = GID FROM EMPLOYEE(NOLOCK) WHERE
	CODE = SUBSTRING(@OPER, CHARINDEX('[',@OPER) + 1, LEN(@OPER) - CHARINDEX('[',@OPER) - 1)
	AND NAME = SUBSTRING(@OPER, 1, CHARINDEX('[',@OPER) - 1)

	UPDATE ALCDIFF SET
	  STAT = 210, CACLDATE = GETDATE(), CANCELER = @EMPGID
	WHERE NUM = @NUM

	EXEC ALCDIFFADDLOG @NUM, 210, '进行中作废', @OPER

	IF EXISTS(SELECT 1 FROM HDOPTION WHERE MODULENO = 0 AND OPTIONCAPTION = 'RUNMODE'
	 	AND OPTIONVALUE = 'KD') --2006.10.30 added by zhanglong, Q8102, 配货差异单支持便利模式
	BEGIN
		EXEC @RE = ALCDIFFSND @NUM, @OPER, '0', 0, @MSG OUTPUT
		IF @RE <> 0
		BEGIN
			SET @MSG = '单据：' + @NUM + '作废失败' + CHAR(10) + CHAR(13) + @MSG
			RETURN @RE
		END
	END

	SET @MSG = '单据：' + @NUM + '作废成功' + CHAR(10) + CHAR(13) + @MSG

	RETURN 0
END
GO
