SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[LTDADJRCV] (
  @SRC  INT,
  @ID   INT,
  @OPER INT
) AS
BEGIN
  DECLARE @TYPE INT
  DECLARE @CHECKER INT
  DECLARE @FILLER INT
  DECLARE @TEMP INT
  DECLARE @NUM CHAR(14)
  DECLARE @SRCNUM CHAR(14)
  DECLARE @SETTLENO INT
  DECLARE @RET INT
  DECLARE @USERGID INT
  DECLARE @EON INT

  --2005.11.12 by panbin 限制业务调整单接收时增加判断,单据明细记录数是否与汇总中记录的明细数一致。
  DECLARE @ERRMSG VARCHAR(256)
  DECLARE @RECCNT INT
  SELECT @ERRMSG = ''
  SELECT @RECCNT = 0

  SELECT
    @NUM = NUM,
    @TYPE = TYPE,
    @FILLER = FILLER,
    @CHECKER = CHECKER
  FROM NLTDADJ WHERE SRC = @SRC AND ID = @ID
  IF @@ROWCOUNT = 0
  BEGIN
    RAISERROR('未找到指定的限制业务调整单', 16, 1)
    RETURN 1
  END

  IF @TYPE <> 1
  BEGIN
    RAISERROR('不是可接收的单据', 16, 1)
    RETURN 1
  END

--2005.11.12 by panbin 限制业务调整单接收时增加判断,单据明细记录数是否与汇总中记录的明细数一致。
  SELECT @RECCNT = SUM(1) FROM NLTDADJDTL WHERE SRC = @SRC AND ID = @ID
  IF  EXISTS(SELECT 1 FROM NLTDADJ WHERE SRC = @SRC AND ID = @ID AND RECCNT <> @RECCNT)
  BEGIN
    SELECT @ERRMSG = '单据的明细数为' + convert(varchar, @RECCNT)+ '条, 与汇总中记录的明细数不一致。'
    RAISERROR(@ERRMSG, 16, 1)
    RETURN 1
  END

  SELECT @FILLER = LGID FROM EMPXLATE(NOLOCK) WHERE NGID = @FILLER
  IF @@ROWCOUNT = 0
  BEGIN
    RAISERROR('本地未包含填单人资料', 16, 1)
    RETURN 1
  END
  SELECT @CHECKER = LGID FROM EMPXLATE(NOLOCK) WHERE NGID = @CHECKER
  IF @@ROWCOUNT = 0
  BEGIN
    RAISERROR('本地未包含审核人资料', 16, 1)
    RETURN 1
  END
  SELECT @TEMP = SUM(CASE WHEN X.LGID IS NULL THEN 1 ELSE 0 END)
  FROM NLTDADJDTL N(NOLOCK), GDXLATE X(NOLOCK)
  WHERE N.SRC = @SRC AND N.ID = @ID AND N.GDGID *= X.NGID
  IF @TEMP > 0
  BEGIN
    RAISERROR('本地未包含商品资料', 16, 1)
    RETURN 1
  END

  SELECT @USERGID = USERGID FROM SYSTEM(NOLOCK)
  IF NOT EXISTS(SELECT 1 FROM LTDADJ WHERE SRC = @SRC AND SRCNUM = @NUM)
  BEGIN
    EXEC GENNEXTBILLNUMEX NULL, 'LTDADJ', @NUM OUTPUT
    SELECT @SETTLENO = MAX(NO) FROM MONTHSETTLE(NOLOCK)
    INSERT INTO LTDADJDTL(NUM, SETTLENO, LINE, GDGID, OLDVALUE, NEWVALUE, NOTE, OLDSALE, NEWSALE, FINISHDATE)
    SELECT @NUM, @SETTLENO, D.LINE, X.LGID, D.OLDVALUE, D.NEWVALUE, D.NOTE, D.OLDSALE, D.NEWSALE, D.FINISHDATE
    FROM NLTDADJDTL D, GDXLATE X
    WHERE D.GDGID = X.NGID AND D.SRC = @SRC AND D.ID = @ID

    --是否本店生效
    IF EXISTS(SELECT 1 FROM NLTDADJLACDTL WHERE SRC = @SRC AND ID = @ID
      AND STOREGID = @USERGID)
      SELECT @EON = 1
    ELSE
      SELECT @EON = 0
    INSERT INTO LTDADJ(NUM, SETTLENO, FILDATE, FILLER, CHECKER, ATYPE, STAT,
    NOTE, RECCNT, LAUNCH, EON, SRC, SRCNUM, SNDTIME, PRNTIME, KEEPATYPE)
    SELECT @NUM, @SETTLENO, FILDATE, @FILLER, @CHECKER, ATYPE, 0,
    NOTE, RECCNT, LAUNCH, @EON, SRC, NUM, SNDTIME, NULL, KEEPATYPE
    FROM NLTDADJ WHERE SRC = @SRC AND ID = @ID

    --接收生效单位明细
    INSERT INTO LTDADJLACDTL(NUM, STOREGID)
    SELECT @NUM, STOREGID FROM NLTDADJLACDTL
    WHERE SRC = @SRC AND ID = @ID AND STOREGID <> @USERGID  --生效单位中包含本店的接收时置eon=1且从生效单位中删除

    EXEC @RET = LTDADJCHK @NUM, @OPER
    IF @RET <> 0 RETURN @RET
  END
  DELETE FROM NLTDADJDTL WHERE SRC = @SRC AND ID = @ID
  DELETE FROM NLTDADJ WHERE SRC = @SRC AND ID = @ID
  DELETE FROM NLTDADJLACDTL WHERE SRC = @SRC AND ID =@ID
  RETURN 0
END
GO
