SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[MKTPRC_CHECK_100TO110]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE @RE INT
  UPDATE MKTPRC
  SET STAT = 110, CACLDATE = GETDATE(), CANCELER = @OPER, LSTUPDTIME = GETDATE()
  WHERE NUM = @NUM

  IF EXISTS(SELECT 1 FROM SYSTEM(NOLOCK) WHERE USERGID <> ZBGID)  --门店
  BEGIN
    EXEC @RE = MKTPRC_SEND @NUM, @OPER, NULL, 0, @MSG OUTPUT
    IF @RE <> 0
    BEGIN
      SET @MSG = '单据：' + @NUM + '发送失败'
      RETURN @RE
    END
  END

  SET @MSG = '单据：' + @NUM + '作废成功' + CHAR(10) + CHAR(13) + @MSG

  RETURN 0
END
GO
