SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[GDINPRCADJ_CHKTO10](
  @NUM	CHAR(14),
  @OPER	CHAR(30),
  @CLS	CHAR(10),
  @TOSTAT	INT,
  @MSG	VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE
    @LAUNCH DATETIME,
    @RE INT

    UPDATE GDINPRCADJ SET STAT = 100, LSTUPDTIME = GETDATE(), CHECKER = @OPER, CHKDATE = GETDATE() WHERE NUM = @NUM

    SELECT @LAUNCH = LAUNCH FROM GDINPRCADJ(NOLOCK) WHERE NUM = @NUM

    IF @LAUNCH <= GETDATE()
    BEGIN
      EXEC @RE = GDINPRCADJ_CHECK @NUM, @OPER, @CLS, 800, @MSG OUTPUT
      IF @RE <> 0 RETURN @RE
    END


  RETURN 0
END
GO
