SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO

CREATE Procedure [dbo].[TA_pay2]
	@WHERE_CLAUSE VARCHAR(255)
As
declare @BeginDate char(10)
        ,@EndDate char(10)

declare @I int

select @I=charIndex(',',@WhERE_CLAUSE)

Select @BeginDate=SubString(@WHERE_CLAUSE,1,@I-1)
Select @EndDate=SubString(@WHERE_CLAUSE,@I+1,100)

EXEC ('DECLARE CUR_GETVOUCHER CURSOR GLOBAL FOR 
	SELECT RTRIM(VENDORH.CODE) A,
        RTRIM(VENDORH.name) B,
        ''供应商'' C,
	CONVERT(VARCHAR(100),SUM(PAYDTL.TOTAL/(1+GOODSH.TAXRATE))) D, 
	CONVERT(VARCHAR(100),SUM(PAYDTL.TOTAL-PAYDTL.TOTAL/(1+GOODSH.TAXRATE))) E, 
	CONVERT(VARCHAR(100),SUM(PAYDTL.TOTAL)) F,
	V_GDSORTA.SORT G,
	V_GDSORTA.NAME H,
	''RMB'' I,
	''1'' J,
	''部门'' K,
	''00'' L,
	''海滨配送中心'' M,
	''商品大类'' N,
	convert(int,GOODSH.TAXRATE) O
	FROM PAYDTL PAYDTL(NOLOCK), PAY PAY(NOLOCK), 
	VENDORH VENDORH(NOLOCK),GOODSH GOODSH(NOLOCK),v_gdsorta v_gdsorta(nolock)
	WHERE PAY.NUM = PAYDTL.NUM
	and  PAY.BILLTO = VENDORH.GID
	and  (PAY.STAT<>0)
        and  PAYDTL.GDGID = GOODSH.GID
        and  PAYDTL.GDGID = V_GDSORTA.GID
        and  GOODSH.SALE = 2
       AND CONVERT(VARCHAR(10),PAY.FILDATE,102) BETWEEN '''+@BEGINDATE+''' AND '''+ @ENDDATE+''' ' +  
	' GROUP BY VENDORH.CODE,VENDORH.name,V_GDSORTA.SORT, V_GDSORTA.NAME,GOODSH.TAXRATE')

RETURN 0






GO
