SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SHOWPAYPLAN]
(
 @PAYDATE  DATETIME,
 @ISPREPAY  INT,  --0:否，1：是
 @VDRGID  INT,
 @BALUNIT INT,
 @OCRBEGINDATE  DATETIME,
 @OCRENDDATE  DATETIME,
 @PAYBEGINDATE  DATETIME,
 @PAYENDDATE  DATETIME,
 @INSTANCE  INT,
 @EMPGID  INT,
 @DEPTCODE VARCHAR(20),
 @TAXRATE DECIMAL(24, 2),
 @MSG  VARCHAR(1500) OUTPUT
)
AS
BEGIN
 DECLARE @VCMD  VARCHAR(2000)
 DECLARE @DEPTLIMIT INT
 Declare @icode VarChar(16)
 Declare @ctype VarChar(32)
 Declare @cmsg VarChar(240)
 Declare @rtn Int
 DECLARE @SSTAT VARCHAR(100)
 DECLARE @SettleDeptMethod INT
 DECLARE @VDEPTCODE VARCHAR(10)
 DECLARE @VWRHGID  INT
 DECLARE @VVDRGID INT
 DECLARE @USERGID INT
 --zhangzhen 090513
  DECLARE @NotAllowLocalPay INT

 Declare cntr_cursor1 cursor for
   select ivccode,chgtype from TMPPAY
     where SPID = @@SPID
 SELECT @USERGID = USERGID FROM SYSTEM
 EXEC OPTREADINT 0,'AutoGetSettleDeptMethod',1,@SettleDeptMethod OUTPUT
 EXEC OPTREADINT 0,'SettleDeptLimit',0,@DEPTLIMIT OUTPUT
 EXEC OPTREADINT 3108, 'CNTR_AllowLocalPay', 0, @NotAllowLocalPay OUTPUT
-- EXEC @DEPTLIMIT = CNTRDEPTLIMIT

 DELETE FROM TMPPAY WHERE SPID = @@SPID
        SELECT @SSTAT = ' AND M.STAT = 1 '

 --供应商结算单
 SELECT @VCMD = 'INSERT INTO TMPPAY (SPID, VDRCODE, VDRNAME, VDRGID, BILLTOCODE, BILLTONAME, BILLTO, '
  + ' CHGTYPE, IVCNUM, IVCCODE, OCRDATE, PAYDATE, TOTAL, FEE, ACTTOTAL, CURTOTAL, ISORNOT, NOTE, PSR, TAXRATE, DEPT)'
  + ' SELECT @@SPID, V.CODE, V.NAME, M.BILLTO, V.CODE, V.NAME, M.BILLTO, '
  + '''供应商结算单'', NULL, M.NUM, NULL, NULL, M.AMT, 0, M.AMT-M.PYTOTAL, M.AMT-M.PYTOTAL, 0, M.NOTE, M.PSR, M.TAXRATELMT, '
 IF @DEPTLIMIT = 1
  SELECT @VCMD = @VCMD +'D.CODE '
 ELSE
  SELECT @VCMD = @VCMD +'''' + RTRIM(@DEPTCODE) + ''' '
  SELECT @VCMD = @VCMD + ' FROM PAY M(NOLOCK), VENDOR V(NOLOCK) '
  IF @DEPTLIMIT = 1
  BEGIN
   IF @SettleDeptMethod = 1
    SELECT @VCMD = @VCMD + ' , SETTLEDEPTDEPT D(NOLOCK), PAYDTL PD(NOLOCK), GOODSH (NOLOCK) '
   IF @SettleDeptMethod = 2
    SELECT @VCMD = @VCMD + ' , SETTLEDEPTVDR D(NOLOCK) '
   IF @SettleDeptMethod = 3
    SELECT @VCMD = @VCMD + ' , SETTLEDEPTWRH D(NOLOCK) '
  END
  SELECT @VCMD = @VCMD + ' WHERE M.BILLTO = V.GID '
  + @SSTAT
  + ' AND M.AMT <> M.PYTOTAL '
 IF @VDRGID IS NOT NULL
  SELECT @VCMD = @VCMD + ' AND M.BILLTO = ' + CONVERT(CHAR(20), @VDRGID)
 IF @OCRBEGINDATE IS NOT NULL
  SELECT @VCMD = @VCMD + ' AND M.FILDATE BETWEEN ' + '''' + CONVERT(CHAR(19), @OCRBEGINDATE, 20)
   + '''' + ' AND ' + '''' + CONVERT(CHAR(19), @OCRENDDATE, 20) + ''''
 IF @PAYBEGINDATE IS NOT NULL
  SELECT @VCMD = @VCMD + ' AND M.FILDATE BETWEEN ' + '''' + CONVERT(CHAR(19), @PAYBEGINDATE, 20)
   + '''' + ' AND ' + '''' + CONVERT(CHAR(19), @PAYENDDATE, 20) + ''''
 IF (@DEPTCODE IS NOT NULL) AND (@DEPTCODE<>'') AND (@DEPTLIMIT = 1)
  SELECT @VCMD = @VCMD + ' AND D.CODE = ' + '''' + @DEPTCODE + ''''
 IF @DEPTLIMIT = 1
 BEGIN
  SELECT @VCMD = @VCMD + ' AND D.CODE IN (SELECT CODE FROM SETTLEDEPTEMP(NOLOCK) '
   + ' WHERE EMPGID = ' + CONVERT(CHAR(20), @EMPGID) + ')'
  IF @SettleDeptMethod = 1
   SELECT @VCMD = @VCMD + ' AND M.NUM = PD.NUM AND GOODSH.GID = PD.GDGID AND PD.LINE = 1 AND GOODSH.F1 = D.DEPTCODE '
  IF @SettleDeptMethod = 2
   SELECT @VCMD = @VCMD + ' AND M.BILLTO = D.VDRGID '
  IF @SettleDeptMethod = 3
   SELECT @VCMD = @VCMD + ' AND M.WRH = D.WRHGID '
 END
 select @VCMD = @VCMD + ' AND M.SRC = ' + CONVERT(VARCHAR, @USERGID)
 IF @TAXRATE IS NOT NULL
   SELECT @VCMD = @VCMD + ' AND M.TAXRATELMT = ' + CONVERT(VARCHAR, @TAXRATE)
 --zhangzhen 090513
 if @NotAllowLocalPay = 1
   select @VCMD = @VCMD + ' AND ISNULL(M.CLECENT, ' + CONVERT(char(20), @usergid) + ') = ' + CONVERT(char(20), @usergid)
 
 ----增加结算中心选择非本店结算单
 SELECT @VCMD = @VCMD + ' UNION  '+
  ' SELECT @@SPID, V.CODE, V.NAME, M.BILLTO, V.CODE, V.NAME, M.BILLTO, '
  + '''供应商结算单'', NULL, M.NUM, NULL, NULL, M.AMT, 0, M.AMT-M.PYTOTAL, M.AMT-M.PYTOTAL, 0, M.NOTE, M.PSR, M.TAXRATELMT, '
 IF @DEPTLIMIT = 1
  SELECT @VCMD = @VCMD +'D.CODE '
 ELSE
  SELECT @VCMD = @VCMD +'''' + RTRIM(@DEPTCODE) + ''' '
  SELECT @VCMD = @VCMD + ' FROM PAY M(NOLOCK), VENDOR V(NOLOCK) '
  IF @DEPTLIMIT = 1
  BEGIN
   IF @SettleDeptMethod = 1
    SELECT @VCMD = @VCMD + ' , SETTLEDEPTDEPT D(NOLOCK)'
   IF @SettleDeptMethod = 2
    SELECT @VCMD = @VCMD + ' , SETTLEDEPTVDR D(NOLOCK) '
   IF @SettleDeptMethod = 3
    SELECT @VCMD = @VCMD + ' , SETTLEDEPTWRH D(NOLOCK) '
  END
  SELECT @VCMD = @VCMD + ' WHERE M.BILLTO = V.GID '
  + @SSTAT
  + ' AND M.AMT <> M.PYTOTAL '
 IF @VDRGID IS NOT NULL
  SELECT @VCMD = @VCMD + ' AND M.BILLTO = ' + CONVERT(CHAR(20), @VDRGID)
 IF @OCRBEGINDATE IS NOT NULL
  SELECT @VCMD = @VCMD + ' AND M.FILDATE BETWEEN ' + '''' + CONVERT(CHAR(19), @OCRBEGINDATE, 20)
   + '''' + ' AND ' + '''' + CONVERT(CHAR(19), @OCRENDDATE, 20) + ''''
 IF @PAYBEGINDATE IS NOT NULL
  SELECT @VCMD = @VCMD + ' AND M.FILDATE BETWEEN ' + '''' + CONVERT(CHAR(19), @PAYBEGINDATE, 20)
   + '''' + ' AND ' + '''' + CONVERT(CHAR(19), @PAYENDDATE, 20) + ''''
 IF (@DEPTCODE IS NOT NULL) AND (@DEPTCODE<>'') AND (@DEPTLIMIT = 1)
  SELECT @VCMD = @VCMD + ' AND D.CODE = ' + '''' + @DEPTCODE + ''''
 IF @DEPTLIMIT = 1
 BEGIN
  SELECT @VCMD = @VCMD + ' AND D.CODE IN (SELECT CODE FROM SETTLEDEPTEMP(NOLOCK) '
   + ' WHERE EMPGID = ' + CONVERT(CHAR(20), @EMPGID) + ')'
  IF @SettleDeptMethod = 1
   SELECT @VCMD = @VCMD + ' AND M.DEPT = D.DEPTCODE '
  IF @SettleDeptMethod = 2
   SELECT @VCMD = @VCMD + ' AND M.BILLTO = D.VDRGID '
  IF @SettleDeptMethod = 3
   SELECT @VCMD = @VCMD + ' AND M.WRH = D.WRHGID '
 END
 select @VCMD = @VCMD + ' AND M.SRC <> ' + CONVERT(VARCHAR, @USERGID) + ' AND M.CLECENT = ' + CONVERT(VARCHAR, @USERGID)
  IF @TAXRATE IS NOT NULL
    SELECT @VCMD = @VCMD + ' AND M.TAXRATELMT = ' + CONVERT(VARCHAR, @TAXRATE)
 --zhangzhen 090513
 if @NotAllowLocalPay = 1
   select @VCMD = @VCMD + ' AND ISNULL(M.CLECENT, ' + CONVERT(char(20), @usergid) + ') = ' + CONVERT(char(20), @usergid)
 EXEC(@VCMD)

 --代销结算单
 SELECT @VCMD = ' INSERT INTO TMPPAY (SPID, VDRCODE, VDRNAME, VDRGID, BILLTOCODE, BILLTONAME, BILLTO, '
  + ' CHGTYPE, IVCNUM, IVCCODE, OCRDATE, PAYDATE, TOTAL, FEE, ACTTOTAL, CURTOTAL, ISORNOT, NOTE, PSR, DEPT)'
  + ' SELECT @@SPID, V.CODE, V.NAME, M.BILLTO, V.CODE, V.NAME, M.BILLTO, '
  + '''代销结算单'', NULL, M.NUM, NULL, NULL, M.AMT, 0, M.AMT - M.PAYTOTAL, M.AMT - M.PAYTOTAL, 0, M.NOTE, M.PSR, '
 IF @DEPTLIMIT = 1
  SELECT @VCMD = @VCMD +'D.CODE '
 ELSE
  SELECT @VCMD = @VCMD +'''' + RTRIM(@DEPTCODE) + ''' '
 SELECT @VCMD = @VCMD + ' FROM SVI M(NOLOCK), VENDOR V(NOLOCK) '
  IF @DEPTLIMIT = 1
  BEGIN
   IF @SettleDeptMethod = 1
    SELECT @VCMD = @VCMD + ' , SETTLEDEPTDEPT D(NOLOCK), SVIDTL PD(NOLOCK), GOODSH (NOLOCK) '
   IF @SettleDeptMethod = 2
    SELECT @VCMD = @VCMD + ' , SETTLEDEPTVDR D(NOLOCK) '
   IF @SettleDeptMethod = 3
    SELECT @VCMD = @VCMD + ' , SETTLEDEPTWRH D(NOLOCK) '
  END
--  ELSE
--   SELECT @VCMD = @VCMD + ' , SETTLEDEPT D(NOLOCK) '
  SELECT @VCMD = @VCMD + ' WHERE M.BILLTO = V.GID '
  + @SSTAT
  + ' AND M.CLS = ''代销'''
  + ' AND M.AMT <> M.PAYTOTAL '
 IF @VDRGID IS NOT NULL
  SELECT @VCMD = @VCMD + ' AND M.BILLTO = ' + CONVERT(CHAR(20), @VDRGID)
 IF @OCRBEGINDATE IS NOT NULL
  SELECT @VCMD = @VCMD + ' AND M.FILDATE BETWEEN ' + '''' + CONVERT(CHAR(19), @OCRBEGINDATE, 20)
   + '''' + ' AND ' + '''' + CONVERT(CHAR(19), @OCRENDDATE, 20) + ''''
 IF @PAYBEGINDATE IS NOT NULL
  SELECT @VCMD = @VCMD + ' AND M.FILDATE BETWEEN ' + '''' + CONVERT(CHAR(19), @PAYBEGINDATE, 20)
   + '''' + ' AND ' + '''' + CONVERT(CHAR(19), @PAYENDDATE, 20) + ''''
 IF (@DEPTCODE IS NOT NULL) AND (@DEPTCODE<>'') AND (@DEPTLIMIT = 1)
  SELECT @VCMD = @VCMD + ' AND D.CODE = ' + '''' + @DEPTCODE + ''''
 IF @DEPTLIMIT = 1
 BEGIN
  SELECT @VCMD = @VCMD + ' AND D.CODE IN (SELECT CODE FROM SETTLEDEPTEMP(NOLOCK) '
   + ' WHERE EMPGID = ' + CONVERT(CHAR(20), @EMPGID) + ')'
  IF @SettleDeptMethod = 1
   SELECT @VCMD = @VCMD + ' AND M.NUM = PD.NUM AND M.CLS = PD.CLS AND GOODSH.GID = PD.GDGID AND PD.LINE = 0 AND GOODSH.F1 = D.DEPTCODE '
  IF @SettleDeptMethod = 2
   SELECT @VCMD = @VCMD + ' AND M.BILLTO = D.VDRGID  '
  IF @SettleDeptMethod = 3
   SELECT @VCMD = @VCMD + ' AND M.WRH = D.WRHGID '
 END
  --IF @TAXRATE IS NOT NULL
    --SELECT @VCMD = @VCMD + ' AND M.TAXRATELMT = ' + CONVERT(VARCHAR, @TAXRATE)
 --EXEC(@VCMD)

  --联销结算单
 SELECT @VCMD = ' INSERT INTO TMPPAY (SPID, VDRCODE, VDRNAME, VDRGID, BILLTOCODE, BILLTONAME, BILLTO, '
  + ' CHGTYPE, IVCNUM, IVCCODE, OCRDATE, PAYDATE, TOTAL, FEE, ACTTOTAL, CURTOTAL, ISORNOT, NOTE, PSR, DEPT)'
  + ' SELECT @@SPID, V.CODE, V.NAME, M.BILLTO, V.CODE, V.NAME, M.BILLTO, '
  + '''联销结算单'', NULL, M.NUM, NULL, NULL, M.AMT, 0, M.AMT - M.PAYTOTAL, M.AMT - M.PAYTOTAL, 0, M.NOTE, M.PSR, '
 IF @DEPTLIMIT = 1
  SELECT @VCMD = @VCMD +'D.CODE '
 ELSE
  SELECT @VCMD = @VCMD +'''' + RTRIM(@DEPTCODE) + ''' '
 SELECT @VCMD = @VCMD + ' FROM SVI M(NOLOCK), VENDOR V(NOLOCK) '
  IF @DEPTLIMIT = 1
  BEGIN
   IF @SettleDeptMethod = 1
    SELECT @VCMD = @VCMD + ' , SETTLEDEPTDEPT D(NOLOCK), SVIDTL PD(NOLOCK), GOODSH (NOLOCK) '
   IF @SettleDeptMethod = 2
    SELECT @VCMD = @VCMD + ' , SETTLEDEPTVDR D(NOLOCK) '
   IF @SettleDeptMethod = 3
    SELECT @VCMD = @VCMD + ' , SETTLEDEPTWRH D(NOLOCK) '
  END
--  ELSE
--   SELECT @VCMD = @VCMD + ' , SETTLEDEPT D(NOLOCK) '
  SELECT @VCMD = @VCMD + ' WHERE M.BILLTO = V.GID '
  + @SSTAT
  + ' AND M.CLS = ''联销'''
  + ' AND M.AMT <> M.PAYTOTAL '
 IF @VDRGID IS NOT NULL
  SELECT @VCMD = @VCMD + ' AND M.BILLTO = ' + STR(@VDRGID)
 IF @OCRBEGINDATE IS NOT NULL
  SELECT @VCMD = @VCMD + ' AND M.FILDATE BETWEEN ' + '''' + CONVERT(CHAR(19), @OCRBEGINDATE, 20)
   + '''' + ' AND ' + '''' + CONVERT(CHAR(19), @OCRENDDATE, 20) + ''''
 IF @PAYBEGINDATE IS NOT NULL
  SELECT @VCMD = @VCMD + ' AND M.FILDATE BETWEEN ' + '''' + CONVERT(CHAR(19), @PAYBEGINDATE, 20)
   + '''' + ' AND ' + '''' + CONVERT(CHAR(19), @PAYENDDATE, 20) + ''''
 IF (@DEPTCODE IS NOT NULL) AND (@DEPTCODE<>'') AND (@DEPTLIMIT = 1)
  SELECT @VCMD = @VCMD + ' AND D.CODE = ' + '''' + @DEPTCODE + ''''
 IF @DEPTLIMIT = 1
 BEGIN
  SELECT @VCMD = @VCMD + ' AND D.CODE IN (SELECT CODE FROM SETTLEDEPTEMP(NOLOCK) '
   + ' WHERE EMPGID = ' + CONVERT(CHAR(20), @EMPGID) + ')'
  IF @SettleDeptMethod = 1
   SELECT @VCMD = @VCMD + ' AND M.NUM = PD.NUM AND M.CLS = PD.CLS AND GOODSH.GID = PD.GDGID AND PD.LINE = 0 AND GOODSH.F1 = D.DEPTCODE '
  IF @SettleDeptMethod = 2
   SELECT @VCMD = @VCMD + ' AND M.BILLTO = D.VDRGID  '
  IF @SettleDeptMethod = 3
   SELECT @VCMD = @VCMD + ' AND M.WRH = D.WRHGID '
 END
  --IF @TAXRATE IS NOT NULL
    --SELECT @VCMD = @VCMD + ' AND M.TAXRATELMT = ' + CONVERT(VARCHAR, @TAXRATE)
 --EXEC(@VCMD)

  --费用单
 SELECT @VCMD = ' INSERT INTO TMPPAY (SPID, VDRCODE, VDRNAME, VDRGID, BILLTOCODE, BILLTONAME, BILLTO, '
  + ' CHGTYPE, IVCNUM, IVCCODE, OCRDATE, PAYDATE, TOTAL, FEE, ACTTOTAL, CURTOTAL, ISORNOT, NOTE, PSR, DEPT, TAXRATE)'
  + ' SELECT @@SPID, V.CODE, V.NAME, M.VENDOR, V.CODE, V.NAME, M.VENDOR, '
  + ' ''费用单'', NULL, M.NUM, M.OCRDATE, M.SIGNDATE, M.PAYDIRECT * M.REALAMT, 0, '
  + ' M.PAYDIRECT * (M.REALAMT-M.PAYTOTAL), M.PAYDIRECT * (M.REALAMT-M.PAYTOTAL), 0, M.FIXNOTE, E.GID, M.DEPT, TAXRATE '
  + ' FROM CHGBOOK M(NOLOCK), VENDOR V(NOLOCK), EMPLOYEEH E(NOLOCK) '
  + ' WHERE M.VENDOR = V.GID '
  + ' AND ISNULL(E.GID,1) = M.PSR ' --采购员关联EMPLOYEEH
  + ' AND M.STAT = 500 '
  + ' AND M.REALAMT <> M.PAYTOTAL '
  + ' AND M.GATHERINGMODE = ''冲扣货款'' '
 IF @VDRGID IS NOT NULL
  SELECT @VCMD = @VCMD + ' AND M.VENDOR = ' + STR(@VDRGID)
 IF @OCRBEGINDATE IS NOT NULL
  SELECT @VCMD = @VCMD + ' AND M.OCRDATE BETWEEN ' + '''' + CONVERT(CHAR(19), @OCRBEGINDATE, 20)
   + '''' + ' AND ' + '''' + CONVERT(CHAR(19), @OCRENDDATE, 20) + ''''
 IF @PAYBEGINDATE IS NOT NULL
  SELECT @VCMD = @VCMD + ' AND M.PAYDATE BETWEEN ' + '''' + CONVERT(CHAR(19), @PAYBEGINDATE, 20)
   + '''' + ' AND ' + '''' + CONVERT(CHAR(19), @PAYENDDATE, 20) + ''''
 IF (@DEPTCODE IS NOT NULL) AND (@DEPTCODE<>'') AND (@DEPTLIMIT = 1)
  SELECT @VCMD = @VCMD + ' AND M.DEPT = ' + '''' + @DEPTCODE + ''''
 IF @DEPTLIMIT = 1   --员工可以操作的单据必须是所属员工结算组中的信息
  SELECT @VCMD = @VCMD + ' AND M.DEPT IN (SELECT CODE FROM SETTLEDEPTEMP(NOLOCK) '
   + ' WHERE EMPGID = ' + CONVERT(CHAR(20), @EMPGID) + ')'
  IF @TAXRATE IS NOT NULL
    SELECT @VCMD = @VCMD + ' AND M.TAXRATE = ' + CONVERT(VARCHAR, @TAXRATE)
  --zhangzhen 090513
  if @NotAllowLocalPay = 1
    select @VCMD = @VCMD + ' AND ISNULL(M.CASHCENTER, ' + CONVERT(char(20), @usergid) + ') = ' + CONVERT(char(20), @usergid)
 EXEC(@VCMD)

 --预付款单
 SELECT @VCMD = ' INSERT INTO TMPPAY (SPID, VDRCODE, VDRNAME, VDRGID, BILLTOCODE, BILLTONAME, BILLTO, '
  + ' CHGTYPE, IVCNUM, IVCCODE, OCRDATE, PAYDATE, TOTAL, FEE, ACTTOTAL, CURTOTAL, ISORNOT, NOTE, PSR, DEPT, TAXRATE)'
  + ' SELECT @@SPID, V.CODE, V.NAME, M.VENDOR, V.CODE, V.NAME, M.VENDOR, '
  + ' ''预付款单'', NULL, M.NUM, M.OCRDATE, NULL, M.TOTAL, 0, M.TOTAL-M.TOTALOFF, M.TOTAL-M.TOTALOFF, 0, M.NOTE, E.GID, M.DEPT, 17 '
  + ' FROM CNTRPREPAY M(NOLOCK), VENDOR V(NOLOCK), EMPLOYEEH E(NOLOCK) '
  + ' WHERE M.VENDOR = V.GID '
  + ' AND E.CODE = M.PSR '
  + ' AND M.STAT = 900 '
  + ' AND M.TOTAL <> M.TOTALOFF '
 IF @VDRGID IS NOT NULL
  SELECT @VCMD = @VCMD + ' AND M.VENDOR = ' + STR(@VDRGID)
 IF @OCRBEGINDATE IS NOT NULL
  SELECT @VCMD = @VCMD + ' AND M.OCRDATE BETWEEN ' + '''' + CONVERT(CHAR(19), @OCRBEGINDATE, 20)
   + '''' + ' AND ' + '''' + CONVERT(CHAR(19), @OCRENDDATE, 20) + ''''
 IF @PAYBEGINDATE IS NOT NULL
  SELECT @VCMD = @VCMD + ' AND M.OCRDATE BETWEEN ' + '''' + CONVERT(CHAR(19), @PAYBEGINDATE, 20)
   + '''' + ' AND ' + '''' + CONVERT(CHAR(19), @PAYENDDATE, 20) + ''''
 IF (@DEPTCODE IS NOT NULL) AND (@DEPTCODE<>'') AND (@DEPTLIMIT = 1)
  SELECT @VCMD = @VCMD + ' AND M.DEPT = ' + '''' + @DEPTCODE + ''''
 IF @DEPTLIMIT = 1    --员工可以操作的单据必须是所属员工结算组中的信息
  SELECT @VCMD = @VCMD + ' AND M.DEPT IN (SELECT CODE FROM SETTLEDEPTEMP(NOLOCK) '
   + ' WHERE EMPGID = ' + CONVERT(CHAR(20), @EMPGID) + ')'
 --zhangzhen 090513
 if @NotAllowLocalPay = 1
   select @VCMD = @VCMD + ' AND ISNULL(M.CLECENT, ' + CONVERT(char(20), @usergid) + ') = ' + CONVERT(char(20), @usergid)
 EXEC(@VCMD)

 if OBJECT_ID('tmpGenDelInfo') IS NULL
   Create table tmpGenDelInfo (SPID INT, NUM Varchar(16), ChgType VarChar(32), Reason Varchar(255) null)  --Fanduoyi
 DELETE FROM tmpGenDelInfo WHERE SPID = @@SPID
 select @MSG = ''
 Open cntr_cursor1
 Fetch next from cntr_cursor1 into @icode,@ctype
 while @@fetch_status = 0
 begin
   select @rtn = 0
   select @ctype = Rtrim(@ctype)
   select @ctype = Ltrim(@ctype)
   EXEC @rtn = CntrCheckBill @ctype,@icode,@cmsg output
   if @rtn > 0
   begin
     -- select @MSG = @MSG + '*' + isnull(@cmsg, '')
     -- select * from #x where NUM = @icode
     select @MSG = NUM from tmpGenDelInfo where NUM = @icode and ChgType = @ctype
     BEGIN TRANSACTION
     if @@ROWCOUNT = 0
       Insert Into tmpGenDelInfo values (@@SPID, @icode, @ctype, @cmsg)
     delete from TMPPAY where current of cntr_cursor1
     Commit
   end
   Fetch next from cntr_cursor1 into @icode,@ctype
 end
 close cntr_cursor1
 deallocate cntr_cursor1

 RETURN 0
END
GO
