SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE PROCEDURE [dbo].[CNTRPREPAYCHK]
(
	@NUM		VARCHAR(14),
	@OPER		VARCHAR(50),
	@CLS		VARCHAR(10),
	@TOSTAT		INT,
	@MSG	VARCHAR(255) OUTPUT
)
AS
BEGIN
	DECLARE
	@VRET		INT
	,@VSTAT		INT
	,@VACTNAME	VARCHAR(20)
	,@VSTATNAME	VARCHAR(50)

	SELECT @VRET = 0
	SELECT @VSTAT = STAT FROM CNTRPREPAY WHERE NUM = @NUM
	--IF SQLCODE = -54 THEN POERR_MSG := '该单据其他人正在处理中，请稍候进行'; RETURN(1); END IF;

	IF @VSTAT IN (0) AND @TOSTAT IN (100,900,600)
	BEGIN
		EXEC @VRET = CHKCNTRPREPAYTO100 @NUM, @OPER, @MSG
		IF @VRET <> 0 RETURN @VRET
		IF @TOSTAT = 100 RETURN 0
	END
	IF @VSTAT IN (0,100) AND @TOSTAT IN (900,600)
	BEGIN
		EXEC @VRET = CHKCNTRPREPAYTO900 @NUM, @OPER, @MSG
		IF @VRET <> 0 RETURN @VRET
		IF @TOSTAT = 900 RETURN 0
	END
	IF @VSTAT IN (0,100,900) AND @TOSTAT IN (600)
	BEGIN
		EXEC @VRET = CHKCNTRPREPAYTO600 @NUM, @OPER, @MSG
		IF @VRET <> 0 RETURN @VRET
		IF @TOSTAT = 600 RETURN 0
	END

	SELECT @VACTNAME = ACTNAME FROM MODULESTAT WHERE NO = @TOSTAT
	SELECT @VSTATNAME = STATNAME FROM MODULESTAT WHERE NO = @VSTAT
	SELECT @MSG = '不能' + @VACTNAME + '状态为' + @VSTATNAME + '的应付扣款单'
	RETURN 1
END 
GO
