SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[NETALCDIFFDEL] (
  @BILL_ID INT,
  @SRC_ID INT,
  @OPER CHAR(30),
  @MSG VARCHAR(255) OUTPUT
) AS
BEGIN
  DELETE FROM NALCDIFFDTL WHERE SRC = @SRC_ID AND ID = @BILL_ID
  DELETE FROM NALCDIFF WHERE SRC = @SRC_ID AND ID = @BILL_ID
  RETURN 0
END
GO
