SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CHKGdSaleAdj_TO100]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS	 CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
	DECLARE @STAT INT, @I INT, @SSQL VARCHAR(255), @USERGID INT, @USERPROPERTY INT, 
	        @SRC INT, @PREORDSET VARCHAR(20), @LAUNCH DATETIME, @ARET INT
	SELECT @USERGID = USERGID FROM SYSTEM
	SELECT @USERPROPERTY = PROPERTY FROM STORE WHERE GID = @USERGID
	SELECT @STAT = STAT, @SRC = SRC, @LAUNCH = LAUNCH FROM GdSaleAdj WHERE NUM = @NUM
	IF @USERPROPERTY & 16 <> 16 
	BEGIN
		SET @MSG = '非总部不能审核'
		RAISERROR('非总部不能审核',16,1)
		RETURN(-1)
	END
	UPDATE GdSaleAdj SET
		STAT = 100,
		CHKDATE = GETDATE(),
		CHECKER = @OPER,  --审批人
		LSTUPDTIME = GETDATE()
	WHERE NUM = @NUM
	SET @ARET = 0
	--如果LAUNCH为空、或者生效时间比当前时间小，就 CHKGdSaleAdj_TO800
    IF @LAUNCH IS NOT NULL
    BEGIN
        IF @LAUNCH < GETDATE()
        BEGIN
            EXEC @ARET = CHKGdSaleAdj_TO800 @NUM, @OPER, @CLS, @TOSTAT, @MSG OUTPUT
            IF @ARET<>0 RETURN @ARET
        END
    END
    ELSE
    BEGIN
        EXEC @ARET = CHKGdSaleAdj_TO800 @NUM, @OPER, @CLS, @TOSTAT, @MSG OUTPUT
        IF @ARET<>0 RETURN @ARET
    END
	EXEC GdSaleAdjADDLOG @NUM,100,'',@OPER
	RETURN 0
END
GO
