SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PCT_CNTR_NETDELETE](
  @BILL_ID INT,
  @SRC_ID INT,
  @OPER VARCHAR(50),
  @MSG VARCHAR(255) OUTPUT
) AS
BEGIN
  DELETE FROM NCTSCOPE WHERE SRC = @SRC_ID AND ID = @BILL_ID
  DELETE FROM NCTCHGDEF WHERE SRC = @SRC_ID AND ID = @BILL_ID
  DELETE FROM NCTCHGDEFFIX WHERE SRC = @SRC_ID AND ID = @BILL_ID
  DELETE FROM NCTCHGDEFRATE WHERE SRC = @SRC_ID AND ID = @BILL_ID
  DELETE FROM NCTDATASRC WHERE SRC = @SRC_ID AND ID = @BILL_ID
  DELETE FROM NCTCHGDATASRC WHERE SRC = @SRC_ID AND ID = @BILL_ID
  DELETE FROM NCTCNTR WHERE SRC = @SRC_ID AND ID = @BILL_ID
  DELETE FROM NCTCNTRDTL WHERE SRC = @SRC_ID AND ID = @BILL_ID
  DELETE FROM NCTCNTRDTLDATASRC WHERE SRC = @SRC_ID AND ID = @BILL_ID
  DELETE FROM NCTCNTRFIXDTL WHERE SRC = @SRC_ID AND ID = @BILL_ID
  DELETE FROM NCTCNTRFIXSTORE WHERE SRC = @SRC_ID AND ID = @BILL_ID
  DELETE FROM NCTCNTRFIXDATE WHERE SRC = @SRC_ID AND ID = @BILL_ID
  DELETE FROM NCTCNTRRATEDTL WHERE SRC = @SRC_ID AND ID = @BILL_ID
  DELETE FROM NCTCNTRRATEDISC WHERE SRC = @SRC_ID AND ID = @BILL_ID
  DELETE FROM NCTCNTRRATESTORE WHERE SRC = @SRC_ID AND ID = @BILL_ID
  DELETE FROM NCTCNTRRATEGOODS WHERE SRC = @SRC_ID AND ID = @BILL_ID
  DELETE FROM NCTCNTRRATESTOREGD WHERE SRC = @SRC_ID AND ID = @BILL_ID
  DELETE FROM NCTCNTRRATESTOREGDDISC WHERE SRC = @SRC_ID AND ID = @BILL_ID
  DELETE FROM NCTCNTRRATEGUARDDISC WHERE SRC = @SRC_ID AND ID = @BILL_ID
  DELETE FROM NCTCNTRRATEGUARDCHG WHERE SRC = @SRC_ID AND ID = @BILL_ID
  DELETE FROM NCTCNTRRATEBYMONTHDISC WHERE SRC = @SRC_ID AND ID = @BILL_ID
  DELETE FROM NCTCNTRRATEBYMONTHSTOREGDDISC WHERE SRC = @SRC_ID AND ID = @BILL_ID
  DELETE FROM NCTCNTRRATECONDPLAN WHERE SRC = @SRC_ID AND ID = @BILL_ID --zz 090508
  DELETE FROM NCTCNTRBRAND WHERE SRC = @SRC_ID AND ID = @BILL_ID --zhujieD
  DELETE FROM NCNTRGROUP WHERE SRC = @SRC_ID AND ID = @BILL_ID
  DELETE FROM NGROUPCNTR WHERE SRC = @SRC_ID AND ID = @BILL_ID
  RETURN 0
END

GO
