SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

/* 调用时如果没有参数，则执行整体同步 */
CREATE PROCEDURE [dbo].[OUTBILLSYNC]
@BILL CHAR(10) = NULL,
@CLS CHAR(10) = NULL,
@NUM CHAR(12) = NULL
AS
BEGIN
	DECLARE @IO_BILL CHAR(10), @IO_CLS CHAR(10), @IO_NUM CHAR(12),
	@SRC_INVNUM CHAR(10),
	@SRC_STAT SMALLINT,
	@SRC_NUM CHAR(10),
	@SRC_SETTLENO INT,
	@SRC_WRH INT,
	@SRC_DSPMODE SMALLINT,
	@SRC_VDRCLT INT,
	@SRC_DSPDATE DATETIME,
	@SRC_CONTACTOR VARCHAR(50),
	@SRC_TEL VARCHAR(40),
	@SRC_ADDR VARCHAR(100),
	@SRC_NEARBY VARCHAR(50),
	@SRC_CHECKER INT,
	@SRC_CHKDATE DATETIME,
	@SRC_PRECHECKER INT,
	@SRC_PRECHKDATE DATETIME,
	@SRC_GEN INT,
	@SRC_GENBILL CHAR(10),
	@SRC_GENCLS CHAR(10),
	@SRC_GENNUM CHAR(12),
	@SRC_CLS CHAR(10),
	@SRC_POSNOCLS CHAR(10),
	@SRC_FLOWNO CHAR(12),
	@SRC_SRC INT

	DECLARE @USERGID INT

	SELECT @USERGID = USERGID FROM SYSTEM

	/* 处理单张单据 */
	IF @BILL IS NOT NULL AND @CLS IS NOT NULL AND @NUM IS NOT NULL
	BEGIN
		IF @BILL = 'DIRALC' AND @CLS <> '直配进退'
		BEGIN
			RAISERROR('调用存储过程OUTBILLSYNC的参数@CLS错误', 16, 1)
			RETURN(1)
		END

		IF NOT EXISTS (SELECT 1 FROM INOUTBILL WHERE BILL = @BILL AND CLS = @CLS
			AND NUM = @NUM)
		BEGIN
			RAISERROR('指定的单据不存在', 16, 1)
			RETURN(1)
		END

		/* 提货单 */
		IF  @BILL IN ('STKOUT', 'STKINBCK', 'DIRALC', 'RTL')
		BEGIN
			SELECT @SRC_STAT = STAT,
			@SRC_INVNUM = INVNUM,
			@SRC_SETTLENO = SETTLENO,
			@SRC_WRH = WRH,
			@SRC_VDRCLT = NULL,
			@SRC_CHECKER = NULL,
			@SRC_CHKDATE = NULL,
			@SRC_PRECHECKER = FILLER,
			@SRC_PRECHKDATE = CREATETIME,
			@SRC_GEN = NULL,
			@SRC_GENBILL = NULL,
			@SRC_GENCLS = NULL,
			@SRC_GENNUM = NULL,
			@SRC_SRC = SRC,
			@SRC_NUM = NUM
			FROM DSP WHERE CLS = @BILL AND POSNOCLS = @CLS AND FLOWNO = @NUM

			IF @SRC_SRC <> @USERGID
			BEGIN
				RAISERROR('指定的提货单不是本店单据', 16, 1)
				RETURN(1)
			END

			IF @SRC_STAT = 3
			BEGIN
				DELETE FROM INOUTBILL WHERE BILL = @BILL AND CLS = @CLS AND NUM = @NUM
				RETURN(0)
			END

			IF @BILL = 'STKOUT'
				SELECT @SRC_VDRCLT = CLIENT,
				@SRC_GEN = GEN,
				@SRC_GENBILL = GENBILL,
				@SRC_GENCLS = GENCLS,
				@SRC_GENNUM = GENNUM
				FROM STKOUT
				WHERE CLS = @CLS AND NUM = @NUM

			IF @BILL = 'STKINBCK'
				SELECT @SRC_VDRCLT = VENDOR,
				@SRC_GEN = GEN,
				@SRC_GENBILL = GENBILL,
				@SRC_GENCLS = GENCLS,
				@SRC_GENNUM = GENNUM
				FROM STKINBCK
				WHERE CLS = @CLS AND NUM = @NUM

			IF @BILL = 'DIRALC' AND @CLS = '直配进退'
				SELECT @SRC_VDRCLT = VENDOR,
				@SRC_GEN = GEN,
				@SRC_GENBILL = GENBILL,
				@SRC_GENCLS = GENCLS,
				@SRC_GENNUM = GENNUM
				FROM DIRALC
				WHERE CLS = @CLS AND NUM = @NUM

			IF @BILL = 'RTL'
				SELECT @SRC_VDRCLT = 1

			IF @SRC_STAT IN (1, 2)
				SELECT @SRC_CHECKER = FILLER,
				@SRC_CHKDATE = FILDATE
				FROM DSPREG WHERE DSPNUM = @SRC_NUM

			UPDATE INOUTBILL
			SET INVNUM = ISNULL(@SRC_INVNUM,''),
			SETTLENO = @SRC_SETTLENO,
			WRH = ISNULL(@SRC_WRH, 1),
			RECEIVER = ISNULL(@SRC_VDRCLT,1),
			CHECKER = ISNULL(@SRC_CHECKER,1),
			CHKDATE = (CASE WHEN @SRC_STAT IN (1,2) THEN @SRC_CHKDATE ELSE NULL END),
			PRECHECKER = @SRC_PRECHECKER,
			PRECHKDATE = @SRC_PRECHKDATE,
			BILLSTAT = (CASE @SRC_STAT WHEN 0 THEN 2 WHEN 1 THEN 3 WHEN 2 THEN 4 END),
			GEN = @SRC_GEN,
			GENBILL = @SRC_GENBILL,
			GENCLS = @SRC_GENCLS,
			GENNUM = @SRC_GENNUM
			WHERE BILL = @BILL AND CLS = @CLS AND NUM = @NUM
		END

        /* 内部调拨单 */
        IF @BILL = 'XF'
        BEGIN
			SELECT @SRC_STAT = STAT,
			@SRC_INVNUM = '',
			@SRC_SETTLENO = SETTLENO,
			@SRC_WRH = FROMWRH,
			@SRC_VDRCLT = TOWRH,
			@SRC_CHECKER = CHECKER,
			@SRC_CHKDATE = FILDATE,
			@SRC_PRECHECKER = CHECKER,
			@SRC_PRECHKDATE = FILDATE,
			@SRC_GEN = NULL,
			@SRC_GENBILL = NULL,
			@SRC_GENCLS = NULL,
			@SRC_GENNUM = NULL
			FROM XF WHERE NUM = @NUM

			IF @@ROWCOUNT = 0
			BEGIN
				DELETE FROM INOUTBILL WHERE BILL = @BILL AND CLS = @CLS AND NUM = @NUM
				RETURN(0)
			END

			IF @SRC_STAT NOT IN (1,8)
			BEGIN
				RAISERROR('指定单据对应的内部调拨单状态不合法', 16, 1)
				RETURN(0)
			END

			IF @SRC_STAT = 1
				UPDATE INOUTBILL
				SET SETTLENO = @SRC_SETTLENO,
				WRH = ISNULL(@SRC_WRH, 1),
				RECEIVER = ISNULL(@SRC_VDRCLT,1),
				CHECKER = ISNULL(@SRC_CHECKER,1),
				CHKDATE = @SRC_CHKDATE,
				PRECHECKER = ISNULL(@SRC_CHECKER,1),
				PRECHKDATE = @SRC_CHKDATE,
				BILLSTAT = 2,
				GEN = @SRC_GEN,
				GENBILL = @SRC_GENBILL,
				GENCLS = @SRC_GENCLS,
				GENNUM = @SRC_GENNUM
				WHERE BILL = @BILL AND CLS = @CLS AND NUM = @NUM

			IF @SRC_STAT = 8
				DELETE FROM INPITBILL WHERE BILL = @BILL AND CLS = @CLS AND NUM = @NUM
        END

		RETURN(0)
	END /* 处理单张单据 */

	/* 处理所有单据 */
	UPDATE INOUTBILL
	SET INVNUM = ISNULL(A.INVNUM,''),
	SETTLENO = A.SETTLENO,
	WRH = ISNULL(A.WRH, 1),
	RECEIVER = ISNULL(B.CLIENT,1),
	CHECKER = 1,
	CHKDATE = NULL,
	PRECHECKER = A.FILLER,
	PRECHKDATE = A.CREATETIME,
	BILLSTAT = 2,
	GEN = B.GEN,
	GENBILL = B.GENBILL,
	GENCLS = B.GENCLS,
	GENNUM = B.GENNUM
	FROM DSP A, STKOUT B
	WHERE INOUTBILL.BILL = 'STKOUT'
	AND INOUTBILL.BILL = A.CLS AND INOUTBILL.NUM = A.FLOWNO AND INOUTBILL.CLS = A.POSNOCLS
	AND A.STAT = 0
	AND A.POSNOCLS *= B.CLS AND A.FLOWNO *= B.NUM
	AND A.SRC = @USERGID

	INSERT INTO INOUTBILL (BILL, CLS, NUM, INVNUM, SETTLENO, WRH, SENDER, RECEIVER,
	CHECKER, CHKDATE, PRECHECKER, PRECHKDATE, BILLSTAT, GEN, GENBILL, GENCLS, GENNUM, SRC)
	SELECT A.CLS, A.POSNOCLS, A.FLOWNO, ISNULL(A.INVNUM,''), A.SETTLENO, ISNULL(A.WRH,1), 1,
	ISNULL(B.CLIENT,1), 1, NULL, A.FILLER, A.CREATETIME, 2, B.GEN, B.GENBILL, B.GENCLS, B.GENNUM, @USERGID
	FROM DSP A, STKOUT B
	WHERE A.CLS = 'STKOUT' AND A.STAT = 0
	AND NOT EXISTS (SELECT 1 FROM INOUTBILL WHERE BILL = A.CLS AND CLS = A.POSNOCLS AND NUM = A.FLOWNO)
	AND A.POSNOCLS *= B.CLS AND A.FLOWNO *= B.NUM
	AND A.SRC = @USERGID


	UPDATE INOUTBILL
	SET INVNUM = ISNULL(A.INVNUM,''),
	SETTLENO = A.SETTLENO,
	WRH = ISNULL(A.WRH, 1),
	RECEIVER = ISNULL(B.VENDOR,1),
	CHECKER = 1,
	CHKDATE = NULL,
	PRECHECKER = A.FILLER,
	PRECHKDATE = A.CREATETIME,
	BILLSTAT = 2,
	GEN = B.GEN,
	GENBILL = B.GENBILL,
	GENCLS = B.GENCLS,
	GENNUM = B.GENNUM
	FROM DSP A, STKINBCK B
	WHERE INOUTBILL.BILL = 'STKINBCK'
	AND INOUTBILL.BILL = A.CLS AND INOUTBILL.NUM = A.FLOWNO AND INOUTBILL.CLS = A.POSNOCLS
	AND A.STAT = 0
	AND A.POSNOCLS *= B.CLS AND A.FLOWNO *= B.NUM
	AND A.SRC = @USERGID

	INSERT INTO INOUTBILL (BILL, CLS, NUM, INVNUM, SETTLENO, WRH, SENDER, RECEIVER,
	CHECKER, CHKDATE, PRECHECKER, PRECHKDATE, BILLSTAT, GEN, GENBILL, GENCLS, GENNUM, SRC)
	SELECT A.CLS, A.POSNOCLS, A.FLOWNO, ISNULL(A.INVNUM,''), A.SETTLENO, ISNULL(A.WRH,1), 1,
	ISNULL(B.VENDOR,1), 1, NULL, A.FILLER, A.CREATETIME, 2, B.GEN, B.GENBILL, B.GENCLS, B.GENNUM, @USERGID
	FROM DSP A, STKINBCK B
	WHERE A.CLS = 'STKINBCK' AND A.STAT = 0
	AND NOT EXISTS (SELECT 1 FROM INOUTBILL WHERE BILL = A.CLS AND CLS = A.POSNOCLS AND NUM = A.FLOWNO)
	AND A.POSNOCLS *= B.CLS AND A.FLOWNO *= B.NUM
	AND A.SRC = @USERGID


	UPDATE INOUTBILL
	SET INVNUM = ISNULL(A.INVNUM,''),
	SETTLENO = A.SETTLENO,
	WRH = ISNULL(A.WRH, 1),
	RECEIVER = ISNULL(B.VENDOR,1),
	CHECKER = 1,
	CHKDATE = NULL,
	PRECHECKER = A.FILLER,
	PRECHKDATE = A.CREATETIME,
	BILLSTAT = 2,
	GEN = B.GEN,
	GENBILL = B.GENBILL,
	GENCLS = B.GENCLS,
	GENNUM = B.GENNUM
	FROM DSP A, DIRALC B
	WHERE INOUTBILL.BILL = 'DIRALC' AND INOUTBILL.CLS = '直配进退'
	AND INOUTBILL.BILL = A.CLS AND INOUTBILL.NUM = A.FLOWNO AND INOUTBILL.CLS = A.POSNOCLS
	AND A.STAT = 0
	AND A.POSNOCLS *= B.CLS AND A.FLOWNO *= B.NUM
	AND A.SRC = @USERGID

	INSERT INTO INOUTBILL (BILL, CLS, NUM, INVNUM, SETTLENO, WRH, SENDER, RECEIVER,
	CHECKER, CHKDATE, PRECHECKER, PRECHKDATE, BILLSTAT, GEN, GENBILL, GENCLS, GENNUM, SRC)
	SELECT A.CLS, A.POSNOCLS, A.FLOWNO, ISNULL(A.INVNUM,''), A.SETTLENO, ISNULL(A.WRH,1), 1,
	ISNULL(B.VENDOR,1), 1, NULL, A.FILLER, A.CREATETIME, 2, B.GEN, B.GENBILL, B.GENCLS, B.GENNUM, @USERGID
	FROM DSP A, DIRALC B
	WHERE A.CLS = 'DIRALC' AND A.POSNOCLS = '直配进退' AND A.STAT = 0
	AND NOT EXISTS (SELECT 1 FROM INOUTBILL WHERE BILL = A.CLS AND CLS = A.POSNOCLS AND NUM = A.FLOWNO)
	AND A.POSNOCLS *= B.CLS AND A.FLOWNO *= B.NUM
	AND A.SRC = @USERGID

	UPDATE INOUTBILL
	SET INVNUM = ISNULL(A.INVNUM,''),
	SETTLENO = A.SETTLENO,
	WRH = ISNULL(A.WRH, 1),
	RECEIVER = 1,
	CHECKER = 1,
	CHKDATE = NULL,
	PRECHECKER = A.FILLER,
	PRECHKDATE = A.CREATETIME,
	BILLSTAT = 2
	FROM DSP A
	WHERE INOUTBILL.BILL = 'RTL'
	AND INOUTBILL.BILL = A.CLS AND INOUTBILL.NUM = A.FLOWNO AND INOUTBILL.CLS = A.POSNOCLS
	AND A.STAT = 0
	AND A.SRC = @USERGID

	INSERT INTO INOUTBILL (BILL, CLS, NUM, INVNUM, SETTLENO, WRH, SENDER, RECEIVER,
	CHECKER, CHKDATE, PRECHECKER, PRECHKDATE, BILLSTAT, GEN, GENBILL, GENCLS, GENNUM, SRC)
	SELECT A.CLS, A.POSNOCLS, A.FLOWNO, ISNULL(A.INVNUM,''), A.SETTLENO, ISNULL(A.WRH,1), 1,
	1, 1, NULL, A.FILLER, A.CREATETIME, 2, NULL, NULL, NULL, NULL, @USERGID
	FROM DSP A
	WHERE A.CLS = 'RTL' AND A.STAT = 0
	AND NOT EXISTS (SELECT 1 FROM INOUTBILL WHERE BILL = A.CLS AND CLS = A.POSNOCLS AND NUM = A.FLOWNO)
	AND A.SRC = @USERGID

	UPDATE INOUTBILL
	SET SETTLENO = A.SETTLENO,
	WRH = A.FROMWRH,
	RECEIVER = A.TOWRH,
	CHECKER = A.CHECKER,
	CHKDATE = A.FILDATE,
	PRECHECKER = A.CHECKER,
	PRECHKDATE = A.FILDATE,
	BILLSTAT = 2
	FROM XF A
	WHERE INOUTBILL.BILL = 'XF' AND INOUTBILL.NUM = A.NUM AND INOUTBILL.CLS = ''
	AND A.STAT = 1

	INSERT INTO INOUTBILL (BILL, CLS, NUM, INVNUM, SETTLENO, WRH, SENDER, RECEIVER,
	CHECKER, CHKDATE, PRECHECKER, PRECHKDATE, BILLSTAT, GEN, GENBILL, GENCLS, GENNUM, SRC)
	SELECT 'XF', '', A.NUM, '', A.SETTLENO, A.FROMWRH, 1, A.TOWRH,
	A.CHECKER, A.FILDATE, A.CHECKER, A.FILDATE, 2, NULL, NULL, NULL, NULL, @USERGID
	FROM XF A
	WHERE A.STAT = 1
	AND NOT EXISTS (SELECT 1 FROM INOUTBILL WHERE BILL = 'XF' AND CLS = '' AND NUM = A.NUM)

	IF EXISTS (SELECT 1 FROM TEMPDB..SYSOBJECTS WHERE TYPE = 'U' AND
		NAME LIKE '#INOUTBILL_DLT%')
		DROP TABLE #INOUTBILL_DLT
	CREATE TABLE #INOUTBILL_DLT (BILL CHAR (10), CLS CHAR(10), NUM CHAR(12))

	DECLARE CURSOR1 CURSOR FOR
	SELECT BILL, CLS, NUM FROM INOUTBILL
	WHERE (BILL  = 'STKOUT' OR BILL = 'STKINBCK' OR BILL = 'RTL' OR BILL = 'XF'
	OR (BILL = 'DIRALC' AND CLS = '直配进退'))
	AND BILLSTAT IN (2,3)
	OPEN CURSOR1
	FETCH NEXT FROM CURSOR1 INTO @IO_BILL, @IO_CLS, @IO_NUM
	WHILE @@FETCH_STATUS = 0
	BEGIN
		/* 提货单 */
		IF @BILL IN ('STKOUT', 'STKINBCK', 'RTL', 'DIRALC', 'XF')
		BEGIN
			SELECT @SRC_INVNUM = INVNUM,
			@SRC_STAT = STAT,
			@SRC_NUM = NUM,
			@SRC_SETTLENO = SETTLENO,
			@SRC_WRH = WRH,
			@SRC_VDRCLT = NULL,
			@SRC_CHECKER = NULL,
			@SRC_CHKDATE = NULL,
			@SRC_PRECHECKER = FILLER,
			@SRC_PRECHKDATE = CREATETIME,
			@SRC_GEN = NULL,
			@SRC_GENBILL = NULL,
			@SRC_GENCLS = NULL,
			@SRC_GENNUM = NULL
			FROM DSP WHERE CLS = @IO_BILL AND POSNOCLS = @IO_CLS AND FLOWNO = @IO_NUM

			IF @@ROWCOUNT = 0
			BEGIN
				INSERT INTO #INOUTBILL_DLT (BILL, CLS, NUM)
				VALUES(@IO_BILL, @IO_CLS, @IO_NUM)

				GOTO NEXT_LOOP
			END

			IF @SRC_STAT = 3
			BEGIN
				INSERT INTO #INOUTBILL_DLT (BILL, CLS, NUM)
				VALUES(@IO_BILL, @IO_CLS, @IO_NUM)

				GOTO NEXT_LOOP
			END

			IF @IO_BILL = 'STKOUT'
				SELECT @SRC_VDRCLT = CLIENT,
				@SRC_GEN = GEN,
				@SRC_GENBILL = GENBILL,
				@SRC_GENCLS = GENCLS,
				@SRC_GENNUM = GENNUM
				FROM STKOUT
				WHERE CLS = @IO_CLS AND NUM = @IO_NUM

			IF @IO_BILL = 'STKINBCK'
				SELECT @SRC_VDRCLT = VENDOR,
				@SRC_GEN = GEN,
				@SRC_GENBILL = GENBILL,
				@SRC_GENCLS = GENCLS,
				@SRC_GENNUM = GENNUM
				FROM STKINBCK
				WHERE CLS = @IO_CLS AND NUM = @IO_NUM

			IF @IO_BILL = 'DIRALC' AND @IO_CLS = '直配进退'
				SELECT @SRC_VDRCLT = VENDOR,
				@SRC_GEN = GEN,
				@SRC_GENBILL = GENBILL,
				@SRC_GENCLS = GENCLS,
				@SRC_GENNUM = GENNUM
				FROM DIRALC
				WHERE CLS = @IO_CLS AND NUM = @IO_NUM

			IF @BILL = 'RTL'
				SELECT @SRC_VDRCLT = 1

			IF @SRC_STAT IN (1, 2)
				SELECT @SRC_CHECKER = FILLER,
				@SRC_CHKDATE = FILDATE
				FROM DSPREG WHERE DSPNUM = @SRC_NUM

			UPDATE INOUTBILL
			SET INVNUM = ISNULL(@SRC_INVNUM, ''),
			SETTLENO = @SRC_SETTLENO,
			WRH = ISNULL(@SRC_WRH, 1),
			RECEIVER = ISNULL(@SRC_VDRCLT,1),
			CHECKER = ISNULL(@SRC_CHECKER,1),
			CHKDATE = (CASE WHEN @SRC_STAT IN (1,2) THEN @SRC_CHKDATE ELSE NULL END),
			PRECHECKER = @SRC_PRECHECKER,
			PRECHKDATE = @SRC_PRECHKDATE,
			BILLSTAT = (CASE @SRC_STAT WHEN 0 THEN 2 WHEN 1 THEN 3 WHEN 2 THEN 4 END),
			GEN = @SRC_GEN,
			GENBILL = @SRC_GENBILL,
			GENCLS = @SRC_GENCLS,
			GENNUM = @SRC_GENNUM
			WHERE BILL = @IO_BILL AND CLS = @IO_CLS AND NUM = @IO_NUM
		END

		IF @BILL = 'XF'
		BEGIN
			SELECT @SRC_STAT = STAT,
			@SRC_NUM = NUM,
			@SRC_SETTLENO = SETTLENO,
			@SRC_WRH = FROMWRH,
			@SRC_VDRCLT = TOWRH,
			@SRC_CHECKER = CHECKER,
			@SRC_CHKDATE = FILDATE,
			@SRC_PRECHECKER = CHECKER,
			@SRC_PRECHKDATE = FILDATE,
			@SRC_GEN = NULL,
			@SRC_GENBILL = NULL,
			@SRC_GENCLS = NULL,
			@SRC_GENNUM = NULL
			FROM XF WHERE NUM = @IO_NUM

			IF @@ROWCOUNT = 0
			BEGIN
				INSERT INTO #INOUTBILL_DLT (BILL, CLS, NUM)
				VALUES(@IO_BILL, @IO_CLS, @IO_NUM)

				GOTO NEXT_LOOP
			END

			IF @SRC_STAT NOT IN (1,8)
				GOTO NEXT_LOOP

            IF @SRC_STAT = 1
				UPDATE INOUTBILL
				SET SETTLENO = @SRC_SETTLENO,
				WRH = ISNULL(@SRC_WRH, 1),
				RECEIVER = ISNULL(@SRC_VDRCLT,1),
				CHECKER = ISNULL(@SRC_CHECKER,1),
				CHKDATE = @SRC_CHKDATE,
				PRECHECKER = ISNULL(@SRC_CHECKER,1),
				PRECHKDATE = @SRC_CHKDATE,
				BILLSTAT = 2,
				GEN = @SRC_GEN,
				GENBILL = @SRC_GENBILL,
				GENCLS = @SRC_GENCLS,
				GENNUM = @SRC_GENNUM
				WHERE BILL = @IO_BILL AND CLS = @IO_CLS AND NUM = @IO_NUM

			IF @SRC_STAT = 8
				INSERT INTO #INOUTBILL_DLT (BILL, CLS, NUM)
				VALUES(@IO_BILL, @IO_CLS, @IO_NUM)
		END

		NEXT_LOOP:
		FETCH NEXT FROM CURSOR1 INTO @IO_BILL, @IO_CLS, @IO_NUM
	END
	CLOSE CURSOR1
	DEALLOCATE CURSOR1

	DELETE FROM INOUTBILL FROM #INOUTBILL_DLT WHERE INOUTBILL.BILL = #INOUTBILL_DLT.BILL
	AND INOUTBILL.CLS = #INOUTBILL_DLT.CLS AND INOUTBILL.NUM = #INOUTBILL_DLT.NUM
END

GO
