SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[RTLBCKSND]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @RCV INT,
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
  	DECLARE
   		@SRC INT,		@STAT SMALLINT,
   		@ID INT,		@USERGID INT,
		@FROMSRC INT

	SELECT @USERGID = USERGID FROM SYSTEM
	SELECT @STAT = STAT, @SRC = isnull(SRC ,@USERGID)
   		FROM RTLBCK WHERE  NUM = @NUM

  IF @STAT = 0
	BEGIN
         	SET @MSG = '未审核单据不能发送！'
         	RETURN(1)
  END

		IF @SRC <> @USERGID
		BEGIN
			SET @MSG = '非本单位生成的单据不能发送！'
			return(1)
		END
		SET @FROMSRC = @SRC

	EXECUTE GETNETBILLID @ID OUTPUT
	INSERT INTO NRTLBCK (ID, SRC, RCV, PRNTIME, NUM, SETTLENO, FILDATE,
		STAT, TOTAL, FILLER, WRH, MODNUM, INVNO, NOTE, RECCNT, CHECKER,
		TAX, DSPWRH, PROVIDER, ASSISTANT, SNDDATE, RCVTIME, NTYPE, NSTAT, NNOTE, SRCNUM)
	SELECT @ID, @SRC, @RCV, PRNTIME, NUM, SETTLENO, FILDATE,
		STAT, TOTAL, FILLER, WRH, MODNUM, INVNO, NOTE, RECCNT, CHECKER,
		TAX, DSPWRH, PROVIDER, ASSISTANT, GETDATE(), NULL, 0, 0, NULL, SRCNUM

      	FROM RTLBCK
	WHERE NUM = @NUM
	IF @@ERROR <> 0
	BEGIN
		SET @MSG = '发送'+@NUM+'单据失败'
		RETURN(1)
	END

	--开始发送
	INSERT INTO NRTLBCKDTL (SRC, ID, NUM, LINE, SETTLENO, GDGID, CASES, QTY, PRICE, DISCOUNT, AMOUNT, RTLPRC, INPRC,
	                    SUBWRH, ALCPRC, DSPSUBWRH, TAX, LXGDNAME, LXGDSPEC, LXGDMUNIT, LXGDTM, COST, COSTPRC, BlueCardCost, RedCardCost, VouAmt)
      	SELECT @SRC, @ID, NUM, LINE, SETTLENO, GDGID, CASES, QTY, PRICE, DISCOUNT, AMOUNT, RTLPRC, INPRC,
      	        SUBWRH, ALCPRC, DSPSUBWRH, TAX, LXGDNAME, LXGDSPEC, LXGDMUNIT, LXGDTM, COST, COSTPRC, BlueCardCost, RedCardCost, VouAmt
      	FROM RTLBCKDTL

	WHERE NUM = @NUM
	IF @@ERROR <> 0
	BEGIN
		SET @MSG = '发送'+@NUM+'单据失败'
		RETURN(1)
	END
	--开始发送付款明细
	INSERT INTO NRTLBCKCURDTL (ID, NUM, ITEMNO, CURRENCY, AMOUNT)
	SELECT @ID, NUM, ITEMNO, CURRENCY, AMOUNT
	FROM RTLBCKCURDTL
	WHERE NUM = @NUM
	IF @@ERROR <> 0
	BEGIN
		SET @MSG = '发送'+@NUM+'单据失败'
		RETURN(1)
	END

END
GO
