SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[MKTPRC_NETDEL](
  @BILL_ID INT,
  @SRC_ID INT,
  @OPER CHAR(30),
  @MSG VARCHAR(255) OUTPUT
) AS
BEGIN
  DELETE FROM NMKTPRCDTL WHERE SRC = @SRC_ID AND ID = @BILL_ID
  DELETE FROM NMKTPRC WHERE SRC = @SRC_ID AND ID = @BILL_ID
  RETURN 0
END
GO
