SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[DISTNOTIFYCHK]
  @PINUM CHAR(10),
  @PIEMPGID INT = 0, -- 0 = 执行该动作的员工内码
  @PITOSTAT SMALLINT = 1,  -- 1=审核；7=预审；8=发货 
  @POERRMSG VARCHAR(200)='' OUTPUT
AS
BEGIN
	DECLARE 
		@STAT SMALLINT, @RETURN_STATUS INT, 
		@CURDATE DATETIME, @CURSETTLENO INT, 
		@STAT_STR CHAR(6)
	
	SELECT @STAT=STAT FROM DISTNOTIFY WHERE NUM=@PINUM
	SELECT @CURSETTLENO = MAX(NO) FROM MONTHSETTLE
	SELECT @CURDATE = CONVERT(DATETIME, CONVERT(CHAR, GETDATE(), 102))

	IF @STAT=0 
	BEGIN
		IF @PITOSTAT=7 
		BEGIN 
			UPDATE DISTNOTIFY SET STAT = 7,FILDATE = GETDATE(),SETTLENO = @CURSETTLENO,FILLER = @PIEMPGID
				WHERE NUM = @PINUM
		END	
		IF @PITOSTAT = 1
		BEGIN
			EXECUTE @RETURN_STATUS=DISTNOTIFY_CHECK @PINUM, @CURDATE, @CURSETTLENO, @POERRMSG OUTPUT
			IF @RETURN_STATUS <> 0 RETURN(@RETURN_STATUS)
			UPDATE DISTNOTIFY SET STAT = 1,FILDATE = GETDATE(),SETTLENO = @CURSETTLENO,FILLER = @PIEMPGID
				,CHECKER=@PIEMPGID
				WHERE NUM = @PINUM
		END
		IF @PITOSTAT = 8
		BEGIN
			EXECUTE @RETURN_STATUS=DISTNOTIFY_CHECK @PINUM, @CURDATE, @CURSETTLENO, @POERRMSG OUTPUT
			IF @RETURN_STATUS <> 0 RETURN(@RETURN_STATUS)
			EXECUTE @RETURN_STATUS=DISTNOTIFY_DELIVER @PINUM, @CURDATE, @CURSETTLENO, @POERRMSG OUTPUT
			IF @RETURN_STATUS <> 0 RETURN(@RETURN_STATUS)

			UPDATE DISTNOTIFY SET STAT = 8,FILDATE = GETDATE(),SETTLENO = @CURSETTLENO,FILLER = @PIEMPGID
				,CHECKER = @PIEMPGID,DISTDATE = GETDATE(),DISTER = @PIEMPGID
				WHERE NUM = @PINUM

		END
	END
	IF @STAT = 7
	BEGIN
		IF @PITOSTAT=7 
		BEGIN 
			SELECT @POERRMSG = '已经预审的单据不需要重新预审！'
			RETURN -1
		END	
		IF @PITOSTAT = 1
		BEGIN
			EXECUTE @RETURN_STATUS=DISTNOTIFY_CHECK @PINUM, @CURDATE, @CURSETTLENO, @POERRMSG OUTPUT
			IF @RETURN_STATUS <> 0 RETURN(@RETURN_STATUS)
			UPDATE DISTNOTIFY SET STAT = 1,FILDATE = GETDATE(),SETTLENO = @CURSETTLENO,CHECKER=@PIEMPGID
				WHERE NUM = @PINUM
		END
		IF @PITOSTAT = 8
		BEGIN
			EXECUTE @RETURN_STATUS=DISTNOTIFY_CHECK @PINUM, @CURDATE, @CURSETTLENO, @POERRMSG OUTPUT
			IF @RETURN_STATUS <> 0 RETURN(@RETURN_STATUS)
			EXECUTE @RETURN_STATUS=DISTNOTIFY_DELIVER @PINUM, @CURDATE, @CURSETTLENO, @POERRMSG OUTPUT
			IF @RETURN_STATUS <> 0 RETURN(@RETURN_STATUS)

			UPDATE DISTNOTIFY SET STAT = 8,FILDATE = GETDATE(),SETTLENO = @CURSETTLENO,CHECKER = @PIEMPGID
				,DISTDATE = GETDATE(),DISTER = @PIEMPGID
				WHERE NUM = @PINUM

		END

	END
	IF @STAT = 1
	BEGIN
		IF @PITOSTAT=7 
		BEGIN 
			SELECT @POERRMSG = '已经审核的单据不能重新预审！'
			RETURN -1
		END	
		IF @PITOSTAT = 1
		BEGIN
			SELECT @POERRMSG = '已经审核的单据不需要重新审核！'
			RETURN -1

		END
		IF @PITOSTAT = 8
		BEGIN
			EXECUTE @RETURN_STATUS=DISTNOTIFY_DELIVER @PINUM, @CURDATE, @CURSETTLENO, @POERRMSG OUTPUT
			IF @RETURN_STATUS <> 0 RETURN(@RETURN_STATUS)

			UPDATE DISTNOTIFY SET STAT = 8,DISTDATE = GETDATE(),DISTER = @PIEMPGID
				WHERE NUM = @PINUM

		END

	END
	IF @STAT = 8
	BEGIN
		SELECT @POERRMSG = '已经发货的单据不能再做任何操作！'
		RETURN -1
		
	END

	RETURN(0)
END
GO
