SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[NETGIFTPRMDEL] (
  @BILL_ID INT,
  @RCV_ID INT,
  @OPER CHAR(30),
  @MSG VARCHAR(255) OUTPUT
) AS
BEGIN
  DELETE FROM NGFTPRMDTL WHERE RCV = @RCV_ID AND ID = @BILL_ID
  DELETE FROM NGFTPRMRULE WHERE RCV = @RCV_ID AND ID = @BILL_ID
  DELETE FROM NGFTPRMRULELMT WHERE RCV = @RCV_ID AND ID = @BILL_ID
  DELETE FROM NGFTPRMRULELMTDTL WHERE RCV = @RCV_ID AND ID = @BILL_ID
  DELETE FROM NGFTPRMGOODS WHERE RCV = @RCV_ID AND ID = @BILL_ID
  DELETE FROM NGFTPRMGIFT WHERE RCV = @RCV_ID AND ID = @BILL_ID
  DELETE FROM NGFTPRMGIFTDTL WHERE RCV = @RCV_ID AND ID = @BILL_ID
  DELETE FROM NGFTPRMRULEMUTEX WHERE RCV = @RCV_ID AND ID = @BILL_ID 
  DELETE FROM NGFTPRM WHERE RCV = @RCV_ID AND ID = @BILL_ID
  RETURN 0
END
GO
