SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ALCADJ_CHECK_0TO100]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE
    @RET INT, @LAUNCH DATETIME

  SELECT @LAUNCH = LAUNCH FROM ALCADJ(NOLOCK) WHERE NUM = @NUM

  UPDATE ALCADJ SET
  STAT = 100, CHKDATE = GETDATE(), CHECKER = @OPER, LSTUPDTIME = GETDATE()
  WHERE NUM = @NUM

  EXEC @RET = ALCADJ_ADDLOG @NUM, '配货方式', @TOSTAT, '审核', @OPER
  IF @RET <> 0 RETURN @RET

  IF (@LAUNCH IS NULL) OR (@LAUNCH <= GETDATE())
  BEGIN
    EXEC @RET = ALCADJ_CHECK_OCR @NUM, @OPER, @CLS, @TOSTAT, @MSG OUTPUT
    IF @RET <> 0 RETURN @RET
  END

  SET @MSG = '单据：' + @NUM + '审核成功'

  RETURN 0
END
GO
