SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[TK_OWNERINFOSND] (
	@RCV	INT ,
	@CLS   CHAR(10)
)
AS
BEGIN
	DECLARE @USERGID INT
	SELECT @USERGID = USERGID FROM SYSTEM(NOLOCK)
	
	DELETE FROM TK_NOWNERINFO WHERE TYPE = 0 AND RCV = @RCV AND CLS = @CLS
	INSERT INTO TK_NOWNERINFO(CLS, OWNERGID, SERIALNO, PIN, SRC, RCV, SNDTIME, 
		RCVTIME, TYPE, NSTAT, NNOTE)
	SELECT CLS, OWNERGID, SERIALNO, PIN, @USERGID, @RCV, GETDATE(), NULL, 0, 0, NULL
	FROM TK_OWNERINFO WHERE CLS = @CLS
	
	RETURN 0
END
GO
