SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[NPS3NOTSCOREGDSCOPE_REMOVE]
(
  @SRC INT,
  @ID  INT
)
AS
BEGIN
  DELETE FROM NPS3NOTSCOREGDSCOPE WHERE SRC = @SRC AND ID = @ID
  DELETE FROM NPS3NOTSCOREGDSCOPEDTL WHERE SRC = @SRC AND ID = @ID
END
GO
