SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[GFTPRMRCV]
(
  @BILL_ID INT,
  @RCV_ID INT,
  @OPER CHAR(30), 
  @MSG VARCHAR(255) OUTPUT
) --WITH ENCRYPTION		
AS
BEGIN
	DECLARE
		@CUR_SETTLENO INT,              @NET_NUM CHAR(14),
		@NET_STAT SMALLINT,		@FRCCHK INT,
		@NET_TYPE SMALLINT,		@RE INT,
		@MSG1 VARCHAR(255)		
		
	SELECT @CUR_SETTLENO = MAX(NO) FROM MONTHSETTLE(NOLOCK)
		
	SELECT  @NET_STAT = STAT, @NET_TYPE = TYPE, @NET_NUM = NUM
	FROM NGFTPRM(NOLOCK) WHERE ID = @BILL_ID AND RCV = @RCV_ID
	IF @@ROWCOUNT = 0 OR @NET_NUM IS NULL
	BEGIN
		SET @MSG = '[接收]单据' +  @NET_NUM + '不存在'
		RETURN 1
	END

	IF EXISTS(SELECT 1 FROM GFTPRM(NOLOCK) WHERE NUM = @NET_NUM AND STAT = @NET_STAT) 
	BEGIN
		SET @MSG = '[接收]单据' +  @NET_NUM + '已经被接收'
		RETURN 2
	END
	
	IF (SELECT MAX(USERGID) FROM SYSTEM(NOLOCK)) <>  @RCV_ID
	BEGIN
		SET @MSG = '[接收]单据' +  @NET_NUM + '接收单位不是本单位'
		RETURN 3
	END
	
	IF @NET_TYPE <> 1
	BEGIN
		SET @MSG = '[接收]单据' +  @NET_NUM + '不在接收缓冲区中'
		RETURN 4
	END
	
	IF EXISTS (SELECT 1 FROM NGFTPRMDTL WHERE RCV = @RCV_ID AND ID = @BILL_ID
	  	AND RULECODE IN (SELECT CODE FROM GFTPRMRULE(NOLOCK) WHERE STAT <> 0))
	BEGIN
		 
		SET @MSG = '[接收]单据' +  @NET_NUM + '其中已有促销规则在本地生效'
		RETURN 5 
	END
	
  	DELETE GFTPRMRULE WHERE CODE IN (SELECT CODE FROM NGFTPRMRULE)
  	DELETE GFTPRMRULELMT WHERE RCODE IN (SELECT CODE FROM NGFTPRMRULE)
  	DELETE GFTPRMRULELMTDTL WHERE RCODE IN (SELECT CODE FROM NGFTPRMRULE)
  	DELETE GFTPRMGOODS WHERE RCODE IN (SELECT CODE FROM NGFTPRMRULE)
  	DELETE GFTPRMGIFT WHERE RCODE IN (SELECT CODE FROM NGFTPRMRULE)
  	DELETE GFTPRMGIFTDTL WHERE RCODE IN (SELECT CODE FROM NGFTPRMRULE)
  	DELETE GFTPRMRULEMUTEX WHERE RCODE IN (SELECT CODE FROM NGFTPRMRULE)
  	DELETE GFTPRMDTL WHERE NUM = @NET_NUM 
  	DELETE GFTPRM WHERE NUM = @NET_NUM 

	INSERT INTO GFTPRM(NUM, STAT, FILLER, FILDATE, CHECKER, CHKDATE, 
    	BEGINTIME, ENDTIME, SRC, LSTUPDTIME, NOTE, PRNTIME, SETTLENO, RECCNT, TOPIC)
        SELECT NUM, STAT, FILLER, FILDATE, CHECKER, CHKDATE, 
    	BEGINTIME, ENDTIME, SRC, GETDATE(), NOTE, PRNTIME, @CUR_SETTLENO, RECCNT, TOPIC 
        FROM NGFTPRM(NOLOCK)
        WHERE RCV = @RCV_ID AND ID = @BILL_ID 
	
	IF @@ERROR <> 0 
	BEGIN
		SET @MSG = '[接收]接收' + @NET_NUM + '单据失败'
		RETURN 6
	END
	
	INSERT INTO GFTPRMDTL(NUM, LINE, RULECODE, NOTE)
        SELECT NUM, LINE, RULECODE, NOTE
        FROM NGFTPRMDTL(NOLOCK)
        WHERE RCV = @RCV_ID AND ID = @BILL_ID 
        
	IF @@ERROR <> 0 
	BEGIN
		SET @MSG = '[接收]接收' + @NET_NUM + '单据失败'
		RETURN 7
	END
	
	INSERT INTO GFTPRMRULE(CODE, NAME, STAT, BEGINTIME, ENDTIME, 
    	QTY, AMT, NOTE, TOPIC, REPORT)
        SELECT CODE, NAME, STAT, BEGINTIME, ENDTIME, 
    	QTY, AMT, NOTE, TOPIC, REPORT
        FROM NGFTPRMRULE(NOLOCK)
        WHERE RCV = @RCV_ID AND ID = @BILL_ID 
        
	IF @@ERROR <> 0 
	BEGIN
		SET @MSG = '[接收]接收' + @NET_NUM + '单据失败'
		RETURN 8
	END

	INSERT INTO GFTPRMRULELMT(RCODE, LMTNO, NOTE)
        SELECT RCODE, LMTNO, NOTE
        FROM NGFTPRMRULELMT(NOLOCK)
        WHERE RCV = @RCV_ID AND ID = @BILL_ID 
        
	IF @@ERROR <> 0 
	BEGIN
		SET @MSG = '[接收]接收' + @NET_NUM + '单据失败'
		RETURN 9
	END
	
	INSERT INTO GFTPRMRULELMTDTL(RCODE, LMTNO, LINE, NAME, VALUE)
        SELECT RCODE, LMTNO, LINE, NAME, VALUE
        FROM NGFTPRMRULELMTDTL(NOLOCK)
        WHERE RCV = @RCV_ID AND ID = @BILL_ID 
        
	IF @@ERROR <> 0 
	BEGIN
		SET @MSG = '[接收]接收' + @NET_NUM + '单据失败'
		RETURN 10
	END
	
	INSERT INTO GFTPRMGOODS(RCODE, LINE, GDCOND, GDCONDTEXT, FILTERCNSTR, QTY, AMT)
        SELECT RCODE, LINE, GDCOND, GDCONDTEXT, FILTERCNSTR, QTY, AMT
        FROM NGFTPRMGOODS(NOLOCK)
        WHERE RCV = @RCV_ID AND ID = @BILL_ID 
        
	IF @@ERROR <> 0 
	BEGIN
		SET @MSG = '[接收]接收' + @NET_NUM + '单据失败'
		RETURN 11
	END
	
	INSERT INTO GFTPRMGIFT(RCODE, GROUPID, QTY, AMT, AMTLMT, SUMAMT, SUMAMTLMT)
        SELECT RCODE, GROUPID, QTY, AMT, AMTLMT, SUMAMT, SUMAMTLMT
        FROM NGFTPRMGIFT(NOLOCK)
        WHERE RCV = @RCV_ID AND ID = @BILL_ID 
        
	IF @@ERROR <> 0 
	BEGIN
		SET @MSG = '[接收]接收' + @NET_NUM + '单据失败'
		RETURN 12
	END
  
	INSERT INTO GFTPRMGIFTDTL(RCODE, GROUPID, GFTGID, QTY, QTYLMT, 
    	SUMQTY, SUMQTYLMT, PAYPRC)
        SELECT RCODE, GROUPID, GFTGID, QTY, QTYLMT, 
    	SUMQTY, SUMQTYLMT, PAYPRC
        FROM NGFTPRMGIFTDTL(NOLOCK)
        WHERE RCV = @RCV_ID AND ID = @BILL_ID 
        
	IF @@ERROR <> 0 
	BEGIN
		SET @MSG = '[接收]接收' + @NET_NUM + '单据失败'
		RETURN 13
	END
	
	INSERT INTO GFTPRMRULEMUTEX(RCODE, MUTEXCODE)
        SELECT RCODE, MUTEXCODE
        FROM NGFTPRMRULEMUTEX(NOLOCK)
        WHERE RCV = @RCV_ID AND ID = @BILL_ID 
        
	IF @@ERROR <> 0 
	BEGIN
		SET @MSG = '[接收]接收' + @NET_NUM + '单据失败'
		RETURN 14
	END
   
        --RECEIVE BILL OVER
	EXEC GFTPRM_ADDLOG @NET_NUM, @NET_STAT, @OPER
	
	SELECT @FRCCHK = FRCCHK FROM NGFTPRM WHERE RCV = @RCV_ID AND ID = @BILL_ID
	IF @FRCCHK = 1
        BEGIN	
        	EXECUTE @RE = GFTPRM_CHECK @NET_NUM, @OPER, '', 100, @MSG
        	IF @RE <> 0 RETURN 15
        END
	
	DELETE FROM NGFTPRMDTL WHERE RCV = @RCV_ID AND ID = @BILL_ID
  	DELETE FROM NGFTPRMRULE WHERE RCV = @RCV_ID AND ID = @BILL_ID
  	DELETE FROM NGFTPRMRULELMT WHERE RCV = @RCV_ID AND ID = @BILL_ID
  	DELETE FROM NGFTPRMRULELMTDTL WHERE RCV = @RCV_ID AND ID = @BILL_ID
  	DELETE FROM NGFTPRMGOODS WHERE RCV = @RCV_ID AND ID = @BILL_ID
  	DELETE FROM NGFTPRMGIFT WHERE RCV = @RCV_ID AND ID = @BILL_ID
  	DELETE FROM NGFTPRMGIFTDTL WHERE RCV = @RCV_ID AND ID = @BILL_ID
  	DELETE FROM NGFTPRMRULEMUTEX WHERE RCV = @RCV_ID AND ID = @BILL_ID 
  	DELETE FROM NGFTPRM WHERE RCV = @RCV_ID AND ID = @BILL_ID
        
	SET @MSG = '单据：' + @NET_NUM + '接收成功' + @MSG
	
	RETURN 0
END
GO
