SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[DepOut_RCV](
  @BILL_ID INT,
  @SRC_ID INT,
  @OPER VARCHAR(50),
  @MSG VARCHAR(255) OUTPUT
) AS
BEGIN
  DECLARE @RCV_GID INT
  DECLARE @NET_NUM VARCHAR(14)
  DECLARE @NET_TYPE INT
  DECLARE @VRET INT
  DECLARE @STAT INT
  DECLARE @NET_VENDOR INT
  DECLARE @NET_NOTE VARCHAR(255)
  DECLARE @CFLAG INT
  DECLARE @PAYER VARCHAR(50)
  DECLARE @TOTAL MONEY
  DECLARE @LINE INT

  SELECT @RCV_GID = RCV, @NET_TYPE = TYPE, @NET_NUM = NUM, @NET_VENDOR = VENDOR,
    @NET_NOTE = NOTE, @CFLAG = CFLAG
  FROM NCNTRDPTBILL(NOLOCK) WHERE ID = @BILL_ID AND SRC = @SRC_ID
  IF @@ROWCOUNT = 0 OR @NET_NUM IS NULL
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '不存在'
    RETURN 1
  END
  
  IF @CFLAG = 0
  BEGIN 
    IF EXISTS(SELECT 1 FROM CNTRDPTBILL(NOLOCK) WHERE NUM = @NET_NUM AND CLS = '付')
    BEGIN
      SET @MSG = '[接收]单据' +  @NET_NUM + '已经被接收'
      RETURN 3
    END
  END

  IF (SELECT MAX(USERGID) FROM FASYSTEM(NOLOCK)) <>  @RCV_GID
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '接收单位不是本单位'
    RETURN 4
  END

  IF @NET_TYPE <> 1
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '不在接收缓冲区中'
    RETURN 5
  END

  IF NOT EXISTS(SELECT 1 FROM VENDOR(NOLOCK) WHERE GID = @NET_VENDOR)
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '结算单位在本地不存在'
    RETURN 6
  END
  
  IF @CFLAG = 0
  BEGIN    
    INSERT INTO CNTRDPTBILL(NUM, CLS, VENDOR, TOTAL, TOTALOFF, STAT, VDROPER, OPER, FILLER,
      FILDATE, CHECKER, PAYER, NOTE, DEPT, STSTORE, PSR, CLECENT, SNDTIME, SRC)
    SELECT NUM, CLS, VENDOR, TOTAL, TOTALOFF, STAT, VDROPER, OPER, FILLER,
      FILDATE, CHECKER, PAYER, NOTE, DEPT, STSTORE, PSR, CLECENT, NULL, SRC
    FROM NCNTRDPTBILL(NOLOCK)
      WHERE SRC = @SRC_ID AND ID = @BILL_ID
      
    INSERT INTO CNTRDPTOUTSRCDTL(NUM, LINE, SRCCLS, SRCNUM, SRCTOTAL, PAYEDAMT, CANPAYAMT,
      TOTAL, NOTE)
    SELECT NUM, LINE, SRCCLS, SRCNUM, SRCTOTAL, PAYEDAMT, CANPAYAMT, TOTAL, NOTE
    FROM NCNTRDPTOUTSRCDTL(NOLOCK)
      WHERE ID = @BILL_ID AND SRC = @SRC_ID
  END ELSE
  BEGIN
    SELECT @STAT = STAT, @PAYER = PAYER
  	 FROM NCNTRDPTBILL(NOLOCK)
    WHERE ID = @BILL_ID AND SRC = @SRC_ID

    UPDATE CNTRDPTBILL SET STAT = @STAT, PAYER = @PAYER
      WHERE NUM = @NET_NUM AND CLS = '付'

    IF EXISTS(SELECT 1 FROM NCNTRDPTOUTSRCDTL WHERE NUM = @NET_NUM)
    BEGIN
      DECLARE C_DTL CURSOR FOR
      SELECT LINE FROM NCNTRDPTOUTSRCDTL
        WHERE SRC = @SRC_ID and ID = @BILL_ID
	    OPEN C_DTL
	    FETCH NEXT from C_DTL INTO @LINE
	    WHILE @@fetch_status = 0
	    BEGIN
  	    SELECT @TOTAL = TOTAL
  	     FROM NCNTRDPTOUTSRCDTL(NOLOCK) 
  	    WHERE ID = @BILL_ID AND SRC = @SRC_ID AND LINE = @LINE

    	  UPDATE CNTRDPTOUTSRCDTL SET TOTAL = @TOTAL
    	   WHERE NUM = @NET_NUM AND LINE = @LINE

  	    FETCH NEXT FROM C_DTL INTO @LINE
  	  END
  	  CLOSE C_DTL
      DEALLOCATE C_DTL
    END
  END  
  DELETE FROM NCNTRDPTBILL WHERE ID = @BILL_ID AND SRC = @SRC_ID
  DELETE FROM NCNTRDPTOUTSRCDTL WHERE ID = @BILL_ID AND SRC = @SRC_ID
  UPDATE CNTRDPTBILL SET NOTE = @NET_NOTE WHERE NUM = @NET_NUM AND CLS = '付'
    
  SET @MSG = '单据：' + @NET_NUM + '接收成功' + @MSG
  
  RETURN 0
END
GO
