SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[POLYLTDADJ_ADD_LOG]
(
  @NUM CHAR(14),
  @STAT INT,
  @ACTION VARCHAR(401),
  @OPER VARCHAR(30)
) AS
BEGIN
  INSERT INTO POLYLTDADJLOG(NUM, STAT, MODIFIER, ACTION, TIME)
    VALUES(@NUM, @STAT, @OPER, @ACTION, GETDATE());
END
GO
