SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[LSFIFOCHK]
	@PI_NUM CHAR(10),
	@PI_LINE INT,
	@PI_WRH INT,
	@PI_GDGID INT,
	@PI_QTY MONEY,
	@PI_COST MONEY OUTPUT,
	@PI_ERRMSG VARCHAR(200) OUTPUT
AS
BEGIN
	DECLARE @AMT MONEY,@NEWSUBWRH INT
		,@SUBWRH INT

	DECLARE @RETURN_STATUS INT

	IF @PI_QTY < 0
	BEGIN
		SELECT @PI_ERRMSG = '不允许为负数'
		RETURN 1005

	END

	EXEC CLEARTEMPSUBWRH @PI_GDGID,@PI_WRH

	IF EXISTS(SELECT 1 FROM LSDTL2 WHERE  NUM = @PI_NUM AND LINE = @PI_LINE)
	BEGIN
		SELECT @PI_ERRMSG = '损耗单不能指定批次损耗'
		RETURN -1

	END

	EXEC @RETURN_STATUS = UNLOADSUBWRH_2 @PI_GDGID,@PI_WRH,@PI_QTY,@PI_COST OUTPUT
	IF @RETURN_STATUS <> 0 RETURN @RETURN_STATUS
	

	INSERT INTO LSDTL2(NUM,LINE,SUBWRH,WRH,GDGID,QTY,COST)
		SELECT @PI_NUM,@PI_LINE,SUBWRH,WRH,GDGID,QTY,COST FROM TEMPSUBWRH
			WHERE SPID = @@SPID AND GDGID = @PI_GDGID AND WRH = @PI_WRH


	SELECT @NEWSUBWRH= MIN(SUBWRH) FROM TEMPSUBWRH WHERE SPID = @@SPID AND WRH = @PI_WRH AND GDGID = @PI_GDGID


	UPDATE LSDTL SET COST = @PI_COST,SUBWRH = @NEWSUBWRH
		WHERE NUM = @PI_NUM AND LINE = @PI_LINE

	EXEC CLEARTEMPSUBWRH @PI_GDGID,@PI_WRH

	RETURN 0

END
GO
