SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE PROCEDURE [dbo].[CNTRDEPTLIMIT]
AS
BEGIN
	DECLARE @DeptRestrict INT
	EXEC OPTREADSTR 0, 'SettleDeptLimit', 0, @DeptRestrict OUTPUT
	RETURN @DeptRestrict
END
GO
