SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRMRTNPNTAGM_MODIFYTO300]
(
  @NUM VARCHAR(14),
  @TOSTAT INT,
  @OPER VARCHAR(30),
  @MSG VARCHAR(255) OUTPUT
) AS
BEGIN
  DECLARE
    @STAT INT,
    @SETTLENO INT
  SELECT @STAT = STAT FROM PRMRTNPNTAGM(NOLOCK) WHERE NUM = @NUM
  IF @@ROWCOUNT = 0
  BEGIN
    SET @MSG = '取单据失败'
    RETURN(1)
  END
  IF @STAT <> 100
  BEGIN
    SET @MSG = '不是已审核的单据，不能进行完成操作'
    RETURN(1)
  END

  SELECT @SETTLENO = MAX(NO) FROM MONTHSETTLE(NOLOCK)
  UPDATE PRMRTNPNTAGM
  SET STAT = @TOSTAT, SETTLENO = @SETTLENO, LSTUPDTIME = GETDATE(), LSTUPDOPER = @OPER
  WHERE NUM = @NUM

  EXEC PRMRTNPNTAGM_ADD_LOG @NUM, @TOSTAT, '完成', @OPER;
  RETURN(0)
END
GO
