SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[GoodsAppUPD]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS	 CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
	DECLARE @VRET INT
	DECLARE @VSTAT INT
    DECLARE @MODNUM VARCHAR(14)
    SET @VSTAT = NULL
    SELECT @VSTAT = STAT, @MODNUM = MODNUM FROM GOODSAPP WHERE NUM = @NUM
	IF @VSTAT = NULL
	BEGIN
		SET @MSG = '不存在单据:['+ @NUM +']'
		RETURN 1
	END
	IF @VSTAT<>401
	BEGIN
		SET @MSG = '不是请求总部批准的状态不能修正单据:['+ @NUM +']'
		RETURN 1
	END
	IF ISNULL(@MODNUM,'') = ''
	BEGIN
		SET @MSG = '找不到要修正的单据:['+ @MODNUM +']'
		RETURN 1
	END
	EXEC @VRET = CHKGoodsApp_40XTO411 @MODNUM, @OPER, @CLS, @TOSTAT, @MSG OUTPUT
	IF @VRET<>0
	BEGIN
		SET @MSG = '作废单据:['+ @NUM +']异常：'+@MSG
		RETURN @VRET
	END
	EXEC @VRET = CHKGoodsApp_0TO401	@NUM, @OPER, @CLS, @TOSTAT, @MSG OUTPUT
	IF @VRET<>0
	BEGIN
		SET @MSG = '改变单据:['+ @NUM +']状态到请求总部批准异常：'+@MSG
		RETURN @VRET
	END
END
GO
