SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[LTDADJSND] (
  @NUM  CHAR(14),
  @OPER INT
) AS
BEGIN
  DECLARE @STAT INT
  DECLARE @SRC INT
  DECLARE @USERGID INT
  DECLARE @STOREGID INT
  DECLARE @BILLID INT
  DECLARE @FILLER INT
  DECLARE @FILDATE DATETIME
  DECLARE @CHECKER INT
  DECLARE @ATYPE INT
  DECLARE @NOTE VARCHAR(100)
  DECLARE @RECCNT INT
  DECLARE @LAUNCH DATETIME
  DECLARE @ALCGID INT
  DECLARE @KEEPATYPE INT

  SELECT
    @STAT = STAT,
    @SRC = SRC,
    @FILLER = FILLER,
    @FILDATE = FILDATE,
    @CHECKER = CHECKER,
    @ATYPE = ATYPE,
    @NOTE = NOTE,
    @RECCNT = RECCNT,
    @LAUNCH = LAUNCH,
    @KEEPATYPE = KEEPATYPE
  FROM LTDADJ WHERE NUM = @NUM
  IF @@ROWCOUNT = 0
  BEGIN
    RAISERROR('单据%s不存在或已被他人删除', 16, 1, @NUM)
    RETURN 1
  END
  IF @STAT not in (100, 800)
  BEGIN
    RAISERROR('单据%s不是已审核单据，不能发送', 16, 1, @NUM)
    RETURN 1
  END
  SELECT @USERGID = USERGID FROM SYSTEM(NOLOCK)
  IF (@SRC <> @USERGID) AND (@SRC <> 1)
  BEGIN
    RAISERROR('单据%s不是本单位产生的单据，不能发送', 16, 1, @NUM)
    RETURN 1
  END

  /*发送到生效配送中心*/
  DECLARE C_LTDADJLAC2 CURSOR FOR
  SELECT ALCGID FROM LTDADJLACDTL2
  WHERE NUM = @NUM
  FOR READ ONLY
  OPEN C_LTDADJLAC2
  FETCH NEXT FROM C_LTDADJLAC2 INTO @ALCGID
  WHILE @@FETCH_STATUS = 0
  BEGIN
    IF @ALCGID <> @USERGID
    BEGIN
      EXEC GETNETBILLID @BILLID OUTPUT
      INSERT INTO NLTDADJ(ID, NUM, FILLER, FILDATE, CHECKER, ATYPE, NOTE, RECCNT,
    LAUNCH, SRC, SNDTIME, RCV, NNOTE, NSTAT, TYPE, RCVTIME, KEEPATYPE)
      VALUES(@BILLID, @NUM, @FILLER, @FILDATE, @CHECKER, @ATYPE, @NOTE, @RECCNT,
    @LAUNCH, @USERGID, GETDATE(), @ALCGID, NULL, 0, 0, NULL, @KEEPATYPE)
      INSERT INTO NLTDADJDTL(SRC, ID, LINE, GDGID, OLDVALUE, NEWVALUE, NOTE, OLDSALE, NEWSALE, FINISHDATE)
      SELECT @USERGID, @BILLID, LINE, GDGID, OLDVALUE, NEWVALUE, NOTE, OLDSALE, NEWSALE, FINISHDATE
      FROM LTDADJDTL WHERE NUM = @NUM
      INSERT INTO NLTDADJLACDTL(ID, NUM , STOREGID, SRC)
      SELECT @BILLID, @NUM, STOREGID, @USERGID
      FROM LTDADJLACDTL WHERE NUM = @NUM
    END
    FETCH NEXT FROM C_LTDADJLAC2 INTO @ALCGID
  END
  CLOSE C_LTDADJLAC2
  DEALLOCATE C_LTDADJLAC2

  /*发送给生效门店*/
  DECLARE C_LTDADJLAC CURSOR FOR
  SELECT STOREGID FROM LTDADJLACDTL
  WHERE NUM = @NUM AND STOREGID NOT IN (SELECT ALCGID FROM LTDADJLACDTL2) --已经在生效配送中心中的生效单位不重复发送
  FOR READ ONLY
  OPEN C_LTDADJLAC
  FETCH NEXT FROM C_LTDADJLAC INTO @STOREGID
  WHILE @@FETCH_STATUS = 0
  BEGIN
    IF @STOREGID <> @USERGID
    BEGIN
      EXEC GETNETBILLID @BILLID OUTPUT
      INSERT INTO NLTDADJ(ID, NUM, FILLER, FILDATE, CHECKER, ATYPE, NOTE, RECCNT,
    LAUNCH, SRC, SNDTIME, RCV, NNOTE, NSTAT, TYPE, RCVTIME, KEEPATYPE)
      VALUES(@BILLID, @NUM, @FILLER, @FILDATE, @CHECKER, @ATYPE, @NOTE, @RECCNT,
    @LAUNCH, @USERGID, GETDATE(), @STOREGID, NULL, 0, 0, NULL, @KEEPATYPE)
      INSERT INTO NLTDADJDTL(SRC, ID, LINE, GDGID, OLDVALUE, NEWVALUE, NOTE, OLDSALE, NEWSALE, FINISHDATE)
      SELECT @USERGID, @BILLID, LINE, GDGID, OLDVALUE, NEWVALUE, NOTE, OLDSALE, NEWSALE, FINISHDATE
      FROM LTDADJDTL WHERE NUM = @NUM
      IF NOT EXISTS(SELECT 1 FROM LTDADJLACDTL2 WHERE NUM = @NUM AND ALCGID = @STOREGID) --如果该门店不在生效配送中心中，则需要发送生效单位明细，记录只有一条，就是该门店
        INSERT INTO NLTDADJLACDTL(SRC, ID, NUM, STOREGID) VALUES(@USERGID, @BILLID, @NUM, @STOREGID)
    END
    FETCH NEXT FROM C_LTDADJLAC INTO @STOREGID
  END
  CLOSE C_LTDADJLAC
  DEALLOCATE C_LTDADJLAC
  UPDATE LTDADJ SET SNDTIME = GETDATE() WHERE NUM = @NUM
  RETURN 0
END
GO
