SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PCT_CNTR_SEND](
  @PINUM CHAR(14),
  @PIVERSION INT,
  @PIOPERGID INT,
  @POERRMSG VARCHAR(255) OUTPUT
) AS
BEGIN
  DECLARE @VRET INT
  DECLARE @ID INT
  DECLARE @RCV INT
  DECLARE @SRC INT
  DECLARE @CATEGORY VARCHAR(20)
  DECLARE @CODE VARCHAR(100)
  DECLARE @DSCODE VARCHAR(10)
  DECLARE @LINE INT
  DECLARE @ITEMNO INT
  DECLARE @ROWNO INT
  DECLARE @CALCCENTER INT
  DECLARE @NEWNUM VARCHAR(14)
  DECLARE @EXSTORE INT


  SELECT @SRC = USERGID FROM FASYSTEM(NOLOCK)
  SET @CALCCENTER = NULL
  SET @EXSTORE = NULL
  SELECT @CALCCENTER = CALCCENTER, @EXSTORE = EXSTORE
  FROM CTCNTR(NOLOCK) WHERE NUM = @PINUM AND VERSION = @PIVERSION
  IF (@CALCCENTER IS NULL OR @SRC = @CALCCENTER) AND (@EXSTORE IS NULL OR @EXSTORE = @SRC)
  BEGIN
    SET @POERRMSG = '发送动作无效，本单不需要发送'
    RETURN -1
  END

  EXEC @VRET = GENNEXTBILLNUMEX NULL, 'CTCNTR', @NEWNUM OUTPUT
  IF @VRET <> 0 RETURN @VRET
  IF SUBSTRING(@PINUM, 1, 4) <> SUBSTRING(@NEWNUM, 1, 4)
  BEGIN
    SET @POERRMSG = '发送动作无效，本单为网络单据不能发送'
    RETURN -1
  END

  UPDATE CTCNTR SET SNDTIME = GETDATE() WHERE NUM = @PINUM AND VERSION = @PIVERSION

  IF NOT (@CALCCENTER IS NULL OR @SRC = @CALCCENTER)
  BEGIN
    EXECUTE GETNETBILLID @ID OUTPUT

    --NCTSCOPE
    DECLARE C CURSOR FOR
      SELECT CATEGORY, CODE
      FROM CTSCOPE(NOLOCK)
      WHERE CODE IN (SELECT STORESCOPE FROM CTCNTRFIXSTORE(NOLOCK) WHERE NUM = @PINUM AND VERSION = @PIVERSION)
        OR CODE IN (SELECT STORESCOPE FROM CTCNTRRATESTOREGD(NOLOCK) WHERE NUM = @PINUM AND VERSION = @PIVERSION)
    OPEN C
    FETCH NEXT FROM C INTO @CATEGORY, @CODE
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTSCOPE (CATEGORY, CODE, SQLCOND, SQLTEXT, NOTE, SRC, ID)
      SELECT CATEGORY, CODE, SQLCOND, SQLTEXT, NOTE, @SRC, @ID
      FROM CTSCOPE(NOLOCK)
      WHERE CATEGORY = @CATEGORY AND CODE = @CODE

      FETCH NEXT FROM C INTO @CATEGORY, @CODE
    END
    CLOSE C
    DEALLOCATE C
    --NCTCHGDEF
    DECLARE C CURSOR FOR
      SELECT CODE
      FROM CTCHGDEF(NOLOCK)
      WHERE CODE IN (SELECT CHGCODE FROM CTCNTRDTL(NOLOCK) WHERE NUM = @PINUM AND VERSION = @PIVERSION)
    OPEN C
    FETCH NEXT FROM C INTO @CODE
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCHGDEF (CODE, NAME, NOTE, CHGCLS, MODALTYPE, AUTOCALC,
        WHENGEN, GENMETHOD, GENUNIT, GENCYCLE, GENDAYOFFSET, PAYDIRECT,
        GATHERINGMODE, TOPAYMETHOD, PAYLIMIT, FINCODE, FINNAME, STOPPED,
        PAYUNIT, DESIGNCYCLE, SRC, ID)
      SELECT CODE, NAME, NOTE, CHGCLS, MODALTYPE, AUTOCALC,
        WHENGEN, GENMETHOD, GENUNIT, GENCYCLE, GENDAYOFFSET, PAYDIRECT,
        GATHERINGMODE, TOPAYMETHOD, PAYLIMIT, FINCODE, FINNAME, STOPPED,
        PAYUNIT, DESIGNCYCLE, @SRC, @ID
      FROM CTCHGDEF(NOLOCK)
      WHERE CODE = @CODE

      FETCH NEXT FROM C INTO @CODE
    END
    CLOSE C
    DEALLOCATE C
    --NCTCHGDEFFIX
    DECLARE C CURSOR FOR
      SELECT CODE
      FROM CTCHGDEFFIX(NOLOCK)
      WHERE CODE IN (SELECT CHGCODE FROM CTCNTRDTL(NOLOCK) WHERE NUM = @PINUM AND VERSION = @PIVERSION)
    OPEN C
    FETCH NEXT FROM C INTO @CODE
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCHGDEFFIX (CODE, FIXMETHOD, AMOUNT, FEETOSTORE, SRC, ID)
      SELECT CODE, FIXMETHOD, AMOUNT, FEETOSTORE, @SRC, @ID
      FROM CTCHGDEFFIX(NOLOCK)
      WHERE CODE = @CODE

      FETCH NEXT FROM C INTO @CODE
    END
    CLOSE C
    DEALLOCATE C
    --NCTCHGDEFRATE
    DECLARE C CURSOR FOR
      SELECT CODE
      FROM CTCHGDEFRATE(NOLOCK)
      WHERE CODE IN (SELECT CHGCODE FROM CTCNTRDTL(NOLOCK) WHERE NUM = @PINUM AND VERSION = @PIVERSION)
    OPEN C
    FETCH NEXT FROM C INTO @CODE
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCHGDEFRATE (CODE, DATASRCCLS, FEEUNIT, FEECYCLE, FEEDAYOFFSET, FIXCOST,
        RATEMODE, CALCMODE, FEEPREC, ROUNDTYPE, AHEADDAYS, DISCOUNTRATE, FEETOSTORE,
        GUARDMODE, SRC, ID)
      SELECT CODE, DATASRCCLS, FEEUNIT, FEECYCLE, FEEDAYOFFSET, FIXCOST,
        RATEMODE, CALCMODE, FEEPREC, ROUNDTYPE, AHEADDAYS, DISCOUNTRATE, FEETOSTORE,
        GUARDMODE, @SRC, @ID
      FROM CTCHGDEFRATE(NOLOCK)
      WHERE CODE = @CODE

      FETCH NEXT FROM C INTO @CODE
    END
    CLOSE C
    DEALLOCATE C
    --NCTDATASRC
    DECLARE C CURSOR FOR
      SELECT CODE
      FROM CTDATASRC(NOLOCK)
      WHERE CODE IN (SELECT DSCODE FROM CTCNTRDTLDATASRC(NOLOCK) WHERE NUM = @PINUM AND VERSION = @PIVERSION)
    OPEN C
    FETCH NEXT FROM C INTO @CODE
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTDATASRC (CODE, NAME, CLS, FLAG, HDPOSVER, NOTE, MODALTYPE, SRC, ID)
      SELECT CODE, NAME, CLS, FLAG, HDPOSVER, NOTE, MODALTYPE, @SRC, @ID
      FROM CTDATASRC(NOLOCK)
      WHERE CODE = @CODE

      FETCH NEXT FROM C INTO @CODE
    END
    CLOSE C
    DEALLOCATE C
    --NCTCHGDATASRC
    DECLARE C CURSOR FOR
      SELECT CODE, DSCODE
      FROM CTCHGDATASRC(NOLOCK)
      WHERE CODE IN (SELECT CHGCODE FROM CTCNTRDTL(NOLOCK) WHERE NUM = @PINUM AND VERSION = @PIVERSION)
    OPEN C
    FETCH NEXT FROM C INTO @CODE, @DSCODE
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCHGDATASRC (CODE, DSCODE, SRC, ID)
      SELECT CODE, DSCODE, @SRC, @ID
      FROM CTCHGDATASRC(NOLOCK)
      WHERE CODE = @CODE AND DSCODE = @DSCODE

      FETCH NEXT FROM C INTO @CODE, @DSCODE
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTR
    INSERT INTO NCTCNTR (NUM, VERSION, STAT, VENDOR, SIGNDATE, BEGINDATE, ENDDATE,
      REALENDDATE, VDRSIGNER, DEPT, SIGNER, CNTRNO, FILETEXT, MODIFIER, LSTUPDTIME,
      PRNTIME, TAG, NOTE, SALECLS, GUARDAMT, UPGUARDRATE, GUARDRATE, RENT, PAYBILLCLS,
      PAYBILLTAXRATE, CUSTOMDEF, EXSTORE, AGENTMODE, SALESQ, CALCCENTER, SNDTIME, SORT,
      SRC, ID, RCV, RCVTIME, NTYPE, NSTAT, NNOTE)
    SELECT NUM, VERSION, STAT, VENDOR, SIGNDATE, BEGINDATE, ENDDATE,
      REALENDDATE, VDRSIGNER, DEPT, SIGNER, CNTRNO, FILETEXT, MODIFIER, LSTUPDTIME,
      PRNTIME, TAG, NOTE, SALECLS, GUARDAMT, UPGUARDRATE, GUARDRATE, RENT, PAYBILLCLS,
      PAYBILLTAXRATE, CUSTOMDEF, EXSTORE, AGENTMODE, SALESQ, CALCCENTER, SNDTIME, SORT,
      @SRC, @ID, CALCCENTER, NULL, 0, 0, NULL
    FROM CTCNTR(NOLOCK)
    WHERE NUM = @PINUM AND VERSION = @PIVERSION
    --NCTCNTRDTL
    DECLARE C CURSOR FOR
      SELECT LINE
      FROM CTCNTRDTL(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRDTL (NUM, VERSION, LINE, CHGCODE, GENUNIT, GENCYCLE, GENDAYOFFSET,
        FSTGENDATE, NEXTGENDATE, GATHERINGMODE, MEMO, PAYUNIT, SRC, ID)
      SELECT NUM, VERSION, LINE, CHGCODE, GENUNIT, GENCYCLE, GENDAYOFFSET,
        FSTGENDATE, NEXTGENDATE, GATHERINGMODE, MEMO, PAYUNIT, @SRC, @ID
      FROM CTCNTRDTL(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE

      FETCH NEXT FROM C INTO @LINE
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRDTLDATASRC
    DECLARE C CURSOR FOR
      SELECT LINE, DSCODE
      FROM CTCNTRDTLDATASRC(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE, @DSCODE
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRDTLDATASRC (NUM, VERSION, LINE, DSCODE, SRC, ID)
      SELECT NUM, VERSION, LINE, DSCODE, @SRC, @ID
      FROM CTCNTRDTLDATASRC(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE AND DSCODE = @DSCODE

      FETCH NEXT FROM C INTO @LINE, @DSCODE
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRFIXDTL
    DECLARE C CURSOR FOR
      SELECT LINE
      FROM CTCNTRFIXDTL(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRFIXDTL (NUM, VERSION, LINE, FEEUNIT, FEECYCLE, FSTFEEDATE,
        NEXTBEGINDATE, NEXTENDDATE, AMOUNT, SRC, ID)
      SELECT NUM, VERSION, LINE, FEEUNIT, FEECYCLE, FSTFEEDATE,
        NEXTBEGINDATE, NEXTENDDATE, AMOUNT, @SRC, @ID
      FROM CTCNTRFIXDTL(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE

      FETCH NEXT FROM C INTO @LINE
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRFIXSTORE
    DECLARE C CURSOR FOR
      SELECT LINE, ITEMNO
      FROM CTCNTRFIXSTORE(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE, @ITEMNO
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRFIXSTORE (NUM, VERSION, LINE, ITEMNO, STORESCOPE, TOTAL,
        NOTE, SRC, ID)
      SELECT NUM, VERSION, LINE, ITEMNO, STORESCOPE, TOTAL,
        NOTE, @SRC, @ID
      FROM CTCNTRFIXSTORE(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE AND ITEMNO = @ITEMNO

      FETCH NEXT FROM C INTO @LINE, @ITEMNO
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRFIXDATE
    DECLARE C CURSOR FOR
      SELECT LINE, ITEMNO
      FROM CTCNTRFIXDATE(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE, @ITEMNO
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRFIXDATE (NUM, VERSION, LINE, ITEMNO, GENDATE, TOTAL, CHGBOOKNUM,
        NOTE, SRC, ID)
      SELECT NUM, VERSION, LINE, ITEMNO, GENDATE, TOTAL, CHGBOOKNUM,
        NOTE, @SRC, @ID
      FROM CTCNTRFIXDATE(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE AND ITEMNO = @ITEMNO

      FETCH NEXT FROM C INTO @LINE, @ITEMNO
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRRATEDTL
    DECLARE C CURSOR FOR
      SELECT LINE
      FROM CTCNTRRATEDTL(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRRATEDTL (NUM, VERSION, LINE, FEEUNIT, FEECYCLE, FEEDAYOFFSET, FSTFEEDATE,
        NEXTBEGINDATE, NEXTENDDATE, FIXCOST, RATEMODE, CALCMODE, FEEPREC, ROUNDTYPE, STORESCOPE,
        GDSCOPE, GDSCOPESQL, GDSCOPETEXT, AHEADDAYS, DISCOUNTRATE, SRC, ID)
      SELECT NUM, VERSION, LINE, FEEUNIT, FEECYCLE, FEEDAYOFFSET, FSTFEEDATE,
        NEXTBEGINDATE, NEXTENDDATE, FIXCOST, RATEMODE, CALCMODE, FEEPREC, ROUNDTYPE, STORESCOPE,
        GDSCOPE, GDSCOPESQL, GDSCOPETEXT, AHEADDAYS, DISCOUNTRATE, @SRC, @ID
      FROM CTCNTRRATEDTL(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE

      FETCH NEXT FROM C INTO @LINE
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRRATEDISC
    DECLARE C CURSOR FOR
      SELECT LINE, ITEMNO
      FROM CTCNTRRATEDISC(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE, @ITEMNO
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRRATEDISC (NUM, VERSION, LINE, ITEMNO, RATE, LOWAMT, HIGHAMT, QBASE, SRC, ID)
      SELECT NUM, VERSION, LINE, ITEMNO, RATE, LOWAMT, HIGHAMT, QBASE, @SRC, @ID
      FROM CTCNTRRATEDISC(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE AND ITEMNO = @ITEMNO

      FETCH NEXT FROM C INTO @LINE, @ITEMNO
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRRATESTORE
    DECLARE C CURSOR FOR
      SELECT LINE, ITEMNO
      FROM CTCNTRRATESTORE(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE, @ITEMNO
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRRATESTORE (NUM, VERSION, LINE, ITEMNO, STOREGID, SRC, ID)
      SELECT NUM, VERSION, LINE, ITEMNO, STOREGID, @SRC, @ID
      FROM CTCNTRRATESTORE(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE AND ITEMNO = @ITEMNO

      FETCH NEXT FROM C INTO @LINE, @ITEMNO
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRRATEGOODS
    DECLARE C CURSOR FOR
      SELECT LINE, ITEMNO
      FROM CTCNTRRATEGOODS(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE, @ITEMNO
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRRATEGOODS (NUM, VERSION, LINE, ITEMNO, GDGID, SRC, ID)
      SELECT NUM, VERSION, LINE, ITEMNO, GDGID, @SRC, @ID
      FROM CTCNTRRATEGOODS(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE AND ITEMNO = @ITEMNO

      FETCH NEXT FROM C INTO @LINE, @ITEMNO
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRRATESTOREGD
    DECLARE C CURSOR FOR
      SELECT LINE, ITEMNO
      FROM CTCNTRRATESTOREGD(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE, @ITEMNO
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRRATESTOREGD (NUM, VERSION, LINE, ITEMNO, STORESCOPE, GDSCOPESQL,
        GDSCOPETEXT, NOTE, SRC, ID)
      SELECT NUM, VERSION, LINE, ITEMNO, STORESCOPE, GDSCOPESQL,
        GDSCOPETEXT, NOTE, @SRC, @ID
      FROM CTCNTRRATESTOREGD(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE AND ITEMNO = @ITEMNO

      FETCH NEXT FROM C INTO @LINE, @ITEMNO
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRRATESTOREGDDISC
    DECLARE C CURSOR FOR
      SELECT LINE, ITEMNO, ROWNO
      FROM CTCNTRRATESTOREGDDISC(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE, @ITEMNO, @ROWNO
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRRATESTOREGDDISC (NUM, VERSION, LINE, ITEMNO, ROWNO, RATE, LOWAMT,
        HIGHAMT, QBASE, SRC, ID)
      SELECT NUM, VERSION, LINE, ITEMNO, ROWNO, RATE, LOWAMT,
        HIGHAMT, QBASE, @SRC, @ID
      FROM CTCNTRRATESTOREGDDISC(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE AND ITEMNO = @ITEMNO AND ROWNO = @ROWNO

      FETCH NEXT FROM C INTO @LINE, @ITEMNO, @ROWNO
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRRATEGUARDDISC
    DECLARE C CURSOR FOR
      SELECT LINE, ITEMNO
      FROM CTCNTRRATEGUARDDISC(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE, @ITEMNO
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRRATEGUARDDISC (NUM, VERSION, LINE, ITEMNO, RATE, LOWAMT,
        HIGHAMT, QBASE, SRC, ID)
      SELECT NUM, VERSION, LINE, ITEMNO, RATE, LOWAMT,
        HIGHAMT, QBASE, @SRC, @ID
      FROM CTCNTRRATEGUARDDISC(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE AND ITEMNO = @ITEMNO

      FETCH NEXT FROM C INTO @LINE, @ITEMNO
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRRATEGUARDCHG
    DECLARE C CURSOR FOR
      SELECT LINE, ITEMNO
      FROM CTCNTRRATEGUARDCHG(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE, @ITEMNO
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRRATEGUARDCHG (NUM, VERSION, LINE, ITEMNO, OTHERCNTRNUM,
        OTHERCHGCODE, SRC, ID)
      SELECT NUM, VERSION, LINE, ITEMNO, OTHERCNTRNUM,
        OTHERCHGCODE, @SRC, @ID
      FROM CTCNTRRATEGUARDCHG(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE AND ITEMNO = @ITEMNO

      FETCH NEXT FROM C INTO @LINE, @ITEMNO
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRRATEBYMONTHDISC
    DECLARE C CURSOR FOR
      SELECT LINE, ITEMNO
      FROM CTCNTRRATEBYMONTHDISC(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE, @ITEMNO
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRRATEBYMONTHDISC (NUM, VERSION, LINE, ITEMNO, RATE, LOWDATE,
        HIGHDATE, GAMT, SRC, ID)
      SELECT NUM, VERSION, LINE, ITEMNO, RATE, LOWDATE,
        HIGHDATE, GAMT, @SRC, @ID
      FROM CTCNTRRATEBYMONTHDISC(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE AND ITEMNO = @ITEMNO

      FETCH NEXT FROM C INTO @LINE, @ITEMNO
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRRATEBYMONTHSTOREGDDISC
    DECLARE C CURSOR FOR
      SELECT LINE, ITEMNO, ROWNO
      FROM CTCNTRRATEBYMONTHSTOREGDDISC(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE, @ITEMNO, @ROWNO
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRRATEBYMONTHSTOREGDDISC (NUM, VERSION, LINE, ITEMNO, ROWNO, RATE,
        LOWDATE, HIGHDATE, GAMT, SRC, ID)
      SELECT NUM, VERSION, LINE, ITEMNO, ROWNO, RATE,
        LOWDATE, HIGHDATE, GAMT, @SRC, @ID
      FROM CTCNTRRATEBYMONTHSTOREGDDISC(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE AND ITEMNO = @ITEMNO AND ROWNO = @ROWNO

      FETCH NEXT FROM C INTO @LINE, @ITEMNO, @ROWNO
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRRATECONDPLAN zz 090508
    DECLARE C CURSOR FOR
      SELECT LINE
      FROM CTCNTRRATECONDPLAN(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE
    WHILE @@FETCH_STATUS = 0
    BEGIN
    INSERT INTO NCTCNTRRATECONDPLAN (NUM, VERSION, LINE, VENDOR, DEPT, BEGINDATE, ENDDATE, EXPAMT,
        ADDRATE, EXESTAT, EXEBILLINFO, NOTE, SRC, ID)
      SELECT NUM, VERSION, LINE, VENDOR, DEPT, BEGINDATE, ENDDATE, EXPAMT, ADDRATE, EXESTAT,
        EXEBILLINFO, NOTE, @SRC, @ID
      FROM CTCNTRRATECONDPLAN(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE

      FETCH NEXT FROM C INTO @LINE
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRBRAND
    DECLARE C CURSOR FOR
      SELECT ITEMNO
      FROM CTCNTRBRAND(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRBRAND(NUM, VERSION, ITEMNO, CODE, TYPE, STATUS, BEGINDATE, ENDDATE,
        NOTE, SRC, ID)
      SELECT NUM, VERSION, ITEMNO, CODE, TYPE, STATUS, BEGINDATE, ENDDATE,
        NOTE, @SRC, @ID
      FROM CTCNTRBRAND(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND ITEMNO = @LINE

      FETCH NEXT FROM C INTO @LINE
    END
    CLOSE C
    DEALLOCATE C
    --NCNTRGROUP
    INSERT INTO NCNTRGROUP (NUM, VERSION, VENDOR, BEGINDATE, ENDDATE, REALENDDATE,
      LSTUPDOPER, LSTUPDTIME, CHECKER, CHKDATE, STAT, TAG, NOTE, SRC, ID)
    SELECT M.NUM, M.VERSION, M.VENDOR, M.BEGINDATE, M.ENDDATE, M.REALENDDATE,
      M.LSTUPDOPER, M.LSTUPDTIME, M.CHECKER, M.CHKDATE, M.STAT, M.TAG, M.NOTE, @SRC, @ID
    FROM CNTRGROUP M(NOLOCK), GROUPCNTR D(NOLOCK)
    WHERE D.CNTRNUM = @PINUM AND D.CNTRVERSION = @PIVERSION AND M.NUM = D.NUM AND M.VERSION = D.VERSION
    --NGROUPCNTR
    INSERT INTO NGROUPCNTR (NUM, VERSION, CNTRNUM, CNTRVERSION, SRC, ID)
    SELECT NUM, VERSION, CNTRNUM, CNTRVERSION, @SRC, @ID
    FROM GROUPCNTR(NOLOCK)
    WHERE CNTRNUM = @PINUM AND CNTRVERSION = @PIVERSION
  END

  IF NOT (@EXSTORE IS NULL OR @EXSTORE = @SRC OR (@CALCCENTER IS NOT NULL AND @EXSTORE = @CALCCENTER))
  BEGIN
    EXECUTE GETNETBILLID @ID OUTPUT

    --NCTSCOPE
    DECLARE C CURSOR FOR
      SELECT CATEGORY, CODE
      FROM CTSCOPE(NOLOCK)
      WHERE CODE IN (SELECT STORESCOPE FROM CTCNTRFIXSTORE(NOLOCK) WHERE NUM = @PINUM AND VERSION = @PIVERSION)
    OPEN C
    FETCH NEXT FROM C INTO @CATEGORY, @CODE
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTSCOPE (CATEGORY, CODE, SQLCOND, SQLTEXT, NOTE, SRC, ID)
      SELECT CATEGORY, CODE, SQLCOND, SQLTEXT, NOTE, @SRC, @ID
      FROM CTSCOPE(NOLOCK)
      WHERE CATEGORY = @CATEGORY AND CODE = @CODE

      FETCH NEXT FROM C INTO @CATEGORY, @CODE
    END
    CLOSE C
    DEALLOCATE C
    --NCTCHGDEF
    DECLARE C CURSOR FOR
      SELECT CODE
      FROM CTCHGDEF(NOLOCK)
      WHERE CODE IN (SELECT CHGCODE FROM CTCNTRDTL(NOLOCK) WHERE NUM = @PINUM AND VERSION = @PIVERSION)
    OPEN C
    FETCH NEXT FROM C INTO @CODE
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCHGDEF (CODE, NAME, NOTE, CHGCLS, MODALTYPE, AUTOCALC,
        WHENGEN, GENMETHOD, GENUNIT, GENCYCLE, GENDAYOFFSET, PAYDIRECT,
        GATHERINGMODE, TOPAYMETHOD, PAYLIMIT, FINCODE, FINNAME, STOPPED,
        PAYUNIT, DESIGNCYCLE, SRC, ID)
      SELECT CODE, NAME, NOTE, CHGCLS, MODALTYPE, AUTOCALC,
        WHENGEN, GENMETHOD, GENUNIT, GENCYCLE, GENDAYOFFSET, PAYDIRECT,
        GATHERINGMODE, TOPAYMETHOD, PAYLIMIT, FINCODE, FINNAME, STOPPED,
        PAYUNIT, DESIGNCYCLE, @SRC, @ID
      FROM CTCHGDEF(NOLOCK)
      WHERE CODE = @CODE

      FETCH NEXT FROM C INTO @CODE
    END
    CLOSE C
    DEALLOCATE C
    --NCTCHGDEFFIX
    DECLARE C CURSOR FOR
      SELECT CODE
      FROM CTCHGDEFFIX(NOLOCK)
      WHERE CODE IN (SELECT CHGCODE FROM CTCNTRDTL(NOLOCK) WHERE NUM = @PINUM AND VERSION = @PIVERSION)
    OPEN C
    FETCH NEXT FROM C INTO @CODE
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCHGDEFFIX (CODE, FIXMETHOD, AMOUNT, FEETOSTORE, SRC, ID)
      SELECT CODE, FIXMETHOD, AMOUNT, FEETOSTORE, @SRC, @ID
      FROM CTCHGDEFFIX(NOLOCK)
      WHERE CODE = @CODE

      FETCH NEXT FROM C INTO @CODE
    END
    CLOSE C
    DEALLOCATE C
    --NCTCHGDEFRATE
    DECLARE C CURSOR FOR
      SELECT CODE
      FROM CTCHGDEFRATE(NOLOCK)
      WHERE CODE IN (SELECT CHGCODE FROM CTCNTRDTL(NOLOCK) WHERE NUM = @PINUM AND VERSION = @PIVERSION)
    OPEN C
    FETCH NEXT FROM C INTO @CODE
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCHGDEFRATE (CODE, DATASRCCLS, FEEUNIT, FEECYCLE, FEEDAYOFFSET, FIXCOST,
        RATEMODE, CALCMODE, FEEPREC, ROUNDTYPE, AHEADDAYS, DISCOUNTRATE, FEETOSTORE,
        GUARDMODE, SRC, ID)
      SELECT CODE, DATASRCCLS, FEEUNIT, FEECYCLE, FEEDAYOFFSET, FIXCOST,
        RATEMODE, CALCMODE, FEEPREC, ROUNDTYPE, AHEADDAYS, DISCOUNTRATE, FEETOSTORE,
        GUARDMODE, @SRC, @ID
      FROM CTCHGDEFRATE(NOLOCK)
      WHERE CODE = @CODE

      FETCH NEXT FROM C INTO @CODE
    END
    CLOSE C
    DEALLOCATE C
    --NCTDATASRC
    DECLARE C CURSOR FOR
      SELECT CODE
      FROM CTDATASRC(NOLOCK)
      WHERE CODE IN (SELECT DSCODE FROM CTCNTRDTLDATASRC(NOLOCK) WHERE NUM = @PINUM AND VERSION = @PIVERSION)
    OPEN C
    FETCH NEXT FROM C INTO @CODE
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTDATASRC (CODE, NAME, CLS, FLAG, HDPOSVER, NOTE, MODALTYPE, SRC, ID)
      SELECT CODE, NAME, CLS, FLAG, HDPOSVER, NOTE, MODALTYPE, @SRC, @ID
      FROM CTDATASRC(NOLOCK)
      WHERE CODE = @CODE

      FETCH NEXT FROM C INTO @CODE
    END
    CLOSE C
    DEALLOCATE C
    --NCTCHGDATASRC
    DECLARE C CURSOR FOR
      SELECT CODE, DSCODE
      FROM CTCHGDATASRC(NOLOCK)
      WHERE CODE IN (SELECT CHGCODE FROM CTCNTRDTL(NOLOCK) WHERE NUM = @PINUM AND VERSION = @PIVERSION)
    OPEN C
    FETCH NEXT FROM C INTO @CODE, @DSCODE
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCHGDATASRC (CODE, DSCODE, SRC, ID)
      SELECT CODE, DSCODE, @SRC, @ID
      FROM CTCHGDATASRC(NOLOCK)
      WHERE CODE = @CODE AND DSCODE = @DSCODE

      FETCH NEXT FROM C INTO @CODE, @DSCODE
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTR
    INSERT INTO NCTCNTR (NUM, VERSION, STAT, VENDOR, SIGNDATE, BEGINDATE, ENDDATE,
      REALENDDATE, VDRSIGNER, DEPT, SIGNER, CNTRNO, FILETEXT, MODIFIER, LSTUPDTIME,
      PRNTIME, TAG, NOTE, SALECLS, GUARDAMT, UPGUARDRATE, GUARDRATE, RENT, PAYBILLCLS,
      PAYBILLTAXRATE, CUSTOMDEF, EXSTORE, AGENTMODE, SALESQ, CALCCENTER, SRC, ID, SORT,
      RCV, RCVTIME, NTYPE, NSTAT, NNOTE)
    SELECT NUM, VERSION, STAT, VENDOR, SIGNDATE, BEGINDATE, ENDDATE,
      REALENDDATE, VDRSIGNER, DEPT, SIGNER, CNTRNO, FILETEXT, MODIFIER, LSTUPDTIME,
      PRNTIME, TAG, NOTE, SALECLS, GUARDAMT, UPGUARDRATE, GUARDRATE, RENT, PAYBILLCLS,
      PAYBILLTAXRATE, CUSTOMDEF, EXSTORE, AGENTMODE, SALESQ, CALCCENTER, @SRC, @ID, SORT,
      @EXSTORE, NULL, 0, 0, NULL
    FROM CTCNTR(NOLOCK)
    WHERE NUM = @PINUM AND VERSION = @PIVERSION
    --NCTCNTRDTL
    DECLARE C CURSOR FOR
      SELECT LINE
      FROM CTCNTRDTL(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRDTL (NUM, VERSION, LINE, CHGCODE, GENUNIT, GENCYCLE, GENDAYOFFSET,
        FSTGENDATE, NEXTGENDATE, GATHERINGMODE, MEMO, PAYUNIT, SRC, ID)
      SELECT NUM, VERSION, LINE, CHGCODE, GENUNIT, GENCYCLE, GENDAYOFFSET,
        FSTGENDATE, NEXTGENDATE, GATHERINGMODE, MEMO, PAYUNIT, @SRC, @ID
      FROM CTCNTRDTL(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE

      FETCH NEXT FROM C INTO @LINE
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRDTLDATASRC
    DECLARE C CURSOR FOR
      SELECT LINE, DSCODE
      FROM CTCNTRDTLDATASRC(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE, @DSCODE
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRDTLDATASRC (NUM, VERSION, LINE, DSCODE, SRC, ID)
      SELECT NUM, VERSION, LINE, DSCODE, @SRC, @ID
      FROM CTCNTRDTLDATASRC(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE AND DSCODE = @DSCODE

      FETCH NEXT FROM C INTO @LINE, @DSCODE
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRFIXDTL
    DECLARE C CURSOR FOR
      SELECT LINE
      FROM CTCNTRFIXDTL(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRFIXDTL (NUM, VERSION, LINE, FEEUNIT, FEECYCLE, FSTFEEDATE,
        NEXTBEGINDATE, NEXTENDDATE, AMOUNT, SRC, ID)
      SELECT NUM, VERSION, LINE, FEEUNIT, FEECYCLE, FSTFEEDATE,
        NEXTBEGINDATE, NEXTENDDATE, AMOUNT, @SRC, @ID
      FROM CTCNTRFIXDTL(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE

      FETCH NEXT FROM C INTO @LINE
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRFIXSTORE
    DECLARE C CURSOR FOR
      SELECT LINE, ITEMNO
      FROM CTCNTRFIXSTORE(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE, @ITEMNO
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRFIXSTORE (NUM, VERSION, LINE, ITEMNO, STORESCOPE, TOTAL,
        NOTE, SRC, ID)
      SELECT NUM, VERSION, LINE, ITEMNO, STORESCOPE, TOTAL,
        NOTE, @SRC, @ID
      FROM CTCNTRFIXSTORE(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE AND ITEMNO = @ITEMNO

      FETCH NEXT FROM C INTO @LINE, @ITEMNO
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRFIXDATE
    DECLARE C CURSOR FOR
      SELECT LINE, ITEMNO
      FROM CTCNTRFIXDATE(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE, @ITEMNO
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRFIXDATE (NUM, VERSION, LINE, ITEMNO, GENDATE, TOTAL, CHGBOOKNUM,
        NOTE, SRC, ID)
      SELECT NUM, VERSION, LINE, ITEMNO, GENDATE, TOTAL, CHGBOOKNUM,
        NOTE, @SRC, @ID
      FROM CTCNTRFIXDATE(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE AND ITEMNO = @ITEMNO

      FETCH NEXT FROM C INTO @LINE, @ITEMNO
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRRATEDTL
    DECLARE C CURSOR FOR
      SELECT LINE
      FROM CTCNTRRATEDTL(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRRATEDTL (NUM, VERSION, LINE, FEEUNIT, FEECYCLE, FEEDAYOFFSET, FSTFEEDATE,
        NEXTBEGINDATE, NEXTENDDATE, FIXCOST, RATEMODE, CALCMODE, FEEPREC, ROUNDTYPE, STORESCOPE,
        GDSCOPE, GDSCOPESQL, GDSCOPETEXT, AHEADDAYS, DISCOUNTRATE, SRC, ID)
      SELECT NUM, VERSION, LINE, FEEUNIT, FEECYCLE, FEEDAYOFFSET, FSTFEEDATE,
        NEXTBEGINDATE, NEXTENDDATE, FIXCOST, RATEMODE, CALCMODE, FEEPREC, ROUNDTYPE, STORESCOPE,
        GDSCOPE, GDSCOPESQL, GDSCOPETEXT, AHEADDAYS, DISCOUNTRATE, @SRC, @ID
      FROM CTCNTRRATEDTL(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE

      FETCH NEXT FROM C INTO @LINE
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRRATEDISC
    DECLARE C CURSOR FOR
      SELECT LINE, ITEMNO
      FROM CTCNTRRATEDISC(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE, @ITEMNO
 WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRRATEDISC (NUM, VERSION, LINE, ITEMNO, RATE, LOWAMT, HIGHAMT, QBASE, SRC, ID)
      SELECT NUM, VERSION, LINE, ITEMNO, RATE, LOWAMT, HIGHAMT, QBASE, @SRC, @ID
      FROM CTCNTRRATEDISC(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE AND ITEMNO = @ITEMNO

      FETCH NEXT FROM C INTO @LINE, @ITEMNO
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRRATESTORE
    DECLARE C CURSOR FOR
      SELECT LINE, ITEMNO
      FROM CTCNTRRATESTORE(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE, @ITEMNO
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRRATESTORE (NUM, VERSION, LINE, ITEMNO, STOREGID, SRC, ID)
      SELECT NUM, VERSION, LINE, ITEMNO, STOREGID, @SRC, @ID
      FROM CTCNTRRATESTORE(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE AND ITEMNO = @ITEMNO

      FETCH NEXT FROM C INTO @LINE, @ITEMNO
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRRATEGOODS
    DECLARE C CURSOR FOR
      SELECT LINE, ITEMNO
      FROM CTCNTRRATEGOODS(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE, @ITEMNO
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRRATEGOODS (NUM, VERSION, LINE, ITEMNO, GDGID, SRC, ID)
      SELECT NUM, VERSION, LINE, ITEMNO, GDGID, @SRC, @ID
      FROM CTCNTRRATEGOODS(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE AND ITEMNO = @ITEMNO

      FETCH NEXT FROM C INTO @LINE, @ITEMNO
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRRATESTOREGD
    DECLARE C CURSOR FOR
      SELECT LINE, ITEMNO
      FROM CTCNTRRATESTOREGD(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE, @ITEMNO
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRRATESTOREGD (NUM, VERSION, LINE, ITEMNO, STORESCOPE, GDSCOPESQL,
        GDSCOPETEXT, NOTE, SRC, ID)
      SELECT NUM, VERSION, LINE, ITEMNO, STORESCOPE, GDSCOPESQL,
        GDSCOPETEXT, NOTE, @SRC, @ID
      FROM CTCNTRRATESTOREGD(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE AND ITEMNO = @ITEMNO

      FETCH NEXT FROM C INTO @LINE, @ITEMNO
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRRATESTOREGDDISC
    DECLARE C CURSOR FOR
      SELECT LINE, ITEMNO, ROWNO
      FROM CTCNTRRATESTOREGDDISC(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE, @ITEMNO, @ROWNO
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRRATESTOREGDDISC (NUM, VERSION, LINE, ITEMNO, ROWNO, RATE, LOWAMT,
        HIGHAMT, QBASE, SRC, ID)
      SELECT NUM, VERSION, LINE, ITEMNO, ROWNO, RATE, LOWAMT,
        HIGHAMT, QBASE, @SRC, @ID
      FROM CTCNTRRATESTOREGDDISC(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE AND ITEMNO = @ITEMNO AND ROWNO = @ROWNO

      FETCH NEXT FROM C INTO @LINE, @ITEMNO, @ROWNO
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRRATEGUARDDISC
    DECLARE C CURSOR FOR
      SELECT LINE, ITEMNO
      FROM CTCNTRRATEGUARDDISC(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE, @ITEMNO
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRRATEGUARDDISC (NUM, VERSION, LINE, ITEMNO, RATE, LOWAMT,
        HIGHAMT, QBASE, SRC, ID)
      SELECT NUM, VERSION, LINE, ITEMNO, RATE, LOWAMT,
        HIGHAMT, QBASE, @SRC, @ID
      FROM CTCNTRRATEGUARDDISC(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE AND ITEMNO = @ITEMNO

      FETCH NEXT FROM C INTO @LINE, @ITEMNO
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRRATEGUARDCHG
    DECLARE C CURSOR FOR
      SELECT LINE, ITEMNO
      FROM CTCNTRRATEGUARDCHG(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE, @ITEMNO
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRRATEGUARDCHG (NUM, VERSION, LINE, ITEMNO, OTHERCNTRNUM,
        OTHERCHGCODE, SRC, ID)
      SELECT NUM, VERSION, LINE, ITEMNO, OTHERCNTRNUM,
        OTHERCHGCODE, @SRC, @ID
      FROM CTCNTRRATEGUARDCHG(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE AND ITEMNO = @ITEMNO

      FETCH NEXT FROM C INTO @LINE, @ITEMNO
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRRATEBYMONTHDISC
    DECLARE C CURSOR FOR
      SELECT LINE, ITEMNO
      FROM CTCNTRRATEBYMONTHDISC(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE, @ITEMNO
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRRATEBYMONTHDISC (NUM, VERSION, LINE, ITEMNO, RATE, LOWDATE,
        HIGHDATE, GAMT, SRC, ID)
      SELECT NUM, VERSION, LINE, ITEMNO, RATE, LOWDATE,
        HIGHDATE, GAMT, @SRC, @ID
      FROM CTCNTRRATEBYMONTHDISC(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE AND ITEMNO = @ITEMNO

      FETCH NEXT FROM C INTO @LINE, @ITEMNO
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRRATEBYMONTHSTOREGDDISC
    DECLARE C CURSOR FOR
      SELECT LINE, ITEMNO, ROWNO
      FROM CTCNTRRATEBYMONTHSTOREGDDISC(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE, @ITEMNO, @ROWNO
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRRATEBYMONTHSTOREGDDISC (NUM, VERSION, LINE, ITEMNO, ROWNO, RATE,
        LOWDATE, HIGHDATE, GAMT, SRC, ID)
      SELECT NUM, VERSION, LINE, ITEMNO, ROWNO, RATE,
        LOWDATE, HIGHDATE, GAMT, @SRC, @ID
      FROM CTCNTRRATEBYMONTHSTOREGDDISC(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE AND ITEMNO = @ITEMNO AND ROWNO = @ROWNO

      FETCH NEXT FROM C INTO @LINE, @ITEMNO, @ROWNO
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRRATECONDPLAN zz 090508
    DECLARE C CURSOR FOR
      SELECT LINE
      FROM CTCNTRRATECONDPLAN(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE
    WHILE @@FETCH_STATUS = 0
    BEGIN
    INSERT INTO NCTCNTRRATECONDPLAN (NUM, VERSION, LINE, VENDOR, DEPT, BEGINDATE, ENDDATE, EXPAMT,
        ADDRATE, EXESTAT, EXEBILLINFO, NOTE, SRC, ID)
      SELECT NUM, VERSION, LINE, VENDOR, DEPT, BEGINDATE, ENDDATE, EXPAMT, ADDRATE, EXESTAT,
        EXEBILLINFO, NOTE, @SRC, @ID
      FROM CTCNTRRATECONDPLAN(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND LINE = @LINE

      FETCH NEXT FROM C INTO @LINE
    END
    CLOSE C
    DEALLOCATE C
    --NCTCNTRBRAND
    DECLARE C CURSOR FOR
      SELECT ITEMNO
      FROM CTCNTRBRAND(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION
    OPEN C
    FETCH NEXT FROM C INTO @LINE
    WHILE @@FETCH_STATUS = 0
    BEGIN
      INSERT INTO NCTCNTRBRAND(NUM, VERSION, ITEMNO, CODE, TYPE, STATUS, BEGINDATE, ENDDATE,
        NOTE, SRC, ID)
      SELECT NUM, VERSION, ITEMNO, CODE, TYPE, STATUS, BEGINDATE, ENDDATE,
        NOTE, @SRC, @ID
      FROM CTCNTRBRAND(NOLOCK)
      WHERE NUM = @PINUM AND VERSION = @PIVERSION AND ITEMNO = @LINE

      FETCH NEXT FROM C INTO @LINE
    END
    CLOSE C
    DEALLOCATE C
    --NCNTRGROUP
    INSERT INTO NCNTRGROUP (NUM, VERSION, VENDOR, BEGINDATE, ENDDATE, REALENDDATE,
      LSTUPDOPER, LSTUPDTIME, CHECKER, CHKDATE, STAT, TAG, NOTE, SRC, ID)
    SELECT M.NUM, M.VERSION, M.VENDOR, M.BEGINDATE, M.ENDDATE, M.REALENDDATE,
      M.LSTUPDOPER, M.LSTUPDTIME, M.CHECKER, M.CHKDATE, M.STAT, M.TAG, M.NOTE, @SRC, @ID
    FROM CNTRGROUP M(NOLOCK), GROUPCNTR D(NOLOCK)
    WHERE D.CNTRNUM = @PINUM AND D.CNTRVERSION = @PIVERSION AND M.NUM = D.NUM AND M.VERSION = D.VERSION
    --NGROUPCNTR
    INSERT INTO NGROUPCNTR (NUM, VERSION, CNTRNUM, CNTRVERSION, SRC, ID)
    SELECT NUM, VERSION, CNTRNUM, CNTRVERSION, @SRC, @ID
    FROM GROUPCNTR(NOLOCK)
    WHERE CNTRNUM = @PINUM AND CNTRVERSION = @PIVERSION
  END

  RETURN(0)
END

GO
