SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ALCBYSTORESND]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE
    @STAT INT, @SRC INT, @STOREGID INT, @ID INT

  SELECT @STAT = STAT FROM ALCBYSTORE(NOLOCK) WHERE NUM = @NUM

  IF @STAT <> 1 AND @STAT <> 17 AND @STAT <> 5
  BEGIN
    SET @MSG = '[发送]单据' + @NUM + '不是已审核或者通知门店状态'
    RETURN 1
  END

  SELECT @SRC = USERGID FROM SYSTEM(NOLOCK)

    SELECT @STOREGID = STOREGID FROM ALCBYSTOREDTL2(NOLOCK) WHERE NUM = @NUM
    UPDATE ALCBYSTORE SET SNDTIME = GETDATE() WHERE NUM =@NUM
    EXECUTE GETNETBILLID @ID OUTPUT

    INSERT INTO NALCBYSTORE(ID, NUM, SETTLENO, STAT, FILLER, FILDATE, CHECKER, DMDDATE, TOTAL,
      TAX, QTY, NOTE, CLS, SRCNUM, DESRCTYPE, DESRCNUM, NSTAT, RCV, SRC, TYPE)
    SELECT  @ID, NUM, SETTLENO, STAT, FILLER, FILDATE, CHECKER, DMDDATE, TOTAL,
      TAX, QTY, NOTE, CLS, SRCNUM, DESRCTYPE, DESRCNUM, 0, @STOREGID, @SRC, 0
    FROM ALCBYSTORE(NOLOCK)
    WHERE NUM = @NUM

    IF @@ERROR <> 0
    BEGIN
      SET @MSG = '发送' + @NUM + '单据失败'
      RETURN 2
    END

    INSERT INTO NALCBYSTOREDTL(NUM, LINE, GDGID, CASES, QTY, INVQTY, TOTAL, TAX, ASNQTY, SRC, ID)
    SELECT NUM, LINE, GDGID, CASES, QTY, INVQTY, TOTAL, TAX, ASNQTY, @SRC, @ID
    FROM ALCBYSTOREDTL(NOLOCK)
    WHERE NUM = @NUM

    IF @@ERROR <> 0
    BEGIN
      SET @MSG = '发送' + @NUM + '单据失败'
      RETURN 3
    END

  UPDATE ALCBYSTORE SET SNDTIME = GETDATE() WHERE NUM = @NUM
  SET @MSG = '发送' + @NUM + '单据成功'

  RETURN 0
END
GO
