SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CHKPGFBOOKTO500]
(
    @PINUM    CHAR(14),
    @PIOPER   CHAR(30),
    @PICLS      CHAR(10),
    @POERR_MSG  VARCHAR(255)  OUTPUT
)
AS
begin
    DECLARE @VISVALID INT
    DECLARE @VPGFCODE   VARCHAR(10)
    DECLARE @VVDRGID  INT
    DECLARE @VCNTRNUM VARCHAR(14)
    DECLARE @VREALAMT MONEY
    DECLARE @VGATHERINGMODE CHAR(10)
    DECLARE @SETTLENO INT
    DECLARE @VRET   INT
    DECLARE @USERGID    INT
    DECLARE @SRC        INT
    DECLARE @CNTRVERSION INT
    DECLARE @CALCCENTER INT
    DECLARE @TNUM VARCHAR(14)
    DECLARE @MODNUM VARCHAR(14)
  
  SELECT @VVDRGID = BILLTO,
    @VCNTRNUM = CNTRNUM,
    @VPGFCODE = PGFCODE,
    @VREALAMT = REALAMT,
    @VGATHERINGMODE = GATHERINGMODE,
    @CNTRVERSION = CNTRVERSION,
    @MODNUM = ISNULL(MODNUM, '')
  FROM PGFBOOK WHERE NUM = @PINUM
  IF @@ROWCOUNT = 0
  BEGIN
    SET @POERR_MSG = '抵扣货款单' + @PINUM + '不存在'
    RETURN 1
  END

  if isnull(@vCntrNum, '') <> ''
  begin
    if not exists(select 1 from CTCNTR m, CTCNTRDTL d
      where m.NUM = d.NUM and m.VERSION = d.VERSION
       and m.STAT in (500, 1400) and m.TAG = 1
       and d.ChgCODE = @vPGFCode and m.NUM = @vCntrNum)
    begin
      SET @POERR_MSG = '抵扣货款单' + @PINUM + '中的对应的合约项目' + @VPGFcode + '不存在。'
      RETURN 1
    END
    SET @CALCCENTER = NULL
    SELECT @CALCCENTER = CALCCENTER FROM CTCNTR(NOLOCK) WHERE NUM = @VCNTRNUM AND VERSION = @CNTRVERSION
    SELECT @USERGID = USERGID FROM FASYSTEM(NOLOCK)
    EXEC GENNEXTBILLNUMEX NULL, 'PGFBOOK', @TNUM OUTPUT
    IF @CALCCENTER IS NOT NULL AND @CALCCENTER <> @USERGID AND SUBSTRING(@TNUM, 1, 4) = SUBSTRING(@PINUM, 1, 4) AND @MODNUM = ''
    BEGIN
      SET @POERR_MSG = '抵扣货款单' + @PINUM + '中的合约计算中心不是本单位'
      RETURN 1
    END
  END ELSE
  BEGIN
    if not exists(select 1 from CTCHGDEF where CODE = @vPGFCode)
    BEGIN
      SET @POERR_MSG = '抵扣货款单' + @PINUM + '中的对应的帐款项目' + @VPGFcode + '不存在。'
      RETURN 1
    END
  END
  
  IF @VISVALID = 1
  BEGIN
    SET @POERR_MSG = '抵扣货款单' + @PINUM + '中的对应的项目' + @VPGFCODE + '已经无效。';
      RETURN 1
  END

  SELECT @SETTLENO = MAX(NO) FROM MONTHSETTLE(NOLOCK) 
  SELECT @USERGID = USERGID FROM FASYSTEM(NOLOCK)
  SET @SRC = NULL
  SELECT @SRC = C2.SRC FROM PGFBOOK C1(NOLOCK), PGFBOOK C2(NOLOCK) WHERE C1.NUM = @PINUM AND C1.MODNUM = C2.NUM
  IF @SRC IS NOT NULL SET @USERGID = @SRC
  UPDATE PGFBOOK SET
    SETTLENO = @SETTLENO,
    STAT = 500,
    CHKDATE = GETDATE(),
    CHECKER = @PIOPER,
    LSTUPDTIME = GETDATE()
  WHERE NUM = @PINUM
  
  UPDATE PGFBOOK SET SRC = @USERGID WHERE NUM = @PINUM AND SRC IS NULL
  
  /*
  SET @VRET = 0
  IF @PICLS IS NULL OR @PICLS = ''
  BEGIN
    EXEC @VRET = CHKCHGBOOK_SEND @PINUM, @PIOPER, @POERR_MSG OUTPUT
    IF @VRET <= 0 SET @VRET = 0
  END
  RETURN @VRET*/
END
GO
