SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[LOADVDRPAYDTL]
(
	@NUM		CHAR(14),
	@NEGFLAG	INT,
	@OPER		VARCHAR(30),
	@MSG		VARCHAR(255)	OUTPUT
)
AS
BEGIN
	DECLARE @VVDRGID	INT
	DECLARE @VRET		INT
	DECLARE @VTOTAL		MONEY
	DECLARE @VPAYTOTAL	MONEY
	DECLARE @CHGNUM		CHAR(14)
	DECLARE @PAYTOTAL	MONEY
	DECLARE	@VPAYDIRECT	MONEY
  declare @vOperGid int
  declare @vOperCode varchar(20)

	SELECT @VRET = 0

	SELECT @VVDRGID = VGID FROM VDRPAY(NOLOCK) WHERE NUM = @NUM
	DECLARE CDTL CURSOR FOR
	SELECT CHGNUM, PAYTOTAL FROM VDRPAYDTL WHERE NUM = @NUM
	FOR UPDATE
	OPEN CDTL
	FETCH NEXT FROM CDTL INTO @CHGNUM, @PAYTOTAL
	WHILE @@FETCH_STATUS = 0
	BEGIN
    exec PCT_Utils_ExtractCode @Oper, @vOperCode output
    select @vOperGid = GID from EMPLOYEE where CODE = @vOperCode
    if @vOperGid is null set @vOperGid = 1
    if @NegFlag = 1
      exec @vRet = PCT_CHGBOOK_DEDUCT @ChgNum, @PayTotal, @vOperGid, @Msg output
    else
      exec @vRet = PCT_CHGBOOK_UNDO_DEDUCT @ChgNum, @PayTotal, @vOperGid, @Msg output

		SELECT 
			@VTOTAL = REALAMT,
			@VPAYTOTAL = PAYTOTAL,
			@VPAYDIRECT = PAYDIRECT
		FROM CHGBOOK(NOLOCK)
		WHERE NUM = @CHGNUM
		
		IF @NEGFLAG = 1
		BEGIN
			UPDATE VDRPAYDTL SET 
				SHOULDPAY = @VPAYDIRECT * @VTOTAL, 
				REALPAY = @VPAYDIRECT * @VPAYTOTAL,
				NOPAYTOTAL = @VPAYDIRECT * (@VTOTAL - @VPAYTOTAL)
		 	 WHERE CURRENT OF CDTL
		END
			
		FETCH NEXT FROM CDTL INTO @CHGNUM, @PAYTOTAL
	END
	CLOSE CDTL
	DEALLOCATE CDTL

	RETURN @VRET
END
GO
