SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[GENGDFLOWCODECUS]
(
  @CURCODE VARCHAR(20),
  @CODELENGTH INT,
  @CURCODEOUT VARCHAR(20) OUTPUT
)
AS
BEGIN
  --定制存储过程,实现不同类别商品,后n为流水码不重复
  SET @CURCODEOUT = '000000'
END
GO
