SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CHECKBARCODEEX]
(
  @BARCODE VARCHAR(20) OUTPUT
)
AS
BEGIN
  DECLARE
    @CODESTYLE VARCHAR(20),
    @CODELEN INT,
    @INTSUM1 INT,
    @INTSUM2 INT,
    @I INT

  EXEC OPTREADSTR 10, 'CHKCODESTYLE', '', @CODESTYLE OUTPUT
  EXEC OPTREADINT 10, 'CHKCODELEN', 8, @CODELEN OUTPUT

  IF (@CODESTYLE = 'EAN-8') OR (@CODESTYLE = 'EAN-13')
    EXEC CHECKBARCODE @BARCODE OUTPUT
  ELSE IF @CODESTYLE = 'CODE128'
  BEGIN
    IF @CODELEN = 8
    BEGIN
      IF LEN(@BARCODE) < 8 SET @BARCODE = REPLICATE('0', 7 - LEN(@BARCODE)) + @BARCODE
      ELSE SET @BARCODE = SUBSTRING(@BARCODE, 1, 7);
      SET @BARCODE = '0' + @BARCODE;
      SET @INTSUM1 = 0
      SET @INTSUM2 = 0
      SET @I = LEN(@BARCODE)
      WHILE @I >= 2
      BEGIN
        SET @INTSUM1 = @INTSUM1 + ASCII(SUBSTRING(@BARCODE, @I, 1)) - ASCII('0')
        SET @INTSUM2 = @INTSUM2 + ASCII(SUBSTRING(@BARCODE, @I - 1, 1)) - ASCII('0')
        SET @I = @I - 2
      END
      SET @BARCODE = SUBSTRING(@BARCODE, 2, 7) + CHAR(ASCII('0') + (@INTSUM1 + @INTSUM2 * 3) % 10)
    END
  END
END
GO
