SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CHKBCKDMDTO410]
(
  @piNUM CHAR(14),
  @piOPER CHAR(30),
  @piCLS	 CHAR(10),
  @piTOSTAT INT,
  @poMSG VARCHAR(255) OUTPUT
)
AS
BEGIN
    IF EXISTS(SELECT 1 FROM BCKDMD (NOLOCK)
    	WHERE ((LOCKNUM IS NOT NULL) OR (RTRIM(LOCKNUM)<>'')) AND NUM = @piNum)
    BEGIN
        SET @poMSG = '已经被导入退货单不能作废['+@piNum+']'
        RETURN 1
    END
	UPDATE BCKDMD SET
		STAT = 410,
		CACLDATE = GETDATE(),
		CANCELER = @piOPER,
		LSTUPDTIME = GETDATE()
	WHERE NUM = @piNUM
	EXEC BCKDMDADDLOG @piNUM, 410, '', @piOPER
	RETURN 0
END
GO
