SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ALCGFTAGM_AUTOCHECK]
(
  @POERRMSG       VARCHAR(255) OUTPUT  
)
WITH ENCRYPTION
AS
BEGIN
  DELETE ALCGFTDTL FROM ALCGFT WHERE ALCGFT.SRCNUM = ALCGFTDTL.SRCNUM AND ALCGFT.FINISH + 1 <= GETDATE()
  DELETE FROM ALCGFT WHERE FINISH + 1 <= GETDATE()
  RETURN(0)   
END
GO
