SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create procedure [dbo].[POLYPAYRATEPRM_OCR]
(
  @Num varchar(14),
  @Cls varchar(10),
  @Oper varchar(20),
  @Msg varchar(255) output
) as
begin
  declare
    @STOREGID INT

  declare SDTL cursor for
    SELECT STOREGID FROM POLYPAYRATEPRMLACSTORE(NOLOCK)
    WHERE NUM = @Num and CLS = @Cls
  OPEN SDTL
  FETCH NEXT FROM SDTL INTO @STOREGID
  WHILE @@FETCH_STATUS = 0
  BEGIN
  	IF @Cls = '批量联销率'
      INSERT INTO POLYPAYRATEPRICE(STORE, BILLNUM, CLS, BILLLINE, ASTART, AFINISH, DEPT, VENDOR, BRAND, POLYPAYRATE, OCRTIME)
        SELECT @STOREGID, NUM, CLS, LINE, ASTART, AFINISH, DEPT, VENDOR, BRAND, POLYPAYRATE, GETDATE()
        FROM POLYPAYRATEPRMDTL D(nolock)
          WHERE D.NUM = @Num and D.CLS = @Cls
    ELSE IF @Cls = '商品折扣'
    --后单压前单
    BEGIN
    	DECLARE @ASTART DATETIME, @AFINISH DATETIME, @DEPT VARCHAR(20), @VENDOR INT, @BRAND VARCHAR(10), @STARTDIS DECIMAL(24,4),
    	  @FINISHDIS DECIMAL(24, 4), @LINE INT, @DISPAYRATE DECIMAL(24, 4)
    	DECLARE C_PRCPRM CURSOR FOR
        SELECT LINE, ASTART, AFINISH, LTRIM(RTRIM(DEPT)), VENDOR, LTRIM(RTRIM(BRAND)), STARTDIS, FINISHDIS, POLYPAYRATE
          FROM POLYPAYRATEPRMDTL WHERE NUM = @Num and CLS = @Cls
      OPEN C_PRCPRM
      FETCH NEXT FROM C_PRCPRM INTO @LINE, @ASTART, @AFINISH, @DEPT, @VENDOR, @BRAND, @STARTDIS, @FINISHDIS, @DISPAYRATE
      WHILE @@FETCH_STATUS = 0
      BEGIN
    	  IF EXISTS (SELECT 1 FROM DISRATEAGMINV
    	    WHERE STORE = @STOREGID AND DEPT = @DEPT AND VENDOR = @VENDOR
    	      AND ((BRAND = @BRAND) OR (BRAND IS NULL) OR (@BRAND IS NULL) OR (BRAND = '') OR (@BRAND = ''))
    	      AND (((ASTART >= @ASTART) AND (ASTART <= @AFINISH)) OR ((AFINISH >= @ASTART) AND (AFINISH <= @AFINISH)))
    	      AND (((STARTDIS >= @STARTDIS) AND (STARTDIS < @FINISHDIS)) OR ((FINISHDIS > @STARTDIS) AND (FINISHDIS <= @FINISHDIS)))
    	    )
    	  BEGIN
    	    DELETE FROM DISRATEAGMINV WHERE STORE = @STOREGID AND DEPT = @DEPT AND VENDOR = @VENDOR 
    	      AND ((BRAND = @BRAND) OR (BRAND IS NULL) OR (@BRAND IS NULL) OR (BRAND = '') OR (@BRAND = ''))
    	      AND (((ASTART >= @ASTART) AND (ASTART <= @AFINISH)) OR ((AFINISH >= @ASTART) AND (AFINISH <= @AFINISH)))
    	      AND (((STARTDIS >= @STARTDIS) AND (STARTDIS < @FINISHDIS)) OR ((FINISHDIS > @STARTDIS) AND (FINISHDIS <= @FINISHDIS)))
    	  END

        FETCH NEXT FROM C_PRCPRM INTO @LINE, @ASTART, @AFINISH, @DEPT, @VENDOR, @BRAND, @STARTDIS, @FINISHDIS, @DISPAYRATE
      END
      CLOSE C_PRCPRM
      DEALLOCATE C_PRCPRM

      INSERT INTO DISRATEAGMINV(STORE, NUM, CLS, LINE, ASTART, AFINISH, DEPT, VENDOR, BRAND, DISPAYRATE, STARTDIS, FINISHDIS)
      SELECT @STOREGID, NUM, CLS, LINE, ASTART, AFINISH, DEPT, VENDOR, BRAND, POLYPAYRATE, STARTDIS, FINISHDIS
      FROM POLYPAYRATEPRMDTL D(nolock)
        WHERE D.NUM = @Num and D.CLS = @Cls
    END

    FETCH NEXT FROM SDTL INTO @STOREGID
  END
  CLOSE SDTL
  DEALLOCATE SDTL

  RETURN(0)
end
GO
