SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CHKGoodsApp_0TO1200]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS	 CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
	UPDATE GoodsApp SET
		STAT = 1200,
		CHKDATE = GETDATE(),
		CHECKER = @OPER,
		LSTUPDTIME = GETDATE()
	WHERE NUM = @NUM
	EXEC GOODSAPPADDLOG @NUM,1200,'',@OPER
	RETURN 0
END
GO
