SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[BCKNOTIFYCHK]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS	 CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
	DECLARE @VRET INT
	DECLARE @VSTAT INT
	DECLARE @VACTNAME CHAR(40)
	DECLARE @VSTATNAME CHAR(40)
	DECLARE @EXP DATETIME
    SET @VRET = 0;

	SELECT @VSTAT = STAT FROM BCKNOTIFY
	WHERE NUM = @NUM
	IF @@ROWCOUNT = 0
	BEGIN
		SET @MSG = '单据' + @NUM + '不存在'
		RETURN 1
	END
	IF @TOSTAT = 100  -- SZ ADD 1524
	BEGIN
	  SELECT @EXP = EXPDATE FROM BCKNOTIFY WHERE NUM = @NUM
	  IF (@EXP IS NOT NULL) AND (@EXP <= GETDATE()-1)
	  BEGIN
	    SET @MSG = '单据' + @NUM + '已经超过到效日期'
	    RETURN 1
	  END
	END
	IF @VSTAT = 0 AND @TOSTAT = 100
	BEGIN
	  EXEC @VRET = CHKBCKNOTIFYTO100 @NUM, @OPER, @CLS, @TOSTAT, @MSG OUTPUT
          RETURN @VRET
        END

	SELECT @VACTNAME = ACTNAME FROM MODULESTAT(NOLOCK) WHERE NO = @TOSTAT
	SELECT @VSTATNAME = STATNAME FROM MODULESTAT(NOLOCK) WHERE NO = @VSTAT
    SET @MSG = '不能' + @VACTNAME + '状态为' + @VSTATNAME + '的退货通知单'
    RETURN 1
END
GO
