SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CHKVDRBCKDMD_40XTO411]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS	 CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
	DECLARE @LmtOperForNotSplitMDBill int,
	        @USERGID INT,         @SRCNUM CHAR(14),
	        @SRC INT,             @LOCKNUM VARCHAR(14),
	        @GENCLS VARCHAR(10)
	EXEC OPTREADINT 569,'LmtOperForNotSplitMDBill',0,@LmtOperForNotSplitMDBill OUTPUT
	SELECT @USERGID = USERGID FROM SYSTEM
	SELECT @SRCNUM = SRCNUM, @SRC = SRC
	FROM VDRBCKDMD WHERE NUM = @NUM
	IF @LmtOperForNotSplitMDBill = 1 AND @SRC <> @USERGID
	  AND (@SRCNUM IS NULL OR RTRIM(@SRCNUM) = '')
	BEGIN
		SET @MSG ='单据是门店单据但未经过拆分不能作废。'
		RETURN 1
	END

	UPDATE VdrBckDmd SET
		STAT = 411, CACLDATE = GETDATE(),
		CANCELER = @OPER, LSTUPDTIME = GETDATE()
	WHERE NUM = @NUM

	EXEC VDRBCKDMDADDLOG @NUM, 411, '', @OPER
	--作废生成的退货单
	SET @LOCKNUM = ''
	SET @GENCLS = '直配进退'
	SELECT @LOCKNUM = LOCKNUM FROM VDRBCKDMD WHERE LOCKCLS = @GENCLS
	    AND STAT in (401, 1600) AND NUM = @NUM
	IF @LOCKNUM <> '' AND @LOCKNUM IS NOT NULL
	  UPDATE DIRALC SET STAT = 13   --作废
	  WHERE CLS = @GENCLS AND NUM = @LOCKNUM AND STAT IN (0, 7)

	SET @LOCKNUM = ''
	SET @GENCLS = '直配出退'
	SELECT @LOCKNUM = LOCKNUM FROM VDRBCKDMD WHERE LOCKCLS = @GENCLS
	    AND STAT in (401, 1600) AND NUM = @NUM
	IF @LOCKNUM <> '' AND @LOCKNUM IS NOT NULL
	  UPDATE DIRALC SET STAT = 13   --作废
	  WHERE CLS = @GENCLS AND NUM = @LOCKNUM AND STAT IN (0, 7)

	RETURN 0
END
GO
