SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[DISTNOTIFY_DELIVER]
	@PINUM CHAR(10),
	@PICURDATE DATETIME,
	@PICURSETTLENO INT,
	@POERRMSG VARCHAR(200)='' OUTPUT
AS
BEGIN
	DECLARE
		@RET INT,
		@FROMWRH INT,@TOSTORE INT, @TOWRH INT, 
		@LINE INT, @GDGID INT, @QTY MONEY,
		@INPRC MONEY,@RTLPRC MONEY,
		@ALCQTY money

	DECLARE @ORDNUM VARCHAR(20)

	SELECT	@FROMWRH=WRH, @TOSTORE=DISTSTORE ,@ORDNUM = ISNULL(ORDNUM,'')
	FROM DISTNOTIFY
	WHERE NUM=@PINUM

	SELECT @TOWRH = NULL
	SELECT @TOWRH = H.GID FROM WAREHOUSEH H(NOLOCK) INNER JOIN STORE S ON H.CODE = S.CODE WHERE S.GID = @TOSTORE
	IF @TOWRH IS NULL
	BEGIN
		SELECT @POERRMSG = '配往单位没有对应自己的集货仓位，集货仓位的代码需要和配往单位的代码一致。'
		RETURN -1
	END

	SELECT @RET = 0
	DECLARE C_DISTNOTIFY CURSOR FOR
		SELECT	LINE, GDGID, REALQTY - SHOULDQTY, REALQTY
		FROM DISTNOTIFYDTL 
		WHERE NUM = @PINUM
		FOR UPDATE
	OPEN C_DISTNOTIFY
	FETCH NEXT FROM C_DISTNOTIFY INTO 
		@LINE, @GDGID, @QTY , @ALCQTY

	WHILE @@FETCH_STATUS = 0 BEGIN
		
		/* XFDTL */
		/* ININPRC, INRTLPRC */
		SELECT @INPRC=INPRC, @RTLPRC=RTLPRC 
		FROM GOODS 
		WHERE GID=@GDGID

		UPDATE DISTNOTIFYDTL 
		SET	OUTINPRC=@INPRC,
			OUTRTLPRC=@RTLPRC
		WHERE CURRENT OF C_DISTNOTIFY
		--ADDED BY HXS 2004.04.22 FOR TASK 1885
		IF @ALCQTY <> 0 
		BEGIN
			EXEC DISTNOTIFYWRITETOORD  @PINUM,  @ORDNUM,   @GDGID,  @ALCQTY
		END
		
		IF @QTY <> 0
		BEGIN
			--修改定单的已配数量,modified by hxs 2004.04.22
		
		
/*			IF ISNULL(@ORDNUM,'') <>''
			BEGIN
				UPDATE ORDDTL SET ASNQTY = ASNQTY + @QTY WHERE NUM = @ORDNUM AND GDGID = @GDGID
			END			
*/
			/* INV */
			EXECUTE @RET=UNLOAD @FROMWRH, @GDGID, @QTY, @RTLPRC, NULL
			IF @RET <> 0 
			BEGIN
				SELECT @POERRMSG='从仓位'+NAME+'['+CODE+']'+'出库'
					FROM WAREHOUSE
					WHERE GID=@FROMWRH
				SELECT @POERRMSG= @POERRMSG +'商品'+NAME+'['+CODE+']'+LTRIM(RTRIM(CONVERT(CHAR,@QTY)))+MUNIT+'错误'
					FROM GOODS
					WHERE GID=@GDGID

				BREAK
			END

		     
			EXECUTE @RET=LOADIN @TOWRH, @GDGID, @QTY, @RTLPRC, NULL  /*2003-03-10*/
			IF @RET <> 0 
			BEGIN
				SELECT @POERRMSG='向仓位'+NAME+'['+CODE+']'+'入库'
					FROM WAREHOUSE
					WHERE GID=@TOWRH
				SELECT @POERRMSG= @POERRMSG +'商品'+NAME+'['+CODE+']'+LTRIM(RTRIM(CONVERT(CHAR,@QTY)))+MUNIT+'错误'
					FROM GOODS
					WHERE GID=@GDGID

				BREAK
			END
			INSERT INTO DB (ADATE, ASETTLENO, BWRH, BGDGID, BVDRGID, BCSTGID,
					NDC_Q, NDC_A, NDC_I, NDC_R)
				VALUES (@PICURDATE, @PICURSETTLENO, @FROMWRH, @GDGID, 1, 1, /*@VDRGID, @CSTGID */
					@QTY, @QTY * @INPRC, @QTY * @INPRC, @QTY * @RTLPRC)

			INSERT INTO DB (ADATE, ASETTLENO, BWRH, BGDGID, BVDRGID, BCSTGID, /*2003-03-10*/
					NDJ_Q, NDJ_A, NDJ_I, NDJ_R)
				VALUES (@PICURDATE, @PICURSETTLENO, @TOWRH, @GDGID, 1, 1, /*@VDRGID, @CSTGID */
					@QTY, @QTY * @INPRC, @QTY * @INPRC, @QTY * @RTLPRC)
		END

		FETCH NEXT FROM C_DISTNOTIFY INTO 
			@LINE, @GDGID, @QTY, @ALCQTY
	END
	CLOSE C_DISTNOTIFY
	DEALLOCATE C_DISTNOTIFY
	
	RETURN(@RET)
END
GO
