SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[NPS3SPECSCOPESCORE_REMOVE]
(
  @SRC INT,
  @ID  INT
)
AS
BEGIN
  DELETE FROM NPS3SPECSCOPESCORE WHERE SRC = @SRC AND ID = @ID
  DELETE FROM NPS3SPECSCOPESCOREDTL WHERE SRC = @SRC AND ID = @ID
  DELETE FROM NPS3SPECSCOPESCOREPROMSUBJOUTDTL WHERE SRC = @SRC AND ID = @ID
END
GO
