SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CHKBCKNOTIFYTO100]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS	 CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
	UPDATE BCKNOTIFY SET
		STAT = 100,
		CHKDATE = GETDATE(),
		CHECKER = @OPER,
		LSTUPDTIME = GETDATE()
	WHERE NUM = @NUM
	EXEC BCKNOTIFYADDLOG @NUM, 100, '', @OPER
	RETURN 0
END
GO
