SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[DISTNOTIFY_CHECK] 
	@PINUM CHAR(10),
	@PICURDATE DATETIME,
	@PICURSETTLENO INT,
	@POERRMSG VARCHAR(200)='' OUTPUT
AS
BEGIN
	DECLARE
		@RET INT,
		@FROMWRH INT, @TOSTORE INT,@TOWRH INT, 
		@LINE INT, @GDGID INT, @SHOULDQTY MONEY,
		@INPRC MONEY,@RTLPRC MONEY,
		@STORE INT, @WRH INT

	DECLARE @ORDNUM VARCHAR(20)
		,@ALCQTY INT,@INVQTY MONEY,@REALSHOULDQTY MONEY
	

	SELECT	@FROMWRH=WRH, @TOSTORE=DISTSTORE ,@ORDNUM = ORDNUM
	FROM DISTNOTIFY
	WHERE NUM=@PINUM

	SELECT @TOWRH = NULL
	SELECT @TOWRH = H.GID FROM WAREHOUSEH H(NOLOCK) INNER JOIN STORE S ON H.CODE = S.CODE WHERE S.GID = @TOSTORE
	IF @TOWRH IS NULL
	BEGIN
		SELECT @POERRMSG = '配往单位没有对应自己的集货仓位，集货仓位的代码需要和配往单位的代码一致。'
		RETURN -1
	END

	SELECT @RET = 0
	DECLARE C_DISTNOTIFY CURSOR FOR
		SELECT	LINE, GDGID, SHOULDQTY	FROM DISTNOTIFYDTL 
		WHERE NUM = @PINUM
		FOR UPDATE
	OPEN C_DISTNOTIFY
	FETCH NEXT FROM C_DISTNOTIFY INTO @LINE, @GDGID, @SHOULDQTY

	WHILE @@FETCH_STATUS = 0 BEGIN

		SELECT @INPRC=INPRC,@RTLPRC=RTLPRC,@ALCQTY = ISNULL(ALCQTY,0) 
			FROM GOODS
			WHERE GID=@GDGID
		IF @ALCQTY = 0 SELECT @ALCQTY = 1
		--ADDED BY HXS 2003.06.22
		SELECT @INVQTY = ISNULL(SUM(QTY),0) FROM INV WHERE WRH = @FROMWRH AND GDGID= @GDGID
		IF @SHOULDQTY > @INVQTY
		BEGIN
			SELECT @REALSHOULDQTY = @INVQTY
		END
		ELSE
		BEGIN
			SELECT @REALSHOULDQTY = @SHOULDQTY
		END

		UPDATE DISTNOTIFYDTL 
		SET	CHKINPRC=@INPRC, 
			CHKRTLPRC=@RTLPRC,
			SHOULDQTY = @REALSHOULDQTY,
			CASES = @REALSHOULDQTY / @ALCQTY
			WHERE CURRENT OF C_DISTNOTIFY
		--修改定单的已配数量 deleted by hxs 2004.04.22 for task 1885
/*		IF ISNULL(@ORDNUM,'') <>''
		BEGIN
			UPDATE ORDDTL SET ASNQTY = ASNQTY + @REALSHOULDQTY WHERE NUM = @ORDNUM AND GDGID = @GDGID
		END
*/
		
		/* INV */
		IF @REALSHOULDQTY <> 0
		BEGIN
			EXECUTE @RET=UNLOAD @FROMWRH, @GDGID, @REALSHOULDQTY, @RTLPRC, NULL
			IF @RET <> 0 
			BEGIN
				SELECT @POERRMSG='从仓位'+NAME+'['+CODE+']'+'出库'
					FROM WAREHOUSE
					WHERE GID=@FROMWRH
				SELECT @POERRMSG= @POERRMSG +'商品'+NAME+'['+CODE+']'+LTRIM(RTRIM(CONVERT(CHAR,@REALSHOULDQTY)))+MUNIT+'错误'
					FROM GOODS
					WHERE GID=@GDGID
	
				BREAK
			END
	
	             
			EXECUTE @RET=LOADIN @TOWRH, @GDGID, @REALSHOULDQTY, @RTLPRC, NULL  /*2003-03-10*/
			IF @RET <> 0 
			BEGIN
				SELECT @POERRMSG='向仓位'+NAME+'['+CODE+']'+'入库'
					FROM WAREHOUSE
					WHERE GID=@TOWRH
				SELECT @POERRMSG= @POERRMSG +'商品'+NAME+'['+CODE+']'+LTRIM(RTRIM(CONVERT(CHAR,@REALSHOULDQTY)))+MUNIT+'错误'
					FROM GOODS
					WHERE GID=@GDGID
	
				BREAK
			END
			INSERT INTO DB (ADATE, ASETTLENO, BWRH, BGDGID, BVDRGID, BCSTGID,
					NDC_Q, NDC_A, NDC_I, NDC_R)
				VALUES (@PICURDATE, @PICURSETTLENO, @FROMWRH, @GDGID, 1, 1, /*@VDRGID, @CSTGID */
					@REALSHOULDQTY, @REALSHOULDQTY * @INPRC, @REALSHOULDQTY * @INPRC, @REALSHOULDQTY * @RTLPRC)
	
			INSERT INTO DB (ADATE, ASETTLENO, BWRH, BGDGID, BVDRGID, BCSTGID, /*2003-03-10*/
					NDJ_Q, NDJ_A, NDJ_I, NDJ_R)
				VALUES (@PICURDATE, @PICURSETTLENO, @TOWRH, @GDGID, 1, 1, /*@VDRGID, @CSTGID */
					@REALSHOULDQTY, @REALSHOULDQTY * @INPRC, @REALSHOULDQTY * @INPRC, @REALSHOULDQTY * @RTLPRC)
		END

		FETCH NEXT FROM C_DISTNOTIFY INTO 
			@LINE, @GDGID, @SHOULDQTY
	END
	CLOSE C_DISTNOTIFY
	DEALLOCATE C_DISTNOTIFY

	RETURN(@RET)
END
GO
