SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[MktIvgtCHK]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS   CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE @VRET INT
  DECLARE @VSTAT INT
  DECLARE @VACTNAME CHAR(40)
  DECLARE @VSTATNAME CHAR(40)
  DECLARE @EXP DATETIME
  DECLARE @LKNUM VARCHAR(13)
  SET @VRET = 0;  
  
  SELECT @VSTAT = STAT FROM PSMktIvgt 
    WHERE NUM = @NUM
  IF @@ROWCOUNT = 0
  BEGIN
    SET @MSG = '单据' + @NUM + '不存在'
    RETURN 1
  END
  IF @VSTAT = 0 AND @TOSTAT = 400  --总部批准
  BEGIN
    EXEC @VRET = MKTIVGTCHK0TO400 @NUM, @OPER, @CLS, @TOSTAT, @MSG OUTPUT
    RETURN @VRET
  END
  IF @VSTAT = 400 AND @TOSTAT = 1200  --提交
  BEGIN
    EXEC @VRET = MKTIVGTCHK400TO1200 @NUM, @OPER, @CLS, @TOSTAT, @MSG OUTPUT
    RETURN @VRET
  END
  IF @VSTAT = 1200 AND @TOSTAT = 100  --审核
  BEGIN
    EXEC @VRET = MKTIVGTCHK1200TO100 @NUM, @OPER, @CLS, @TOSTAT, @MSG OUTPUT
    RETURN @VRET
  END
  IF @VSTAT = 100 AND @TOSTAT = 110  --作废
  BEGIN
    EXEC @VRET = MKTIVGTCHK100TO110 @NUM, @OPER, @CLS, @TOSTAT, @MSG OUTPUT
    RETURN @VRET
  END
      
  SELECT @VACTNAME = ACTNAME FROM MODULESTAT(NOLOCK) WHERE NO = @TOSTAT
  SELECT @VSTATNAME = STATNAME FROM MODULESTAT(NOLOCK) WHERE NO = @VSTAT
  SET @MSG = '不能' + @VACTNAME + '状态为' + @VSTATNAME + '的市场调研单'
  RETURN 1
END
GO
