SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ALCDIFF_CHECK]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS	 CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)				-- RETURN ERROR FROM 0
AS
BEGIN
	DECLARE
	  @VRET INT,		 @VSTAT INT

    	SET @VRET = 0;

	SELECT @VSTAT = STAT FROM ALCDIFF(NOLOCK)
	WHERE NUM = @NUM
	IF @@ROWCOUNT = 0
	BEGIN
		SET @MSG = '单据' + @NUM + '不存在'
		RETURN 1
	END

	IF @VSTAT = 0 AND @TOSTAT = 401  --请求总部批准
	BEGIN
	  	EXEC @VRET = ALCDIFF_CHECK_0TO401 @NUM, @OPER, @CLS, @TOSTAT, @MSG OUTPUT
          	RETURN @VRET
        END

	IF @VSTAT = 401 AND @TOSTAT = 400  --总部批准
	BEGIN
	  	EXEC @VRET = ALCDIFF_CHECK_401TO400 @NUM, @OPER, @CLS, @TOSTAT, @MSG OUTPUT
          	RETURN @VRET
        END

	IF @VSTAT = 401 AND @TOSTAT = 210  --进行中作废
	BEGIN
	  	EXEC @VRET = ALCDIFF_CHECK_401TO210 @NUM, @OPER, @CLS, @TOSTAT, @MSG OUTPUT
          	RETURN @VRET
        END

        SET @MSG = '单据' + @NUM + '操作失败'

    	RETURN 2
END
GO
