SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[VDRPAYADDLOG]
(
	@CLS	CHAR(20),
	@NUM	CHAR(14),
	@TOSTAT	INT,
	@OPER	CHAR(30)
)
AS
BEGIN
	INSERT INTO VDRPAYLOG (NUM, STAT, MODIFIER, TIME) 
	VALUES(@NUM, @TOSTAT, @OPER, GETDATE());
END;
GO
