SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[RCVONEPROMB]
(
	@SRC	int,
	@ID	INT,
	@OPER	VARCHAR(30),
	@MSG	VARCHAR(255)	OUTPUT
)
AS
BEGIN
    DECLARE	
	@VRET INT,
	@VFLAG INT,
	@VSTORE INT,
	@VNUM VARCHAR(14),
	@VCLS VARCHAR(10),
	@VRCV INT,
	@VFOUND INT,
	@TMPSTR	VARCHAR(50),	
	@VSTAT  INT,
	@VNSTAT INT
        
	SET @VRET = 0
	SET @TMPSTR = '组合促销单';
	SELECT @VSTORE = USERGID FROM SYSTEM(NOLOCK)
	SET @VCLS = '组合'
	SELECT @VNUM = NUM, @VRCV = RCV, @VNSTAT =STAT
	  FROM NPROMB(NOLOCK) WHERE SRC = @SRC AND ID = @ID 
	IF @VRCV <> @VSTORE 
	  BEGIN	
		SET @MSG = '收到接收单位非本单位的组合促销单；单号=' + @VNUM 
		EXEC DELNPROMB @SRC, @ID
		RETURN(0) 
	  END
	  
	SELECT @VFOUND = COUNT(*) FROM PROMB WHERE NUM = @VNUM
	
	SELECT @VFLAG = 1, @VSTAT = STAT FROM PROMB WHERE NUM = @VNUM;

	IF @VFOUND > 0 AND @VSTAT = 100 AND @VNSTAT = 110 --唯一正确可处理状态
	  BEGIN
		EXEC @VRET = PROMBDLT @VCLS,@VNUM,'网络交换',110,@MSG
		IF @VRET <> 0 
		  begin
  			UPDATE NPROMB SET NNOTE = @MSG WHERE SRC = @SRC AND ID = @ID
			RETURN(@VRET)
		  end
		EXEC DELNPROMB @SRC, @ID
		RETURN(0)
	  END	
	IF @VFOUND > 0 OR (@VFOUND = 0 AND @VNSTAT = 110)
	  BEGIN	
		EXEC DELNPROMB @SRC, @ID
		RETURN(0); 
	  END	
                
	--插入到当前表中
	INSERT INTO PROMB (NUM,STAT,FILDATE,FILLER,SNDTIME,PRNTIME,RECCNT,
	                LSTUPDTIME,TOPIC,STORESCOPE,NOTE,ASTART,AFINISH,
			CYCLE, CSTART, CFINISH, CSPEC, PSETTLENO,OCRTIME, DLTPRICEPROM)			     
		SELECT NUM, 0, FILDATE,FILLER, SNDTIME, PRNTIME,RECCNT, 
		        LSTUPDTIME,TOPIC,STORESCOPE,NOTE,ASTART,AFINISH,
			CYCLE, CSTART, CFINISH, CSPEC, PSETTLENO,OCRTIME, DLTPRICEPROM
		FROM NPROMB
		WHERE SRC = @SRC AND ID = @ID	
	INSERT INTO PROMBGOODS (NUM,LINE,GDGID,GDCODE,QPC,QPCSTR,RTLPRC,MBRPRC,CNTRINPRC,COST,PRMDIV1,PRMDIV2,PRMDIV3, ISDLT)				
		SELECT NUM,LINE,GDGID,GDCODE,QPC,QPCSTR,RTLPRC,MBRPRC,CNTRINPRC,COST,PRMDIV1,PRMDIV2,PRMDIV3, ISDLT
		FROM NPROMBGOODS
		WHERE SRC = @SRC AND ID = @ID
	--门店接收时自动增加生效门店记录0
	INSERT INTO PROMBSTORE(NUM, STOREGID)		
		SELECT NUM,@VSTORE FROM NPROMB
		WHERE SRC = @SRC AND ID = @ID	
	INSERT INTO PROMBDIS(NUM, QTY, RTLPRC)
		SELECT NUM,QTY,RTLPRC FROM NPROMBDIS
		WHERE SRC = @SRC AND ID = @ID		
	EXEC @VRET = PROMBCHK @VNUM,@VCLS,'网络交换',100,@MSG
	IF @VRET <> 0
          BEGIN
		UPDATE NPROMB SET NNOTE = @MSG WHERE SRC = @SRC AND ID = @ID
		RETURN(@VRET) 
          END
	EXEC DELNPROMB @SRC, @ID
	RETURN(0) 

END
GO
