SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[GoodsAppApply]
(
  @NUM CHAR(14),
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
	DECLARE @STAT INT, @I INT, @SSQL VARCHAR(255), @USERGID INT, @USERPROPERTY INT, @APPMODE VARCHAR(20)
	DECLARE @FIELDNAME VARCHAR(30)
	DECLARE @RET INT
	SELECT @USERGID = USERGID FROM SYSTEM
	SELECT @USERPROPERTY = PROPERTY FROM STORE WHERE GID = @USERGID
	SET @RET = 0
	SELECT @STAT = STAT, @APPMODE = RTRIM(APPMODE) FROM GOODSAPP WHERE NUM = @NUM
	IF @STAT<>400
	BEGIN
		SET @MSG = '单据状态不是总部批准'
		RETURN(-1)
	END
	IF @APPMODE = '修改'
	BEGIN
		EXEC @RET = GoodsAppApplyUpd @NUM, @MSG OUTPUT
		RETURN @RET
	END
	IF @APPMODE = '删除'
	BEGIN
		EXEC @RET = GoodsAppApplyDel @NUM, @MSG OUTPUT
		RETURN 0--@RET
	END
	IF @APPMODE = '新增'
	BEGIN
		EXEC @RET = GoodsAppApplyNew @NUM, @MSG OUTPUT
		RETURN @RET
	END
	--UPDATE GOODSAPPDTL SET FLAG = 1 WHERE NUM = @NUM
	RETURN(0)

END
GO
