SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[GENNEXTBILLNUMOLD]
	@PICLS	VARCHAR(10),
	@PIBILL	VARCHAR(100),
	@PONEWNUM VARCHAR(14) OUTPUT
AS
BEGIN
	DECLARE
	@V_CMD		VARCHAR(255)
	,@V_STORECODE	CHAR(10)
	,@V_STOREGID	INT
  	,@V_NUM       VARCHAR(14) 
	,@V_RET		INT

	SELECT @V_CMD = 'DECLARE CUR_GENNEXTBILLNUMOLD CURSOR FOR SELECT MAX(NUM) FROM ' + @PIBILL + '(NOLOCK)'
	IF (@PICLS IS NOT NULL) AND (RTRIM(@PICLS) <> '')
		SELECT @V_CMD = @V_CMD + ' WHERE CLS = ''' + @PICLS + ''''

	EXEC(@V_CMD)

	OPEN CUR_GENNEXTBILLNUMOLD
	FETCH NEXT FROM CUR_GENNEXTBILLNUMOLD INTO @V_NUM
	IF @@FETCH_STATUS = 0 
	BEGIN
		IF @V_NUM IS NULL OR @V_NUM = ''
			SELECT @V_NUM = '0000000000'
	END ELSE
		SELECT @V_NUM = '0000000000'
	CLOSE CUR_GENNEXTBILLNUMOLD
	DEALLOCATE CUR_GENNEXTBILLNUMOLD

	EXEC @V_RET = NEXTBN @V_NUM, @PONEWNUM OUTPUT
	RETURN(@V_RET) 
END
GO
