SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[NPOLYPAYRATEPRM_REMOVE]
(
  @SRC      INT,
  @ID  INT
)
AS
BEGIN
  DELETE FROM NPOLYPAYRATEPRM WHERE SRC = @SRC AND ID = @ID
  DELETE FROM NPOLYPAYRATEPRMDTL WHERE SRC = @SRC AND ID = @ID
END
GO
