SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PURCHASESTKIN_RCV]
(
  @BILL_ID INT,
  @SRC_ID INT,
  @OPER CHAR(30),
  @MSG VARCHAR(255) OUTPUT
) --WITH ENCRYPTION
AS
BEGIN
  DECLARE
    @CUR_SETTLENO INT,    @NET_NUM CHAR(14),
    @RCV_GID INT,         @NET_STAT SMALLINT,
    @NET_TYPE SMALLINT,   @RE INT,
    @NET_CLS CHAR(10),    @VDRCODE CHAR(10),
    @VDRGID INT,          @PSRGID INT,
    @fillergid INT,       @wrh int,
    @PRECHECKERgid int,   @NET_SRCNUM CHAR(14)

  SELECT @CUR_SETTLENO = MAX(NO) FROM MONTHSETTLE(NOLOCK)

  SELECT  @RCV_GID = RCV, @NET_STAT = STAT, @NET_TYPE = TYPE, @NET_NUM = NUM, @NET_CLS = CLS,
          @VDRCODE = SUPPLIERCODE, @PSRGID = PSR, @fillergid = filler, @NET_SRCNUM = SRCNUM,
          @PRECHECKERgid = PRECHECKER
  FROM NPURCHASEORDER(NOLOCK) WHERE ID = @BILL_ID AND SRC = @SRC_ID
  IF @@ROWCOUNT = 0 OR @NET_NUM IS NULL
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '不存在'
    RETURN 1
  END

  IF EXISTS(SELECT 1 FROM PURCHASEORDER(NOLOCK) WHERE NUM = @NET_NUM AND CLS = '销售进货' AND STAT = 600)
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '已经被接收且复核'
    RETURN 2
  END

  IF EXISTS(SELECT 1 FROM PURCHASEORDER(NOLOCK) WHERE NUM = @NET_NUM AND CLS = '销售进货' AND STAT = 3200)
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '已经被接收'
    RETURN 2
  END

  IF (SELECT MAX(USERGID) FROM SYSTEM(NOLOCK)) <>  @RCV_GID
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '接收单位不是本单位'
    RETURN 3
  END

  IF @NET_TYPE <> 1
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '不在接收缓冲区中'
    RETURN 4
  END

  SELECT @VDRGID = GID FROM VENDOR(NOLOCK) WHERE CODE = @VDRCODE
  IF @VDRGID IS NULL
  BEGIN
    SET @MSG = '单据中的供应商' + @VDRCODE + '在总部不存在'
    RETURN 5
  END

  IF NOT EXISTS( SELECT 1 FROM EMPLOYEE(NOLOCK) WHERE GID = @PSRGID )
  BEGIN
    IF EXISTS( SELECT LGID FROM EMPXLATE WHERE NGID = @PSRGID )
      SELECT @PSRGID = LGID FROM EMPXLATE WHERE NGID = @PSRGID
    ELSE
    BEGIN
      UPDATE NPURCHASEORDER SET NSTAT = 1, NNOTE = '本地找不到采购员对应的员工(对照表中也不存在)'
      WHERE SRC = @SRC_ID AND ID = @BILL_ID
      SET @MSG = '本地找不到采购员对应的员工(对照表中也不存在)'
      RETURN 6
    END
  END

  IF NOT EXISTS( SELECT 1 FROM EMPLOYEE(NOLOCK) WHERE GID = @fillergid )
  BEGIN
    IF EXISTS( SELECT LGID FROM EMPXLATE WHERE NGID = @fillergid )
      SELECT @fillergid = LGID FROM EMPXLATE WHERE NGID = @fillergid
    ELSE
    BEGIN
      SET @MSG = '本地找不到填单员对应的员工(对照表中也不存在)' + convert(varchar, @fillergid)
      UPDATE NPURCHASEORDER SET NSTAT = 1, NNOTE = @MSG
      WHERE SRC = @SRC_ID AND ID = @BILL_ID
      RETURN 7
    END
  END

  IF NOT EXISTS( SELECT 1 FROM EMPLOYEE(NOLOCK) WHERE GID = @PRECHECKERgid )
  BEGIN
    IF EXISTS( SELECT LGID FROM EMPXLATE WHERE NGID = @PRECHECKERgid )
      SELECT @PRECHECKERgid = LGID FROM EMPXLATE WHERE NGID = @PRECHECKERgid
    ELSE
    BEGIN
      UPDATE NPURCHASEORDER SET NSTAT = 1, NNOTE = '本地找不到预审人对应的员工(对照表中也不存在)'
      WHERE SRC = @SRC_ID AND ID = @BILL_ID
      SET @MSG = '本地找不到预审员对应的员工(对照表中也不存在)'
      RETURN 9
    END
  END

  IF EXISTS(SELECT 1 FROM NPURCHASEORDERDTL D(NOLOCK) WHERE
    GDGID NOT IN (SELECT GID FROM GOODS(NOLOCK)) AND D.SRC = @SRC_ID AND D.ID = @BILL_ID )
  BEGIN
    UPDATE NPURCHASEORDER SET NSTAT = 1, NNOTE = '单据明细中的商品在本地不存在'
    WHERE SRC = @SRC_ID AND ID = @BILL_ID
    SET @MSG = '单据明细中的商品在本地不存在'
    RETURN 8
  END

  IF NOT EXISTS( SELECT 1 FROM PURCHASEORDER(NOLOCK) WHERE CLS = '销售定货' AND NUM = @NET_SRCNUM )
  BEGIN
    SET @MSG = '请先接收对应的销售定货单' + @NET_SRCNUM
    RETURN 10
  END

  select TOP 1 @wrh = G.WRH FROM NPURCHASEORDERDTL D(NOLOCK), GOODSH G(NOLOCK)
    WHERE D.SRC = @SRC_ID AND D.ID = @BILL_ID AND D.GDGID = G.GID

  DELETE FROM PURCHASEORDER WHERE NUM = @NET_NUM AND CLS = '销售进货'
  DELETE FROM PURCHASEORDERDTL WHERE NUM = @NET_NUM AND CLS = '销售进货'

  INSERT INTO PURCHASEORDER(NUM, CLS, SETTLENO, VENDOR, TOTAL, TAX, NOTE, FILDATE, FILLER,
    CHECKER, STAT, WRH, RECCNT, SRC, SRCNUM, SNDTIME, RECEIVER, PSR, PRNTIME, PRECHECKER,
    PRECHKDATE, DEPT, CUSTOMIZETYPE, RCVTYPE, SELLERAPPROVEOPERATOR, SELLERREFNUMBER,
    SELLERAPPROVETIME, SELLERREMARK, BUYERNAME, BUYERREFNUMBER, BUYERADDRESS, BUYERTELEPHONE,
    BUYERORDERTIME, BUYERORDEREXPIRATIONDATE, BUYERORDERTYPE, BUYERFILDATE, BUYERSELLOPERATOR,
    BUYERCUSTMIZEDIMAGE, BUYERINVOICENUMBER, SUPPLIERCODE, SUPPLIERNAME, CHECKDATE, LSTUPDTIME,
    CONFIRMDATE, CONFIRMER, CUSTOMIZEMEMO, BCKCAUSE, FINISHED, NearBy, LANE, BUILDING,
    ROOM, BUYERREGIONDTL, RTLTOTAL, ORDAMT, INPRCAMT)
  SELECT NUM, CLS, @CUR_SETTLENO, @VDRGID, TOTAL, TAX, NOTE, FILDATE, @fillergid,
    CHECKER, STAT, @wrh, RECCNT, SRC, SRCNUM, SNDTIME, RECEIVER, @PSRGID, PRNTIME, @PRECHECKERgid,
    PRECHKDATE, DEPT, CUSTOMIZETYPE, RCVTYPE, SELLERAPPROVEOPERATOR, SELLERREFNUMBER,
    SELLERAPPROVETIME, SELLERREMARK, BUYERNAME, BUYERREFNUMBER, BUYERADDRESS, BUYERTELEPHONE,
    BUYERORDERTIME, BUYERORDEREXPIRATIONDATE, BUYERORDERTYPE, BUYERFILDATE, BUYERSELLOPERATOR,
    BUYERCUSTMIZEDIMAGE, BUYERINVOICENUMBER, SUPPLIERCODE, SUPPLIERNAME, CHKDATE, GETDATE(),
    CONFIRMDATE, CONFIRMER, CUSTOMIZEMEMO, BCKCAUSE, FINISHED, NearBy, LANE, BUILDING,
    ROOM, BUYERREGIONDTL, RTLTOTAL, ORDAMT, INPRCAMT
  FROM NPURCHASEORDER(NOLOCK)
  WHERE SRC = @SRC_ID AND ID = @BILL_ID

  IF @@ERROR <> 0
  BEGIN
    SET @MSG = '[接收]接收' + @NET_NUM + '单据失败'
    RETURN 11
  END

  INSERT INTO PURCHASEORDERDTL(NUM,CLS, LINE, GDGID, ORDQTY, PRICE, TOTAL, TAX, WRH, INVQTY,
    ARVQTY, BCKQTY, NOTE, FLOWNO, POSNO, RTLQTY, RTLBCKQTY, RTLPRC, RTLTOTAL, PRNUM, ORDPRC, ORDAMT, INPRC, INPRCAMT)
  SELECT D.NUM,D.CLS, D.LINE, D.GDGID, D.ORDQTY, D.PRICE, D.TOTAL, D.TAX, G.WRH, D.INVQTY,
    D.ARVQTY, D.BCKQTY, D.NOTE, D.FLOWNO, D.POSNO, D.RTLQTY, D.RTLBCKQTY, D.RTLPRC, D.RTLTOTAL, D.PRNUM, D.ORDPRC, D.ORDAMT, D.INPRC, D.INPRCAMT
  FROM NPURCHASEORDERDTL D(NOLOCK), GOODSH G(NOLOCK)
  WHERE D.SRC = @SRC_ID AND D.ID = @BILL_ID AND G.GID = D.GDGID

  IF @@ERROR <> 0
  BEGIN
    SET @MSG = '[接收]接收' + @NET_NUM + '单据失败'
    RETURN 12
  END

  UPDATE PURCHASEORDER SET RCVER = @OPER, RCVTIME = GETDATE()
  WHERE CLS = '销售进货' AND NUM = @NET_NUM

  DELETE FROM NPURCHASEORDER WHERE ID = @BILL_ID AND SRC = @SRC_ID
  DELETE FROM NPURCHASEORDERDTL WHERE ID = @BILL_ID AND SRC = @SRC_ID

  --RECEIVE BILL OVER
  EXEC PURCHASEORDERADDLOG @NET_NUM, @NET_CLS, @NET_STAT, '接收', @OPER

  IF (SELECT OPTIONVALUE FROM HDOPTION WHERE OPTIONCAPTION = 'AutoFuhe' AND MODULENO = 665) = 1
  BEGIN
    EXEC @RE = PURCHASEORDER_CHECK_100TO600 @NET_NUM, @OPER, @NET_CLS, 600, @MSG OUTPUT
    IF @RE <> 0
    BEGIN
      SET @MSG = '单据：' + @NET_NUM + '接收时自动复核失败'
      RETURN @RE
    END
  END

  SET @MSG = '单据：' + @NET_NUM + '接收成功' + @MSG

  RETURN 0
END
GO
