SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[LOADPROMBDTLTO50]
(
	@PICLS	  VARCHAR(10),
	@PINUM	  VARCHAR(14),
	@PISTOREGID  INT,
	@PIPSETTLENO INT,
	@PIASTART   DATETIME,
	@PIAFINISH  DATETIME,
	@PICYCLE    DATETIME,
	@PICSTART   DATETIME,
	@PICFINISH  DATETIME,
	@PICSPEC    VARCHAR(255),
	@PILINE     INT,
	@PIGDGID    INT,
	@PIGDCODE   CHAR(13),		
	@POERR_MSG  VARCHAR(255) OUTPUT	
) AS
BEGIN
    DECLARE  
	@VRET 		INT,
	@VQPC		DECIMAL(24,4),
	@VIQPCSTR 	varchar(20),
	@VOCRTIME	DATETIME,
        @Code           varchar(30)

	set @VRET = 0	
	UPDATE GOODS SET LSTUPDTIME = getdate() WHERE GID = @PIGDGID

	SELECT  @VOCRTIME = OCRTIME FROM PROMB WHERE NUM = @PINUM	
	SELECT @VQPC = QPC, @VIQPCSTR = QPCSTR
	FROM GDINPUT(nolock)
	WHERE GID = @PIGDGID AND CODE = @PIGDCODE

	INSERT INTO PRICES (STORE,GDGID,GDCODE,
			ASTART,AFINISH,CYCLE,CSTART,CFINISH,CSPEC,ISGFT,
			OCRTIME,BILLNUM,PSETTLENO,CLS,BILLLINE,QPC)	        		        
		SELECT  @PISTOREGID, @PIGDGID,@PIGDCODE,
			@PIASTART,@PIAFINISH,@PICYCLE,@PICSTART,@PICFINISH,@PICSPEC,0,
		    @VOCRTIME,@PINUM,@PIPSETTLENO,@PICLS,@PILINE,@VQPC
		FROM PROMBGOODS
		WHERE NUM = @PINUM AND LINE = @PILINE
		
  if @PIGDGID <> -1
  BEGIN
    DECLARE C CURSOR FOR
      SELECT CODE
      FROM GDINPUT(nolock)
      WHERE GID = @PIGDGID AND CODE <> @PIGDCODE
         AND QPCSTR = @VIQPCSTR
    OPEN C
    FETCH NEXT FROM C INTO @CODE
    WHILE @@fetch_status = 0
    BEGIN
    	INSERT INTO PRICES (STORE,GDGID,GDCODE,
		    ASTART, AFINISH, CYCLE, CSTART,CFINISH,CSPEC,ISGFT,
			  OCRTIME,BILLNUM,PSETTLENO,CLS,BILLLINE,QPC)	        		        
		  SELECT  @PISTOREGID, @PIGDGID, @CODE,
			  @PIASTART, @PIAFINISH, @PICYCLE, @PICSTART, @PICFINISH, @PICSPEC, 0,
		    @VOCRTIME, @PINUM, @PIPSETTLENO, @PICLS, @PILINE, @VQPC
		  FROM PROMBGOODS
		  WHERE NUM = @PINUM AND LINE = @PILINE
		  FETCH NEXT FROM C INTO @CODE
    END
    CLOSE C
    DEALLOCATE C
  end
    		

	/*FOR R IN C(VIQPCSTR) LOOP
		INSERT INTO PRICES (STORE,GDGID,GDCODE,
			ASTART,AFINISH,CYCLE,CSTART,CFINISH,CSPEC,ISGFT,
			OCRTIME,BILLNUM,PSETTLENO,CLS,BILLLINE,QPC)
		SELECT  @PISTOREGID, @PIGDGID,R.CODE,PIASTART,PIAFINISH,PICYCLE,PICSTART,
			PICFINISH,PICSPEC,0,VOCRTIME,PINUM,PIPSETTLENO,PICLS,PILINE,VQPC
		FROM PROMBGOODS
		WHERE NUM = PINUM AND LINE = PILINE	
	END LOOP;*/
	RETURN(0)

END
GO
