SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[NCRMSTAMPSCORULE_REMOVE]
(
  @SRC INT,
  @ID  INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN 
  declare @NUM VARCHAR(14) 
  SELECT @NUM = NUM FROM NCRMSTAMPSCORULE(NOLOCK) WHERE SRC = @SRC AND ID = @ID
  if @@rowcount = 0
  begin
	set @msg = '找不到指定的网络单据'
	return(1)
  end 

  DELETE FROM NCRMSTAMPSCORULE WHERE SRC = @SRC AND ID = @ID
  DELETE FROM NCRMSTAMPSCORULEDTL WHERE SRC = @SRC AND ID = @ID
  DELETE FROM NCRMSTAMPSCORULEDTL2 WHERE SRC = @SRC AND ID = @ID
  DELETE FROM NCRMSTAMPSCORULELACSTORE WHERE SRC = @SRC AND ID = @ID
END

GO
