SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CHKGoodsApp_40XTO411]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS	 CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
	DECLARE @USERGID INT
	SELECT @USERGID = USERGID FROM SYSTEM
  if (select BOCLS from GOODSAPP(nolock) where num = @num) = '大总部生成'
	begin
      SET @MSG = '不能作废大总部的商品申请单据'
      return(1)
	end

	IF @USERGID <> (SELECT RATIFIER FROM GOODSAPP WHERE NUM = @NUM)
	BEGIN
		IF (SELECT SNDTIME FROM GOODSAPP WHERE NUM = @NUM) IS NOT NULL
		BEGIN
			SET @MSG = '不能作废已经发送的商品资料申请单'
			RETURN 1
		END
	END
	UPDATE GoodsApp SET
		STAT = 411,
		--RATDATE = GETDATE(),
		--RATOPER = @OPER,
		LSTUPDTIME = GETDATE()
	WHERE NUM = @NUM
	UPDATE GOODSAPPDTL SET FLAG = 1 WHERE NUM = @NUM
	EXEC GOODSAPPADDLOG @NUM,411,'',@OPER
	RETURN 0
END
GO
