SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[POORD_RCV]
(
  @BILL_ID INT,
  @SRC_ID INT,
  @OPER CHAR(30),
  @MSG VARCHAR(255) OUTPUT
) --WITH ENCRYPTION
AS
BEGIN
  DECLARE
    @CUR_SETTLENO INT,    @NET_NUM CHAR(14), @wrh int,
    @RCV_GID INT,         @NET_STAT SMALLINT,
    @NET_TYPE SMALLINT,   @RE INT, @VDRGID int, @vdrcode char(10),
    @NET_CLS CHAR(10),    @PSRGID INT, @FILLERGID INT, @NET_RCVTYPE char(20)

  SELECT @CUR_SETTLENO = MAX(NO) FROM MONTHSETTLE(NOLOCK)

  SELECT  @RCV_GID = RCV, @NET_STAT = STAT, @NET_TYPE = TYPE, @NET_NUM = NUM, @NET_CLS = CLS, @VDRCODE = SUPPLIERCODE, @PSRGID = PSR, @FILLERGID = FILLER,
  @NET_RCVTYPE = RCVTYPE
  FROM NPURCHASEORDER(NOLOCK) WHERE ID = @BILL_ID AND SRC = @SRC_ID
  IF @@ROWCOUNT = 0 OR @NET_NUM IS NULL
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '不存在'
    RETURN 1
  END

  IF EXISTS(SELECT 1 FROM PURCHASEORDER(NOLOCK) WHERE NUM = @NET_NUM AND STAT = @NET_STAT AND CLS = '销售定货' AND RCVTYPE = @NET_RCVTYPE)
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '已经被接收'
    RETURN 2
  END

  IF EXISTS(SELECT 1 FROM PURCHASEORDER(NOLOCK) WHERE NUM = @NET_NUM AND STAT = 300 AND CLS = '销售定货' AND RCVTYPE = @NET_RCVTYPE)
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '已经被接收'
    RETURN 2
  END
  IF EXISTS(SELECT 1 FROM PURCHASEORDER(NOLOCK) WHERE NUM = @NET_NUM AND STAT = 1000 and @NET_STAT = 3200 AND CLS = '销售定货' AND RCVTYPE = @NET_RCVTYPE)
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '已经被接收'
    RETURN 2
  END

  IF (SELECT MAX(USERGID) FROM SYSTEM(NOLOCK)) <>  @RCV_GID
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '接收单位不是本单位'
    RETURN 3
  END

  IF @NET_TYPE <> 1
  BEGIN
    SET @MSG = '[接收]单据' +  @NET_NUM + '不在接收缓冲区中'
    RETURN 4
  END

  DELETE FROM PURCHASEORDER WHERE NUM = @NET_NUM AND CLS = '销售定货'
  DELETE FROM PURCHASEORDERDTL WHERE NUM = @NET_NUM AND CLS = '销售定货'
  DELETE FROM PURCHASEORDERTRANSDTL WHERE NUM = @NET_NUM AND CLS = '销售定货'
  select @VDRGID = GID from vendor(nolock)
    where CODE = @VDRCODE
  if @vdrgid is null
  begin
     SET @MSG = '单据中的供应商' + @vdrcode + '在总部不存在'
     return(5)
  end

  IF NOT EXISTS( SELECT 1 FROM EMPLOYEE(NOLOCK) WHERE GID = @PSRGID )
  BEGIN
    IF EXISTS( SELECT LGID FROM EMPXLATE WHERE NGID = @PSRGID )
      SELECT @PSRGID = LGID FROM EMPXLATE WHERE NGID = @PSRGID
    ELSE
    BEGIN
      UPDATE NPURCHASEORDER SET NSTAT = 1, NNOTE = '本地找不到采购员对应的员工(对照表中也不存在)'
      WHERE SRC = @SRC_ID AND ID = @BILL_ID
      SET @MSG = '本地找不到采购员对应的员工(对照表中也不存在)'
      RETURN 6
    END
  END

  IF NOT EXISTS( SELECT 1 FROM EMPLOYEE(NOLOCK) WHERE GID = @FILLERGID )
  BEGIN
    IF EXISTS( SELECT LGID FROM EMPXLATE WHERE NGID = @FILLERGID )
      SELECT @FILLERGID = LGID FROM EMPXLATE WHERE NGID = @FILLERGID
    ELSE
    BEGIN
      UPDATE NPURCHASEORDER SET NSTAT = 1, NNOTE = '本地找不到填单人对应的员工(对照表中也不存在)'
      WHERE SRC = @SRC_ID AND ID = @BILL_ID
      SET @MSG = '本地找不到填单人对应的员工(对照表中也不存在)'
      RETURN 6
    END
  END

  if exists(select 1 from NPURCHASEORDERDTL D(NOLOCK) where
    GDGID not in (select GID from GOODS(NOLOCK)) and D.SRC = @SRC_ID AND D.ID = @BILL_ID )
  begin
    UPDATE NPURCHASEORDER SET NSTAT = 1, NNOTE = '单据明细中的商品在本地不存在'
    WHERE SRC = @SRC_ID AND ID = @BILL_ID
    SET @MSG = '单据明细中的商品在本地不存在'
    RETURN 6
  end

  select TOP 1 @wrh = G.WRH FROM NPURCHASEORDERDTL D(NOLOCK), GOODSH G(NOLOCK)
    WHERE D.SRC = @SRC_ID AND D.ID = @BILL_ID AND D.GDGID = G.GID

  INSERT INTO PURCHASEORDER(NUM, CLS, SETTLENO, VENDOR, TOTAL, TAX, RTLTOTAL, ORDAMT, NOTE, FILDATE, FILLER,
    CHECKER, STAT, WRH, RECCNT, SRC, SRCNUM, SNDTIME, RECEIVER, PSR, PRNTIME, PRECHECKER,
    PRECHKDATE, DEPT, CUSTOMIZETYPE, RCVTYPE, SELLERAPPROVEOPERATOR, SELLERREFNUMBER,
    SELLERAPPROVETIME, SUPPLIERORDERTIME, SELLERREMARK, BUYERNAME, BUYERREFNUMBER, BUYERADDRESS, BUYERTELEPHONE,
    BUYERORDERTIME, BUYERORDEREXPIRATIONDATE, BUYERORDERTYPE, BUYERFILDATE, BUYERSELLOPERATOR,
    BUYERCUSTMIZEDIMAGE, BUYERINVOICENUMBER, SUPPLIERCODE, SUPPLIERNAME, CHECKDATE, LSTUPDTIME,
    CONFIRMDATE, CONFIRMER, SellerConInfo, FINISHEDDATE)
  SELECT NUM, CLS, @CUR_SETTLENO, @VDRGID, TOTAL, TAX, RTLTOTAL, ORDAMT, NOTE, FILDATE, @FILLERGID,
    CHECKER, STAT, @wrh, RECCNT, SRC, SRCNUM, SNDTIME, RECEIVER, @PSRGID, PRNTIME, PRECHECKER,
    PRECHKDATE, DEPT, CUSTOMIZETYPE, RCVTYPE, SELLERAPPROVEOPERATOR, SELLERREFNUMBER,
    SELLERAPPROVETIME, SUPPLIERORDERTIME, SELLERREMARK, BUYERNAME, BUYERREFNUMBER, BUYERADDRESS, BUYERTELEPHONE,
    BUYERORDERTIME, BUYERORDEREXPIRATIONDATE, BUYERORDERTYPE, BUYERFILDATE, BUYERSELLOPERATOR,
    BUYERCUSTMIZEDIMAGE, BUYERINVOICENUMBER, SUPPLIERCODE, SUPPLIERNAME, CHKDATE, GETDATE(),
    CONFIRMDATE, CONFIRMER, SellerConInfo, FINISHEDDATE
  FROM NPURCHASEORDER(NOLOCK)
  WHERE SRC = @SRC_ID AND ID = @BILL_ID

  IF @@ERROR <> 0
  BEGIN
    SET @MSG = '[接收]接收' + @NET_NUM + '单据失败'
    RETURN 7
  END

  INSERT INTO PURCHASEORDERDTL(NUM,CLS, LINE, GDGID, ORDQTY, PRICE, TOTAL, TAX, ORDPRC, ORDAMT, WRH, INVQTY,
    ARVQTY, BCKQTY, NOTE, FLOWNO, POSNO, RTLQTY, RTLBCKQTY, RTLPRC, RTLTOTAL, PRNUM)
  SELECT D.NUM,D.CLS, D.LINE, D.GDGID, D.ORDQTY, D.PRICE, D.TOTAL, D.TAX, D.ORDPRC, D.ORDAMT, G.WRH, D.INVQTY,
    D.ARVQTY, D.BCKQTY, D.NOTE, D.FLOWNO, D.POSNO, D.RTLQTY, D.RTLBCKQTY, D.RTLPRC, D.RTLTOTAL, D.PRNUM
  FROM NPURCHASEORDERDTL D(NOLOCK), GOODSH G(NOLOCK)
  WHERE D.SRC = @SRC_ID AND D.ID = @BILL_ID and D.gdgid = g.gid

  INSERT INTO PURCHASEORDERTRANSDTL(NUM, CLS, POSNO, FLOWNO, REALAMT, QTY, RECCNT, GUEST)
  select D.NUM, D.CLS, D.POSNO, D.FLOWNO, D.REALAMT, D.QTY, D.RECCNT, D.GUEST
  from NPURCHASEORDERTRANSDTL D(nolock)
  where D.SRC = @SRC_ID and D.ID = @BILL_ID

  IF @@ERROR <> 0
  BEGIN
    SET @MSG = '[接收]接收' + @NET_NUM + '单据失败'
    RETURN 8
  END

  UPDATE PURCHASEORDER SET RCVER = @OPER, RCVTIME = GETDATE()
  WHERE CLS = '销售定货' AND NUM = @NET_NUM

  DELETE FROM NPURCHASEORDER WHERE ID = @BILL_ID AND SRC = @SRC_ID
  DELETE FROM NPURCHASEORDERDTL WHERE ID = @BILL_ID AND SRC = @SRC_ID

  --RECEIVE BILL OVER
  EXEC PURCHASEORDADDLOG @NET_NUM, @NET_CLS, @NET_STAT, '接收', @OPER

  SET @MSG = '单据：' + @NET_NUM + '接收成功' + @MSG

  RETURN 0
END
GO
