SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[POLYLTDADJ_REMOVE]
(
  @NUM CHAR(14),         --单号
  @MSG VARCHAR(255) OUTPUT  --错误信息
)
AS
BEGIN
  DECLARE
    @STAT INT,
    @RET INT
  SELECT @STAT = STAT FROM POLYLTDADJ(NOLOCK) WHERE NUM = @NUM
  IF @STAT <> 0
  BEGIN
    SET @MSG = '单据 ' + @NUM + ' 不是未审核状态，不允许删除!';
    RETURN(1);
  END
  EXEC @RET = POLYLTDADJ_DOREMOVE @NUM, @MSG OUTPUT
  IF @RET <> 0 RETURN(@RET)
  DELETE FROM POLYLTDADJLOG WHERE NUM = @NUM
  RETURN(0)
END
GO
