SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[GDBCKNOTIFY_CHECK_0TO100]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE
    @STAT  INT,
    @BCKFLAG VARCHAR(10),
    @LINE INT, 
    @GDGID INT, 
    @VENDORGID INT,
    @STORESCOPE VARCHAR(4000),
    @LIMITQTY MONEY, 
    @LSTBCKDATE DATETIME, 
    @ACTION SMALLINT,
    @STOREGID INT,
    @NOTE  VARCHAR(100),
    @NOTEDTL  VARCHAR(100),
    @NOTEDTLDTL  VARCHAR(100)

  SELECT @STAT = STAT, @BCKFLAG = BCKFLAG FROM GDBCKNOTIFY(NOLOCK) WHERE NUM = @NUM
  IF @STAT <> 0 
  BEGIN
    SET @MSG = '不是未审核状态。'
    RETURN 1
  END
  IF @TOSTAT <>  100
  BEGIN
    SET @MSG = '不是审核操作。'
    RETURN 1
  END

  DECLARE C1 CURSOR FOR
    SELECT LINE, GDGID, VENDORGID, NOTE FROM GDBCKNOTIFYDTL(NOLOCK) WHERE NUM = @NUM ORDER BY LINE
  OPEN C1
  FETCH NEXT FROM C1 INTO @LINE, @GDGID, @VENDORGID, @NOTEDTL
  WHILE @@FETCH_STATUS = 0
  BEGIN        
    DECLARE C2 CURSOR FOR
      SELECT STORESCOPE, LIMITQTY, LSTBCKDATE, ACTION, NOTE FROM GDBCKNOTIFYDTLDTL(NOLOCK) WHERE NUM = @NUM AND LINE = @LINE ORDER BY ITEMNO
    OPEN C2
    FETCH NEXT FROM C2 INTO @STORESCOPE, @LIMITQTY, @LSTBCKDATE, @ACTION, @NOTEDTLDTL
    WHILE @@FETCH_STATUS = 0
    BEGIN
      EXEC('DECLARE C3 CURSOR FOR SELECT DISTINCT GID FROM STORE(NOLOCK) WHERE ' + @STORESCOPE)
      OPEN C3
      FETCH NEXT FROM C3 INTO @STOREGID
      WHILE @@FETCH_STATUS = 0
      BEGIN 
      	IF @NOTEDTL = '' AND @NOTEDTLDTL = ''
      	SET  @NOTE = NULL
      	ELSE
      	SET  @NOTE = @NOTEDTL + @NOTEDTLDTL
        DELETE FROM CURGDBCKNOTIFY WHERE GDGID = @GDGID AND STOREGID = @STOREGID;
        INSERT INTO CURGDBCKNOTIFY (GDGID, STOREGID, VDRGID, FILLER, FILDATE, BCKFALG, LIMITQTY, LSTBCKDATE, ACTION, SRCNUM, NOTE)
        VALUES (@GDGID, @STOREGID, @VENDORGID, @OPER, GETDATE(), @BCKFLAG, @LIMITQTY, @LSTBCKDATE, @ACTION, @NUM, @NOTE)
          
        FETCH NEXT FROM C3 INTO @STOREGID
      END
      CLOSE C3
      DEALLOCATE C3      

      FETCH NEXT FROM C2 INTO @STORESCOPE, @LIMITQTY, @LSTBCKDATE, @ACTION, @NOTEDTLDTL
    END
    CLOSE C2
    DEALLOCATE C2  

    FETCH NEXT FROM C1 INTO @LINE, @GDGID, @VENDORGID, @NOTEDTL
  END
  CLOSE C1
  DEALLOCATE C1
  
  UPDATE GDBCKNOTIFY SET STAT = @TOSTAT, CHECKER = @OPER, CHKDATE = GETDATE(), LASTMODIFYOPER = @OPER, LSTUPDTIME = GETDATE()
  WHERE NUM = @NUM
  
  SET @MSG = '单据：' + @NUM + '审核成功'

  RETURN 0
END
GO
