SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SENDONESTORESCHEME]
(
  @NUM VARCHAR(14),
  @SRC INT,
  @RCV INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE
    @ID INT
  EXECUTE GETNETBILLID @ID OUTPUT

  INSERT INTO NSTOREOPERSCHEME(NUM, STAT, SETTLENO, FILDATE, FILLER, SNDTIME, CHKDATE, CHECKER, LSTUPDTIME,
    LSTUPDOPER, NOTE, RECCNT, SRC, ID, RCV, RCVTIME, TYPE, NSTAT, NNOTE)
  SELECT NUM, STAT, SETTLENO, FILDATE, FILLER, SNDTIME, CHKDATE, CHECKER, LSTUPDTIME,
    LSTUPDOPER, NOTE, RECCNT, @SRC, @ID, @RCV, NULL, 0, 0, NULL
  FROM STOREOPERSCHEME(NOLOCK)
  WHERE NUM = @NUM

  INSERT INTO NSTOREOPERSCHEMEDTL(NUM, LINE, SORTCODE, NOTE, SRC, ID)
  SELECT NUM, LINE, SORTCODE, NOTE, @SRC, @ID
  FROM STOREOPERSCHEMEDTL(NOLOCK)
  WHERE NUM = @NUM

  INSERT INTO NSTORESCHSORTGOODS(NUM, SORTCODE, GDGID, ISOPER, ISNECESSARY, SRC, ID)
  SELECT NUM, SORTCODE, GDGID, ISOPER, ISNECESSARY, @SRC, @ID
  FROM STORESCHSORTGOODS(NOLOCK)
  WHERE NUM = @NUM

  RETURN 0
END
GO
