SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CHGORDQTY]
  @CLS CHAR(10),
  @ORDNUM CHAR(10)
AS
BEGIN
  DECLARE
    @OPTDECORDQTY INT, @DECORDQTY MONEY, @STORE INT,
    @GDGID INT, @WRH INT
  IF @CLS = '自营' EXEC OPTREADINT 52, 'DECORDQTY', 0, @OPTDECORDQTY OUTPUT
  IF @CLS = '调入' EXEC OPTREADINT 73, 'DECORDQTY', 0, @OPTDECORDQTY OUTPUT
  IF @CLS = '直配进' EXEC OPTREADINT 84, 'DECORDQTY', 0, @OPTDECORDQTY OUTPUT
  IF @OPTDECORDQTY = 1
  BEGIN
    DECLARE C_ORD CURSOR FOR
    SELECT GDGID, WRH, QTY - ARVQTY - ASNQTY
    FROM ORDDTL(NOLOCK) WHERE NUM = @ORDNUM AND QTY > ARVQTY + ASNQTY
    OPEN C_ORD
    FETCH NEXT FROM C_ORD INTO @GDGID, @WRH, @DECORDQTY
    WHILE @@FETCH_STATUS = 0 BEGIN
      SELECT @STORE = NULL
      SELECT @STORE = GID FROM STORE WHERE GID = @WRH
      IF @STORE IS NULL SELECT @STORE = USERGID FROM SYSTEM
      UPDATE INV SET ORDQTY = ORDQTY - @DECORDQTY WHERE STORE = @STORE AND WRH = @WRH AND GDGID = @GDGID
      FETCH NEXT FROM C_ORD INTO @GDGID, @WRH, @DECORDQTY
    END
    CLOSE C_ORD
    DEALLOCATE C_ORD
  END
END
GO
