SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PROMSEND]  
(  
  @CLS      VARCHAR(10),  
  @NUM      VARCHAR(14),  
  @OPER     VARCHAR(30),  
  @TOSTAT   INT,  
  @MSG      VARCHAR(255) OUTPUT  
)  
AS  
BEGIN  
  DECLARE  
    @RET    INT,  
    @STORE  INT,  
    @STAT   INT,  
    @GID    INT  
  
  SET @RET = 0  
  SELECT @STORE = USERGID FROM FASYSTEM(NOLOCK)  
  SELECT @STAT = STAT FROM PROM(NOLOCK) WHERE NUM = @NUM AND CLS = @CLS  
  IF @STAT = 0  
  BEGIN  
    SET @MSG = '未审核单据不能发送'  
    RETURN 1  
  END  
  
  DECLARE CDTL CURSOR FOR  
  SELECT GID FROM PROMSTORE(NOLOCK), STORE(NOLOCK)  
  WHERE NUM = @NUM AND CLS = @CLS AND STOREGID = GID AND GID <> @STORE  
  
  OPEN CDTL  
  FETCH NEXT FROM CDTL INTO @GID  
  if @@FETCH_STATUS <> 0 
  begin
    SET @MSG = '生效单位只有本店的单据无需发送'
    CLOSE CDTL
    DEALLOCATE CDTL
    RETURN 1    
  end 	

  WHILE @@FETCH_STATUS = 0  
  BEGIN  
    EXEC @RET = SENDONEPROM @NUM, @CLS, @STORE, @GID, @MSG output 
    IF @RET <> 0  
      RETURN 1  
    FETCH NEXT FROM CDTL INTO @GID  
  END  
  CLOSE CDTL  
  DEALLOCATE CDTL  
  
  UPDATE PROM SET SNDTIME = GETDATE(), LSTUPDTIME = GETDATE()  
    WHERE NUM = @NUM AND CLS = @CLS  
  RETURN @RET  
END  
GO
