SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO

CREATE Procedure [dbo].[TA_BUY]
	@WHERE_CLAUSE VARCHAR(255)
As
declare @BeginDate char(10)
        ,@EndDate char(10)

declare @I int

select @I=charIndex(',',@WhERE_CLAUSE)


Select @BeginDate=SubString(@WHERE_CLAUSE,1,@I-1)
Select @EndDate=SubString(@WHERE_CLAUSE,@I+1,100)

EXEC ('DECLARE CUR_GETVOUCHER CURSOR GLOBAL FOR 

SELECT CONVERT(VARCHAR(100),SUM(case when  BUY11.CURRENCY =-1 then -BUY11.AMOUNT else BUY11.AMOUNT end))A,
       CONVERT(VARCHAR(100),SUM(case when BUY11.CURRENCY= -1 then  - BUY11.AMOUNT  when  BUY11.CURRENCY= 1 then   BUY11.AMOUNT   end)) B,
       CONVERT(VARCHAR(100),SUM(case when (BUY11.CURRENCY=2 or BUY11.CURRENCY=3)  then  BUY11.AMOUNT  end)) C, 
       CONVERT(VARCHAR(100),SUM(case BUY11.CURRENCY when 4  then  BUY11.AMOUNT  end)) D, 
       CONVERT(VARCHAR(100),SUM(case BUY11.CURRENCY when 5  then  BUY11.AMOUNT  end)) E, 
       CONVERT(VARCHAR(100),SUM(case BUY11.CURRENCY when 6  then  BUY11.AMOUNT  end)) F,
       CONVERT(VARCHAR(100),(SUM(case when  BUY11.CURRENCY =-1 then -BUY11.AMOUNT else BUY11.AMOUNT end)-SUM(case when BUY11.CURRENCY= -1 then  - BUY11.AMOUNT  when  BUY11.CURRENCY= 1 then   BUY11.AMOUNT   end))) G
FROM BUY1 BUY1(NOLOCK), BUY11 BUY11(NOLOCK)
WHERE (BUY1.FLOWNO = BUY11.FLOWNO
 and  BUY1.POSNO = BUY11.POSNO )
 and  CONVERT(VARCHAR(10),BUY1.FILDATE,102)  BETWEEN '''+@BEGINDATE+''' AND '''+ @ENDDATE+''' ')
 


RETURN 0


GO
