SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[MKTPRCSCHEME_SEND]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE
    @STAT INT, @SRC INT, @STOREGID INT, @ID INT

  SELECT @STAT = STAT FROM MKTPRCSCHEME(NOLOCK) WHERE NUM = @NUM

  IF @STAT <> 100
  BEGIN
    SET @MSG = '[发送]单据' + @NUM + '不是已审核状态'
    RETURN 1
  END

  UPDATE MKTPRCSCHEME SET SNDTIME = GETDATE() WHERE NUM = @NUM

  SELECT @SRC = USERGID FROM SYSTEM(NOLOCK)

  DECLARE C_LINE CURSOR FOR
  SELECT STOREGID FROM MKTPRCSCHEMESTOREDTL(NOLOCK) WHERE NUM = @NUM AND STOREGID <> @SRC
  OPEN C_LINE
  FETCH NEXT FROM C_LINE
  INTO @STOREGID
  WHILE @@FETCH_STATUS = 0
  BEGIN
    EXECUTE GETNETBILLID @ID OUTPUT

    INSERT INTO NMKTPRCSCHEME(NUM, NAME, STAT, CREATOR, CREATETIME, CHECKER, CHKDATE, SNDTIME,
      LSTUPDTIME, NOTE, SRC, ID, RCV, RCVTIME, NTYPE, NSTAT, NNOTE)
    SELECT NUM, NAME, STAT, CREATOR, CREATETIME, CHECKER, CHKDATE, SNDTIME,
      LSTUPDTIME, NOTE, @SRC, @ID, @STOREGID, GETDATE(), 0, 0, NULL
    FROM MKTPRCSCHEME(NOLOCK)
    WHERE NUM = @NUM

    IF @@ERROR <> 0
    BEGIN
      SET @MSG = '发送' + @NUM + '单据失败'
      RETURN 2
    END

    INSERT INTO NMKTPRCSCHEMEGDDTL(NUM, LINE, GDGID, GDQPCSTR, GDQPC, NOTE, SRC, ID)
    SELECT NUM, LINE, GDGID, GDQPCSTR, GDQPC, NOTE, @SRC, @ID
    FROM MKTPRCSCHEMEGDDTL(NOLOCK)
    WHERE NUM = @NUM

    IF @@ERROR <> 0
    BEGIN
      SET @MSG = '发送' + @NUM + '单据失败'
      RETURN 3
    END

    FETCH NEXT FROM C_LINE INTO @STOREGID
  END
  DEALLOCATE C_LINE

  SET @MSG = '发送' + @NUM + '单据成功'

  RETURN 0
END
GO
