SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[GETFIFODEFINPRC]
	@PI_GDGID INT,
	@PI_INPRC MONEY OUTPUT
AS
BEGIN
	DECLARE @DEFINVPRC VARCHAR(10)

	SELECT @DEFINVPRC = ISNULL(OPTIONVALUE,'1') FROM HDOPTION WHERE MODULENO = 0 AND UPPER(OPTIONCAPTION)='DEFBATCHINVPRC'
	IF @DEFINVPRC = 0
	BEGIN
		SELECT @PI_INPRC = 0
	END
	ELSE
	BEGIN
		IF @DEFINVPRC = 2
		BEGIN
			SELECT @PI_INPRC = LSTINPRC FROM GOODS WHERE GID = @PI_GDGID
		END
		ELSE
		BEGIN
			SELECT @PI_INPRC = CNTINPRC FROM GOODS WHERE GID = @PI_GDGID
		END
	END
END
GO
