SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[GENGDHLINV](
@NO INT,@UPD int)
WITH ENCRYPTION AS
BEGIN
  IF @NO = 0
    BEGIN
      UPDATE GOODS SET LOWINV = B.LOWINV,
                     HIGHINV = B.HIGHINV,
                     AUTOORD = B.AUTOORD       --Added by ShenMin, 2005.6.20, Q4204
                 FROM GOODS A, tmpGDHLInv B
                 WHERE A.CODE = B.CODE AND B.ID = (SELECT MAX(ID) FROM TMPGDHLINV WHERE CODE = A.CODE)
      UPDATE GOODS SET NOAUTOORDREASON = B.NOAUTOORDREASON
                 FROM GOODS A, tmpGDHLInv B
                 WHERE A.CODE = B.CODE AND B.ID = (SELECT MAX(ID) FROM TMPGDHLINV WHERE CODE = A.CODE)
                   AND A.AUTOORD = 0;
    END;
  ELSE IF @NO = 1 and @UPD = 0
  BEGIN
    UPDATE GDSTORE SET LOWINV = B.LOWINV, HIGHINV = B.HIGHINV FROM GDSTORE A,tmpSTGDHLInv B
      WHERE A.STOREGID = B.STOREGID AND A.GDGID = B.GDGID
      AND B.ID = (SELECT MAX(ID) FROM TMPSTGDHLINV WHERE GDGID = A.GDGID AND STOREGID = A.STOREGID)
    DELETE tmpSTGDHLInv FROM tmpSTGDHLInv A INNER JOIN GDSTORE B ON A.STOREGID = B.STOREGID AND A.GDGID = B.GDGID
    insert into gdstore(storegid, gdgid, billto, sale, rtlprc,
      inprc, lowinv, highinv, promote, gft, lwtrtlprc,
      mbrprc, dxprc, payrate, cntinprc)
      SELECT B.STOREGID,B.GDGID,A.BILLTO,A.SALE,A.RTLPRC,A.INPRC,B.LOWINV,B.HIGHINV,
      A.PROMOTE,A.GFT,A.LWTRTLPRC,A.MBRPRC,A.DXPRC,A.PAYRATE,A.CNTINPRC
      FROM GOODS A, TMPSTGDHLINV B WHERE A.GID = B.GDGID
      AND B.ID = (SELECT MAX(ID) FROM TMPSTGDHLINV WHERE GDGID = B.GDGID AND STOREGID = B.STOREGID)
  END
   ELSE
      BEGIN
        UPDATE GDSTORE SET LOWINV = B.LOWINV, HIGHINV = B.HIGHINV FROM GDSTORE A,tmpSTGDHLInv B
          WHERE A.STOREGID = B.STOREGID AND A.GDGID = B.GDGID
          AND B.ID = (SELECT MAX(ID) FROM TMPSTGDHLINV WHERE GDGID = B.GDGID AND STOREGID = B.STOREGID)
        UPDATE adjbill set alctime = getdate()
          from tmpSTGDHLInv t,adjbill a,workstation w
          where  a.alctime is null  and a.cls = '调上下限' and a.posno=w.no and t.storegid=w.storegid and a.gdgid=t.gdgid
          and t.id = (select max(id) from tmpstgdhlinv where storegid = t.storegid and gdgid = t.gdgid)
        DELETE tmpSTGDHLInv FROM tmpSTGDHLInv A INNER JOIN GDSTORE B ON A.STOREGID = B.STOREGID AND A.GDGID = B.GDGID
        INSERT INTO GDSTORE(STOREGID, GDGID, BILLTO, SALE, RTLPRC,
          INPRC, LOWINV, HIGHINV, PROMOTE, GFT, LWTRTLPRC,
          MBRPRC, DXPRC, PAYRATE, CNTINPRC)
          SELECT B.STOREGID,B.GDGID,A.BILLTO,A.SALE,A.RTLPRC,A.INPRC,B.LOWINV,B.HIGHINV,
          A.PROMOTE,A.GFT,A.LWTRTLPRC,A.MBRPRC,A.DXPRC,A.PAYRATE,A.CNTINPRC
          FROM GOODS A, TMPSTGDHLINV B WHERE A.GID = B.GDGID
          AND B.ID = (SELECT MAX(ID) FROM TMPSTGDHLINV WHERE STOREGID = B.STOREGID AND GDGID = B.GDGID)
      END
END
GO
