SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ALCGFTAGM_CHECK_0TO100]
(
  @NUM	CHAR(14),
  @OPER	CHAR(30),
  @CLS	CHAR(10),
  @TOSTAT	INT,
  @MSG	VARCHAR(255) OUTPUT
)				
AS
BEGIN
	DECLARE 
	  @EMPGID INT, 		@RE INT,
	  @STOREGID INT,	@GDGID INT,
	  @NEWPRC MONEY,	@ALCGID INT,
	  @START DATETIME,	@FINISH DATETIME
	  
	SELECT @EMPGID = GID FROM EMPLOYEE(NOLOCK) WHERE 
	CODE = SUBSTRING(@OPER, CHARINDEX('[',@OPER) + 1, LEN(@OPER) - CHARINDEX('[',@OPER) - 1)
	AND NAME = SUBSTRING(@OPER, 1, CHARINDEX('[',@OPER) - 1)
	
	--数据检查
	SELECT @START = START, @FINISH = FINISH, @ALCGID = ALCGID FROM ALCGFTAGM WHERE NUM = @NUM
	IF @START < GETDATE()
	BEGIN
	  SET @MSG = '开始时间不能小于现在时间。'
	  RETURN(2) 
	END
	
	IF @FINISH < @START
	BEGIN
	  SET @MSG = '开始时间不能大于结束时间。'
	  RETURN(3) 
	END
	
	--插入主表 
	INSERT INTO ALCGFT (SRCNUM, ALCGID, START, FINISH)
	SELECT @NUM, @ALCGID, @START, @FINISH
	
	--插入主商品
	INSERT INTO ALCGFTDTL (SRCNUM, GDGID, ALCQTY, FLAG)
	SELECT @NUM, GDGID, ALCQTY, 0 
	FROM ALCGFTAGMGDDTL
	WHERE NUM = @NUM
	
	--插入赠品
	INSERT INTO ALCGFTDTL (SRCNUM, GFTGID, GFTQTY, GFTLMTQTY, GFTWRH, FLAG)
	SELECT @NUM, GFTGID, GFTQTY, GFTLMTQTY, GFTWRH, 1 
	FROM ALCGFTAGMGFTDTL
	WHERE NUM = @NUM
	
	UPDATE ALCGFTAGM SET
	  STAT = 100, CHKDATE = GETDATE(), CHECKER = @EMPGID
	WHERE NUM = @NUM	
	
	EXEC ALCGFTAGMADDLOG @NUM, 100, '审核', @OPER
	
	RETURN 0
END
GO
