SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ADDONEPRMOFFSETDTLTEMPRECORD]
(
 @PINUM VARCHAR(14), --单号
 @PISETTLENO INT,
 @PIGDGID INT, --商品
 @PIAGMNUM VARCHAR(14), --协议单号
 @PIAGMLINE INT, --协议行号
 @PIAGMTABLENAME VARCHAR(32),
 @PIQTY MONEY, --数量
 @PITOTAL MONEY, --返点金额
 @PISTART DATETIME,
 @PIFINISH DATETIME
)
AS
BEGIN
  DECLARE
    @VLINE INT, --以商品区分行号
    @VQPC INT,
    @VQPCSTR VARCHAR(20),
    @VCNTINPRC MONEY,
    @VALC CHAR(10),
    @VTAXRATE MONEY,
    @VTAX MONEY,
    @VAMOUNT MONEY
  --以一张促销补差单里只有一个协议号位前提
  SELECT @VQPC = GD.QPC, @VQPCSTR = GD.QPCSTR, @VCNTINPRC = G.CNTINPRC,
    @VALC = ISNULL(G.ALC, '统配'), @VTAXRATE = G.TAXRATE
  FROM GDINPUT GD(NOLOCK), GOODS G(NOLOCK)
  WHERE GD.GID = G.GID
  AND GD.CODE = G.CODE
  AND G.GID = @PIGDGID
  SELECT @VAMOUNT = @PITOTAL / (1 + (@VTAXRATE / 100))
  SELECT @VTAX = @PITOTAL - @VAMOUNT
  SELECT @VLINE = LINE FROM PRMOFFSETDTLTEMP(NOLOCK)
  WHERE SPID = @@SPID AND NUM = @PINUM AND GDGID = @PIGDGID
  IF @VLINE IS NULL
  BEGIN
    SELECT @VLINE = ISNULL(MAX(LINE) + 1, 1) FROM PRMOFFSETDTLTEMP(NOLOCK)
    WHERE SPID = @@SPID AND NUM = @PINUM
    INSERT INTO PRMOFFSETDTLTEMP(SPID, NUM, LINE, SETTLENO, GDGID, QPC, QPCSTR, AGMNUM, AGMLINE, SAMT, RAMT, OFFSETPRC,
      CNTINPRC, QTY, START, FINISH, NOTE, ALC, TOTAL, AMOUNT, TAX, DIFFPRC, PAYQTY, PAYAMT, SQTY, AGMTABLENAME)
    VALUES(@@SPID, @PINUM, @VLINE, @PISETTLENO, @PIGDGID, @VQPC, @VQPCSTR, @PIAGMNUM, @PIAGMLINE, @PITOTAL, @PITOTAL, null,
      @VCNTINPRC, @PIQTY, @PISTART, @PIFINISH, NULL, @VALC, @PITOTAL, @VAMOUNT, @VTAX, 0, 0, 0, @PIQTY, @PIAGMTABLENAME)
  END
  ELSE BEGIN
    UPDATE PRMOFFSETDTLTEMP SET SAMT = SAMT + @PITOTAL, RAMT = RAMT + @PITOTAL,
      QTY = QTY + @PIQTY, SQTY = SQTY + @PIQTY,
      TOTAL = TOTAL + @PITOTAL, AMOUNT = AMOUNT + @VAMOUNT, TAX = TAX + @VTAX
    WHERE SPID = @@SPID AND NUM = @PINUM AND LINE = @VLINE
  END
  RETURN(0)
END
GO
