SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[GDINVCHGNOTIFY_DOCHECK]
(
  @NUM CHAR(14),
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
  DECLARE 
    @OUTGDGID INT,
    @INGDGID INT,
    @OUTGDCODE VARCHAR(20),
    @OUTGDNAME VARCHAR(50),
    @INGDCODE VARCHAR(20),
    @INGDNAME VARCHAR(50),
    @OPT VARCHAR(1),
    @SETPKG INT,
    @LINE INT,
    @CNT INT 
    
  EXEC OPTREADSTR 466, 'ONEBYONERELATION', '0', @OPT OUTPUT
  SELECT @SETPKG = SETPKG FROM GDINVCHGNOTIFY(NOLOCK) WHERE NUM = @NUM
  SET @MSG = ''
  DECLARE C CURSOR FOR
    SELECT OUTGDGID, INGDGID, LINE FROM GDINVCHGNOTIFYDTL(NOLOCK) WHERE NUM = @NUM
  OPEN C
  FETCH NEXT FROM C INTO @OUTGDGID, @INGDGID, @LINE 
  WHILE @@FETCH_STATUS = 0 
  BEGIN
    SELECT @OUTGDCODE = LTRIM(RTRIM(GO.CODE)), @OUTGDNAME = LTRIM(RTRIM(GO.NAME)), 
      @INGDCODE = LTRIM(RTRIM(GI.CODE)), @INGDNAME = LTRIM(RTRIM(GI.NAME)) 
    FROM GOODSH GO(NOLOCK), GOODSH GI(NOLOCK)
    WHERE GO.GID = @OUTGDGID AND GI.GID = @INGDGID
        
    IF EXISTS (SELECT 1 FROM GOODS(NOLOCK) WHERE GID = @OUTGDGID AND ISPKG = 1)
    BEGIN    
      SET @MSG = '大包装商品 ' + @OUTGDNAME + '[' + @OUTGDCODE + '] 已经为大包装商品' 
      BREAK
    END
    
    IF EXISTS (SELECT 1 FROM GOODS(NOLOCK) WHERE GID = @OUTGDGID AND ISNULL(ISBIND, 0) = 1)
    BEGIN    
      SET @MSG = '大包装商品 ' + @OUTGDNAME + '[' + @OUTGDCODE + '] 为捆绑商品' 
      BREAK
    END
    
    IF @OUTGDGID = @INGDGID 
    BEGIN
      SET @MSG = '大包装商品 ' + @OUTGDNAME + '[' + @OUTGDCODE + '] 和基本商品' + @INGDNAME + '[' + @INGDCODE + ']相同'  
      BREAK
    END
    
    IF EXISTS (SELECT 1 FROM GOODS(NOLOCK) WHERE GID = @INGDGID AND ISPKG = 1)
    BEGIN    
      SET @MSG = '基本商品 ' + @INGDNAME + '[' + @INGDCODE + '] 为大包装商品' 
      BREAK
    END
    
    IF EXISTS (SELECT 1 FROM GOODS(NOLOCK) WHERE GID = @INGDGID AND ISNULL(ISBIND, 0) = 1)
    BEGIN    
      SET @MSG = '基本商品 ' + @INGDNAME + '[' + @INGDCODE + '] 为捆绑商品' 
      BREAK
    END
    
    IF @OPT = 1 
    BEGIN
      IF EXISTS (SELECT 1 FROM INVCHG(NOLOCK) WHERE GDGID IN (@OUTGDGID, @INGDGID) OR GDGID2 IN (@OUTGDGID, @INGDGID))
      BEGIN
        SET @MSG = '第' + LTRIM(RTRIM(@LINE)) + '行大包装或基本商品在库存转换关系表已存在' 
        BREAK
      END
    END
    
    IF @SETPKG = 1
    BEGIN
      SELECT @CNT = COUNT(1) FROM (SELECT SALE FROM GOODS(NOLOCK) WHERE GID IN (@OUTGDGID, @INGDGID) GROUP BY SALE) A
      IF @CNT > 1 
      BEGIN
        SET @MSG = '大包装商品 ' + @OUTGDNAME + '[' + @OUTGDCODE + '] 和基本商品' + @INGDNAME + '[' + @INGDCODE + ']营销方式不相同'  
        BREAK
      END
      SELECT @CNT = COUNT(1) FROM (SELECT BILLTO FROM GOODS(NOLOCK) WHERE GID IN (@OUTGDGID, @INGDGID) GROUP BY BILLTO) A
      IF @CNT > 1 
      BEGIN
        SET @MSG = '大包装商品 ' + @OUTGDNAME + '[' + @OUTGDCODE + '] 和基本商品' + @INGDNAME + '[' + @INGDCODE + ']缺省供应商不相同'  
        BREAK
      END
    END
    
    FETCH NEXT FROM C INTO @OUTGDGID, @INGDGID, @LINE
  END  
  CLOSE C
  DEALLOCATE C  

  IF @MSG = '' RETURN 0
  ELSE RETURN 1
END
GO
