SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create procedure [dbo].[CHQSNDVENDOR](
	@GID INT,
	@OPERGID INT,
	@MSG VARCHAR(255) OUTPUT
) as
begin
  declare @GROUPID INT,     @NTYPE SMALLINT,    @NNOTE varchar(100),
          @EXTIME DATETIME, @RHQUUID CHAR(32),  @NSTAT SMALLINT
  
  --exec OPTREADINT 0, '...', 0, @optvalue output
  exec @GROUPID = SeqNextValue 'CHQBASIC'
  set @RHQUUID = '1'
  set @NTYPE = 0
  set @NNOTE = ''
  set @NSTAT = 0
  set @EXTIME = Getdate()
  insert into CQNVENDOR(GROUPID, RHQUUID, NTYPE, NSTAT, NNOTE, EXTIME, 
      GID, CODE, NAME, SHORTNAME, ADDRESS, TAXNO, ACCOUNTNO, 
      FAX, ZIP, TELE, CREATEDATE, PROPERTY, SETTLEACCOUNT, PAYTERM, 
      MEMO, LAWREP, CONTACTOR, CTRPHONE, CTRBP, SRC, SNDTIME, 
      LSTUPDTIME, FILLER, MODIFIER, KEEPAMT, TAXTYPE, EMAILADR, 
      WWWADR, CDTRATE, ADFEE, PRMFEE, INVCODE, DAYS, PAYCLS, MVDR, 
      ISUSETOKEN, SAFEAMT, PAYLIMITED, SendArea, PayType, UpCtrl, SendType, UPay, SendLocation)
    select @GROUPID, @RHQUUID, @NTYPE, @NSTAT, @NNOTE, @EXTIME, 
      GID, CODE, NAME, SHORTNAME, ADDRESS, TAXNO, ACCOUNTNO, 
      FAX, ZIP, TELE, CREATEDATE, PROPERTY, SETTLEACCOUNT, PAYTERM, 
      MEMO, LAWREP, CONTACTOR, CTRPHONE, CTRBP, SRC, SNDTIME, 
      LSTUPDTIME, FILLER, MODIFIER, KEEPAMT, TAXTYPE, EMAILADR, 
      WWWADR, CDTRATE, ADFEE, PRMFEE, INVCODE, DAYS, PAYCLS, MVDR, 
      ISUSETOKEN, SAFEAMT, PAYLIMITED, SendArea, PayType, UpCtrl, SendType, UPay, SendLocation
    from VENDOR(nolock)
    where GID = @GID
end;
GO
