SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CHKICPAYTO600]
(
  @NUM CHAR(14),
  @OPER CHAR(30),
  @CLS	 CHAR(10),
  @TOSTAT INT,
  @MSG VARCHAR(255) OUTPUT
)
AS
BEGIN
	UPDATE ICPAY SET STAT = 600, CARDTIME = GETDATE(), MODIFIER = @OPER, LSTUPDTIME = GETDATE() WHERE NUM = @NUM
	RETURN 0
END
GO
