SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SALEDIFFFINISH] (
  @NUM	CHAR(14),
  @OPER	INT = 1
) AS
BEGIN
  DECLARE @FINISHED INT
  SELECT @FINISHED = FINISHED FROM SALEDIF WHERE NUM = @NUM
  IF @@ROWCOUNT = 0
  BEGIN
    RAISERROR('单据%s不存在', 16, 1, @NUM);
    RETURN 1
  END ELSE IF @FINISHED = 1
  BEGIN
    RAISERROR('单据%s已结束', 16, 1, @NUM)
    RETURN 1
  END
  UPDATE SALEDIF SET FINISHED = 1 WHERE NUM = @NUM
  
  RETURN 0
END
GO
