SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[LTDADJCHK] (
  @NUM	CHAR(14),
  @OPER	INT
) AS
BEGIN
  DECLARE @STAT INT
  DECLARE @LAUNCH DATETIME
  DECLARE @RET INT

  SELECT @STAT = STAT, @LAUNCH = LAUNCH
  FROM LTDADJ WHERE NUM = @NUM
  IF @STAT <> 0
  BEGIN
  	RAISERROR('单据%s不是未审核单据', 16, 1, @NUM);
  	RETURN 1
  END

  UPDATE LTDADJ SET STAT = 100, CHECKER = @OPER, FILDATE = GETDATE() WHERE NUM = @NUM

  IF (@LAUNCH IS NULL) OR (@LAUNCH <= GETDATE())
  BEGIN
    EXEC @RET = LTDADJOCR @NUM, @OPER
    IF @RET <> 0 RETURN @RET
  END

  RETURN 0
END
GO
