SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SENDONEPROMB]
(
 	@NUM	VARCHAR(14),
   	@SRC	INT,
   	@RCV	INT,   	
   	@MSG	VARCHAR(255) OUTPUT
)
AS
BEGIN
    DECLARE
	@id int
	
	execute GETNETBILLID @id output

	insert into NPROMB (ID, SRC, NUM, STAT, FILDATE, FILLER, SNDTIME,
			PRNTIME, LSTUPDTIME, TOPIC, STORESCOPE, NOTE, ASTART, AFINISH,
			CYCLE, CSTART, CFINISH, CSPEC, RCV, RCVTIME, TYPE, NSTAT, NNOTE,RECCNT,PSETTLENO,OCRTIME, DLTPRICEPROM)
		SELECT @id, @SRC, @NUM, STAT, FILDATE,FILLER,getdate(),
			PRNTIME,LSTUPDTIME,TOPIC,STORESCOPE,NOTE,ASTART,AFINISH,
			CYCLE, CSTART, CFINISH, CSPEC, @RCV, null, 0, 0, '',RECCNT,PSETTLENO,OCRTIME, DLTPRICEPROM
		from PROMB
		where NUM = @NUM
	INSERT INTO NPROMBGOODS (SRC, ID, NUM,LINE,GDGID,
			GDCODE,QPC,QPCSTR,RTLPRC,MBRPRC,CNTRINPRC,COST,PRMDIV1,PRMDIV2,PRMDIV3, ISDLT)
		select @SRC, @ID, @NUM, LINE, GDGID,
			GDCODE,QPC,QPCSTR,RTLPRC,MBRPRC,CNTRINPRC,COST,PRMDIV1,PRMDIV2,PRMDIV3, ISDLT
		from PROMBGOODS
		where NUM = @NUM
	INSERT INTO NPROMBDIS (SRC, ID, NUM, QTY, RTLPRC)
	    SELECT @SRC, @ID, @NUM, QTY, RTLPRC
	    FROM PROMBDIS
	    WHERE NUM = @NUM
	RETURN(0)
END
GO
