CREATE TABLE [dbo].[BPCK]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NULL,
[FILDATE] [datetime] NULL CONSTRAINT [DF__BPCK__FILDATE__560A9D62] DEFAULT (getdate()),
[FILLER] [int] NULL,
[WRH] [int] NULL,
[STAT] [smallint] NULL CONSTRAINT [DF__BPCK__STAT__56FEC19B] DEFAULT (0),
[RECCNT] [smallint] NULL CONSTRAINT [DF__BPCK__RECCNT__57F2E5D4] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[ImportNum] [char] (10) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BPCK] WITH NOCHECK ADD CONSTRAINT [BPCK_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[BPCK] ADD CONSTRAINT [PK__BPCK__1975C517] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
