CREATE TABLE [dbo].[RCPCST]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NULL,
[FILDATE] [datetime] NULL,
[FILLER] [int] NULL,
[CHECKER] [int] NULL,
[CLIENT] [int] NULL,
[WRH] [int] NULL,
[STAT] [smallint] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[PRNTIME] [datetime] NULL,
[INIBAL] [money] NULL,
[OCRTOTAL] [money] NULL,
[PAYTOTAL] [money] NULL,
[PAY] [money] NULL,
[Paycls] [varchar] (25) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RCPCST] WITH NOCHECK ADD CONSTRAINT [RCPCST_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[RCPCST] ADD CONSTRAINT [PK__RCPCST__0BB1B5A5] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FILDATE] ON [dbo].[RCPCST] ([FILDATE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
