CREATE TABLE [dbo].[SALEBCK]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__SALEBCK__FILDATE__4515E6E1] DEFAULT (getdate()),
[FILLER] [int] NOT NULL CONSTRAINT [DF__SALEBCK__FILLER__460A0B1A] DEFAULT (1),
[WRH] [int] NOT NULL,
[INVNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TOTAL] [money] NOT NULL,
[STAT] [smallint] NOT NULL,
[ACPTIME] [datetime] NULL,
[ACPEMP] [int] NULL,
[PAYTIME] [datetime] NULL,
[PAYEMP] [int] NULL,
[OPER] [int] NULL,
[RECCNT] [int] NOT NULL,
[DSPNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[PAYMODE] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[FINISHED] [smallint] NOT NULL CONSTRAINT [DF__SALEBCK__FINISHE__597CD241] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SALEBCK] WITH NOCHECK ADD CONSTRAINT [SALEBCK_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[SALEBCK] ADD CONSTRAINT [PK__SALEBCK__18178C8A] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
