CREATE TABLE [dbo].[CRMSCOREADJ]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__CRMSCOREAD__STAT__2C76B84E] DEFAULT (0),
[REVSCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMSCOREA__REVSC__2D6ADC87] DEFAULT (0),
[SCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMSCOREA__SCORE__2E5F00C0] DEFAULT (0),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__CRMSCOREA__FILDA__2F5324F9] DEFAULT (getdate()),
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMSCOREADJ] ADD CONSTRAINT [PK__CRMSCOREADJ__30474932] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
