CREATE TABLE [dbo].[NEMPLOYEE]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[GID] [int] NOT NULL,
[CODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[IDCARD] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[WORKTYPE] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[DISCOUNT] [money] NOT NULL CONSTRAINT [DF__NEMPLOYEE__DISCO__0DB0A35E] DEFAULT (100),
[CREATEDATE] [datetime] NOT NULL CONSTRAINT [DF__NEMPLOYEE__CREAT__0EA4C797] DEFAULT (getdate()),
[PASSWORD] [char] (32) COLLATE Chinese_PRC_CI_AS NULL,
[LOCALRIGHT] [text] COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NEMPLOYEE__LOCAL__0F98EBD0] DEFAULT (''),
[LOCALEXTRARIGHT] [char] (255) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NEMPLOYEE__LOCAL__108D1009] DEFAULT (''),
[MEMO] [char] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL CONSTRAINT [DF__NEMPLOYEE__SRC__11813442] DEFAULT (1),
[SNDTIME] [datetime] NOT NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[FRCUPD] [smallint] NOT NULL,
[TYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[ISUSETOKEN] [smallint] NOT NULL CONSTRAINT [DF__NEMPLOYEE__ISUSE__4DE10263] DEFAULT (0),
[ISSPECLIM] [smallint] NOT NULL CONSTRAINT [DF__NEMPLOYEE__ISSPE__4020EBA4] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NEMPLOYEE] ADD CONSTRAINT [PK__NEMPLOYEE__278EDA44] PRIMARY KEY CLUSTERED  ([SRC], [ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
