CREATE TABLE [dbo].[NPRMOFFSETAGMDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[MUNIT] [char] (6) COLLATE Chinese_PRC_CI_AS NULL,
[QPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPRMOFFSETA__QPC__4CFC8F2C] DEFAULT (1),
[QPCSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NPRMOFFSE__QPCST__4DF0B365] DEFAULT ('1*1'),
[AGMCNTINPRC] [decimal] (24, 4) NULL,
[AGMPRC] [decimal] (24, 4) NULL,
[DIFFPRC] [decimal] (24, 4) NOT NULL,
[TOPQTY] [decimal] (24, 4) NULL,
[TOPAMT] [decimal] (24, 2) NULL,
[ASTART] [datetime] NULL,
[AFINISH] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPRMOFFSETAGMDTL] ADD CONSTRAINT [PK__NPRMOFFSETAGMDTL__4EE4D79E] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPRMOFFSETAGMDTL_GDGID] ON [dbo].[NPRMOFFSETAGMDTL] ([GDGID]) ON [PRIMARY]
GO
