CREATE TABLE [dbo].[INPRCADJINVDTL]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SETTLENO] [int] NOT NULL,
[STORE] [int] NOT NULL,
[WRH] [int] NULL,
[SUBWRH] [int] NULL,
[QTY] [money] NOT NULL,
[COST] [money] NOT NULL,
[ADJCOST] [money] NOT NULL,
[LACTIME] [datetime] NULL CONSTRAINT [DF__INPRCADJI__LACTI__7EA4354F] DEFAULT (getdate()),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INPRCADJINVDTL] ADD CONSTRAINT [PK__INPRCADJINVDTL__6FBF826D] PRIMARY KEY NONCLUSTERED  ([CLS], [NUM], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INPRCADJINVDTL] ADD CONSTRAINT [UQ__INPRCADJINVDTL__76EBA2E9] UNIQUE CLUSTERED  ([STORE], [WRH], [SUBWRH], [CLS], [NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
