CREATE TABLE [dbo].[CRMSCORESUBJECT]
(
[CODE] [char] (3) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DIRECT] [smallint] NOT NULL CONSTRAINT [DF__CRMSCORES__DIREC__40E7C54F] DEFAULT (1),
[NOTE] [char] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMSCORESUBJECT] ADD CONSTRAINT [PK__CRMSCORESUBJECT__41DBE988] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
