CREATE TABLE [dbo].[CHECKINPOOLS]
(
[ID] [int] NOT NULL,
[FILLTIME] [datetime] NOT NULL,
[OPERATOR] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CASHIER] [int] NOT NULL,
[STORENO] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[THEDATE] [datetime] NOT NULL,
[FROMDATE] [datetime] NOT NULL,
[AMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CHECKINPO__AMOUN__19E3D21E] DEFAULT (0),
[REALAMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CHECKINPO__REALA__1AD7F657] DEFAULT (0),
[RETAILAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CHECKINPO__RETAI__1BCC1A90] DEFAULT (0),
[MILKAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CHECKINPO__MILKA__1CC03EC9] DEFAULT (0),
[PUCAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CHECKINPO__PUCAM__1DB46302] DEFAULT (0),
[BILLCOUNT] [int] NOT NULL CONSTRAINT [DF__CHECKINPO__BILLC__1EA8873B] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CHECKINPOOLS] ADD CONSTRAINT [PK__CHECKINPOOLS__18EFADE5] PRIMARY KEY CLUSTERED  ([ID], [STORENO], [THEDATE], [CASHIER]) ON [PRIMARY]
GO
