CREATE TABLE [dbo].[NCHARGECHKDTL2]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[NUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[PAYCLS] [smallint] NOT NULL,
[TOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCHARGECH__TOTAL__6E3BF0B8] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCHARGECHKDTL2] ADD CONSTRAINT [PK__NCHARGECHKDTL2__6F3014F1] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) ON [PRIMARY]
GO
