CREATE TABLE [dbo].[NRTLBCKCURDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[CURRENCY] [smallint] NOT NULL,
[AMOUNT] [decimal] (24, 4) NOT NULL,
[ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NRTLBCKCURDTL] ADD CONSTRAINT [PK__NRTLBCKCURDTL__76A582D9] PRIMARY KEY CLUSTERED  ([ID], [ITEMNO]) ON [PRIMARY]
GO
