CREATE TABLE [dbo].[PROMOTEMONEY]
(
[BILLNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PRMNO] [int] NOT NULL,
[TOTAL] [decimal] (24, 2) NOT NULL,
[PRMTOTAL] [decimal] (24, 2) NOT NULL,
[IFGFT] [int] NOT NULL,
[GFTQTY] [decimal] (24, 4) NOT NULL,
[PTOTAL] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PROMOTEMO__PTOTA__64F1B249] DEFAULT (0),
[ISFULL] [int] NOT NULL CONSTRAINT [DF__PROMOTEMO__ISFUL__65E5D682] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROMOTEMONEY] ADD CONSTRAINT [PK__PROMOTEMONEY__66D9FABB] PRIMARY KEY CLUSTERED  ([BILLNUM], [CLS], [PRMNO]) ON [PRIMARY]
GO
