CREATE TABLE [dbo].[DSPREGDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[SETTLENO] [int] NOT NULL,
[DSPLINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[AVAQTY] [money] NOT NULL,
[QTY] [money] NOT NULL,
[SUBWRH] [int] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[INVQTY] [money] NOT NULL,
[SUBQTY] [money] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DSPREGDTL] ADD CONSTRAINT [PK__DSPREGDTL__4FD1D5C8] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [dspregdtl_gdgid] ON [dbo].[DSPREGDTL] ([GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
