CREATE TABLE [dbo].[PSTASKFORMULA]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FCODE] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSTASKFORMULA] ADD CONSTRAINT [PK__PSTASKFORMULA__0770E77F] PRIMARY KEY CLUSTERED  ([NUM], [FCODE]) ON [PRIMARY]
GO
