CREATE TABLE [dbo].[TMPPROCEXECRAWDTL]
(
[SPID] [int] NOT NULL,
[RAW] [smallint] NOT NULL CONSTRAINT [DF__TMPPROCEXEC__RAW__00B9C84F] DEFAULT (1),
[GDGID] [int] NULL,
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__TMPPROCEXEC__QTY__01ADEC88] DEFAULT (0)
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_TMPPROCEXECRAWDTL_SPID] ON [dbo].[TMPPROCEXECRAWDTL] ([SPID]) ON [PRIMARY]
GO
