CREATE TABLE [dbo].[PS3NOTSCOREGDSCOPEINV]
(
[UUID] [varchar] (36) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DEPT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[VENDOR] [int] NULL,
[SORT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[BRAND] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[GDGID] [int] NULL,
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[SRCNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PS3NOTSCO__SRCNU__2DA3DF64] DEFAULT ('-'),
[SRCCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PS3NOTSCO__SRCCL__2E98039D] DEFAULT ('-')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3NOTSCOREGDSCOPEINV] ADD CONSTRAINT [PK__PS3NOTSCOREGDSCO__29143471] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3NOTSCOREGDSCOPEINV_4] ON [dbo].[PS3NOTSCOREGDSCOPEINV] ([BRAND]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3NOTSCOREGDSCOPEINV_1] ON [dbo].[PS3NOTSCOREGDSCOPEINV] ([DEPT]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3NOTSCOREGDSCOPEINV_5] ON [dbo].[PS3NOTSCOREGDSCOPEINV] ([GDGID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3NOTSCOREGDSCOPEINV_3] ON [dbo].[PS3NOTSCOREGDSCOPEINV] ([SORT]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3NOTSCOREGDSCOPEINV_6] ON [dbo].[PS3NOTSCOREGDSCOPEINV] ([SRCNUM], [SRCCLS]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3NOTSCOREGDSCOPEINV_2] ON [dbo].[PS3NOTSCOREGDSCOPEINV] ([VENDOR]) ON [PRIMARY]
GO
