CREATE TABLE [dbo].[CTCNTRRATEGUARDCHG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VERSION] [smallint] NOT NULL,
[LINE] [smallint] NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[OTHERCNTRNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OTHERCHGCODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CTCNTRRATEGUARDCHG] ADD CONSTRAINT [PK__CTCNTRRATEGUARDC__702F2622] PRIMARY KEY CLUSTERED  ([NUM], [VERSION], [LINE], [ITEMNO]) ON [PRIMARY]
GO
