CREATE TABLE [dbo].[PRCADJDTLHST]
(
[GDGID] [int] NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[LSTADJTIME] [datetime] NULL,
[PRCADJNUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PRCADJFILDATE] [datetime] NULL,
[GDQPCSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PRCADJDTL__GDQPC__6BB489C8] DEFAULT ('1*1'),
[OLDPRC] [decimal] (24, 4) NULL,
[NEWPRC] [decimal] (24, 4) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRCADJDTLHST] ADD CONSTRAINT [PK__PRCADJDTLHST__6CA8AE01] PRIMARY KEY CLUSTERED  ([CLS], [LINE], [PRCADJNUM]) ON [PRIMARY]
GO
