CREATE TABLE [dbo].[GDINVCHG]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[TOTAL] [money] NOT NULL,
[TAX] [money] NOT NULL,
[FILDATE] [datetime] NOT NULL,
[FILLER] [int] NOT NULL CONSTRAINT [DF__GDINVCHG__FILLER__0080C572] DEFAULT (1),
[CHECKER] [int] NOT NULL CONSTRAINT [DF__GDINVCHG__CHECKE__0174E9AB] DEFAULT (1),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__GDINVCHG__STAT__02690DE4] DEFAULT (0),
[MODNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[PSR] [int] NOT NULL CONSTRAINT [DF__GDINVCHG__PSR__035D321D] DEFAULT (1),
[RECCNT] [int] NOT NULL,
[PRNTIME] [datetime] NULL,
[PRECHECKER] [int] NULL CONSTRAINT [DF__GDINVCHG__PRECHE__04515656] DEFAULT (0),
[PRECHKDATE] [datetime] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GDINVCHG] ADD CONSTRAINT [GDINVCHG_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[GDINVCHG] ADD CONSTRAINT [PK__GDINVCHG__7F8CA139] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FILDATE] ON [dbo].[GDINVCHG] ([FILDATE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
