CREATE TABLE [dbo].[JMSTOREPAY]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GENCLS] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREID] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STORENAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[SETTLENO] [int] NOT NULL,
[FEECLS] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VAL1] [float] NULL CONSTRAINT [DF__JMSTOREPAY__VAL1__5524937D] DEFAULT (0),
[VAL2] [float] NULL CONSTRAINT [DF__JMSTOREPAY__VAL2__5618B7B6] DEFAULT (0),
[VAL3] [float] NULL CONSTRAINT [DF__JMSTOREPAY__VAL3__570CDBEF] DEFAULT (0),
[STATE] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__JMSTOREPA__STATE__58010028] DEFAULT (0),
[EMP] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[CHECKER] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[JMSTOREPAY] ADD CONSTRAINT [PK__JMSTOREPAY__58F52461] PRIMARY KEY CLUSTERED  ([NUM], [GENCLS], [STOREID], [SETTLENO], [FEECLS]) ON [PRIMARY]
GO
