CREATE TABLE [dbo].[AMTADJ]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FILLER] [int] NOT NULL CONSTRAINT [DF__AMTADJ__FILLER__353F71CB] DEFAULT (1),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__AMTADJ__FILDATE__36339604] DEFAULT (getdate()),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__AMTADJ__STAT__3727BA3D] DEFAULT (0),
[CHECKER] [int] NULL,
[WRH] [int] NOT NULL,
[CLIENT] [int] NOT NULL,
[ADJAMT] [money] NOT NULL,
[RECCNT] [int] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AMTADJ] WITH NOCHECK ADD CONSTRAINT [AMTADJ_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[AMTADJ] ADD CONSTRAINT [PK__AMTADJ__0EF836A4] PRIMARY KEY CLUSTERED  ([CLS], [NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
