CREATE TABLE [dbo].[CSTGD]
(
[CSTGID] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[CSTGDCODE] [char] (13) COLLATE Chinese_PRC_CI_AS NULL,
[SALE] [smallint] NOT NULL,
[ALCQTY] [money] NOT NULL CONSTRAINT [DF__CSTGD__ALCQTY__64CE895C] DEFAULT (1),
[ALCPRC] [money] NOT NULL CONSTRAINT [DF__CSTGD__ALCPRC__65C2AD95] DEFAULT (0),
[ISLTD] [smallint] NULL CONSTRAINT [DF__CSTGD__ISLTD__66B6D1CE] DEFAULT (0),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__CSTGD__LSTUPDTIM__67AAF607] DEFAULT (getdate()),
[LSTMODIFIER] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[MEMO] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[CODE2] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[CRTLPRC] [money] NOT NULL CONSTRAINT [DF__cstgd__CRTLPRC__71F37A50] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CSTGD] ADD CONSTRAINT [PK__CSTGD__63DA6523] PRIMARY KEY CLUSTERED  ([GDGID], [CSTGID]) ON [PRIMARY]
GO
