CREATE TABLE [dbo].[GDDRPTPOOL]
(
[ID] [int] NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ADATE] [datetime] NOT NULL,
[GDGID] [int] NOT NULL,
[DQ1] [money] NOT NULL CONSTRAINT [DF__GDDRPTPOOL__DQ1__69409AC3] DEFAULT (0),
[DQ2] [money] NOT NULL CONSTRAINT [DF__GDDRPTPOOL__DQ2__6A34BEFC] DEFAULT (0),
[DT1] [money] NOT NULL CONSTRAINT [DF__GDDRPTPOOL__DT1__6B28E335] DEFAULT (0),
[DT2] [money] NOT NULL CONSTRAINT [DF__GDDRPTPOOL__DT2__6C1D076E] DEFAULT (0),
[DT3] [money] NOT NULL CONSTRAINT [DF__GDDRPTPOOL__DT3__6D112BA7] DEFAULT (0),
[DI1] [money] NOT NULL CONSTRAINT [DF__GDDRPTPOOL__DI1__6E054FE0] DEFAULT (0),
[DI2] [money] NOT NULL CONSTRAINT [DF__GDDRPTPOOL__DI2__6EF97419] DEFAULT (0),
[DR1] [money] NOT NULL CONSTRAINT [DF__GDDRPTPOOL__DR1__6FED9852] DEFAULT (0),
[DR2] [money] NOT NULL CONSTRAINT [DF__GDDRPTPOOL__DR2__70E1BC8B] DEFAULT (0),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__GDDRPTPOOL__STAT__0D09C544] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GDDRPTPOOL] ADD CONSTRAINT [PK__GDDRPTPOOL__71D5E0C4] PRIMARY KEY CLUSTERED  ([ID], [POSNO], [ADATE], [GDGID]) ON [PRIMARY]
GO
