CREATE TABLE [dbo].[POLYPRCPRMLACDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[POLYPRCPRMLACDTL] ADD CONSTRAINT [PK__POLYPRCPRMLACDTL__33B1BE75] PRIMARY KEY CLUSTERED  ([NUM], [STOREGID]) ON [PRIMARY]
GO
