CREATE TABLE [dbo].[ALCDIFFDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[SRCNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CASES] [decimal] (24, 4) NOT NULL,
[QTY] [decimal] (24, 4) NOT NULL,
[WRH] [int] NOT NULL CONSTRAINT [DF__ALCDIFFDTL__WRH__16D25B49] DEFAULT (1),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ALCDIFFDTL] ADD CONSTRAINT [PK__ALCDIFFDTL__17C67F82] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
