CREATE TABLE [dbo].[XSRVTASKDTL]
(
[TID] [int] NOT NULL,
[OID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[XSRVTASKDTL] ADD CONSTRAINT [PK__XSRVTASKDTL__43E296DD] PRIMARY KEY CLUSTERED  ([TID], [OID]) ON [PRIMARY]
GO
