CREATE TABLE [dbo].[GDINVCHGNOTIFYDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[OUTGDGID] [int] NOT NULL,
[INGDGID] [int] NOT NULL,
[RELQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__GDINVCHGN__RELQT__34396C55] DEFAULT (1),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GDINVCHGNOTIFYDTL] ADD CONSTRAINT [PK__GDINVCHGNOTIFYDT__352D908E] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
