CREATE TABLE [dbo].[CRMCARDINVSTAT]
(
[STAT] [smallint] NOT NULL,
[NAME] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMCARDINVSTAT] ADD CONSTRAINT [PK__CRMCARDINVSTAT__6C5C3339] PRIMARY KEY CLUSTERED  ([STAT]) ON [PRIMARY]
GO
