CREATE TABLE [dbo].[BILLRELATE]
(
[FROMNUM] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FROMCLS] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TOTAL] [money] NOT NULL CONSTRAINT [DF__BILLRELAT__TOTAL__41EF6173] DEFAULT (0),
[TAX] [money] NOT NULL CONSTRAINT [DF__BILLRELATE__TAX__42E385AC] DEFAULT (0),
[TAXNUM] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TAXCLS] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BTOTAL] [money] NOT NULL CONSTRAINT [DF__BILLRELAT__BTOTA__43D7A9E5] DEFAULT (0),
[BTAX] [money] NOT NULL CONSTRAINT [DF__BILLRELATE__BTAX__44CBCE1E] DEFAULT (0),
[ACRDATE] [datetime] NOT NULL,
[TAXNO] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[BTYPE] [smallint] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__BILLRELATE__STAT__45BFF257] DEFAULT (0),
[FILDATE] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BILLRELATE] ADD CONSTRAINT [PK__BILLRELATE__178D7CA5] PRIMARY KEY CLUSTERED  ([FROMNUM], [FROMCLS], [TAXNUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
