CREATE TABLE [dbo].[GDWRH]
(
[GDGID] [int] NOT NULL,
[WRH] [int] NOT NULL,
[INVPRC] [money] NOT NULL CONSTRAINT [DF__GDWRH__INVPRC__1FC466A1] DEFAULT (0),
[INVCOST] [money] NOT NULL CONSTRAINT [DF__GDWRH__INVCOST__20B88ADA] DEFAULT (0)
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[GDWRH_UPD]
ON [dbo].[GDWRH]
FOR  UPDATE 
AS 
IF UPDATE(INVPRC)
BEGIN
UPDATE GOODS SET INVPRC=INSERTED.INVPRC 
FROM INSERTED
WHERE GOODS.GID=INSERTED.GDGID 
and INSERTED.WRH=1
END
GO
ALTER TABLE [dbo].[GDWRH] ADD CONSTRAINT [PK__GDWRH__1ED04268] PRIMARY KEY CLUSTERED  ([GDGID], [WRH]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
