CREATE TABLE [dbo].[PS3_ONLINECNTRRATEDISC]
(
[UUID] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PLATFORM] [varchar] (80) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CNTRNO] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DLINE] [smallint] NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[LOWAMT] [decimal] (24, 2) NOT NULL,
[HIGHAMT] [decimal] (24, 2) NOT NULL,
[RATE] [decimal] (24, 4) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3_ONLINECNTRRATEDISC] ADD CONSTRAINT [PK__PS3_ONLI__0C2ECB37355E0878] PRIMARY KEY CLUSTERED  ([UUID], [DLINE], [ITEMNO]) ON [PRIMARY]
GO
