CREATE TABLE [dbo].[ALCSCHEME]
(
[CODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[BELONGHEADQ] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ALCSCHEME] ADD CONSTRAINT [PK__AlcScheme__57B7B2BC] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
