CREATE TABLE [dbo].[PAYADJ]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NULL,
[FILDATE] [datetime] NULL,
[FILLER] [int] NULL,
[CHECKER] [int] NULL,
[WRH] [int] NULL,
[BILLTO] [int] NULL,
[STAT] [int] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[PRNTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAYADJ] WITH NOCHECK ADD CONSTRAINT [PAYADJ_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[PAYADJ] ADD CONSTRAINT [PK__PAYADJ__658C0CBD] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FILDATE] ON [dbo].[PAYADJ] ([FILDATE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
