CREATE TABLE [dbo].[PS3_ONLINERETURNORD]
(
[PLATFORM] [varchar] (80) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ORDNO] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SHOPNO] [varchar] (8) COLLATE Chinese_PRC_CI_AS NOT NULL,
[RTNTYPE] [varchar] (16) COLLATE Chinese_PRC_CI_AS NULL,
[STAT] [varchar] (16) COLLATE Chinese_PRC_CI_AS NULL,
[APPROVESTAT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CREATOR] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CREATEDATE] [datetime] NOT NULL CONSTRAINT [DF__PS3_ONLIN__CREAT__13481C3F] DEFAULT (getdate()),
[LSTMODIFIER] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTMODTIME] [datetime] NOT NULL CONSTRAINT [DF__PS3_ONLIN__LSTMO__143C4078] DEFAULT (getdate()),
[CSTNAME] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[CSTPHONE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[CSTADDRESS] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[ORDID] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CSTNOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[REFUNDSTAT] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FREIGHT] [decimal] (24, 2) NOT NULL,
[AMOUNT] [decimal] (24, 2) NOT NULL,
[SETTLEAMOUNT] [decimal] (24, 2) NULL,
[RTNSTATE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[DLVMAN] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[DLVPHONE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[OPERATIONSTAT] [smallint] NOT NULL CONSTRAINT [DF__PS3_ONLIN__OPERA__153064B1] DEFAULT (0),
[OPERATIONNOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[UUID] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLFROM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[SRCORDNO] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[RTNCTNAME] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[RTNCTPHONE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[RTNCTADDRESS] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SHOPAMOUNT] [decimal] (24, 2) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3_ONLINERETURNORD] ADD CONSTRAINT [PK__PS3_OnLineReturn__162488EA] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3_OnLineReturnOrd_PO] ON [dbo].[PS3_ONLINERETURNORD] ([PLATFORM], [ORDNO]) ON [PRIMARY]
GO
