CREATE TABLE [dbo].[NTAXSORTADJ]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NTAXSORTA__FILDA__6A9B0C67] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__NTAXSORTA__RECCN__6B8F30A0] DEFAULT ((0)),
[STAT] [smallint] NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[NSTAT] [smallint] NOT NULL CONSTRAINT [DF__NTAXSORTA__NSTAT__6C8354D9] DEFAULT ((0)),
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[RCV] [int] NOT NULL,
[LAUNCH] [datetime] NULL,
[SNDTIME] [datetime] NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__NTAXSORTA__LSTUP__6D777912] DEFAULT (getdate()),
[PROVINCE] [char] (32) COLLATE Chinese_PRC_CI_AS NULL,
[FRCCHK] [int] NOT NULL CONSTRAINT [DF__NTAXSORTA__FRCCH__6E6B9D4B] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NTAXSORTADJ] ADD CONSTRAINT [PK__NTAXSORT__A93FC8E37053E5BD] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NTAXSORTADJ_TYPE] ON [dbo].[NTAXSORTADJ] ([TYPE]) ON [PRIMARY]
GO
