CREATE TABLE [dbo].[PAYCURRENCYCONF]
(
[PAYCURRENCY] [int] NOT NULL,
[PAYCOSTCURRENCY] [int] NULL,
[PAYDLL] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PORTNO] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAYCURRENCYCONF] ADD CONSTRAINT [PK__PAYCURRENCYCONF__34AC0B9C] PRIMARY KEY CLUSTERED  ([PAYCURRENCY]) ON [PRIMARY]
GO
