CREATE TABLE [dbo].[DSPDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[SALELINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[SALEPRICE] [money] NOT NULL,
[SALEQTY] [money] NOT NULL,
[SALETOTAL] [money] NOT NULL,
[DSPQTY] [money] NOT NULL CONSTRAINT [DF__DSPDTL__DSPQTY__3A98586E] DEFAULT (0),
[BCKQTY] [money] NOT NULL CONSTRAINT [DF__DSPDTL__BCKQTY__3B8C7CA7] DEFAULT (0),
[LSTDSPQTY] [money] NOT NULL CONSTRAINT [DF__DSPDTL__LSTDSPQT__3C80A0E0] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SUBWRH] [int] NULL,
[DSPTOTAL] [money] NULL CONSTRAINT [DF__DSPDTL__DSPTOTAL__5D0D6C03] DEFAULT (0),
[BCKTOTAL] [money] NULL CONSTRAINT [DF__DSPDTL__BCKTOTAL__5E01903C] DEFAULT (0),
[cls] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[posnocls] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[flowno] [char] (12) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DSPDTL] WITH NOCHECK ADD CONSTRAINT [提货数量不能大于销售数量] CHECK (([dspqty]<=[saleqty]))
GO
ALTER TABLE [dbo].[DSPDTL] WITH NOCHECK ADD CONSTRAINT [提货金额不能大于销售金额] CHECK (([dsptotal]<=[saletotal]))
GO
ALTER TABLE [dbo].[DSPDTL] ADD CONSTRAINT [PK__DSPDTL__4DE98D56] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [dspdtl_gdgid] ON [dbo].[DSPDTL] ([GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
