CREATE TABLE [dbo].[CQNSTKINBCKDTL2]
(
[GROUPID] [int] NOT NULL,
[RHQUUID] [char] (32) COLLATE Chinese_PRC_CI_AS NULL,
[NTYPE] [int] NOT NULL,
[NSTAT] [int] NOT NULL CONSTRAINT [DF__CQNSTKINB__NSTAT__269EAEBE] DEFAULT (0),
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[EXTIME] [datetime] NOT NULL CONSTRAINT [DF__CQNSTKINB__EXTIM__2792D2F7] DEFAULT (getdate()),
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CQNSTKINBCK__CLS__2886F730] DEFAULT ('自营'),
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SUBWRH] [int] NOT NULL,
[WRH] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNSTKINBCK__QTY__297B1B69] DEFAULT (0),
[COST] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNSTKINBC__COST__2A6F3FA2] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CQNSTKINBCKDTL2] ADD CONSTRAINT [PK__CQNSTKINBCKDTL2__2B6363DB] PRIMARY KEY CLUSTERED  ([GROUPID], [CLS], [NUM], [LINE], [SUBWRH]) ON [PRIMARY]
GO
