CREATE TABLE [dbo].[EMPRTLPLAN]
(
[AYEAR] [smallint] NOT NULL,
[AMONTH] [smallint] NOT NULL,
[EMPGID] [int] NOT NULL CONSTRAINT [DF__EMPRTLPLA__EMPGI__7A1EABFD] DEFAULT (1),
[TOTAL] [money] NOT NULL,
[PROFIT] [money] NOT NULL,
[PRORATE] [money] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMPRTLPLAN] ADD CONSTRAINT [PK__EMPRTLPLAN__567ED357] PRIMARY KEY CLUSTERED  ([AYEAR], [AMONTH], [EMPGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
