CREATE TABLE [dbo].[PSZBTASKMANGDDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[STOREGID] [int] NOT NULL CONSTRAINT [DF__PSZBTASKM__STORE__0D29C0D5] DEFAULT (0),
[HIGHINV] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PSZBTASKM__HIGHI__0E1DE50E] DEFAULT (0),
[LOWINV] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PSZBTASKM__LOWIN__0F120947] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSZBTASKMANGDDTL] ADD CONSTRAINT [PK__PSZBTASKMANGDDTL__10062D80] PRIMARY KEY CLUSTERED  ([NUM], [GDGID], [STOREGID]) ON [PRIMARY]
GO
