CREATE TABLE [dbo].[NRTLCURDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[CURRENCY] [smallint] NOT NULL,
[AMOUNT] [decimal] (24, 4) NOT NULL,
[CARDNUM] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NRTLCURDTL] ADD CONSTRAINT [PK__NRTLCURDTL__74BD3A67] PRIMARY KEY CLUSTERED  ([ID], [ITEMNO]) ON [PRIMARY]
GO
