CREATE TABLE [dbo].[NPSCP]
(
[ID] [int] NOT NULL,
[GID] [int] NOT NULL,
[CODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CREATEDATE] [datetime] NOT NULL CONSTRAINT [DF__NPSCP__CREATEDAT__18F9042F] DEFAULT (getdate()),
[FILLER] [int] NOT NULL CONSTRAINT [DF__NPSCP__FILLER__19ED2868] DEFAULT (1),
[MODIFIER] [int] NOT NULL CONSTRAINT [DF__NPSCP__MODIFIER__1AE14CA1] DEFAULT (1),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__NPSCP__LSTUPDTIM__1BD570DA] DEFAULT (getdate()),
[RAWRECCNT] [int] NOT NULL,
[PDTRECCNT] [int] NOT NULL,
[SndTime] [datetime] NULL,
[SRC] [int] NOT NULL CONSTRAINT [DF__NPSCP__SRC__1CC99513] DEFAULT (1),
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[FRCUPD] [smallint] NOT NULL,
[TYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[STAT] [int] NOT NULL CONSTRAINT [DF__NPSCP__STAT__7A0CCAC0] DEFAULT (1),
[CYCLE] [int] NULL,
[PSCPTYPE] [smallint] NOT NULL CONSTRAINT [DF__NPSCP__PSCPTYPE__5B533976] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPSCP] ADD CONSTRAINT [PK__NPSCP__4707859D] PRIMARY KEY CLUSTERED  ([ID], [SRC]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
