CREATE TABLE [dbo].[INVCHGYRPTX]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[BGDGID] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[DIN1] [money] NOT NULL CONSTRAINT [DF__INVCHGYRPT__DIN1__7D45FCC2] DEFAULT (0),
[DIN2] [money] NOT NULL CONSTRAINT [DF__INVCHGYRPT__DIN2__7E3A20FB] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INVCHGYRPTX] ADD CONSTRAINT [PK__INVCHGYRPTX__7E8CC4B1] PRIMARY KEY CLUSTERED  ([ASETTLENO], [BGDGID], [BWRH], [ASTORE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
