CREATE TABLE [dbo].[PROMFPRCSTORE]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROMFPRCSTORE] ADD CONSTRAINT [PK__PROMFPRCSTORE__3BD137D3] PRIMARY KEY CLUSTERED  ([NUM], [CLS], [STOREGID]) ON [PRIMARY]
GO
