CREATE TABLE [dbo].[NDSPDTL]
(
[SRC] [int] NOT NULL CONSTRAINT [DF__NDSPDTL__SRC__1C88D29A] DEFAULT (1),
[ID] [int] NOT NULL,
[LINE] [int] NOT NULL,
[SALELINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[SALEPRICE] [money] NOT NULL,
[SALEQTY] [money] NOT NULL,
[SALETOTAL] [money] NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NDSPDTL] ADD CONSTRAINT [PK__NDSPDTL__24B26D99] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
