CREATE TABLE [dbo].[GFTPRMRULE]
(
[CODE] [char] (18) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (200) COLLATE Chinese_PRC_CI_AS NULL,
[STAT] [int] NOT NULL CONSTRAINT [DF__GFTPRMRULE__STAT__5B30DBE0] DEFAULT (0),
[BEGINTIME] [datetime] NOT NULL,
[ENDTIME] [datetime] NOT NULL,
[QTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMRULE__QTY__5C250019] DEFAULT (0),
[AMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMRULE__AMT__5D192452] DEFAULT (0),
[NOTE] [text] COLLATE Chinese_PRC_CI_AS NULL,
[TOPIC] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__GFTPRMRUL__TOPIC__5E0D488B] DEFAULT ('-'),
[REPORT] [text] COLLATE Chinese_PRC_CI_AS NULL,
[PASSQTY] [money] NOT NULL CONSTRAINT [DF__GFTPRMRUL__PASSQ__4034638F] DEFAULT (0),
[PASSAMT] [money] NOT NULL CONSTRAINT [DF__GFTPRMRUL__PASSA__412887C8] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GFTPRMRULE] ADD CONSTRAINT [PK__GFTPRMRULE__5A3CB7A7] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
