CREATE TABLE [dbo].[BILLAPDX]
(
[BILL] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__BILLAPDX__FILDAT__0B5E4698] DEFAULT (getdate()),
[DSPMODE] [smallint] NOT NULL CONSTRAINT [DF__BILLAPDX__DSPMOD__0C526AD1] DEFAULT (0),
[DSPDATE] [datetime] NULL,
[OUTCTR] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[OUTCTRPHONE] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[OUTADDR] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[OUTNEARBY] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[INCTR] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[INCTRPHONE] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[INADDR] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[INNEARBY] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[INSTDATE] [datetime] NOT NULL CONSTRAINT [DF__BILLAPDX__INSTDA__0D468F0A] DEFAULT (getdate()),
[DBGDATE] [datetime] NOT NULL CONSTRAINT [DF__BILLAPDX__DBGDAT__0E3AB343] DEFAULT (getdate()),
[FILLER] [int] NOT NULL CONSTRAINT [DF__BILLAPDX__FILLER__0F2ED77C] DEFAULT (1),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[HDBILLNUM] [varchar] (16) COLLATE Chinese_PRC_CI_AS NULL,
[INUNIT] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE2] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SRCNUM] [char] (12) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BILLAPDX] WITH NOCHECK ADD CONSTRAINT [BILLAPDX_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[BILLAPDX] ADD CONSTRAINT [PK__BILLAPDX__1699586C] PRIMARY KEY CLUSTERED  ([BILL], [CLS], [NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
