CREATE TABLE [dbo].[VDROUTADJDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[SETTLENO] [int] NULL,
[DATE] [datetime] NULL,
[GDGID] [int] NULL,
[VENDOR] [int] NULL,
[OLDQTY] [money] NULL,
[OLDTOTAL] [money] NULL,
[QTY] [money] NULL,
[TOTAL] [money] NULL,
[PRNTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VDROUTADJDTL] ADD CONSTRAINT [PK__VDROUTADJDTL__3B60C8C7] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
