CREATE TABLE [dbo].[NSCOSCHEMEDTL]
(
[ID] [int] NOT NULL,
[CODE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[GDQPCSTR] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NSCOSCHEM__GDQPC__35155499] DEFAULT ('1*1'),
[SCORATE] [money] NOT NULL CONSTRAINT [DF__NSCOSCHEM__SCORA__360978D2] DEFAULT (0),
[SRC] [int] NOT NULL CONSTRAINT [DF__NSCOSCHEMED__SRC__36FD9D0B] DEFAULT (1),
[SNDTIME] [datetime] NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NSCOSCHEMEDTL] ADD CONSTRAINT [PK__NSCOSCHEMEDTL__34213060] PRIMARY KEY CLUSTERED  ([SRC], [RCV], [ID], [CODE], [GDGID], [GDQPCSTR]) ON [PRIMARY]
GO
