CREATE TABLE [dbo].[NPRMBANLAN]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[BGDGID] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[BCSTGID] [int] NOT NULL,
[DQ1] [money] NOT NULL CONSTRAINT [DF__NPRMBANLAN__DQ1__52AFD921] DEFAULT (0),
[DQ2] [money] NOT NULL CONSTRAINT [DF__NPRMBANLAN__DQ2__53A3FD5A] DEFAULT (0),
[DQ3] [money] NOT NULL CONSTRAINT [DF__NPRMBANLAN__DQ3__54982193] DEFAULT (0),
[DQ4] [money] NOT NULL CONSTRAINT [DF__NPRMBANLAN__DQ4__558C45CC] DEFAULT (0),
[DP1] [money] NOT NULL CONSTRAINT [DF__NPRMBANLAN__DP1__56806A05] DEFAULT (0),
[DP2] [money] NOT NULL CONSTRAINT [DF__NPRMBANLAN__DP2__57748E3E] DEFAULT (0),
[DP3] [money] NOT NULL CONSTRAINT [DF__NPRMBANLAN__DP3__5868B277] DEFAULT (0),
[DP4] [money] NOT NULL CONSTRAINT [DF__NPRMBANLAN__DP4__595CD6B0] DEFAULT (0),
[DI1] [money] NOT NULL CONSTRAINT [DF__NPRMBANLAN__DI1__5A50FAE9] DEFAULT (0),
[DI2] [money] NOT NULL CONSTRAINT [DF__NPRMBANLAN__DI2__5B451F22] DEFAULT (0),
[DI3] [money] NOT NULL CONSTRAINT [DF__NPRMBANLAN__DI3__5C39435B] DEFAULT (0),
[DI4] [money] NOT NULL CONSTRAINT [DF__NPRMBANLAN__DI4__5D2D6794] DEFAULT (0),
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[RCV] [int] NULL,
[SNDTIME] [datetime] NOT NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPRMBANLAN] ADD CONSTRAINT [PK__NPRMBANLAN__51BBB4E8] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
