CREATE TABLE [dbo].[NPOLYPROMQTYSCHMDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[LOWQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPOLYPROM__LOWQT__68A574F8] DEFAULT (0),
[HIGHQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPOLYPROM__HIGHQ__69999931] DEFAULT (99999999),
[DISCOUNT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPOLYPROM__DISCO__6A8DBD6A] DEFAULT (0),
[FAVAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NPOLYPROM__FAVAM__6B81E1A3] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPOLYPROMQTYSCHMDTL] ADD CONSTRAINT [PK__NPOLYPROMQTYSCHM__6C7605DC] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) ON [PRIMARY]
GO
