CREATE TABLE [dbo].[FASECURITYSTYH]
(
[GID] [int] NOT NULL,
[CODE] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (255) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ENGNAME] [char] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SHORTCHNNAME] [char] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SHORTENGNAME] [char] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__FASECURIT__FILDA__6C2296CF] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__FASECURIT__LSTUP__6D16BB08] DEFAULT (getdate()),
[LASTMODIFYOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [char] (255) COLLATE Chinese_PRC_CI_AS NULL,
[PWDMINLENGTH] [smallint] NOT NULL CONSTRAINT [DF__FASECURIT__PWDMI__6E0ADF41] DEFAULT (0),
[FIRSTLOGMSG] [smallint] NOT NULL CONSTRAINT [DF__FASECURIT__FIRST__6EFF037A] DEFAULT (0),
[PWDERRTIMES] [smallint] NOT NULL CONSTRAINT [DF__FASECURIT__PWDER__6FF327B3] DEFAULT (3),
[PWDNEVERLOSE] [smallint] NOT NULL CONSTRAINT [DF__FASECURIT__PWDNE__70E74BEC] DEFAULT (0),
[PWDEXPIRYDAY] [smallint] NOT NULL CONSTRAINT [DF__FASECURIT__PWDEX__71DB7025] DEFAULT (0),
[PWDEXPIRYPROMPTDAY] [smallint] NOT NULL CONSTRAINT [DF__FASECURIT__PWDEX__72CF945E] DEFAULT (0),
[PWDREUSELMT] [smallint] NOT NULL CONSTRAINT [DF__FASECURIT__PWDRE__73C3B897] DEFAULT (0),
[PWDLEVEL] [smallint] NOT NULL CONSTRAINT [DF__FASECURIT__PWDLE__74B7DCD0] DEFAULT (0),
[PWDSAMEPWDLNAME] [smallint] NOT NULL CONSTRAINT [DF__FASECURIT__PWDSA__75AC0109] DEFAULT (0),
[PWDDUPLIMIT] [smallint] NOT NULL CONSTRAINT [DF__FASECURIT__PWDDU__76A02542] DEFAULT (0),
[PWDDEGREE] [smallint] NOT NULL CONSTRAINT [DF__FASECURIT__PWDDE__7794497B] DEFAULT (0)
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_FASECURITYSTYH_G] ON [dbo].[FASECURITYSTYH] ([GID]) ON [PRIMARY]
GO
