CREATE TABLE [dbo].[GFTPRMBCKDTLDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GROUPID] [int] NULL,
[RCODE] [char] (18) COLLATE Chinese_PRC_CI_AS NULL,
[GFTGID] [int] NOT NULL,
[SRCQTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMBCK__SRCQT__40497228] DEFAULT (0),
[BCKQTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMBCK__BCKQT__413D9661] DEFAULT (0),
[QTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMBCKDT__QTY__4231BA9A] DEFAULT (0),
[AMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMBCKDT__AMT__4325DED3] DEFAULT (0),
[BCKAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMBCK__BCKAM__441A030C] DEFAULT (0),
[GFTPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMBCK__GFTPR__450E2745] DEFAULT (0),
[REALGFTPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMBCK__REALG__46024B7E] DEFAULT (0),
[RULEBCKCNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMBCK__RULEB__46F66FB7] DEFAULT (0),
[MAINLINE] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GFTPRMBCKDTLDTL] ADD CONSTRAINT [PK__GFTPRMBCKDTLDTL__47EA93F0] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
