CREATE TABLE [dbo].[SALEORD]
(
[CLS] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[SENDER] [int] NOT NULL,
[VENDOR] [int] NOT NULL CONSTRAINT [DF__SALEORD__VENDOR__5E5695F7] DEFAULT (1),
[TOTAL] [money] NOT NULL CONSTRAINT [DF__SALEORD__TOTAL__5F4ABA30] DEFAULT (0),
[TAX] [money] NOT NULL CONSTRAINT [DF__SALEORD__TAX__603EDE69] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__SALEORD__FILDATE__613302A2] DEFAULT (getdate()),
[PAYDATE] [datetime] NULL,
[PREPAY] [money] NOT NULL CONSTRAINT [DF__SALEORD__PREPAY__622726DB] DEFAULT (0),
[FILLER] [int] NOT NULL CONSTRAINT [DF__SALEORD__FILLER__631B4B14] DEFAULT (1),
[CHECKER] [int] NOT NULL CONSTRAINT [DF__SALEORD__CHECKER__640F6F4D] DEFAULT (1),
[PSR] [int] NOT NULL CONSTRAINT [DF__SALEORD__PSR__65039386] DEFAULT (1),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__SALEORD__STAT__65F7B7BF] DEFAULT (0),
[MODNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[WRH] [int] NOT NULL CONSTRAINT [DF__SALEORD__WRH__66EBDBF8] DEFAULT (1),
[RECCNT] [int] NOT NULL CONSTRAINT [DF__SALEORD__RECCNT__67E00031] DEFAULT (0),
[SRC] [int] NOT NULL,
[SRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[RECEIVER] [int] NOT NULL,
[PRNTIME] [datetime] NULL,
[FINISHED] [smallint] NOT NULL CONSTRAINT [DF__SALEORD__FINISHE__68D4246A] DEFAULT (0),
[ALCCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[EXPDATE] [datetime] NULL,
[PRECHECKER] [int] NULL,
[PRECHKDATE] [datetime] NULL,
[DLVBDATE] [datetime] NULL,
[DLVEDATE] [datetime] NULL,
[IMPFLAG] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[DLVADDR] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SALEORD] ADD CONSTRAINT [SALEORD_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[SALEORD] ADD CONSTRAINT [PK__SALEORD__5D6271BE] PRIMARY KEY CLUSTERED  ([CLS], [NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [EXPDATE] ON [dbo].[SALEORD] ([EXPDATE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FILDATE] ON [dbo].[SALEORD] ([FILDATE]) ON [PRIMARY]
GO
