CREATE TABLE [dbo].[PAYDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SETTLENO] [int] NULL,
[GDGID] [int] NULL,
[NPQTY] [money] NULL,
[NPTOTAL] [money] NULL,
[NPSTOTAL] [money] NULL,
[QTY] [money] NULL,
[TOTAL] [money] NULL,
[STOTAL] [money] NULL,
[INPRC] [money] NULL,
[RTLPRC] [money] NULL,
[BNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[FROMCLS] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[FROMNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[FROMLINE] [smallint] NULL,
[tax] [money] NULL,
[FromPayDate] [datetime] NULL,
[FROMTOTAL] [money] NOT NULL CONSTRAINT [DF__PAYDTL__FROMTOTA__51E69D71] DEFAULT (0),
[FROMVDRNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAYDTL] ADD CONSTRAINT [PK__PAYDTL__6774552F] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PAYDTL_INDEXS] ON [dbo].[PAYDTL] ([FROMNUM], [NUM], [FROMCLS]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [paydtl_gdgid] ON [dbo].[PAYDTL] ([GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
