CREATE TABLE [dbo].[MEMPPLAN]
(
[YEAR] [decimal] (4, 0) NOT NULL,
[MONTH] [decimal] (2, 0) NOT NULL,
[EMP] [int] NOT NULL,
[TOTAL] [money] NOT NULL,
[GP] [money] NOT NULL,
[GPRATE] [money] NOT NULL,
[DEPTG] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__MEMPPLAN__DEPTG__04410BC7] DEFAULT ('-'),
[STORE] [int] NOT NULL CONSTRAINT [DF__MEMPPLAN__STORE__62CB0963] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MEMPPLAN] ADD CONSTRAINT [PK__MEMPPLAN__06295439] PRIMARY KEY CLUSTERED  ([YEAR], [MONTH], [EMP], [DEPTG]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[Curdflt]', N'[dbo].[MEMPPLAN].[GP]'
GO
EXEC sp_bindefault N'[dbo].[Curdflt]', N'[dbo].[MEMPPLAN].[GPRATE]'
GO
