CREATE TABLE [dbo].[ICBUY2]
(
[STORE] [int] NOT NULL,
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[SETTLENO] [int] NOT NULL,
[GID] [int] NOT NULL,
[QTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__ICBUY2__QTY__3A98586E] DEFAULT (0),
[INPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__ICBUY2__INPRC__3B8C7CA7] DEFAULT (0),
[PRICE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__ICBUY2__PRICE__3C80A0E0] DEFAULT (0),
[REALAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__ICBUY2__REALAMT__3D74C519] DEFAULT (0),
[FAVAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__ICBUY2__FAVAMT__3E68E952] DEFAULT (0),
[PRMTAG] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[ASSISTANT] [int] NULL,
[WRH] [int] NULL CONSTRAINT [DF__ICBUY2__WRH__3F5D0D8B] DEFAULT (1),
[INVNO] [char] (10) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ICBUY2] ADD CONSTRAINT [PK__ICBUY2__39A43435] PRIMARY KEY CLUSTERED  ([STORE], [POSNO], [FLOWNO], [ITEMNO]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
