CREATE TABLE [dbo].[NBCKNOTIFY]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[RECCNT] [int] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NBCKNOTIF__FILDA__1D3DCB08] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHKDATE] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[SNDDATE] [datetime] NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__NBCKNOTIFY__STAT__1E31EF41] DEFAULT (0),
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[NTYPE] [smallint] NOT NULL,
[NSTAT] [int] NOT NULL,
[NNOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__NBCKNOTIF__LSTUP__1F26137A] DEFAULT (getdate()),
[EXPDATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NBCKNOTIFY] ADD CONSTRAINT [PK__NBCKNOTIFY__1C49A6CF] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
