CREATE TABLE [dbo].[PAYCHANNLDTL]
(
[CNAME] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ENAME] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PAYCODE] [smallint] NOT NULL,
[ISVISIBLE] [smallint] NOT NULL CONSTRAINT [DF__PAYCHANNL__ISVIS__48900D26] DEFAULT (0),
[SRCPLAT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PAYCHANNL__SRCPL__09BEB205] DEFAULT ('HDPAY')
) ON [PRIMARY]
GO
