CREATE TABLE [dbo].[IMPTASKCOLINFO]
(
[TBNAME] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FIELDNAME] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FIELDLABEL] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ISIMPORT] [smallint] NOT NULL CONSTRAINT [DF__IMPTASKCO__ISIMP__6A7B10D6] DEFAULT (0)
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [UK_IMPTASKCOLINFO_NAME] ON [dbo].[IMPTASKCOLINFO] ([TBNAME], [FIELDNAME]) ON [PRIMARY]
GO
