CREATE TABLE [dbo].[NPROMMONEY]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[NO] [smallint] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PRMNO] [int] NOT NULL,
[TOTAL] [decimal] (24, 4) NOT NULL,
[PRMTOTAL] [decimal] (24, 4) NOT NULL,
[IFGFT] [int] NOT NULL,
[GFTQTY] [decimal] (24, 4) NOT NULL,
[PTOTAL] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPROMMONE__PTOTA__79ECCF2F] DEFAULT (0),
[ISFULL] [int] NOT NULL CONSTRAINT [DF__NPROMMONE__ISFUL__7AE0F368] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPROMMONEY] ADD CONSTRAINT [PK__NPROMMONEY__7BD517A1] PRIMARY KEY CLUSTERED  ([SRC], [ID], [NO], [NUM], [CLS], [PRMNO]) ON [PRIMARY]
GO
