CREATE TABLE [dbo].[SCODRPT]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[BCARRIER] [int] NOT NULL,
[BCARD] [int] NOT NULL,
[DT1] [money] NOT NULL CONSTRAINT [DF__SCODRPT__DT1__49073EAD] DEFAULT (0),
[DT2] [money] NOT NULL CONSTRAINT [DF__SCODRPT__DT2__49FB62E6] DEFAULT (0),
[DS1] [money] NOT NULL CONSTRAINT [DF__SCODRPT__DS1__4AEF871F] DEFAULT (0),
[DS2] [money] NOT NULL CONSTRAINT [DF__SCODRPT__DS2__4BE3AB58] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SCODRPT] ADD CONSTRAINT [PK__SCODRPT__19FFD4FC] PRIMARY KEY CLUSTERED  ([ADATE], [BCARRIER], [BCARD], [ASTORE], [ASETTLENO]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
