CREATE TABLE [dbo].[ICRTLBCK]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[CURRENCY] [smallint] NOT NULL CONSTRAINT [DF__ICRTLBCK__CURREN__30A6708E] DEFAULT (0),
[DEPOSITCARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BCKAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__ICRTLBCK__BCKAMT__319A94C7] DEFAULT (0),
[BCKTIME] [datetime] NOT NULL CONSTRAINT [DF__ICRTLBCK__BCKTIM__328EB900] DEFAULT (getdate()),
[OPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STORE] [int] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ICRTLBCK] ADD CONSTRAINT [PK__ICRTLBCK__3382DD39] PRIMARY KEY CLUSTERED  ([NUM], [ITEMNO]) ON [PRIMARY]
GO
