CREATE TABLE [dbo].[PROPAPDX]
(
[GID] [int] NOT NULL IDENTITY(1000001, 1),
[CLS] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CODE] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROPAPDX] ADD CONSTRAINT [PK__PROPAPDX__224EFAED] PRIMARY KEY CLUSTERED  ([GID]) ON [PRIMARY]
GO
