CREATE TABLE [dbo].[ONLINESALEORDCURRENCY]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[CURRENCY] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[AMOUNT] [decimal] (24, 2) NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ONLINESALEORDCURRENCY] ADD CONSTRAINT [PK__OnlineSaleOrdCur__70F3043B] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
