CREATE TABLE [dbo].[BUY1]
(
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NULL,
[FILDATE] [datetime] NULL CONSTRAINT [DF__BUY1__FILDATE__0678CA93] DEFAULT (getdate()),
[CASHIER] [int] NULL CONSTRAINT [DF__BUY1__CASHIER__076CEECC] DEFAULT (1),
[WRH] [int] NULL CONSTRAINT [DF__BUY1__WRH__08611305] DEFAULT (1),
[ASSISTANT] [int] NULL,
[TOTAL] [money] NULL CONSTRAINT [DF__BUY1__TOTAL__0955373E] DEFAULT (0),
[REALAMT] [money] NULL CONSTRAINT [DF__BUY1__REALAMT__0A495B77] DEFAULT (0),
[PREVAMT] [money] NULL CONSTRAINT [DF__BUY1__PREVAMT__0B3D7FB0] DEFAULT (0),
[GUEST] [int] NULL,
[RECCNT] [int] NULL CONSTRAINT [DF__BUY1__RECCNT__0C31A3E9] DEFAULT (0),
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[TAG] [smallint] NULL CONSTRAINT [DF__BUY1__TAG__0D25C822] DEFAULT (0),
[InvNo] [char] (13) COLLATE Chinese_PRC_CI_AS NULL,
[SCORE] [money] NULL,
[CARDCODE] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[DEALER] [int] NULL,
[FLAG] [int] NOT NULL CONSTRAINT [DF__BUY1__FLAG__6A2A9D5B] DEFAULT (0),
[SCOREINFO] [char] (100) COLLATE Chinese_PRC_CI_AS NULL,
[PROCDATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BUY1] ADD CONSTRAINT [PK__BUY1__1C5231C2] PRIMARY KEY CLUSTERED  ([POSNO], [FLOWNO]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FILDATE] ON [dbo].[BUY1] ([FILDATE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_BUY1_PROCDATE] ON [dbo].[BUY1] ([PROCDATE]) ON [PRIMARY]
GO
