CREATE TABLE [dbo].[RCPCURDTL]
(
[NUM] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CURRENCY] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[AMOUNT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__RCPCURDTL__AMOUN__78287B01] DEFAULT (0),
[CARDCODE] [varchar] (128) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RCPCURDTL] ADD CONSTRAINT [PK__RCPCURDTL__791C9F3A] PRIMARY KEY CLUSTERED  ([NUM], [CURRENCY]) ON [PRIMARY]
GO
