CREATE TABLE [dbo].[PS3SCONOTSCOREBRAND]
(
[BRAND] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3SCONOTSCOREBRAND] ADD CONSTRAINT [PK__PS3SCONOTSCOREBR__108F720E] PRIMARY KEY CLUSTERED  ([BRAND]) ON [PRIMARY]
GO
