CREATE TABLE [dbo].[VDRPAY]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__VDRPAY__FILDATE__77FD9278] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ACNTER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[STAT] [smallint] NOT NULL,
[PRNTIME] [datetime] NULL,
[PAYTOTAL] [decimal] (24, 2) NOT NULL,
[MODNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[VGID] [int] NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__VDRPAY__LSTUPDTI__78F1B6B1] DEFAULT (getdate()),
[SETTLEACCOUNTNO] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[DEPT] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[ABOLISHRESON] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[STSTORE] [int] NULL,
[SNDTIME] [datetime] NULL,
[SRC] [int] NULL,
[CLIPAYSTAT] [smallint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VDRPAY] ADD CONSTRAINT [PK__VDRPAY__1BF637C2] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
