CREATE TABLE [dbo].[CTCNTR]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VERSION] [smallint] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__CTCNTR__STAT__2C0CA3FA] DEFAULT (0),
[VENDOR] [int] NOT NULL,
[SIGNDATE] [datetime] NULL,
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[REALENDDATE] [datetime] NULL,
[VDRSIGNER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[DEPT] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SIGNER] [int] NOT NULL CONSTRAINT [DF__CTCNTR__SIGNER__2D00C833] DEFAULT (1),
[CNTRNO] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[FILETEXT] [text] COLLATE Chinese_PRC_CI_AS NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__CTCNTR__LSTUPDTI__2DF4EC6C] DEFAULT (getdate()),
[PRNTIME] [datetime] NULL,
[TAG] [int] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[AGENTMODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SALESQ] [money] NULL,
[SALECLS] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[GUARDAMT] [money] NULL,
[UPGUARDRATE] [money] NULL,
[GUARDRATE] [money] NULL,
[RENT] [money] NULL,
[PAYBILLCLS] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[PAYBILLTAXRATE] [money] NULL,
[CUSTOMDEF] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[EXSTORE] [int] NULL,
[CALCCENTER] [int] NULL,
[SNDTIME] [datetime] NULL,
[SORT] [char] (13) COLLATE Chinese_PRC_CI_AS NULL,
[ACTSQ] [decimal] (24, 2) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CTCNTR] ADD CONSTRAINT [PK__CTCNTR__2EE910A5] PRIMARY KEY CLUSTERED  ([NUM], [VERSION]) ON [PRIMARY]
GO
