CREATE TABLE [dbo].[ONLINESALEBCKORD]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__ONLINESALE__STAT__310D8950] DEFAULT (0),
[STOREGID] [int] NOT NULL,
[MBRGID] [int] NOT NULL,
[MBRCARDNO] [varchar] (60) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__ONLINESAL__FILDA__3201AD89] DEFAULT (getdate()),
[FILLER] [int] NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__ONLINESAL__LSTUP__32F5D1C2] DEFAULT (getdate()),
[LSTUPDOPER] [int] NOT NULL,
[CHKDATE] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[PRNTIME] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[BILLFROM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[AMOUNT] [decimal] (24, 2) NOT NULL,
[ORDNUM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[SRCNUM] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[ORIORDNUM] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CLTNAME] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[CLTPHONE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[DLVERNAME] [varchar] (60) COLLATE Chinese_PRC_CI_AS NULL,
[DLVERPHONE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[ORDDATE] [datetime] NULL,
[SALEDATE] [datetime] NULL,
[RTNNAME] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[RTNPHONE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[RTNADDRESS] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ONLINESALEBCKORD] ADD CONSTRAINT [PK__ONLINESALEBCKORD__33E9F5FB] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
