CREATE TABLE [dbo].[PS3SPECSCOPESCORESPECDIS]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[CARDTYPECODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARDTYPENAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DISCOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3SPECSC__DISCO__7AC4F08A] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3SPECSCOPESCORESPECDIS] ADD CONSTRAINT [PK__PS3SPECSCOPESCOR__7BB914C3] PRIMARY KEY CLUSTERED  ([NUM], [CLS], [LINE]) ON [PRIMARY]
GO
