CREATE TABLE [dbo].[BLTALLYORD]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[POSNO] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__BLTALLYOR__FILDA__3D6D057D] DEFAULT (getdate()),
[OPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDCODE] [varchar] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[QTY] [decimal] (24, 4) NULL,
[PROCTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BLTALLYORD] ADD CONSTRAINT [PK__BLTALLYORD__3E6129B6] PRIMARY KEY CLUSTERED  ([NUM], [CLS], [POSNO], [LINE]) ON [PRIMARY]
GO
