CREATE TABLE [dbo].[INVOICELOG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [int] NOT NULL,
[ACT] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MODIFIER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INVOICELOG] ADD CONSTRAINT [PK__INVOICELOG__4DF93E58] PRIMARY KEY CLUSTERED  ([NUM], [STAT], [ACT], [TIME]) ON [PRIMARY]
GO
