CREATE TABLE [dbo].[CNTRACNTINFOCFG]
(
[NO] [int] NOT NULL,
[SUBJECT] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLAG] [int] NOT NULL CONSTRAINT [DF__CNTRACNTIN__FLAG__383D70B5] DEFAULT (1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CNTRACNTINFOCFG] ADD CONSTRAINT [PK__CNTRACNTINFOCFG__393194EE] PRIMARY KEY CLUSTERED  ([NO]) ON [PRIMARY]
GO
