CREATE TABLE [dbo].[CRMDATAEXCHANGEORG]
(
[FORGCODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FORGCLS] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FDATABASELINK] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[FACTIVE] [smallint] NOT NULL CONSTRAINT [DF__CRMDATAEX__FACTI__160AB647] DEFAULT (0),
[FPAUSETIME] [datetime] NULL,
[FEXGTYPE] [smallint] NOT NULL CONSTRAINT [DF__CRMDATAEX__FEXGT__16FEDA80] DEFAULT (0),
[FDBMS] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[FSERVER] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[FDATABASE] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[FUSERNAME] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[FPASSWORD] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[FENCRYPT] [smallint] NOT NULL CONSTRAINT [DF__CRMDATAEX__FENCR__17F2FEB9] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMDATAEXCHANGEORG] ADD CONSTRAINT [PK__CRMDATAEXCHANGEO__18E722F2] PRIMARY KEY CLUSTERED  ([FORGCODE]) ON [PRIMARY]
GO
