CREATE TABLE [dbo].[LEAGUESTOREALCACCOUNT]
(
[STOREGID] [int] NOT NULL,
[ACCOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__LEAGUESTO__ACCOU__5D64D3C3] DEFAULT (0),
[TOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__LEAGUESTO__TOTAL__5E58F7FC] DEFAULT (0),
[LSTUPDTIME] [datetime] NOT NULL,
[LSTMODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SHOULDPAY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__LEAGUESTO__SHOUL__09393460] DEFAULT (0),
[PAY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__LEAGUESTORE__PAY__0A2D5899] DEFAULT (0),
[USEACCOUNT] [smallint] NOT NULL CONSTRAINT [DF__LEAGUESTO__USEAC__1FD280F5] DEFAULT (1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LEAGUESTOREALCACCOUNT] ADD CONSTRAINT [PK__LEAGUESTOREALCAC__5F4D1C35] PRIMARY KEY CLUSTERED  ([STOREGID]) ON [PRIMARY]
GO
