CREATE TABLE [dbo].[RFBILLDTL]
(
[RFNUM] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [int] NOT NULL,
[BARCODE] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CODETYPE] [int] NOT NULL CONSTRAINT [DF__RFBILLDTL__CODET__3F4B2C4E] DEFAULT (0),
[GID] [int] NOT NULL,
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__RFBILLDTL__QTY__403F5087] DEFAULT (0),
[PRICE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__RFBILLDTL__PRICE__413374C0] DEFAULT (0),
[AMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__RFBILLDTL__AMOUN__422798F9] DEFAULT (0),
[MBRPRICE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__RFBILLDTL__MBRPR__431BBD32] DEFAULT (0),
[MBRAMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__RFBILLDTL__MBRAM__440FE16B] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RFBILLDTL] ADD CONSTRAINT [PK__RFBILLDTL__450405A4] PRIMARY KEY CLUSTERED  ([RFNUM], [ITEMNO]) ON [PRIMARY]
GO
