CREATE TABLE [dbo].[SUBWRHINV]
(
[WRH] [int] NOT NULL,
[SUBWRH] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[QTY] [money] NULL CONSTRAINT [DF__SUBWRHINV__QTY__32F736A6] DEFAULT (0),
[TOTAL] [money] NULL CONSTRAINT [DF__SUBWRHINV__TOTAL__33EB5ADF] DEFAULT (0),
[LSTINPRC] [money] NULL,
[DSPQTY] [money] NULL CONSTRAINT [DF__subwrhinv__DSPQT__1C1EBE46] DEFAULT (0),
[BCKQTY] [money] NULL CONSTRAINT [DF__subwrhinv__BCKQT__1D12E27F] DEFAULT (0),
[COST] [money] NULL CONSTRAINT [DF__SUBWRHINV__COST__1493766E] DEFAULT (0),
[CODE] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[RSVALCQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__SUBWRHINV__RSVAL__26FEA171] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SUBWRHINV] ADD CONSTRAINT [PK_SUBWRHINV] PRIMARY KEY NONCLUSTERED  ([GDGID], [SUBWRH], [WRH]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_SUBWRH] ON [dbo].[SUBWRHINV] ([SUBWRH]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_WRH] ON [dbo].[SUBWRHINV] ([WRH]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [SUBWRHINV_CODE] ON [dbo].[SUBWRHINV] ([WRH], [CODE], [GDGID]) ON [PRIMARY]
GO
