CREATE TABLE [dbo].[BCKNOTIFYDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[note] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BCKNOTIFYDTL] ADD CONSTRAINT [PK__BCKNOTIFYDTL__0FE3CFEA] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [BCK] ON [dbo].[BCKNOTIFYDTL] ([NUM], [GDGID]) ON [PRIMARY]
GO
