CREATE TABLE [dbo].[NPOLYPRCPRM]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL,
[RECCNT] [int] NOT NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL,
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[TOPIC] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PSETTLENO] [int] NULL,
[OCRTYPE] [smallint] NOT NULL,
[OCRTIME] [datetime] NULL,
[EXGDRECCNT] [int] NOT NULL CONSTRAINT [DF__NPOLYPRCP__EXGDR__4C7D6C3F] DEFAULT (0),
[POLYPRIOR] [smallint] NOT NULL CONSTRAINT [DF__NPOLYPRCP__POLYP__5AEB8727] DEFAULT (0),
[PRIORITY] [int] NOT NULL CONSTRAINT [DF__NPOLYPRCP__PRIOR__7910E6EB] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPOLYPRCPRM] ADD CONSTRAINT [PK__NPOLYPRCPRM__4D719078] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
