CREATE TABLE [dbo].[CRMDATAEXGSENDLOG]
(
[FSENDTIME] [datetime] NOT NULL,
[FCLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FUUID] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[FSRCUUID] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[FACTION] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FNOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[FSRCORG] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FDESTORG] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_DATAEXGSENDLOG_FCLS] ON [dbo].[CRMDATAEXGSENDLOG] ([FDESTORG], [FCLS], [FUUID], [FACTION], [FSENDTIME]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_DATAEXGSENDLOG] ON [dbo].[CRMDATAEXGSENDLOG] ([FSENDTIME], [FACTION]) ON [PRIMARY]
GO
