CREATE TABLE [dbo].[CHECK_XXX]
(
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[INPUTER] [int] NULL CONSTRAINT [DF__CHECK_XXX__INPUT__24092D7A] DEFAULT (1),
[OPERATOR] [int] NULL CONSTRAINT [DF__CHECK_XXX__OPERA__24FD51B3] DEFAULT (1),
[FILDATE] [datetime] NULL CONSTRAINT [DF__CHECK_XXX__FILDA__25F175EC] DEFAULT (getdate()),
[WRH] [int] NULL,
[GDGID] [int] NULL,
[QTY] [money] NULL CONSTRAINT [DF__CHECK_XXX__QTY__26E59A25] DEFAULT (0),
[INPRC] [money] NULL CONSTRAINT [DF__CHECK_XXX__INPRC__27D9BE5E] DEFAULT (0),
[PRICE] [money] NULL CONSTRAINT [DF__CHECK_XXX__PRICE__28CDE297] DEFAULT (0),
[AMOUNT] [money] NULL CONSTRAINT [DF__CHECK_XXX__AMOUN__29C206D0] DEFAULT (0),
[TAG] [smallint] NULL CONSTRAINT [DF__CHECK_XXX__TAG__2AB62B09] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CHECK_XXX] ADD CONSTRAINT [PK__CHECK_XXX__24E777C3] PRIMARY KEY CLUSTERED  ([POSNO], [FLOWNO], [ITEMNO]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
