CREATE TABLE [dbo].[CNTR_GENVDRLSEDEPT]
(
[CNTRNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VERSION] [smallint] NOT NULL,
[CHGCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VDRGID] [int] NOT NULL,
[DEPT] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PAYRATE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CNTR_GENV__PAYRA__2B3E0AB3] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CNTR_GENVDRLSEDEPT] ADD CONSTRAINT [PK__CNTR_GENVDRLSEDE__2C322EEC] PRIMARY KEY CLUSTERED  ([CNTRNUM], [VERSION], [CHGCODE], [VDRGID], [DEPT]) ON [PRIMARY]
GO
