CREATE TABLE [dbo].[NRTLBCKDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SETTLENO] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[CASES] [decimal] (24, 4) NULL,
[QTY] [decimal] (24, 4) NOT NULL,
[PRICE] [decimal] (24, 4) NOT NULL,
[DISCOUNT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NRTLBCKDT__DISCO__6FF8854A] DEFAULT (100),
[AMOUNT] [decimal] (24, 4) NOT NULL,
[RTLPRC] [decimal] (24, 4) NOT NULL,
[INPRC] [decimal] (24, 4) NOT NULL,
[SUBWRH] [int] NULL,
[ALCPRC] [decimal] (24, 4) NULL,
[DSPSUBWRH] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[TAX] [decimal] (24, 4) NOT NULL,
[LXGDNAME] [char] (50) COLLATE Chinese_PRC_CI_AS NULL,
[LXGDSPEC] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[LXGDMUNIT] [char] (6) COLLATE Chinese_PRC_CI_AS NULL,
[LXGDTM] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[COST] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NRTLBCKDTL__COST__70ECA983] DEFAULT (0),
[COSTPRC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NRTLBCKDT__COSTP__71E0CDBC] DEFAULT (0),
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[REDCARDCOST] [decimal] (24, 4) NULL,
[BLUECARDCOST] [decimal] (24, 4) NULL,
[VOUAMT] [decimal] (24, 4) NULL,
[GFTFLAG] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NRTLBCKDTL] ADD CONSTRAINT [PK__NRTLBCKDTL__72D4F1F5] PRIMARY KEY CLUSTERED  ([ID], [LINE]) ON [PRIMARY]
GO
