CREATE TABLE [dbo].[VDRXLATE]
(
[NGID] [int] NOT NULL,
[LGID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VDRXLATE] ADD CONSTRAINT [PK__VDRXLATE__3C54ED00] PRIMARY KEY CLUSTERED  ([NGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
