CREATE TABLE [dbo].[CTCNTRBRANDSTATUS]
(
[GID] [smallint] NOT NULL,
[NAME] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CTCNTRBRANDSTATUS] ADD CONSTRAINT [PK__CTCNTRBRANDSTATU__3D6545E1] PRIMARY KEY CLUSTERED  ([GID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IDX_CTCNTRBRANDSTATUS_NAME] ON [dbo].[CTCNTRBRANDSTATUS] ([NAME]) ON [PRIMARY]
GO
