CREATE TABLE [dbo].[LS]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NULL,
[WRH] [int] NULL,
[FILDATE] [datetime] NULL CONSTRAINT [DF__LS__FILDATE__07D70320] DEFAULT (getdate()),
[FILLER] [int] NULL,
[CHECKER] [int] NULL,
[STAT] [smallint] NULL CONSTRAINT [DF__LS__STAT__08CB2759] DEFAULT (0),
[MODNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[AMTLS] [money] NULL CONSTRAINT [DF__LS__AMTLS__09BF4B92] DEFAULT (0),
[RECCNT] [int] NULL CONSTRAINT [DF__LS__RECCNT__0AB36FCB] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[PRNTIME] [datetime] NULL,
[CAUSE] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__ls__CAUSE__5BAF3376] DEFAULT ('不明'),
[FSOURSE] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[FSOURSENUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LS] WITH NOCHECK ADD CONSTRAINT [LS_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[LS] ADD CONSTRAINT [PK__LS__08162EEB] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FILDATE] ON [dbo].[LS] ([FILDATE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
