CREATE TABLE [dbo].[NSTKOUT]
(
[ID] [int] NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SRCORDNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[CLIENT] [int] NULL CONSTRAINT [DF__NSTKOUT__CLIENT__785FB566] DEFAULT (1),
[BILLTO] [int] NULL CONSTRAINT [DF__NSTKOUT__BILLTO__7953D99F] DEFAULT (1),
[OCRDATE] [datetime] NULL,
[TOTAL] [money] NULL,
[TAX] [money] NULL,
[FILDATE] [datetime] NULL,
[PAYDATE] [datetime] NULL,
[CHECKER] [int] NULL CONSTRAINT [DF__NSTKOUT__CHECKER__7A47FDD8] DEFAULT (1),
[STAT] [smallint] NULL CONSTRAINT [DF__NSTKOUT__STAT__7B3C2211] DEFAULT (0),
[MODNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NULL,
[NSTAT] [smallint] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[RCV] [int] NULL,
[SNDTIME] [datetime] NULL,
[RCVTIME] [datetime] NULL,
[FRCCHK] [smallint] NULL,
[TYPE] [smallint] NULL,
[OTHERSIDENUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NSTKOUT] ADD CONSTRAINT [PK__NSTKOUT__4EA8A765] PRIMARY KEY CLUSTERED  ([SRC], [ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NSTKOUT_TYPE] ON [dbo].[NSTKOUT] ([TYPE]) ON [PRIMARY]
GO
