CREATE TABLE [dbo].[NCNTRPREPAY]
(
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VENDOR] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__NCNTRPREPA__STAT__66D0A471] DEFAULT (0),
[PAYER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[VDRRCVER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[OCRDATE] [datetime] NOT NULL,
[NOTE] [char] (255) COLLATE Chinese_PRC_CI_AS NULL,
[DEPT] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[PSR] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCNTRPREP__TOTAL__67C4C8AA] DEFAULT (0),
[TOTALOFF] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCNTRPREP__TOTAL__68B8ECE3] DEFAULT (0),
[CHKFLAG] [smallint] NOT NULL CONSTRAINT [DF__NCNTRPREP__CHKFL__69AD111C] DEFAULT (0),
[PAYFLAG] [smallint] NOT NULL CONSTRAINT [DF__NCNTRPREP__PAYFL__6AA13555] DEFAULT (1),
[ABOLISHRESON] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SETTLEACCOUNTNO] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[CLECENT] [int] NULL,
[SNDTIME] [datetime] NULL,
[SRC] [int] NOT NULL CONSTRAINT [DF__NCNTRPREPAY__SRC__6B95598E] DEFAULT (0),
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[RCV] [int] NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL,
[CFLAG] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCNTRPREPAY] ADD CONSTRAINT [PK__NCNTRPREPAY__6C897DC7] PRIMARY KEY CLUSTERED  ([ID], [SRC]) ON [PRIMARY]
GO
