CREATE TABLE [dbo].[CRMMBRCONTACT]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MBRGID] [int] NOT NULL,
[PERSON] [int] NOT NULL,
[ATIME] [datetime] NULL,
[WAYS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[TITLE] [char] (50) COLLATE Chinese_PRC_CI_AS NULL,
[CONTENT] [text] COLLATE Chinese_PRC_CI_AS NULL,
[FILLER] [char] (50) COLLATE Chinese_PRC_CI_AS NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__CRMMBRCON__FILDA__12B6E64B] DEFAULT (getdate()),
[STAT] [int] NOT NULL CONSTRAINT [DF__CRMMBRCONT__STAT__13AB0A84] DEFAULT (0),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__CRMMBRCON__LSTUP__149F2EBD] DEFAULT (getdate()),
[PRNTIME] [datetime] NULL,
[SETTLENO] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMMBRCONTACT] ADD CONSTRAINT [PK__CRMMBRCONTACT__159352F6] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
