CREATE TABLE [dbo].[STOREOUTDRPT]
(
[STORE] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[DEPTCODE1] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[DEPTNAME1] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[DEPTCODE2] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DEPTNAME2] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[ATYPE] [varchar] (1) COLLATE Chinese_PRC_CI_AS NOT NULL,
[QTY] [money] NULL,
[TOTAL] [money] NULL,
[ML] [money] NULL,
[FAVAMT] [money] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STOREOUTDRPT] ADD CONSTRAINT [STORE_PK] PRIMARY KEY CLUSTERED  ([STORE], [ADATE], [DEPTCODE2], [ATYPE]) ON [PRIMARY]
GO
