CREATE TABLE [dbo].[NCTCNTRBRAND]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VERSION] [smallint] NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[CODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TYPE] [smallint] NOT NULL,
[STATUS] [smallint] NOT NULL,
[BEGINDATE] [datetime] NULL,
[ENDDATE] [datetime] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCTCNTRBRAND] ADD CONSTRAINT [PK__NCTCNTRBRAND__074860FB] PRIMARY KEY CLUSTERED  ([SRC], [ID], [ITEMNO]) ON [PRIMARY]
GO
