CREATE TABLE [dbo].[PS3REDBLUECARDSTOREDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3REDBLUECARDSTOREDTL] ADD CONSTRAINT [PK__PS3REDBLUECARDST__0BCC539F] PRIMARY KEY CLUSTERED  ([NUM], [STOREGID]) ON [PRIMARY]
GO
