CREATE TABLE [dbo].[VDRORDSET]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[VDRGID] [int] NOT NULL,
[ORDUNIT] [char] (4) COLLATE Chinese_PRC_CI_AS NULL,
[ORDINDEX] [char] (2) COLLATE Chinese_PRC_CI_AS NULL,
[DELAYDAY] [int] NULL,
[WMSGID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VDRORDSET] ADD CONSTRAINT [PK__VDRORDSET__5FC21D81] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
