CREATE TABLE [dbo].[SVI]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL,
[FILLER] [int] NOT NULL,
[CHECKER] [int] NOT NULL,
[WRH] [int] NOT NULL,
[BILLTO] [int] NOT NULL,
[EPayDate] [datetime] NOT NULL,
[AMT] [money] NOT NULL,
[SAMT] [money] NOT NULL,
[STAT] [smallint] NOT NULL,
[MODNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[PRNTIME] [datetime] NULL,
[BPAYDATE] [datetime] NULL,
[CLS] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__SVI__CLS__00ABADFB] DEFAULT ('代销'),
[PSR] [int] NOT NULL CONSTRAINT [DF__SVI__PSR__64F971E5] DEFAULT (1),
[PAYTOTAL] [money] NOT NULL CONSTRAINT [DF__SVI__PAYTOTAL__65ED961E] DEFAULT (0),
[TAXRATELMT] [money] NULL,
[DEPT] [varchar] (13) COLLATE Chinese_PRC_CI_AS NULL,
[CHKTAG] [smallint] NOT NULL CONSTRAINT [DF__SVI__CHKTAG__7D528068] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SVI] ADD CONSTRAINT [SVI_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[SVI] ADD CONSTRAINT [PK__SVI__019FD234] PRIMARY KEY CLUSTERED  ([CLS], [NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FILDATE] ON [dbo].[SVI] ([FILDATE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
