CREATE TABLE [dbo].[CRMSTAMPSCORULE]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__CRMSTAMPSC__STAT__31F45E8C] DEFAULT (0),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__CRMSTAMPS__FILDA__32E882C5] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[CHKDATE] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[ABORTDATE] [datetime] NULL,
[ABORTER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__CRMSTAMPS__LSTUP__33DCA6FE] DEFAULT (getdate()),
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMSTAMPS__LSTUP__34D0CB37] DEFAULT ('未知[-]'),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SETTLENO] [int] NOT NULL CONSTRAINT [DF__CRMSTAMPS__SETTL__35C4EF70] DEFAULT (0),
[RECCNT] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMSTAMPSCORULE] ADD CONSTRAINT [PK__CRMSTAMPSCORULE__36B913A9] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
