CREATE TABLE [dbo].[INVYRPTX]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[BGDGID] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[CIN] [money] NOT NULL CONSTRAINT [DF__INVYRPTX__CIN__6FEC01A4] DEFAULT (0),
[FIN] [money] NOT NULL CONSTRAINT [DF__INVYRPTX__FIN__70E025DD] DEFAULT (0),
[FTAXRATE] [money] NOT NULL CONSTRAINT [DF__INVYRPTX__FTAXRA__71D44A16] DEFAULT (17),
[FSALETAX] [money] NOT NULL CONSTRAINT [DF__INVYRPTX__FSALET__72C86E4F] DEFAULT (17)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INVYRPTX] ADD CONSTRAINT [PK__INVYRPTX__04459E07] PRIMARY KEY CLUSTERED  ([ASETTLENO], [BGDGID], [BWRH], [ASTORE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
