CREATE TABLE [dbo].[STOREWEATHER]
(
[ADATE] [datetime] NOT NULL,
[SRC] [int] NOT NULL,
[RCV] [int] NOT NULL,
[WEATHER] [int] NOT NULL,
[SPECCOND] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[LOWTMPER] [decimal] (24, 2) NOT NULL,
[HIGHTMPER] [decimal] (24, 2) NOT NULL,
[SNDTIME] [datetime] NOT NULL,
[RCVTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STOREWEATHER] ADD CONSTRAINT [PK__STOREWEATHER__5BFFA6F1] PRIMARY KEY CLUSTERED  ([ADATE], [SRC]) ON [PRIMARY]
GO
