CREATE TABLE [dbo].[NPOLYPROM]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL,
[FILDATE] [datetime] NOT NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL,
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHKDATE] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__NPOLYPROM__RECCN__15823D10] DEFAULT (0),
[EXGDRECCNT] [int] NOT NULL CONSTRAINT [DF__NPOLYPROM__EXGDR__16766149] DEFAULT (0),
[SCHMRECCNT] [int] NOT NULL CONSTRAINT [DF__NPOLYPROM__SCHMR__176A8582] DEFAULT (0),
[DLTPRICEPROM] [smallint] NOT NULL CONSTRAINT [DF__NPOLYPROM__DLTPR__185EA9BB] DEFAULT (0),
[CALBYRTLPRC] [smallint] NOT NULL CONSTRAINT [DF__NPOLYPROM__CALBY__1952CDF4] DEFAULT (0),
[TOPIC] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[PSETTLENO] [int] NULL,
[PRIORITY] [int] NOT NULL CONSTRAINT [DF__NPOLYPROM__PRIOR__312035E4] DEFAULT (0),
[EXPROM] [int] NOT NULL CONSTRAINT [DF__NPOLYPROM__EXPRO__77B2AE5E] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPOLYPROM] ADD CONSTRAINT [PK__NPOLYPROM__1A46F22D] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
