CREATE TABLE [dbo].[BILLTOADJLACDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BILLTOADJLACDTL] ADD CONSTRAINT [PK__BILLTOADJLACDTL__5672817B] PRIMARY KEY CLUSTERED  ([NUM], [STOREGID]) ON [PRIMARY]
GO
