CREATE TABLE [dbo].[VDRLESSORTD]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SORT] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PAYRATE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__VDRLESSOR__PAYRA__6FA44AE6] DEFAULT (0),
[SHOPNO] [char] (30) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VDRLESSORTD] ADD CONSTRAINT [PK__VDRLESSORTD__70986F1F] PRIMARY KEY CLUSTERED  ([NUM], [SORT]) ON [PRIMARY]
GO
