CREATE TABLE [dbo].[ORIPOSKBDSCHEME]
(
[SCANCODE] [smallint] NOT NULL,
[FUNCTION] [smallint] NOT NULL,
[ALEFT] [smallint] NOT NULL,
[TOP] [smallint] NOT NULL,
[WIDTH] [smallint] NOT NULL,
[HEIGHT] [smallint] NOT NULL,
[DEVICEINDEX] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORIPOSKBDSCHEME] ADD CONSTRAINT [PK__ORIPOSKBDSCHEME__5A1A5A11] PRIMARY KEY CLUSTERED  ([DEVICEINDEX], [SCANCODE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
