CREATE TABLE [dbo].[CUSTOMERORDERBUY2]
(
[FLOWNO] [char] (16) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[GID] [int] NOT NULL,
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CUSTOMERORD__QTY__2975BDD2] DEFAULT (0),
[INPRC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CUSTOMERO__INPRC__2A69E20B] DEFAULT (0),
[PRICE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CUSTOMERO__PRICE__2B5E0644] DEFAULT (0),
[REALAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CUSTOMERO__REALA__2C522A7D] DEFAULT (0),
[FAVAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CUSTOMERO__FAVAM__2D464EB6] DEFAULT (0),
[SENT] [varchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[QPCGID] [int] NULL,
[PRMTAG] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[ASSISTANT] [int] NULL,
[WRH] [int] NULL CONSTRAINT [DF__CUSTOMERORD__WRH__2E3A72EF] DEFAULT (1),
[INVNO] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[BindWith] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CUSTOMERO__BindW__2F2E9728] DEFAULT (0),
[DEALER] [int] NULL,
[RFNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[IQTY] [decimal] (24, 2) NULL,
[GDCODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[GDNAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[SCRPRICE] [decimal] (24, 4) NULL,
[SCRFAVRATE] [decimal] (24, 4) NULL,
[SCORE] [decimal] (24, 4) NULL,
[SCOREINFO] [char] (100) COLLATE Chinese_PRC_CI_AS NULL,
[GDTYPE] [smallint] NOT NULL CONSTRAINT [DF__CUSTOMERO__GDTYP__3022BB61] DEFAULT (0),
[GDCODE2] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[MCODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUSTOMERORDERBUY2] ADD CONSTRAINT [PK__CustomerOrderBUY__3116DF9A] PRIMARY KEY CLUSTERED  ([FLOWNO], [POSNO], [ITEMNO]) ON [PRIMARY]
GO
