CREATE TABLE [dbo].[NCTSCOPE]
(
[CATEGORY] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CODE] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SQLCOND] [varchar] (255) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SQLTEXT] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCTSCOPE] ADD CONSTRAINT [PK__NCTSCOPE__7A77AA6B] PRIMARY KEY CLUSTERED  ([SRC], [ID], [CATEGORY], [CODE]) ON [PRIMARY]
GO
