CREATE TABLE [dbo].[ALCBYGOODS]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [smallint] NOT NULL,
[STAT] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[QTY] [money] NOT NULL CONSTRAINT [DF__ALCBYGOODS__QTY__70403C08] DEFAULT (0),
[TOTAL] [money] NOT NULL CONSTRAINT [DF__ALCBYGOOD__TOTAL__71346041] DEFAULT (0),
[TAX] [money] NOT NULL CONSTRAINT [DF__ALCBYGOODS__TAX__7228847A] DEFAULT (0),
[FILLER] [int] NOT NULL CONSTRAINT [DF__ALCBYGOOD__FILLE__731CA8B3] DEFAULT (1),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__ALCBYGOOD__FILDA__7410CCEC] DEFAULT (getdate()),
[CHECKER] [int] NOT NULL CONSTRAINT [DF__ALCBYGOOD__CHECK__7504F125] DEFAULT (1),
[INVQTY] [money] NOT NULL,
[DMDDATE] [datetime] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[sndtime] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ALCBYGOODS] ADD CONSTRAINT [PK__ALCBYGOODS__6F4C17CF] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
