CREATE TABLE [dbo].[TOURSCONSUMECARINFO]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[LICENSEPLATE] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARTYPE] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CUSTOMERS] [int] NOT NULL CONSTRAINT [DF__TOURSCONS__CUSTO__54D12470] DEFAULT (1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TOURSCONSUMECARINFO] ADD CONSTRAINT [PK__TOURSCONSUMECARI__55C548A9] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
