CREATE TABLE [dbo].[ESTORE]
(
[GID] [int] NOT NULL,
[FLAG] [smallint] NOT NULL CONSTRAINT [DF__ESTORE__FLAG__1413882A] DEFAULT (0),
[LSTUPDTIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ESTORE] ADD CONSTRAINT [PK__ESTORE__131F63F1] PRIMARY KEY CLUSTERED  ([GID]) ON [PRIMARY]
GO
