CREATE TABLE [dbo].[VOUCHERRECYCLEDTL]
(
[NUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[VOUCHERNUM] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERRECYCLEDTL] ADD CONSTRAINT [PK__VOUCHERRECYCLEDT__6281BBF7] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_VOUCHERRECYCLEDTL_NUMLINE] ON [dbo].[VOUCHERRECYCLEDTL] ([NUM], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_VOUCHERRECYCLEDTL_VOUCHERNUM] ON [dbo].[VOUCHERRECYCLEDTL] ([VOUCHERNUM]) ON [PRIMARY]
GO
