CREATE TABLE [dbo].[INVXFDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[MUNIT] [char] (6) COLLATE Chinese_PRC_CI_AS NOT NULL,
[QPCSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL,
[QPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__INVXFDTL__QPC__40097B06] DEFAULT (1),
[QTYSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__INVXFDTL__QTYSTR__40FD9F3F] DEFAULT ('0'),
[FROMBIN] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[TOBIN] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[FROMQTYSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__INVXFDTL__FROMQT__41F1C378] DEFAULT ('0'),
[TOQTYSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__INVXFDTL__TOQTYS__42E5E7B1] DEFAULT ('0'),
[FROMRTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__INVXFDTL__FROMRT__43DA0BEA] DEFAULT (0),
[TORTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__INVXFDTL__TORTOT__44CE3023] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__INVXFDTL__QTY__45C2545C] DEFAULT (0),
[BNUM] [char] (12) COLLATE Chinese_PRC_CI_AS NULL,
[CAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__INVXFDTL__CAMT__46B67895] DEFAULT (0),
[CTAX] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__INVXFDTL__CTAX__47AA9CCE] DEFAULT (0),
[VDRGID] [int] NULL,
[BILLTO] [int] NULL,
[SALE] [smallint] NULL,
[VBNUM] [char] (16) COLLATE Chinese_PRC_CI_AS NULL,
[VALIDDATE] [datetime] NULL,
[HAS2] [smallint] NOT NULL CONSTRAINT [DF__INVXFDTL__HAS2__489EC107] DEFAULT (0),
[REASON] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[PRICE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__INVXFDTL__PRICE__4992E540] DEFAULT (0),
[TOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__INVXFDTL__TOTAL__4A870979] DEFAULT (0),
[TAX] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__INVXFDTL__TAX__4B7B2DB2] DEFAULT (0),
[DMDQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__INVXFDTL__DMDQTY__4C6F51EB] DEFAULT (0),
[ALLOWQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__INVXFDTL__ALLOWQ__4D637624] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INVXFDTL] ADD CONSTRAINT [PK__INVXFDTL__3F1556CD] PRIMARY KEY CLUSTERED  ([NUM], [CLS], [LINE]) ON [PRIMARY]
GO
