CREATE TABLE [dbo].[ICPAYDTL]
(
[Num] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[Cls] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARDTYPE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[Count] [int] NOT NULL CONSTRAINT [DF__ICPAYDTL__Count__0D6755F2] DEFAULT (0),
[BALANCE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__ICPAYDTL__BALANC__0E5B7A2B] DEFAULT (0),
[CARDCOST] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__ICPAYDTL__CARDCO__0F4F9E64] DEFAULT (0),
[Amt] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__ICPAYDTL__Amt__1043C29D] DEFAULT (0)
) ON [PRIMARY]
GO
