CREATE TABLE [dbo].[MVENDORPLAN]
(
[YEAR] [decimal] (4, 0) NOT NULL,
[MONTH] [decimal] (2, 0) NOT NULL,
[VENDOR] [int] NOT NULL,
[TOTAL] [money] NOT NULL,
[GP] [money] NOT NULL,
[GPRATE] [money] NOT NULL,
[FPAY] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__MVENDORPLA__FPAY__034CE78E] DEFAULT ('-'),
[STORE] [int] NOT NULL CONSTRAINT [DF__MVENDORPL__STORE__61D6E52A] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MVENDORPLAN] ADD CONSTRAINT [PK__MVENDORPLAN__05353000] PRIMARY KEY CLUSTERED  ([YEAR], [MONTH], [VENDOR], [FPAY]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[Curdflt]', N'[dbo].[MVENDORPLAN].[GP]'
GO
EXEC sp_bindefault N'[dbo].[Curdflt]', N'[dbo].[MVENDORPLAN].[GPRATE]'
GO
