CREATE TABLE [dbo].[TA_KingdeeFACE]
(
[Fdate] [datetime] NULL,
[Fperiod] [int] NULL,
[Fgroup] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[Fnum] [int] NOT NULL,
[FEntryID] [int] NOT NULL,
[Fexp] [char] (80) COLLATE Chinese_PRC_CI_AS NULL,
[FAcctID] [char] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FClsName1] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[FObjID1] [char] (80) COLLATE Chinese_PRC_CI_AS NULL,
[FObjName1] [char] (80) COLLATE Chinese_PRC_CI_AS NULL,
[FClsName2] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[FObjID2] [char] (80) COLLATE Chinese_PRC_CI_AS NULL,
[FObjName2] [char] (80) COLLATE Chinese_PRC_CI_AS NULL,
[FClsName3] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[FObjID3] [char] (80) COLLATE Chinese_PRC_CI_AS NULL,
[FObjName3] [char] (80) COLLATE Chinese_PRC_CI_AS NULL,
[FClsName4] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[FObjID4] [char] (80) COLLATE Chinese_PRC_CI_AS NULL,
[FObjName4] [char] (80) COLLATE Chinese_PRC_CI_AS NULL,
[FClsName5] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[FObjID5] [char] (80) COLLATE Chinese_PRC_CI_AS NULL,
[FObjName5] [char] (80) COLLATE Chinese_PRC_CI_AS NULL,
[FClsName6] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[FObjID6] [char] (80) COLLATE Chinese_PRC_CI_AS NULL,
[FObjName6] [char] (80) COLLATE Chinese_PRC_CI_AS NULL,
[FClsName7] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[FObjID7] [char] (80) COLLATE Chinese_PRC_CI_AS NULL,
[FObjName7] [char] (80) COLLATE Chinese_PRC_CI_AS NULL,
[FClsName8] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[FObjID8] [char] (80) COLLATE Chinese_PRC_CI_AS NULL,
[FObjName8] [char] (80) COLLATE Chinese_PRC_CI_AS NULL,
[FTransID] [char] (80) COLLATE Chinese_PRC_CI_AS NULL,
[FCyID] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[FExchRate] [money] NULL,
[FDC] [char] (1) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FFcAmt] [money] NULL,
[Fqty] [money] NULL,
[Fprice] [money] NULL,
[Fdebit] [money] NULL,
[Fcredit] [money] NULL,
[FSettleCode] [char] (80) COLLATE Chinese_PRC_CI_AS NULL,
[FSettleNO] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[Fprepare] [char] (80) COLLATE Chinese_PRC_CI_AS NULL,
[Fpay] [char] (80) COLLATE Chinese_PRC_CI_AS NULL,
[Fcash] [char] (80) COLLATE Chinese_PRC_CI_AS NULL,
[Fposter] [char] (80) COLLATE Chinese_PRC_CI_AS NULL,
[Fchecker] [char] (80) COLLATE Chinese_PRC_CI_AS NULL,
[Fattchment] [int] NOT NULL CONSTRAINT [DF__TA_Kingde__Fattc__5E57614E] DEFAULT (0),
[Fposted] [bit] NOT NULL CONSTRAINT [DF__TA_Kingde__Fpost__5F4B8587] DEFAULT (0),
[Fmodule] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Fdeleted] [bit] NOT NULL CONSTRAINT [DF__TA_Kingde__Fdele__603FA9C0] DEFAULT (0),
[FSerialNO] [int] NULL
) ON [PRIMARY]
GO
