CREATE TABLE [dbo].[TEMPXLSORDERPOOL]
(
[spid] [int] NOT NULL,
[GDCODE] [char] (13) COLLATE Chinese_PRC_CI_AS NULL,
[VDRCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[WRHCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[COMBINETYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SENDDATE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[QTY] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[PRICE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[ORDERTYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[ORDERDATE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SPLITDAYS] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[ROUNDTYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[STOREORDAPPLYTYPE] [int] NULL,
[STOREORDAPPLYSTAT] [int] NULL
) ON [PRIMARY]
GO
