CREATE TABLE [dbo].[NORDERDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NULL,
[CASES] [money] NULL,
[QTY] [money] NULL,
[PRICE] [money] NULL,
[TOTAL] [money] NULL,
[TAX] [money] NULL,
[VALIDDATE] [datetime] NULL,
[WRH] [int] NULL CONSTRAINT [DF__NORDERDTL__WRH__69DC8BE5] DEFAULT (1),
[INVQTY] [money] NULL CONSTRAINT [DF__NORDERDTL__INVQT__6AD0B01E] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[FROMGID] [int] NOT NULL CONSTRAINT [DF__norderdtl__FROMG__1AFFB184] DEFAULT (1),
[FLAG] [int] NOT NULL CONSTRAINT [DF__norderdtl__FLAG__1BF3D5BD] DEFAULT (0),
[subwrh] [int] NULL,
[SUBWRHCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[ADVQTY] [decimal] (24, 4) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NORDERDTL] ADD CONSTRAINT [PK__NORDERDTL__3AA1AEB8] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
