CREATE TABLE [dbo].[TMP_GRPGFTSENDED]
(
[spid] [int] NOT NULL,
[RCODE] [char] (18) COLLATE Chinese_PRC_CI_AS NULL,
[GROUPID] [int] NULL,
[CTRTYPE] [int] NULL CONSTRAINT [DF__TMP_GRPGF__CTRTY__29647622] DEFAULT (0),
[QTY] [decimal] (24, 2) NULL,
[TOBCKQTY] [decimal] (24, 2) NULL,
[AMT] [decimal] (24, 2) NULL,
[TOBCKAMT] [decimal] (24, 2) NULL,
[DONE] [int] NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx_TMP_GRPGFTSENDED_spid] ON [dbo].[TMP_GRPGFTSENDED] ([spid]) ON [PRIMARY]
GO
