CREATE TABLE [dbo].[CRMWEBSESSION]
(
[SID] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[USERGID] [int] NOT NULL,
[STOREGID] [int] NOT NULL,
[OPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[WORKSTATION] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[EXPIRINGDATE] [datetime] NOT NULL CONSTRAINT [DF__CRMWEBSES__EXPIR__118DB7E8] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMWEBSESSION] ADD CONSTRAINT [PK__CRMWEBSESSION__1281DC21] PRIMARY KEY CLUSTERED  ([SID]) ON [PRIMARY]
GO
