CREATE TABLE [dbo].[GIFTHST]
(
[LSTID] [char] (16) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL,
[VENDOR] [int] NOT NULL,
[START] [datetime] NOT NULL CONSTRAINT [DF__GIFTHST__START__1546D82E] DEFAULT ('1899.12.30 00:00:00'),
[FINISH] [datetime] NOT NULL CONSTRAINT [DF__GIFTHST__FINISH__163AFC67] DEFAULT ('9999.12.31 23:59:59'),
[GDGID] [int] NOT NULL,
[INQTY] [money] NOT NULL,
[GFTGID] [int] NOT NULL,
[GFTQTY] [money] NOT NULL,
[SRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRCLINE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CANCELDATE] [datetime] NOT NULL CONSTRAINT [DF__GIFTHST__CANCELD__172F20A0] DEFAULT ('1899.12.31 23:59:59'),
[GFTWRH] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GIFTHST] ADD CONSTRAINT [PK__GIFTHST__1452B3F5] PRIMARY KEY CLUSTERED  ([LSTID], [STOREGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
