CREATE TABLE [dbo].[VOUCHERGIVERULEOCR]
(
[STORE] [int] NOT NULL,
[BILLNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VOUCHERACTIVITY] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ISWHOLEGIVE] [smallint] NOT NULL,
[ISALLPRMOUT] [smallint] NOT NULL,
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[AMTCOND] [smallint] NOT NULL,
[AMTCONDUSEAMT] [decimal] (24, 2) NULL,
[ISACCUCALC] [smallint] NOT NULL,
[SUBJECT] [varchar] (255) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERGIVERULEOCR] ADD CONSTRAINT [PK__VOUCHERGIVERULEO__31979935] PRIMARY KEY CLUSTERED  ([STORE], [BILLNUM]) ON [PRIMARY]
GO
