CREATE TABLE [dbo].[NLMTPRMDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[START] [datetime] NOT NULL CONSTRAINT [DF__NLMTPRMDT__START__179934F4] DEFAULT ('1899.12.30 00:00:00'),
[FINISH] [datetime] NOT NULL CONSTRAINT [DF__NLMTPRMDT__FINIS__188D592D] DEFAULT ('9999.12.31 23:59:59'),
[QTYLMT] [money] NOT NULL CONSTRAINT [DF__NLMTPRMDT__QTYLM__19817D66] DEFAULT (0),
[PRICE] [money] NOT NULL CONSTRAINT [DF__NLMTPRMDT__PRICE__1A75A19F] DEFAULT (0),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__NLMTPRMDTL__STAT__1B69C5D8] DEFAULT (0),
[LSTID] [char] (16) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NLMTPRMDTL] ADD CONSTRAINT [PK__NLMTPRMDTL__16A510BB] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
