CREATE TABLE [dbo].[CNTRPAYCASHDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[CHGTYPE] [char] (16) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRCNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[IVCNUM] [char] (16) COLLATE Chinese_PRC_CI_AS NULL,
[IVCCODE] [char] (16) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TOTALBAL] [decimal] (24, 2) NOT NULL,
[IVCAMT] [decimal] (24, 2) NOT NULL,
[IVCPAY] [decimal] (24, 2) NOT NULL,
[PAYTOTAL] [decimal] (24, 2) NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CNTRPAYCASHDTL] ADD CONSTRAINT [PK__CNTRPAYCASHDTL__102F7F5B] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
