CREATE TABLE [dbo].[PROCEXECPOOLLOG]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[OPERTIME] [datetime] NOT NULL,
[PROCTASKNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PSCPCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PROCEXECNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ACTION] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [char] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROCEXECPOOLLOG] ADD CONSTRAINT [PK__PROCEXECPOOLLOG__0766C5DE] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
