CREATE TABLE [dbo].[FAFLOWOBJZORDER]
(
[UUID] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [int] NOT NULL,
[LINE] [int] NOT NULL,
[FZORDER] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FAFLOWOBJZORDER] ADD CONSTRAINT [PK__FAFLOWOBJZORDER__19E568CC] PRIMARY KEY CLUSTERED  ([UUID], [ITEMNO], [LINE]) ON [PRIMARY]
GO
