CREATE TABLE [dbo].[NBLPREORDDTL]
(
[ID] [int] NOT NULL,
[SRC] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[FLAG] [smallint] NOT NULL CONSTRAINT [DF__NBLPREORDD__FLAG__31C648A7] DEFAULT (0),
[GDGID] [int] NULL,
[MINORDCases] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NBLPREORD__MINOR__32BA6CE0] DEFAULT (0),
[MINORDQTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NBLPREORD__MINOR__33AE9119] DEFAULT (0),
[ORDPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NBLPREORD__ORDPR__34A2B552] DEFAULT (0),
[RTLPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NBLPREORD__RTLPR__3596D98B] DEFAULT (0),
[WHSPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NBLPREORD__WHSPR__368AFDC4] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NBLPREORDDTL] ADD CONSTRAINT [PK__NBLPREORDDTL__377F21FD] PRIMARY KEY CLUSTERED  ([ID], [SRC], [LINE]) ON [PRIMARY]
GO
