CREATE TABLE [dbo].[ord_bhsvr]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NULL,
[VENDOR] [int] NULL,
[TOTAL] [money] NULL,
[TAX] [money] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[FILDATE] [datetime] NULL,
[PAYDATE] [datetime] NULL,
[PREPAY] [money] NULL,
[FILLER] [int] NULL,
[CHECKER] [int] NULL,
[PSR] [int] NULL,
[STAT] [smallint] NULL,
[MODNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[WRH] [int] NULL,
[RECCNT] [int] NULL,
[SRC] [int] NULL,
[SRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[RECEIVER] [int] NULL,
[PRNTIME] [datetime] NULL,
[FINISHED] [smallint] NULL,
[AUTO] [smallint] NULL,
[ALCCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[EXPDATE] [datetime] NULL,
[PRECHECKER] [int] NULL,
[PRECHKDATE] [datetime] NULL,
[DLVBDATE] [datetime] NULL,
[DLVEDATE] [datetime] NULL,
[IMPFLAG] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
