CREATE TABLE [dbo].[BRANDDELETE]
(
[CODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[AREA] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__BRANDDELET__AREA__7EEC1DD7] DEFAULT (1),
[TEMPLATEGID] [int] NULL,
[CREATOR] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__BRANDDELE__CREAT__7FE04210] DEFAULT ('未知[-]'),
[CREATETIME] [datetime] NOT NULL CONSTRAINT [DF__BRANDDELE__CREAT__00D46649] DEFAULT (getdate()),
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__BRANDDELE__LSTUP__01C88A82] DEFAULT ('未知[-]'),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__BRANDDELE__LSTUP__02BCAEBB] DEFAULT (getdate()),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[INTRODUCETIME] [datetime] NULL,
[INTRODUCEOPER] [int] NULL,
[BUSINESSSTAT] [smallint] NOT NULL CONSTRAINT [DF__BRANDDELE__BUSIN__03B0D2F4] DEFAULT (1),
[ELIMINATETIME] [datetime] NULL,
[BRANDCLASS] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BRANDDELETE] ADD CONSTRAINT [PK__BRANDDELETE__04A4F72D] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
