CREATE TABLE [dbo].[BCPDEF]
(
[OBJNAME] [char] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FIELDNAME] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FIELDLABEL] [char] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DATATYPE] [smallint] NOT NULL CONSTRAINT [DF__BCPDEF__DATATYPE__6ECDC039] DEFAULT (1),
[DATALENGTH] [smallint] NULL,
[DATADECIMAL] [smallint] NULL,
[DATAISNULL] [smallint] NOT NULL CONSTRAINT [DF__BCPDEF__DATAISNU__6FC1E472] DEFAULT (0),
[CTRLSTYLE] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__BCPDEF__CTRLSTYL__70B608AB] DEFAULT ('TEdit'),
[DEFVALUE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[VALIDVALUE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[HASSYNC] [smallint] NOT NULL CONSTRAINT [DF__BCPDEF__HASSYNC__71AA2CE4] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BCPDEF] ADD CONSTRAINT [PK__BCPDEF__14B10FFA] PRIMARY KEY CLUSTERED  ([OBJNAME], [FIELDNAME]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
