CREATE TABLE [dbo].[PS3SCOREGOODS]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [int] NOT NULL,
[BGNTIME] [datetime] NOT NULL,
[ENDTIME] [datetime] NOT NULL,
[SCORESORT] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PS3SCOREG__SCORE__500ED158] DEFAULT ('-'),
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__PS3SCOREG__LSTUP__5102F591] DEFAULT (getdate()),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3SCOREGOODS] ADD CONSTRAINT [PK__PS3SCOREGOODS__51F719CA] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
