CREATE TABLE [dbo].[CRMCARDBLKLST]
(
[CARDNUM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GRADE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMCARDBL__GRADE__0D757046] DEFAULT ('正常处理'),
[SNDTIME] [datetime] NULL,
[LSTUPDTIME] [datetime] NULL CONSTRAINT [DF__CRMCARDBL__LSTUP__0E69947F] DEFAULT (getdate()),
[SYSUUID] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMCARDBLKLST] ADD CONSTRAINT [PK__CRMCARDBLKLST__0F5DB8B8] PRIMARY KEY CLUSTERED  ([CARDNUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_CRMCARDBLKLST_LST] ON [dbo].[CRMCARDBLKLST] ([LSTUPDTIME]) ON [PRIMARY]
GO
