CREATE TABLE [dbo].[EMPLOYEERIGHT]
(
[EMPLOYEE] [int] NOT NULL,
[EMPLOYEEGROUP] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMPLOYEERIGHT] ADD CONSTRAINT [PK__EMPLOYEERIGHT__54968AE5] PRIMARY KEY CLUSTERED  ([EMPLOYEE], [EMPLOYEEGROUP]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
