CREATE TABLE [dbo].[SETTLEACCOUNT]
(
[NO] [smallint] NOT NULL,
[NAME] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[CODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SETTLEACCOUNT] ADD CONSTRAINT [PK__SETTLEACCOUNT__1CDC41A7] PRIMARY KEY CLUSTERED  ([NO]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SETTLEACCOUNT] ADD CONSTRAINT [UQ__SETTLEACCOUNT__1A966887] UNIQUE NONCLUSTERED  ([CODE]) ON [PRIMARY]
GO
