CREATE TABLE [dbo].[GFTPRM]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[BEGINTIME] [datetime] NOT NULL,
[ENDTIME] [datetime] NOT NULL,
[SRC] [int] NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__GFTPRM__LSTUPDTI__50B34D6D] DEFAULT (getdate()),
[NOTE] [text] COLLATE Chinese_PRC_CI_AS NULL,
[PRNTIME] [datetime] NULL,
[SETTLENO] [int] NOT NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__GFTPRM__RECCNT__51A771A6] DEFAULT (0),
[TOPIC] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__GFTPRM__TOPIC__529B95DF] DEFAULT ('-')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GFTPRM] ADD CONSTRAINT [PK__GFTPRM__4FBF2934] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
