CREATE TABLE [dbo].[CTCHGDEF]
(
[CODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[CHGCLS] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MODALTYPE] [char] (2) COLLATE Chinese_PRC_CI_AS NOT NULL,
[AUTOCALC] [smallint] NOT NULL CONSTRAINT [DF__CTCHGDEF__AUTOCA__14351A69] DEFAULT (0),
[WHENGEN] [char] (8) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GENMETHOD] [smallint] NULL,
[GENUNIT] [char] (4) COLLATE Chinese_PRC_CI_AS NULL,
[GENCYCLE] [smallint] NULL,
[GENDAYOFFSET] [smallint] NULL,
[PAYDIRECT] [smallint] NOT NULL CONSTRAINT [DF__CTCHGDEF__PAYDIR__15293EA2] DEFAULT (1),
[GATHERINGMODE] [char] (8) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CTCHGDEF__GATHER__161D62DB] DEFAULT ('冲扣货款'),
[TOPAYMETHOD] [smallint] NOT NULL CONSTRAINT [DF__CTCHGDEF__TOPAYM__17118714] DEFAULT (0),
[PAYLIMIT] [smallint] NOT NULL CONSTRAINT [DF__CTCHGDEF__PAYLIM__1805AB4D] DEFAULT (0),
[FINCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[FINNAME] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[STOPPED] [smallint] NOT NULL CONSTRAINT [DF__CTCHGDEF__STOPPE__446E3D70] DEFAULT (0),
[PAYUNIT] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CTCHGDEF__PAYUNI__52D3CD65] DEFAULT ('总部'),
[DESIGNCYCLE] [smallint] NOT NULL CONSTRAINT [DF__CTCHGDEF__DESIGN__68C30E84] DEFAULT (0),
[COUNTUNIT] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CTCHGDEF__COUNTU__09DD16E8] DEFAULT ('月'),
[TAXRATE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CTCHGDEF__TAXRAT__74B9737E] DEFAULT ((0)),
[TAXSORTCODE] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[IVCDTLNAME] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CTCHGDEF] ADD CONSTRAINT [PK__CTCHGDEF__18F9CF86] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
