CREATE TABLE [dbo].[ITEMREG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STORE] [int] NOT NULL,
[CONSUMER] [varchar] (16) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CONTACT] [varchar] (256) COLLATE Chinese_PRC_CI_AS NULL,
[FILLDATE] [datetime] NOT NULL CONSTRAINT [DF__ITEMREG__FILLDAT__55255ED4] DEFAULT (getdate()),
[OVERDATE] [datetime] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__ITEMREG__STAT__5619830D] DEFAULT (0),
[RECCNT] [int] NOT NULL,
[OPERATOR] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[QUEUENUM] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[REGFEE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__ITEMREG__REGFEE__570DA746] DEFAULT (0),
[MEMO] [varchar] (256) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ITEMREG] ADD CONSTRAINT [PK__ITEMREG__5801CB7F] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
