CREATE TABLE [dbo].[PSSUMGDSCOREHST]
(
[UUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARDNUM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARRIER] [int] NOT NULL,
[SORT] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[AMOUNT] [decimal] (24, 2) NULL,
[QTY] [decimal] (24, 4) NULL,
[SCORE] [decimal] (24, 2) NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__PSSUMGDSC__FILDA__1305C318] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSSUMGDSCOREHST] ADD CONSTRAINT [PK__PSSUMGDSCOREHST__13F9E751] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PSSUMGDSCOREHST_CARDNUM] ON [dbo].[PSSUMGDSCOREHST] ([CARDNUM]) ON [PRIMARY]
GO
