CREATE TABLE [dbo].[PSBRANDSORT]
(
[BRANDCODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SORTCODE] [varchar] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[AGENTNAME] [varchar] (200) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PSBRANDSO__AGENT__20C77085] DEFAULT ('未知[-]'),
[MANUFACTURENAME] [varchar] (200) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PSBRANDSO__MANUF__21BB94BE] DEFAULT ('未知[-]'),
[CLIENTDESC] [varchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[CLIENTSEX] [int] NOT NULL CONSTRAINT [DF__PSBRANDSO__CLIEN__22AFB8F7] DEFAULT (0),
[INTRODUCEEMP] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[INTRODUCEDATE] [datetime] NULL,
[CREATOR] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PSBRANDSO__CREAT__23A3DD30] DEFAULT ('未知[-]'),
[CREATETIME] [datetime] NOT NULL CONSTRAINT [DF__PSBRANDSO__CREAT__24980169] DEFAULT (getdate()),
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PSBRANDSO__LSTUP__258C25A2] DEFAULT ('未知[-]'),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__PSBRANDSO__LSTUP__268049DB] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSBRANDSORT] ADD CONSTRAINT [PK__PSBRANDSORT__27746E14] PRIMARY KEY CLUSTERED  ([BRANDCODE], [SORTCODE]) ON [PRIMARY]
GO
