CREATE TABLE [dbo].[MODULESTATFLOW]
(
[MODULENO] [int] NOT NULL,
[NO] [int] NOT NULL,
[STATNO] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MODULESTATFLOW] ADD CONSTRAINT [PK__MODULESTATFLOW__38A5EE5B] PRIMARY KEY CLUSTERED  ([MODULENO], [NO]) ON [PRIMARY]
GO
