CREATE TABLE [dbo].[PSTASKMAN]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BOCLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PSTASKMAN__BOCLS__5A9E4108] DEFAULT ('工作任务'),
[STAT] [smallint] NOT NULL,
[BGNTIME] [datetime] NULL,
[ENDTIME] [datetime] NULL,
[SUBTIME] [datetime] NULL,
[SUBEMP] [int] NULL,
[DEPTNAME] [varchar] (120) COLLATE Chinese_PRC_CI_AS NULL,
[REPT] [int] NOT NULL CONSTRAINT [DF__PSTASKMAN__REPT__5B926541] DEFAULT (0),
[CYCLE] [int] NOT NULL CONSTRAINT [DF__PSTASKMAN__CYCLE__5C86897A] DEFAULT (0),
[SUBJECT] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[CONTENT] [text] COLLATE Chinese_PRC_CI_AS NULL,
[EXESTAT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PSTASKMAN__EXEST__5D7AADB3] DEFAULT (0),
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL,
[LSTRPLYTIME] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSTASKMAN] ADD CONSTRAINT [PK__PSTASKMAN__5E6ED1EC] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
