CREATE TABLE [dbo].[PAYSTORESALECHECKLOG]
(
[CLS] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHECKTIME] [datetime] NOT NULL CONSTRAINT [DF__PAYSTORES__CHECK__1AC3B315] DEFAULT (getdate()),
[CHECKER] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAYSTORESALECHECKLOG] ADD CONSTRAINT [PK__PAYSTORESALECHEC__1BB7D74E] PRIMARY KEY CLUSTERED  ([CLS], [NUM]) ON [PRIMARY]
GO
