CREATE TABLE [dbo].[NPROMQTY]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[NO] [smallint] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PRMNO] [int] NOT NULL,
[QTY] [decimal] (24, 4) NOT NULL,
[PRMTOTAL] [decimal] (24, 4) NOT NULL,
[IFGFT] [int] NOT NULL,
[GFTQTY] [decimal] (24, 4) NOT NULL,
[PTOTAL] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPROMQTY__PTOTAL__35D8675B] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPROMQTY] ADD CONSTRAINT [PK__NPROMQTY__780486BD] PRIMARY KEY CLUSTERED  ([SRC], [ID], [NO], [NUM], [CLS], [PRMNO]) ON [PRIMARY]
GO
