CREATE TABLE [dbo].[PS3DISNOTDISCOUNTDEPT]
(
[DEPT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3DISNOTDISCOUNTDEPT] ADD CONSTRAINT [PK__PS3DISNOTDISCOUN__2E1FD4F5] PRIMARY KEY CLUSTERED  ([DEPT]) ON [PRIMARY]
GO
