CREATE TABLE [dbo].[PSSORTSCORULEOPT]
(
[OPTCAPTION] [varchar] (128) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OPTVALUE] [varchar] (128) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__PSSORTSCO__LSTUP__43A8FA73] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSSORTSCORULEOPT] ADD CONSTRAINT [PK__PSSORTSCORULEOPT__449D1EAC] PRIMARY KEY CLUSTERED  ([OPTCAPTION]) ON [PRIMARY]
GO
