CREATE TABLE [dbo].[PS3MAXSCORELIMIT]
(
[UUID] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3MAXSCO__SCORE__252CFE46] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3MAXSCORELIMIT] ADD CONSTRAINT [PK__PS3MAXSCORELIMIT__2621227F] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
