CREATE TABLE [dbo].[NTAXSORT]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[GID] [int] NOT NULL,
[CODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[PROVINCE] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[FRCUPD] [smallint] NOT NULL,
[TYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NTAXSORT] ADD CONSTRAINT [PK__NTAXSORT__A93FC8E37BC59869] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
