CREATE TABLE [dbo].[RTLINV]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLIENT] [char] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[SPEC] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Munit] [char] (4) COLLATE Chinese_PRC_CI_AS NULL,
[TOTAL] [money] NOT NULL,
[ISSUER] [int] NOT NULL,
[ISSUETIME] [datetime] NOT NULL,
[PRINTTIMES] [smallint] NOT NULL CONSTRAINT [DF__RTLINV__PRINTTIM__48A74BFA] DEFAULT (0),
[MODNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[PRNTIME] [datetime] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [smallint] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__RTLINV__STAT__499B7033] DEFAULT (0),
[ALLAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__RtlInv__ALLAMT__0F99B727] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RTLINV] WITH NOCHECK ADD CONSTRAINT [RTLINV_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[RTLINV] ADD CONSTRAINT [单号重复] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
