CREATE TABLE [dbo].[CoupondDispatch]
(
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (8) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[COUPONCODE] [varchar] (128) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PARVALUE] [money] NOT NULL CONSTRAINT [DF__CoupondDi__PARVA__50312EEE] DEFAULT (0),
[COUPONCOUNT] [int] NOT NULL CONSTRAINT [DF__CoupondDi__COUPO__51255327] DEFAULT (0),
[MEMO] [char] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
