CREATE TABLE [dbo].[TAXSORTADJ]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__TAXSORTAD__FILDA__559FEF81] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__TAXSORTADJ__STAT__569413BA] DEFAULT ((0)),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__TAXSORTAD__RECCN__578837F3] DEFAULT ((0)),
[LAUNCH] [datetime] NULL,
[EON] [smallint] NOT NULL CONSTRAINT [DF__TAXSORTADJ__EON__587C5C2C] DEFAULT ((1)),
[SRC] [int] NOT NULL CONSTRAINT [DF__TAXSORTADJ__SRC__59708065] DEFAULT ((1)),
[SRCNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[LSTUPDTIME] [datetime] NULL,
[PROVINCE] [char] (32) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TAXSORTADJ] ADD CONSTRAINT [PK__TAXSORTA__C7D1B76B5B58C8D7] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [INDEX_RTLPRCADJ_FILDATE] ON [dbo].[TAXSORTADJ] ([FILDATE]) ON [PRIMARY]
GO
