CREATE TABLE [dbo].[STOREBUY21]
(
[STOREGID] [int] NOT NULL,
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[FAVTYPE] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FAVAMT] [money] NOT NULL CONSTRAINT [DF__STOREBUY2__FAVAM__23F4EA38] DEFAULT (0),
[TAG] [smallint] NOT NULL CONSTRAINT [DF__STOREBUY21__TAG__24E90E71] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STOREBUY21] ADD CONSTRAINT [PK__STOREBUY21__2300C5FF] PRIMARY KEY CLUSTERED  ([STOREGID], [POSNO], [FLOWNO], [ITEMNO], [FAVTYPE]) ON [PRIMARY]
GO
