CREATE TABLE [dbo].[rb_BUY1]
(
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__rb_BUY1__FILDATE__1E29644E] DEFAULT (getdate()),
[CASHIER] [int] NOT NULL CONSTRAINT [DF__rb_BUY1__CASHIER__1F1D8887] DEFAULT (1),
[WRH] [int] NOT NULL CONSTRAINT [DF__rb_BUY1__WRH__2011ACC0] DEFAULT (1),
[ASSISTANT] [int] NULL,
[TOTAL] [money] NOT NULL CONSTRAINT [DF__rb_BUY1__TOTAL__2105D0F9] DEFAULT (0),
[REALAMT] [money] NOT NULL CONSTRAINT [DF__rb_BUY1__REALAMT__21F9F532] DEFAULT (0),
[PREVAMT] [money] NOT NULL CONSTRAINT [DF__rb_BUY1__PREVAMT__22EE196B] DEFAULT (0),
[GUEST] [int] NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__rb_BUY1__RECCNT__23E23DA4] DEFAULT (0),
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[TAG] [smallint] NOT NULL CONSTRAINT [DF__rb_BUY1__TAG__24D661DD] DEFAULT (0),
[INVNO] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SCORE] [money] NULL,
[CardCode] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[DEALER] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[rb_BUY1] ADD CONSTRAINT [PK__rb_BUY1__1D354015] PRIMARY KEY CLUSTERED  ([POSNO], [FLOWNO]) ON [PRIMARY]
GO
