CREATE TABLE [dbo].[ASBUY1_002]
(
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__ASBUY1_00__FILDA__25C391D1] DEFAULT (getdate()),
[CASHIER] [int] NOT NULL CONSTRAINT [DF__ASBUY1_00__CASHI__26B7B60A] DEFAULT (1),
[WRH] [int] NOT NULL CONSTRAINT [DF__ASBUY1_002__WRH__27ABDA43] DEFAULT (1),
[ASSISTANT] [int] NULL,
[TOTAL] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__ASBUY1_00__TOTAL__289FFE7C] DEFAULT (0),
[REALAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__ASBUY1_00__REALA__299422B5] DEFAULT (0),
[PREVAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__ASBUY1_00__PREVA__2A8846EE] DEFAULT (0),
[GUEST] [int] NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__ASBUY1_00__RECCN__2B7C6B27] DEFAULT (0),
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[TAG] [smallint] NOT NULL CONSTRAINT [DF__ASBUY1_002__TAG__2C708F60] DEFAULT (0),
[INVNO] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SCORE] [decimal] (24, 4) NULL,
[CARDCODE] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[DEALER] [int] NULL,
[FLAG] [int] NOT NULL CONSTRAINT [DF__ASBUY1_002__FLAG__2D64B399] DEFAULT (0),
[SCOREINFO] [char] (100) COLLATE Chinese_PRC_CI_AS NULL,
[ASNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ASBUY1_002] ADD CONSTRAINT [PK__ASBUY1_002__2E58D7D2] PRIMARY KEY CLUSTERED  ([FLOWNO], [POSNO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FILDATE] ON [dbo].[ASBUY1_002] ([FILDATE]) ON [PRIMARY]
GO
