CREATE TABLE [dbo].[GOODSAPP]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__GOODSAPP__STAT__36BE7140] DEFAULT (0),
[RATIFIER] [int] NOT NULL,
[SRC] [int] NOT NULL,
[PSR] [int] NOT NULL CONSTRAINT [DF__GOODSAPP__PSR__37B29579] DEFAULT (1),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__GOODSAPP__FILDAT__38A6B9B2] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[RATOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[RATDATE] [datetime] NULL,
[DEADDATE] [datetime] NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__GOODSAPP__LSTUPD__399ADDEB] DEFAULT (getdate()),
[PRNTIME] [datetime] NULL,
[SNDTIME] [datetime] NULL,
[SETTLENO] [int] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[GOODSCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[APPMODE] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__GOODSAPP__RECCNT__3A8F0224] DEFAULT (0),
[MODNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[BOCLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GOODSAPP] ADD CONSTRAINT [PK__GOODSAPP__35CA4D07] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
