CREATE TABLE [dbo].[VOUCHERCASHAUTHOR]
(
[NUM] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[CODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLAG] [int] NOT NULL,
[CODE2] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[FLAG2] [smallint] NOT NULL CONSTRAINT [DF__VOUCHERCA__FLAG2__2BEFD5C5] DEFAULT (0),
[GDGID] [int] NOT NULL CONSTRAINT [DF__VOUCHERCA__GDGID__40B5E881] DEFAULT ((-1))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERCASHAUTHOR] ADD CONSTRAINT [PK__VOUCHERCASHAUTHO__457A9D9E] PRIMARY KEY CLUSTERED  ([NUM], [LINE], [GDGID]) ON [PRIMARY]
GO
