CREATE TABLE [dbo].[EGOODS]
(
[GID] [int] NOT NULL,
[FLAG] [smallint] NOT NULL CONSTRAINT [DF__EGOODS__FLAG__0C726662] DEFAULT (0),
[LSTUPDTIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EGOODS] ADD CONSTRAINT [PK__EGOODS__0B7E4229] PRIMARY KEY CLUSTERED  ([GID]) ON [PRIMARY]
GO
