CREATE TABLE [dbo].[PRMOFFSET]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VDRGID] [int] NOT NULL,
[SETTLENO] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__PRMOFFSET__FILDA__14983A78] DEFAULT (getdate()),
[FILLER] [int] NOT NULL CONSTRAINT [DF__PRMOFFSET__FILLE__158C5EB1] DEFAULT (1),
[CHECKER] [int] NULL,
[CHKDATE] [datetime] NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__PRMOFFSET__RECCN__168082EA] DEFAULT (0),
[STAT] [int] NOT NULL CONSTRAINT [DF__PRMOFFSET__STAT__1774A723] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[EON] [smallint] NOT NULL CONSTRAINT [DF__PRMOFFSET__EON__1868CB5C] DEFAULT (1),
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[LAUNCH] [datetime] NULL,
[LSTUPDTIME] [datetime] NULL,
[OFFSETTYPE] [int] NOT NULL CONSTRAINT [DF__PRMOFFSET__OFFSE__195CEF95] DEFAULT (0),
[OFFSETCALCTYPE] [int] NOT NULL CONSTRAINT [DF__PRMOFFSET__OFFSE__1A5113CE] DEFAULT (0),
[TOTAL] [decimal] (24, 4) NULL,
[AMOUNT] [decimal] (24, 4) NULL,
[TAX] [decimal] (24, 4) NULL,
[BILLTO] [int] NOT NULL,
[GATHERINGMODE] [int] NOT NULL CONSTRAINT [DF__PRMOFFSET__GATHE__1B453807] DEFAULT (0),
[SRC] [int] NULL,
[CHGNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[DeptLmt] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[PAYFLAG] [int] NULL,
[SETTLEDEPTCODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[PSR] [int] NULL,
[PAYDIRECT] [smallint] NOT NULL CONSTRAINT [DF__PRMOFFSET__PAYDI__1C395C40] DEFAULT (1),
[BTYPE] [smallint] NOT NULL CONSTRAINT [DF__PRMOFFSET__BTYPE__1D2D8079] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRMOFFSET] ADD CONSTRAINT [PK__PRMOFFSET__1E21A4B2] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
