CREATE TABLE [dbo].[NOAUTOORDERREASON]
(
[REASONCODE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[REASONNAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NOAUTOORDERREASON] ADD CONSTRAINT [PK__NOAUTOORDERREASO__5D3B81E8] PRIMARY KEY CLUSTERED  ([REASONCODE]) ON [PRIMARY]
GO
