CREATE TABLE [dbo].[PRCADJ]
(
[CLS] [char] (8) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PRCADJ__CLS__46093FC3] DEFAULT ('核算售价'),
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NULL,
[FILDATE] [datetime] NULL CONSTRAINT [DF__PRCADJ__FILDATE__46FD63FC] DEFAULT (getdate()),
[FILLER] [int] NULL CONSTRAINT [DF__PRCADJ__FILLER__47F18835] DEFAULT (1),
[CHECKER] [int] NULL CONSTRAINT [DF__PRCADJ__CHECKER__48E5AC6E] DEFAULT (1),
[ADJAMT] [money] NULL CONSTRAINT [DF__PRCADJ__ADJAMT__49D9D0A7] DEFAULT (0),
[STAT] [smallint] NULL CONSTRAINT [DF__PRCADJ__STAT__4ACDF4E0] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NULL CONSTRAINT [DF__PRCADJ__RECCNT__4BC21919] DEFAULT (0),
[LAUNCH] [datetime] NULL,
[EON] [smallint] NULL CONSTRAINT [DF__PRCADJ__EON__4CB63D52] DEFAULT (1),
[SRC] [int] NULL CONSTRAINT [DF__PRCADJ__SRC__4DAA618B] DEFAULT (1),
[SRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[WRH] [int] NULL,
[SrcFilDate] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRCADJ] WITH NOCHECK ADD CONSTRAINT [PRCADJ_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[PRCADJ] ADD CONSTRAINT [PK__PRCADJ__73DA2C14] PRIMARY KEY CLUSTERED  ([CLS], [NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FILDATE] ON [dbo].[PRCADJ] ([FILDATE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
