CREATE TABLE [dbo].[PSGDLISTLACDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSGDLISTLACDTL] ADD CONSTRAINT [PK__PSGDLISTLACDTL__375504CB] PRIMARY KEY CLUSTERED  ([NUM], [STOREGID]) ON [PRIMARY]
GO
