CREATE TABLE [dbo].[WEBSUSER]
(
[UUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LOGINNAME] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PASSWORD] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SHOPCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SHOPNAME] [char] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GID] [int] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WEBSUSER] ADD CONSTRAINT [PK__WEBSUSER__6C57A0F9] PRIMARY KEY CLUSTERED  ([SHOPCODE], [GID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [UK_WEBSUSER_GID] ON [dbo].[WEBSUSER] ([GID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [UK_WEBSUSER_SHOPCODE] ON [dbo].[WEBSUSER] ([SHOPCODE]) ON [PRIMARY]
GO
