CREATE TABLE [dbo].[PS3_OTHERBUYDTL]
(
[LINE] [smallint] NOT NULL,
[BUYTYPE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[QTY] [decimal] (24, 4) NOT NULL,
[REALAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PS3_OTHER__REALA__7CE4A52B] DEFAULT ((0)),
[PRICE] [decimal] (24, 4) NOT NULL,
[TOTAL] [decimal] (24, 4) NOT NULL,
[REMARK] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[UUID] [varchar] (38) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3_OTHERBUYDTL] ADD CONSTRAINT [PK__PS3_OTHE__33AEB8217ECCED9D] PRIMARY KEY CLUSTERED  ([UUID], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_OTHERBUYDTL_TYPE] ON [dbo].[PS3_OTHERBUYDTL] ([UUID], [BUYTYPE]) ON [PRIMARY]
GO
