CREATE TABLE [dbo].[PS3_ONLINECNTRRATEBYMONTHDISC]
(
[UUID] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PLATFORM] [varchar] (80) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CNTRNO] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DLINE] [smallint] NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[LOWDATE] [datetime] NOT NULL,
[HIGHDATE] [datetime] NOT NULL,
[RATE] [decimal] (24, 4) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3_ONLINECNTRRATEBYMONTHDISC] ADD CONSTRAINT [PK__PS3_ONLI__0C2ECB37392E995C] PRIMARY KEY CLUSTERED  ([UUID], [DLINE], [ITEMNO]) ON [PRIMARY]
GO
