CREATE TABLE [dbo].[RTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__RTL__STAT__21ED718C] DEFAULT (0),
[TOTAL] [money] NOT NULL,
[TAX] [money] NOT NULL,
[CHANGE] [money] NOT NULL,
[FILLER] [int] NOT NULL,
[UNDERTAKER] [int] NULL,
[WARRANTOR] [int] NULL,
[WRH] [int] NOT NULL,
[DSPUNIT] [int] NOT NULL,
[DSPWRH] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PROVIDER] [int] NOT NULL,
[MODNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[INVNO] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL,
[SENDER] [int] NULL,
[CHECKER] [int] NULL,
[PRNTIME] [datetime] NULL,
[ASSISTANT] [int] NULL,
[PAYSTAT] [smallint] NOT NULL CONSTRAINT [DF__RTL__PAYSTAT__6392AE65] DEFAULT (0),
[SRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NULL,
[OFFLINESTAT] [smallint] NOT NULL CONSTRAINT [DF__RTL__OFFLINESTAT__6D9119EB] DEFAULT (0),
[GFTPRO] [int] NULL,
[GFTPROWRH] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RTL] WITH NOCHECK ADD CONSTRAINT [RTL_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[RTL] ADD CONSTRAINT [PK__RTL__0F824689] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
