CREATE TABLE [dbo].[jxccenter2]
(
[Code] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BarCode] [char] (13) COLLATE Chinese_PRC_CI_AS NULL,
[Name] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Unit] [char] (4) COLLATE Chinese_PRC_CI_AS NULL,
[Size] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[CargoNo] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Produce] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[DepNo] [char] (6) COLLATE Chinese_PRC_CI_AS NULL,
[GrpNo] [char] (6) COLLATE Chinese_PRC_CI_AS NULL,
[Class] [char] (6) COLLATE Chinese_PRC_CI_AS NULL,
[Supply] [char] (8) COLLATE Chinese_PRC_CI_AS NULL,
[Grade] [char] (8) COLLATE Chinese_PRC_CI_AS NULL,
[Package] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[LblNo] [char] (6) COLLATE Chinese_PRC_CI_AS NULL,
[Label] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[JhDate] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[KeepMonth] [int] NULL,
[Season] [char] (6) COLLATE Chinese_PRC_CI_AS NULL,
[Weight] [money] NULL,
[JPrice] [money] NULL,
[Price] [money] NULL,
[HyPrice] [money] NULL,
[PfPrice] [money] NULL,
[HCount] [numeric] (8, 2) NULL,
[LCount] [numeric] (8, 2) NULL,
[JTaxRate] [smallint] NULL,
[XTaxRate] [smallint] NULL,
[CodeType] [char] (1) COLLATE Chinese_PRC_CI_AS NULL,
[Mode] [char] (1) COLLATE Chinese_PRC_CI_AS NULL,
[TsBz] [char] (1) COLLATE Chinese_PRC_CI_AS NULL,
[PreCode] [char] (13) COLLATE Chinese_PRC_CI_AS NULL,
[SizeNo] [char] (3) COLLATE Chinese_PRC_CI_AS NULL,
[SizeName] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[ColorNo] [char] (2) COLLATE Chinese_PRC_CI_AS NULL,
[ColorName] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[tjcode] [char] (12) COLLATE Chinese_PRC_CI_AS NULL,
[type] [char] (1) COLLATE Chinese_PRC_CI_AS NULL,
[jhperson] [char] (8) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
