CREATE TABLE [dbo].[PROCEXEC]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BOCLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PROCEXEC__BOCLS__2CA26C2E] DEFAULT ('一般'),
[TASKNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL,
[BGNTIME] [datetime] NULL,
[ENDTIME] [datetime] NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__PROCEXEC__FILDAT__2D969067] DEFAULT (getdate()),
[CHKTIME] [datetime] NULL,
[CHKEMP] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[SUBJECT] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[ALGAVGTAG] [varchar] (255) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[SRC] [int] NOT NULL CONSTRAINT [DF__PROCEXEC__SRC__2E8AB4A0] DEFAULT (1),
[PRNTIME] [datetime] NULL,
[MODE] [smallint] NOT NULL,
[SNDTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROCEXEC] ADD CONSTRAINT [PK__PROCEXEC__2F7ED8D9] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
