CREATE TABLE [dbo].[STOREWRH]
(
[STOREGID] [int] NOT NULL,
[WRHGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STOREWRH] ADD CONSTRAINT [PK__STOREWRH__629E8A2C] PRIMARY KEY CLUSTERED  ([STOREGID], [WRHGID]) ON [PRIMARY]
GO
