CREATE TABLE [dbo].[BLPREORDMDADTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[MDAFILENAME] [char] (255) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MDAUUID] [char] (64) COLLATE Chinese_PRC_CI_AS NULL,
[MDANAME] [char] (120) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BLPREORDMDADTL] ADD CONSTRAINT [PK__BLPREORDMDADTL__7C74361F] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
