CREATE TABLE [dbo].[PS3BIRTHDAYNSCORE]
(
[UUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NSCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [d_PS3BIRTHDAYNSCORE_1] DEFAULT (1),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3BIRTHDAYNSCORE] ADD CONSTRAINT [PK__PS3BIRTHDAYNSCOR__3FF86520] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
