CREATE TABLE [dbo].[PCKDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__PCKDTL__STAT__5D6271BE] DEFAULT (0),
[GDGID] [int] NOT NULL,
[QTY] [money] NOT NULL CONSTRAINT [DF__PCKDTL__QTY__5E5695F7] DEFAULT (0),
[TOTAL] [money] NOT NULL CONSTRAINT [DF__PCKDTL__TOTAL__5F4ABA30] DEFAULT (0),
[CKNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[CKLINE] [int] NULL,
[SUBWRH] [int] NULL,
[InPrc] [money] NOT NULL CONSTRAINT [DF__pckdtl__InPrc__267F7E84] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PCKDTL] ADD CONSTRAINT [PK__PCKDTL__6E2152BE] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [pckdtl_gdgid] ON [dbo].[PCKDTL] ([GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
