CREATE TABLE [dbo].[EXCHANGESTATE]
(
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SVRCURVER] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[POSCURVER] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[STAT] [char] (20) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EXCHANGESTATE] ADD CONSTRAINT [PK__EXCHANGESTATE__42797158] PRIMARY KEY CLUSTERED  ([POSNO], [CLS]) ON [PRIMARY]
GO
