CREATE TABLE [dbo].[SETTLEDEPTWRH]
(
[WRHGID] [int] NOT NULL,
[CODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SETTLEDEPTWRH] ADD CONSTRAINT [PK__SETTLEDEPTWRH__0E7C4113] PRIMARY KEY CLUSTERED  ([CODE], [WRHGID]) ON [PRIMARY]
GO
