CREATE TABLE [dbo].[MODULERIGHT]
(
[NO] [int] NOT NULL,
[MODULE] [smallint] NOT NULL,
[FUNCTION] [smallint] NULL,
[NAME] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[TABLENAME] [char] (32) COLLATE Chinese_PRC_CI_AS NULL,
[FIELDNAME] [char] (32) COLLATE Chinese_PRC_CI_AS NULL,
[SPEC] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[FORMNAME] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[FORMCAPTION] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[COMPONENTNAME] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[COMPONENTCAPTION] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[RIGHTALL] [smallint] NOT NULL CONSTRAINT [DF__modulerig__RIGHT__32ED1505] DEFAULT (0),
[COMPONENTTYPE] [int] NOT NULL CONSTRAINT [DF__MODULERIG__COMPO__3299A5F8] DEFAULT (1),
[NO2] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__MODULERIGHT__NO2__338DCA31] DEFAULT ('-'),
[DISPLAY] [smallint] NOT NULL CONSTRAINT [DF__MODULERIG__DISPL__3481EE6A] DEFAULT (1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MODULERIGHT] ADD CONSTRAINT [PK__MODULERIGHT__6505F58B] PRIMARY KEY CLUSTERED  ([NO], [NO2]) ON [PRIMARY]
GO
