CREATE TABLE [dbo].[NCRMCARDDESHST]
(
[CARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARRIER] [int] NOT NULL CONSTRAINT [DF__NCRMCARDD__CARRI__0962863B] DEFAULT (1),
[OLDBAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCRMCARDD__OLDBA__0A56AA74] DEFAULT (0),
[OCCUR] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCRMCARDD__OCCUR__0B4ACEAD] DEFAULT (0),
[NUM] [char] (26) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCRMCARDDESHST] ADD CONSTRAINT [PK__NCRMCARDDESHST__0C3EF2E6] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
