CREATE TABLE [dbo].[TALLYTYPE]
(
[CODE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[CREATOR] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__TALLYTYPE__CREAT__0B8B9126] DEFAULT ('未知[-]'),
[CREATETIME] [datetime] NOT NULL CONSTRAINT [DF__TALLYTYPE__CREAT__0C7FB55F] DEFAULT (getdate()),
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__TALLYTYPE__LSTUP__0D73D998] DEFAULT ('未知[-]'),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__TALLYTYPE__LSTUP__0E67FDD1] DEFAULT (getdate()),
[ORDTAG] [smallint] NOT NULL CONSTRAINT [DF__TALLYTYPE__ORDTA__0F5C220A] DEFAULT (0),
[GDGID] [int] NOT NULL CONSTRAINT [DF__TALLYTYPE__GDGID__10504643] DEFAULT (1),
[SENDTIME] [datetime] NULL,
[SRC] [int] NOT NULL CONSTRAINT [DF__TALLYTYPE__SRC__11446A7C] DEFAULT (1),
[INEFFECT] [int] NOT NULL CONSTRAINT [DF__TALLYTYPE__INEFF__12388EB5] DEFAULT (1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TALLYTYPE] ADD CONSTRAINT [PK__TALLYTYPE__132CB2EE] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
