CREATE TABLE [dbo].[GFTPRMSNDGIFT]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[RCODE] [char] (18) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GROUPID] [int] NOT NULL,
[GFTGID] [int] NOT NULL,
[PAYPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMSND__PAYPR__08F7A690] DEFAULT (0),
[COSTPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMSND__COSTP__09EBCAC9] DEFAULT (0),
[QTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMSNDGI__QTY__0ADFEF02] DEFAULT (0),
[BCKQTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMSND__BCKQT__0BD4133B] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GFTPRMSNDGIFT] ADD CONSTRAINT [PK__GFTPRMSNDGIFT__08038257] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
