CREATE TABLE [dbo].[SALEDIF]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__SALEDIF__FILDATE__58939B00] DEFAULT (getdate()),
[FILLER] [int] NOT NULL CONSTRAINT [DF__SALEDIF__FILLER__5987BF39] DEFAULT (1),
[CHECKER] [int] NOT NULL CONSTRAINT [DF__SALEDIF__CHECKER__5A7BE372] DEFAULT (1),
[VENDOR] [int] NOT NULL CONSTRAINT [DF__SALEDIF__VENDOR__5B7007AB] DEFAULT (1),
[BILLTO] [int] NOT NULL CONSTRAINT [DF__SALEDIF__BILLTO__5C642BE4] DEFAULT (1),
[TOTAL] [money] NOT NULL CONSTRAINT [DF__SALEDIF__TOTAL__5D58501D] DEFAULT (0),
[TAX] [money] NOT NULL CONSTRAINT [DF__SALEDIF__TAX__5E4C7456] DEFAULT (0),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__SALEDIF__STAT__5F40988F] DEFAULT (0),
[FINISHED] [smallint] NOT NULL CONSTRAINT [DF__SALEDIF__FINISHE__6034BCC8] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__SALEDIF__RECCNT__6128E101] DEFAULT (0),
[SRC] [int] NOT NULL CONSTRAINT [DF__SALEDIF__SRC__621D053A] DEFAULT (1),
[SRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SALEDIF] ADD CONSTRAINT [PK__SALEDIF__579F76C7] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [SALEDIF_FILDATE] ON [dbo].[SALEDIF] ([FILDATE]) ON [PRIMARY]
GO
