CREATE TABLE [dbo].[GFTPRMRULELMT]
(
[RCODE] [char] (18) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LMTNO] [int] NOT NULL,
[NOTE] [char] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GFTPRMRULELMT] ADD CONSTRAINT [PK__GFTPRMRULELMT__5FF590FD] PRIMARY KEY CLUSTERED  ([RCODE], [LMTNO]) ON [PRIMARY]
GO
