CREATE TABLE [dbo].[NTAXSORTADJDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[OLDTAXSORT] [int] NULL,
[NEWTAXSORT] [int] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NTAXSORTADJDTL] ADD CONSTRAINT [PK__NTAXSORT__CC5F643F742476A1] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) ON [PRIMARY]
GO
