CREATE TABLE [dbo].[VOUCHERLAUNCHSCOPETEMPLATE]
(
[CODE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (60) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ESTABLISHTIME] [datetime] NOT NULL CONSTRAINT [DF__VOUCHERLA__ESTAB__70450012] DEFAULT (getdate()),
[ASTART] [datetime] NOT NULL,
[AFINISH] [datetime] NOT NULL,
[DEF] [smallint] NOT NULL CONSTRAINT [DF__VOUCHERLAUN__DEF__7139244B] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERLAUNCHSCOPETEMPLATE] ADD CONSTRAINT [PK__VOUCHERLAUNCHSCO__722D4884] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
