CREATE TABLE [dbo].[ORDDTLDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[STOREGID] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[QTY] [money] NOT NULL,
[ASNQTY] [money] NULL CONSTRAINT [DF__ORDDTLDTL__ASNQT__074E89E9] DEFAULT (0),
[ORDNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ORDLINE] [int] NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [orddtldtlline] ON [dbo].[ORDDTLDTL] ([NUM], [LINE]) ON [PRIMARY]
GO
