CREATE TABLE [dbo].[BRANDEMP]
(
[EMPGID] [int] NOT NULL,
[BRANDCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BRANDEMP] ADD CONSTRAINT [PK__BRANDEMP__05F44A0F] PRIMARY KEY CLUSTERED  ([EMPGID], [BRANDCODE]) ON [PRIMARY]
GO
