CREATE TABLE [dbo].[LSDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SETTLENO] [int] NULL,
[GDGID] [int] NULL,
[QTYLS] [money] NULL CONSTRAINT [DF__LSDTL__QTYLS__0E8400AF] DEFAULT (0),
[AMTLS] [money] NULL CONSTRAINT [DF__LSDTL__AMTLS__0F7824E8] DEFAULT (0),
[INPRC] [money] NULL CONSTRAINT [DF__LSDTL__INPRC__106C4921] DEFAULT (0),
[RTLPRC] [money] NULL CONSTRAINT [DF__LSDTL__RTLPRC__11606D5A] DEFAULT (0),
[VALIDDATE] [datetime] NULL,
[subwrh] [int] NULL,
[COST] [money] NOT NULL CONSTRAINT [DF__LSDTL__COST__355EA205] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LSDTL] ADD CONSTRAINT [PK__LSDTL__090A5324] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [lsdtl_gdgid] ON [dbo].[LSDTL] ([GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LSDTL] ADD CONSTRAINT [在损耗单中商品不能重复] UNIQUE NONCLUSTERED  ([NUM], [GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
