CREATE TABLE [dbo].[TK_NOWNERINFO]
(
[CLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OWNERGID] [int] NOT NULL,
[SERIALNO] [varchar] (16) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PIN] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRC] [int] NOT NULL,
[RCV] [int] NOT NULL,
[SNDTIME] [datetime] NOT NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [int] NOT NULL CONSTRAINT [DF__TK_NOWNERI__TYPE__4F0A30C6] DEFAULT (0),
[NSTAT] [int] NOT NULL CONSTRAINT [DF__TK_NOWNER__NSTAT__4FFE54FF] DEFAULT (0),
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
