CREATE TABLE [dbo].[DMDPRMDTLDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[ITEM] [smallint] NOT NULL,
[SETTLENO] [int] NOT NULL,
[START] [datetime] NOT NULL CONSTRAINT [DF__DMDPRMDTL__START__322EC64D] DEFAULT ('1899.12.30 00:00:00'),
[FINISH] [datetime] NOT NULL CONSTRAINT [DF__DMDPRMDTL__FINIS__3322EA86] DEFAULT ('9999.12.31 23:59:59'),
[CYCLE] [datetime] NOT NULL CONSTRAINT [DF__DMDPRMDTL__CYCLE__34170EBF] DEFAULT ('1899.12.30 00:00:00'),
[CSTART] [datetime] NOT NULL CONSTRAINT [DF__DMDPRMDTL__CSTAR__350B32F8] DEFAULT ('1899.12.30 00:00:00'),
[CFINISH] [datetime] NOT NULL CONSTRAINT [DF__DMDPRMDTL__CFINI__35FF5731] DEFAULT ('9999.12.31 23:59:59'),
[CSPEC] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[QTYLO] [money] NOT NULL CONSTRAINT [DF__DMDPRMDTL__QTYLO__36F37B6A] DEFAULT (0),
[QTYHI] [money] NOT NULL CONSTRAINT [DF__DMDPRMDTL__QTYHI__37E79FA3] DEFAULT (99999999),
[PRICE] [money] NULL,
[DISCOUNT] [decimal] (5, 2) NULL,
[GFTGID] [int] NULL,
[GFTQTY] [money] NULL,
[GFTPER] [money] NULL,
[GFTTYPE] [smallint] NULL,
[INPRC] [money] NULL,
[PRMTAG] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[MBRPRC] [money] NULL,
[PRMLWTPRC] [decimal] (24, 4) NULL,
[CONFIRM] [smallint] NULL CONSTRAINT [DF__DMDPRMDTL__CONFI__72CA04FD] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DMDPRMDTLDTL] ADD CONSTRAINT [PK__DMDPRMDTLDTL__4A18FC72] PRIMARY KEY CLUSTERED  ([NUM], [LINE], [ITEM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
