CREATE TABLE [dbo].[CRMCARDH]
(
[CARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BYTIME] [datetime] NOT NULL CONSTRAINT [DF__CRMCARDH__BYTIME__3CE22A41] DEFAULT ('2001.1.1'),
[BALANCE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCARDH__BALANC__3DD64E7A] DEFAULT (0),
[CONSUME] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCARDH__CONSUM__3ECA72B3] DEFAULT (0),
[SCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCARDH__SCORE__3FBE96EC] DEFAULT (0),
[BANTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCARDH__BANTOT__40B2BB25] DEFAULT (0),
[SCRTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCARDH__SCRTOT__41A6DF5E] DEFAULT (0),
[CARDTYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARRIER] [int] NOT NULL CONSTRAINT [DF__CRMCARDH__CARRIE__429B0397] DEFAULT (1),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__CRMCARDH__STAT__438F27D0] DEFAULT (0),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__CRMCARDH__LSTUPD__44834C09] DEFAULT (getdate()),
[VERSION] [char] (9) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMCARDH__VERSIO__45777042] DEFAULT ('020000000'),
[MAKETIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMCARDH] ADD CONSTRAINT [PK__CRMCARDH__466B947B] PRIMARY KEY CLUSTERED  ([CARDNUM], [CARRIER]) ON [PRIMARY]
GO
