CREATE TABLE [dbo].[NCARDTYPE]
(
[NAME] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARDTYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NCARDTYPE__CARDT__4456CCD2] DEFAULT ('折扣卡'),
[DISCOUNT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NCARDTYPE__DISCO__454AF10B] DEFAULT (100),
[PARVALUE] [decimal] (24, 2) NULL,
[CARDCOST] [decimal] (24, 4) NULL,
[CARDUSAGE] [smallint] NOT NULL CONSTRAINT [DF__NCARDTYPE__CARDU__463F1544] DEFAULT (0),
[MEDIUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MSPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCARDTYPE__MSPRC__4733397D] DEFAULT (0),
[VSPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCARDTYPE__VSPRC__48275DB6] DEFAULT (0),
[MPPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCARDTYPE__MPPRC__491B81EF] DEFAULT (0),
[VPPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCARDTYPE__VPPRC__4A0FA628] DEFAULT (0),
[MCPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCARDTYPE__MCPRC__4B03CA61] DEFAULT (0),
[VCPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCARDTYPE__VCPRC__4BF7EE9A] DEFAULT (0),
[VALIDPRD] [int] NULL,
[ABORTPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCARDTYPE__ABORT__4CEC12D3] DEFAULT (0),
[BACKPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCARDTYPE__BACKP__4DE0370C] DEFAULT (0),
[RESUMEPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCARDTYPE__RESUM__4ED45B45] DEFAULT (0),
[TRANRATE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCARDTYPE__TRANR__4FC87F7E] DEFAULT (0),
[Src] [int] NOT NULL,
[ID] [int] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[RCV] [int] NULL,
[RCVTIME] [datetime] NULL,
[FRCCHK] [smallint] NOT NULL,
[NTYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCARDTYPE] ADD CONSTRAINT [PK__NCARDTYPE__4362A899] PRIMARY KEY CLUSTERED  ([ID], [Src]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
