CREATE TABLE [dbo].[WEBSBUY2]
(
[UUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SHOPCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSID] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[CODE] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDCOLOR] [char] (32) COLLATE Chinese_PRC_CI_AS NULL,
[GDSIZE] [char] (32) COLLATE Chinese_PRC_CI_AS NULL,
[QTY] [decimal] (24, 4) NOT NULL,
[PRICE] [decimal] (24, 4) NOT NULL,
[REALPRICE] [decimal] (24, 4) NOT NULL,
[COSTPRICE] [decimal] (24, 4) NULL,
[AMOUNT] [decimal] (24, 4) NOT NULL,
[REALAMT] [decimal] (24, 4) NOT NULL,
[FAVAMOUNT] [decimal] (24, 4) NOT NULL,
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[BILL] [varchar] (32) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WEBSBUY2] ADD CONSTRAINT [PK__WEBSBUY2__2B48F7AB] PRIMARY KEY CLUSTERED  ([SHOPCODE], [FLOWNO], [POSID], [ITEMNO]) ON [PRIMARY]
GO
