CREATE TABLE [dbo].[EMPMACSET]
(
[EMPCODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLIENTNAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MACADDR] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMPMACSET] ADD CONSTRAINT [PK__EMPMACSET__3EE5DC04] PRIMARY KEY CLUSTERED  ([EMPCODE], [MACADDR]) ON [PRIMARY]
GO
