CREATE TABLE [dbo].[CRMSCOREPRIZEPRZDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[NAME] [char] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[QTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMSCOREPRI__QTY__21F929DB] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMSCOREPRIZEPRZDTL] ADD CONSTRAINT [PK__CRMSCOREPRIZEPRZ__22ED4E14] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
