CREATE TABLE [dbo].[PS3SCONOTSCORESORT]
(
[SORT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3SCONOTSCORESORT] ADD CONSTRAINT [PK__PS3SCONOTSCORESO__173C6F9D] PRIMARY KEY CLUSTERED  ([SORT]) ON [PRIMARY]
GO
