CREATE TABLE [dbo].[ALCADJLACDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ALCADJLACDTL] ADD CONSTRAINT [PK__ALCADJLACDTL__61562B8F] PRIMARY KEY CLUSTERED  ([NUM], [STOREGID]) ON [PRIMARY]
GO
