CREATE TABLE [dbo].[FAUSERSTYLOG]
(
[USERGID] [int] NOT NULL,
[STYGID] [int] NOT NULL,
[BDATE] [datetime] NOT NULL CONSTRAINT [DF__FAUSERSTY__BDATE__1B9C9FC7] DEFAULT (getdate()),
[EDATE] [datetime] NOT NULL CONSTRAINT [DF__FAUSERSTY__EDATE__1C90C400] DEFAULT (getdate()),
[NO] [int] NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__FAUSERSTY__LSTUP__1D84E839] DEFAULT (getdate()),
[LASTMODIFYOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FAUSERSTYLOG] ADD CONSTRAINT [PK__FAUSERSTYLOG__1E790C72] PRIMARY KEY CLUSTERED  ([USERGID], [STYGID], [BDATE], [EDATE]) ON [PRIMARY]
GO
