CREATE TABLE [dbo].[CRMDATAEXGWEBEMP]
(
[GID] [int] NOT NULL,
[ISWEBUSER] [smallint] NOT NULL CONSTRAINT [DF__CRMDATAEX__ISWEB__3B3C3AF6] DEFAULT (0),
[WEBPWD] [varchar] (32) COLLATE Chinese_PRC_CI_AS NULL,
[STARTDATE] [datetime] NULL,
[ENDDATE] [datetime] NULL,
[INEFFECT] [smallint] NOT NULL CONSTRAINT [DF__CRMDATAEX__INEFF__3C305F2F] DEFAULT (0),
[STORE] [varchar] (32) COLLATE Chinese_PRC_CI_AS NULL,
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL CONSTRAINT [DF__CRMDATAEXGW__SRC__3D248368] DEFAULT (1),
[SNDTIME] [datetime] NULL,
[CREATETIME] [datetime] NOT NULL CONSTRAINT [DF__CRMDATAEX__CREAT__3E18A7A1] DEFAULT (getdate()),
[CREATOR] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__CRMDATAEX__LSTUP__3F0CCBDA] DEFAULT (getdate()),
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMDATAEX__LSTUP__4000F013] DEFAULT ('未知[-]'),
[SYSUUID] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMDATAEX__SYSUU__40F5144C] DEFAULT ('-'),
[FSENDTIME] [datetime] NOT NULL,
[FSRCORG] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FDESTORG] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMDATAEXGWEBEMP] ADD CONSTRAINT [PK__CRMDATAEXGWEBEMP__41E93885] PRIMARY KEY CLUSTERED  ([FSRCORG], [FDESTORG], [FSENDTIME], [GID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_CRMDATAEXGWEBEMP_FST] ON [dbo].[CRMDATAEXGWEBEMP] ([FSENDTIME]) ON [PRIMARY]
GO
