CREATE TABLE [dbo].[BILLTOADJ]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[SRC] [int] NOT NULL,
[FILLER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__BILLTOADJ__FILLE__4CE91741] DEFAULT ('未知[-]'),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__BILLTOADJ__FILDA__4DDD3B7A] DEFAULT (getdate()),
[CHECKER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__BILLTOADJ__RECCN__4ED15FB3] DEFAULT (0),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__BILLTOADJ__STAT__4FC583EC] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[LAUNCH] [datetime] NOT NULL CONSTRAINT [DF__BILLTOADJ__LAUNC__50B9A825] DEFAULT (getdate()),
[GoOnChk] [int] NOT NULL CONSTRAINT [DF__BILLTOADJ__GoOnC__51ADCC5E] DEFAULT (0),
[LSTMODIFIER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__BILLTOADJ__LSTMO__52A1F097] DEFAULT ('未知[-]'),
[LstUpdTime] [datetime] NOT NULL CONSTRAINT [DF__BILLTOADJ__LstUp__539614D0] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BILLTOADJ] ADD CONSTRAINT [PK__BILLTOADJ__548A3909] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
