CREATE TABLE [dbo].[XF]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NULL,
[FILDATE] [datetime] NULL CONSTRAINT [DF__XF__FILDATE__20A2B0EA] DEFAULT (getdate()),
[FILLER] [int] NULL,
[CHECKER] [int] NULL,
[FROMWRH] [int] NULL,
[TOWRH] [int] NULL,
[AMT] [money] NULL CONSTRAINT [DF__XF__AMT__2196D523] DEFAULT (0),
[STAT] [smallint] NULL CONSTRAINT [DF__XF__STAT__228AF95C] DEFAULT (0),
[RECCNT] [int] NULL CONSTRAINT [DF__XF__RECCNT__237F1D95] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[PRNTIME] [datetime] NULL,
[INVCOST] [money] NOT NULL CONSTRAINT [DF__XF__INVCOST__55A21FBC] DEFAULT (0),
[OUTEMP] [int] NULL,
[OUTDATE] [datetime] NULL,
[INEMP] [int] NULL,
[INDATE] [datetime] NULL,
[TAX] [money] NOT NULL CONSTRAINT [DF__XF__TAX__0D50B0AB] DEFAULT (0),
[SrcStkinNum] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[AFLAG] [smallint] NULL CONSTRAINT [DF__XF__AFLAG__75A671A8] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[XF] WITH NOCHECK ADD CONSTRAINT [XF_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[XF] ADD CONSTRAINT [PK__XF__44EA3301] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FILDATE] ON [dbo].[XF] ([FILDATE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
