CREATE TABLE [dbo].[GDBIND]
(
[BINDGID] [int] NOT NULL,
[EGID] [int] NOT NULL,
[QTY] [money] NOT NULL,
[EQPCSTR] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__GDBIND__EQPCSTR__34CD9DDB] DEFAULT ('1*1')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GDBIND] ADD CONSTRAINT [PK__GDBIND__5D2BD0E6] PRIMARY KEY CLUSTERED  ([BINDGID], [EGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
