CREATE TABLE [dbo].[tCsbm]
(
[Code] [varchar] (8) COLLATE Chinese_PRC_CI_AS NOT NULL,
[Name] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Zip] [varchar] (4) COLLATE Chinese_PRC_CI_AS NULL,
[Addr] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LPerson] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Property] [varchar] (2) COLLATE Chinese_PRC_CI_AS NULL,
[Tel] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Fax] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Telex] [varchar] (12) COLLATE Chinese_PRC_CI_AS NULL,
[PostCode] [varchar] (6) COLLATE Chinese_PRC_CI_AS NULL,
[Bank] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[BankNo] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[TaxNo] [varchar] (15) COLLATE Chinese_PRC_CI_AS NULL,
[Comment] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[LxFlag] [varchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[DiscRate] [int] NULL,
[Mode] [varchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[Zch] [varchar] (26) COLLATE Chinese_PRC_CI_AS NULL,
[ZcZj] [varchar] (14) COLLATE Chinese_PRC_CI_AS NULL,
[CsBzj] [varchar] (14) COLLATE Chinese_PRC_CI_AS NULL,
[CsYrr] [varchar] (8) COLLATE Chinese_PRC_CI_AS NULL,
[CsSpr] [varchar] (8) COLLATE Chinese_PRC_CI_AS NULL,
[JyQsRq] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[JyZzRq] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Lxr1] [varchar] (8) COLLATE Chinese_PRC_CI_AS NULL,
[Lxr2] [varchar] (8) COLLATE Chinese_PRC_CI_AS NULL,
[Lxr3] [varchar] (8) COLLATE Chinese_PRC_CI_AS NULL,
[Tel1] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Tel2] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Tel3] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Zw1] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Zw2] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Zw3] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Fld1] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Fld2] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Fld3] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Remark] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[CheckFlg] [varchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[JyFw] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[htdj] [float] NULL,
[htno] [varchar] (6) COLLATE Chinese_PRC_CI_AS NULL,
[ggfy] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[tjcode] [varchar] (12) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
