CREATE TABLE [dbo].[EPSSENDRTNTOTAL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STORE] [int] NOT NULL,
[STATE] [int] NOT NULL CONSTRAINT [DF__EPSSENDRT__STATE__28C7B9A9] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EPSSENDRTNTOTAL] ADD CONSTRAINT [PK__EPSSENDRTNTOTAL__29BBDDE2] PRIMARY KEY CLUSTERED  ([NUM], [STORE]) ON [PRIMARY]
GO
