CREATE TABLE [dbo].[STORESCHSORTGOODS]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SORTCODE] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[ISOPER] [int] NOT NULL,
[ISNECESSARY] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STORESCHSORTGOODS] ADD CONSTRAINT [PK__STORESCHSORTGOOD__1C0F3F0E] PRIMARY KEY CLUSTERED  ([NUM], [GDGID]) ON [PRIMARY]
GO
