CREATE TABLE [dbo].[NALCBYSTOREDTL]
(
[SRC] [int] NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ID] [int] NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[CASES] [decimal] (24, 4) NULL,
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NALCBYSTORE__QTY__71A26D48] DEFAULT (0),
[INVQTY] [decimal] (24, 4) NOT NULL,
[TOTAL] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NALCBYSTO__TOTAL__72969181] DEFAULT (0),
[TAX] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NALCBYSTORE__TAX__738AB5BA] DEFAULT (0),
[ASNQTY] [decimal] (24, 4) NULL CONSTRAINT [DF__NALCBYSTO__ASNQT__747ED9F3] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NALCBYSTOREDTL] ADD CONSTRAINT [PK__NALCBYSTOREDTL__7572FE2C] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) ON [PRIMARY]
GO
