CREATE TABLE [dbo].[CRMHOLDCARDNUM]
(
[CARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[CREATOR] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMHOLDCA__CREAT__588A44B6] DEFAULT ('未知[-]'),
[CREATETIME] [datetime] NOT NULL CONSTRAINT [DF__CRMHOLDCA__CREAT__597E68EF] DEFAULT (getdate()),
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMHOLDCA__LSTUP__5A728D28] DEFAULT ('未知[-]'),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__CRMHOLDCA__LSTUP__5B66B161] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMHOLDCARDNUM] ADD CONSTRAINT [PK__CRMHOLDCARDNUM__5C5AD59A] PRIMARY KEY CLUSTERED  ([CARDNUM]) ON [PRIMARY]
GO
