CREATE TABLE [dbo].[NGFTPRMRULELMT]
(
[RCV] [int] NOT NULL,
[ID] [int] NOT NULL,
[RCODE] [char] (18) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LMTNO] [int] NOT NULL,
[NOTE] [char] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NGFTPRMRULELMT] ADD CONSTRAINT [PK__NGFTPRMRULELMT__458D4A32] PRIMARY KEY CLUSTERED  ([RCV], [ID], [RCODE], [LMTNO]) ON [PRIMARY]
GO
