CREATE TABLE [dbo].[PROM]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__PROM__STAT__3A075444] DEFAULT (0),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__PROM__FILDATE__3AFB787D] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__PROM__LSTUPDTIME__3BEF9CB6] DEFAULT (getdate()),
[TOPIC] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STORESCOPE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[ASTART] [datetime] NOT NULL,
[AFINISH] [datetime] NOT NULL,
[CYCLE] [datetime] NULL,
[CSTART] [datetime] NULL,
[CFINISH] [datetime] NULL,
[CSPEC] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[PSETTLENO] [int] NULL,
[OCRTIME] [datetime] NOT NULL CONSTRAINT [DF__PROM__OCRTIME__3CE3C0EF] DEFAULT (getdate()),
[FIXRATIO] [decimal] (24, 4) NULL,
[GFTRATIO] [decimal] (24, 4) NULL,
[HASCOND] [int] NOT NULL CONSTRAINT [DF__PROM__HASCOND__3DD7E528] DEFAULT (0),
[EXPROM] [int] NOT NULL CONSTRAINT [DF__PROM__EXPROM__3ECC0961] DEFAULT (0),
[MONTHSETTLENO] [int] NOT NULL CONSTRAINT [DF__PROM__MONTHSETTL__2C4EFD21] DEFAULT (0),
[DLTPRICEPROM] [smallint] NOT NULL CONSTRAINT [DF__PROM__DLTPRICEPR__5EDA7CEE] DEFAULT (0),
[OVERWRITERULE] [smallint] NOT NULL CONSTRAINT [DF__PROM__OVERWRITER__264C0B08] DEFAULT (0),
[CALBYRTLPRC] [tinyint] NOT NULL CONSTRAINT [DF__PROM__CALBYRTLPR__76A8B035] DEFAULT (0),
[ONLYMEMBER] [tinyint] NOT NULL CONSTRAINT [DF__PROM__ONLYMEMBER__280B019F] DEFAULT (0),
[PRIORITY] [int] NOT NULL CONSTRAINT [DF__PROM__PRIORITY__1C2518FE] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROM] ADD CONSTRAINT [PK__PROM__3FC02D9A] PRIMARY KEY CLUSTERED  ([NUM], [CLS]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PROM_TOPIC] ON [dbo].[PROM] ([TOPIC]) ON [PRIMARY]
GO
