CREATE TABLE [dbo].[NCstMizeDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[GQTY] [money] NOT NULL,
[QTY] [money] NOT NULL,
[PRICE] [money] NOT NULL,
[GTOTAL] [money] NOT NULL,
[TOTAL] [money] NOT NULL,
[TAX] [money] NOT NULL,
[WRH] [int] NOT NULL CONSTRAINT [DF__NCstMizeDTL__WRH__7AA98739] DEFAULT (1),
[INPRC] [money] NOT NULL,
[RTLPRC] [money] NOT NULL,
[SUBWRH] [int] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCstMizeDTL] ADD CONSTRAINT [PK__NCstMizeDTL__1C1D2798] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
