CREATE TABLE [dbo].[POLYPRCPRMOCR]
(
[STOREGID] [int] NOT NULL,
[BILLNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLLINE] [int] NOT NULL,
[BILLITEM] [int] NOT NULL,
[TOPIC] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PRI] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__POLYPRCPRMO__PRI__41FFDDCC] DEFAULT (0),
[OCRTIME] [datetime] NOT NULL,
[DEPT] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VENDOR] [int] NULL,
[BRAND] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[START] [datetime] NOT NULL CONSTRAINT [DF__POLYPRCPR__START__42F40205] DEFAULT ('1899.12.30 00:00:00'),
[FINISH] [datetime] NOT NULL CONSTRAINT [DF__POLYPRCPR__FINIS__43E8263E] DEFAULT ('9999.12.31 23:59:59'),
[RTLPRCDISCNT] [decimal] (5, 2) NOT NULL CONSTRAINT [DF__POLYPRCPR__RTLPR__44DC4A77] DEFAULT (0),
[MBRPRCDISCNT] [decimal] (5, 2) NOT NULL CONSTRAINT [DF__POLYPRCPR__MBRPR__45D06EB0] DEFAULT (0),
[PREC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__POLYPRCPRM__PREC__46C492E9] DEFAULT (0.01),
[ROUNDTYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__POLYPRCPR__ROUND__47B8B722] DEFAULT ('四舍五入'),
[POLYPRIOR] [smallint] NOT NULL CONSTRAINT [DF__POLYPRCPR__POLYP__59F762EE] DEFAULT (0),
[PRIORITY] [int] NOT NULL CONSTRAINT [DF__POLYPRCPR__PRIOR__3525D0F2] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[POLYPRCPRMOCR] ADD CONSTRAINT [PK__POLYPRCPRMOCR__48ACDB5B] PRIMARY KEY CLUSTERED  ([STOREGID], [BILLNUM], [BILLLINE], [BILLITEM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_POLYPRCPRMOCR_RANGE] ON [dbo].[POLYPRCPRMOCR] ([STOREGID], [FINISH]) ON [PRIMARY]
GO
