CREATE TABLE [dbo].[TOURSCONSUMEDISDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDDIS] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__TOURSCONS__GDDIS__66EFD4AB] DEFAULT (0),
[REALAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__TOURSCONS__REALA__67E3F8E4] DEFAULT (0),
[DISTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__TOURSCONS__DISTO__68D81D1D] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TOURSCONSUMEDISDTL] ADD CONSTRAINT [PK__TOURSCONSUMEDISD__69CC4156] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
