CREATE TABLE [dbo].[VDRPAYPAYDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STORENO] [char] (64) COLLATE Chinese_PRC_CI_AS NULL,
[POSNO] [char] (64) COLLATE Chinese_PRC_CI_AS NULL,
[TMNLFTUR] [char] (64) COLLATE Chinese_PRC_CI_AS NULL,
[TENANTID] [char] (64) COLLATE Chinese_PRC_CI_AS NULL,
[UUID] [char] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[REFUUID] [char] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ORDNUM] [char] (96) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PAYCODE] [char] (64) COLLATE Chinese_PRC_CI_AS NULL,
[CHANNEL] [char] (64) COLLATE Chinese_PRC_CI_AS NULL,
[PAYNO] [char] (64) COLLATE Chinese_PRC_CI_AS NULL,
[AMOUNT] [decimal] (24, 2) NULL,
[STATUS] [smallint] NULL,
[CREATEDATE] [datetime] NULL,
[LATUPDDATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VDRPAYPAYDTL] ADD CONSTRAINT [PK__VDRPAYPAYDTL__4C4B8F71] PRIMARY KEY CLUSTERED  ([ORDNUM]) ON [PRIMARY]
GO
