CREATE TABLE [dbo].[VOUCHERBCKSTGRCVDTL2]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[VOUCHERNUM] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VOUCHERTYPE] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[AMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__VOUCHERBC__AMOUN__6DBD9922] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERBCKSTGRCVDTL2] ADD CONSTRAINT [PK__VOUCHERBCKSTGRCV__6EB1BD5B] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
