CREATE TABLE [dbo].[GFTPRMBCKDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GROUPID] [int] NULL,
[RCODE] [char] (18) COLLATE Chinese_PRC_CI_AS NULL,
[GFTGID] [int] NOT NULL,
[SRCQTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMBCK__SRCQT__1DF2C376] DEFAULT (0),
[BCKQTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMBCK__BCKQT__1EE6E7AF] DEFAULT (0),
[QTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMBCKDT__QTY__1FDB0BE8] DEFAULT (0),
[AMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMBCKDT__AMT__20CF3021] DEFAULT (0),
[BCKAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMBCK__BCKAM__21C3545A] DEFAULT (0),
[GFTPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMBCK__GFTPR__22B77893] DEFAULT (0),
[REALGFTPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMBCK__REALG__23AB9CCC] DEFAULT (0),
[RULEBCKCNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__gftprmbck__RULEB__5CCF0B8F] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GFTPRMBCKDTL] ADD CONSTRAINT [PK__GFTPRMBCKDTL__1CFE9F3D] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
