CREATE TABLE [dbo].[FAVDRPT]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[BVDRGID] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[BGDGID] [int] NOT NULL,
[FAVTYPE] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FAVRATE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__FAVDRPT__FAVRATE__5B8843A0] DEFAULT (0),
[FAVAMOUNT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__FAVDRPT__FAVAMOU__5C7C67D9] DEFAULT (0),
[FAVPAY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__FAVDRPT__FAVPAY__5D708C12] DEFAULT (0),
[PROMCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[PROMNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[PROMLINE] [int] NULL,
[BCSTGID] [int] NOT NULL CONSTRAINT [DF__FAVDRPT__BCSTGID__6A957D06] DEFAULT (1),
[LSTUPDTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FAVDRPT] ADD CONSTRAINT [PK__FAVDRPT__6B89A13F] PRIMARY KEY CLUSTERED  ([ASTORE], [ASETTLENO], [ADATE], [BVDRGID], [BWRH], [BGDGID], [BCSTGID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX1] ON [dbo].[FAVDRPT] ([ADATE], [BVDRGID], [BWRH], [BGDGID]) ON [PRIMARY]
GO
