CREATE TABLE [dbo].[CRMCONSCOREDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[OCRDATE] [datetime] NOT NULL,
[AMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCONSCO__AMOUN__3F898CC2] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMCONSCOREDTL] ADD CONSTRAINT [PK__CRMCONSCOREDTL__407DB0FB] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
