CREATE TABLE [dbo].[rb_BUY2]
(
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[GID] [int] NOT NULL,
[QTY] [money] NOT NULL CONSTRAINT [DF__rb_BUY2__QTY__2C7783A5] DEFAULT (0),
[INPRC] [money] NOT NULL CONSTRAINT [DF__rb_BUY2__INPRC__2D6BA7DE] DEFAULT (0),
[PRICE] [money] NOT NULL CONSTRAINT [DF__rb_BUY2__PRICE__2E5FCC17] DEFAULT (0),
[REALAMT] [money] NOT NULL CONSTRAINT [DF__rb_BUY2__REALAMT__2F53F050] DEFAULT (0),
[FAVAMT] [money] NOT NULL CONSTRAINT [DF__rb_BUY2__FAVAMT__30481489] DEFAULT (0),
[TAG] [smallint] NOT NULL CONSTRAINT [DF__rb_BUY2__TAG__313C38C2] DEFAULT (0),
[QPCGID] [int] NULL,
[PRMTAG] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[ASSISTANT] [int] NULL,
[WRH] [int] NULL CONSTRAINT [DF__rb_BUY2__WRH__32305CFB] DEFAULT (1),
[INVNO] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[DEALER] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[rb_BUY2] ADD CONSTRAINT [PK__rb_BUY2__2B835F6C] PRIMARY KEY CLUSTERED  ([POSNO], [FLOWNO], [ITEMNO]) ON [PRIMARY]
GO
