CREATE TABLE [dbo].[POLYPROMOCR]
(
[STORE] [int] NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLLINE] [int] NOT NULL,
[DEPT] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VENDOR] [int] NULL,
[BRAND] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[ASTART] [datetime] NOT NULL,
[AFINISH] [datetime] NOT NULL,
[OCRTIME] [datetime] NOT NULL,
[DLTPRICEPROM] [smallint] NOT NULL CONSTRAINT [DF__POLYPROMO__DLTPR__5C49BFB4] DEFAULT (0),
[CALBYRTLPRC] [smallint] NOT NULL CONSTRAINT [DF__POLYPROMO__CALBY__5D3DE3ED] DEFAULT (0),
[PRIORITY] [int] NOT NULL CONSTRAINT [DF__POLYPROMO__PRIOR__302C11AB] DEFAULT (0),
[EXPROM] [int] NOT NULL CONSTRAINT [DF__POLYPROMO__EXPRO__76BE8A25] DEFAULT (0),
[PREC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__POLYPROMOC__PREC__5DD542CF] DEFAULT (1.0),
[ROUNDTYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__POLYPROMO__ROUND__5EC96708] DEFAULT ('四舍五入')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[POLYPROMOCR] ADD CONSTRAINT [PK__POLYPROMOCR__5E320826] PRIMARY KEY CLUSTERED  ([STORE], [CLS], [BILLNUM], [BILLLINE]) ON [PRIMARY]
GO
