CREATE TABLE [dbo].[EMPLOYEEGROUP_2009042802]
(
[GID] [int] NOT NULL IDENTITY(1, 1),
[NO] [smallint] NULL,
[NAME] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[RIGHT] [text] COLLATE Chinese_PRC_CI_AS NULL,
[EXTRARIGHT] [char] (255) COLLATE Chinese_PRC_CI_AS NULL,
[MEMO] [char] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
