CREATE TABLE [dbo].[CHARGECHK]
(
[NUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHARGEDATE] [datetime] NOT NULL,
[SALETYPE] [int] NOT NULL CONSTRAINT [DF__CHARGECHK__SALET__6C1E9E1C] DEFAULT (0),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__CHARGECHK__STAT__6D12C255] DEFAULT (0),
[FILLER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL,
[CHECKER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[LSTUPDTIME] [datetime] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SHOULDRCVTOTALT0] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CHARGECHK__SHOUL__6E06E68E] DEFAULT (0),
[SHOULDRCVTOTALT1] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CHARGECHK__SHOUL__6EFB0AC7] DEFAULT (0),
[RCVTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CHARGECHK__RCVTO__6FEF2F00] DEFAULT (0),
[OTHERTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CHARGECHK__OTHER__70E35339] DEFAULT (0),
[SNDTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CHARGECHK] ADD CONSTRAINT [PK__CHARGECHK__71D77772] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
