CREATE TABLE [dbo].[STKINBCK]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__STKINBCK__CLS__271AA44F] DEFAULT ('自营'),
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NULL,
[VENDOR] [int] NULL CONSTRAINT [DF__STKINBCK__VENDOR__280EC888] DEFAULT (1),
[VENDORNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[BILLTO] [int] NULL CONSTRAINT [DF__STKINBCK__BILLTO__2902ECC1] DEFAULT (1),
[OCRDATE] [datetime] NULL CONSTRAINT [DF__STKINBCK__OCRDAT__29F710FA] DEFAULT (getdate()),
[TOTAL] [money] NULL CONSTRAINT [DF__STKINBCK__TOTAL__2AEB3533] DEFAULT (0),
[TAX] [money] NULL CONSTRAINT [DF__STKINBCK__TAX__2BDF596C] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[FILDATE] [datetime] NULL CONSTRAINT [DF__STKINBCK__FILDAT__2CD37DA5] DEFAULT (getdate()),
[FILLER] [int] NULL CONSTRAINT [DF__STKINBCK__FILLER__2DC7A1DE] DEFAULT (1),
[CHECKER] [int] NULL CONSTRAINT [DF__STKINBCK__CHECKE__2EBBC617] DEFAULT (1),
[STAT] [smallint] NULL CONSTRAINT [DF__STKINBCK__STAT__2FAFEA50] DEFAULT (1),
[MODNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[PSR] [int] NULL CONSTRAINT [DF__STKINBCK__PSR__30A40E89] DEFAULT (1),
[RECCNT] [int] NULL CONSTRAINT [DF__STKINBCK__RECCNT__319832C2] DEFAULT (0),
[SRC] [int] NULL,
[SRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[FINISHED] [smallint] NULL CONSTRAINT [DF__STKINBCK__FINISH__328C56FB] DEFAULT (0),
[CHKDATE] [datetime] NULL,
[WRH] [int] NULL,
[PRECHECKER] [int] NULL CONSTRAINT [DF__stkinbck__PRECHE__729298CE] DEFAULT (0),
[PRECHKDATE] [datetime] NULL,
[GEN] [int] NULL,
[GENBILL] [char] (32) COLLATE Chinese_PRC_CI_AS NULL,
[GENCLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[GENNUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NULL,
[TAXRATELMT] [money] NULL,
[DEPT] [varchar] (13) COLLATE Chinese_PRC_CI_AS NULL,
[ModTime] [datetime] NOT NULL CONSTRAINT [DF__stkinbck__ModTim__780F73B5] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STKINBCK] WITH NOCHECK ADD CONSTRAINT [STKINBCK_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[STKINBCK] WITH NOCHECK ADD CONSTRAINT [退货单单号长度为10] CHECK NOT FOR REPLICATION ((len([num])=(10) AND left([num],(1))='0'))
GO
ALTER TABLE [dbo].[STKINBCK] ADD CONSTRAINT [PK__STKINBCK__1FB8AE52] PRIMARY KEY CLUSTERED  ([CLS], [NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FILDATE] ON [dbo].[STKINBCK] ([FILDATE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
