CREATE TABLE [dbo].[VOUCHERRECYCLE]
(
[NUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__VOUCHERREC__STAT__5CC8E2A1] DEFAULT (0),
[FROMSTORE] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__VOUCHERRE__FILDA__5DBD06DA] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__VOUCHERRE__FILLE__5EB12B13] DEFAULT ('未知[-]'),
[CHKDATE] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NULL,
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PRNTIME] [datetime] NULL,
[RECYCLEPATTERN] [int] NOT NULL CONSTRAINT [DF__VOUCHERRE__RECYC__5FA54F4C] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERRECYCLE] ADD CONSTRAINT [PK__VOUCHERRECYCLE__60997385] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_VOUCHERRECYCLE_NUM] ON [dbo].[VOUCHERRECYCLE] ([NUM]) ON [PRIMARY]
GO
