CREATE TABLE [dbo].[PS3_ONLINECNTRRATECOND]
(
[UUID] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PLATFORM] [varchar] (80) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CNTRNO] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[SALEAMT] [decimal] (24, 2) NOT NULL,
[ADDRATE] [decimal] (24, 2) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3_ONLINECNTRRATECOND] ADD CONSTRAINT [PK__PS3_ONLI__33AEB8212527A0AF] PRIMARY KEY CLUSTERED  ([UUID], [LINE]) ON [PRIMARY]
GO
