CREATE TABLE [dbo].[CRMMBRPROMTYPEBILL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__CRMMBRPROM__STAT__1503E57A] DEFAULT (0),
[STORE] [int] NOT NULL,
[SUBJCODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SUBJNAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ALLMBR] [smallint] NOT NULL CONSTRAINT [DF__CRMMBRPRO__ALLMB__15F809B3] DEFAULT (0),
[NOTE] [varchar] (200) COLLATE Chinese_PRC_CI_AS NULL,
[FILLER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL,
[CHECKER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[MODIFIER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMMBRPRO__MODIF__16EC2DEC] DEFAULT ('未知'),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__CRMMBRPRO__LSTUP__17E05225] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMMBRPROMTYPEBILL] ADD CONSTRAINT [PK__CRMMBRPROMTYPEBI__18D4765E] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
