CREATE TABLE [dbo].[RTLPRCADJLACDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RTLPRCADJLACDTL] ADD CONSTRAINT [PK__RTLPRCADJLACDTL__218E4A30] PRIMARY KEY CLUSTERED  ([NUM], [STOREGID]) ON [PRIMARY]
GO
