CREATE TABLE [dbo].[PROCESSGOODSJOBLAC]
(
[JOBID] [int] NOT NULL,
[STOREGID] [int] NOT NULL,
[GENBILLTYPE] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROCESSGOODSJOBLAC] ADD CONSTRAINT [PK__PROCESSGOODSJOBL__13ACA132] PRIMARY KEY CLUSTERED  ([JOBID], [STOREGID]) ON [PRIMARY]
GO
