CREATE TABLE [dbo].[PROCDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[RAW] [smallint] NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[QTY] [money] NOT NULL,
[TOTAL] [money] NOT NULL,
[CSTPRC] [money] NOT NULL,
[INPRC] [money] NOT NULL,
[RTLPRC] [money] NOT NULL,
[WRH] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROCDTL] ADD CONSTRAINT [PK__PROCDTL__7B7B4DDC] PRIMARY KEY CLUSTERED  ([NUM], [RAW], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
