CREATE TABLE [dbo].[PROMLOG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROMLOG] ADD CONSTRAINT [PK__PROMLOG__55AF6EB9] PRIMARY KEY CLUSTERED  ([NUM], [CLS], [STAT], [FILDATE]) ON [PRIMARY]
GO
