CREATE TABLE [dbo].[PRMRTNPNTAGMEXGDDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRMRTNPNTAGMEXGDDTL] ADD CONSTRAINT [PK__PRMRTNPNTAGMEXGD__66D16FC8] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PRMRTNPNTAGMEXGDDTL_GDGID] ON [dbo].[PRMRTNPNTAGMEXGDDTL] ([GDGID]) ON [PRIMARY]
GO
