CREATE TABLE [dbo].[EMPLOYEEGROUP]
(
[GID] [int] NOT NULL IDENTITY(1, 1),
[NO] [smallint] NULL,
[NAME] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[RIGHT] [text] COLLATE Chinese_PRC_CI_AS NULL,
[EXTRARIGHT] [char] (255) COLLATE Chinese_PRC_CI_AS NULL,
[MEMO] [char] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[SRC] [int] NOT NULL CONSTRAINT [DF__EMPLOYEEGRO__SRC__258CF0F9] DEFAULT (1)
) ON [PRIMARY]
GO
