CREATE TABLE [dbo].[NMXF]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[NUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FROMSTORE] [int] NOT NULL,
[TOSTORE] [int] NOT NULL,
[XCHGSTORE] [int] NOT NULL,
[WRH] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NMXF__FILDATE__3D4AA7E7] DEFAULT (getdate()),
[FILLER] [int] NOT NULL CONSTRAINT [DF__NMXF__FILLER__3E3ECC20] DEFAULT (1),
[FROMTOTAL] [money] NOT NULL CONSTRAINT [DF__NMXF__FROMTOTAL__3F32F059] DEFAULT (0),
[TOTOTAL] [money] NOT NULL CONSTRAINT [DF__NMXF__TOTOTAL__40271492] DEFAULT (0),
[FROMTAX] [money] NOT NULL CONSTRAINT [DF__NMXF__FROMTAX__411B38CB] DEFAULT (0),
[TOTAX] [money] NOT NULL CONSTRAINT [DF__NMXF__TOTAX__420F5D04] DEFAULT (0),
[FROMCOST] [money] NOT NULL CONSTRAINT [DF__NMXF__FROMCOST__4303813D] DEFAULT (0),
[TOCOST] [money] NOT NULL CONSTRAINT [DF__NMXF__TOCOST__43F7A576] DEFAULT (0),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__NMXF__STAT__44EBC9AF] DEFAULT (0),
[RECCNT] [int] NOT NULL,
[SNDTIME] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[RCV] [int] NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[FRCFLAG] [smallint] NOT NULL CONSTRAINT [DF__NMXF__FRCFLAG__45DFEDE8] DEFAULT (1),
[NNOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[MODNUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NULL,
[DMDNUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NMXF] ADD CONSTRAINT [PK__NMXF__3C5683AE] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
