CREATE TABLE [dbo].[VOUCHERACTBCKVOUGIVEDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[VOUCHERACTIVITY] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VOUCHERNUM] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VOUCHERAMT] [decimal] (24, 2) NOT NULL,
[ISRECYCLED] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERACTBCKVOUGIVEDTL] ADD CONSTRAINT [PK__VOUCHERACTBCKVOU__6A10FC82] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
