CREATE TABLE [dbo].[CRMCARDPHY]
(
[CARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PCODE] [char] (128) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMCARDPHY] ADD CONSTRAINT [PK__CRMCARDPHY__64F01B9B] PRIMARY KEY CLUSTERED  ([CARDNUM]) ON [PRIMARY]
GO
