CREATE TABLE [dbo].[PSCPH]
(
[GID] [int] NOT NULL,
[CODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CREATEDATE] [datetime] NOT NULL CONSTRAINT [DF__PSCPH__CREATEDAT__1063BE2E] DEFAULT (getdate()),
[FILLER] [int] NOT NULL CONSTRAINT [DF__PSCPH__FILLER__1157E267] DEFAULT (1),
[MODIFIER] [int] NOT NULL CONSTRAINT [DF__PSCPH__MODIFIER__124C06A0] DEFAULT (1),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__PSCPH__LSTUPDTIM__13402AD9] DEFAULT (getdate()),
[RAWRECCNT] [int] NOT NULL,
[PDTRECCNT] [int] NOT NULL,
[SndTime] [datetime] NULL,
[SRC] [int] NOT NULL CONSTRAINT [DF__PSCPH__SRC__14344F12] DEFAULT (1),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[PSCPTYPE] [smallint] NOT NULL CONSTRAINT [DF__PSCPH__PSCPTYPE__4310D03A] DEFAULT (0),
[STAT] [int] NOT NULL CONSTRAINT [DF__PSCPH__STAT__7918A687] DEFAULT (1),
[CYCLE] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSCPH] ADD CONSTRAINT [PK__PSCPH__02284B6B] PRIMARY KEY CLUSTERED  ([GID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
