CREATE TABLE [dbo].[PS3_ONLINECNTRCHECKAGMT]
(
[UUID] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PLATFORM] [varchar] (80) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CNTRNO] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CMONTH] [smallint] NOT NULL,
[GUARDSALEAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3_ONLIN__GUARD__28040D5A] DEFAULT ((0)),
[GUARDGPRATE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3_ONLIN__GUARD__28F83193] DEFAULT ((0))
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_OLCNTRCHECKAGMT_1] ON [dbo].[PS3_ONLINECNTRCHECKAGMT] ([UUID], [CMONTH]) ON [PRIMARY]
GO
