CREATE TABLE [dbo].[ONLINESALEORD]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__ONLINESALE__STAT__667575C8] DEFAULT (0),
[STOREGID] [int] NOT NULL,
[MBRGID] [int] NOT NULL,
[MBRCARDNO] [varchar] (60) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__ONLINESAL__FILDA__67699A01] DEFAULT (getdate()),
[FILLER] [int] NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__ONLINESAL__LSTUP__685DBE3A] DEFAULT (getdate()),
[LSTUPDOPER] [int] NOT NULL,
[CHKDATE] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[PRNTIME] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[BILLFROM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[DLVMODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[ORDNUM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[SRCNUM] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CLTNAME] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[CLTPHONE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[DLVERNAME] [varchar] (60) COLLATE Chinese_PRC_CI_AS NULL,
[DLVERPHONE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[ORDDATE] [datetime] NULL,
[SALEDATE] [datetime] NULL,
[RCVNAME] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[RCVPHONE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[RCVADDRESS] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ONLINESALEORD] ADD CONSTRAINT [PK__OnlineSaleOrd__6951E273] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
