CREATE TABLE [dbo].[CASHCLT]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL,
[OPER] [int] NOT NULL,
[CASHIER] [int] NOT NULL,
[FROMTIME] [datetime] NOT NULL,
[TOTIME] [datetime] NOT NULL,
[TOTAL] [money] NOT NULL,
[NOTE] [varchar] (200) COLLATE Chinese_PRC_CI_AS NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[STAT] [int] NOT NULL CONSTRAINT [DF__CASHCLT__STAT__234D40C7] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CASHCLT] WITH NOCHECK ADD CONSTRAINT [CASHCLT_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[CASHCLT] ADD CONSTRAINT [PK__CASHCLT__220B0B18] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
