CREATE TABLE [dbo].[NBUY1]
(
[ID] [int] NOT NULL,
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NBUY1__FILDATE__27C57B1C] DEFAULT (getdate()),
[CASHIER] [int] NOT NULL CONSTRAINT [DF__NBUY1__CASHIER__28B99F55] DEFAULT (1),
[WRH] [int] NOT NULL CONSTRAINT [DF__NBUY1__WRH__29ADC38E] DEFAULT (1),
[ASSISTANT] [int] NULL,
[TOTAL] [money] NOT NULL CONSTRAINT [DF__NBUY1__TOTAL__2AA1E7C7] DEFAULT (0),
[REALAMT] [money] NOT NULL CONSTRAINT [DF__NBUY1__REALAMT__2B960C00] DEFAULT (0),
[PREVAMT] [money] NOT NULL CONSTRAINT [DF__NBUY1__PREVAMT__2C8A3039] DEFAULT (0),
[GUEST] [int] NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__NBUY1__RECCNT__2D7E5472] DEFAULT (0),
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[TAG] [smallint] NOT NULL CONSTRAINT [DF__NBUY1__TAG__2E7278AB] DEFAULT (0),
[INVNO] [char] (13) COLLATE Chinese_PRC_CI_AS NULL,
[SCORE] [money] NULL,
[CARDCODE] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[RCV] [int] NULL,
[SNDTIME] [datetime] NOT NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL,
[DEALER] [int] NULL,
[FLAG] [int] NOT NULL CONSTRAINT [DF__NBUY1__FLAG__6B1EC194] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NBUY1] ADD CONSTRAINT [PK__NBUY1__26D156E3] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
