CREATE TABLE [dbo].[PKG]
(
[PGID] [int] NOT NULL,
[EGID] [int] NULL,
[QTY] [money] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PKG] ADD CONSTRAINT [PK__PKG__70099B30] PRIMARY KEY CLUSTERED  ([PGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx_egid] ON [dbo].[PKG] ([EGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
