CREATE TABLE [dbo].[INPRICE]
(
[STOREGID] [int] NOT NULL,
[VDRGID] [int] NOT NULL CONSTRAINT [DF__INPRICE__VDRGID__224BCD91] DEFAULT (0),
[GDGID] [int] NOT NULL,
[ASTART] [datetime] NOT NULL CONSTRAINT [DF__INPRICE__ASTART__233FF1CA] DEFAULT (getdate()),
[AFINISH] [datetime] NOT NULL CONSTRAINT [DF__INPRICE__AFINISH__24341603] DEFAULT ('9999.12.31 23:59:59'),
[PRICE] [money] NOT NULL,
[SRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INPRICE] ADD CONSTRAINT [UQ__INPRICE__2157A958] UNIQUE NONCLUSTERED  ([STOREGID], [VDRGID], [GDGID], [ASTART], [AFINISH]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
