CREATE TABLE [dbo].[VDRLESSORTBRANDINV]
(
[VDRGID] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SORT] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BRAND] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PAYRATE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__VDRLESSOR__PAYRA__7C0A21CB] DEFAULT (0),
[SORTCODE] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__VDRLESSOR__SORTC__16F4B8DF] DEFAULT (''),
[SHOPNO] [char] (30) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VDRLESSORTBRANDINV] ADD CONSTRAINT [PK__VDRLESSORTBRANDI__7CFE4604] PRIMARY KEY CLUSTERED  ([VDRGID], [SORT], [BRAND]) ON [PRIMARY]
GO
