CREATE TABLE [dbo].[NSQLITEM]
(
[OID] [int] NOT NULL,
[ANAME] [char] (64) COLLATE Chinese_PRC_CI_AS NULL,
[SECTION] [char] (64) COLLATE Chinese_PRC_CI_AS NULL,
[CLSID] [int] NULL CONSTRAINT [DF__NSQLITEM__CLSID__1EEF72A2] DEFAULT (0),
[GRPID] [int] NULL CONSTRAINT [DF__NSQLITEM__GRPID__1FE396DB] DEFAULT (0),
[ACTID] [smallint] NULL CONSTRAINT [DF__NSQLITEM__ACTID__20D7BB14] DEFAULT (0),
[ASELECT] [text] COLLATE Chinese_PRC_CI_AS NULL,
[AINSERT] [text] COLLATE Chinese_PRC_CI_AS NULL,
[ADELETE] [text] COLLATE Chinese_PRC_CI_AS NULL,
[INFOSQL1] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[INFOSQL2] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NSQLITEM] ADD CONSTRAINT [PK__NSQLITEM__49E3F248] PRIMARY KEY CLUSTERED  ([OID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
