CREATE TABLE [dbo].[PROCTASK]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BOCLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PROCTASK__BOCLS__1D60289E] DEFAULT ('一般'),
[STAT] [smallint] NOT NULL,
[BGNTIME] [datetime] NULL,
[ENDTIME] [datetime] NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__PROCTASK__FILDAT__1E544CD7] DEFAULT (getdate()),
[CHKTIME] [datetime] NULL,
[CHKEMP] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CANMULTI] [int] NOT NULL CONSTRAINT [DF__PROCTASK__CANMUL__1F487110] DEFAULT (0),
[SUBJECT] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__PROCTASK__LSTUPD__203C9549] DEFAULT (getdate()),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[ALGAVGTAG] [varchar] (255) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[PRNTIME] [datetime] NULL,
[SRC] [int] NOT NULL CONSTRAINT [DF__PROCTASK__SRC__2130B982] DEFAULT (1),
[MODE] [smallint] NOT NULL,
[CYCLE] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROCTASK] ADD CONSTRAINT [PK__PROCTASK__2224DDBB] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
