CREATE TABLE [dbo].[NSTKOUTDTL2]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[LINE] [smallint] NOT NULL,
[SUBWRH] [int] NOT NULL,
[WRH] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[QTY] [money] NOT NULL CONSTRAINT [DF__NSTKOUTDTL2__QTY__4DB619DA] DEFAULT (0),
[COST] [money] NOT NULL CONSTRAINT [DF__NSTKOUTDTL__COST__4EAA3E13] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NSTKOUTDTL2] ADD CONSTRAINT [PK__NSTKOUTDTL2__4CC1F5A1] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE], [SUBWRH]) ON [PRIMARY]
GO
