CREATE TABLE [dbo].[VDRPAYDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[CHGNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SHOULDPAY] [decimal] (24, 2) NOT NULL,
[REALPAY] [decimal] (24, 2) NOT NULL,
[PAYTOTAL] [decimal] (24, 2) NOT NULL,
[NOPAYTOTAL] [decimal] (24, 2) NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VDRPAYDTL] ADD CONSTRAINT [PK__VDRPAYDTL__68218E01] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
