CREATE TABLE [dbo].[CQNBRAND]
(
[GROUPID] [int] NOT NULL,
[RHQUUID] [char] (32) COLLATE Chinese_PRC_CI_AS NULL,
[NTYPE] [int] NOT NULL,
[NSTAT] [int] NOT NULL CONSTRAINT [DF__CQNBRAND__NSTAT__4A1CF525] DEFAULT (0),
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[EXTIME] [datetime] NOT NULL CONSTRAINT [DF__CQNBRAND__EXTIME__4B11195E] DEFAULT (getdate()),
[CODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (40) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
