CREATE TABLE [dbo].[PAYVDR]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NULL,
[FILDATE] [datetime] NULL,
[FILLER] [int] NULL,
[CHECKER] [int] NULL,
[VENDOR] [int] NULL,
[WRH] [int] NULL,
[STAT] [smallint] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[PRNTIME] [datetime] NULL,
[INIBAL] [money] NULL,
[OCRTOTAL] [money] NULL,
[PAYTOTAL] [money] NULL,
[PAY] [money] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAYVDR] WITH NOCHECK ADD CONSTRAINT [PAYVDR_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[PAYVDR] ADD CONSTRAINT [PK__PAYVDR__6C390A4C] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FILDATE] ON [dbo].[PAYVDR] ([FILDATE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
