CREATE TABLE [dbo].[TEMPLIMIT]
(
[USERGID] [int] NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[WRH] [int] NOT NULL,
[BVDRGID] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TEMPLIMIT] ADD CONSTRAINT [PK__TEMPLIMIT__22EEE4C2] PRIMARY KEY CLUSTERED  ([USERGID], [NUM], [GDGID], [ASETTLENO], [ADATE], [WRH], [BVDRGID]) ON [PRIMARY]
GO
