CREATE TABLE [dbo].[PRMOFFSETXLSTEMP]
(
[spid] [int] NOT NULL,
[VDRCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDCODE] [varchar] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[QTY] [decimal] (24, 2) NOT NULL,
[TOTAL] [decimal] (24, 2) NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[AGMNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[AGMLINE] [int] NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PST_VGD] ON [dbo].[PRMOFFSETXLSTEMP] ([spid], [VDRCODE], [GDCODE]) ON [PRIMARY]
GO
