CREATE TABLE [dbo].[STKOUTDTL2]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__STKOUTDTL2__CLS__1FEF4F2A] DEFAULT ('自营'),
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SUBWRH] [int] NOT NULL,
[WRH] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[QTY] [money] NOT NULL CONSTRAINT [DF__STKOUTDTL2__QTY__20E37363] DEFAULT (0),
[COST] [money] NOT NULL CONSTRAINT [DF__STKOUTDTL2__COST__21D7979C] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STKOUTDTL2] ADD CONSTRAINT [PK__STKOUTDTL2__1EFB2AF1] PRIMARY KEY CLUSTERED  ([SUBWRH], [CLS], [NUM], [LINE]) ON [PRIMARY]
GO
