CREATE TABLE [dbo].[PS3SPECSCOPESCOREINVOUT]
(
[UUID] [varchar] (36) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SUBJCODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SUBJCLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRCNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PS3SPECSC__SRCNU__5D1EB3B3] DEFAULT ('-'),
[SRCCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PS3SPECSC__SRCCL__5E12D7EC] DEFAULT ('-'),
[Flag] [int] NOT NULL CONSTRAINT [DF__PS3SPECSCO__Flag__08AA923B] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3SPECSCOPESCOREINVOUT] ADD CONSTRAINT [PK__PS3SPECSCOPESCOR__5F06FC25] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3SPECSCOPESCOREINVOUT_NUMCLS] ON [dbo].[PS3SPECSCOPESCOREINVOUT] ([SRCNUM], [SRCCLS]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3SPECSCOPESCOREINVOUT_SUBJCODE] ON [dbo].[PS3SPECSCOPESCOREINVOUT] ([SUBJCODE]) ON [PRIMARY]
GO
