CREATE TABLE [dbo].[GOODSAPPLOG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [int] NOT NULL,
[ACT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GOODSAPPLOG] ADD CONSTRAINT [PK__GOODSAPPLOG__163C9315] PRIMARY KEY CLUSTERED  ([NUM], [STAT], [TIME], [ACT]) ON [PRIMARY]
GO
