CREATE TABLE [dbo].[CTPREPAYRTN]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VENDOR] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__CTPREPAYRT__STAT__1E2AFAFC] DEFAULT (0),
[FILLER] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL,
[CHECKER] [int] NULL,
[CHKDATE] [datetime] NULL,
[OCRDATE] [datetime] NOT NULL,
[DEPT] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[PSR] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[TOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CTPREPAYR__TOTAL__1F1F1F35] DEFAULT (0),
[PREPAYNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__CTPREPAYR__LSTUP__2D6D3E8C] DEFAULT (getdate()),
[LASTMODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CLECENT] [int] NULL,
[SNDTIME] [datetime] NULL,
[SRC] [int] NOT NULL CONSTRAINT [DF__CTPREPAYRTN__SRC__5333C018] DEFAULT (0),
[BRAND] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SORT] [varchar] (13) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CTPREPAYRTN] ADD CONSTRAINT [PK__CTPREPAYRTN__2013436E] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_CTPREPAYRTN_PREPAYNUM] ON [dbo].[CTPREPAYRTN] ([PREPAYNUM]) ON [PRIMARY]
GO
