CREATE TABLE [dbo].[NGDINVCHGNOTIFY]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NGDINVCHG__FILDA__39F245AB] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[STAT] [smallint] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__NGDINVCHG__RECCN__3AE669E4] DEFAULT (0),
[LAUNCH] [datetime] NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__NGDINVCHG__LSTUP__3BDA8E1D] DEFAULT (getdate()),
[EON] [smallint] NOT NULL CONSTRAINT [DF__NGDINVCHGNO__EON__3CCEB256] DEFAULT (0),
[SETPKG] [smallint] NOT NULL CONSTRAINT [DF__NGDINVCHG__SETPK__3DC2D68F] DEFAULT (0),
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[NTYPE] [smallint] NOT NULL,
[NSTAT] [int] NOT NULL,
[NNOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[EXDIRECT] [smallint] NOT NULL CONSTRAINT [DF__NGDINVCHG__EXDIR__5EA4A76D] DEFAULT (1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NGDINVCHGNOTIFY] ADD CONSTRAINT [PK__NGDINVCHGNOTIFY__3EB6FAC8] PRIMARY KEY CLUSTERED  ([ID], [SRC]) ON [PRIMARY]
GO
