CREATE TABLE [dbo].[DA_SLOT_GROUP]
(
[SLOTCODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SLOTGRP] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DA_SLOT_GROUP] ADD CONSTRAINT [PK__DA_SLOT_GROUP__08843BF2] PRIMARY KEY CLUSTERED  ([SLOTCODE]) ON [PRIMARY]
GO
