CREATE TABLE [dbo].[PRMOFFSETAGMDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[MUNIT] [char] (6) COLLATE Chinese_PRC_CI_AS NULL,
[QPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PRMOFFSETAG__QPC__3ADDDEF1] DEFAULT (1),
[QPCSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PRMOFFSET__QPCST__3BD2032A] DEFAULT ('1*1'),
[AGMCNTINPRC] [decimal] (24, 4) NULL,
[AGMPRC] [decimal] (24, 4) NULL,
[DIFFPRC] [decimal] (24, 4) NOT NULL,
[TOPQTY] [decimal] (24, 4) NULL,
[TOPAMT] [decimal] (24, 2) NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[ASTART] [datetime] NULL,
[AFINISH] [datetime] NULL,
[INUSE] [smallint] NOT NULL CONSTRAINT [DF__PRMOFFSET__INUSE__3CC62763] DEFAULT (0),
[LOCKNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[OFFSETED] [smallint] NULL CONSTRAINT [DF__PRMOFFSET__OFFSE__3DBA4B9C] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRMOFFSETAGMDTL] ADD CONSTRAINT [PK__PRMOFFSETAGMDTL__3EAE6FD5] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
