CREATE TABLE [dbo].[GDQPCSTORE]
(
[GDGID] [int] NOT NULL,
[STOREGID] [int] NOT NULL,
[QPCSTR] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__GDQPCSTOR__QPCST__32263B5A] DEFAULT ('1*1'),
[QPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__GDQPCSTORE__QPC__331A5F93] DEFAULT (1),
[RTLPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GDQPCSTOR__RTLPR__340E83CC] DEFAULT (0),
[WHSPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GDQPCSTOR__WHSPR__3502A805] DEFAULT (0),
[MBRPRC] [decimal] (24, 2) NULL,
[LWTRTLPRC] [decimal] (24, 4) NULL,
[TOPRTLPRC] [decimal] (24, 4) NULL,
[BQTYPRC] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[PROMOTE] [smallint] NOT NULL CONSTRAINT [DF__GDQPCSTOR__PROMO__35F6CC3E] DEFAULT ((-1))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GDQPCSTORE] ADD CONSTRAINT [PK__GDQPCSTORE__36EAF077] PRIMARY KEY CLUSTERED  ([GDGID], [STOREGID], [QPCSTR]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_GDQPCSTORE_GIDX] ON [dbo].[GDQPCSTORE] ([GDGID], [STOREGID], [QPC]) ON [PRIMARY]
GO
