CREATE TABLE [dbo].[CLEARDEFINE]
(
[No] [int] NOT NULL,
[item] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[procname] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[flag] [int] NOT NULL,
[Months] [int] NOT NULL CONSTRAINT [DF__CLEARDEFI__Month__36F37B6A] DEFAULT (12),
[Note] [varchar] (255) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CLEARDEFIN__Note__37E79FA3] DEFAULT ('')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLEARDEFINE] ADD CONSTRAINT [PK__CLEARDEFINE__35FF5731] PRIMARY KEY CLUSTERED  ([No]) ON [PRIMARY]
GO
