CREATE TABLE [dbo].[PSCTGDDISRULE]
(
[UUID] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARDTYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[GDQPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PSCTGDDIS__GDQPC__7B696C9F] DEFAULT (0),
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL CONSTRAINT [DF__PSCTGDDIS__ENDDA__7C5D90D8] DEFAULT ('2099.12.31'),
[DISCOUNT] [decimal] (24, 4) NOT NULL,
[EXDIS] [int] NOT NULL CONSTRAINT [DF__PSCTGDDIS__EXDIS__7D51B511] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF_PSCTGDDISRULE_NOTE] DEFAULT ('-')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSCTGDDISRULE] ADD CONSTRAINT [PK__PSCTGDDISRULE__7E45D94A] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PSGDDISRULE] ON [dbo].[PSCTGDDISRULE] ([CARDTYPE], [GDGID], [GDQPC], [BEGINDATE]) ON [PRIMARY]
GO
