CREATE TABLE [dbo].[NDIRALCDTL2]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[LINE] [smallint] NOT NULL,
[SUBWRH] [int] NOT NULL,
[WRH] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[QTY] [money] NOT NULL CONSTRAINT [DF__NDIRALCDTL2__QTY__55573BA2] DEFAULT (0),
[COST] [money] NOT NULL CONSTRAINT [DF__NDIRALCDTL__COST__564B5FDB] DEFAULT (0),
[SUBWRHCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NDIRALCDTL2] ADD CONSTRAINT [PK__NDIRALCDTL2__54631769] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE], [SUBWRH]) ON [PRIMARY]
GO
