CREATE TABLE [dbo].[MCKPOOL_PROBLEM]
(
[TIME] [datetime] NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[GDGID] [int] NOT NULL,
[INPUTER] [int] NOT NULL CONSTRAINT [DF__MCKPOOL_P__INPUT__64702D57] DEFAULT (1),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__MCKPOOL_P__FILDA__65645190] DEFAULT (getdate()),
[QTY] [money] NOT NULL CONSTRAINT [DF__MCKPOOL_PRO__QTY__665875C9] DEFAULT (0),
[INPRC] [money] NOT NULL CONSTRAINT [DF__MCKPOOL_P__INPRC__674C9A02] DEFAULT (0),
[PRICE] [money] NOT NULL CONSTRAINT [DF__MCKPOOL_P__PRICE__6840BE3B] DEFAULT (0),
[AMOUNT] [money] NOT NULL CONSTRAINT [DF__MCKPOOL_P__AMOUN__6934E274] DEFAULT (0),
[CheckTag] [int] NOT NULL CONSTRAINT [DF__MCKPOOL_P__Check__6A2906AD] DEFAULT (0)
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_MCKPOOL_TIME] ON [dbo].[MCKPOOL_PROBLEM] ([TIME], [POSNO]) ON [PRIMARY]
GO
