CREATE TABLE [dbo].[PSCONSSORTRATE]
(
[UUID] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARDTYPE] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SCORESORT] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[SCORATE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PSCONSSOR__SCORA__7EFECA6B] DEFAULT (1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSCONSSORTRATE] ADD CONSTRAINT [PK__PSCONSSORTRATE__7FF2EEA4] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
