CREATE TABLE [dbo].[STKOUT]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NULL,
[ORDNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[CLIENT] [int] NULL CONSTRAINT [DF__STKOUT__CLIENT__6A11960F] DEFAULT (1),
[BILLTO] [int] NULL CONSTRAINT [DF__STKOUT__BILLTO__6B05BA48] DEFAULT (1),
[OCRDATE] [datetime] NULL,
[TOTAL] [money] NULL,
[TAX] [money] NULL,
[WRH] [int] NULL,
[FILDATE] [datetime] NULL,
[FILLER] [int] NULL CONSTRAINT [DF__STKOUT__FILLER__6BF9DE81] DEFAULT (1),
[CHECKER] [int] NULL CONSTRAINT [DF__STKOUT__CHECKER__6CEE02BA] DEFAULT (1),
[STAT] [smallint] NULL CONSTRAINT [DF__STKOUT__STAT__6DE226F3] DEFAULT (0),
[MODNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SLR] [int] NULL CONSTRAINT [DF__STKOUT__SLR__6ED64B2C] DEFAULT (1),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[PRERCP] [money] NULL CONSTRAINT [DF__STKOUT__PRERCP__6FCA6F65] DEFAULT (0),
[RCPTOTAL] [money] NULL CONSTRAINT [DF__STKOUT__RCPTOTAL__70BE939E] DEFAULT (0),
[RECCNT] [int] NULL,
[SRC] [int] NULL,
[SRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SRCORDNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[PAYDATE] [datetime] NULL,
[PAYMODE] [char] (20) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__STKOUT__PAYMODE__71B2B7D7] DEFAULT ('应收款'),
[PRNTIME] [datetime] NULL,
[GEN] [int] NULL,
[GENBILL] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[GENCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[GENNUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NULL,
[READY] [smallint] NULL CONSTRAINT [DF__stkout__READY__5E8BA021] DEFAULT (0),
[DSPDATE] [datetime] NOT NULL CONSTRAINT [DF__stkout__DSPDATE__6350553E] DEFAULT (getdate()),
[DSPMODE] [smallint] NOT NULL CONSTRAINT [DF__stkout__DSPMODE__64447977] DEFAULT (0),
[BUYERNAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[TEL] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[ADDR] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[NEARBY] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[PRECHECKER] [int] NULL CONSTRAINT [DF__stkout__PRECHECK__70AA505C] DEFAULT (0),
[PRECHKDATE] [datetime] NULL,
[FINISHED] [smallint] NOT NULL CONSTRAINT [DF__STKOUT__FINISHED__53C3F8EB] DEFAULT (0),
[OTHERSIDENUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SALETYPE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[ReCheckDate] [datetime] NULL,
[LOGACNT] [smallint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STKOUT] WITH NOCHECK ADD CONSTRAINT [STKOUT_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[STKOUT] ADD CONSTRAINT [PK__STKOUT__22951AFD] PRIMARY KEY CLUSTERED  ([CLS], [NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [INX_CLSCLIENT] ON [dbo].[STKOUT] ([CLS], [CLIENT], [STAT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FILDATE] ON [dbo].[STKOUT] ([FILDATE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
