CREATE TABLE [dbo].[CHECKINS]
(
[FILLTIME] [datetime] NOT NULL,
[OPERATOR] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CASHIER] [int] NOT NULL,
[STORENO] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[THEDATE] [datetime] NOT NULL,
[FROMDATE] [datetime] NOT NULL,
[AMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CHECKINS__AMOUNT__0E721F72] DEFAULT (0),
[REALAMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CHECKINS__REALAM__0F6643AB] DEFAULT (0),
[RETAILAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CHECKINS__RETAIL__105A67E4] DEFAULT (0),
[MILKAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CHECKINS__MILKAM__114E8C1D] DEFAULT (0),
[PUCAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CHECKINS__PUCAMT__1242B056] DEFAULT (0),
[BILLCOUNT] [int] NOT NULL CONSTRAINT [DF__CHECKINS__BILLCO__1336D48F] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CHECKINS] ADD CONSTRAINT [PK__CHECKINS__0D7DFB39] PRIMARY KEY CLUSTERED  ([STORENO], [THEDATE], [CASHIER]) ON [PRIMARY]
GO
