CREATE TABLE [dbo].[PAYRATEPRM]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[LASTMODIFIER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PAYRATEPR__LASTM__6B149FF3] DEFAULT ('未知[-]'),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__PAYRATEPR__LSTUP__6C08C42C] DEFAULT (getdate()),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__PAYRATEPR__FILDA__6CFCE865] DEFAULT (getdate()),
[FILLER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PAYRATEPR__FILLE__6DF10C9E] DEFAULT ('未知[-]'),
[CHECKER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__PAYRATEPR__RECCN__6EE530D7] DEFAULT (0),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__PAYRATEPRM__STAT__6FD95510] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[EON] [smallint] NOT NULL CONSTRAINT [DF__PAYRATEPRM__EON__70CD7949] DEFAULT (1),
[SRC] [int] NOT NULL CONSTRAINT [DF__PAYRATEPRM__SRC__71C19D82] DEFAULT (1),
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[LAUNCH] [datetime] NULL,
[PSETTLENO] [int] NULL,
[TOPIC] [char] (10) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAYRATEPRM] ADD CONSTRAINT [PK__PAYRATEPRM__72B5C1BB] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
