CREATE TABLE [dbo].[NMKTPRC]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__NMKTPRC__STAT__3C24A6E0] DEFAULT (0),
[STOREGID] [int] NOT NULL,
[SCHEMENUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[INVSTER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[INVSTDATE] [datetime] NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NMKTPRC__FILDATE__3D18CB19] DEFAULT (getdate()),
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[CANCELER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CACLDATE] [datetime] NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__NMKTPRC__LSTUPDT__3E0CEF52] DEFAULT (getdate()),
[SNDTIME] [datetime] NULL,
[RECCNT] [int] NOT NULL,
[PRNTIME] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[INVSTOBJ] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[INVSTPLACE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[NTYPE] [smallint] NOT NULL,
[NSTAT] [int] NOT NULL,
[NNOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NMKTPRC] ADD CONSTRAINT [PK__NMktPrc__3F01138B] PRIMARY KEY CLUSTERED  ([ID], [SRC]) ON [PRIMARY]
GO
