CREATE TABLE [dbo].[STORERETAILFAVDTL]
(
[Num] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[Cls] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ItemNo] [smallint] NOT NULL,
[FAVTYPE] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FavAmt] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__STORERETA__FavAm__0D34ADCD] DEFAULT (0),
[Tag] [smallint] NOT NULL CONSTRAINT [DF__STORERETAIL__Tag__0E28D206] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STORERETAILFAVDTL] ADD CONSTRAINT [PK__StoreRetailFavDt__0F1CF63F] PRIMARY KEY CLUSTERED  ([Num], [Cls], [ItemNo], [FAVTYPE]) ON [PRIMARY]
GO
