CREATE TABLE [dbo].[PDAMACHINE]
(
[MAC] [varchar] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [varchar] (40) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PDAMACHINE] ADD CONSTRAINT [PK__PDAMACHINE__18561EC8] PRIMARY KEY CLUSTERED  ([MAC]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PDAMACHINE_NUM] ON [dbo].[PDAMACHINE] ([NUM]) ON [PRIMARY]
GO
