CREATE TABLE [dbo].[INYRPTX]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[BGDGID] [int] NOT NULL,
[BVDRGID] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[DTN1] [money] NOT NULL CONSTRAINT [DF__INYRPTX__DTN1__7B92BE7A] DEFAULT (0),
[DTN2] [money] NOT NULL CONSTRAINT [DF__INYRPTX__DTN2__7C86E2B3] DEFAULT (0),
[DTN3] [money] NOT NULL CONSTRAINT [DF__INYRPTX__DTN3__7D7B06EC] DEFAULT (0),
[DTN4] [money] NOT NULL CONSTRAINT [DF__INYRPTX__DTN4__7E6F2B25] DEFAULT (0),
[DTN5] [money] NOT NULL CONSTRAINT [DF__INYRPTX__DTN5__7F634F5E] DEFAULT (0),
[DTN6] [money] NOT NULL CONSTRAINT [DF__INYRPTX__DTN6__00577397] DEFAULT (0),
[DTN7] [money] NOT NULL CONSTRAINT [DF__INYRPTX__DTN7__014B97D0] DEFAULT (0),
[DTX1] [money] NOT NULL CONSTRAINT [DF__INYRPTX__DTX1__023FBC09] DEFAULT (0),
[DTX2] [money] NOT NULL CONSTRAINT [DF__INYRPTX__DTX2__0333E042] DEFAULT (0),
[DTX3] [money] NOT NULL CONSTRAINT [DF__INYRPTX__DTX3__0428047B] DEFAULT (0),
[DTX4] [money] NOT NULL CONSTRAINT [DF__INYRPTX__DTX4__051C28B4] DEFAULT (0),
[DTX5] [money] NOT NULL CONSTRAINT [DF__INYRPTX__DTX5__06104CED] DEFAULT (0),
[DTX6] [money] NOT NULL CONSTRAINT [DF__INYRPTX__DTX6__07047126] DEFAULT (0),
[DTX7] [money] NOT NULL CONSTRAINT [DF__INYRPTX__DTX7__07F8955F] DEFAULT (0),
[DIN1] [money] NOT NULL CONSTRAINT [DF__INYRPTX__DIN1__08ECB998] DEFAULT (0),
[DIN2] [money] NOT NULL CONSTRAINT [DF__INYRPTX__DIN2__09E0DDD1] DEFAULT (0),
[DIN3] [money] NOT NULL CONSTRAINT [DF__INYRPTX__DIN3__0AD5020A] DEFAULT (0),
[DIN4] [money] NOT NULL CONSTRAINT [DF__INYRPTX__DIN4__0BC92643] DEFAULT (0),
[DIN5] [money] NOT NULL CONSTRAINT [DF__INYRPTX__DIN5__0CBD4A7C] DEFAULT (0),
[DIN6] [money] NOT NULL CONSTRAINT [DF__INYRPTX__DIN6__0DB16EB5] DEFAULT (0),
[DIN7] [money] NOT NULL CONSTRAINT [DF__INYRPTX__DIN7__0EA592EE] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INYRPTX] ADD CONSTRAINT [PK__INYRPTX__062DE679] PRIMARY KEY CLUSTERED  ([ASETTLENO], [BGDGID], [BVDRGID], [BWRH], [ASTORE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
