CREATE TABLE [dbo].[PSNMKTIVGTPROP]
(
[CODE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TYPECODE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TYPENAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PROPCLS] [smallint] NOT NULL CONSTRAINT [DF__PSNMKTIVG__PROPC__44586380] DEFAULT (0),
[PROPTYPE] [smallint] NOT NULL CONSTRAINT [DF__PSNMKTIVG__PROPT__454C87B9] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[CREATOR] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CREATETIME] [datetime] NULL CONSTRAINT [DF__PSNMKTIVG__CREAT__4640ABF2] DEFAULT (getdate()),
[ID] [int] NOT NULL,
[RCV] [int] NULL,
[SRC] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSNMKTIVGTPROP] ADD CONSTRAINT [PK__PSNMKTIVGTPROP__43643F47] PRIMARY KEY CLUSTERED  ([TYPECODE], [CODE], [ID], [SRC]) ON [PRIMARY]
GO
