CREATE TABLE [dbo].[CRMDATAEXGSENDLIST]
(
[FSENDTIME] [datetime] NOT NULL,
[FCLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FNOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[FSRCORG] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FDESTORG] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FDELTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMDATAEXGSENDLIST] ADD CONSTRAINT [PK__CRMDATAEXGSENDLI__1BC38F9D] PRIMARY KEY CLUSTERED  ([FSRCORG], [FDESTORG], [FCLS]) ON [PRIMARY]
GO
