CREATE TABLE [dbo].[PRCCSTGDADJGRP]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__PRCCSTGDA__FILDA__72AAD4C3] DEFAULT (getdate()),
[FILLER] [int] NOT NULL CONSTRAINT [DF__PRCCSTGDA__FILLE__739EF8FC] DEFAULT (1),
[CHKDATE] [datetime] NULL,
[CHECKER] [int] NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__PRCCSTGDAD__STAT__74931D35] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__PRCCSTGDA__RECCN__7587416E] DEFAULT (0),
[SRC] [int] NOT NULL CONSTRAINT [DF__PRCCSTGDADJ__SRC__767B65A7] DEFAULT (1),
[SRCNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__PRCCSTGDA__LSTUP__776F89E0] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRCCSTGDADJGRP] ADD CONSTRAINT [PK__PRCCSTGDADJGRP__7863AE19] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FILDATE] ON [dbo].[PRCCSTGDADJGRP] ([FILDATE]) ON [PRIMARY]
GO
