CREATE TABLE [dbo].[CLRINV]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILLER] [int] NULL,
[FILDATE] [datetime] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLRINV] WITH NOCHECK ADD CONSTRAINT [CLRINV_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[CLRINV] ADD CONSTRAINT [PK__CLRINV__2F650636] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
