CREATE TABLE [dbo].[NPOLYPROMTOTALSCHMDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[LOWAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NPOLYPROM__LOWAM__21E813F5] DEFAULT (0),
[HIGHAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NPOLYPROM__HIGHA__22DC382E] DEFAULT (99999999),
[DISCOUNT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPOLYPROM__DISCO__23D05C67] DEFAULT (0),
[FAVAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NPOLYPROM__FAVAM__24C480A0] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPOLYPROMTOTALSCHMDTL] ADD CONSTRAINT [PK__NPOLYPROMTOTALSC__25B8A4D9] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) ON [PRIMARY]
GO
