CREATE TABLE [dbo].[GDLACK]
(
[NUM] [int] NOT NULL IDENTITY(1, 1),
[GENDATE] [datetime] NULL CONSTRAINT [DF__GDLACK__GENDATE__01FEF990] DEFAULT (getdate()),
[GDGID] [int] NULL,
[WRH] [int] NULL,
[REQQTY] [money] NULL CONSTRAINT [DF__GDLACK__REQQTY__02F31DC9] DEFAULT (0),
[REQTOTAL] [money] NULL CONSTRAINT [DF__GDLACK__REQTOTAL__03E74202] DEFAULT (0),
[ACNTQTY] [money] NULL CONSTRAINT [DF__GDLACK__ACNTQTY__04DB663B] DEFAULT (0),
[ACNTTOTAL] [money] NULL CONSTRAINT [DF__GDLACK__ACNTTOTA__05CF8A74] DEFAULT (0),
[BILLNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[BILLCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GDLACK] ADD CONSTRAINT [PK__GDLACK__60FC61CA] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_GDW] ON [dbo].[GDLACK] ([GDGID], [WRH]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_GENDATE] ON [dbo].[GDLACK] ([GENDATE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
