CREATE TABLE [dbo].[CQNSTKINBCKDTL]
(
[GROUPID] [int] NOT NULL,
[RHQUUID] [char] (32) COLLATE Chinese_PRC_CI_AS NULL,
[NTYPE] [int] NOT NULL,
[NSTAT] [int] NOT NULL CONSTRAINT [DF__CQNSTKINB__NSTAT__1E0968BD] DEFAULT (0),
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[EXTIME] [datetime] NOT NULL CONSTRAINT [DF__CQNSTKINB__EXTIM__1EFD8CF6] DEFAULT (getdate()),
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CQNSTKINBCK__CLS__1FF1B12F] DEFAULT ('自营'),
[SETTLENO] [int] NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[CASES] [decimal] (24, 4) NULL,
[QTY] [decimal] (24, 4) NOT NULL,
[PRICE] [decimal] (24, 4) NOT NULL,
[TOTAL] [decimal] (24, 4) NOT NULL,
[TAX] [decimal] (24, 4) NOT NULL,
[VALIDDATE] [datetime] NULL,
[WRH] [int] NOT NULL CONSTRAINT [DF__CQNSTKINBCK__WRH__20E5D568] DEFAULT (1),
[INPRC] [decimal] (24, 4) NOT NULL,
[RTLPRC] [decimal] (24, 4) NOT NULL,
[PAYQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNSTKINB__PAYQT__21D9F9A1] DEFAULT (0),
[PAYAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNSTKINB__PAYAM__22CE1DDA] DEFAULT (0),
[BNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SUBWRH] [int] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[COST] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNSTKINBC__COST__23C24213] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CQNSTKINBCKDTL] ADD CONSTRAINT [PK__CQNSTKINBCKDTL__24B6664C] PRIMARY KEY CLUSTERED  ([GROUPID], [CLS], [NUM], [LINE]) ON [PRIMARY]
GO
