CREATE TABLE [dbo].[EAREA]
(
[CODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EAREA] ADD CONSTRAINT [PK__EAREA__15FBD09C] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
