CREATE TABLE [dbo].[LEAGUECLIENTACCOUNT]
(
[CLIENTGID] [int] NOT NULL,
[ACCOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__LEAGUECLI__ACCOU__055394E3] DEFAULT (0),
[TOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__LEAGUECLI__TOTAL__0647B91C] DEFAULT (0),
[LSTUPDTIME] [datetime] NOT NULL,
[LSTMODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SHOULDPAY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__LEAGUECLI__SHOUL__12AD9001] DEFAULT (0),
[PAY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__LEAGUECLIEN__PAY__13A1B43A] DEFAULT (0),
[USEACCOUNT] [smallint] NOT NULL CONSTRAINT [DF__LEAGUECLI__USEAC__20C6A52E] DEFAULT (1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LEAGUECLIENTACCOUNT] ADD CONSTRAINT [PK__LEAGUECLIENTACCO__073BDD55] PRIMARY KEY CLUSTERED  ([CLIENTGID]) ON [PRIMARY]
GO
