CREATE TABLE [dbo].[CusGDList]
(
[NID] [int] NOT NULL,
[GDNAME] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDCODE] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CusGDList] ADD CONSTRAINT [PK__CusGDList__593DA676] PRIMARY KEY CLUSTERED  ([NID]) ON [PRIMARY]
GO
