CREATE TABLE [dbo].[TMPIMPXLSSTKOUTBCK]
(
[spid] [int] NOT NULL,
[STOREGID] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[GDQTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__TMPIMPXLS__GDQTY__2C3857DA] DEFAULT (0)
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_TMPIMPXLSSTKOUTBCK_SPID] ON [dbo].[TMPIMPXLSSTKOUTBCK] ([spid]) ON [PRIMARY]
GO
