CREATE TABLE [dbo].[IMPTASKLOG]
(
[IMPTASKCODE] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MEMO] [text] COLLATE Chinese_PRC_CI_AS NULL,
[OPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TIME] [datetime] NOT NULL CONSTRAINT [DF__IMPTASKLOG__TIME__6892C864] DEFAULT (getdate())
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_IMPTASKLOG_1] ON [dbo].[IMPTASKLOG] ([IMPTASKCODE], [TIME], [OPER]) ON [PRIMARY]
GO
