CREATE TABLE [dbo].[BCKDMDSPLITDTL]
(
[DMDSTORE] [int] NOT NULL,
[NEWNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRCNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NEWCLS] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRCCLS] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[NEWLINE] [int] NULL,
[SRCLINE] [int] NOT NULL,
[STAT] [int] NULL,
[OCRDATE] [datetime] NULL CONSTRAINT [DF__BCKDMDSPL__OCRDA__6EEDBBCA] DEFAULT (0),
[RCVTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BCKDMDSPLITDTL] ADD CONSTRAINT [PK__BCKDMDSPLITDTL__72BE4CAE] PRIMARY KEY CLUSTERED  ([SRCNUM], [SRCCLS], [SRCLINE]) ON [PRIMARY]
GO
