CREATE TABLE [dbo].[NSENDWEATHER]
(
[ADATE] [datetime] NOT NULL,
[ID] [int] NOT NULL,
[SRC] [int] NOT NULL,
[RCV] [int] NOT NULL,
[NSTAT] [int] NOT NULL CONSTRAINT [DF__NSENDWEAT__NSTAT__74AB592A] DEFAULT (0),
[NNOTE] [varchar] (256) COLLATE Chinese_PRC_CI_AS NULL,
[WEATHER] [int] NOT NULL,
[LOWTMPER] [decimal] (24, 2) NOT NULL,
[HIGHTMPER] [decimal] (24, 2) NOT NULL,
[TYPE] [smallint] NOT NULL,
[SNDTIME] [datetime] NOT NULL,
[RCVTIME] [datetime] NULL,
[SPECCOND] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NSENDWEATHER] ADD CONSTRAINT [PK__NSENDWEATHER__759F7D63] PRIMARY KEY CLUSTERED  ([ID], [SRC]) ON [PRIMARY]
GO
