CREATE TABLE [dbo].[TAXSORTADJLACDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TAXSORTADJLACDTL] ADD CONSTRAINT [PK__TAXSORTA__AA14E68F62F9EA9F] PRIMARY KEY CLUSTERED  ([NUM], [STOREGID]) ON [PRIMARY]
GO
