CREATE TABLE [dbo].[PSGDCONSSCOREDTL]
(
[UUID] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SCORESORT] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SCORE] [decimal] (24, 2) NOT NULL,
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSGDCONSSCOREDTL] ADD CONSTRAINT [PK__PSGDCONSSCOREDTL__6FBC86DB] PRIMARY KEY CLUSTERED  ([UUID], [SCORESORT]) ON [PRIMARY]
GO
