CREATE TABLE [dbo].[NCTCHGDEF]
(
[CODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[CHGCLS] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MODALTYPE] [char] (2) COLLATE Chinese_PRC_CI_AS NOT NULL,
[AUTOCALC] [smallint] NOT NULL CONSTRAINT [DF__NCTCHGDEF__AUTOC__7C5FF2DD] DEFAULT (0),
[WHENGEN] [char] (8) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GENMETHOD] [smallint] NULL,
[GENUNIT] [char] (4) COLLATE Chinese_PRC_CI_AS NULL,
[GENCYCLE] [smallint] NULL,
[GENDAYOFFSET] [smallint] NULL,
[PAYDIRECT] [smallint] NOT NULL CONSTRAINT [DF__NCTCHGDEF__PAYDI__7D541716] DEFAULT (1),
[GATHERINGMODE] [char] (8) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NCTCHGDEF__GATHE__7E483B4F] DEFAULT ('冲扣货款'),
[TOPAYMETHOD] [smallint] NOT NULL CONSTRAINT [DF__NCTCHGDEF__TOPAY__7F3C5F88] DEFAULT (0),
[PAYLIMIT] [smallint] NOT NULL CONSTRAINT [DF__NCTCHGDEF__PAYLI__003083C1] DEFAULT (0),
[FINCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[FINNAME] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[STOPPED] [smallint] NOT NULL CONSTRAINT [DF__NCTCHGDEF__STOPP__0124A7FA] DEFAULT (0),
[PAYUNIT] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NCTCHGDEF__PAYUN__0218CC33] DEFAULT ('总部'),
[DESIGNCYCLE] [smallint] NOT NULL CONSTRAINT [DF__NCTCHGDEF__DESIG__030CF06C] DEFAULT (0),
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCTCHGDEF] ADD CONSTRAINT [PK__NCTCHGDEF__040114A5] PRIMARY KEY CLUSTERED  ([SRC], [ID], [CODE]) ON [PRIMARY]
GO
