CREATE TABLE [dbo].[KWHMETERRECORD]
(
[KWHMETER] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[YEARMONTH] [char] (6) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLEDEPT] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[VENDOR] [int] NULL,
[BRANDCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[STARTNUM] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__KWHMETERR__START__58F15D78] DEFAULT ((0)),
[ENDNUM] [decimal] (24, 2) NULL,
[STARTDATE] [datetime] NULL,
[ENDDATE] [datetime] NULL,
[CHECKNAME] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[VERSION] [int] NOT NULL CONSTRAINT [DF__KWHMETERR__VERSI__59E581B1] DEFAULT ((1)),
[STAT] [int] NOT NULL CONSTRAINT [DF__KWHMETERRE__STAT__5AD9A5EA] DEFAULT ((0)),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SHAREDNUM] [decimal] (24, 2) NULL,
[SHAREDNOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[KWHMETERRECORD] ADD CONSTRAINT [PK__KWHMETER__4205C74B5CC1EE5C] PRIMARY KEY CLUSTERED  ([KWHMETER], [YEARMONTH]) ON [PRIMARY]
GO
