CREATE TABLE [dbo].[PRMOFFSETAGMPRM]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRCPRMNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRCPRMCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRMOFFSETAGMPRM] ADD CONSTRAINT [PK__PRMOFFSETAGMPRM__427F00B9] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
