CREATE TABLE [dbo].[CRMSYSFUN]
(
[SYSUUID] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FUNTYPE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMSYSFUN__FUNTY__4035FA3D] DEFAULT ('1000000000'),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__CRMSYSFUN__LSTUP__412A1E76] DEFAULT (getdate()),
[NAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
