CREATE TABLE [dbo].[VDRDRPTI]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[BVDRGID] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[BGDGID] [int] NOT NULL,
[CQ1] [money] NULL CONSTRAINT [DF__VDRDRPTI__CQ1__76EC6E40] DEFAULT (0),
[CQ2] [money] NULL CONSTRAINT [DF__VDRDRPTI__CQ2__77E09279] DEFAULT (0),
[CQ3] [money] NULL CONSTRAINT [DF__VDRDRPTI__CQ3__78D4B6B2] DEFAULT (0),
[CQ4] [money] NULL CONSTRAINT [DF__VDRDRPTI__CQ4__79C8DAEB] DEFAULT (0),
[CQ5] [money] NULL CONSTRAINT [DF__VDRDRPTI__CQ5__7ABCFF24] DEFAULT (0),
[CQ6] [money] NULL CONSTRAINT [DF__VDRDRPTI__CQ6__7BB1235D] DEFAULT (0),
[CT1] [money] NULL CONSTRAINT [DF__VDRDRPTI__CT1__7CA54796] DEFAULT (0),
[CT2] [money] NULL CONSTRAINT [DF__VDRDRPTI__CT2__7D996BCF] DEFAULT (0),
[CT3] [money] NULL CONSTRAINT [DF__VDRDRPTI__CT3__7E8D9008] DEFAULT (0),
[CT4] [money] NULL CONSTRAINT [DF__VDRDRPTI__CT4__7F81B441] DEFAULT (0),
[CT5] [money] NULL CONSTRAINT [DF__VDRDRPTI__CT5__0075D87A] DEFAULT (0),
[CT6] [money] NULL CONSTRAINT [DF__VDRDRPTI__CT6__0169FCB3] DEFAULT (0),
[CT7] [money] NULL CONSTRAINT [DF__VDRDRPTI__CT7__025E20EC] DEFAULT (0),
[CT8] [money] NULL CONSTRAINT [DF__VDRDRPTI__CT8__03524525] DEFAULT (0),
[CI2] [money] NULL CONSTRAINT [DF__VDRDRPTI__CI2__0446695E] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VDRDRPTI] ADD CONSTRAINT [PK__VDRDRPTI__55422D09] PRIMARY KEY CLUSTERED  ([ASTORE], [ASETTLENO], [ADATE], [BVDRGID], [BWRH], [BGDGID]) ON [PRIMARY]
GO
