CREATE TABLE [dbo].[RTLBCK]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__RTLBCK__STAT__298E9354] DEFAULT (0),
[TOTAL] [money] NOT NULL,
[FILLER] [int] NOT NULL,
[WRH] [int] NOT NULL,
[MODNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[INVNO] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL,
[CHECKER] [int] NULL,
[TAX] [money] NOT NULL,
[DSPWRH] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PROVIDER] [int] NOT NULL,
[PRNTIME] [datetime] NULL,
[ASSISTANT] [int] NULL,
[SRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NULL,
[GFTPRO] [int] NULL,
[GFTPROWRH] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RTLBCK] WITH NOCHECK ADD CONSTRAINT [RTLBCK_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[RTLBCK] ADD CONSTRAINT [PK__RTLBCK__10766AC2] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
