CREATE TABLE [dbo].[MKTPRCSCHEME]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__MKTPRCSCHE__STAT__1F886832] DEFAULT (0),
[CREATOR] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CREATETIME] [datetime] NOT NULL CONSTRAINT [DF__MKTPRCSCH__CREAT__207C8C6B] DEFAULT (getdate()),
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[SNDTIME] [datetime] NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__MKTPRCSCH__LSTUP__2170B0A4] DEFAULT (getdate()),
[PRNTIME] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MKTPRCSCHEME] ADD CONSTRAINT [PK__MktPrcScheme__2264D4DD] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
