CREATE TABLE [dbo].[ALCPOOLH]
(
[STOREGID] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[LINE] [int] NOT NULL,
[QTY] [money] NOT NULL CONSTRAINT [DF__ALCPOOLH__QTY__3787ACF0] DEFAULT (0),
[DMDDATE] [datetime] NOT NULL,
[SRCGRP] [smallint] NOT NULL,
[SRCBILL] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SRCCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SRCLINE] [int] NULL,
[GENTIME] [datetime] NULL,
[GENNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__ALCPOOLH__GENNUM__387BD129] DEFAULT ('-'),
[GENCLS] [char] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SRCQTY] [money] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[APARTER] [int] NULL,
[ALCER] [int] NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_ALCPOOLH_DMDDATE] ON [dbo].[ALCPOOLH] ([DMDDATE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_ALCPOOLH_SRCGRP] ON [dbo].[ALCPOOLH] ([SRCGRP]) ON [PRIMARY]
GO
