CREATE TABLE [dbo].[ALCLMT]
(
[VENDOR] [smallint] NOT NULL CONSTRAINT [DF__ALCLMT__VENDOR__5FDEEBB6] DEFAULT (0),
[CLIENT] [smallint] NOT NULL CONSTRAINT [DF__ALCLMT__CLIENT__60D30FEF] DEFAULT (0),
[ALC] [smallint] NOT NULL CONSTRAINT [DF__ALCLMT__ALC__61C73428] DEFAULT (0),
[ISGDSTORE] [smallint] NOT NULL CONSTRAINT [DF__ALCLMT__ISGDSTOR__62BB5861] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ALCLMT] ADD CONSTRAINT [PK__ALCLMT__5EEAC77D] PRIMARY KEY CLUSTERED  ([VENDOR], [CLIENT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
