CREATE TABLE [dbo].[PS3_OTHERBUYPAYMENT]
(
[LINE] [smallint] NOT NULL,
[CURRENCY] [smallint] NOT NULL CONSTRAINT [DF__PS3_OTHER__CURRE__01A95A48] DEFAULT ((0)),
[AMOUNT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PS3_OTHER__AMOUN__029D7E81] DEFAULT ((0)),
[PAYTIME] [datetime] NOT NULL,
[FAVTYPE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NULL,
[FAVAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PS3_OTHER__FAVAM__0391A2BA] DEFAULT ((0)),
[UUID] [varchar] (38) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3_OTHERBUYPAYMENT] ADD CONSTRAINT [PK__PS3_OTHE__33AEB8210579EB2C] PRIMARY KEY CLUSTERED  ([UUID], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_OTHERBUYPAY_CUR] ON [dbo].[PS3_OTHERBUYPAYMENT] ([UUID], [CURRENCY]) ON [PRIMARY]
GO
