CREATE TABLE [dbo].[POLYPROMLACDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[POLYPROMLACDTL] ADD CONSTRAINT [PK__POLYPROMLACDTL__596D5309] PRIMARY KEY CLUSTERED  ([NUM], [CLS], [STOREGID]) ON [PRIMARY]
GO
