CREATE TABLE [dbo].[PROMBSTORE]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROMBSTORE] ADD CONSTRAINT [PK__PROMBSTORE__60AC2019] PRIMARY KEY CLUSTERED  ([NUM], [STOREGID]) ON [PRIMARY]
GO
