CREATE TABLE [dbo].[INVXF]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__INVXF__STAT__32AF7FE8] DEFAULT (0),
[MODNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__INVXF__FILDATE__33A3A421] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__INVXF__LSTUPDTIM__3497C85A] DEFAULT (getdate()),
[PRNTIME] [datetime] NULL,
[SETTLENO] [int] NOT NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__INVXF__RECCNT__358BEC93] DEFAULT (0),
[FROMSTORE] [int] NOT NULL,
[FROMWRH] [int] NOT NULL,
[TOSTORE] [int] NOT NULL,
[TOWRH] [int] NOT NULL,
[FROMRTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__INVXF__FROMRTOTA__368010CC] DEFAULT (0),
[TORTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__INVXF__TORTOTAL__37743505] DEFAULT (0),
[CAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__INVXF__CAMT__3868593E] DEFAULT (0),
[CTAX] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__INVXF__CTAX__395C7D77] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[OCRDATE] [datetime] NOT NULL CONSTRAINT [DF__INVXF__OCRDATE__3A50A1B0] DEFAULT (getdate()),
[SRC] [int] NOT NULL,
[TOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__INVXF__TOTAL__3B44C5E9] DEFAULT (0),
[TAX] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__INVXF__TAX__3C38EA22] DEFAULT (0),
[SENDCOUNT] [int] NOT NULL CONSTRAINT [DF__INVXF__SENDCOUNT__3D2D0E5B] DEFAULT (0),
[SRCNUM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INVXF] ADD CONSTRAINT [PK__INVXF__31BB5BAF] PRIMARY KEY CLUSTERED  ([NUM], [CLS]) ON [PRIMARY]
GO
