CREATE TABLE [dbo].[EMPCLT]
(
[EMPGID] [int] NOT NULL,
[CLTGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMPCLT] ADD CONSTRAINT [PK__EMPCLT__741727A4] PRIMARY KEY CLUSTERED  ([CLTGID], [EMPGID]) ON [PRIMARY]
GO
