CREATE TABLE [dbo].[GSTLMT]
(
[GUEST] [int] NOT NULL,
[LSTID] [char] (16) COLLATE Chinese_PRC_CI_AS NOT NULL,
[QTYLMT] [money] NOT NULL CONSTRAINT [DF__GSTLMT__QTYLMT__2BA02DA1] DEFAULT (0),
[QTYBUY] [money] NOT NULL CONSTRAINT [DF__GSTLMT__QTYBUY__2C9451DA] DEFAULT (0),
[BUYDATE] [datetime] NOT NULL CONSTRAINT [DF__GSTLMT__BUYDATE__2D887613] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GSTLMT] ADD CONSTRAINT [PK__GSTLMT__72E79E89] PRIMARY KEY NONCLUSTERED  ([GUEST], [LSTID], [BUYDATE]) ON [PRIMARY]
GO
