CREATE TABLE [dbo].[CRMCARDSALE]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__CRMCARDSAL__STAT__63C6ED38] DEFAULT (0),
[STORE] [int] NOT NULL,
[COUNT] [int] NOT NULL,
[TOTALBALANCE] [decimal] (24, 2) NOT NULL,
[BUYER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__CRMCARDSA__FILDA__64BB1171] DEFAULT (getdate()),
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NULL,
[TOTALCARDCOST] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCARDSA__TOTAL__65AF35AA] DEFAULT (0),
[SRC] [int] NOT NULL,
[PAY] [decimal] (24, 2) NOT NULL,
[PREPAY] [decimal] (24, 2) NOT NULL,
[DEBTPAY] [decimal] (24, 2) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMCARDSALE] ADD CONSTRAINT [PK__CRMCARDSALE__66A359E3] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
