CREATE TABLE [dbo].[PSTASKMANGDDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSTASKMANGDDTL] ADD CONSTRAINT [PK__PSTASKMANGDDTL__0B417863] PRIMARY KEY CLUSTERED  ([NUM], [GDGID]) ON [PRIMARY]
GO
