CREATE TABLE [dbo].[BUY21POOL]
(
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[FAVTYPE] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FAVAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__BUY21POOL__FAVAM__684E0D38] DEFAULT (0),
[TAG] [smallint] NOT NULL CONSTRAINT [DF__BUY21POOL__TAG__69423171] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BUY21POOL] ADD CONSTRAINT [PK__BUY21POOL__6A3655AA] PRIMARY KEY CLUSTERED  ([FLOWNO], [POSNO], [ITEMNO], [FAVTYPE]) ON [PRIMARY]
GO
