CREATE TABLE [dbo].[PRCPRMLACDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRCPRMLACDTL] ADD CONSTRAINT [PK__PRCPRMLACDTL__7993056A] PRIMARY KEY CLUSTERED  ([NUM], [STOREGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
