CREATE TABLE [dbo].[NGOODSAPP]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__NGOODSAPP__STAT__5FC086D3] DEFAULT (0),
[RATIFIER] [int] NOT NULL,
[SRC] [int] NOT NULL,
[PSR] [int] NOT NULL CONSTRAINT [DF__NGOODSAPP__PSR__60B4AB0C] DEFAULT (1),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NGOODSAPP__FILDA__61A8CF45] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[RATOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[RATDATE] [datetime] NULL,
[DEADDATE] [datetime] NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__NGOODSAPP__LSTUP__629CF37E] DEFAULT (getdate()),
[PRNTIME] [datetime] NULL,
[SNDTIME] [datetime] NULL,
[SETTLENO] [int] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[GOODSCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[APPMODE] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__NGOODSAPP__RECCN__639117B7] DEFAULT (0),
[MODNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[ID] [int] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[NSTAT] [smallint] NOT NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[FRCCHK] [smallint] NOT NULL,
[TYPE] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NGOODSAPP] ADD CONSTRAINT [PK__NGOODSAPP__5ECC629A] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NGOODSAPP_TYPE] ON [dbo].[NGOODSAPP] ([TYPE]) ON [PRIMARY]
GO
