CREATE TABLE [dbo].[CRMDATAEXCHANGECFG]
(
[FEXGCLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SENDSP] [varchar] (80) COLLATE Chinese_PRC_CI_AS NULL,
[RECEIVESP] [varchar] (80) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMDATAEXCHANGECFG] ADD CONSTRAINT [PK__CRMDATAEXCHANGEC__217C68F3] PRIMARY KEY CLUSTERED  ([FEXGCLS]) ON [PRIMARY]
GO
