CREATE TABLE [dbo].[PROMQTY]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PRMNO] [int] NOT NULL,
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PROMQTY__QTY__4B31E046] DEFAULT (1),
[PRMTOTAL] [decimal] (24, 4) NOT NULL,
[IFGFT] [int] NOT NULL CONSTRAINT [DF__PROMQTY__IFGFT__4C26047F] DEFAULT (0),
[GFTQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PROMQTY__GFTQTY__4D1A28B8] DEFAULT (0),
[PTOTAL] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PROMQTY__PTOTAL__33F01EE9] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROMQTY] ADD CONSTRAINT [PK__PROMQTY__4E0E4CF1] PRIMARY KEY CLUSTERED  ([NUM], [CLS], [PRMNO]) ON [PRIMARY]
GO
