CREATE TABLE [dbo].[CTCNTRLOG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VERSION] [smallint] NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[FROMSTAT] [smallint] NULL,
[TOSTAT] [smallint] NOT NULL,
[OPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OPERTIME] [datetime] NOT NULL,
[SETTLENO] [int] NOT NULL,
[TAG] [smallint] NOT NULL CONSTRAINT [DF__CTCNTRLOG__TAG__48A8E2A8] DEFAULT (0),
[ACTION] [char] (10) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CTCNTRLOG] ADD CONSTRAINT [PK__CTCNTRLOG__499D06E1] PRIMARY KEY CLUSTERED  ([NUM], [VERSION], [ITEMNO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_CTCNTRLOG_NVFTT] ON [dbo].[CTCNTRLOG] ([NUM], [VERSION], [FROMSTAT], [TOSTAT], [TAG]) ON [PRIMARY]
GO
