CREATE TABLE [dbo].[PRMEXCLUSIVECURRENCY]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CURRENCY] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRMEXCLUSIVECURRENCY] ADD CONSTRAINT [PK__PRMEXCLUSIVECURR__6E5CB7A0] PRIMARY KEY CLUSTERED  ([NUM], [CLS], [CURRENCY]) ON [PRIMARY]
GO
