CREATE TABLE [dbo].[PS3NOTSCOREGDSCOPELACSTORE]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3NOTSCOREGDSCOPELACSTORE] ADD CONSTRAINT [PK__PS3NOTSCOREGDSCO__3485E71D] PRIMARY KEY CLUSTERED  ([NUM], [CLS], [STOREGID]) ON [PRIMARY]
GO
