CREATE TABLE [dbo].[VDRClear]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL,
[FILLER] [int] NOT NULL,
[BILLTO] [int] NOT NULL,
[IsUpd] [smallint] NOT NULL CONSTRAINT [DF__VDRClear__IsUpd__1745C5E7] DEFAULT (0),
[IsDel] [smallint] NOT NULL CONSTRAINT [DF__VDRClear__IsDel__1839EA20] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VDRClear] WITH NOCHECK ADD CONSTRAINT [VDRClear_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[VDRClear] ADD CONSTRAINT [PK__VDRClear__32CB82C6] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
