CREATE TABLE [dbo].[BCKDMD]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[RECCNT] [int] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__BCKDMD__FILDATE__14A88507] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHKDATE] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CACLDATE] [datetime] NULL,
[CANCELER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[SNDDATE] [datetime] NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__BCKDMD__STAT__159CA940] DEFAULT (0),
[CHKSTOREGID] [int] NOT NULL,
[SRC] [int] NOT NULL,
[SNDTIME] [datetime] NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__BCKDMD__LSTUPDTI__1690CD79] DEFAULT (getdate()),
[PRNTIME] [datetime] NULL,
[PSR] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LOCKNUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NULL,
[LOCKCLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[EXPDATE] [datetime] NULL,
[BCKCLS] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[DMDSTORE] [int] NOT NULL CONSTRAINT [DF__bckdmd__DMDSTORE__5FAB783A] DEFAULT ((-1)),
[SRCNUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NULL,
[SRCCLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[BEGINDATE] [datetime] NULL,
[PSRGID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BCKDMD] ADD CONSTRAINT [PK__BCKDMD__13B460CE] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
