CREATE TABLE [dbo].[PSFORMULAENTPARAM]
(
[CODE] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PARAMNAME] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PARAMVALUE] [varchar] (120) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSFORMULAENTPARAM] ADD CONSTRAINT [PK__PSFORMULAEntPARA__05889F0D] PRIMARY KEY CLUSTERED  ([CODE], [PARAMNAME]) ON [PRIMARY]
GO
