CREATE TABLE [dbo].[PSBRANDSORTSTORE]
(
[BRANDCODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SORTCODE] [varchar] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL,
[STATUS] [int] NOT NULL CONSTRAINT [DF__PSBRANDSO__STATU__295CB686] DEFAULT (0),
[STARTDATE] [datetime] NULL,
[SUSPENDDATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSBRANDSORTSTORE] ADD CONSTRAINT [PK__PSBRANDSORTSTORE__2A50DABF] PRIMARY KEY CLUSTERED  ([BRANDCODE], [SORTCODE], [STOREGID]) ON [PRIMARY]
GO
