CREATE TABLE [dbo].[TaxRate]
(
[NO] [smallint] NOT NULL,
[CLS] [char] (6) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TaxRate] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TaxRate] ADD CONSTRAINT [PK__TaxRate__EE0B5A020D7A3450] PRIMARY KEY CLUSTERED  ([NO], [CLS]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [UQ_TAXRATE] ON [dbo].[TaxRate] ([CLS], [TaxRate]) ON [PRIMARY]
GO
