CREATE TABLE [dbo].[PRMSETTLE]
(
[PSETTLENO] [int] NOT NULL,
[STARTDATE] [datetime] NOT NULL,
[FINISHDATE] [datetime] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRMSETTLE] ADD CONSTRAINT [PK__PRMSETTLE__0652A614] PRIMARY KEY CLUSTERED  ([PSETTLENO]) ON [PRIMARY]
GO
