CREATE TABLE [dbo].[CLIENTPRERCV]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLIENT] [int] NOT NULL,
[STAT] [int] NOT NULL CONSTRAINT [DF__CLIENTPRER__STAT__1157E267] DEFAULT (0),
[PAYER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[PAYRCV] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[OCRDATE] [datetime] NULL,
[TOTAL] [money] NOT NULL CONSTRAINT [DF__CLIENTPRE__TOTAL__124C06A0] DEFAULT (0),
[FILLER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL,
[CHECKER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENTPRERCV] ADD CONSTRAINT [PK__CLIENTPRERCV__1063BE2E] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
