CREATE TABLE [dbo].[CRMPRESENTNSCORULE]
(
[UUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STORE] [int] NULL,
[GOODS] [int] NOT NULL,
[CARDTYPE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[NSCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMPRESEN__NSCOR__1E7775C4] DEFAULT (1),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMPRESENTNSCORULE] ADD CONSTRAINT [PK__CRMPRESENTNSCORU__1F6B99FD] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
