CREATE TABLE [dbo].[CTCNTRRATESTORE]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VERSION] [smallint] NOT NULL,
[LINE] [smallint] NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CTCNTRRATESTORE] ADD CONSTRAINT [PK__CTCNTRRATESTORE__44D851C4] PRIMARY KEY CLUSTERED  ([NUM], [VERSION], [LINE], [ITEMNO]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IDX_CTCNTRSTORE_STOREGID] ON [dbo].[CTCNTRRATESTORE] ([NUM], [VERSION], [LINE], [STOREGID]) ON [PRIMARY]
GO
