CREATE TABLE [dbo].[RFBILL]
(
[RFNUM] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [int] NOT NULL CONSTRAINT [DF__RFBILL__STAT__399252F8] DEFAULT (0),
[FILLER] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__RFBILL__RECCNT__3A867731] DEFAULT (0),
[TOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__RFBILL__TOTAL__3B7A9B6A] DEFAULT (0),
[MBRTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__RFBILL__MBRTOTAL__3C6EBFA3] DEFAULT (0),
[CARDCODE] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RFBILL] ADD CONSTRAINT [PK__RFBILL__3D62E3DC] PRIMARY KEY CLUSTERED  ([RFNUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_RFBILL_CARDCODE] ON [dbo].[RFBILL] ([CARDCODE]) ON [PRIMARY]
GO
