CREATE TABLE [dbo].[SALEORDDTL]
(
[SETTLENO] [int] NOT NULL,
[CLS] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[CASES] [money] NULL,
[QTY] [money] NOT NULL,
[PRICE] [money] NOT NULL,
[TOTAL] [money] NOT NULL,
[TAX] [money] NOT NULL,
[VALIDDATE] [datetime] NULL,
[WRH] [int] NOT NULL CONSTRAINT [DF__SALEORDDTL__WRH__6CA4B54E] DEFAULT (1),
[INVQTY] [money] NOT NULL CONSTRAINT [DF__SALEORDDT__INVQT__6D98D987] DEFAULT (0),
[ARVQTY] [money] NULL CONSTRAINT [DF__SALEORDDT__ARVQT__6E8CFDC0] DEFAULT (0),
[ASNQTY] [money] NULL CONSTRAINT [DF__SALEORDDT__ASNQT__6F8121F9] DEFAULT (0),
[ALLINVQTY] [money] NOT NULL CONSTRAINT [DF__SALEORDDT__ALLIN__70754632] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SALEORDDTL] ADD CONSTRAINT [PK__SALEORDDTL__6BB09115] PRIMARY KEY CLUSTERED  ([CLS], [NUM], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [saleorddtl_gdgid] ON [dbo].[SALEORDDTL] ([GDGID]) ON [PRIMARY]
GO
