CREATE TABLE [dbo].[LTDADJLACDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LTDADJLACDTL] ADD CONSTRAINT [PK__LTDADJLACDTL__07839413] PRIMARY KEY CLUSTERED  ([NUM], [STOREGID]) ON [PRIMARY]
GO
