CREATE TABLE [dbo].[PS3STOREEMPCARD]
(
[CARDINFO] [varchar] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL,
[EMPGID] [int] NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[CREATOR] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CREATETIME] [datetime] NOT NULL CONSTRAINT [DF__PS3STOREE__CREAT__775124FD] DEFAULT (getdate()),
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__PS3STOREE__LSTUP__78454936] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3STOREEMPCARD] ADD CONSTRAINT [PK__PS3STOREEMPCARD__79396D6F] PRIMARY KEY CLUSTERED  ([CARDINFO]) ON [PRIMARY]
GO
