CREATE TABLE [dbo].[SEQ]
(
[OBJNAME] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NEXTVALUE] [int] NOT NULL,
[INC] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SEQ] ADD CONSTRAINT [PK__SEQ__5734971C] PRIMARY KEY CLUSTERED  ([OBJNAME]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
