CREATE TABLE [dbo].[TMPRFORDVDR]
(
[SPID] [int] NOT NULL,
[VDRGID] [int] NOT NULL,
[VDRCODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VDRNAME] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_TMPRFORDVDR_SPID] ON [dbo].[TMPRFORDVDR] ([SPID]) ON [PRIMARY]
GO
