CREATE TABLE [dbo].[CMSTOREGRADEGD]
(
[CMSCODE] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[SALEINFO] [smallint] NOT NULL CONSTRAINT [DF__CMSTOREGR__SALEI__26005B97] DEFAULT (0),
[MSALERATE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CMSTOREGR__MSALE__26F47FD0] DEFAULT (0),
[SALEQTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CMSTOREGR__SALEQ__27E8A409] DEFAULT (0),
[GSALERATE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CMSTOREGR__GSALE__28DCC842] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[NEEDED] [int] NOT NULL CONSTRAINT [DF__CMSTOREGR__NEEDE__58EBCE17] DEFAULT (0),
[FALCQTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CMSTOREGR__FALCQ__59DFF250] DEFAULT (0),
[RACKRATE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CMSTOREGR__RACKR__5AD41689] DEFAULT (0),
[LOWINV] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CMSTOREGR__LOWIN__5BC83AC2] DEFAULT (0),
[HIGHINV] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CMSTOREGR__HIGHI__5CBC5EFB] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CMSTOREGRADEGD] ADD CONSTRAINT [PK__CMSTOREGRADEGD__29D0EC7B] PRIMARY KEY CLUSTERED  ([CMSCODE], [GDGID]) ON [PRIMARY]
GO
