CREATE TABLE [dbo].[QRYARTICLELOG]
(
[UUID] [varchar] (38) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PDANUM] [varchar] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OPERCODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OPERTIME] [datetime] NOT NULL,
[WRHCODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ARTICLECODE] [varchar] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL,
[INVQTY] [decimal] (24, 4) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[QRYARTICLELOG] ADD CONSTRAINT [PK__QRYARTICLELOG__20E14328] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_QRYARTICLELOG_OPERCODE] ON [dbo].[QRYARTICLELOG] ([OPERCODE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_QRYARTICLELOG_PDANUM] ON [dbo].[QRYARTICLELOG] ([PDANUM]) ON [PRIMARY]
GO
