CREATE TABLE [dbo].[CRMCARDHSTPOOL]
(
[ACTION] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__CRMCARDHS__FILDA__48BEBC98] DEFAULT (getdate()),
[STORE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OLDCARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[OLDBAL] [decimal] (24, 2) NULL,
[OCCUR] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCARDHS__OCCUR__49B2E0D1] DEFAULT (0),
[SCORESUBJECT] [char] (3) COLLATE Chinese_PRC_CI_AS NULL,
[OLDSCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCARDHS__OLDSC__4AA7050A] DEFAULT (0),
[SCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCARDHS__SCORE__4B9B2943] DEFAULT (0),
[OLDBYDATE] [datetime] NULL,
[NEWBYDATE] [datetime] NULL,
[OPER] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[CARRIER] [int] NOT NULL CONSTRAINT [DF__CRMCARDHS__CARRI__4C8F4D7C] DEFAULT (1),
[CARDCOST] [decimal] (24, 2) NULL,
[CARDTYPE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[LSTSNDTIME] [datetime] NULL,
[SENDER] [int] NULL,
[SRC] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHARGE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCARDHS__CHARG__4D8371B5] DEFAULT (0),
[OLDRTOTAL] [decimal] (24, 2) NULL,
[RTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCARDHS__RTOTA__4E7795EE] DEFAULT (0),
[TAG] [int] NOT NULL CONSTRAINT [DF__CRMCARDHSTP__TAG__4F6BBA27] DEFAULT (0),
[ID] [int] NOT NULL,
[NUM] [char] (26) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FGSTAT] [smallint] NOT NULL CONSTRAINT [DF__CRMCARDHS__FGSTA__505FDE60] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMCARDHSTPOOL] ADD CONSTRAINT [PK__CRMCARDHSTPOOL__51540299] PRIMARY KEY CLUSTERED  ([ID], [NUM]) ON [PRIMARY]
GO
