CREATE TABLE [dbo].[PSCSSSTOREINVINIT]
(
[NO] [int] NOT NULL,
[STOREGID] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PSCSSSTOREI__QTY__1322914D] DEFAULT (0),
[ORDQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PSCSSSTOR__ORDQT__1416B586] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSCSSSTOREINVINIT] ADD CONSTRAINT [PK__PSCSSSTOREINVINI__150AD9BF] PRIMARY KEY CLUSTERED  ([NO], [STOREGID], [GDGID]) ON [PRIMARY]
GO
