CREATE TABLE [dbo].[BCKNOTIFYLACDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BCKNOTIFYLACDTL] ADD CONSTRAINT [PK__BCKNOTIFYLACDTL__0DFB8778] PRIMARY KEY CLUSTERED  ([NUM], [STOREGID]) ON [PRIMARY]
GO
