CREATE TABLE [dbo].[WEBSCURRCOMPARISON]
(
[SHOPCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PAYMODE] [int] NOT NULL,
[PAYMENTCODE] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WEBSCURRCOMPARISON] ADD CONSTRAINT [PK__WEBSCURRCOMPARIS__702831DD] PRIMARY KEY CLUSTERED  ([SHOPCODE], [PAYMODE], [PAYMENTCODE]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [UK_WEBSCURRCOMPARISON_PAYMENTCODE] ON [dbo].[WEBSCURRCOMPARISON] ([SHOPCODE], [PAYMENTCODE]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [UK_WEBSCURRCOMPARISON_PAYMODE] ON [dbo].[WEBSCURRCOMPARISON] ([SHOPCODE], [PAYMODE]) ON [PRIMARY]
GO
