CREATE TABLE [dbo].[CHARGECHKPAYCLS2]
(
[CODE] [smallint] NOT NULL,
[NAME] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__CHARGECHKP__STAT__46ED196D] DEFAULT (1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CHARGECHKPAYCLS2] ADD CONSTRAINT [PK__CHARGECHKPAYCLS2__79ADA364] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
