CREATE TABLE [dbo].[GFTPRMSNDRULE]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[RCODE] [char] (18) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TAG] [smallint] NOT NULL CONSTRAINT [DF__GFTPRMSNDRU__TAG__0EB07FE6] DEFAULT (0),
[COUNT] [smallint] NOT NULL,
[BCKCOUNT] [smallint] NOT NULL CONSTRAINT [DF__GFTPRMSND__BCKCO__0FA4A41F] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GFTPRMSNDRULE] ADD CONSTRAINT [PK__GFTPRMSNDRULE__0DBC5BAD] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
