CREATE TABLE [dbo].[PRCADJDTL]
(
[CLS] [char] (8) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PRCADJDTL__CLS__53633AE1] DEFAULT ('核算售价'),
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SETTLENO] [int] NULL,
[GDGID] [int] NULL,
[OLDPRC] [money] NULL,
[NEWPRC] [money] NULL,
[QTY] [money] NULL CONSTRAINT [DF__PRCADJDTL__QTY__54575F1A] DEFAULT (0),
[note] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[QPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PRCADJDTL__QPC__28B1DFB9] DEFAULT (1),
[QPCSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PRCADJDTL__QPCST__29A603F2] DEFAULT ('1*1')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRCADJDTL] WITH NOCHECK ADD CONSTRAINT [CK_PRCADJDTL] CHECK NOT FOR REPLICATION ((len([num])=(10) AND (left([num],(1))='9' OR left([num],(1))='0')))
GO
ALTER TABLE [dbo].[PRCADJDTL] ADD CONSTRAINT [PK__PRCADJDTL__74CE504D] PRIMARY KEY CLUSTERED  ([CLS], [NUM], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [prcadjdtl_gdgid] ON [dbo].[PRCADJDTL] ([GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
