CREATE TABLE [dbo].[NPAYRATEPRMDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[QPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPAYRATEPRM__QPC__08A502DA] DEFAULT (1),
[QPCSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NPAYRATEP__QPCST__09992713] DEFAULT ('1*1'),
[ASTART] [datetime] NOT NULL CONSTRAINT [DF__NPAYRATEP__ASTAR__0A8D4B4C] DEFAULT (getdate()),
[AFINISH] [datetime] NOT NULL CONSTRAINT [DF__NPAYRATEP__AFINI__0B816F85] DEFAULT ('9999.12.31 23:59:59'),
[PAYRATE] [decimal] (24, 4) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPAYRATEPRMDTL] ADD CONSTRAINT [PK__NPAYRATEPRMDTL__0C7593BE] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) ON [PRIMARY]
GO
