CREATE TABLE [dbo].[PSSUMGDDTLLOG]
(
[TYPE] [smallint] NOT NULL,
[OPER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OPERTIME] [datetime] NOT NULL CONSTRAINT [DF__PSSUMGDDT__OPERT__097C58DE] DEFAULT (getdate()),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
