CREATE TABLE [dbo].[PRMOFFSETLACDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRMOFFSETLACDTL] ADD CONSTRAINT [PK__PRMOFFSETLACDTL__2009ED24] PRIMARY KEY CLUSTERED  ([NUM], [STOREGID]) ON [PRIMARY]
GO
