CREATE TABLE [dbo].[POLYPAYRATEPRMDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[DEPT] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VENDOR] [int] NULL,
[BRAND] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[POLYPAYRATE] [decimal] (24, 4) NOT NULL,
[ASTART] [datetime] NOT NULL CONSTRAINT [DF__POLYPAYRA__ASTAR__39B3E537] DEFAULT ('1899.12.30 00:00:00'),
[AFINISH] [datetime] NOT NULL CONSTRAINT [DF__POLYPAYRA__AFINI__3AA80970] DEFAULT ('9999.12.31 23:59:59'),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[STARTDIS] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__POLYPAYRA__START__23E56B00] DEFAULT (0),
[FINISHDIS] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__POLYPAYRA__FINIS__24D98F39] DEFAULT (100)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[POLYPAYRATEPRMDTL] ADD CONSTRAINT [PK__POLYPAYRATEPRMDT__3B9C2DA9] PRIMARY KEY CLUSTERED  ([NUM], [CLS], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_POLYPAYRATEPRMDTL_DEPT] ON [dbo].[POLYPAYRATEPRMDTL] ([DEPT]) ON [PRIMARY]
GO
