CREATE TABLE [dbo].[STEALYARDGOODPLU]
(
[GDGID] [int] NOT NULL,
[LFCode] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STEALYARDGOODPLU] ADD CONSTRAINT [PK__StealYardGoodPlu__7C8A100F] PRIMARY KEY CLUSTERED  ([GDGID]) ON [PRIMARY]
GO
