CREATE TABLE [dbo].[NCRMSTAMPSCORULELACSTORE]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[STOREGID] [int] NOT NULL,
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCRMSTAMPSCORULELACSTORE] ADD CONSTRAINT [PK__NCRMSTAMPSCORULE__5063D713] PRIMARY KEY CLUSTERED  ([SRC], [ID], [NUM], [STOREGID]) ON [PRIMARY]
GO
