CREATE TABLE [dbo].[NCHARGECHKDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[NUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[PAYTYPE] [smallint] NOT NULL,
[SHOULDRCVTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCHARGECH__SHOUL__6A6B5FD4] DEFAULT (0),
[RCVTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCHARGECH__RCVTO__6B5F840D] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCHARGECHKDTL] ADD CONSTRAINT [PK__NCHARGECHKDTL__6C53A846] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) ON [PRIMARY]
GO
