CREATE TABLE [dbo].[QUERYSORT]
(
[CODE] [varchar] (8) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[sType] [char] (1) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[QUERYSORT] ADD CONSTRAINT [PK__QUERYSORT__041093DD] PRIMARY KEY CLUSTERED  ([CODE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
