CREATE TABLE [dbo].[NGFTAGMDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[START] [datetime] NOT NULL CONSTRAINT [DF__NGFTAGMDT__START__0CB1922D] DEFAULT ('1899.12.30 00:00:00'),
[FINISH] [datetime] NOT NULL CONSTRAINT [DF__NGFTAGMDT__FINIS__0DA5B666] DEFAULT ('9999.12.31 23:59:59'),
[GDGID] [int] NOT NULL,
[INQTY] [money] NOT NULL,
[GFTGID] [int] NOT NULL,
[GFTQTY] [money] NOT NULL,
[GFTLINE] [smallint] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__NGFTAGMDTL__STAT__0E99DA9F] DEFAULT (0),
[LSTID] [char] (16) COLLATE Chinese_PRC_CI_AS NULL,
[GFTWRH] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NGFTAGMDTL] ADD CONSTRAINT [PK__NGFTAGMDTL__0BBD6DF4] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE], [GFTLINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
