CREATE TABLE [dbo].[MXFDTL]
(
[NUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[WRH] [int] NOT NULL,
[QTY] [money] NOT NULL CONSTRAINT [DF__MXFDTL__QTY__2C201BE5] DEFAULT (0),
[FROMPRICE] [money] NOT NULL CONSTRAINT [DF__MXFDTL__FROMPRIC__2D14401E] DEFAULT (0),
[FROMTOTAL] [money] NOT NULL CONSTRAINT [DF__MXFDTL__FROMTOTA__2E086457] DEFAULT (0),
[FROMTAX] [money] NOT NULL CONSTRAINT [DF__MXFDTL__FROMTAX__2EFC8890] DEFAULT (0),
[TOPRICE] [money] NOT NULL CONSTRAINT [DF__MXFDTL__TOPRICE__2FF0ACC9] DEFAULT (0),
[TOTOTAL] [money] NOT NULL CONSTRAINT [DF__MXFDTL__TOTOTAL__30E4D102] DEFAULT (0),
[TOTAX] [money] NOT NULL CONSTRAINT [DF__MXFDTL__TOTAX__31D8F53B] DEFAULT (0),
[FROMCOST] [money] NOT NULL CONSTRAINT [DF__MXFDTL__FROMCOST__32CD1974] DEFAULT (0),
[TOCOST] [money] NOT NULL CONSTRAINT [DF__MXFDTL__TOCOST__33C13DAD] DEFAULT (0),
[SUBWRH] [int] NULL,
[INPRC] [money] NOT NULL CONSTRAINT [DF__MXFDTL__INPRC__34B561E6] DEFAULT (0),
[RTLPRC] [money] NOT NULL CONSTRAINT [DF__MXFDTL__RTLPRC__35A9861F] DEFAULT (0),
[CASES] [money] NOT NULL CONSTRAINT [DF__MXFDTL__CASES__0C140A5D] DEFAULT (0),
[BNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[FROMGDVDR] [int] NULL,
[FROMGDALC] [char] (10) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MXFDTL] ADD CONSTRAINT [PK__MXFDTL__5CE5B0D6] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
