CREATE TABLE [dbo].[VOUCHERGIVE]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__VOUCHERGIV__STAT__4A985129] DEFAULT (0),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__VOUCHERGI__FILLE__4B8C7562] DEFAULT ('未知[-]'),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__VOUCHERGI__FILDA__4C80999B] DEFAULT (getdate()),
[CHKDATE] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__VOUCHERGI__RECCN__4D74BDD4] DEFAULT (0),
[PRNTIME] [datetime] NULL,
[SRCLS] [smallint] NULL,
[UPDVCSTAT] [smallint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERGIVE] ADD CONSTRAINT [PK__VOUCHERGIVE__4E68E20D] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
