CREATE TABLE [dbo].[TMPSTKOUTGFTDTL]
(
[SPID] [int] NOT NULL,
[LISTNO] [int] NOT NULL,
[AGANUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MATCHTIME] [int] NOT NULL,
[GDGID] [int] NULL,
[ALCQTY] [decimal] (24, 2) NULL,
[GFTGID] [int] NULL,
[GFTQTY] [decimal] (24, 2) NULL,
[GFTWRH] [int] NULL,
[FLAG] [smallint] NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_TMPSTKOUTGFTDTL_SPID] ON [dbo].[TMPSTKOUTGFTDTL] ([SPID]) ON [PRIMARY]
GO
