CREATE TABLE [dbo].[CRMSCOPRIZGDRPT]
(
[CARDNUM] [varchar] (16) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRC] [int] NOT NULL CONSTRAINT [DF__CRMSCOPRIZG__SRC__60453921] DEFAULT (0),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__CRMSCOPRI__FILDA__61395D5A] DEFAULT (getdate()),
[STORECODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CRMSCOPRIZG__QTY__622D8193] DEFAULT (1),
[SCORE] [decimal] (24, 2) NOT NULL,
[SCORESORT] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMSCOPRI__SCORE__6321A5CC] DEFAULT ('-'),
[POSNO] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[FLOWNO] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[UUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NULL,
[BILLNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMSCOPRIZGDRPT] ADD CONSTRAINT [PK__CRMSCOPRIZGDRPT__6415CA05] PRIMARY KEY CLUSTERED  ([CARDNUM], [SRC], [FILDATE], [STORECODE], [GDGID]) ON [PRIMARY]
GO
