CREATE TABLE [dbo].[CMSENDLIST]
(
[CMCODE] [char] (2) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL,
[ACTION] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CMSENDLIST] ADD CONSTRAINT [PK__CMSENDLIST__2DA17D5F] PRIMARY KEY CLUSTERED  ([CMCODE], [STOREGID]) ON [PRIMARY]
GO
