CREATE TABLE [dbo].[PRMOFFSETAGM]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VDRGID] [int] NOT NULL,
[BEGINDATE] [datetime] NOT NULL CONSTRAINT [DF__PRMOFFSET__BEGIN__315474B7] DEFAULT (getdate()),
[ENDDATE] [datetime] NOT NULL CONSTRAINT [DF__PRMOFFSET__ENDDA__324898F0] DEFAULT (getdate()),
[SRC] [int] NOT NULL,
[STAT] [int] NOT NULL CONSTRAINT [DF__PRMOFFSETA__STAT__333CBD29] DEFAULT (0),
[OFFSETVIEW] [int] NOT NULL CONSTRAINT [DF__PRMOFFSET__OFFSE__3430E162] DEFAULT (0),
[SETTLENO] [int] NOT NULL,
[PSR] [int] NOT NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__PRMOFFSET__FILDA__3525059B] DEFAULT (getdate()),
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__PRMOFFSET__RECCN__361929D4] DEFAULT (0),
[DeptLmt] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[LSTUPDTIME] [datetime] NULL,
[LAUNCH] [datetime] NULL,
[COVERALL] [smallint] NOT NULL CONSTRAINT [DF__PRMOFFSET__COVER__370D4E0D] DEFAULT (0),
[OFFSETED] [smallint] NULL CONSTRAINT [DF__PRMOFFSET__OFFSE__38017246] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRMOFFSETAGM] ADD CONSTRAINT [PK__PRMOFFSETAGM__38F5967F] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
