CREATE TABLE [dbo].[AVTBILL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLIENT] [char] (40) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__AVTBILL__CLIENT__54582A71] DEFAULT ('顾客'),
[FILDATE] [datetime] NOT NULL,
[TOTAL] [money] NOT NULL,
[TAX] [money] NOT NULL,
[ASSISTANT] [int] NULL,
[ISSUSER] [int] NOT NULL,
[ISSUETIME] [datetime] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__AVTBILL__STAT__554C4EAA] DEFAULT (0),
[MODNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[PRNTIME] [datetime] NULL,
[PAYTERM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [smallint] NOT NULL,
[AVTNUM] [char] (16) COLLATE Chinese_PRC_CI_AS NULL,
[POSNO] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[FLOWNO] [char] (10) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AVTBILL] WITH NOCHECK ADD CONSTRAINT [AVTBILL_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[AVTBILL] ADD CONSTRAINT [PK__AVTBILL__11D4A34F] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
