CREATE TABLE [dbo].[MCKPOOL]
(
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[INPUTER] [int] NOT NULL CONSTRAINT [DF__MCKPOOL__INPUTER__3B4E1C33] DEFAULT (1),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__MCKPOOL__FILDATE__3C42406C] DEFAULT (getdate()),
[QTY] [money] NOT NULL CONSTRAINT [DF__MCKPOOL__QTY__3D3664A5] DEFAULT (0),
[INPRC] [money] NOT NULL CONSTRAINT [DF__MCKPOOL__INPRC__3E2A88DE] DEFAULT (0),
[PRICE] [money] NOT NULL CONSTRAINT [DF__MCKPOOL__PRICE__3F1EAD17] DEFAULT (0),
[AMOUNT] [money] NOT NULL CONSTRAINT [DF__MCKPOOL__AMOUNT__4012D150] DEFAULT (0),
[CheckTag] [int] NOT NULL CONSTRAINT [DF__MCKPOOL__CheckTa__4106F589] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MCKPOOL] ADD CONSTRAINT [PK__MCKPOOL__3A59F7FA] PRIMARY KEY CLUSTERED  ([POSNO], [GDGID]) ON [PRIMARY]
GO
