CREATE TABLE [dbo].[INVMRPT]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[BGDGID] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[CQ] [money] NULL CONSTRAINT [DF__INVMRPT__CQ__236A0EFC] DEFAULT (0),
[CT] [money] NULL CONSTRAINT [DF__INVMRPT__CT__245E3335] DEFAULT (0),
[FQ] [money] NULL CONSTRAINT [DF__INVMRPT__FQ__2552576E] DEFAULT (0),
[FT] [money] NULL CONSTRAINT [DF__INVMRPT__FT__26467BA7] DEFAULT (0),
[FINPRC] [money] NULL CONSTRAINT [DF__INVMRPT__FINPRC__273A9FE0] DEFAULT (0),
[FRTLPRC] [money] NULL CONSTRAINT [DF__INVMRPT__FRTLPRC__282EC419] DEFAULT (0),
[FDXPRC] [money] NULL CONSTRAINT [DF__INVMRPT__FDXPRC__2922E852] DEFAULT (0),
[FPAYRATE] [money] NULL CONSTRAINT [DF__INVMRPT__FPAYRAT__2A170C8B] DEFAULT (0),
[FINVPRC] [money] NULL CONSTRAINT [DF__INVMRPT__FINVPRC__2B0B30C4] DEFAULT (0),
[FLSTINPRC] [money] NULL CONSTRAINT [DF__INVMRPT__FLSTINP__2BFF54FD] DEFAULT (0),
[FINVCOST] [money] NOT NULL CONSTRAINT [DF__INVMRPT__FINVCOS__3A235722] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INVMRPT] ADD CONSTRAINT [PK__INVMRPT__0169315C] PRIMARY KEY CLUSTERED  ([ASETTLENO], [BGDGID], [BWRH], [ASTORE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
