CREATE TABLE [dbo].[SORTCLIENT]
(
[ACODE] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SCODE] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GID] [int] NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__SORTCLIEN__LSTUP__65B9574B] DEFAULT (getdate()),
[SORTTARGET1] [money] NOT NULL CONSTRAINT [DF__SORTCLIEN__SORTT__596AF104] DEFAULT ((-1))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SORTCLIENT] ADD CONSTRAINT [PK__SORTCLIENT__66AD7B84] PRIMARY KEY CLUSTERED  ([ACODE], [SCODE], [GID]) ON [PRIMARY]
GO
