CREATE TABLE [dbo].[PSFORMULAENT]
(
[CODE] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FCODE] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[RANGE] [int] NOT NULL CONSTRAINT [DF__PSFORMULA__RANGE__00C3E9F0] DEFAULT (7),
[RANGEUNIT] [smallint] NOT NULL CONSTRAINT [DF__PSFORMULA__RANGE__01B80E29] DEFAULT (0),
[BGNDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__PSFORMULA__LSTUP__02AC3262] DEFAULT (getdate()),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSFORMULAENT] ADD CONSTRAINT [PK__PSFORMULAEnt__03A0569B] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [UQ_PSFORMULAPARAM_NAME] ON [dbo].[PSFORMULAENT] ([NAME]) ON [PRIMARY]
GO
