CREATE TABLE [dbo].[GDPRCADJ]
(
[GDGID] [int] NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTADJTIME] [datetime] NULL,
[PRCADJNUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NULL,
[PRCADJFILDATE] [datetime] NULL,
[GDQPCSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__GDPRCADJ__GDQPCS__2C82709D] DEFAULT ('1*1')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GDPRCADJ] ADD CONSTRAINT [PK__GDPRCADJ__2B793DCB] PRIMARY KEY CLUSTERED  ([GDGID], [CLS], [GDQPCSTR]) ON [PRIMARY]
GO
