CREATE TABLE [dbo].[STORESCOSCHEME]
(
[CODE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[MODIFIER] [int] NOT NULL CONSTRAINT [DF__STORESCOS__MODIF__2D7432D1] DEFAULT (1),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__STORESCOS__LSTUP__2E68570A] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STORESCOSCHEME] ADD CONSTRAINT [PK__STORESCOSCHEME__2C800E98] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
