CREATE TABLE [dbo].[PSGDLIST]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LISTNAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LISTTYPE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LISTCLS] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__PSGDLIST__FILDAT__30A8073C] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__PSGDLIST__STAT__319C2B75] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__PSGDLIST__RECCNT__32904FAE] DEFAULT (0),
[SRCNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[LSTUPDTIME] [datetime] NULL,
[ISSUER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ISSUETIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSGDLIST] ADD CONSTRAINT [PK__PSGDLIST__338473E7] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [INDEX_PSGDLIST_FILDATE] ON [dbo].[PSGDLIST] ([FILDATE]) ON [PRIMARY]
GO
