CREATE TABLE [dbo].[BILLMEMO]
(
[MODULEID] [int] NOT NULL,
[BILLNUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[GID] [int] NOT NULL,
[LINE] [int] NOT NULL,
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__BILLMEMO__LSTUPD__3A874288] DEFAULT (getdate()),
[CREATETIME] [datetime] NOT NULL CONSTRAINT [DF__BILLMEMO__CREATE__3B7B66C1] DEFAULT (getdate()),
[STAT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BILLMEMO] ADD CONSTRAINT [PK__BILLMEMO__3C6F8AFA] PRIMARY KEY CLUSTERED  ([MODULEID], [BILLNUM], [GID], [LINE]) ON [PRIMARY]
GO
