CREATE TABLE [dbo].[INVCHG]
(
[SRC] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[GDGID2] [int] NOT NULL,
[RELQTY] [money] NOT NULL CONSTRAINT [DF__INVCHG__RELQTY__2F0840DF] DEFAULT (1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INVCHG] ADD CONSTRAINT [PK__INVCHG__7BBC1055] PRIMARY KEY CLUSTERED  ([GDGID], [GDGID2]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
