CREATE TABLE [dbo].[PSATTRIBUTEEX]
(
[CODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GRADE] [int] NOT NULL CONSTRAINT [DF__PSATTRIBU__GRADE__76907440] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[AGROUP] [int] NOT NULL CONSTRAINT [DF__PSATTRIBU__AGROU__77849879] DEFAULT (0),
[ACLS] [int] NOT NULL CONSTRAINT [DF__PSATTRIBUT__ACLS__7878BCB2] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSATTRIBUTEEX] ADD CONSTRAINT [PK__PSATTRIBUTEEX__796CE0EB] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IDX_PSATTRIBUTEEX_NAME] ON [dbo].[PSATTRIBUTEEX] ([NAME]) ON [PRIMARY]
GO
