CREATE TABLE [dbo].[GDINVCHGNOTIFY]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__GDINVCHGN__FILDA__2BA42654] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[STAT] [smallint] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__GDINVCHGN__RECCN__2C984A8D] DEFAULT (0),
[LAUNCH] [datetime] NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__GDINVCHGN__LSTUP__2D8C6EC6] DEFAULT (getdate()),
[EON] [smallint] NOT NULL CONSTRAINT [DF__GDINVCHGNOT__EON__2E8092FF] DEFAULT (0),
[SETPKG] [smallint] NOT NULL CONSTRAINT [DF__GDINVCHGN__SETPK__2F74B738] DEFAULT (0),
[SRC] [int] NOT NULL,
[EXDIRECT] [smallint] NOT NULL CONSTRAINT [DF__GDINVCHGN__EXDIR__5DB08334] DEFAULT (1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GDINVCHGNOTIFY] ADD CONSTRAINT [PK__GDINVCHGNOTIFY__3068DB71] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [GDINVCHGNOTIFY_FILDATE] ON [dbo].[GDINVCHGNOTIFY] ([FILDATE]) ON [PRIMARY]
GO
