CREATE TABLE [dbo].[TK_NTOKENINFO]
(
[ID] [int] NOT NULL CONSTRAINT [DF__TK_NTOKENINF__ID__3FC7ED36] DEFAULT (0),
[SERIALNO] [varchar] (16) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ATYPE] [int] NOT NULL CONSTRAINT [DF__TK_NTOKEN__ATYPE__40BC116F] DEFAULT (0),
[SECUREKEY] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[INITTIME] [int] NOT NULL CONSTRAINT [DF__TK_NTOKEN__INITT__41B035A8] DEFAULT (0),
[DIFFERENCE] [int] NOT NULL CONSTRAINT [DF__TK_NTOKEN__DIFFE__42A459E1] DEFAULT (0),
[INITTOKENTIME] [int] NULL CONSTRAINT [DF__TK_NTOKEN__INITT__43987E1A] DEFAULT (0),
[STATE] [int] NOT NULL CONSTRAINT [DF__TK_NTOKEN__STATE__448CA253] DEFAULT (1),
[LASTTIME] [int] NOT NULL CONSTRAINT [DF__TK_NTOKEN__LASTT__4580C68C] DEFAULT (0),
[ADTIME] [datetime] NOT NULL CONSTRAINT [DF__TK_NTOKEN__ADTIM__4674EAC5] DEFAULT (getdate()),
[HDDIFF] [int] NOT NULL CONSTRAINT [DF__TK_NTOKEN__HDDIF__47690EFE] DEFAULT (0),
[ERRTIMES] [int] NOT NULL CONSTRAINT [DF__TK_NTOKEN__ERRTI__485D3337] DEFAULT (0),
[LASTAUTHTIME] [datetime] NOT NULL CONSTRAINT [DF__TK_NTOKEN__LASTA__49515770] DEFAULT (getdate()),
[TOTALAUTH] [int] NOT NULL CONSTRAINT [DF__TK_NTOKEN__TOTAL__4A457BA9] DEFAULT (0),
[TOTALSUCC] [int] NOT NULL CONSTRAINT [DF__TK_NTOKEN__TOTAL__4B399FE2] DEFAULT (0),
[SUCCTOKEN] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[SNDTIME] [datetime] NOT NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [int] NOT NULL CONSTRAINT [DF__TK_NTOKENI__TYPE__4C2DC41B] DEFAULT (0),
[NSTAT] [int] NOT NULL CONSTRAINT [DF__TK_NTOKEN__NSTAT__4D21E854] DEFAULT (0),
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
