CREATE TABLE [dbo].[CRMMBRPROMSUBJINV]
(
[UUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STORE] [int] NOT NULL CONSTRAINT [DF__CRMMBRPRO__STORE__762A589F] DEFAULT (0),
[SUBJCODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ALLMBR] [smallint] NOT NULL CONSTRAINT [DF__CRMMBRPRO__ALLMB__771E7CD8] DEFAULT (0),
[OPER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OPERTIME] [datetime] NOT NULL CONSTRAINT [DF__CRMMBRPRO__OPERT__7812A111] DEFAULT (getdate()),
[SRCNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMMBRPROMSUBJINV] ADD CONSTRAINT [PK__CRMMBRPROMSUBJIN__7906C54A] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_MBRPROMSUBJ_SUBJ] ON [dbo].[CRMMBRPROMSUBJINV] ([SUBJCODE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_MBRPROMSUBJ_SUBJMBR] ON [dbo].[CRMMBRPROMSUBJINV] ([SUBJCODE], [ALLMBR]) ON [PRIMARY]
GO
