CREATE TABLE [dbo].[CRMCARDDESHST]
(
[CARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARRIER] [int] NOT NULL CONSTRAINT [DF__CRMCARDDE__CARRI__74676955] DEFAULT (1),
[OLDBAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCARDDE__OLDBA__755B8D8E] DEFAULT (0),
[OCCUR] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCARDDE__OCCUR__764FB1C7] DEFAULT (0),
[NUM] [char] (26) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMCARDDESHST] ADD CONSTRAINT [PK__CRMCARDDESHST__7743D600] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
