CREATE TABLE [dbo].[COUPONEXCHANGELOG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TIME] [datetime] NOT NULL,
[ACTION] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_COUPONEXCHANGELOG_1] ON [dbo].[COUPONEXCHANGELOG] ([NUM]) ON [PRIMARY]
GO
