CREATE TABLE [dbo].[PS3_ONLINEPROMACTSTORE]
(
[ACTIVITY] [varchar] (60) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STORECODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3_ONLINEPROMACTSTORE] ADD CONSTRAINT [PK__PS3_ONLI__88E41C587F2C14F9] PRIMARY KEY CLUSTERED  ([ACTIVITY], [STORECODE]) ON [PRIMARY]
GO
