CREATE TABLE [dbo].[PayDtlDtl]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[WRH] [int] NOT NULL,
[BVDRGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PayDtlDtl] ADD CONSTRAINT [PK__PAYDTLDTL] PRIMARY KEY CLUSTERED  ([NUM], [GDGID], [ASETTLENO], [ADATE], [WRH], [BVDRGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [paydtldtl_gdgid] ON [dbo].[PayDtlDtl] ([GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
