CREATE TABLE [dbo].[CK]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NULL,
[CKDATE] [datetime] NULL CONSTRAINT [DF__CK__CKDATE__43EBED27] DEFAULT (getdate()),
[FILLER] [int] NULL,
[OVFAMT] [money] NULL CONSTRAINT [DF__CK__OVFAMT__44E01160] DEFAULT (0),
[LOSAMT] [money] NULL CONSTRAINT [DF__CK__LOSAMT__45D43599] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[CLS] [smallint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CK] WITH NOCHECK ADD CONSTRAINT [CK_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[CK] ADD CONSTRAINT [PK__CK__26CFC035] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [CKDATE] ON [dbo].[CK] ([CKDATE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
