CREATE TABLE [dbo].[NPRMOFFSETAGM]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__NPRMOFFSET__STAT__4467492B] DEFAULT (0),
[VDRGID] [int] NOT NULL,
[BEGINDATE] [datetime] NOT NULL CONSTRAINT [DF__NPRMOFFSE__BEGIN__455B6D64] DEFAULT (getdate()),
[ENDDATE] [datetime] NOT NULL CONSTRAINT [DF__NPRMOFFSE__ENDDA__464F919D] DEFAULT (getdate()),
[OFFSETVIEW] [int] NOT NULL CONSTRAINT [DF__NPRMOFFSE__OFFSE__4743B5D6] DEFAULT (0),
[PSR] [int] NOT NULL,
[DeptLmt] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[LAUNCH] [datetime] NULL,
[COVERALL] [smallint] NOT NULL CONSTRAINT [DF__NPRMOFFSE__COVER__4837DA0F] DEFAULT (0),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NPRMOFFSE__FILDA__492BFE48] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NPRMOFFSE__FILLE__4A202281] DEFAULT ('未知[-]'),
[CHKDATE] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPRMOFFSETAGM] ADD CONSTRAINT [PK__NPRMOFFSETAGM__4B1446BA] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPRMOFFSETAGM_NUM] ON [dbo].[NPRMOFFSETAGM] ([NUM]) ON [PRIMARY]
GO
