CREATE TABLE [dbo].[SHOULDEXCHGDATADTL]
(
[SENDDATE] [datetime] NOT NULL,
[SRC] [int] NOT NULL,
[TGT] [int] NOT NULL,
[CLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHECKINT1] [int] NOT NULL CONSTRAINT [DF__SHOULDEXC__CHECK__78A077DF] DEFAULT (0),
[CHECKINT2] [int] NOT NULL CONSTRAINT [DF__SHOULDEXC__CHECK__79949C18] DEFAULT (0),
[CHECKINT3] [int] NOT NULL CONSTRAINT [DF__SHOULDEXC__CHECK__7A88C051] DEFAULT (0),
[CHECKDATA1] [decimal] (20, 2) NOT NULL CONSTRAINT [DF__SHOULDEXC__CHECK__7B7CE48A] DEFAULT (0),
[CHECKDATA2] [decimal] (20, 2) NOT NULL CONSTRAINT [DF__SHOULDEXC__CHECK__7C7108C3] DEFAULT (0),
[CHECKDATA3] [decimal] (20, 2) NOT NULL CONSTRAINT [DF__SHOULDEXC__CHECK__7D652CFC] DEFAULT (0),
[FINISHED] [int] NOT NULL CONSTRAINT [DF__SHOULDEXC__FINIS__7E595135] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SHOULDEXCHGDATADTL] ADD CONSTRAINT [PK__SHOULDEXCHGDATAD__77AC53A6] PRIMARY KEY CLUSTERED  ([SENDDATE], [SRC], [TGT], [CLS], [NUM]) ON [PRIMARY]
GO
