CREATE TABLE [dbo].[CQNPKG]
(
[GROUPID] [int] NOT NULL,
[RHQUUID] [char] (32) COLLATE Chinese_PRC_CI_AS NULL,
[NTYPE] [int] NOT NULL,
[NSTAT] [int] NOT NULL CONSTRAINT [DF__CQNPKG__NSTAT__15A92CE6] DEFAULT (0),
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[EXTIME] [datetime] NOT NULL CONSTRAINT [DF__CQNPKG__EXTIME__169D511F] DEFAULT (getdate()),
[EGID] [int] NOT NULL,
[PGID] [int] NOT NULL,
[QTY] [decimal] (24, 4) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CQNPKG] ADD CONSTRAINT [PK__CQNPKG__17917558] PRIMARY KEY CLUSTERED  ([NTYPE], [GROUPID], [PGID]) ON [PRIMARY]
GO
