CREATE TABLE [dbo].[CRMALERTSORT]
(
[ALERTTYPE] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GRADE] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMALERTSORT] ADD CONSTRAINT [PK__CRMALERTSORT__399BA942] PRIMARY KEY CLUSTERED  ([ALERTTYPE]) ON [PRIMARY]
GO
