CREATE TABLE [dbo].[CQNGDINPUT]
(
[GROUPID] [int] NOT NULL,
[RHQUUID] [char] (32) COLLATE Chinese_PRC_CI_AS NULL,
[NTYPE] [int] NOT NULL,
[NSTAT] [int] NOT NULL CONSTRAINT [DF__CQNGDINPU__NSTAT__0FF05390] DEFAULT (0),
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[EXTIME] [datetime] NOT NULL CONSTRAINT [DF__CQNGDINPU__EXTIM__10E477C9] DEFAULT (getdate()),
[CODE] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CODETYPE] [smallint] NOT NULL CONSTRAINT [DF__CQNGDINPU__CODET__11D89C02] DEFAULT (0),
[GID] [int] NOT NULL,
[FLAGS] [int] NOT NULL CONSTRAINT [DF__CQNGDINPU__FLAGS__12CCC03B] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CQNGDINPUT] ADD CONSTRAINT [PK__CQNGDINPUT__13C0E474] PRIMARY KEY CLUSTERED  ([NTYPE], [GROUPID], [CODE]) ON [PRIMARY]
GO
