CREATE TABLE [dbo].[ORDCHKLVL]
(
[ID] [int] NOT NULL,
[AMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__ORDCHKLVL__AMT__0568A37C] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORDCHKLVL] ADD CONSTRAINT [PK__ORDCHKLVL__065CC7B5] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
