CREATE TABLE [dbo].[CRMCARDSALESETTLEMENT]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PAY] [decimal] (24, 2) NOT NULL,
[PREPAY] [decimal] (24, 2) NOT NULL,
[DEBTPAY] [decimal] (24, 2) NOT NULL,
[CURRENCY] [int] NOT NULL,
[SETTLEMENT] [decimal] (24, 2) NOT NULL,
[OPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OPERTIME] [datetime] NOT NULL CONSTRAINT [DF__CRMCARDSA__OPERT__73FD5501] DEFAULT (getdate()),
[BEGINSTAT] [smallint] NOT NULL,
[ENDSTAT] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMCARDSALESETTLEMENT] ADD CONSTRAINT [PK__CRMCARDSALESETTL__74F1793A] PRIMARY KEY CLUSTERED  ([NUM], [OPER], [OPERTIME]) ON [PRIMARY]
GO
