CREATE TABLE [dbo].[INPRCPRMDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SETTLENO] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[ASTART] [datetime] NOT NULL CONSTRAINT [DF__INPRCPRMD__ASTAR__1E7B3CAD] DEFAULT (getdate()),
[AFINISH] [datetime] NOT NULL CONSTRAINT [DF__INPRCPRMD__AFINI__1F6F60E6] DEFAULT ('9999.12.31 23:59:59'),
[PRICE] [money] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INPRCPRMDTL] ADD CONSTRAINT [PK__INPRCPRMDTL__1D871874] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
