CREATE TABLE [dbo].[STEELYARDSENDLOG]
(
[CODE] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[OPERTIME] [datetime] NULL,
[SYID] [int] NULL,
[STAT] [int] NOT NULL CONSTRAINT [DF__STEELYARDS__STAT__018303FF] DEFAULT (0)
) ON [PRIMARY]
GO
