CREATE TABLE [dbo].[NINVCHG]
(
[SRC] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[GDGID2] [int] NOT NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[RELQTY] [money] NULL CONSTRAINT [DF__NINVCHG__RELQTY__2FFC6518] DEFAULT (1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NINVCHG] ADD CONSTRAINT [PK__NINVCHG__7DA458C7] PRIMARY KEY CLUSTERED  ([GDGID], [GDGID2], [RCV]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
