CREATE TABLE [dbo].[ICCARDBLKLST]
(
[CARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ICCARDBLKLST] ON [dbo].[ICCARDBLKLST] ([CARDNUM] DESC) WITH (FILLFACTOR=80, PAD_INDEX=ON) ON [PRIMARY]
GO
