CREATE TABLE [dbo].[ALCGFT]
(
[SRCNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ALCGID] [int] NOT NULL,
[START] [datetime] NOT NULL,
[FINISH] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ALCGFT] ADD CONSTRAINT [PK__ALCGFT__1BD70788] PRIMARY KEY CLUSTERED  ([SRCNUM]) ON [PRIMARY]
GO
