CREATE TABLE [dbo].[VOUCHERLAUNCHSCOPETEMPLATESTORE]
(
[CODE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERLAUNCHSCOPETEMPLATESTORE] ADD CONSTRAINT [PK__VOUCHERLAUNCHSCO__75FDD968] PRIMARY KEY CLUSTERED  ([CODE], [STOREGID]) ON [PRIMARY]
GO
