CREATE TABLE [dbo].[SUBWRH]
(
[GID] [int] NOT NULL,
[CODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[WRH] [int] NOT NULL,
[ALENGTH] [money] NULL,
[AWIDTH] [money] NULL,
[AHEIGHT] [money] NULL,
[WEIGHT] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[GDGID] [int] NOT NULL CONSTRAINT [DF__SUBWRH__GDGID__5C043931] DEFAULT (1),
[INPRC] [money] NOT NULL CONSTRAINT [DF__SUBWRH__INPRC__5CF85D6A] DEFAULT (0),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__SUBWRH__LSTUPDTI__5DEC81A3] DEFAULT (getdate())
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[SUBWRH_UPD] ON [dbo].[SUBWRH] FOR UPDATE AS
BEGIN
	UPDATE SUBWRH SET LSTUPDTIME = GETDATE()
		FROM INSERTED I
		WHERE  SUBWRH.GID = I.GID AND SUBWRH.GDGID = I.GDGID

END
GO
ALTER TABLE [dbo].[SUBWRH] ADD CONSTRAINT [PK__SUBWRH__50A6C9C7] PRIMARY KEY NONCLUSTERED  ([GID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SUBWRH] ADD CONSTRAINT [UQ__SUBWRH__284DF453] UNIQUE CLUSTERED  ([CODE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
