CREATE TABLE [dbo].[PAYRATEPRICE]
(
[STOREGID] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[QPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PAYRATEPRIC__QPC__7C3F2BF5] DEFAULT (1),
[QPCSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PAYRATEPR__QPCST__7D33502E] DEFAULT ('1*1'),
[ASTART] [datetime] NOT NULL CONSTRAINT [DF__PAYRATEPR__ASTAR__7E277467] DEFAULT (getdate()),
[AFINISH] [datetime] NOT NULL CONSTRAINT [DF__PAYRATEPR__AFINI__7F1B98A0] DEFAULT ('9999.12.31 23:59:59'),
[PAYRATE] [decimal] (24, 4) NOT NULL,
[SRCNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [UQ_INPRICE] ON [dbo].[PAYRATEPRICE] ([STOREGID], [GDGID], [ASTART], [AFINISH], [QPCSTR]) ON [PRIMARY]
GO
