CREATE TABLE [dbo].[CTCNTRRATEDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VERSION] [smallint] NOT NULL,
[LINE] [smallint] NOT NULL,
[FEEUNIT] [char] (4) COLLATE Chinese_PRC_CI_AS NULL,
[FEECYCLE] [smallint] NULL,
[FEEDAYOFFSET] [smallint] NULL,
[FSTFEEDATE] [datetime] NULL,
[NEXTBEGINDATE] [datetime] NULL,
[NEXTENDDATE] [datetime] NULL,
[FIXCOST] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CTCNTRRAT__FIXCO__38727ADF] DEFAULT (0),
[RATEMODE] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CTCNTRRAT__RATEM__39669F18] DEFAULT ('数值分段'),
[CALCMODE] [varchar] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FEEPREC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CTCNTRRAT__FEEPR__3B4EE78A] DEFAULT (0.01),
[ROUNDTYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CTCNTRRAT__ROUND__3C430BC3] DEFAULT ('四舍五入'),
[STORESCOPE] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CTCNTRRAT__STORE__3D372FFC] DEFAULT ('全部'),
[GDSCOPE] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CTCNTRRAT__GDSCO__3E2B5435] DEFAULT ('全部'),
[GDSCOPESQL] [char] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[GDSCOPETEXT] [char] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[AHEADDAYS] [int] NOT NULL CONSTRAINT [DF__CTCNTRRAT__AHEAD__3F1F786E] DEFAULT (0),
[DISCOUNTRATE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CTCNTRRAT__DISCO__40139CA7] DEFAULT (0),
[LIMITTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CTCNTRRAT__LIMIT__0E61098C] DEFAULT (0),
[SUMTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CTCNTRRAT__SUMTO__0F552DC5] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CTCNTRRATEDTL] ADD CONSTRAINT [PK__CTCNTRRATEDTL__4107C0E0] PRIMARY KEY CLUSTERED  ([NUM], [VERSION], [LINE]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[DF__CTCNTRRAT__CALCM__12345678]', N'[dbo].[CTCNTRRATEDTL].[CALCMODE]'
GO
