CREATE TABLE [dbo].[NVDRDRPT]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ASTORE] [int] NULL,
[ASETTLENO] [int] NULL,
[ADATE] [datetime] NULL,
[BVDRGID] [int] NULL,
[BWRH] [int] NULL,
[BGDGID] [int] NULL,
[DQ1] [money] NULL CONSTRAINT [DF__NVDRDRPT__DQ1__4B97FBE7] DEFAULT (0),
[DQ2] [money] NULL CONSTRAINT [DF__NVDRDRPT__DQ2__4C8C2020] DEFAULT (0),
[DQ3] [money] NULL CONSTRAINT [DF__NVDRDRPT__DQ3__4D804459] DEFAULT (0),
[DQ4] [money] NULL CONSTRAINT [DF__NVDRDRPT__DQ4__4E746892] DEFAULT (0),
[DQ5] [money] NULL CONSTRAINT [DF__NVDRDRPT__DQ5__4F688CCB] DEFAULT (0),
[DQ6] [money] NULL CONSTRAINT [DF__NVDRDRPT__DQ6__505CB104] DEFAULT (0),
[DT1] [money] NULL CONSTRAINT [DF__NVDRDRPT__DT1__5150D53D] DEFAULT (0),
[DT2] [money] NULL CONSTRAINT [DF__NVDRDRPT__DT2__5244F976] DEFAULT (0),
[DT3] [money] NULL CONSTRAINT [DF__NVDRDRPT__DT3__53391DAF] DEFAULT (0),
[DT4] [money] NULL CONSTRAINT [DF__NVDRDRPT__DT4__542D41E8] DEFAULT (0),
[DT5] [money] NULL CONSTRAINT [DF__NVDRDRPT__DT5__55216621] DEFAULT (0),
[DT6] [money] NULL CONSTRAINT [DF__NVDRDRPT__DT6__56158A5A] DEFAULT (0),
[DT7] [money] NULL CONSTRAINT [DF__NVDRDRPT__DT7__5709AE93] DEFAULT (0),
[NSTAT] [smallint] NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NULL,
[RCV] [int] NULL,
[SNDTIME] [datetime] NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NULL,
[di2] [money] NULL CONSTRAINT [DF__nvdrdrpt__di2__24DE2179] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVDRDRPT] ADD CONSTRAINT [PK__NVDRDRPT__546180BB] PRIMARY KEY CLUSTERED  ([ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
