CREATE TABLE [dbo].[IPA2SWDTL]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SUBWRH] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[INBILL] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[INCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[INNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[INLINE] [smallint] NOT NULL,
[INCHKDATE] [datetime] NULL,
[QTY] [money] NOT NULL CONSTRAINT [DF__IPA2SWDTL__QTY__65589941] DEFAULT (0),
[ADJCOST] [money] NOT NULL,
[NEWPRC] [money] NOT NULL,
[COST] [money] NOT NULL CONSTRAINT [DF__IPA2SWDTL__COST__664CBD7A] DEFAULT (0),
[ADJINCOST] [money] NOT NULL CONSTRAINT [DF__IPA2SWDTL__ADJIN__6740E1B3] DEFAULT (0),
[ADJINVCOST] [money] NOT NULL CONSTRAINT [DF__IPA2SWDTL__ADJIN__683505EC] DEFAULT (0),
[ADJOUTCOST] [money] NOT NULL CONSTRAINT [DF__IPA2SWDTL__ADJOU__69292A25] DEFAULT (0),
[ADJALCAMT] [money] NOT NULL CONSTRAINT [DF__IPA2SWDTL__ADJAL__6A1D4E5E] DEFAULT (0),
[PAYAMT] [money] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IPA2SWDTL] ADD CONSTRAINT [PK__IPA2SWDTL__64647508] PRIMARY KEY CLUSTERED  ([CLS], [NUM], [SUBWRH]) ON [PRIMARY]
GO
