CREATE TABLE [dbo].[PROMOTE]
(
[STORE] [int] NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLLINE] [smallint] NOT NULL,
[ASTART] [datetime] NOT NULL,
[AFINISH] [datetime] NOT NULL,
[CYCLE] [datetime] NULL,
[CSTART] [datetime] NULL,
[CFINISH] [datetime] NULL,
[CSPEC] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[GDGID] [int] NOT NULL,
[GDCODE] [varchar] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[QTY] [decimal] (24, 4) NULL,
[PSETTLENO] [int] NULL,
[OCRTIME] [datetime] NOT NULL CONSTRAINT [DF__PROMOTE__OCRTIME__5E44B4BA] DEFAULT (getdate()),
[FIXRATIO] [decimal] (24, 4) NULL,
[GFTRATIO] [decimal] (24, 4) NULL,
[FLAG] [int] NOT NULL CONSTRAINT [DF__PROMOTE__FLAG__5F38D8F3] DEFAULT (0),
[HASCOND] [int] NOT NULL CONSTRAINT [DF__PROMOTE__HASCOND__602CFD2C] DEFAULT (0),
[EXPROM] [int] NOT NULL CONSTRAINT [DF__PROMOTE__EXPROM__61212165] DEFAULT (0),
[QPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PROMOTE__QPC__6215459E] DEFAULT (1),
[OVERWRITERULE] [smallint] NOT NULL CONSTRAINT [DF__PROMOTE__OVERWRI__27402F41] DEFAULT (0),
[FLAG2] [smallint] NOT NULL CONSTRAINT [DF__PROMOTE__FLAG2__2913691A] DEFAULT (0),
[GDCODE2] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[CALBYRTLPRC] [tinyint] NOT NULL CONSTRAINT [DF__PROMOTE__CALBYRT__779CD46E] DEFAULT (0),
[DLTPRICEPROM] [smallint] NOT NULL CONSTRAINT [DF__PROMOTE__DLTPRIC__243A70BB] DEFAULT (0),
[ONLYMEMBER] [tinyint] NOT NULL CONSTRAINT [DF__PROMOTE__ONLYMEM__29F34A11] DEFAULT (0),
[PRIORITY] [int] NOT NULL CONSTRAINT [DF__PROMOTE__PRIORIT__1D193D37] DEFAULT (0),
[PREC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PROMOTE__PREC__5BECFA5D] DEFAULT (1.0),
[ROUNDTYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PROMOTE__ROUNDTY__5CE11E96] DEFAULT ('四舍五入')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROMOTE] ADD CONSTRAINT [PK__PROMOTE__667D3564] PRIMARY KEY CLUSTERED  ([STORE], [CLS], [BILLNUM], [BILLLINE], [FLAG], [GDGID], [GDCODE]) ON [PRIMARY]
GO
