CREATE TABLE [dbo].[FAFUNCTREELEAF]
(
[PRODUCT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NODENO] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MODULENO] [int] NOT NULL,
[MODULETYPE] [smallint] NOT NULL,
[MODULENAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[ORDERNUM] [int] NOT NULL,
[ISSHOW] [smallint] NOT NULL CONSTRAINT [DF__FAFUNCTRE__ISSHO__13979299] DEFAULT (1),
[TAG] [smallint] NOT NULL CONSTRAINT [DF__FAFUNCTREEL__TAG__148BB6D2] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FAFUNCTREELEAF] ADD CONSTRAINT [PK__FAFUNCTREELEAF__157FDB0B] PRIMARY KEY CLUSTERED  ([PRODUCT], [NODENO], [MODULENO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_FAFUNCTREELEAF] ON [dbo].[FAFUNCTREELEAF] ([PRODUCT], [NODENO], [MODULETYPE], [ORDERNUM]) ON [PRIMARY]
GO
