CREATE TABLE [dbo].[COLLATE]
(
[NO] [smallint] NOT NULL,
[TABLENAME] [char] (32) COLLATE Chinese_PRC_CI_AS NULL,
[TABLELABEL] [char] (64) COLLATE Chinese_PRC_CI_AS NULL,
[STYLE] [char] (2) COLLATE Chinese_PRC_CI_AS NULL,
[MASTER] [smallint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COLLATE] ADD CONSTRAINT [PK__COLLATE__324172E1] PRIMARY KEY CLUSTERED  ([NO]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
