CREATE TABLE [dbo].[CRMMODIFYCARDDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[CARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARRIER] [int] NOT NULL,
[BALANCE] [decimal] (24, 2) NOT NULL,
[ADJUST] [decimal] (24, 2) NOT NULL,
[MODIFYTYPE] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[MODIFYREASON] [char] (80) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMMODIFYCARDDTL] ADD CONSTRAINT [PK__CRMMODIFYCARDDTL__5578CDE1] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
