CREATE TABLE [dbo].[INMRPTX]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[BGDGID] [int] NOT NULL,
[BVDRGID] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[DTN1] [money] NOT NULL CONSTRAINT [DF__INMRPTX__DTN1__65A37D5B] DEFAULT (0),
[DTN2] [money] NOT NULL CONSTRAINT [DF__INMRPTX__DTN2__6697A194] DEFAULT (0),
[DTN3] [money] NOT NULL CONSTRAINT [DF__INMRPTX__DTN3__678BC5CD] DEFAULT (0),
[DTN4] [money] NOT NULL CONSTRAINT [DF__INMRPTX__DTN4__687FEA06] DEFAULT (0),
[DTN5] [money] NOT NULL CONSTRAINT [DF__INMRPTX__DTN5__69740E3F] DEFAULT (0),
[DTN6] [money] NOT NULL CONSTRAINT [DF__INMRPTX__DTN6__6A683278] DEFAULT (0),
[DTN7] [money] NOT NULL CONSTRAINT [DF__INMRPTX__DTN7__6B5C56B1] DEFAULT (0),
[DTX1] [money] NOT NULL CONSTRAINT [DF__INMRPTX__DTX1__6C507AEA] DEFAULT (0),
[DTX2] [money] NOT NULL CONSTRAINT [DF__INMRPTX__DTX2__6D449F23] DEFAULT (0),
[DTX3] [money] NOT NULL CONSTRAINT [DF__INMRPTX__DTX3__6E38C35C] DEFAULT (0),
[DTX4] [money] NOT NULL CONSTRAINT [DF__INMRPTX__DTX4__6F2CE795] DEFAULT (0),
[DTX5] [money] NOT NULL CONSTRAINT [DF__INMRPTX__DTX5__70210BCE] DEFAULT (0),
[DTX6] [money] NOT NULL CONSTRAINT [DF__INMRPTX__DTX6__71153007] DEFAULT (0),
[DTX7] [money] NOT NULL CONSTRAINT [DF__INMRPTX__DTX7__72095440] DEFAULT (0),
[DIN1] [money] NOT NULL CONSTRAINT [DF__INMRPTX__DIN1__72FD7879] DEFAULT (0),
[DIN2] [money] NOT NULL CONSTRAINT [DF__INMRPTX__DIN2__73F19CB2] DEFAULT (0),
[DIN3] [money] NOT NULL CONSTRAINT [DF__INMRPTX__DIN3__74E5C0EB] DEFAULT (0),
[DIN4] [money] NOT NULL CONSTRAINT [DF__INMRPTX__DIN4__75D9E524] DEFAULT (0),
[DIN5] [money] NOT NULL CONSTRAINT [DF__INMRPTX__DIN5__76CE095D] DEFAULT (0),
[DIN6] [money] NOT NULL CONSTRAINT [DF__INMRPTX__DIN6__77C22D96] DEFAULT (0),
[DIN7] [money] NOT NULL CONSTRAINT [DF__INMRPTX__DIN7__78B651CF] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INMRPTX] ADD CONSTRAINT [PK__INMRPTX__7226EDCC] PRIMARY KEY CLUSTERED  ([ASETTLENO], [BGDGID], [BVDRGID], [BWRH], [ASTORE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
