CREATE TABLE [dbo].[LSDTL2]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SUBWRH] [int] NOT NULL,
[WRH] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[QTY] [money] NOT NULL CONSTRAINT [DF__LSDTL2__QTY__38BAFCF4] DEFAULT (0),
[COST] [money] NOT NULL CONSTRAINT [DF__LSDTL2__COST__39AF212D] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LSDTL2] ADD CONSTRAINT [PK__LSDTL2__37C6D8BB] PRIMARY KEY CLUSTERED  ([SUBWRH], [NUM], [LINE]) ON [PRIMARY]
GO
