CREATE TABLE [dbo].[MXFDTL2]
(
[NUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SUBWRH] [int] NOT NULL,
[FROMTO] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[WRH] [int] NOT NULL,
[QTY] [money] NOT NULL CONSTRAINT [DF__MXFDTL2__QTY__3885F2CA] DEFAULT (0),
[COST] [money] NOT NULL CONSTRAINT [DF__MXFDTL2__COST__397A1703] DEFAULT (0),
[COSTADJ] [money] NOT NULL CONSTRAINT [DF__MXFDTL2__COSTADJ__3A6E3B3C] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MXFDTL2] ADD CONSTRAINT [PK__MXFDTL2__5DD9D50F] PRIMARY KEY CLUSTERED  ([NUM], [LINE], [SUBWRH], [FROMTO]) ON [PRIMARY]
GO
