CREATE TABLE [dbo].[PSSORTSCORULE]
(
[UUID] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARDTYPE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SORTCODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL CONSTRAINT [DF__PSSORTSCO__ENDDA__383747C7] DEFAULT ('2099.12.31'),
[AMOUNT] [decimal] (24, 2) NOT NULL,
[SCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PSSORTSCO__SCORE__392B6C00] DEFAULT (0),
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__PSSORTSCO__LSTUP__3A1F9039] DEFAULT (getdate()),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSSORTSCORULE] ADD CONSTRAINT [PK__PSSORTSCORULE__3B13B472] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PSSORTSCORULE_IDX1] ON [dbo].[PSSORTSCORULE] ([CARDTYPE], [SORTCODE], [BEGINDATE]) ON [PRIMARY]
GO
