CREATE TABLE [dbo].[NSETTLEAREA]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[CODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NSETTLEAREA] ADD CONSTRAINT [PK__NSETTLEAREA__449EB55A] PRIMARY KEY CLUSTERED  ([SRC], [ID], [CODE], [NAME]) ON [PRIMARY]
GO
