CREATE TABLE [dbo].[SORTSTORE]
(
[ACODE] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SCODE] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GID] [int] NOT NULL,
[FNO] [int] NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__SORTSTORE__LSTUP__60007DF5] DEFAULT (getdate()),
[SORTTARGET1] [money] NOT NULL CONSTRAINT [DF__SORTSTORE__SORTT__5782A892] DEFAULT ((-1))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SORTSTORE] ADD CONSTRAINT [PK__SORTSTORE__60F4A22E] PRIMARY KEY CLUSTERED  ([ACODE], [SCODE], [GID]) ON [PRIMARY]
GO
