CREATE TABLE [dbo].[CRMCARDSCOHST]
(
[CARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARRIER] [int] NOT NULL CONSTRAINT [DF__CRMCARDSC__CARRI__792C1E72] DEFAULT (1),
[SCORESUBJECT] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMCARDSC__SCORE__7A2042AB] DEFAULT ('未知'),
[OLDSCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCARDSC__OLDSC__7B1466E4] DEFAULT (0),
[SCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCARDSC__SCORE__7C088B1D] DEFAULT (0),
[FGSTAT] [smallint] NOT NULL CONSTRAINT [DF__CRMCARDSC__FGSTA__7CFCAF56] DEFAULT (0),
[NUM] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SCORESORT] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMCARDSC__SCORE__7DF0D38F] DEFAULT ('-')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMCARDSCOHST] ADD CONSTRAINT [PK__CRMCARDSCOHST__4CEAADEF] PRIMARY KEY CLUSTERED  ([NUM], [SCORESORT], [SCORESUBJECT]) ON [PRIMARY]
GO
