CREATE TABLE [dbo].[CTCHGDEFRATE]
(
[CODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DATASRCCLS] [char] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FEEUNIT] [char] (4) COLLATE Chinese_PRC_CI_AS NULL,
[FEECYCLE] [smallint] NULL,
[FEEDAYOFFSET] [smallint] NULL,
[FIXCOST] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CTCHGDEFR__FIXCO__1DBE84A3] DEFAULT (0),
[RATEMODE] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CTCHGDEFR__RATEM__1EB2A8DC] DEFAULT ('数值分段'),
[CALCMODE] [varchar] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FEEPREC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CTCHGDEFR__FEEPR__209AF14E] DEFAULT (0.01),
[ROUNDTYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CTCHGDEFR__ROUND__218F1587] DEFAULT ('四舍五入'),
[AHEADDAYS] [int] NOT NULL CONSTRAINT [DF__CTCHGDEFR__AHEAD__228339C0] DEFAULT (0),
[DISCOUNTRATE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CTCHGDEFR__DISCO__23775DF9] DEFAULT (0),
[FEETOSTORE] [smallint] NOT NULL CONSTRAINT [DF__CTCHGDEFR__FEETO__751174CB] DEFAULT (0),
[GUARDMODE] [smallint] NOT NULL CONSTRAINT [DF__CTCHGDEFR__GUARD__09386909] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CTCHGDEFRATE] ADD CONSTRAINT [PK__CTCHGDEFRATE__246B8232] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[DF__CTCHGDEFR__CALCM__12345678]', N'[dbo].[CTCHGDEFRATE].[CALCMODE]'
GO
