CREATE TABLE [dbo].[PS3MAXSCORE]
(
[UUID] [varchar] (36) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[MAXSCORE] [int] NOT NULL CONSTRAINT [DF__PS3MAXSCO__MAXSC__09667EEE] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SCORESORT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PS3MAXSCO__SCORE__07F337C8] DEFAULT ('-')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3MAXSCORE] ADD CONSTRAINT [PK__PS3MAXSCORE__0A5AA327] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
