CREATE TABLE [dbo].[NSTORESCHSORTGOODS]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SORTCODE] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[ISOPER] [int] NOT NULL,
[ISNECESSARY] [int] NOT NULL,
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NSTORESCHSORTGOODS] ADD CONSTRAINT [PK__NSTORESCHSORTGOO__268CCD81] PRIMARY KEY CLUSTERED  ([NUM], [GDGID], [SRC], [ID]) ON [PRIMARY]
GO
