CREATE TABLE [dbo].[NPS3SPECSCOPESCORE]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__NPS3SPECSC__STAT__755F8641] DEFAULT (0),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NPS3SPECS__FILDA__7653AA7A] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[CHKDATE] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__NPS3SPECS__LSTUP__7747CEB3] DEFAULT (getdate()),
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NPS3SPECS__LSTUP__783BF2EC] DEFAULT ('未知[-]'),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SETTLENO] [int] NOT NULL CONSTRAINT [DF__NPS3SPECS__SETTL__79301725] DEFAULT (0),
[RECCNT] [int] NOT NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPS3SPECSCOPESCORE] ADD CONSTRAINT [PK__NPS3SPECSCOPESCO__7A243B5E] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPS3SPECSCOPESCORE_NUM] ON [dbo].[NPS3SPECSCOPESCORE] ([NUM]) ON [PRIMARY]
GO
