CREATE TABLE [dbo].[CARDTYPELIM]
(
[NAME] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TYPE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SPECIFYNUM] [int] NOT NULL CONSTRAINT [DF__CARDTYPEL__SPECI__040D984B] DEFAULT (0),
[DISABLENUM] [int] NOT NULL CONSTRAINT [DF__CARDTYPEL__DISAB__0501BC84] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CARDTYPELIM] ADD CONSTRAINT [PK__CARDTYPELIM__05F5E0BD] PRIMARY KEY CLUSTERED  ([NAME]) ON [PRIMARY]
GO
