CREATE TABLE [dbo].[VOUCHERH]
(
[NUM] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STATE] [int] NOT NULL CONSTRAINT [DF__VOUCHERH__STATE__717784BF] DEFAULT (0),
[PHASE] [int] NOT NULL CONSTRAINT [DF__VOUCHERH__PHASE__726BA8F8] DEFAULT (0),
[CREATETIME] [datetime] NOT NULL CONSTRAINT [DF__VOUCHERH__CREATE__735FCD31] DEFAULT (getdate()),
[CREATOR] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[AMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__VOUCHERH__AMOUNT__7453F16A] DEFAULT (0),
[ENCRYPTKEY] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL,
[RECEIVESTORE] [int] NULL,
[RECEIVEOPERATOR] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[RECEIVETIME] [datetime] NULL,
[RECYCLESTORE] [int] NULL,
[RECYCLEOPERATOR] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[RECYCLETIME] [datetime] NULL,
[DISPOSESTORE] [int] NULL,
[DISPOSEOPERATOR] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[DISPOSETIME] [datetime] NULL,
[VOUCHERTYPE] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL,
[SELLAMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__VOUCHERH__SELLAM__5D6735C8] DEFAULT (0),
[SELLOPERATOR] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[SELLSTORE] [int] NULL,
[SELLTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERH] ADD CONSTRAINT [PK__VOUCHERH__754815A3] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
