CREATE TABLE [dbo].[LEAGUECLIENTACCOUNTPAY]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLIENTGID] [int] NOT NULL,
[ACCOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__LEAGUECLI__ACCOU__092425C7] DEFAULT (0),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SHOULDPAY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__LEAGUECLI__SHOUL__47215840] DEFAULT (0),
[PAY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__LEAGUECLIEN__PAY__48157C79] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LEAGUECLIENTACCOUNTPAY] ADD CONSTRAINT [PK__LEAGUECLIENTACCO__0A184A00] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
