CREATE TABLE [dbo].[POSDBDATAVERSION]
(
[DATAVERSION] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GENTIME] [datetime] NOT NULL CONSTRAINT [DF__POSDBDATA__GENTI__1E8FB1B9] DEFAULT (getdate()),
[EXPIRETIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[POSDBDATAVERSION] ADD CONSTRAINT [PK__POSDBDAT__143AD7562077FA2B] PRIMARY KEY CLUSTERED  ([DATAVERSION]) ON [PRIMARY]
GO
