CREATE TABLE [dbo].[CKTASK]
(
[SRC] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NO] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CREATETIME] [datetime] NOT NULL CONSTRAINT [DF__CKTASK__CREATETI__300F4376] DEFAULT (getdate()),
[COMPUTERNAME] [char] (255) COLLATE Chinese_PRC_CI_AS NOT NULL,
[IPADDR] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[OPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MEMO] [char] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CKTASK] ADD CONSTRAINT [PK__CKTASK__593FCB7531F78BE8] PRIMARY KEY CLUSTERED  ([SRC], [NO]) ON [PRIMARY]
GO
