CREATE TABLE [dbo].[PS3_OUTERGENBILLS]
(
[PLATFORM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLNUM] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GENBILLNAME] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GENBILLNUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[UUID] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__PS3_OUTER__LSTUP__59FA904A] DEFAULT (getdate()),
[BILLCLS] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PS3_OUTER__BILLC__22803E2E] DEFAULT ('差额付款调整')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3_OUTERGENBILLS] ADD CONSTRAINT [PK__PS3_OUTE__AA2C96D25BE2D8BC] PRIMARY KEY CLUSTERED  ([UUID], [GENBILLNAME]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_OBGENBILL_PG] ON [dbo].[PS3_OUTERGENBILLS] ([PLATFORM], [GENBILLNAME]) ON [PRIMARY]
GO
