CREATE TABLE [dbo].[CUSTOMERORDERBUY21]
(
[FLOWNO] [char] (16) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[FAVTYPE] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FAVAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CUSTOMERO__FAVAM__32FF280C] DEFAULT (0),
[SENT] [varchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[PROMNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[PROMCLS] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL,
[PROMLVL] [int] NULL,
[PROMGDCNT] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUSTOMERORDERBUY21] ADD CONSTRAINT [PK__CustomerOrderBUY__33F34C45] PRIMARY KEY CLUSTERED  ([FLOWNO], [POSNO], [ITEMNO], [FAVTYPE]) ON [PRIMARY]
GO
