CREATE TABLE [dbo].[DCTALLOG]
(
[PRNTIME] [datetime] NOT NULL CONSTRAINT [DF__DCTALLOG__PRNTIM__7EFAD1B8] DEFAULT (getdate()),
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STORE] [int] NOT NULL,
[QTY] [int] NOT NULL CONSTRAINT [DF__DCTALLOG__QTY__7FEEF5F1] DEFAULT (0),
[ZQTY] [int] NOT NULL CONSTRAINT [DF__DCTALLOG__ZQTY__00E31A2A] DEFAULT (0),
[OPER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_DCTALLOG] ON [dbo].[DCTALLOG] ([PRNTIME]) ON [PRIMARY]
GO
