CREATE TABLE [dbo].[STKINBCKDTL]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__STKINBCKDTL__CLS__3568C3A6] DEFAULT ('自营'),
[SETTLENO] [int] NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NULL,
[CASES] [money] NULL,
[QTY] [money] NULL,
[PRICE] [money] NULL,
[TOTAL] [money] NULL,
[TAX] [money] NULL,
[VALIDDATE] [datetime] NULL,
[WRH] [int] NULL CONSTRAINT [DF__STKINBCKDTL__WRH__365CE7DF] DEFAULT (1),
[INPRC] [money] NULL,
[RTLPRC] [money] NULL,
[PAYQTY] [money] NULL CONSTRAINT [DF__STKINBCKD__PAYQT__37510C18] DEFAULT (0),
[PAYAMT] [money] NULL CONSTRAINT [DF__STKINBCKD__PAYAM__38453051] DEFAULT (0),
[BNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[subwrh] [int] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[COST] [money] NOT NULL CONSTRAINT [DF__STKINBCKDT__COST__318E1121] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STKINBCKDTL] WITH NOCHECK ADD CONSTRAINT [退货单号长度为10] CHECK NOT FOR REPLICATION ((len([num])=(10) AND left([num],(1))='0'))
GO
ALTER TABLE [dbo].[STKINBCKDTL] ADD CONSTRAINT [PK__STKINBCKDTL__20ACD28B] PRIMARY KEY CLUSTERED  ([CLS], [NUM], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [stkinbckdtl_gdgid] ON [dbo].[STKINBCKDTL] ([GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
