CREATE TABLE [dbo].[FATEMPLATE]
(
[ID] [varchar] (38) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SQLCOMMAND] [varchar] (4000) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DISPLAYTEXT] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL,
[ACTIVE] [int] NOT NULL CONSTRAINT [DF__FATEMPLAT__ACTIV__3F7614D7] DEFAULT (0),
[MEMO] [varchar] (256) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FATEMPLATE] ADD CONSTRAINT [PK__FATEMPLATE__406A3910] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
