CREATE TABLE [dbo].[EMPSTORE]
(
[EMPGID] [int] NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMPSTORE] ADD CONSTRAINT [PK__EMPSTORE__722EDF32] PRIMARY KEY CLUSTERED  ([STOREGID], [EMPGID]) ON [PRIMARY]
GO
