CREATE TABLE [dbo].[NCRMSTAMPSCORULEDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[CLS] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[UUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCRMSTAMP__TOTAL__47CE9112] DEFAULT (0),
[SCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCRMSTAMP__SCORE__48C2B54B] DEFAULT (0),
[SCOTOP] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCRMSTAMP__SCOTO__49B6D984] DEFAULT (0),
[BEGINDATE] [datetime] NOT NULL CONSTRAINT [DF__NCRMSTAMP__BEGIN__4AAAFDBD] DEFAULT (getdate()),
[ENDDATE] [datetime] NOT NULL CONSTRAINT [DF__NCRMSTAMP__ENDDA__4B9F21F6] DEFAULT (getdate()),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCRMSTAMPSCORULEDTL] ADD CONSTRAINT [PK__NCRMSTAMPSCORULE__4C93462F] PRIMARY KEY CLUSTERED  ([SRC], [ID], [NUM], [LINE]) ON [PRIMARY]
GO
