CREATE TABLE [dbo].[SWINVMRPT]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[BGDGID] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[BSUBWRH] [int] NOT NULL,
[CQ] [money] NOT NULL CONSTRAINT [DF__SWINVMRPT__CQ__2EA782D5] DEFAULT (0),
[CT] [money] NOT NULL CONSTRAINT [DF__SWINVMRPT__CT__2F9BA70E] DEFAULT (0),
[FQ] [money] NOT NULL CONSTRAINT [DF__SWINVMRPT__FQ__308FCB47] DEFAULT (0),
[FT] [money] NOT NULL CONSTRAINT [DF__SWINVMRPT__FT__3183EF80] DEFAULT (0),
[CI] [money] NOT NULL CONSTRAINT [DF__SWINVMRPT__CI__15879AA7] DEFAULT (0),
[FI] [money] NOT NULL CONSTRAINT [DF__SWINVMRPT__FI__167BBEE0] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SWINVMRPT] ADD CONSTRAINT [PK__SWINVMRPT__2942188C] PRIMARY KEY CLUSTERED  ([ASETTLENO], [BGDGID], [BWRH], [BSUBWRH], [ASTORE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
