CREATE TABLE [dbo].[STKINBCKDTL2]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__STKINBCKDTL__CLS__1B2A9A0D] DEFAULT ('自营'),
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SUBWRH] [int] NOT NULL,
[WRH] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[QTY] [money] NOT NULL CONSTRAINT [DF__STKINBCKDTL__QTY__1C1EBE46] DEFAULT (0),
[COST] [money] NOT NULL CONSTRAINT [DF__STKINBCKDT__COST__1D12E27F] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STKINBCKDTL2] ADD CONSTRAINT [PK__STKINBCKDTL2__1A3675D4] PRIMARY KEY CLUSTERED  ([SUBWRH], [CLS], [NUM], [LINE]) ON [PRIMARY]
GO
