CREATE TABLE [dbo].[NCRMCARD]
(
[CARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BYTIME] [datetime] NOT NULL CONSTRAINT [DF__NCRMCARD__BYTIME__26F2E922] DEFAULT ('2001.1.1'),
[CARDTYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARRIER] [int] NOT NULL CONSTRAINT [DF__NCRMCARD__CARRIE__27E70D5B] DEFAULT (1),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__NCRMCARD__STAT__28DB3194] DEFAULT (0),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__NCRMCARD__LSTUPD__29CF55CD] DEFAULT (getdate()),
[VERSION] [char] (9) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NCRMCARD__VERSIO__2AC37A06] DEFAULT ('020000000'),
[MAKETIME] [datetime] NOT NULL,
[SNDTIME] [datetime] NULL,
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[RCV] [int] NULL,
[RCVTIME] [datetime] NULL,
[FRCCHK] [smallint] NOT NULL,
[NTYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [char] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCRMCARD] ADD CONSTRAINT [PK__NCRMCARD__2BB79E3F] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
