CREATE TABLE [dbo].[POLYPRCPRMEXGDDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[POLYPRCPRMEXGDDTL] ADD CONSTRAINT [PK__POLYPRCPRMEXGDDT__3F237121] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_POLYPRCPRMEXGDDTL_GDGID] ON [dbo].[POLYPRCPRMEXGDDTL] ([NUM], [GDGID]) ON [PRIMARY]
GO
