CREATE TABLE [dbo].[NGDSALEADJDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[SETTLENO] [int] NULL,
[GDGID] [int] NULL,
[OLDGDSALE] [smallint] NOT NULL,
[NEWGDSALE] [smallint] NULL,
[NEWPAYRATE] [decimal] (24, 2) NULL,
[CHGFLAG] [smallint] NOT NULL CONSTRAINT [DF__NGDSALEAD__CHGFL__580A5672] DEFAULT (0),
[CHGFROMDATE] [datetime] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NGDSALEADJDTL] ADD CONSTRAINT [PK__NGDSALEADJDTL__57163239] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) ON [PRIMARY]
GO
