CREATE TABLE [dbo].[NCRMCARDSCODTL]
(
[CARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCRMCARDS__SCORE__3358C007] DEFAULT (0),
[SCRTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCRMCARDS__SCRTO__344CE440] DEFAULT (0),
[ADJSCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCRMCARDS__ADJSC__35410879] DEFAULT (0),
[ADJSCORETIME] [datetime] NULL,
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCRMCARDSCODTL] ADD CONSTRAINT [PK__NCRMCARDSCODTL__36352CB2] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
