CREATE TABLE [dbo].[QUERY]
(
[NAME] [varchar] (80) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SORT] [varchar] (8) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[QUERY] ADD CONSTRAINT [PK__QUERY__031C6FA4] PRIMARY KEY CLUSTERED  ([NAME], [SORT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
