CREATE TABLE [dbo].[VOUCHERACTBCKBINDTRANSDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERACTBCKBINDTRANSDTL] ADD CONSTRAINT [PK__VOUCHERACTBCKBIN__6DE18D66] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
