CREATE TABLE [dbo].[LTDADJDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[OLDVALUE] [int] NOT NULL,
[NEWVALUE] [int] NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[FINISHDATE] [datetime] NOT NULL CONSTRAINT [DF__LTDADJDTL__FINIS__7981EF84] DEFAULT ('9999.12.31 23:59:59'),
[OLDSALE] [int] NULL,
[NEWSALE] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LTDADJDTL] ADD CONSTRAINT [PK__LTDADJDTL__096BDC85] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
