CREATE TABLE [dbo].[PAYRATEPRMLOG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TIME] [datetime] NOT NULL,
[ACT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAYRATEPRMLOG] ADD CONSTRAINT [PK__PAYRATEPRMLOG__0E5DDC30] PRIMARY KEY CLUSTERED  ([NUM], [TIME], [ACT]) ON [PRIMARY]
GO
