CREATE TABLE [dbo].[EMPFEE]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[EMP] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[FEEID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMPFEE] ADD CONSTRAINT [PK__EMPFEE__5CC5B545] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
