CREATE TABLE [dbo].[STOREOPERSCHEMEDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[SORTCODE] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STOREOPERSCHEMEDTL] ADD CONSTRAINT [PK__STOREOPERSCHEMED__183EAE2A] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_STOREOPERSCHEMEDTL_SORT] ON [dbo].[STOREOPERSCHEMEDTL] ([SORTCODE]) ON [PRIMARY]
GO
