CREATE TABLE [dbo].[ERPBILLEINVOICE]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[IVCEXTCODE] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[EIVCSTAT] [smallint] NOT NULL CONSTRAINT [DF__ERPBILLEI__EIVCS__1249D665] DEFAULT ((0)),
[LOCALSTAT] [smallint] NOT NULL CONSTRAINT [DF__ERPBILLEI__LOCAL__133DFA9E] DEFAULT ((0)),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__ERPBILLEI__LSTUP__14321ED7] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ERPBILLEINVOICE] ADD CONSTRAINT [PK__ERPBILLE__6D85EFDA161A6749] PRIMARY KEY CLUSTERED  ([CLS], [NUM]) ON [PRIMARY]
GO
