CREATE TABLE [dbo].[RFNUM]
(
[RFNUM] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RFNUM] ADD CONSTRAINT [PK__RFNUM__37AA0A86] PRIMARY KEY CLUSTERED  ([RFNUM]) ON [PRIMARY]
GO
