CREATE TABLE [dbo].[RFRECEIVEDTL]
(
[RCVNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[GDCODE] [varchar] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDINPUT] [varchar] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDNAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ARVQTY] [decimal] (24, 4) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RFRECEIVEDTL] ADD CONSTRAINT [PK__RFRECEIVEDTL__269A1C7E] PRIMARY KEY CLUSTERED  ([RCVNUM], [LINE]) ON [PRIMARY]
GO
