CREATE TABLE [dbo].[CRMCONSCORE]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__CRMCONSCOR__STAT__39D0B36C] DEFAULT (0),
[MEMBER] [int] NOT NULL,
[CARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OLDSCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCONSCO__OLDSC__3AC4D7A5] DEFAULT (0),
[SCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCONSCO__SCORE__3BB8FBDE] DEFAULT (0),
[RUNMODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__CRMCONSCO__LSTUP__3CAD2017] DEFAULT (getdate()),
[PRNTIME] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMCONSCORE] ADD CONSTRAINT [PK__CRMCONSCORE__3DA14450] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
