CREATE TABLE [dbo].[GFTPRMSND]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL,
[SRC] [int] NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__GFTPRMSND__LSTUP__78C13EC7] DEFAULT (getdate()),
[NOTE] [text] COLLATE Chinese_PRC_CI_AS NULL,
[CLIENT] [int] NULL,
[CTRNAME] [char] (16) COLLATE Chinese_PRC_CI_AS NULL,
[SNDCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__GFTPRMSND__SNDCL__79B56300] DEFAULT ('自动计算'),
[SETTLENO] [smallint] NOT NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[PAYAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMSND__PAYAM__7AA98739] DEFAULT (0),
[TAG] [smallint] NOT NULL CONSTRAINT [DF__GFTPRMSND__TAG__2E141CA6] DEFAULT (0),
[MODNUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GFTPRMSND] ADD CONSTRAINT [PK__GFTPRMSND__77CD1A8E] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
