CREATE TABLE [dbo].[TMPGENDELINFO]
(
[spid] [int] NOT NULL,
[NUM] [char] (16) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHGTYPE] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[REASON] [char] (255) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx_TMPGENDELINFO_spid] ON [dbo].[TMPGENDELINFO] ([spid]) ON [PRIMARY]
GO
