CREATE TABLE [dbo].[PS3SPECGDSCOREINVOUT]
(
[UUID] [varchar] (36) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SUBJCODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SUBJCLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRCNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PS3SPECGD__SRCNU__557D91EB] DEFAULT ('-'),
[SRCCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PS3SPECGD__SRCCL__5671B624] DEFAULT ('-'),
[Flag] [int] NOT NULL CONSTRAINT [DF__PS3SPECGDS__Flag__2AFFAA3F] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3SPECGDSCOREINVOUT] ADD CONSTRAINT [PK__PS3SPECGDSCOREIN__5765DA5D] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3SPECGDSCOREINVOUT_NUMCLS] ON [dbo].[PS3SPECGDSCOREINVOUT] ([SRCNUM], [SRCCLS]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3SPECGDSCOREINVOUT_SUBJCODE] ON [dbo].[PS3SPECGDSCOREINVOUT] ([SUBJCODE]) ON [PRIMARY]
GO
