CREATE TABLE [dbo].[NPROCYRPT]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[BGDGID] [int] NOT NULL,
[CQ1] [money] NOT NULL CONSTRAINT [DF__NPROCYRPT__CQ1__607FA0E2] DEFAULT (0),
[CT1] [money] NOT NULL CONSTRAINT [DF__NPROCYRPT__CT1__6173C51B] DEFAULT (0),
[CI1] [money] NOT NULL CONSTRAINT [DF__NPROCYRPT__CI1__6267E954] DEFAULT (0),
[CR1] [money] NOT NULL CONSTRAINT [DF__NPROCYRPT__CR1__635C0D8D] DEFAULT (0),
[CD1] [money] NOT NULL CONSTRAINT [DF__NPROCYRPT__CD1__645031C6] DEFAULT (0),
[DQ1] [money] NOT NULL CONSTRAINT [DF__NPROCYRPT__DQ1__654455FF] DEFAULT (0),
[DT1] [money] NOT NULL CONSTRAINT [DF__NPROCYRPT__DT1__66387A38] DEFAULT (0),
[DI1] [money] NOT NULL CONSTRAINT [DF__NPROCYRPT__DI1__672C9E71] DEFAULT (0),
[DR1] [money] NOT NULL CONSTRAINT [DF__NPROCYRPT__DR1__6820C2AA] DEFAULT (0),
[DD1] [money] NOT NULL CONSTRAINT [DF__NPROCYRPT__DD1__6914E6E3] DEFAULT (0),
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[RCV] [int] NULL,
[SNDTIME] [datetime] NOT NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPROCYRPT] ADD CONSTRAINT [PK__NPROCYRPT__46136164] PRIMARY KEY CLUSTERED  ([ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
