CREATE TABLE [dbo].[PSMKTIVGT]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__PSMKTIVGT__STAT__5ABD7142] DEFAULT (0),
[RATIFIER] [int] NULL,
[SRC] [int] NOT NULL,
[Ivgtor] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__PSMKTIVGT__FILDA__5BB1957B] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[REQOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[REQDATE] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[BEGINDATE] [datetime] NULL,
[LSTUPDTIME] [datetime] NULL CONSTRAINT [DF__PSMKTIVGT__LSTUP__5CA5B9B4] DEFAULT (getdate()),
[PRNTIME] [datetime] NULL,
[SNDTIME] [datetime] NULL,
[SETTLENO] [int] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__PSMKTIVGT__RECCN__5D99DDED] DEFAULT (0),
[OCRSTORE] [int] NULL CONSTRAINT [DF__PSMKTIVGT__OCRST__5E8E0226] DEFAULT (0),
[ADDR] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__PSMKTIVGT__ADDR__5F82265F] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSMKTIVGT] ADD CONSTRAINT [PK__PSMktIvgt__60764A98] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
