CREATE TABLE [dbo].[FAGADGET]
(
[ID] [varchar] (38) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TITLE] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[MEMO] [varchar] (256) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FAGADGET] ADD CONSTRAINT [PK__FAGADGET__3D8DCC65] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
