CREATE TABLE [dbo].[STOREINVESTDATA]
(
[STOREGID] [int] NOT NULL,
[INVESTAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__STOREINVE__INVES__07D00EDB] DEFAULT (0),
[FIXINVEST] [decimal] (24, 2) NULL,
[PRFRATE] [decimal] (24, 2) NULL,
[COSTSALE] [decimal] (24, 2) NULL,
[PROFITSALE] [decimal] (24, 2) NULL,
[MONTHLYFEE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__STOREINVE__MONTH__08C43314] DEFAULT (0),
[PREPAY] [decimal] (24, 2) NULL,
[LOANAMT] [decimal] (24, 2) NULL,
[FITNAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[FITFEE] [decimal] (24, 2) NULL,
[FITEXP] [datetime] NULL,
[EQP] [int] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STOREINVESTDATA] ADD CONSTRAINT [PK__STOREINVESTDATA__09B8574D] PRIMARY KEY CLUSTERED  ([STOREGID]) ON [PRIMARY]
GO
