CREATE TABLE [dbo].[PS3SPECGDSCOREPROMSUBJOUTDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[SUBJCODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SUBJCLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3SPECGDSCOREPROMSUBJOUTDTL] ADD CONSTRAINT [PK__PS3SPECGDSCOREPR__594E22CF] PRIMARY KEY CLUSTERED  ([NUM], [CLS], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3SPECGDSCOREPROMSUBJOUTDTL_1] ON [dbo].[PS3SPECGDSCOREPROMSUBJOUTDTL] ([SUBJCODE]) ON [PRIMARY]
GO
