CREATE TABLE [dbo].[CRMCARDCOSTRET]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ACCOUNTINGDATE] [datetime] NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__CRMCARDCOS__STAT__0869CFC2] DEFAULT (0),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__CRMCARDCO__FILDA__095DF3FB] DEFAULT (getdate()),
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMCARDCOSTRET] ADD CONSTRAINT [PK__CRMCARDCOSTRET__0A521834] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_CRMSCOREADJ_LST] ON [dbo].[CRMCARDCOSTRET] ([LSTUPDTIME]) ON [PRIMARY]
GO
