CREATE TABLE [dbo].[ALCPOOLTEMP]
(
[STOREGID] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[GDCODE] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PSRALCQTY] [money] NOT NULL CONSTRAINT [DF__ALCPOOLTE__PSRAL__35B53E6E] DEFAULT (0),
[ORDQTY] [money] NOT NULL CONSTRAINT [DF__ALCPOOLTE__ORDQT__36A962A7] DEFAULT (0),
[AUTOALCQTY] [money] NOT NULL CONSTRAINT [DF__ALCPOOLTE__AUTOA__379D86E0] DEFAULT (0),
[ALC] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VENDOR] [int] NOT NULL,
[SORT] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[WRH] [int] NOT NULL,
[PSR] [int] NOT NULL,
[F1] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL,
[F2] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL,
[SRCBILL] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[INVQTY] [money] NOT NULL CONSTRAINT [DF__ALCPOOLTE__INVQT__3891AB19] DEFAULT (0),
[QTY] [money] NOT NULL CONSTRAINT [DF__ALCPOOLTEMP__QTY__3985CF52] DEFAULT (0),
[QTYFROM] [int] NOT NULL CONSTRAINT [DF__ALCPOOLTE__QTYFR__3A79F38B] DEFAULT (1),
[TAXRATE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__ALCPOOLTE__TAXRA__21BAC967] DEFAULT (0)
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ALCPOOLTEMP_INDEXS] ON [dbo].[ALCPOOLTEMP] ([STOREGID], [GDGID], [ALC]) ON [PRIMARY]
GO
