CREATE TABLE [dbo].[PRCPRMDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SETTLENO] [int] NULL,
[GDGID] [int] NULL,
[PRMTYPE] [smallint] NULL CONSTRAINT [DF__PRCPRMDTL__PRMTY__6A46A039] DEFAULT (0),
[CANGFT] [smallint] NULL CONSTRAINT [DF__PRCPRMDTL__CANGF__6B3AC472] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[QPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PRCPRMDTL__QPC__37DF14B0] DEFAULT (1),
[QPCSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PRCPRMDTL__QPCST__38D338E9] DEFAULT ('1*1')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRCPRMDTL] WITH NOCHECK ADD CONSTRAINT [CK_PRCPRMDTL] CHECK NOT FOR REPLICATION ((len([num])=(10) AND left([num],(1))='0'))
GO
ALTER TABLE [dbo].[PRCPRMDTL] ADD CONSTRAINT [PK__PRCPRMDTL__77AABCF8] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [prcprmdtl_gdgid] ON [dbo].[PRCPRMDTL] ([GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
