CREATE TABLE [dbo].[ICCARD]
(
[CARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BYTIME] [datetime] NOT NULL CONSTRAINT [DF__ICCARD__BYTIME__64C39C64] DEFAULT ('2001.1.1'),
[BALANCE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__ICCARD__BALANCE__65B7C09D] DEFAULT (0),
[CONSUME] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__ICCARD__CONSUME__66ABE4D6] DEFAULT (0),
[Score] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__ICCARD__Score__67A0090F] DEFAULT (0),
[BanTotal] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__ICCARD__BanTotal__68942D48] DEFAULT (0),
[ScrTotal] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__ICCARD__ScrTotal__69885181] DEFAULT (0),
[CARDTYPE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARRIER] [int] NOT NULL CONSTRAINT [DF__ICCARD__CARRIER__6A7C75BA] DEFAULT (1),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__ICCARD__STAT__6B7099F3] DEFAULT (0),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__ICCARD__LSTUPDTI__6C64BE2C] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ICCARD] ADD CONSTRAINT [PK__ICCARD__63CF782B] PRIMARY KEY CLUSTERED  ([CARDNUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
