CREATE TABLE [dbo].[ESORT]
(
[CODE] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (36) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ESORT] ADD CONSTRAINT [PK__ESORT__0E5AAED4] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
