CREATE TABLE [dbo].[WELFARECARDTYPE]
(
[NAME] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PARVALUE] [decimal] (24, 2) NULL,
[CARDCOST] [decimal] (24, 4) NULL,
[MEDIUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__WELFARECA__MEDIU__53D07C91] DEFAULT ('IC卡')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WELFARECARDTYPE] ADD CONSTRAINT [PK__WELFARECARDTYPE__54C4A0CA] PRIMARY KEY CLUSTERED  ([NAME]) ON [PRIMARY]
GO
