CREATE TABLE [dbo].[NBUY11]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[SETTLENO] [int] NOT NULL,
[CURRENCY] [smallint] NOT NULL CONSTRAINT [DF__NBUY11__CURRENCY__314EE556] DEFAULT (0),
[AMOUNT] [money] NOT NULL CONSTRAINT [DF__NBUY11__AMOUNT__3243098F] DEFAULT (0),
[TAG] [smallint] NOT NULL CONSTRAINT [DF__NBUY11__TAG__33372DC8] DEFAULT (0),
[CARDCODE] [varchar] (128) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NBUY11] ADD CONSTRAINT [PK__NBUY11__305AC11D] PRIMARY KEY CLUSTERED  ([SRC], [ID], [ITEMNO]) ON [PRIMARY]
GO
