CREATE TABLE [dbo].[PROCESSGOODSJOB]
(
[ID] [int] NOT NULL,
[CREATOR] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CREATETIME] [datetime] NOT NULL CONSTRAINT [DF__PROCESSGO__CREAT__0DF3C7DC] DEFAULT (getdate()),
[LASTMODIFIEDTIME] [datetime] NULL,
[GOODSCOUNT] [int] NOT NULL CONSTRAINT [DF__PROCESSGO__GOODS__0EE7EC15] DEFAULT (0),
[STAT] [int] NOT NULL CONSTRAINT [DF__PROCESSGOO__STAT__0FDC104E] DEFAULT (0),
[MEMO] [varchar] (256) COLLATE Chinese_PRC_CI_AS NULL,
[LockFlag] [int] NOT NULL CONSTRAINT [DF__PROCESSGO__LockF__10D03487] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROCESSGOODSJOB] ADD CONSTRAINT [PK__PROCESSGOODSJOB__11C458C0] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
