CREATE TABLE [dbo].[CRMSTAMPSCORULEDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[CLS] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[UUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMSTAMPS__TOTAL__38A15C1B] DEFAULT (0),
[SCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMSTAMPS__SCORE__39958054] DEFAULT (0),
[SCOTOP] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMSTAMPS__SCOTO__3A89A48D] DEFAULT (0),
[BEGINDATE] [datetime] NOT NULL CONSTRAINT [DF__CRMSTAMPS__BEGIN__3B7DC8C6] DEFAULT (getdate()),
[ENDDATE] [datetime] NOT NULL CONSTRAINT [DF__CRMSTAMPS__ENDDA__3C71ECFF] DEFAULT (getdate()),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMSTAMPSCORULEDTL] ADD CONSTRAINT [PK__CRMSTAMPSCORULED__3D661138] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
