CREATE TABLE [dbo].[SALEDIFDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[ASSISTANT] [int] NOT NULL,
[QTY] [money] NOT NULL,
[PRICE] [money] NOT NULL,
[TOTAL] [money] NOT NULL,
[TAX] [money] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SALEDIFDTL] ADD CONSTRAINT [PK__SALEDIFDTL__64054DAC] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [SALEDIFDTL_GDGID] ON [dbo].[SALEDIFDTL] ([GDGID]) ON [PRIMARY]
GO
