CREATE TABLE [dbo].[CHARGECHKPAYCLSDTL]
(
[CODE] [smallint] NOT NULL,
[ISCLIENT] [smallint] NOT NULL CONSTRAINT [DF__CHARGECHK__ISCLI__77C55AF2] DEFAULT (0),
[DTLCODE] [varchar] (13) COLLATE Chinese_PRC_CI_AS NULL,
[DTLNAME] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__CHARGECHKP__STAT__45F8F534] DEFAULT (1),
[ACCOUNTNO] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
