CREATE TABLE [dbo].[NORDER]
(
[ID] [int] NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[VENDOR] [int] NULL CONSTRAINT [DF__NORDER__VENDOR__614745E4] DEFAULT (1),
[TOTAL] [money] NULL CONSTRAINT [DF__NORDER__TOTAL__623B6A1D] DEFAULT (0),
[TAX] [money] NULL CONSTRAINT [DF__NORDER__TAX__632F8E56] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[FILDATE] [datetime] NULL CONSTRAINT [DF__NORDER__FILDATE__6423B28F] DEFAULT (getdate()),
[PAYDATE] [datetime] NULL,
[PREPAY] [money] NULL,
[CHECKER] [int] NULL CONSTRAINT [DF__NORDER__CHECKER__6517D6C8] DEFAULT (1),
[STAT] [smallint] NULL CONSTRAINT [DF__NORDER__STAT__660BFB01] DEFAULT (0),
[MODNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[RECEIVER] [int] NULL,
[RECCNT] [int] NULL CONSTRAINT [DF__NORDER__RECCNT__67001F3A] DEFAULT (0),
[NSTAT] [int] NULL,
[SRC] [int] NOT NULL,
[RCV] [int] NULL,
[SNDTIME] [datetime] NULL,
[RCVTIME] [datetime] NULL,
[FRCCHK] [smallint] NULL,
[TYPE] [smallint] NULL,
[ALCCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[expdate] [datetime] NULL CONSTRAINT [DF__norder__expdate__033ECD3A] DEFAULT (null),
[DLVBDATE] [datetime] NULL,
[DLVEDATE] [datetime] NULL,
[ALCGID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NORDER] ADD CONSTRAINT [PK__NORDER__605321AB] PRIMARY KEY CLUSTERED  ([SRC], [ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NORDER_TYPE] ON [dbo].[NORDER] ([TYPE]) ON [PRIMARY]
GO
