CREATE TABLE [dbo].[PSCARDSCOEFFECT]
(
[CARDTYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BGNTIME] [datetime] NOT NULL,
[ENDTIME] [datetime] NOT NULL,
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSCARDSCOEFFECT] ADD CONSTRAINT [PK__PSCARDSCOEFFECT__738D17BF] PRIMARY KEY CLUSTERED  ([CARDTYPE], [BGNTIME]) ON [PRIMARY]
GO
