CREATE TABLE [dbo].[PROMBLOG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROMBLOG] ADD CONSTRAINT [PK__PROMBLOG__6E061B37] PRIMARY KEY CLUSTERED  ([NUM], [STAT], [FILDATE]) ON [PRIMARY]
GO
