CREATE TABLE [dbo].[PROCTASKBILL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[TYPE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILL] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLCLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[EXNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TAG] [int] NOT NULL CONSTRAINT [DF__PROCTASKBIL__TAG__27DDB711] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROCTASKBILL] ADD CONSTRAINT [PK__PROCTASKBILL__28D1DB4A] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
