CREATE TABLE [dbo].[PS3NOTSCORECURRENCY]
(
[CURCODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3NOTSCORECURRENCY] ADD CONSTRAINT [PK__PS3NOTSCORECURRE__077E367C] PRIMARY KEY CLUSTERED  ([CURCODE]) ON [PRIMARY]
GO
