CREATE TABLE [dbo].[PRMDIRPRCPRM]
(
[PRMSEQ] [int] NOT NULL,
[PRCPRMNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRMDIRPRCPRM] ADD CONSTRAINT [PK__PRMDIRPRCPRM__7CABA24E] PRIMARY KEY CLUSTERED  ([PRMSEQ], [PRCPRMNO]) ON [PRIMARY]
GO
