CREATE TABLE [dbo].[DEPTRTLPLAN]
(
[AYEAR] [smallint] NOT NULL,
[AMONTH] [smallint] NOT NULL,
[DEPT] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TOTAL] [money] NOT NULL,
[PROFIT] [money] NOT NULL,
[PRORATE] [money] NOT NULL,
[employees] [money] NOT NULL CONSTRAINT [DF__DEPTRTLPL__emplo__45ABAF15] DEFAULT (0),
[prizerate] [money] NOT NULL CONSTRAINT [DF__DEPTRTLPL__prize__469FD34E] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPTRTLPLAN] ADD CONSTRAINT [PK__DEPTRTLPLAN__436BFEE3] PRIMARY KEY CLUSTERED  ([AYEAR], [AMONTH], [DEPT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
