CREATE TABLE [dbo].[NINPRCADJDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[LINE] [smallint] NOT NULL,
[STORE] [int] NOT NULL,
[BILL] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLLINE] [smallint] NOT NULL,
[QTY] [money] NOT NULL,
[INCOST] [money] NULL,
[OUTCOST] [money] NULL,
[AMT] [money] NULL,
[ADJINCOST] [money] NULL,
[ADJOUTCOST] [money] NULL,
[ADJAMT] [money] NULL,
[LACTIME] [datetime] NOT NULL CONSTRAINT [DF__NINPRCADJ__LACTI__1F1104E1] DEFAULT (getdate()),
[BILLSRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SUBWRH] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NINPRCADJDTL] ADD CONSTRAINT [PK__NINPRCADJDTL__3118447E] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
