CREATE TABLE [dbo].[PRICE]
(
[STOREGID] [int] NULL,
[GDGID] [int] NULL,
[START] [datetime] NULL CONSTRAINT [DF__PRICE__START__519AEE00] DEFAULT ('1899.12.30 00:00:00'),
[FINISH] [datetime] NULL CONSTRAINT [DF__PRICE__FINISH__528F1239] DEFAULT ('9999.12.31 23:59:59'),
[CYCLE] [datetime] NULL CONSTRAINT [DF__PRICE__CYCLE__53833672] DEFAULT ('1899.12.30 00:00:00'),
[CSTART] [datetime] NULL CONSTRAINT [DF__PRICE__CSTART__54775AAB] DEFAULT ('1899.12.30 00:00:00'),
[CFINISH] [datetime] NULL CONSTRAINT [DF__PRICE__CFINISH__556B7EE4] DEFAULT ('9999.12.31 23:59:59'),
[CSPEC] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[QTYLO] [money] NULL CONSTRAINT [DF__PRICE__QTYLO__565FA31D] DEFAULT (0),
[QTYHI] [money] NULL CONSTRAINT [DF__PRICE__QTYHI__5753C756] DEFAULT (99999999),
[PRICE] [money] NULL,
[DISCOUNT] [decimal] (5, 2) NULL,
[GFTGID] [int] NULL,
[GFTQTY] [money] NULL,
[GFTPER] [money] NULL,
[GFTTYPE] [smallint] NULL,
[INPRC] [money] NULL,
[PrmTag] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[MBRPRC] [money] NULL,
[QPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PRICE__QPC__39C75D22] DEFAULT (1),
[QPCSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PRICE__QPCSTR__3ABB815B] DEFAULT ('1*1'),
[PRMTOPICCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[srcnum] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[PRIORITY] [int] NOT NULL CONSTRAINT [DF__PRICE__PRIORITY__3D860CC9] DEFAULT (0)
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [UQ_PRICE] ON [dbo].[PRICE] ([STOREGID], [GDGID], [QPCSTR], [START], [FINISH], [CYCLE], [CSTART], [CFINISH], [QTYLO], [QTYHI], [GFTGID], [GFTPER], [PRIORITY]) ON [PRIMARY]
GO
