CREATE TABLE [dbo].[VDRDRPT]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[BVDRGID] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[BGDGID] [int] NOT NULL,
[DQ1] [money] NULL CONSTRAINT [DF__VDRDRPT__DQ1__0722D609] DEFAULT (0),
[DQ2] [money] NULL CONSTRAINT [DF__VDRDRPT__DQ2__0816FA42] DEFAULT (0),
[DQ3] [money] NULL CONSTRAINT [DF__VDRDRPT__DQ3__090B1E7B] DEFAULT (0),
[DQ4] [money] NULL CONSTRAINT [DF__VDRDRPT__DQ4__09FF42B4] DEFAULT (0),
[DQ5] [money] NULL CONSTRAINT [DF__VDRDRPT__DQ5__0AF366ED] DEFAULT (0),
[DQ6] [money] NULL CONSTRAINT [DF__VDRDRPT__DQ6__0BE78B26] DEFAULT (0),
[DT1] [money] NULL CONSTRAINT [DF__VDRDRPT__DT1__0CDBAF5F] DEFAULT (0),
[DT2] [money] NULL CONSTRAINT [DF__VDRDRPT__DT2__0DCFD398] DEFAULT (0),
[DT3] [money] NULL CONSTRAINT [DF__VDRDRPT__DT3__0EC3F7D1] DEFAULT (0),
[DT4] [money] NULL CONSTRAINT [DF__VDRDRPT__DT4__0FB81C0A] DEFAULT (0),
[DT5] [money] NULL CONSTRAINT [DF__VDRDRPT__DT5__10AC4043] DEFAULT (0),
[DT6] [money] NULL CONSTRAINT [DF__VDRDRPT__DT6__11A0647C] DEFAULT (0),
[DT7] [money] NULL CONSTRAINT [DF__VDRDRPT__DT7__129488B5] DEFAULT (0),
[DI2] [money] NULL CONSTRAINT [DF__VDRDRPT__DI2__1388ACEE] DEFAULT (0),
[LSTUPDTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VDRDRPT] ADD CONSTRAINT [PK__VDRDRPT__34B3CB38] PRIMARY KEY CLUSTERED  ([ASTORE], [ASETTLENO], [ADATE], [BVDRGID], [BWRH], [BGDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX1] ON [dbo].[VDRDRPT] ([ADATE], [BVDRGID], [BWRH], [BGDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
