CREATE TABLE [dbo].[NPS3REDBLUECARDDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[LOWLIMIT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NPS3REDBL__LOWLI__1555BDD9] DEFAULT (0),
[TOPLIMIT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NPS3REDBL__TOPLI__1649E212] DEFAULT (0),
[LIMITPERCENT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NPS3REDBL__LIMIT__173E064B] DEFAULT (0),
[LIMITTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NPS3REDBL__LIMIT__18322A84] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[RCV] [int] NOT NULL,
[ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPS3REDBLUECARDDTL] ADD CONSTRAINT [PK__NPS3REDBLUECARDD__19264EBD] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) ON [PRIMARY]
GO
