CREATE TABLE [dbo].[INPRCADJNOTIFYLOG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__INPRCADJNOT__CLS__10304AB2] DEFAULT (''),
[STAT] [smallint] NOT NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TIME] [datetime] NOT NULL,
[ACT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INPRCADJNOTIFYLOG] ADD CONSTRAINT [PK__INPRCADJNOTIFYLO__11246EEB] PRIMARY KEY CLUSTERED  ([NUM], [CLS], [STAT], [TIME], [ACT]) ON [PRIMARY]
GO
