CREATE TABLE [dbo].[CASHCLTDTL2]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PAYCODE] [smallint] NOT NULL,
[TIMES] [smallint] NOT NULL CONSTRAINT [DF__CASHCLTDT__TIMES__4990833B] DEFAULT (1),
[PICKER] [int] NOT NULL CONSTRAINT [DF__CASHCLTDT__PICKE__4A84A774] DEFAULT (1),
[PICKERTime] [datetime] NOT NULL CONSTRAINT [DF__CASHCLTDT__PICKE__4B78CBAD] DEFAULT (getdate()),
[REALAMT] [money] NOT NULL CONSTRAINT [DF__CASHCLTDT__REALA__4C6CEFE6] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[OPER] [int] NOT NULL CONSTRAINT [DF__CASHCLTDTL__OPER__19C3D68D] DEFAULT (1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CASHCLTDTL2] ADD CONSTRAINT [PK__CASHCLTDTL2__23F3538A] PRIMARY KEY CLUSTERED  ([NUM], [PAYCODE], [TIMES]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
