CREATE TABLE [dbo].[TMP_PFA_REGISTER_STACK]
(
[SPID] [smallint] NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[FKEY] [varchar] (500) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TMP_PFA_REGISTER_STACK] ADD CONSTRAINT [PK__TMP_PFA_REGISTER__59CA1860] PRIMARY KEY CLUSTERED  ([SPID], [ITEMNO]) ON [PRIMARY]
GO
