CREATE TABLE [dbo].[CstMize]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[VENDOR] [int] NOT NULL CONSTRAINT [DF__CstMize__VENDOR__5483DE51] DEFAULT (1),
[CLIENT] [int] NOT NULL CONSTRAINT [DF__CstMize__CLIENT__5578028A] DEFAULT (1),
[BILLTO] [int] NOT NULL CONSTRAINT [DF__CstMize__BILLTO__566C26C3] DEFAULT (1),
[TOTAL] [money] NOT NULL CONSTRAINT [DF__CstMize__TOTAL__57604AFC] DEFAULT (0),
[TAX] [money] NOT NULL CONSTRAINT [DF__CstMize__TAX__58546F35] DEFAULT (0),
[GTOTAL] [money] NOT NULL CONSTRAINT [DF__CstMize__GTOTAL__5948936E] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__CstMize__FILDATE__5A3CB7A7] DEFAULT (getdate()),
[CHKDATE] [datetime] NULL,
[CFMDATE] [datetime] NULL,
[GATHDATE] [datetime] NULL,
[PREPAY] [money] NOT NULL CONSTRAINT [DF__CstMize__PREPAY__5B30DBE0] DEFAULT (0),
[FILLER] [int] NOT NULL CONSTRAINT [DF__CstMize__FILLER__5C250019] DEFAULT (1),
[CHECKER] [int] NOT NULL CONSTRAINT [DF__CstMize__CHECKER__5D192452] DEFAULT (1),
[CONFIRMER] [int] NOT NULL CONSTRAINT [DF__CstMize__CONFIRM__5E0D488B] DEFAULT (1),
[CASHIER] [int] NOT NULL CONSTRAINT [DF__CstMize__CASHIER__5F016CC4] DEFAULT (1),
[SLR] [int] NOT NULL CONSTRAINT [DF__CstMize__SLR__5FF590FD] DEFAULT (1),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__CstMize__STAT__60E9B536] DEFAULT (0),
[MODNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[WRH] [int] NOT NULL CONSTRAINT [DF__CstMize__WRH__61DDD96F] DEFAULT (1),
[RECCNT] [int] NOT NULL CONSTRAINT [DF__CstMize__RECCNT__62D1FDA8] DEFAULT (0),
[SRC] [int] NOT NULL,
[SRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[RECEIVER] [int] NOT NULL,
[PRNTIME] [datetime] NULL,
[FINISHED] [int] NOT NULL CONSTRAINT [DF__CstMize__FINISHE__63C621E1] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CstMize] WITH NOCHECK ADD CONSTRAINT [CSTMIZE_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[CstMize] ADD CONSTRAINT [PK__CstMize__39E294A9] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FILDATE] ON [dbo].[CstMize] ([FILDATE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
