CREATE TABLE [dbo].[财务库存]
(
[settleno] [int] NOT NULL,
[gid] [int] NOT NULL,
[QtyWW] [money] NOT NULL CONSTRAINT [DF__财务库存__QtyWW__232BAE88] DEFAULT (0),
[QtyWY] [money] NOT NULL CONSTRAINT [DF__财务库存__QtyWY__241FD2C1] DEFAULT (0),
[QtyYW] [money] NOT NULL CONSTRAINT [DF__财务库存__QtyYW__2513F6FA] DEFAULT (0),
[QtyYY] [money] NOT NULL CONSTRAINT [DF__财务库存__QtyYY__26081B33] DEFAULT (0),
[QtyWWQC] [money] NOT NULL CONSTRAINT [DF__财务库存__QtyWWQC__26FC3F6C] DEFAULT (0),
[QtyWYQC] [money] NOT NULL CONSTRAINT [DF__财务库存__QtyWYQC__27F063A5] DEFAULT (0),
[QtyYWQC] [money] NOT NULL CONSTRAINT [DF__财务库存__QtyYWQC__28E487DE] DEFAULT (0),
[QtyYYQC] [money] NOT NULL CONSTRAINT [DF__财务库存__QtyYYQC__29D8AC17] DEFAULT (0),
[AmtWW] [money] NOT NULL CONSTRAINT [DF__财务库存__AmtWW__2ACCD050] DEFAULT (0),
[AmtWY] [money] NOT NULL CONSTRAINT [DF__财务库存__AmtWY__2BC0F489] DEFAULT (0),
[AmtYW] [money] NOT NULL CONSTRAINT [DF__财务库存__AmtYW__2CB518C2] DEFAULT (0),
[AmtYY] [money] NOT NULL CONSTRAINT [DF__财务库存__AmtYY__2DA93CFB] DEFAULT (0),
[AmtWWQC] [money] NOT NULL CONSTRAINT [DF__财务库存__AmtWWQC__2E9D6134] DEFAULT (0),
[AmtWYQC] [money] NOT NULL CONSTRAINT [DF__财务库存__AmtWYQC__2F91856D] DEFAULT (0),
[AmtYWQC] [money] NOT NULL CONSTRAINT [DF__财务库存__AmtYWQC__3085A9A6] DEFAULT (0),
[AmtYYQC] [money] NOT NULL CONSTRAINT [DF__财务库存__AmtYYQC__3179CDDF] DEFAULT (0)
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [cwkc_gid] ON [dbo].[财务库存] ([settleno], [gid]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
