CREATE TABLE [dbo].[NBUY2]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[SETTLENO] [int] NOT NULL,
[GID] [int] NOT NULL,
[QTY] [money] NOT NULL CONSTRAINT [DF__NBUY2__QTY__36139A73] DEFAULT (0),
[INPRC] [money] NOT NULL CONSTRAINT [DF__NBUY2__INPRC__3707BEAC] DEFAULT (0),
[PRICE] [money] NOT NULL CONSTRAINT [DF__NBUY2__PRICE__37FBE2E5] DEFAULT (0),
[REALAMT] [money] NOT NULL CONSTRAINT [DF__NBUY2__REALAMT__38F0071E] DEFAULT (0),
[FAVAMT] [money] NOT NULL CONSTRAINT [DF__NBUY2__FAVAMT__39E42B57] DEFAULT (0),
[TAG] [smallint] NOT NULL CONSTRAINT [DF__NBUY2__TAG__3AD84F90] DEFAULT (0),
[QPCGID] [int] NULL,
[PRMTAG] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[ASSISTANT] [int] NULL,
[WRH] [int] NULL CONSTRAINT [DF__NBUY2__WRH__3BCC73C9] DEFAULT (1),
[INVNO] [char] (13) COLLATE Chinese_PRC_CI_AS NULL,
[COST] [money] NOT NULL CONSTRAINT [DF__NBUY2__COST__3CC09802] DEFAULT (0),
[DEALER] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NBUY2] ADD CONSTRAINT [PK__NBUY2__351F763A] PRIMARY KEY CLUSTERED  ([SRC], [ID], [ITEMNO]) ON [PRIMARY]
GO
