CREATE TABLE [dbo].[CQNVDRGD]
(
[GROUPID] [int] NOT NULL,
[RHQUUID] [char] (32) COLLATE Chinese_PRC_CI_AS NULL,
[NTYPE] [int] NOT NULL,
[NSTAT] [int] NOT NULL CONSTRAINT [DF__CQNVDRGD__NSTAT__1979BDCA] DEFAULT (0),
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[EXTIME] [datetime] NOT NULL CONSTRAINT [DF__CQNVDRGD__EXTIME__1A6DE203] DEFAULT (getdate()),
[VDRGID] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[WRH] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CQNVDRGD] ADD CONSTRAINT [PK__CQNVDRGD__1B62063C] PRIMARY KEY CLUSTERED  ([NTYPE], [GROUPID], [VDRGID], [GDGID], [WRH]) ON [PRIMARY]
GO
