CREATE TABLE [dbo].[STKINDTL]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__STKINDTL__CLS__38AF44A5] DEFAULT ('自营'),
[SETTLENO] [int] NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NULL,
[CASES] [money] NULL,
[QTY] [money] NULL,
[LOSS] [money] NULL CONSTRAINT [DF__STKINDTL__LOSS__39A368DE] DEFAULT (0),
[PRICE] [money] NULL,
[TOTAL] [money] NULL,
[TAX] [money] NULL,
[VALIDDATE] [datetime] NULL,
[WRH] [int] NULL CONSTRAINT [DF__STKINDTL__WRH__3A978D17] DEFAULT (1),
[BCKQTY] [money] NULL CONSTRAINT [DF__STKINDTL__BCKQTY__3B8BB150] DEFAULT (0),
[PAYQTY] [money] NULL CONSTRAINT [DF__STKINDTL__PAYQTY__3C7FD589] DEFAULT (0),
[BCKAMT] [money] NULL CONSTRAINT [DF__STKINDTL__BCKAMT__3D73F9C2] DEFAULT (0),
[PAYAMT] [money] NULL CONSTRAINT [DF__STKINDTL__PAYAMT__3E681DFB] DEFAULT (0),
[INPRC] [money] NULL,
[RTLPRC] [money] NULL,
[BNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[subwrh] [int] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[ORDLINE] [int] NOT NULL CONSTRAINT [DF__STKINDTL__ORDLIN__29A3A1ED] DEFAULT (0),
[SNEWFLAG] [int] NOT NULL CONSTRAINT [DF__stkindtl__SNEWFL__08C29C66] DEFAULT (0),
[CHECKOUTFLAG] [int] NULL,
[DecOrdQty] [money] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STKINDTL] WITH NOCHECK ADD CONSTRAINT [付款和退货数必须不大于进货数] CHECK (([QTY]<(0) OR ([QTY]-[BCKQTY])-[PAYQTY]>=(0)))
GO
ALTER TABLE [dbo].[STKINDTL] WITH NOCHECK ADD CONSTRAINT [单号位数必须为10] CHECK NOT FOR REPLICATION ((len([num])=(10) AND left([num],(1))='0'))
GO
ALTER TABLE [dbo].[STKINDTL] ADD CONSTRAINT [PK__STKINDTL__21A0F6C4] PRIMARY KEY CLUSTERED  ([CLS], [NUM], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [stkindtl_gdgid] ON [dbo].[STKINDTL] ([GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
