CREATE TABLE [dbo].[PROCESSGOODSLIST]
(
[JOBID] [int] NOT NULL,
[STOREGID] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[GUID] [varchar] (38) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[QPCSTR] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PROCESSGO__QPCST__083AEE86] DEFAULT ('1*1'),
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PROCESSGOOD__QTY__092F12BF] DEFAULT (1),
[ISGENERATE] [int] NOT NULL CONSTRAINT [DF__PROCESSGO__ISGEN__0A2336F8] DEFAULT (0),
[TOTAL] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PROCESSGO__TOTAL__0B175B31] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROCESSGOODSLIST] ADD CONSTRAINT [PK__ProcessGoodsList__0C0B7F6A] PRIMARY KEY CLUSTERED  ([JOBID], [STOREGID], [GDGID], [GUID], [LINE]) ON [PRIMARY]
GO
