CREATE TABLE [dbo].[STOREGRADEBCKFILE]
(
[CODE] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BCKFILE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BCKFILE2] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STOREGRADEBCKFILE] ADD CONSTRAINT [PK__STOREGRADEBCKFIL__0F32D02F] PRIMARY KEY CLUSTERED  ([CODE], [BCKFILE]) ON [PRIMARY]
GO
