CREATE TABLE [dbo].[PRMDIR]
(
[PRMSEQ] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__PRMDIR__STAT__7139EFA2] DEFAULT (0),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__PRMDIR__LSTUPDTI__722E13DB] DEFAULT (getdate()),
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PRMDIR__LSTUPDOP__73223814] DEFAULT ('未知[-]'),
[TOPIC] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[ASTART] [datetime] NOT NULL,
[AFINISH] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRMDIR] ADD CONSTRAINT [PK__PRMDIR__74165C4D] PRIMARY KEY CLUSTERED  ([PRMSEQ]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PRMDIR_TOPIC] ON [dbo].[PRMDIR] ([TOPIC]) ON [PRIMARY]
GO
