CREATE TABLE [dbo].[PS3SCONOTSCOREGOODS]
(
[GDGID] [int] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3SCONOTSCOREGOODS] ADD CONSTRAINT [PK__PS3SCONOTSCOREGO__1DE96D2C] PRIMARY KEY CLUSTERED  ([GDGID]) ON [PRIMARY]
GO
