CREATE TABLE [dbo].[CusRtlInv]
(
[NUM] [varchar] (15) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLient] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL,
[FILDATE] [datetime] NULL,
[TOTAL] [decimal] (24, 2) NULL,
[ISSUER] [int] NULL,
[STAT] [int] NOT NULL,
[PRNTTIME] [datetime] NULL,
[PRNTCOUNT] [int] NOT NULL CONSTRAINT [DF__CusRtlInv__PRNTC__5478F159] DEFAULT (0),
[RECNO] [int] NOT NULL CONSTRAINT [DF__CusRtlInv__RECNO__556D1592] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[PAYMODE] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CusRtlInv] ADD CONSTRAINT [PK__CusRtlInv__5384CD20] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
