CREATE TABLE [dbo].[DIRALC]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ORDNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SETTLENO] [int] NULL,
[VENDOR] [int] NULL,
[SENDER] [int] NULL,
[RECEIVER] [int] NULL,
[OCRDATE] [datetime] NULL CONSTRAINT [DF__DIRALC__OCRDATE__14FBF414] DEFAULT (getdate()),
[PSR] [int] NULL,
[TOTAL] [money] NULL,
[TAX] [money] NULL,
[ALCTOTAL] [money] NULL,
[STAT] [smallint] NULL CONSTRAINT [DF__DIRALC__STAT__15F0184D] DEFAULT (0),
[SRC] [int] NULL,
[SRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SRCORDNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NULL,
[FILLER] [int] NULL CONSTRAINT [DF__DIRALC__FILLER__16E43C86] DEFAULT (1),
[CHECKER] [int] NULL CONSTRAINT [DF__DIRALC__CHECKER__17D860BF] DEFAULT (1),
[MODNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[VENDORNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[FILDATE] [datetime] NULL CONSTRAINT [DF__DIRALC__FILDATE__18CC84F8] DEFAULT (getdate()),
[FINISHED] [smallint] NULL CONSTRAINT [DF__DIRALC__FINISHED__19C0A931] DEFAULT (0),
[PRNTIME] [datetime] NULL,
[CHKDATE] [datetime] NULL,
[WRH] [int] NULL,
[GEN] [int] NULL,
[GENBILL] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[GENCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[GENNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[PRECHECKER] [int] NULL CONSTRAINT [DF__diralc__PRECHECK__719E7495] DEFAULT (0),
[PRECHKDATE] [datetime] NULL,
[SLR] [int] NOT NULL CONSTRAINT [DF__DIRALC__SLR__1022FBB5] DEFAULT (1),
[OUTTAX] [money] NOT NULL CONSTRAINT [DF__DIRALC__OUTTAX__11171FEE] DEFAULT (0),
[RCPFINISHED] [smallint] NOT NULL CONSTRAINT [DF__DIRALC__RCPFINIS__307ABCAE] DEFAULT (0),
[PAYMODE] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__DirAlc__PAYMODE__4B8483FC] DEFAULT ('应收款'),
[PAYDATE] [datetime] NULL,
[SRCORDCLS] [char] (4) COLLATE Chinese_PRC_CI_AS NULL,
[FROMNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[FROMCLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[VERIFIER] [int] NULL,
[TAXRATELMT] [money] NULL,
[DEPT] [varchar] (13) COLLATE Chinese_PRC_CI_AS NULL,
[ClrOrdQty] [int] NOT NULL CONSTRAINT [DF__DIRALC__ClrOrdQt__77305E15] DEFAULT ('0')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DIRALC] WITH NOCHECK ADD CONSTRAINT [DIRALC_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[DIRALC] ADD CONSTRAINT [PK__DIRALC__4460231C] PRIMARY KEY CLUSTERED  ([CLS], [NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [INX_CLSVDR] ON [dbo].[DIRALC] ([CLS], [VENDOR], [STAT]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FILDATE] ON [dbo].[DIRALC] ([FILDATE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
