CREATE TABLE [dbo].[SVIDTLDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[Item] [smallint] NOT NULL,
[STORE] [int] NOT NULL,
[SETTLENO] [int] NOT NULL,
[DATE] [datetime] NOT NULL,
[VDRGID] [int] NOT NULL,
[WRH] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[QTY] [money] NOT NULL CONSTRAINT [DF__SVIDTLDTL__QTY__760336FF] DEFAULT (0),
[DT1] [money] NOT NULL CONSTRAINT [DF__SVIDTLDTL__DT1__76F75B38] DEFAULT (0),
[DT2] [money] NOT NULL CONSTRAINT [DF__SVIDTLDTL__DT2__77EB7F71] DEFAULT (0),
[DT3] [money] NOT NULL CONSTRAINT [DF__SVIDTLDTL__DT3__78DFA3AA] DEFAULT (0),
[CLS] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__SVIDTLDTL__CLS__047C3EDF] DEFAULT ('代销'),
[ISPAY] [smallint] NOT NULL CONSTRAINT [DF__SVIDTLDTL__ISPAY__06648751] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SVIDTLDTL] ADD CONSTRAINT [PK__SVIDTLDTL__05706318] PRIMARY KEY CLUSTERED  ([CLS], [NUM], [LINE], [Item]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SVIDTLDTL] ADD CONSTRAINT [结算记录不能重复] UNIQUE NONCLUSTERED  ([CLS], [NUM], [STORE], [SETTLENO], [DATE], [VDRGID], [WRH], [GDGID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [SVIDTLDTL_GDGID] ON [dbo].[SVIDTLDTL] ([GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
