CREATE TABLE [dbo].[PSCSSCFGSCHEMEDTL]
(
[UUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[CFGCODE] [varchar] (128) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CFGVALUE] [varchar] (1024) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSCSSCFGSCHEMEDTL] ADD CONSTRAINT [PK__PSCSSCFGSCHEMEDT__52FD1F40] PRIMARY KEY CLUSTERED  ([UUID], [ITEMNO]) ON [PRIMARY]
GO
