CREATE TABLE [dbo].[SALEBCKDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[SETTLENO] [int] NOT NULL,
[DSPLINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[AVAQTY] [money] NOT NULL,
[SALEPRICE] [money] NOT NULL,
[QTY] [money] NOT NULL,
[PRICE] [money] NOT NULL,
[TOTAL] [money] NOT NULL,
[INPRC] [money] NOT NULL,
[RTLPRC] [money] NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SUBWRH] [int] NULL,
[INVQTY] [money] NOT NULL,
[SUBQTY] [money] NOT NULL,
[RCPQTY] [money] NOT NULL CONSTRAINT [DF__SALEBCKDT__RCPQT__5A70F67A] DEFAULT (0),
[RCPAMT] [money] NOT NULL CONSTRAINT [DF__SALEBCKDT__RCPAM__5B651AB3] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SALEBCKDTL] ADD CONSTRAINT [PK__SALEBCKDTL__190BB0C3] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [salebckdtl_gdgid] ON [dbo].[SALEBCKDTL] ([GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
