CREATE TABLE [dbo].[NVDRPAY]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NVDRPAY__FILDATE__5E9A85CC] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ACNTER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[STAT] [smallint] NOT NULL,
[PRNTIME] [datetime] NULL,
[PAYTOTAL] [decimal] (24, 2) NOT NULL,
[MODNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[VGID] [int] NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__NVDRPAY__LSTUPDT__5F8EAA05] DEFAULT (getdate()),
[SETTLEACCOUNTNO] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[DEPT] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[ABOLISHRESON] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[STSTORE] [int] NULL,
[SNDTIME] [datetime] NULL,
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[NTYPE] [smallint] NOT NULL,
[NSTAT] [int] NOT NULL,
[NNOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVDRPAY] ADD CONSTRAINT [PK__NVDRPAY__6082CE3E] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
