CREATE TABLE [dbo].[LTDADJSCHEME]
(
[CODE] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[LTDGROUP] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LTDADJSCHEME] ADD CONSTRAINT [PK__LTDADJSCHEME__6C114F1F] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
