CREATE TABLE [dbo].[PROMFPRC]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__PROMFPRC__STAT__3430160B] DEFAULT (0),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__PROMFPRC__FILDAT__35243A44] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[CHKDATE] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__PROMFPRC__LSTUPD__36185E7D] DEFAULT (getdate()),
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PROMFPRC__LSTUPD__370C82B6] DEFAULT ('未知[-]'),
[TOPIC] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[ASTART] [datetime] NOT NULL,
[AFINISH] [datetime] NOT NULL,
[CYCLE] [datetime] NULL,
[CSTART] [datetime] NULL,
[CFINISH] [datetime] NULL,
[CSPEC] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[PSETTLENO] [int] NULL,
[MONTHSETTLENO] [int] NOT NULL CONSTRAINT [DF__PROMFPRC__MONTHS__3800A6EF] DEFAULT (0),
[OCRTIME] [datetime] NULL,
[SRCLSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__PROMFPRC__SRCLST__38F4CB28] DEFAULT (getdate()),
[SRCNUM] [varchar] (16) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROMFPRC] ADD CONSTRAINT [PK__PROMFPRC__39E8EF61] PRIMARY KEY CLUSTERED  ([NUM], [CLS]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PROMFPRC_TOPIC] ON [dbo].[PROMFPRC] ([TOPIC]) ON [PRIMARY]
GO
