CREATE TABLE [dbo].[PRMRTNPNTAGM]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL CONSTRAINT [DF__PRMRTNPNT__SETTL__5A6B98E3] DEFAULT (0),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__PRMRTNPNTA__STAT__5B5FBD1C] DEFAULT (0),
[RECCNT] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__PRMRTNPNT__FILDA__5C53E155] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VENDOR] [int] NOT NULL,
[BEGINTIME] [datetime] NOT NULL CONSTRAINT [DF__PRMRTNPNT__BEGIN__5D48058E] DEFAULT (getdate()),
[ENDTIME] [datetime] NOT NULL CONSTRAINT [DF__PRMRTNPNT__ENDTI__5E3C29C7] DEFAULT ('9999.12.31 23:59:59'),
[AUTOGEN] [smallint] NOT NULL CONSTRAINT [DF__PRMRTNPNT__AUTOG__5F304E00] DEFAULT (0),
[GENTIME] [datetime] NULL,
[RTNSTAT] [smallint] NOT NULL CONSTRAINT [DF__PRMRTNPNT__RTNST__60247239] DEFAULT (0),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__PRMRTNPNT__LSTUP__61189672] DEFAULT (getdate()),
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PRMRTNPNT__LSTUP__620CBAAB] DEFAULT ('未知[-]'),
[CHKTIME] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRMRTNPNTAGM] ADD CONSTRAINT [PK__PRMRTNPNTAGM__6300DEE4] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
