CREATE TABLE [dbo].[PROCEXECBILL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[TYPE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILL] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLCLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[EXNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TAG] [int] NOT NULL CONSTRAINT [DF__PROCEXECBIL__TAG__3537B22F] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROCEXECBILL] ADD CONSTRAINT [PK__PROCEXECBILL__362BD668] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
