CREATE TABLE [dbo].[DMDPRMLACDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DMDPRMLACDTL] ADD CONSTRAINT [PK__DMDPRMLACDTL__4B0D20AB] PRIMARY KEY CLUSTERED  ([NUM], [STOREGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
