CREATE TABLE [dbo].[SENDWEATHER]
(
[WEATHER] [int] NOT NULL,
[LOWTMPER] [decimal] (24, 2) NOT NULL,
[HIGHTMPER] [decimal] (24, 2) NOT NULL,
[ADATE] [datetime] NOT NULL,
[OPER] [int] NOT NULL,
[SPECCOND] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_SENDWEATHER] ON [dbo].[SENDWEATHER] ([ADATE], [OPER]) ON [PRIMARY]
GO
