CREATE TABLE [dbo].[MONTHSETTLE]
(
[NO] [int] NOT NULL,
[BEGINDATE] [datetime] NULL,
[ENDDATE] [datetime] NULL CONSTRAINT [DF__MONTHSETT__ENDDA__75ED5D0F] DEFAULT ('12/31/2099'),
[EMPLOYEECODE] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[EMPLOYEENAME] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[NANO] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MONTHSETTLE] WITH NOCHECK ADD CONSTRAINT [终止时间不能小于起始时间] CHECK (([BEGINDATE]<=[ENDDATE]))
GO
ALTER TABLE [dbo].[MONTHSETTLE] ADD CONSTRAINT [PK__MONTHSETTLE__10AB74EC] PRIMARY KEY CLUSTERED  ([NO]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
