CREATE TABLE [dbo].[LMTPRMDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SETTLENO] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[START] [datetime] NOT NULL CONSTRAINT [DF__LMTPRMDTL__START__0B335E0F] DEFAULT ('1899.12.30 00:00:00'),
[FINISH] [datetime] NOT NULL CONSTRAINT [DF__LMTPRMDTL__FINIS__0C278248] DEFAULT ('9999.12.31 23:59:59'),
[QTYLMT] [money] NOT NULL CONSTRAINT [DF__LMTPRMDTL__QTYLM__0D1BA681] DEFAULT (0),
[PRICE] [money] NOT NULL CONSTRAINT [DF__LMTPRMDTL__PRICE__0E0FCABA] DEFAULT (0),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__LMTPRMDTL__STAT__0F03EEF3] DEFAULT (0),
[LSTID] [char] (16) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LMTPRMDTL] ADD CONSTRAINT [PK__LMTPRMDTL__0A3F39D6] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [lmtprmdtl_gdgid] ON [dbo].[LMTPRMDTL] ([GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
