CREATE TABLE [dbo].[CRMCARDSTAT]
(
[STAT] [smallint] NOT NULL,
[NAME] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMCARDSTAT] ADD CONSTRAINT [PK__CRMCARDSTAT__56A1FC44] PRIMARY KEY CLUSTERED  ([STAT]) ON [PRIMARY]
GO
