CREATE TABLE [dbo].[PS3NSCORE]
(
[UUID] [varchar] (36) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[NSCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [d_ps3nscore_1] DEFAULT (1),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SCORESORT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PS3NSCORE__SCORE__08E75C01] DEFAULT ('-'),
[CARDTYPE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3NSCORE] ADD CONSTRAINT [PK__PS3NSCORE__0D370FD2] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
