CREATE TABLE [dbo].[CRMWEBLOG]
(
[CATEGORY] [smallint] NOT NULL CONSTRAINT [DF__CRMWEBLOG__CATEG__09EC9620] DEFAULT (0),
[OPERTIME] [datetime] NOT NULL CONSTRAINT [DF__CRMWEBLOG__OPERT__0AE0BA59] DEFAULT (getdate()),
[OPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMWEBLOG__OPER__0BD4DE92] DEFAULT ('未知[-]'),
[STOREGID] [int] NOT NULL CONSTRAINT [DF__CRMWEBLOG__STORE__0CC902CB] DEFAULT (1),
[STORECODE] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMWEBLOG__STORE__0DBD2704] DEFAULT ('-'),
[WORKSTATION] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[USERGID] [int] NOT NULL CONSTRAINT [DF__CRMWEBLOG__USERG__0EB14B3D] DEFAULT (1),
[USERCODE] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMWEBLOG__USERC__0FA56F76] DEFAULT ('-'),
[CONTENT] [text] COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
