CREATE TABLE [dbo].[SPVOUCHERLOG]
(
[SN] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__SPVOUCHERLOG__SN__0B95B2C7] DEFAULT (''),
[ITEMNO] [int] NOT NULL,
[FROMSTAT] [smallint] NULL,
[TOSTAT] [smallint] NOT NULL,
[OPER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[OPERTIME] [datetime] NOT NULL,
[SRC] [int] NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SPVOUCHERLOG] ADD CONSTRAINT [PK__SPVOUCHERLOG__0AA18E8E] PRIMARY KEY CLUSTERED  ([SN], [ITEMNO]) ON [PRIMARY]
GO
