CREATE TABLE [dbo].[VOUCHERGIVERULEPRMOUTDTLOCR]
(
[BILLNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLLINE] [int] NOT NULL,
[PRMTOPIC] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[PRMNAME] [varchar] (32) COLLATE Chinese_PRC_CI_AS NULL,
[PRMBILL] [varchar] (32) COLLATE Chinese_PRC_CI_AS NULL,
[PRMCLS] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[PRMNUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NULL,
[PRMTAG] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERGIVERULEPRMOUTDTLOCR] ADD CONSTRAINT [PK__VOUCHERGIVERULEP__3B21036F] PRIMARY KEY CLUSTERED  ([BILLNUM], [BILLLINE]) ON [PRIMARY]
GO
