CREATE TABLE [dbo].[NETRECVLOG]
(
[CLS] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILENAME] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[NETNUM] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[MODIFIER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_LOG_TIME] ON [dbo].[NETRECVLOG] ([TIME]) ON [PRIMARY]
GO
