CREATE TABLE [dbo].[PS3SCOUNITESCORE]
(
[UUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MINAMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3SCOUNI__MINAM__24966ABB] DEFAULT (0),
[AMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3SCOUNI__AMOUN__258A8EF4] DEFAULT (0),
[SCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3SCOUNI__SCORE__267EB32D] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3SCOUNITESCORE] ADD CONSTRAINT [PK__PS3SCOUNITESCORE__2772D766] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
