CREATE TABLE [dbo].[VOUCHERACTBCKVOUACTGETDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[ITEM] [int] NOT NULL,
[VOUCHERNUM] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VOUCHERAMT] [decimal] (24, 2) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERACTBCKVOUACTGETDTL] ADD CONSTRAINT [PK__VOUCHERACTBCKVOU__66406B9E] PRIMARY KEY CLUSTERED  ([NUM], [LINE], [ITEM]) ON [PRIMARY]
GO
