CREATE TABLE [dbo].[CRMSCORESORT]
(
[CODE] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[FLAG] [int] NOT NULL CONSTRAINT [DF__CRMSCORESO__FLAG__497D0B50] DEFAULT (1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMSCORESORT] ADD CONSTRAINT [PK__CRMSCORESORT__4A712F89] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
