CREATE TABLE [dbo].[ICCARDH]
(
[CardNum] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BYTIME] [datetime] NOT NULL CONSTRAINT [DF__ICCARDH__BYTIME__52A4EC29] DEFAULT ('2001.1.1'),
[BALANCE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__ICCARDH__BALANCE__53991062] DEFAULT (0),
[CONSUME] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__ICCARDH__CONSUME__548D349B] DEFAULT (0),
[Score] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__ICCARDH__Score__558158D4] DEFAULT (0),
[BanTotal] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__ICCARDH__BanTota__56757D0D] DEFAULT (0),
[ScrTotal] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__ICCARDH__ScrTota__5769A146] DEFAULT (0),
[CARDTYPE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARRIER] [int] NOT NULL CONSTRAINT [DF__ICCARDH__CARRIER__585DC57F] DEFAULT (1),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__ICCARDH__STAT__5951E9B8] DEFAULT (0),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__ICCARDH__LSTUPDT__5A460DF1] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ICCARDH] ADD CONSTRAINT [PK__ICCARDH__51B0C7F0] PRIMARY KEY CLUSTERED  ([CardNum], [CARRIER]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
