CREATE TABLE [dbo].[INVCHGDRPT]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[BGDGID] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[DQ1] [money] NULL CONSTRAINT [DF__INVCHGDRPT__DQ1__498FB7E4] DEFAULT (0),
[DQ2] [money] NULL CONSTRAINT [DF__INVCHGDRPT__DQ2__4A83DC1D] DEFAULT (0),
[DQ4] [money] NULL CONSTRAINT [DF__INVCHGDRPT__DQ4__4B780056] DEFAULT (0),
[DQ5] [money] NULL CONSTRAINT [DF__INVCHGDRPT__DQ5__4C6C248F] DEFAULT (0),
[DI1] [money] NULL CONSTRAINT [DF__INVCHGDRPT__DI1__4D6048C8] DEFAULT (0),
[DI2] [money] NULL CONSTRAINT [DF__INVCHGDRPT__DI2__4E546D01] DEFAULT (0),
[DI3] [money] NULL CONSTRAINT [DF__INVCHGDRPT__DI3__4F48913A] DEFAULT (0),
[DI4] [money] NULL CONSTRAINT [DF__INVCHGDRPT__DI4__503CB573] DEFAULT (0),
[DI5] [money] NULL CONSTRAINT [DF__INVCHGDRPT__DI5__5130D9AC] DEFAULT (0),
[DR1] [money] NULL CONSTRAINT [DF__INVCHGDRPT__DR1__5224FDE5] DEFAULT (0),
[DR2] [money] NULL CONSTRAINT [DF__INVCHGDRPT__DR2__5319221E] DEFAULT (0),
[DR3] [money] NULL CONSTRAINT [DF__INVCHGDRPT__DR3__540D4657] DEFAULT (0),
[DR4] [money] NULL CONSTRAINT [DF__INVCHGDRPT__DR4__55016A90] DEFAULT (0),
[DR5] [money] NULL CONSTRAINT [DF__INVCHGDRPT__DR5__55F58EC9] DEFAULT (0),
[DQ6] [money] NOT NULL CONSTRAINT [DF__INVCHGDRPT__DQ6__0821E73A] DEFAULT (0),
[DQ7] [money] NOT NULL CONSTRAINT [DF__INVCHGDRPT__DQ7__09160B73] DEFAULT (0),
[DT6] [money] NOT NULL CONSTRAINT [DF__INVCHGDRPT__DT6__0A0A2FAC] DEFAULT (0),
[DT7] [money] NOT NULL CONSTRAINT [DF__INVCHGDRPT__DT7__0AFE53E5] DEFAULT (0),
[DI6] [money] NOT NULL CONSTRAINT [DF__INVCHGDRPT__DI6__0BF2781E] DEFAULT (0),
[DI7] [money] NOT NULL CONSTRAINT [DF__INVCHGDRPT__DI7__0CE69C57] DEFAULT (0),
[DR6] [money] NOT NULL CONSTRAINT [DF__INVCHGDRPT__DR6__0DDAC090] DEFAULT (0),
[DR7] [money] NOT NULL CONSTRAINT [DF__INVCHGDRPT__DR7__0ECEE4C9] DEFAULT (0),
[DI8] [money] NOT NULL CONSTRAINT [DF__INVCHGDRPT__DI8__695E344F] DEFAULT (0),
[LSTUPDTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INVCHGDRPT] ADD CONSTRAINT [PK__INVCHGDRPT__78D3EB5B] PRIMARY KEY CLUSTERED  ([ADATE], [BGDGID], [BWRH], [ASETTLENO], [ASTORE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
