CREATE TABLE [dbo].[VOUCHERSELLSTOREDTL]
(
[NUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERSELLSTOREDTL] ADD CONSTRAINT [PK__VOUCHERSELLSTORE__5AE09A2F] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_VOUCHERSELLSTOREDTL_STOREGID] ON [dbo].[VOUCHERSELLSTOREDTL] ([STOREGID]) ON [PRIMARY]
GO
