CREATE TABLE [dbo].[RFPCK]
(
[UUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILLER] [int] NOT NULL,
[WRH] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__RFPCK__QTY__2E704870] DEFAULT (0),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__RFPCK__FILDATE__2F646CA9] DEFAULT (getdate()),
[LSTUPDTIME] [datetime] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[GENNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[GENCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SUBWRH] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__RFPCK__SUBWRH__305890E2] DEFAULT (''),
[PDANUM] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RFPCK] ADD CONSTRAINT [PK__RFPCK__314CB51B] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
