CREATE TABLE [dbo].[GFTPRMBCK]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [int] NOT NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL,
[SRC] [int] NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__GFTPRMBCK__LSTUP__1B1656CB] DEFAULT (getdate()),
[NOTE] [text] COLLATE Chinese_PRC_CI_AS NULL,
[SNDNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[FLOWNO] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLIENT] [int] NULL,
[CTRNAME] [char] (16) COLLATE Chinese_PRC_CI_AS NULL,
[GENNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHECKDATE] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[MODNUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NULL,
[SETTLENO] [smallint] NOT NULL CONSTRAINT [DF__GFTPRMBCK__SETTL__4BBB24D4] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GFTPRMBCK] ADD CONSTRAINT [PK__GFTPRMBCK__1A223292] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
