CREATE TABLE [dbo].[ALCGFTAGMGDDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[ALCQTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__ALCGFTAGM__ALCQT__1341C187] DEFAULT (0),
[WRH] [int] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ALCGFTAGMGDDTL] ADD CONSTRAINT [PK__ALCGFTAGMGDDTL__1435E5C0] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
