CREATE TABLE [dbo].[NDMDPRM]
(
[ID] [int] NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NDMDPRM__FILDATE__3AC40C4E] DEFAULT (getdate()),
[FILLER] [int] NOT NULL CONSTRAINT [DF__NDMDPRM__FILLER__3BB83087] DEFAULT (1),
[RECCNT] [int] NOT NULL CONSTRAINT [DF__NDMDPRM__RECCNT__3CAC54C0] DEFAULT (0),
[NSTAT] [smallint] NOT NULL,
[EON] [smallint] NOT NULL CONSTRAINT [DF__NDMDPRM__EON__3DA078F9] DEFAULT (1),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[RCV] [int] NOT NULL,
[SNDTIME] [datetime] NOT NULL,
[RCVTIME] [datetime] NULL,
[FRCCHK] [smallint] NOT NULL,
[TYPE] [smallint] NOT NULL,
[RATIFYSTORE] [int] NOT NULL,
[SUBMITDATE] [datetime] NULL,
[SUBMITTER] [int] NULL,
[RATIFYDATE] [datetime] NULL,
[RATIFIER] [int] NULL,
[LAUNCH] [datetime] NULL,
[STAT] [smallint] NULL CONSTRAINT [DF__NDMDPRM__STAT__74B24D6F] DEFAULT (0),
[SRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[TOPIC] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[CANCELDATE] [datetime] NULL,
[CANCELER] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NDMDPRM] ADD CONSTRAINT [PK__NDMDPRM__1FEDB87C] PRIMARY KEY CLUSTERED  ([SRC], [ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NDMDPRM_TYPE] ON [dbo].[NDMDPRM] ([TYPE]) ON [PRIMARY]
GO
