CREATE TABLE [dbo].[PSTASKFORMULAPARAM]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FCODE] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PARAMNAME] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PARAMVALUE] [varchar] (120) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSTASKFORMULAPARAM] ADD CONSTRAINT [PK__PSTASKFORMULAPAR__09592FF1] PRIMARY KEY CLUSTERED  ([NUM], [PARAMNAME]) ON [PRIMARY]
GO
