CREATE TABLE [dbo].[ORDERPOOLLOG]
(
[ATIME] [datetime] NOT NULL,
[SETTLENO] [smallint] NULL,
[ATYPE] [smallint] NULL CONSTRAINT [DF__ORDERPOOL__ATYPE__0128A0AD] DEFAULT (0),
[ACALLER] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[CONTENT] [text] COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
