CREATE TABLE [dbo].[VDRSENDAREA]
(
[CODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TAG] [int] NULL,
[NOTE] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VDRSENDAREA] ADD CONSTRAINT [PK__VDRSENDAREA__759AB959] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
