CREATE TABLE [dbo].[RTLCURDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[CURRENCY] [smallint] NOT NULL,
[AMOUNT] [money] NOT NULL,
[CARDNUM] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CardBalance] [decimal] (24, 4) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RTLCURDTL] ADD CONSTRAINT [PK__RTLCURDTL__1352D76D] PRIMARY KEY CLUSTERED  ([NUM], [ITEMNO]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
