CREATE TABLE [dbo].[NRTLPRCADJDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[OLDRTLPRC] [money] NOT NULL,
[NEWRTLPRC] [money] NULL,
[OLDLWTPRC] [money] NULL,
[NEWLWTPRC] [money] NULL,
[OLDTOPPRC] [money] NULL,
[NEWTOPPRC] [money] NULL,
[QTY] [money] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[OLDMBRPRC] [money] NULL,
[NEWMBRPRC] [money] NULL,
[OLDWHSPRC] [money] NULL,
[NEWWHSPRC] [money] NULL,
[QPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NRTLPRCADJD__QPC__4350C75C] DEFAULT (1),
[QPCSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NRTLPRCAD__QPCST__4444EB95] DEFAULT ('1*1')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NRTLPRCADJDTL] ADD CONSTRAINT [PK__NRTLPRCADJDTL__2A239031] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) ON [PRIMARY]
GO
