CREATE TABLE [dbo].[STORERETAIL]
(
[Num] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[Cls] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[Stat] [smallint] NOT NULL CONSTRAINT [DF__STORERETAI__Stat__7FDAB2AF] DEFAULT (0),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__STORERETA__LSTUP__00CED6E8] DEFAULT (getdate()),
[LastModifier] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__STORERETA__LastM__01C2FB21] DEFAULT ('未知[-]'),
[Remark] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[Filler] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL,
[FilDate] [datetime] NOT NULL CONSTRAINT [DF__STORERETA__FilDa__02B71F5A] DEFAULT (getdate()),
[SettleNo] [int] NOT NULL,
[PRNTIME] [datetime] NULL,
[Seller] [int] NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SellerApproveTime] [datetime] NULL,
[SellerApprover] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL,
[SellerWrh] [int] NOT NULL,
[SellerReceiveDate] [datetime] NULL,
[Sender] [int] NOT NULL,
[SenderWrh] [int] NOT NULL,
[SenderActionCode] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Buyer] [int] NULL,
[BuyerName] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[BuyerAddress] [varchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[BuyerRegion] [varchar] (200) COLLATE Chinese_PRC_CI_AS NULL,
[BuyerTelephone] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[BuyerActionCode] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[BuyerOrderTime] [datetime] NULL,
[BuyerOrderExpirationDate] [datetime] NULL,
[Total] [decimal] (24, 2) NOT NULL,
[Tax] [decimal] (24, 2) NOT NULL,
[Earnest] [decimal] (24, 2) NULL,
[ReceiveTotal] [decimal] (24, 2) NULL,
[ElseTotal] [decimal] (24, 2) NULL,
[Dealer] [int] NULL,
[CardNum] [varchar] (128) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL,
[SCORE] [decimal] (24, 2) NULL,
[ImportToPO] [int] NOT NULL CONSTRAINT [DF__STORERETA__Impor__03AB4393] DEFAULT (0),
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STORERETAIL] ADD CONSTRAINT [PK__StoreRetail__049F67CC] PRIMARY KEY CLUSTERED  ([Num], [Cls]) ON [PRIMARY]
GO
