CREATE TABLE [dbo].[NMKTPRCSCHEMEGDDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[GDQPCSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NMKTPRCSC__GDQPC__385415FC] DEFAULT ('1*1'),
[GDQPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NMKTPRCSC__GDQPC__39483A35] DEFAULT (1),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NMKTPRCSCHEMEGDDTL] ADD CONSTRAINT [PK__NMktPrcSchemeGDD__3A3C5E6E] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) ON [PRIMARY]
GO
