CREATE TABLE [dbo].[GFTPRMGOODS]
(
[RCODE] [char] (18) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDCOND] [text] COLLATE Chinese_PRC_CI_AS NULL,
[GDCONDTEXT] [text] COLLATE Chinese_PRC_CI_AS NULL,
[FILTERCNSTR] [text] COLLATE Chinese_PRC_CI_AS NOT NULL,
[QTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMGOODS__QTY__64BA461A] DEFAULT (0),
[AMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMGOODS__AMT__65AE6A53] DEFAULT (0),
[LOW] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMGOODS__LOW__445EBE38] DEFAULT (0),
[HIGH] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMGOOD__HIGH__4552E271] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GFTPRMGOODS] ADD CONSTRAINT [PK__GFTPRMGOODS__63C621E1] PRIMARY KEY CLUSTERED  ([RCODE], [LINE]) ON [PRIMARY]
GO
