CREATE TABLE [dbo].[BATCHINGOODSLOG]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[GDNAME] [varchar] (65) COLLATE Chinese_PRC_CI_AS NOT NULL,
[EMPNAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CREATETIME] [datetime] NOT NULL,
[NOTE] [varchar] (256) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BATCHINGOODSLOG] ADD CONSTRAINT [PK__BATCHINGOODSLOG__236F9E5D] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
