CREATE TABLE [dbo].[SXFREASON]
(
[CODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ENGDESC] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[CHNDESC] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[LMODDATE] [datetime] NOT NULL CONSTRAINT [DF__SXFREASON__LMODD__2EDEEF04] DEFAULT (getdate()),
[LMODOPID] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__SXFREASON__LMODO__2FD3133D] DEFAULT ('未知[-]')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SXFREASON] ADD CONSTRAINT [PK__SXFREASON__2DEACACB] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
