CREATE TABLE [dbo].[NIPA2SWDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[SUBWRH] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[INBILL] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[INCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[INNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[INLINE] [smallint] NOT NULL,
[QTY] [money] NOT NULL CONSTRAINT [DF__NIPA2SWDTL__QTY__03DD2061] DEFAULT (0),
[ADJCOST] [money] NOT NULL,
[NEWPRC] [money] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NIPA2SWDTL] ADD CONSTRAINT [PK__NIPA2SWDTL__02E8FC28] PRIMARY KEY CLUSTERED  ([SRC], [ID], [SUBWRH]) ON [PRIMARY]
GO
