CREATE TABLE [dbo].[NBCKDMDSPLITDTL]
(
[DMDSTORE] [int] NOT NULL,
[NEWNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRCNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NEWCLS] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRCCLS] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[NEWLINE] [int] NULL,
[SRCLINE] [int] NOT NULL,
[STAT] [int] NULL,
[OCRDATE] [datetime] NULL CONSTRAINT [DF__NBCKDMDSP__OCRDA__71CA2875] DEFAULT (0),
[ID] [int] NOT NULL,
[SRC] [int] NOT NULL,
[RCV] [int] NULL,
[SNDDATE] [datetime] NULL,
[RCVTIME] [datetime] NULL,
[NTYPE] [int] NULL,
[NSTAT] [int] NULL,
[NNOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NBCKDMDSPLITDTL] ADD CONSTRAINT [PK__NBCKDMDSPLITDTL__73B270E7] PRIMARY KEY CLUSTERED  ([ID], [SRC], [SRCNUM], [SRCCLS], [SRCLINE]) ON [PRIMARY]
GO
