CREATE TABLE [dbo].[VOUCHERGIVEGOODS]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[PRICE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__VOUCHERGI__PRICE__532D972A] DEFAULT (0),
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__VOUCHERGIVE__QTY__5421BB63] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[NOMINALAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__VOUCHERGI__NOMIN__5515DF9C] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERGIVEGOODS] ADD CONSTRAINT [PK__VOUCHERGIVEGOODS__560A03D5] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [VOUCHERGIVEGOODS_GDGID] ON [dbo].[VOUCHERGIVEGOODS] ([GDGID]) ON [PRIMARY]
GO
