CREATE TABLE [dbo].[PSNMKTIVGTTYPE]
(
[CODE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CREATOR] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CREATETIME] [datetime] NULL CONSTRAINT [DF__PSNMKTIVG__CREAT__4087D29C] DEFAULT (getdate()),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__PSNMKTIVGT__STAT__417BF6D5] DEFAULT (0),
[SNDTIME] [datetime] NULL,
[ID] [int] NOT NULL,
[SRC] [int] NOT NULL,
[RCV] [int] NULL,
[NTYPE] [int] NULL,
[NSTAT] [int] NULL,
[NNOTE] [char] (255) COLLATE Chinese_PRC_CI_AS NULL,
[RCVTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSNMKTIVGTTYPE] ADD CONSTRAINT [PK__PSNMKTIVGTTYPE__3F93AE63] PRIMARY KEY CLUSTERED  ([CODE], [ID], [SRC]) ON [PRIMARY]
GO
