CREATE TABLE [dbo].[CRMDATAEXGCARD]
(
[CARDNUM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BYTIME] [datetime] NOT NULL CONSTRAINT [DF__CRMDATAEX__BYTIM__48963614] DEFAULT ('2001.1.1'),
[CARDTYPE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARRIER] [int] NOT NULL CONSTRAINT [DF__CRMDATAEX__CARRI__498A5A4D] DEFAULT (1),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__CRMDATAEXG__STAT__4A7E7E86] DEFAULT (0),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__CRMDATAEX__LSTUP__4B72A2BF] DEFAULT (getdate()),
[VERSION] [varchar] (9) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMDATAEX__VERSI__4C66C6F8] DEFAULT ('020000000'),
[MAKETIME] [datetime] NOT NULL,
[SNDTIME] [datetime] NULL,
[FSENDTIME] [datetime] NOT NULL,
[FSRCORG] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FDESTORG] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMDATAEXGCARD] ADD CONSTRAINT [PK__CRMDATAEXGCARD__4D5AEB31] PRIMARY KEY CLUSTERED  ([FSRCORG], [FDESTORG], [FSENDTIME], [CARDNUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_CRMDATAEXGCARD_FST] ON [dbo].[CRMDATAEXGCARD] ([FSENDTIME]) ON [PRIMARY]
GO
