CREATE TABLE [dbo].[ALCDIFF]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[CLIENT] [int] NOT NULL CONSTRAINT [DF__ALCDIFF__CLIENT__0D48F10F] DEFAULT (1),
[BILLTO] [int] NOT NULL CONSTRAINT [DF__ALCDIFF__BILLTO__0E3D1548] DEFAULT (1),
[WRH] [int] NULL,
[FILLER] [int] NOT NULL CONSTRAINT [DF__ALCDIFF__FILLER__0F313981] DEFAULT (1),
[FILDATE] [datetime] NOT NULL,
[REQOPER] [int] NULL,
[REQDATE] [datetime] NULL,
[CHECKER] [int] NULL,
[CHKDATE] [datetime] NULL,
[CANCELER] [int] NULL,
[CACLDATE] [datetime] NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__ALCDIFF__LSTUPDT__10255DBA] DEFAULT (getdate()),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__ALCDIFF__STAT__111981F3] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[CAUSE] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__ALCDIFF__CAUSE__120DA62C] DEFAULT ('不明'),
[ATTITUDE] [smallint] NOT NULL CONSTRAINT [DF__ALCDIFF__ATTITUD__1301CA65] DEFAULT (0),
[ALCFROM] [int] NOT NULL,
[GENNOTE] [varchar] (200) COLLATE Chinese_PRC_CI_AS NULL,
[GENSTAT] [smallint] NOT NULL CONSTRAINT [DF__ALCDIFF__GENSTAT__13F5EE9E] DEFAULT (1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ALCDIFF] ADD CONSTRAINT [PK__ALCDIFF__14EA12D7] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FILDATE] ON [dbo].[ALCDIFF] ([FILDATE]) ON [PRIMARY]
GO
