CREATE TABLE [dbo].[HDMESSAGE]
(
[NO] [int] NOT NULL,
[CONTENT] [char] (512) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HDMESSAGE] ADD CONSTRAINT [PK__HDMESSAG__3214D54831628F0B] PRIMARY KEY CLUSTERED  ([NO]) ON [PRIMARY]
GO
