CREATE TABLE [dbo].[TMPGFTSNDRESULT]
(
[spid] [int] NOT NULL,
[RCODE] [char] (18) COLLATE Chinese_PRC_CI_AS NULL,
[COUNT] [decimal] (24, 2) NULL CONSTRAINT [DF__TMPGFTSND__COUNT__2FDC6987] DEFAULT (0),
[COST] [decimal] (24, 2) NULL CONSTRAINT [DF__TMPGFTSNDR__COST__30D08DC0] DEFAULT (0)
) ON [PRIMARY]
GO
