CREATE TABLE [dbo].[CHARGECHKDTL]
(
[NUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[PAYCLS] [smallint] NOT NULL,
[SHOULDRCVTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CHARGECHK__SHOUL__5A34F80B] DEFAULT (0),
[RCVTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CHARGECHK__RCVTO__5B291C44] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CHARGECHKDTL] ADD CONSTRAINT [PK__CHARGECHKDTL__5C1D407D] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
