CREATE TABLE [dbo].[NPS3NOTSCOREGDSCOPEDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[DEPT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[VENDOR] [int] NULL,
[SORT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[BRAND] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[GDGID] [int] NULL,
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPS3NOTSCOREGDSCOPEDTL] ADD CONSTRAINT [PK__NPS3NOTSCOREGDSC__3D1B2D1E] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPS3NOTSCOREGDSCOPEDTL_5] ON [dbo].[NPS3NOTSCOREGDSCOPEDTL] ([BRAND]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPS3NOTSCOREGDSCOPEDTL_2] ON [dbo].[NPS3NOTSCOREGDSCOPEDTL] ([DEPT]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPS3NOTSCOREGDSCOPEDTL_6] ON [dbo].[NPS3NOTSCOREGDSCOPEDTL] ([GDGID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPS3NOTSCOREGDSCOPEDTL_1] ON [dbo].[NPS3NOTSCOREGDSCOPEDTL] ([NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPS3NOTSCOREGDSCOPEDTL_4] ON [dbo].[NPS3NOTSCOREGDSCOPEDTL] ([SORT]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPS3NOTSCOREGDSCOPEDTL_3] ON [dbo].[NPS3NOTSCOREGDSCOPEDTL] ([VENDOR]) ON [PRIMARY]
GO
