CREATE TABLE [dbo].[AMTADJDTL]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[WRH] [int] NOT NULL,
[VENDOR] [int] NOT NULL,
[ADJAMT] [money] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AMTADJDTL] ADD CONSTRAINT [PK__AMTADJDTL__0FEC5ADD] PRIMARY KEY CLUSTERED  ([CLS], [NUM], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
