CREATE TABLE [dbo].[MKTPRCSCHEMEGDDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[GDQPCSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__MKTPRCSCH__GDQPC__244D1D4F] DEFAULT ('1*1'),
[GDQPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__MKTPRCSCH__GDQPC__25414188] DEFAULT (1),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MKTPRCSCHEMEGDDTL] ADD CONSTRAINT [PK__MktPrcSchemeGDDt__263565C1] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
