CREATE TABLE [dbo].[STORESTATTYPE]
(
[STATTYPENAME] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STORESTATTYPE] ADD CONSTRAINT [PK__STORESTATTYPE__471998A4] PRIMARY KEY CLUSTERED  ([STATTYPENAME]) ON [PRIMARY]
GO
