CREATE TABLE [dbo].[PRMOFFSETDTLTEMP]
(
[spid] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SETTLENO] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[QPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PRMOFFSETDT__QPC__61F7AC12] DEFAULT (1),
[QPCSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PRMOFFSET__QPCST__62EBD04B] DEFAULT ('1*1'),
[AGMNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PRMOFFSET__AGMNU__63DFF484] DEFAULT (''),
[AGMLINE] [int] NULL,
[SAMT] [decimal] (24, 2) NULL,
[RAMT] [decimal] (24, 2) NULL,
[OFFSETPRC] [decimal] (24, 4) NULL,
[CNTINPRC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PRMOFFSET__CNTIN__64D418BD] DEFAULT (0),
[QTY] [decimal] (24, 4) NULL,
[START] [datetime] NOT NULL CONSTRAINT [DF__PRMOFFSET__START__65C83CF6] DEFAULT ('1899.12.30 00:00:00'),
[FINISH] [datetime] NOT NULL CONSTRAINT [DF__PRMOFFSET__FINIS__66BC612F] DEFAULT ('9999.12.31 23:59:59'),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[ALC] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PRMOFFSETDT__ALC__67B08568] DEFAULT (0),
[TOTAL] [decimal] (24, 4) NULL,
[AMOUNT] [decimal] (24, 4) NULL,
[TAX] [decimal] (24, 4) NULL,
[DIFFPRC] [decimal] (24, 4) NULL,
[PAYQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PRMOFFSET__PAYQT__68A4A9A1] DEFAULT (0),
[PAYAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PRMOFFSET__PAYAM__6998CDDA] DEFAULT (0),
[SQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PRMOFFSETD__SQTY__6A8CF213] DEFAULT (0),
[AGMTABLENAME] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PRMOFFSET__AGMTA__6B81164C] DEFAULT ('PRMOFFSETAGM')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRMOFFSETDTLTEMP] ADD CONSTRAINT [PK__PRMOFFSETDTLTEMP__6C753A85] PRIMARY KEY CLUSTERED  ([spid], [NUM], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PRMOFFSETDTLTEMP_GDGID] ON [dbo].[PRMOFFSETDTLTEMP] ([spid], [GDGID]) ON [PRIMARY]
GO
