CREATE TABLE [dbo].[NINVDRPT]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ASTORE] [int] NULL,
[ASETTLENO] [int] NULL,
[ADATE] [datetime] NULL,
[BGDGID] [int] NULL,
[BWRH] [int] NULL,
[CQ] [money] NULL CONSTRAINT [DF__NINVDRPT__CQ__10773619] DEFAULT (0),
[CT] [money] NULL CONSTRAINT [DF__NINVDRPT__CT__116B5A52] DEFAULT (0),
[FQ] [money] NULL CONSTRAINT [DF__NINVDRPT__FQ__125F7E8B] DEFAULT (0),
[FT] [money] NULL CONSTRAINT [DF__NINVDRPT__FT__1353A2C4] DEFAULT (0),
[FINPRC] [money] NULL CONSTRAINT [DF__NINVDRPT__FINPRC__1447C6FD] DEFAULT (0),
[FRTLPRC] [money] NULL CONSTRAINT [DF__NINVDRPT__FRTLPR__153BEB36] DEFAULT (0),
[FDXPRC] [money] NULL CONSTRAINT [DF__NINVDRPT__FDXPRC__16300F6F] DEFAULT (0),
[FPAYRATE] [money] NULL CONSTRAINT [DF__NINVDRPT__FPAYRA__172433A8] DEFAULT (0),
[FINVPRC] [money] NULL CONSTRAINT [DF__NINVDRPT__FINVPR__181857E1] DEFAULT (0),
[FLSTINPRC] [money] NULL CONSTRAINT [DF__NINVDRPT__FLSTIN__190C7C1A] DEFAULT (0),
[NSTAT] [smallint] NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NULL,
[RCV] [int] NULL,
[SNDTIME] [datetime] NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NULL,
[FINVCOST] [money] NOT NULL CONSTRAINT [DF__NINVDRPT__FINVCO__3C0B9F94] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NINVDRPT] ADD CONSTRAINT [PK__NINVDRPT__35DCF99B] PRIMARY KEY CLUSTERED  ([ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
