CREATE TABLE [dbo].[STOREOPERSCHEME]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__STOREOPERS__STAT__1191B09B] DEFAULT (0),
[SETTLENO] [int] NOT NULL CONSTRAINT [DF__STOREOPER__SETTL__1285D4D4] DEFAULT (0),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__STOREOPER__FILDA__1379F90D] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[CHKDATE] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__STOREOPER__LSTUP__146E1D46] DEFAULT (getdate()),
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__STOREOPER__LSTUP__1562417F] DEFAULT ('未知[-]'),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STOREOPERSCHEME] ADD CONSTRAINT [PK__STOREOPERSCHEME__165665B8] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [STOREOPERSCHEME_FILDATE] ON [dbo].[STOREOPERSCHEME] ([FILDATE]) ON [PRIMARY]
GO
