CREATE TABLE [dbo].[FAMODULEREFDEFDTL]
(
[NO] [int] NOT NULL,
[ITEMNO] [int] NOT NULL,
[MODULENO] [int] NOT NULL,
[MODULECAPTION] [varchar] (120) COLLATE Chinese_PRC_CI_AS NULL,
[VISIBLE] [int] NOT NULL CONSTRAINT [DF__FAMODULER__VISIB__6630BA9C] DEFAULT (1),
[ICONID] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FAMODULEREFDEFDTL] ADD CONSTRAINT [PK__FAMODULEREFDEFDT__6724DED5] PRIMARY KEY CLUSTERED  ([NO], [ITEMNO]) ON [PRIMARY]
GO
