CREATE TABLE [dbo].[PSFORMULABASICDTL]
(
[CODE] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PARAMNO] [int] NOT NULL,
[PARAMNAME] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PARAMVALUE] [varchar] (120) COLLATE Chinese_PRC_CI_AS NULL,
[PARAMVALTAG] [smallint] NOT NULL CONSTRAINT [DF__PSFORMULA__PARAM__69016EF8] DEFAULT (0),
[VALUECAPTION] [varchar] (120) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSFORMULABASICDTL] ADD CONSTRAINT [PK__PSFORMULABASICDT__69F59331] PRIMARY KEY CLUSTERED  ([CODE], [PARAMNO]) ON [PRIMARY]
GO
