CREATE TABLE [dbo].[VOUCHERGIVERULEAMTCONDDTLOCR]
(
[BILLNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLLINE] [int] NOT NULL,
[TOTAL] [decimal] (24, 2) NOT NULL,
[QTY] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERGIVERULEAMTCONDDTLOCR] ADD CONSTRAINT [PK__VOUCHERGIVERULEA__3EF19453] PRIMARY KEY CLUSTERED  ([BILLNUM], [BILLLINE]) ON [PRIMARY]
GO
