CREATE TABLE [dbo].[NPRCSCHEMEDTL]
(
[ID] [int] NOT NULL,
[CODE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[GDQPCSTR] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NPRCSCHEM__GDQPC__57F47C82] DEFAULT ('1*1'),
[PRCCLS] [char] (8) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NPRCSCHEM__PRCCL__58E8A0BB] DEFAULT ('核算售价'),
[CTRMODE] [int] NOT NULL CONSTRAINT [DF__NPRCSCHEM__CTRMO__59DCC4F4] DEFAULT (0),
[SRC] [int] NOT NULL CONSTRAINT [DF__NPRCSCHEMED__SRC__5AD0E92D] DEFAULT (1),
[SNDTIME] [datetime] NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[LaunchByStore] [smallint] NOT NULL CONSTRAINT [DF__NPRCSCHEM__Launc__4F6C857E] DEFAULT (0),
[TOPPRC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPRCSCHEM__TOPPR__5060A9B7] DEFAULT (0),
[LOWPRC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPRCSCHEM__LOWPR__5154CDF0] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPRCSCHEMEDTL] ADD CONSTRAINT [PK__NPRCSCHEMEDTL__57005849] PRIMARY KEY CLUSTERED  ([SRC], [RCV], [ID], [CODE], [GDGID], [GDQPCSTR]) ON [PRIMARY]
GO
