CREATE TABLE [dbo].[CTCNTRFIXDATE]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VERSION] [smallint] NOT NULL,
[LINE] [smallint] NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[GENDATE] [datetime] NOT NULL,
[TOTAL] [decimal] (24, 2) NOT NULL,
[CHGBOOKNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[PAYRATE] [decimal] (24, 2) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CTCNTRFIXDATE] ADD CONSTRAINT [PK__CTCNTRFIXDATE__368A326D] PRIMARY KEY CLUSTERED  ([NUM], [VERSION], [LINE], [ITEMNO]) ON [PRIMARY]
GO
