CREATE TABLE [dbo].[NGDSALEADJ]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__NGDSALEADJ__STAT__515D58E3] DEFAULT (0),
[SETTLENO] [int] NULL,
[SRC] [int] NOT NULL,
[PSR] [int] NOT NULL CONSTRAINT [DF__NGDSALEADJ__PSR__52517D1C] DEFAULT (1),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NGDSALEAD__FILDA__5345A155] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[LAUNCH] [datetime] NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__NGDSALEAD__LSTUP__5439C58E] DEFAULT (getdate()),
[PRNTIME] [datetime] NULL,
[SNDTIME] [datetime] NULL,
[EON] [smallint] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__NGDSALEAD__RECCN__552DE9C7] DEFAULT (0),
[ID] [int] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[NSTAT] [smallint] NOT NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[FRCCHK] [smallint] NOT NULL,
[TYPE] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NGDSALEADJ] ADD CONSTRAINT [PK__NGDSALEADJ__506934AA] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
