CREATE TABLE [dbo].[COLGDPRC]
(
[GDGID] [int] NOT NULL,
[COLDATE] [datetime] NOT NULL CONSTRAINT [DF__COLGDPRC__COLDAT__56EA7E59] DEFAULT (getdate()),
[LOCUS] [char] (100) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__COLGDPRC__LOCUS__57DEA292] DEFAULT (''),
[INPRC] [money] NOT NULL CONSTRAINT [DF__COLGDPRC__INPRC__58D2C6CB] DEFAULT (0),
[RTLPRC] [money] NOT NULL CONSTRAINT [DF__COLGDPRC__RTLPRC__59C6EB04] DEFAULT (0),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__COLGDPRC__LSTUPD__5ABB0F3D] DEFAULT (getdate()),
[MODIFIER] [int] NOT NULL,
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COLGDPRC] ADD CONSTRAINT [PK__COLGDPRC__314D4EA8] PRIMARY KEY CLUSTERED  ([GDGID], [COLDATE], [LOCUS]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
