CREATE TABLE [dbo].[RENTCONTRACT]
(
[STOREGID] [int] NOT NULL,
[CONTRACTKIND] [varchar] (255) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CONTRACTSTAT] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[RENTER] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DEPOSITEPAYER] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[NAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[IDCARDNO] [varchar] (18) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PHONE] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SIGNDATE] [datetime] NOT NULL,
[STARTDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[RENT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__RENTCONTRA__RENT__04F3A230] DEFAULT (0),
[DEPOSITE] [decimal] (24, 2) NULL,
[ATTORN] [decimal] (24, 2) NULL,
[OTHERCHARGE] [decimal] (24, 2) NULL,
[RENTCHGRCD] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[OTHERBUSINESS] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[DEVELOPNAME] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[DEVELOPCONTACTWAY] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[DEVELOPDEPARTMENT] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[AMDRCD] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RENTCONTRACT] ADD CONSTRAINT [PK__RENTCONTRACT__05E7C669] PRIMARY KEY CLUSTERED  ([STOREGID]) ON [PRIMARY]
GO
