CREATE TABLE [dbo].[ALCPOOL]
(
[STOREGID] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[LINE] [int] NOT NULL,
[QTY] [money] NOT NULL CONSTRAINT [DF__ALCPOOL__QTY__0AF43244] DEFAULT (0),
[DMDDATE] [datetime] NOT NULL,
[SRCGRP] [smallint] NOT NULL,
[SRCBILL] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SRCCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SRCLINE] [int] NULL,
[SrcQty] [money] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[APARTER] [int] NULL,
[ALCER] [int] NULL,
[ORDTIME] [datetime] NULL,
[ZLGENSTAT] [smallint] NULL CONSTRAINT [DF__ALCPOOL__ZLGENST__2708C312] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ALCPOOL] ADD CONSTRAINT [PK__ALCPOOL__0A000E0B] PRIMARY KEY CLUSTERED  ([STOREGID], [GDGID], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_ALCPOOL_DMDDATE] ON [dbo].[ALCPOOL] ([DMDDATE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_ALCPOOL_SRCGRP] ON [dbo].[ALCPOOL] ([SRCGRP]) ON [PRIMARY]
GO
