CREATE TABLE [dbo].[VDRDRPTLOG]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[BVDRGID] [int] NOT NULL,
[MWRH] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[BGDGID] [int] NOT NULL,
[SALE] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VDRDRPTLOG] ADD CONSTRAINT [PK_VDRDRPTLOG] PRIMARY KEY CLUSTERED  ([ASTORE], [ASETTLENO], [ADATE], [MWRH], [BGDGID], [BVDRGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
