CREATE TABLE [dbo].[NPRCPRMDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NULL,
[PRMTYPE] [smallint] NULL CONSTRAINT [DF__NPRCPRMDT__PRMTY__7B712C3B] DEFAULT (0),
[CANGFT] [smallint] NULL CONSTRAINT [DF__NPRCPRMDT__CANGF__7C655074] DEFAULT (0),
[QPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPRCPRMDTL__QPC__3BAFA594] DEFAULT (1),
[QPCSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NPRCPRMDT__QPCST__3CA3C9CD] DEFAULT ('1*1')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPRCPRMDTL] ADD CONSTRAINT [PK__NPRCPRMDTL__4242D080] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
