CREATE TABLE [dbo].[VDRPAYLOG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VDRPAYLOG] ADD CONSTRAINT [PK__VDRPAYLOG__6A09D673] PRIMARY KEY CLUSTERED  ([TIME], [NUM], [STAT]) ON [PRIMARY]
GO
