CREATE TABLE [dbo].[TMPPROCEXECPOOL]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[SPID] [int] NOT NULL,
[PROCTASKNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PSCPGID] [int] NOT NULL,
[PSCPCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PSCPQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__TMPPROCEX__PSCPQ__7BF51332] DEFAULT (0),
[PRODGID] [int] NULL,
[PRODQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__TMPPROCEX__PRODQ__7CE9376B] DEFAULT (0),
[RAWGID] [int] NULL,
[RAWQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__TMPPROCEX__RAWQT__7DDD5BA4] DEFAULT (0),
[ALCQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__TMPPROCEX__ALCQT__7ED17FDD] DEFAULT (0)
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_TMPPROCEXECDTL_SPID] ON [dbo].[TMPPROCEXECPOOL] ([SPID]) ON [PRIMARY]
GO
