CREATE TABLE [dbo].[PRCPRMLOG]
(
[CLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TIME] [datetime] NOT NULL,
[ACT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRCPRMLOG] ADD CONSTRAINT [PK__PrcPrmLOG__788DCB4B] PRIMARY KEY CLUSTERED  ([CLS], [NUM], [TIME], [ACT]) ON [PRIMARY]
GO
