CREATE TABLE [dbo].[TWICEBUY]
(
[PREBUYFLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PREBUYPOSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BUYFLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BUYPOSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[RECORDTIME] [datetime] NOT NULL,
[PROCED] [smallint] NOT NULL CONSTRAINT [DF__TWICEBUY__PROCED__7D6B87B4] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TWICEBUY] ADD CONSTRAINT [PK__TWICEBUY__7E5FABED] PRIMARY KEY CLUSTERED  ([PREBUYFLOWNO], [PREBUYPOSNO]) ON [PRIMARY]
GO
