CREATE TABLE [dbo].[PS3SCOSPECDEPTSCORE]
(
[UUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DEPT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MINAMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3SCOSPE__MINAM__0BCABCF1] DEFAULT (0),
[AMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3SCOSPE__AMOUN__0CBEE12A] DEFAULT (0),
[SCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3SCOSPE__SCORE__0DB30563] DEFAULT (0),
[BGNDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3SCOSPECDEPTSCORE] ADD CONSTRAINT [PK__PS3SCOSPECDEPTSC__0EA7299C] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3SCOSPECDEPTSCORE] ON [dbo].[PS3SCOSPECDEPTSCORE] ([DEPT]) ON [PRIMARY]
GO
