CREATE TABLE [dbo].[VDRLESSORTBRAND]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SORT] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BRAND] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__VDRLESSOR__BRAND__7280B791] DEFAULT ('-'),
[PAYRATE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__VDRLESSOR__PAYRA__7374DBCA] DEFAULT (0),
[SORTCODE] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__VDRLESSOR__SORTC__166AA8FA] DEFAULT (' '),
[SHOPNO] [char] (30) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VDRLESSORTBRAND] ADD CONSTRAINT [PK__VDRLESSORTBRAND__74690003] PRIMARY KEY CLUSTERED  ([NUM], [SORT], [BRAND]) ON [PRIMARY]
GO
