CREATE TABLE [dbo].[NPS3REDBLUECARDLOG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TIME] [datetime] NOT NULL,
[ACT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPS3REDBLUECARDLOG] ADD CONSTRAINT [PK__NPS3REDBLUECARDL__1B0E972F] PRIMARY KEY CLUSTERED  ([NUM], [TIME], [ACT]) ON [PRIMARY]
GO
