CREATE TABLE [dbo].[CNTRGDSCOPE]
(
[NO] [int] NOT NULL,
[NOTE] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SQL] [char] (300) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SQLTEXT] [char] (400) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
