CREATE TABLE [dbo].[NPS3NOTSCOREGDSCOPE]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__NPS3NOTSCO__STAT__366E2F8F] DEFAULT (0),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NPS3NOTSC__FILDA__376253C8] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[CHKDATE] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__NPS3NOTSC__LSTUP__38567801] DEFAULT (getdate()),
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NPS3NOTSC__LSTUP__394A9C3A] DEFAULT ('未知[-]'),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SETTLENO] [int] NOT NULL CONSTRAINT [DF__NPS3NOTSC__SETTL__3A3EC073] DEFAULT (0),
[RECCNT] [int] NOT NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPS3NOTSCOREGDSCOPE] ADD CONSTRAINT [PK__NPS3NOTSCOREGDSC__3B32E4AC] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPS3NOTSCOREGDSCOPE_1] ON [dbo].[NPS3NOTSCOREGDSCOPE] ([NUM]) ON [PRIMARY]
GO
