CREATE TABLE [dbo].[WEBSBUY11RECORD]
(
[UUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SHOPCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSID] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[PAYMENTCODE] [smallint] NOT NULL,
[AMOUNT] [decimal] (24, 4) NOT NULL,
[CHANGE] [decimal] (24, 4) NOT NULL,
[DISCHANGE] [decimal] (24, 4) NOT NULL,
[CARDCODE] [varchar] (128) COLLATE Chinese_PRC_CI_AS NULL,
[BANKCODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[BILL] [varchar] (32) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WEBSBUY11RECORD] ADD CONSTRAINT [PK__WEBSBUY11RECORD__669EC7A3] PRIMARY KEY CLUSTERED  ([SHOPCODE], [FLOWNO], [POSID], [ITEMNO]) ON [PRIMARY]
GO
