CREATE TABLE [dbo].[CTCNTRRATEGOODS]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VERSION] [smallint] NOT NULL,
[LINE] [smallint] NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[GDGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CTCNTRRATEGOODS] ADD CONSTRAINT [PK__CTCNTRRATEGOODS__46C09A36] PRIMARY KEY CLUSTERED  ([NUM], [VERSION], [LINE], [ITEMNO]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IDX_CTCNTRGOODS_GDGID] ON [dbo].[CTCNTRRATEGOODS] ([NUM], [VERSION], [LINE], [GDGID]) ON [PRIMARY]
GO
