CREATE TABLE [dbo].[IPA2INVDTL]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SUBWRH] [int] NOT NULL,
[LINE] [smallint] NOT NULL,
[STORE] [int] NOT NULL,
[WRH] [int] NOT NULL,
[QTY] [money] NOT NULL,
[COST] [money] NOT NULL,
[ADJCOST] [money] NOT NULL,
[LACTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IPA2INVDTL] ADD CONSTRAINT [PK__IPA2INVDTL__72B2945F] PRIMARY KEY CLUSTERED  ([CLS], [NUM], [SUBWRH], [LINE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IPA2INVDTL] ADD CONSTRAINT [UQ__IPA2INVDTL__73A6B898] UNIQUE NONCLUSTERED  ([SUBWRH], [WRH], [STORE], [CLS], [NUM]) ON [PRIMARY]
GO
