CREATE TABLE [dbo].[ALCGFTAGMGFTDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GFTLINE] [int] NOT NULL,
[GFTGID] [int] NOT NULL,
[GFTQTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__ALCGFTAGM__GFTQT__161E2E32] DEFAULT (0),
[GFTWRH] [int] NOT NULL CONSTRAINT [DF__ALCGFTAGM__GFTWR__1712526B] DEFAULT (0),
[GFTLMTQTY] [decimal] (24, 2) NULL,
[GFTNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ALCGFTAGMGFTDTL] ADD CONSTRAINT [PK__ALCGFTAGMGFTDTL__180676A4] PRIMARY KEY CLUSTERED  ([NUM], [GFTLINE]) ON [PRIMARY]
GO
