CREATE TABLE [dbo].[PS3SPECGDSCOREINVSPECDIS]
(
[UUID] [varchar] (36) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARDTYPECODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARDTYPENAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DISCOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3SPECGD__DISCO__12477460] DEFAULT (0),
[SRCNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PS3SPECGD__SRCNU__133B9899] DEFAULT ('-'),
[SRCCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PS3SPECGD__SRCCL__142FBCD2] DEFAULT ('-')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3SPECGDSCOREINVSPECDIS] ADD CONSTRAINT [PK__PS3SPECGDSCOREIN__1523E10B] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
