CREATE TABLE [dbo].[PAYRATEPRMDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SETTLENO] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[QPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PAYRATEPRMD__QPC__7686529F] DEFAULT (1),
[QPCSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PAYRATEPR__QPCST__777A76D8] DEFAULT ('1*1'),
[ASTART] [datetime] NOT NULL CONSTRAINT [DF__PAYRATEPR__ASTAR__786E9B11] DEFAULT (getdate()),
[AFINISH] [datetime] NOT NULL CONSTRAINT [DF__PAYRATEPR__AFINI__7962BF4A] DEFAULT ('9999.12.31 23:59:59'),
[PAYRATE] [decimal] (24, 4) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAYRATEPRMDTL] ADD CONSTRAINT [PK__PAYRATEPRMDTL__7A56E383] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
