CREATE TABLE [dbo].[STOREBUY1]
(
[STOREGID] [int] NOT NULL,
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__STOREBUY1__FILDA__0C1D60A7] DEFAULT (getdate()),
[CASHIER] [int] NOT NULL CONSTRAINT [DF__STOREBUY1__CASHI__0D1184E0] DEFAULT (1),
[WRH] [int] NOT NULL CONSTRAINT [DF__STOREBUY1__WRH__0E05A919] DEFAULT (1),
[ASSISTANT] [int] NULL,
[TOTAL] [money] NOT NULL CONSTRAINT [DF__STOREBUY1__TOTAL__0EF9CD52] DEFAULT (0),
[REALAMT] [money] NOT NULL CONSTRAINT [DF__STOREBUY1__REALA__0FEDF18B] DEFAULT (0),
[PREVAMT] [money] NOT NULL CONSTRAINT [DF__STOREBUY1__PREVA__10E215C4] DEFAULT (0),
[GUEST] [int] NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__STOREBUY1__RECCN__11D639FD] DEFAULT (0),
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[TAG] [smallint] NOT NULL CONSTRAINT [DF__STOREBUY1__TAG__12CA5E36] DEFAULT (0),
[INVNO] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SCORE] [money] NULL,
[CARDCODE] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[DEALER] [int] NULL,
[FLAG] [int] NOT NULL CONSTRAINT [DF__STOREBUY1__FLAG__6C12E5CD] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STOREBUY1] ADD CONSTRAINT [PK__STOREBUY1__0B293C6E] PRIMARY KEY CLUSTERED  ([STOREGID], [POSNO], [FLOWNO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FILDATE] ON [dbo].[STOREBUY1] ([FILDATE]) ON [PRIMARY]
GO
