CREATE TABLE [dbo].[NPS3REDBLUECARD]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__NPS3REDBLU__STAT__0F9CE483] DEFAULT (0),
[SRC] [int] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[ID] [int] NOT NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[FRCCHK] [smallint] NOT NULL,
[NTYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [char] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NPS3REDBL__FILDA__109108BC] DEFAULT (getdate()),
[FILLER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NPS3REDBL__FILLE__11852CF5] DEFAULT ('未知[-]'),
[CHECKER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[VENDOR] [int] NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__NPS3REDBL__LSTUP__1279512E] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPS3REDBLUECARD] ADD CONSTRAINT [PK__NPS3REDBLUECARD__136D7567] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPRCPRM_TYPE] ON [dbo].[NPS3REDBLUECARD] ([NTYPE]) ON [PRIMARY]
GO
