CREATE TABLE [dbo].[STOREORDQTYPOOL]
(
[STOREGID] [int] NOT NULL,
[WRH] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[ORDQTY] [money] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STOREORDQTYPOOL] ADD CONSTRAINT [PK__STOREORDQTYPOOL__417B2B7E] PRIMARY KEY CLUSTERED  ([STOREGID], [WRH], [GDGID]) ON [PRIMARY]
GO
