CREATE TABLE [dbo].[GFTPRMLACDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GFTPRMLACDTL] ADD CONSTRAINT [PK__GFTPRMLACDTL__566C26C3] PRIMARY KEY CLUSTERED  ([NUM], [STOREGID]) ON [PRIMARY]
GO
