CREATE TABLE [dbo].[GDXLATE]
(
[NGID] [int] NOT NULL,
[LGID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GDXLATE] ADD CONSTRAINT [PK__GDXLATE__64CCF2AE] PRIMARY KEY CLUSTERED  ([NGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
