CREATE TABLE [dbo].[CUSTOMERORDERBUY11]
(
[FLOWNO] [char] (16) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[CURRENCY] [smallint] NOT NULL CONSTRAINT [DF__CUSTOMERO__CURRE__23BCE47C] DEFAULT (0),
[AMOUNT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CUSTOMERO__AMOUN__24B108B5] DEFAULT (0),
[SENT] [varchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[CARDCODE] [varchar] (128) COLLATE Chinese_PRC_CI_AS NULL,
[FAVTYPE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NULL,
[FAVAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CUSTOMERO__FAVAM__25A52CEE] DEFAULT (0),
[PARVALUE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CUSTOMERO__PARVA__26995127] DEFAULT (0),
[CURRENCYTYPE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[ORIGINALAMT] [decimal] (24, 4) NULL,
[PARITIES] [decimal] (24, 4) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUSTOMERORDERBUY11] ADD CONSTRAINT [PK__CustomerOrderBUY__278D7560] PRIMARY KEY CLUSTERED  ([FLOWNO], [POSNO], [ITEMNO]) ON [PRIMARY]
GO
