CREATE TABLE [dbo].[NCTCNTRRATESTOREGD]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VERSION] [smallint] NOT NULL,
[LINE] [smallint] NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[STORESCOPE] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDSCOPESQL] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[GDSCOPETEXT] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCTCNTRRATESTOREGD] ADD CONSTRAINT [PK__NCTCNTRRATESTORE__3C456DC8] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE], [ITEMNO]) ON [PRIMARY]
GO
