CREATE TABLE [dbo].[PS3SPECGDSCOREDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[MINAMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3SPECGD__MINAM__4B694C75] DEFAULT (0),
[AMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3SPECGD__AMOUN__4C5D70AE] DEFAULT (0),
[SCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3SPECGD__SCORE__4D5194E7] DEFAULT (0),
[MAXDISCOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3SPECGD__MAXDI__4E45B920] DEFAULT (100),
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SCORESORT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PS3SPECGD__SCORE__023A5E72] DEFAULT ('-'),
[NSCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3SPECGD__NSCOR__2C30983E] DEFAULT (1),
[DISCOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3SPECGD__DISCO__69455ECD] DEFAULT (0),
[DISMAXDIS] [decimal] (24, 2) NULL,
[DISPREC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PS3SPECGD__DISPR__6A398306] DEFAULT (0.01)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3SPECGDSCOREDTL] ADD CONSTRAINT [PK__PS3SPECGDSCOREDT__4F39DD59] PRIMARY KEY CLUSTERED  ([NUM], [CLS], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3SPECGDSCOREDTL_1] ON [dbo].[PS3SPECGDSCOREDTL] ([GDGID]) ON [PRIMARY]
GO
