CREATE TABLE [dbo].[NINPRCADJINVDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[LINE] [smallint] NOT NULL,
[STORE] [int] NOT NULL,
[QTY] [money] NOT NULL,
[COST] [money] NOT NULL,
[ADJCOST] [money] NOT NULL,
[LACTIME] [datetime] NOT NULL CONSTRAINT [DF__NINPRCADJ__LACTI__0FCEC151] DEFAULT (getdate()),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NINPRCADJINVDTL] ADD CONSTRAINT [PK__NINPRCADJINVDTL__320C68B7] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
