CREATE TABLE [dbo].[VDRGD]
(
[VDRGID] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[WRH] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VDRGD] ADD CONSTRAINT [PK__VDRGD__379037E3] PRIMARY KEY CLUSTERED  ([GDGID], [VDRGID], [WRH]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [GDGID] ON [dbo].[VDRGD] ([GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
