CREATE TABLE [dbo].[BUYRTNCONTROL]
(
[BCKPOSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BCKFLOWNO] [varchar] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BCKITEMNO] [int] NULL CONSTRAINT [DF__BUYRTNCON__BCKIT__4A6019A3] DEFAULT (0),
[ORIPOSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ORIFLOWNO] [varchar] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ORIITEMNO] [int] NOT NULL,
[BCKQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__BUYRTNCON__BCKQT__4B543DDC] DEFAULT (0),
[RGUID] [varchar] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__BUYRTNCONT__STAT__4C486215] DEFAULT (0),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__BUYRTNCON__LSTUP__4D3C864E] DEFAULT (getdate())
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_BUYRTNCONTROL_OSA] ON [dbo].[BUYRTNCONTROL] ([ORIPOSNO], [ORIFLOWNO], [ORIITEMNO], [STAT]) ON [PRIMARY]
GO
