CREATE TABLE [dbo].[POSKEYDEF]
(
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SCANCODE] [smallint] NOT NULL,
[FUNCTION] [smallint] NOT NULL,
[GOODSCODE] [char] (13) COLLATE Chinese_PRC_CI_AS NULL,
[ALEFT] [smallint] NOT NULL,
[TOP] [smallint] NOT NULL,
[WIDTH] [smallint] NOT NULL,
[HEIGHT] [smallint] NOT NULL,
[DEVICEINDEX] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[POSKEYDEF] ADD CONSTRAINT [PK__POSKEYDEF__71F1E3A2] PRIMARY KEY CLUSTERED  ([POSNO], [SCANCODE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
