CREATE TABLE [dbo].[OSBAL]
(
[STORE] [int] NOT NULL,
[SETTLENO] [int] NOT NULL,
[DATE] [datetime] NOT NULL,
[VDRGID] [int] NOT NULL,
[WRH] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[QTY] [money] NOT NULL CONSTRAINT [DF__OSBAL__QTY__6B85A88C] DEFAULT (0),
[DT1] [money] NOT NULL CONSTRAINT [DF__OSBAL__DT1__6C79CCC5] DEFAULT (0),
[DT2] [money] NOT NULL CONSTRAINT [DF__OSBAL__DT2__6D6DF0FE] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OSBAL] ADD CONSTRAINT [PK__OSBAL__6A918453] PRIMARY KEY CLUSTERED  ([STORE], [SETTLENO], [DATE], [VDRGID], [WRH], [GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
