CREATE TABLE [dbo].[FAFLOWLINEFONT]
(
[UUID] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [int] NOT NULL,
[FHEIGHT] [int] NOT NULL,
[FCOLOR] [int] NOT NULL,
[FPITCH] [int] NOT NULL,
[FSTYLE] [int] NOT NULL,
[FCHARSET] [int] NOT NULL,
[FFTNAME] [varchar] (120) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FAFLOWLINEFONT] ADD CONSTRAINT [PK__FAFLOWLINEFONT__33103DF2] PRIMARY KEY CLUSTERED  ([UUID], [ITEMNO]) ON [PRIMARY]
GO
