CREATE TABLE [dbo].[THDUpdhst]
(
[FID] [int] NOT NULL IDENTITY(1, 1),
[FVersionNo] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FType] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FFileName] [char] (255) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FFlag] [int] NOT NULL CONSTRAINT [DF__THDUpdhst__FFlag__186EF44A] DEFAULT (0),
[FINSERTDATETIME] [datetime] NOT NULL CONSTRAINT [DF__THDUpdhst__FINSE__19631883] DEFAULT (getdate()),
[FUPDATEDATETIME] [datetime] NULL,
[FEXECTIME] [datetime] NULL,
[FSENDDATETIME] [datetime] NULL,
[FTM] [timestamp] NOT NULL,
[FNote] [varchar] (1000) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__THDUpdhst__FNote__1A573CBC] DEFAULT ('')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[THDUpdhst] ADD CONSTRAINT [PK__THDUpdhst__177AD011] PRIMARY KEY CLUSTERED  ([FID]) ON [PRIMARY]
GO
