CREATE TABLE [dbo].[TMPALCGFT]
(
[SPID] [int] NOT NULL,
[SRCNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GFTVAlUE] [decimal] (24, 2) NULL,
[GFTRNT] [decimal] (24, 2) NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_TMPALCGFT_SPID] ON [dbo].[TMPALCGFT] ([SPID]) ON [PRIMARY]
GO
