CREATE TABLE [dbo].[CARDTYPE]
(
[NAME] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARDTYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CARDTYPE__CARDTY__3608AD7B] DEFAULT ('折扣卡'),
[DISCOUNT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CARDTYPE__DISCOU__36FCD1B4] DEFAULT (100),
[PARVALUE] [decimal] (24, 2) NULL,
[CARDCOST] [decimal] (24, 4) NULL,
[CARDUSAGE] [smallint] NOT NULL CONSTRAINT [DF__CARDTYPE__CARDUS__37F0F5ED] DEFAULT (0),
[MEDIUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MSPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CARDTYPE__MSPRC__38E51A26] DEFAULT (0),
[VSPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CARDTYPE__VSPRC__39D93E5F] DEFAULT (0),
[MPPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CARDTYPE__MPPRC__3ACD6298] DEFAULT (0),
[VPPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CARDTYPE__VPPRC__3BC186D1] DEFAULT (0),
[MCPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CARDTYPE__MCPRC__3CB5AB0A] DEFAULT (0),
[VCPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CARDTYPE__VCPRC__3DA9CF43] DEFAULT (0),
[VALIDPRD] [int] NULL,
[ABORTPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CARDTYPE__ABORTP__3E9DF37C] DEFAULT (0),
[BACKPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CARDTYPE__BACKPR__3F9217B5] DEFAULT (0),
[RESUMEPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CARDTYPE__RESUME__40863BEE] DEFAULT (0),
[TRANRATE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CARDTYPE__TRANRA__417A6027] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CARDTYPE] ADD CONSTRAINT [PK__CARDTYPE__35148942] PRIMARY KEY CLUSTERED  ([NAME]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
