CREATE TABLE [dbo].[PREBUY11]
(
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[SETTLENO] [int] NOT NULL,
[CURRENCY] [smallint] NOT NULL CONSTRAINT [DF__PREBUY11__CURREN__390B706F] DEFAULT (0),
[AMOUNT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PREBUY11__AMOUNT__39FF94A8] DEFAULT (0),
[TAG] [smallint] NOT NULL CONSTRAINT [DF__PREBUY11__TAG__3AF3B8E1] DEFAULT (0),
[CARDCODE] [varchar] (128) COLLATE Chinese_PRC_CI_AS NULL,
[FAVTYPE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NULL,
[FAVAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PREBUY11__FAVAMT__3BE7DD1A] DEFAULT (0),
[PARVALUE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PREBUY11__PARVAL__3CDC0153] DEFAULT (0),
[CURRENCYTYPE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[ORIGINALAMT] [decimal] (24, 4) NULL,
[PARITIES] [decimal] (24, 4) NULL,
[LSTUPDTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PREBUY11] ADD CONSTRAINT [PK__PREBUY11__3DD0258C] PRIMARY KEY CLUSTERED  ([FLOWNO], [POSNO], [ITEMNO]) ON [PRIMARY]
GO
