CREATE TABLE [dbo].[VDRPAYBYSALEINV]
(
[VENDOR] [int] NOT NULL,
[BEGINDATE] [datetime] NULL,
[ENDDATE] [datetime] NULL,
[SRCNUM] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PAYNUM] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SRCCLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OCCUPYSALEAMT] [decimal] (24, 2) NULL CONSTRAINT [DF__VDRPAYBYS__OCCUP__78772604] DEFAULT (0),
[RELEASESALEAMT] [decimal] (24, 2) NULL CONSTRAINT [DF__VDRPAYBYS__RELEA__796B4A3D] DEFAULT (0),
[GENDATE] [datetime] NULL,
[GENOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[STAT] [int] NOT NULL CONSTRAINT [DF__VDRPAYBYSA__STAT__7A5F6E76] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[BILLSRC] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VDRPAYBYSALEINV] ADD CONSTRAINT [PK__VDRPAYBYSALEINV__778301CB] PRIMARY KEY CLUSTERED  ([SRCNUM], [SRCCLS]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_VDRPAYBYSALEINV_VENDOR] ON [dbo].[VDRPAYBYSALEINV] ([VENDOR]) ON [PRIMARY]
GO
