CREATE TABLE [dbo].[CstMizeDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[GQTY] [money] NOT NULL,
[QTY] [money] NOT NULL,
[PRICE] [money] NOT NULL,
[GTOTAL] [money] NOT NULL,
[TOTAL] [money] NOT NULL,
[TAX] [money] NOT NULL,
[WRH] [int] NOT NULL CONSTRAINT [DF__CstMizeDTL__WRH__6796B2C5] DEFAULT (1),
[INPRC] [money] NOT NULL,
[RTLPRC] [money] NOT NULL,
[SUBWRH] [int] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CstMizeDTL] ADD CONSTRAINT [PK__CstMizeDTL__3AD6B8E2] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [CstMizedtl_gdgid] ON [dbo].[CstMizeDTL] ([GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CstMizeDTL] ADD CONSTRAINT [在定制单中商品不能重复] UNIQUE NONCLUSTERED  ([NUM], [GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
