CREATE TABLE [dbo].[CRMCARDSCODTL]
(
[CARDNUM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCARDSC__SCORE__79AC0CB6] DEFAULT (0),
[SCRTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCARDSC__SCRTO__7AA030EF] DEFAULT (0),
[ADJSCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCARDSC__ADJSC__7B945528] DEFAULT (0),
[ADJSCORETIME] [datetime] NULL,
[LSTUPDTIME] [datetime] NULL CONSTRAINT [DF__CRMCARDSC__LSTUP__7C887961] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMCARDSCODTL] ADD CONSTRAINT [PK__CRMCARDSCODTL__7D7C9D9A] PRIMARY KEY CLUSTERED  ([CARDNUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_CRMCARDSCODTL_LST] ON [dbo].[CRMCARDSCODTL] ([LSTUPDTIME]) ON [PRIMARY]
GO
