CREATE TABLE [dbo].[PS3STAMPSCORULE]
(
[UUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3STAMPS__TOTAL__233C2AE1] DEFAULT (0),
[SCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3STAMPS__SCORE__24304F1A] DEFAULT (0),
[SCOTOP] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3STAMPS__SCOTO__25247353] DEFAULT (0),
[BEGINDATE] [datetime] NOT NULL CONSTRAINT [DF__PS3STAMPS__BEGIN__2618978C] DEFAULT (getdate()),
[ENDDATE] [datetime] NOT NULL CONSTRAINT [DF__PS3STAMPS__ENDDA__270CBBC5] DEFAULT (getdate()),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[OPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OPERTIME] [datetime] NOT NULL CONSTRAINT [DF__PS3STAMPS__OPERT__2800DFFE] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3STAMPSCORULE] ADD CONSTRAINT [PK__PS3STAMPSCORULE__28F50437] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
