CREATE TABLE [dbo].[PSSUMCONSUMEDTL]
(
[CARDNUM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARRIER] [int] NOT NULL,
[SORT] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CONSUME] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PSSUMCONS__CONSU__1029566D] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSSUMCONSUMEDTL] ADD CONSTRAINT [PK__PSSUMCONSUMEDTL__111D7AA6] PRIMARY KEY CLUSTERED  ([CARDNUM], [CARRIER], [SORT]) ON [PRIMARY]
GO
