CREATE TABLE [dbo].[PSSUMGDDTL]
(
[UUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SORT] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSSUMGDDTL] ADD CONSTRAINT [PK__PSSUMGDDTL__0794106C] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PSSUMGDDTL_SORT] ON [dbo].[PSSUMGDDTL] ([SORT]) ON [PRIMARY]
GO
