CREATE TABLE [dbo].[StoreBILL]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[OPNCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__StoreBILL__OPNCO__324D2B30] DEFAULT (''),
[GDGID] [int] NOT NULL,
[QTY] [money] NOT NULL CONSTRAINT [DF__StoreBILL__QTY__33414F69] DEFAULT (0),
[PRICE] [money] NOT NULL CONSTRAINT [DF__StoreBILL__PRICE__343573A2] DEFAULT (0),
[TOTAL] [money] NOT NULL CONSTRAINT [DF__StoreBILL__TOTAL__352997DB] DEFAULT (0),
[FILDATE] [datetime] NULL,
[OCRDATE] [datetime] NULL,
[FILLER] [int] NOT NULL CONSTRAINT [DF__StoreBILL__FILLE__361DBC14] DEFAULT (1),
[ORDNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__StoreBILL__ORDNU__3711E04D] DEFAULT (''),
[VendorNum] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__StoreBILL__Vendo__38060486] DEFAULT (''),
[ALCTIME] [datetime] NULL,
[ToCls] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__StoreBILL__ToCls__38FA28BF] DEFAULT (''),
[ToNum] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__StoreBILL__ToNum__39EE4CF8] DEFAULT (''),
[NOTE] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__StoreBILL__NOTE__3AE27131] DEFAULT ('')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[StoreBILL] ADD CONSTRAINT [PK__StoreBILL__6D7C0B52] PRIMARY KEY CLUSTERED  ([CLS], [POSNO], [NUM], [LINE], [GDGID]) ON [PRIMARY]
GO
