CREATE TABLE [dbo].[NPRMOFFSETDRPT]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[GDGID] [int] NOT NULL,
[VDRGID] [int] NOT NULL,
[CNTINPRC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPRMOFFSE__CNTIN__29B352EF] DEFAULT (0),
[OFFSETPRC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPRMOFFSE__OFFSE__2AA77728] DEFAULT (0),
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPRMOFFSETD__QTY__2B9B9B61] DEFAULT (0),
[OFFSETAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPRMOFFSE__OFFSE__2C8FBF9A] DEFAULT (0),
[NSTAT] [int] NOT NULL CONSTRAINT [DF__NPRMOFFSE__NSTAT__2D83E3D3] DEFAULT (0),
[NNOTE] [varchar] (256) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[RCV] [int] NOT NULL,
[SNDTIME] [datetime] NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [int] NOT NULL CONSTRAINT [DF__NPRMOFFSET__TYPE__2E78080C] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPRMOFFSETDRPT] ADD CONSTRAINT [PK__NPRMOFFSETDRPT__2F6C2C45] PRIMARY KEY CLUSTERED  ([ASTORE], [ASETTLENO], [ADATE], [GDGID], [VDRGID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PRMOFFSETDRPT] ON [dbo].[NPRMOFFSETDRPT] ([ADATE], [GDGID], [VDRGID]) ON [PRIMARY]
GO
