CREATE TABLE [dbo].[PSUPOWERNOTIFICATIONLOG]
(
[ID] [varchar] (60) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__PSUPOWERN__FILDA__7D58DB20] DEFAULT (getdate()),
[REMARK] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSUPOWERNOTIFICATIONLOG] ADD CONSTRAINT [PK__PSUPOWERNOTIFICA__7E4CFF59] PRIMARY KEY CLUSTERED  ([ID], [FILDATE]) ON [PRIMARY]
GO
