CREATE TABLE [dbo].[TA_FIELDDEFINE]
(
[FIELDDEFINEID] [int] NOT NULL,
[OPERATIONID] [int] NOT NULL,
[SERIALNO] [int] NOT NULL,
[CHNAME] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TA_FIELDDEFINE] ADD CONSTRAINT [PK__TA_FIELDDEFINE__2B2A60FE] PRIMARY KEY CLUSTERED  ([FIELDDEFINEID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
