CREATE TABLE [dbo].[NSTKOUTDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NULL,
[CASES] [money] NULL,
[QTY] [money] NULL,
[PRICE] [money] NULL,
[TOTAL] [money] NULL,
[TAX] [money] NULL,
[VALIDDATE] [datetime] NULL,
[WRH] [int] NULL CONSTRAINT [DF__NSTKOUTDTL__WRH__7E188EBC] DEFAULT (1),
[SUBWRH] [int] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[COST] [money] NOT NULL CONSTRAINT [DF__NSTKOUTDTL__COST__60C8EE4E] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NSTKOUTDTL] ADD CONSTRAINT [PK__NSTKOUTDTL__51851410] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
