CREATE TABLE [dbo].[CRMMODIFYCARD]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__CRMMODIFYC__STAT__50B418C4] DEFAULT (0),
[MODIFYMODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STORE] [int] NOT NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__CRMMODIFY__FILDA__51A83CFD] DEFAULT (getdate()),
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__CRMMODIFY__LSTUP__529C6136] DEFAULT (getdate()),
[PRNTIME] [datetime] NULL,
[SRC] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMMODIFYCARD] ADD CONSTRAINT [PK__CRMMODIFYCARD__5390856F] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
