CREATE TABLE [dbo].[NCNTRPAYCASHDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[CHGTYPE] [char] (16) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRCNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[IVCNUM] [char] (16) COLLATE Chinese_PRC_CI_AS NULL,
[IVCCODE] [char] (16) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TOTALBAL] [decimal] (24, 2) NOT NULL,
[IVCAMT] [decimal] (24, 2) NOT NULL,
[IVCPAY] [decimal] (24, 2) NOT NULL,
[PAYTOTAL] [decimal] (24, 2) NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL CONSTRAINT [DF__NCNTRPAYCAS__SRC__2DBFE242] DEFAULT (1),
[GROUPID] [int] NOT NULL,
[NO] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCNTRPAYCASHDTL] ADD CONSTRAINT [PK__NCNTRPAYCASHDTL__2EB4067B] PRIMARY KEY CLUSTERED  ([SRC], [GROUPID], [NO], [LINE]) ON [PRIMARY]
GO
