CREATE TABLE [dbo].[WEATHER]
(
[NO] [int] NOT NULL,
[WEATHER] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WEATHER] ADD CONSTRAINT [PK__WEATHER__628CA8EF] PRIMARY KEY CLUSTERED  ([NO]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [UQ_WEATHER] ON [dbo].[WEATHER] ([WEATHER]) ON [PRIMARY]
GO
