CREATE TABLE [dbo].[IPA2]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[VENDOR] [int] NULL,
[CLIENT] [int] NULL,
[ADJCOST] [money] NOT NULL CONSTRAINT [DF__IPA2__ADJCOST__58F2C25C] DEFAULT (0),
[ADJINCOST] [money] NOT NULL CONSTRAINT [DF__IPA2__ADJINCOST__59E6E695] DEFAULT (0),
[ADJINVCOST] [money] NOT NULL CONSTRAINT [DF__IPA2__ADJINVCOST__5ADB0ACE] DEFAULT (0),
[ADJOUTCOST] [money] NOT NULL CONSTRAINT [DF__IPA2__ADJOUTCOST__5BCF2F07] DEFAULT (0),
[ADJALCAMT] [money] NOT NULL CONSTRAINT [DF__IPA2__ADJALCAMT__5CC35340] DEFAULT (0),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__IPA2__FILDATE__5DB77779] DEFAULT (getdate()),
[FILLER] [int] NOT NULL CONSTRAINT [DF__IPA2__FILLER__5EAB9BB2] DEFAULT (1),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__IPA2__STAT__5F9FBFEB] DEFAULT (0),
[LAUNCH] [smallint] NOT NULL CONSTRAINT [DF__IPA2__LAUNCH__6093E424] DEFAULT (0),
[CHECKER] [int] NULL,
[CHKDATE] [datetime] NULL,
[VERIFIER] [int] NULL,
[VRFDATE] [datetime] NULL,
[SRC] [int] NOT NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[FINISHED] [smallint] NOT NULL CONSTRAINT [DF__IPA2__FINISHED__6188085D] DEFAULT (0),
[CAUSE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__IPA2__CAUSE__627C2C96] DEFAULT ('供应商返利'),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SEARCHINF] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IPA2] ADD CONSTRAINT [PK__IPA2__57FE9E23] PRIMARY KEY CLUSTERED  ([CLS], [NUM]) ON [PRIMARY]
GO
