CREATE TABLE [dbo].[VOUCHERSELL]
(
[NUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__VOUCHERSEL__STAT__4D869F11] DEFAULT (0),
[FROMSTORE] [int] NOT NULL,
[SALESMAN] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[AMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__VOUCHERSE__AMOUN__4E7AC34A] DEFAULT (0),
[SELLAMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__VOUCHERSE__SELLA__4F6EE783] DEFAULT (0),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__VOUCHERSE__FILDA__50630BBC] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__VOUCHERSE__FILLE__51572FF5] DEFAULT ('未知[-]'),
[CHKDATE] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NULL,
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PRNTIME] [datetime] NULL,
[VOUCHERTYPE] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERSELL] ADD CONSTRAINT [PK__VOUCHERSELL__524B542E] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_VOUCHERSELL_NUM] ON [dbo].[VOUCHERSELL] ([NUM]) ON [PRIMARY]
GO
