CREATE TABLE [dbo].[FASECURITYSTYLOG]
(
[GID] [int] NOT NULL,
[CODE] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (255) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ENGNAME] [char] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SHORTCHNNAME] [char] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SHORTENGNAME] [char] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__FASECURIT__FILDA__43DF9B4B] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__FASECURIT__LSTUP__44D3BF84] DEFAULT (getdate()),
[LASTMODIFYOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [char] (255) COLLATE Chinese_PRC_CI_AS NULL,
[PWDMINLENGTH] [smallint] NOT NULL CONSTRAINT [DF__FASECURIT__PWDMI__45C7E3BD] DEFAULT (0),
[FIRSTLOGMSG] [smallint] NOT NULL CONSTRAINT [DF__FASECURIT__FIRST__46BC07F6] DEFAULT (0),
[PWDERRTIMES] [smallint] NOT NULL CONSTRAINT [DF__FASECURIT__PWDER__47B02C2F] DEFAULT (3),
[PWDNEVERLOSE] [smallint] NOT NULL CONSTRAINT [DF__FASECURIT__PWDNE__48A45068] DEFAULT (0),
[PWDEXPIRYDAY] [smallint] NOT NULL CONSTRAINT [DF__FASECURIT__PWDEX__499874A1] DEFAULT (0),
[PWDEXPIRYPROMPTDAY] [smallint] NOT NULL CONSTRAINT [DF__FASECURIT__PWDEX__4A8C98DA] DEFAULT (0),
[PWDREUSELMT] [smallint] NOT NULL CONSTRAINT [DF__FASECURIT__PWDRE__4B80BD13] DEFAULT (0),
[PWDLEVEL] [smallint] NOT NULL CONSTRAINT [DF__FASECURIT__PWDLE__4C74E14C] DEFAULT (0),
[BDATE] [datetime] NOT NULL CONSTRAINT [DF__FASECURIT__BDATE__4D690585] DEFAULT (getdate()),
[EDATE] [datetime] NOT NULL CONSTRAINT [DF__FASECURIT__EDATE__4E5D29BE] DEFAULT (getdate()),
[NO] [int] NULL,
[NOLSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__FASECURIT__NOLST__4F514DF7] DEFAULT (getdate()),
[NOLASTMODIFYOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[PWDSAMEPWDLNAME] [smallint] NOT NULL CONSTRAINT [DF__FASECURIT__PWDSA__50457230] DEFAULT (0),
[PWDDUPLIMIT] [smallint] NOT NULL CONSTRAINT [DF__FASECURIT__PWDDU__51399669] DEFAULT (0),
[PWDDEGREE] [smallint] NOT NULL CONSTRAINT [DF__FASECURIT__PWDDE__522DBAA2] DEFAULT (0)
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_FASECURITYSTYLOG_BE] ON [dbo].[FASECURITYSTYLOG] ([BDATE], [EDATE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_FASECURITYSTYLOG_G] ON [dbo].[FASECURITYSTYLOG] ([GID]) ON [PRIMARY]
GO
