CREATE TABLE [dbo].[NPS3STAMPSCORULE]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[CLS] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[UUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NPS3STAMP__TOTAL__2DB9B954] DEFAULT (0),
[SCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NPS3STAMP__SCORE__2EADDD8D] DEFAULT (0),
[SCOTOP] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NPS3STAMP__SCOTO__2FA201C6] DEFAULT (0),
[BEGINDATE] [datetime] NOT NULL CONSTRAINT [DF__NPS3STAMP__BEGIN__309625FF] DEFAULT (getdate()),
[ENDDATE] [datetime] NOT NULL CONSTRAINT [DF__NPS3STAMP__ENDDA__318A4A38] DEFAULT (getdate()),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[OPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OPERTIME] [datetime] NOT NULL CONSTRAINT [DF__NPS3STAMP__OPERT__327E6E71] DEFAULT (getdate()),
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPS3STAMPSCORULE] ADD CONSTRAINT [PK__NPS3STAMPSCORULE__337292AA] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
