CREATE TABLE [dbo].[POLYPROMQTYSCHMDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[LOWQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__POLYPROMQ__LOWQT__5D33C24C] DEFAULT (0),
[HIGHQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__POLYPROMQ__HIGHQ__5E27E685] DEFAULT (99999999),
[DISCOUNT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__POLYPROMQ__DISCO__5F1C0ABE] DEFAULT (0),
[FAVAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__POLYPROMQ__FAVAM__60102EF7] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[POLYPROMQTYSCHMDTL] ADD CONSTRAINT [PK__POLYPROMQTYSCHMD__61045330] PRIMARY KEY CLUSTERED  ([NUM], [CLS], [LINE]) ON [PRIMARY]
GO
