CREATE TABLE [dbo].[NGFTAGM]
(
[ID] [int] NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[VENDOR] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NGFTAGM__FILDATE__0604949E] DEFAULT (getdate()),
[FILLER] [int] NOT NULL CONSTRAINT [DF__NGFTAGM__FILLER__06F8B8D7] DEFAULT (1),
[CHECKER] [int] NOT NULL CONSTRAINT [DF__NGFTAGM__CHECKER__07ECDD10] DEFAULT (1),
[RECCNT] [int] NOT NULL CONSTRAINT [DF__NGFTAGM__RECCNT__08E10149] DEFAULT (0),
[NSTAT] [smallint] NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL CONSTRAINT [DF__NGFTAGM__SRC__09D52582] DEFAULT (1),
[SNDTIME] [datetime] NULL,
[RCV] [int] NULL,
[RCVTIME] [datetime] NULL,
[FRCCHK] [smallint] NOT NULL,
[TYPE] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NGFTAGM] ADD CONSTRAINT [PK__NGFTAGM__05107065] PRIMARY KEY CLUSTERED  ([SRC], [ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
