CREATE TABLE [dbo].[POSPRNMODULE]
(
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MODULE] [smallint] NOT NULL,
[LINE] [smallint] NOT NULL,
[BLOCK] [smallint] NOT NULL,
[ALEFT] [smallint] NOT NULL,
[WIDTH] [smallint] NOT NULL,
[ALIGNMENT] [char] (1) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FONTSIZE] [smallint] NOT NULL,
[COLOR] [smallint] NOT NULL,
[EOL] [smallint] NOT NULL,
[CONTENT] [smallint] NOT NULL,
[FIXEDSTRING] [char] (255) COLLATE Chinese_PRC_CI_AS NULL,
[MODULESETCODE] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[POSPRNMODULE] ADD CONSTRAINT [PK__POSPRNMODULE__72E607DB] PRIMARY KEY CLUSTERED  ([POSNO], [MODULE], [LINE], [BLOCK]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
