CREATE TABLE [dbo].[VOUCHERLAUNCHSCOPETEMPLATEGOODS]
(
[CODE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[SCOPECODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[FLAG] [smallint] NOT NULL,
[SCOPECODE2] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[FLAG2] [smallint] NOT NULL CONSTRAINT [DF__VOUCHERLA__FLAG2__2A078D53] DEFAULT (0),
[GDGID] [int] NOT NULL CONSTRAINT [DF__VOUCHERLA__GDGID__3ECDA00F] DEFAULT ((-1))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERLAUNCHSCOPETEMPLATEGOODS] ADD CONSTRAINT [PK__VOUCHERLAUNCHSCO__44867965] PRIMARY KEY CLUSTERED  ([CODE], [LINE], [GDGID]) ON [PRIMARY]
GO
