CREATE TABLE [dbo].[SORTEMP]
(
[EMPGID] [int] NOT NULL,
[SORTCODE] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SORTEMP] ADD CONSTRAINT [PK__SORTEMP__372E14F5] PRIMARY KEY CLUSTERED  ([SORTCODE], [EMPGID]) ON [PRIMARY]
GO
