CREATE TABLE [dbo].[MEMBER]
(
[GID] [int] NOT NULL,
[CODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ADDRESS] [char] (50) COLLATE Chinese_PRC_CI_AS NULL,
[ZIP] [char] (6) COLLATE Chinese_PRC_CI_AS NULL,
[TELE] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[EMAILADR] [char] (50) COLLATE Chinese_PRC_CI_AS NULL,
[WWWADR] [char] (50) COLLATE Chinese_PRC_CI_AS NULL,
[CDTLMT] [decimal] (24, 2) NULL,
[IDCARD] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LASTTIME] [datetime] NULL,
[TOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__MEMBER__TOTAL__79BEB94A] DEFAULT (0),
[FAVAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__MEMBER__FAVAMT__7AB2DD83] DEFAULT (0),
[TLCNT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__MEMBER__TLCNT__7BA701BC] DEFAULT (0),
[TLGD] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__MEMBER__TLGD__7C9B25F5] DEFAULT (0),
[ADDR2] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[SEX] [smallint] NULL CONSTRAINT [DF__MEMBER__SEX__7D8F4A2E] DEFAULT (0),
[COMPANY] [char] (50) COLLATE Chinese_PRC_CI_AS NULL,
[BUSINESS] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[FAMILIES] [int] NULL,
[INCOME] [decimal] (24, 2) NULL,
[HOBBY] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[TRAFFIC] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[TRANSACTOR] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[WEDDINGDAY] [datetime] NULL,
[FAVCOLOR] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[OTHER] [char] (60) COLLATE Chinese_PRC_CI_AS NULL,
[MOBILEPHONE] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[BP] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[BALANCE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__MEMBER__BALANCE__7E836E67] DEFAULT (0),
[MAXOVERDRAFT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__MEMBER__MAXOVERD__7F7792A0] DEFAULT (0),
[DETAILLEVEL] [smallint] NOT NULL CONSTRAINT [DF__MEMBER__DETAILLE__006BB6D9] DEFAULT (0),
[CREDIT] [smallint] NOT NULL CONSTRAINT [DF__MEMBER__CREDIT__015FDB12] DEFAULT (0),
[MASTERCLN] [int] NULL,
[BACKBUYTOTAL] [decimal] (24, 2) NULL CONSTRAINT [DF__MEMBER__BACKBUYT__0253FF4B] DEFAULT (0),
[AGE] [int] NULL CONSTRAINT [DF__MEMBER__AGE__03482384] DEFAULT (0),
[CREATEDATE] [datetime] NOT NULL CONSTRAINT [DF__MEMBER__CREATEDA__043C47BD] DEFAULT (getdate()),
[MEMO] [varchar] (200) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL CONSTRAINT [DF__MEMBER__SRC__05306BF6] DEFAULT (1),
[SNDTIME] [datetime] NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__MEMBER__LSTUPDTI__0624902F] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__MEMBER__FILLER__0718B468] DEFAULT (1),
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__MEMBER__MODIFIER__080CD8A1] DEFAULT (1)
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

create trigger [dbo].[MEMBER_DLT] on [dbo].[MEMBER] for delete as
begin
  if exists(select 1 from deleted where GID = 1)
  begin
    raiserror('不能删除系统设定的会员: 未知[-]', 16, 1)
    return
  end
end
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

create trigger [dbo].[MEMBER_INS] on [dbo].[MEMBER] for insert as
begin
  insert into MEMBERH select * from inserted
end
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

create trigger [dbo].[MEMBER_UPD] on [dbo].[MEMBER] for update as
begin
  delete from MEMBERH from deleted where MEMBERH.GID = deleted.GID
  insert into MEMBERH select * from inserted
end
GO
ALTER TABLE [dbo].[MEMBER] ADD CONSTRAINT [PK__MEMBER__78CA9511] PRIMARY KEY CLUSTERED  ([GID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [mbr_code] ON [dbo].[MEMBER] ([CODE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
