CREATE TABLE [dbo].[PS3UNITESCORE]
(
[UUID] [varchar] (36) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MINAMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3UNITES__MINAM__01C55D26] DEFAULT (0),
[AMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3UNITES__AMOUN__02B9815F] DEFAULT (0),
[SCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3UNITES__SCORE__03ADA598] DEFAULT (0),
[MAXDISCOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3UNITES__MAXDI__04A1C9D1] DEFAULT (100),
[SCORESORT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PS3UNITES__SCORE__06FF138F] DEFAULT ('-')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3UNITESCORE] ADD CONSTRAINT [PK__PS3UNITESCORE__0595EE0A] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
