CREATE TABLE [dbo].[NGFTPRM]
(
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[BEGINTIME] [datetime] NOT NULL,
[ENDTIME] [datetime] NOT NULL,
[SRC] [int] NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__NGFTPRM__LSTUPDT__3927734D] DEFAULT (getdate()),
[NOTE] [text] COLLATE Chinese_PRC_CI_AS NULL,
[PRNTIME] [datetime] NULL,
[SETTLENO] [int] NOT NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__NGFTPRM__RECCNT__3A1B9786] DEFAULT (0),
[TOPIC] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NGFTPRM__TOPIC__3B0FBBBF] DEFAULT ('-'),
[NSTAT] [int] NOT NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[FRCCHK] [int] NOT NULL CONSTRAINT [DF__NGFTPRM__FRCCHK__5B7C8B51] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NGFTPRM] ADD CONSTRAINT [PK__NGFTPRM__3C03DFF8] PRIMARY KEY CLUSTERED  ([ID], [RCV]) ON [PRIMARY]
GO
