CREATE TABLE [dbo].[CHARGECHKDTL2DTL]
(
[NUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[DTLDTLLINE] [int] NOT NULL,
[DTLCLS] [smallint] NOT NULL,
[CODE] [varchar] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHKNO] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[TOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CHARGECHK__TOTAL__28338823] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CHARGECHKDTL2DTL] ADD CONSTRAINT [PK__CHARGECHKDTL2DTL__2927AC5C] PRIMARY KEY CLUSTERED  ([NUM], [LINE], [DTLDTLLINE]) ON [PRIMARY]
GO
