CREATE TABLE [dbo].[VOUCHERGIVERULECUROUTDTLOCR]
(
[BILLNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLLINE] [int] NOT NULL,
[CURCODE] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERGIVERULECUROUTDTLOCR] ADD CONSTRAINT [PK__VOUCHERGIVERULEC__3D094BE1] PRIMARY KEY CLUSTERED  ([BILLNUM], [BILLLINE]) ON [PRIMARY]
GO
