CREATE TABLE [dbo].[BUY11POOL]
(
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[SETTLENO] [int] NOT NULL,
[CURRENCY] [smallint] NOT NULL CONSTRAINT [DF__BUY11POOL__CURRE__5817A56F] DEFAULT (0),
[AMOUNT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__BUY11POOL__AMOUN__590BC9A8] DEFAULT (0),
[TAG] [smallint] NOT NULL CONSTRAINT [DF__BUY11POOL__TAG__59FFEDE1] DEFAULT (0),
[CARDCODE] [varchar] (128) COLLATE Chinese_PRC_CI_AS NULL,
[FAVTYPE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NULL,
[FAVAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__BUY11POOL__FAVAM__5AF4121A] DEFAULT (0),
[PARVALUE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__BUY11POOL__PARVA__5BE83653] DEFAULT (0),
[CURRENCYTYPE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[ORIGINALAMT] [decimal] (24, 4) NULL,
[PARITIES] [decimal] (24, 4) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BUY11POOL] ADD CONSTRAINT [PK__BUY11POOL__5CDC5A8C] PRIMARY KEY CLUSTERED  ([FLOWNO], [POSNO], [ITEMNO]) ON [PRIMARY]
GO
