CREATE TABLE [dbo].[VDRGD2]
(
[STOREGID] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[VDRGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VDRGD2] ADD CONSTRAINT [PK__VDRGD2__46892E07] PRIMARY KEY CLUSTERED  ([STOREGID], [GDGID], [VDRGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX] ON [dbo].[VDRGD2] ([VDRGID], [GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
