CREATE TABLE [dbo].[PSFORMULABASIC]
(
[CODE] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[QUESTYPE] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FORMULATYPE] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DISC] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[FDISC] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__PSFORMULA__LSTUP__62547169] DEFAULT (getdate()),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSFORMULABASIC] ADD CONSTRAINT [PK__PSFORMULABASIC__634895A2] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
