CREATE TABLE [dbo].[PSSUMPROMOTEGDDTL]
(
[UUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SORT] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSSUMPROMOTEGDDTL] ADD CONSTRAINT [PK__PSSUMPROMOTEGDDT__15E22FC3] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PSSUMPROMOTEGDDTL_GDGID] ON [dbo].[PSSUMPROMOTEGDDTL] ([GDGID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PSSUMPROMOTEGDDTL_SORT] ON [dbo].[PSSUMPROMOTEGDDTL] ([SORT]) ON [PRIMARY]
GO
