CREATE TABLE [dbo].[TMP_STOREPRODUCTS]
(
[spid] [int] NOT NULL,
[FGDGID] [int] NOT NULL,
[FLOWINV] [decimal] (24, 2) NULL,
[FHIGHINV] [decimal] (24, 2) NULL,
[LSTUPDTIME] [datetime] NULL,
[FLASTMODIFYTIME] [datetime] NULL,
[FLASTMODIFYOPER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[FINVLOWBOUND] [decimal] (24, 2) NULL,
[FINVHIGHBOUND] [decimal] (24, 2) NULL,
[FSUGGESTEDQTY] [decimal] (24, 2) NULL,
[FSUGGESTEDQTYHIGHBOUND] [decimal] (24, 2) NULL,
[FSUGGESTEDQTYLOWBOUND] [decimal] (24, 2) NULL,
[FORDQTYMIN] [decimal] (24, 2) NULL,
[FALWSORD] [int] NULL,
[FORDERMODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[FAUOTDELIVERALGORITHM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[FISBUSINESS] [int] NULL,
[FPURRTN] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[FRPOMOTIONINFO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_TMP_STOREPRODUCTS_FGDGID] ON [dbo].[TMP_STOREPRODUCTS] ([spid], [FGDGID]) ON [PRIMARY]
GO
