CREATE TABLE [dbo].[VOUCHERUSERULEOCR]
(
[STORE] [int] NOT NULL,
[BILLNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VOUCHERACTIVITY] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ISWHOLEUSE] [smallint] NOT NULL,
[ISALLPRMOUT] [smallint] NOT NULL,
[ISQTYLMT] [smallint] NOT NULL,
[LMTQTY] [int] NULL,
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[AMTCOND] [smallint] NOT NULL,
[AMTCONDUSEAMT] [decimal] (24, 2) NULL,
[AMTCONDUSEMUL] [decimal] (24, 2) NULL,
[SUBJECT] [varchar] (255) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERUSERULEOCR] ADD CONSTRAINT [PK__VOUCHERUSERULEOC__40D9DCC5] PRIMARY KEY CLUSTERED  ([STORE], [BILLNUM]) ON [PRIMARY]
GO
