CREATE TABLE [dbo].[EMPGROUPSPECRIGHT]
(
[EMPGROUPID] [int] NOT NULL,
[SPECRIGHTNO] [int] NOT NULL,
[RIGHTLEVEL] [int] NOT NULL,
[SPECRIGHTNO2] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
