CREATE TABLE [dbo].[EPSTASKMAN_GDSALECMD]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLAG] [int] NOT NULL CONSTRAINT [DF__EPSTASKMAN__FLAG__7DE77D45] DEFAULT (0),
[SNDTIME] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EPSTASKMAN_GDSALECMD] ADD CONSTRAINT [PK__EPSTASKMAN_GDSAL__7EDBA17E] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
