CREATE TABLE [dbo].[RCPDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SETTLENO] [int] NULL,
[GDGID] [int] NULL,
[NPQTY] [money] NULL,
[NPTOTAL] [money] NULL,
[QTY] [money] NULL,
[TOTAL] [money] NULL,
[INPRC] [money] NULL,
[RTLPRC] [money] NULL,
[FROMCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[FROMNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[FROMLINE] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RCPDTL] ADD CONSTRAINT [PK__RCPDTL__0CA5D9DE] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [rcpdtl_gdgid] ON [dbo].[RCPDTL] ([GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
