CREATE TABLE [dbo].[GFTAGMLACDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GFTAGMLACDTL] ADD CONSTRAINT [PK__GFTAGMLACDTL__7D6F4E9D] PRIMARY KEY CLUSTERED  ([NUM], [STOREGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
