CREATE TABLE [dbo].[TOURGUIDES]
(
[CODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TEL] [char] (50) COLLATE Chinese_PRC_CI_AS NULL,
[BELONGAREA] [char] (50) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[CREATOR] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__TOURGUIDE__CREAT__1AA482DB] DEFAULT ('未知[-]'),
[CREATETIME] [datetime] NOT NULL CONSTRAINT [DF__TOURGUIDE__CREAT__1B98A714] DEFAULT (getdate()),
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__TOURGUIDE__LSTUP__1C8CCB4D] DEFAULT ('未知[-]'),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__TOURGUIDE__LSTUP__1D80EF86] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TOURGUIDES] ADD CONSTRAINT [PK__TOURGUIDES__1E7513BF] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
