CREATE TABLE [dbo].[GFTPRMGIFTDTL]
(
[RCODE] [char] (18) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GROUPID] [int] NOT NULL,
[GFTGID] [int] NOT NULL,
[QTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMGIFTD__QTY__6F37D48D] DEFAULT (0),
[QTYLMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMGIF__QTYLM__702BF8C6] DEFAULT (0),
[SUMQTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMGIF__SUMQT__71201CFF] DEFAULT (0),
[SUMQTYLMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMGIF__SUMQT__72144138] DEFAULT (0),
[PAYPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMGIF__PAYPR__73086571] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GFTPRMGIFTDTL] ADD CONSTRAINT [PK__GFTPRMGIFTDTL__6E43B054] PRIMARY KEY CLUSTERED  ([RCODE], [GROUPID], [GFTGID]) ON [PRIMARY]
GO
