CREATE TABLE [dbo].[NICCARDHST]
(
[ACTION] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NICCARDHS__FILDA__70354F10] DEFAULT (getdate()),
[STORE] [int] NOT NULL,
[CARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OLDCARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[OLDBAL] [decimal] (24, 2) NULL,
[OCCUR] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NICCARDHS__OCCUR__71297349] DEFAULT (0),
[OLDSCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NICCARDHS__OLDSC__721D9782] DEFAULT (0),
[Score] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NICCARDHS__Score__7311BBBB] DEFAULT (0),
[OLDBYDATE] [datetime] NULL,
[NEWBYDATE] [datetime] NULL,
[OPER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[CARRIER] [int] NOT NULL CONSTRAINT [DF__NICCARDHS__CARRI__7405DFF4] DEFAULT (1),
[CARDCOST] [decimal] (24, 2) NULL,
[CardType] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[LstSndTime] [datetime] NULL,
[Sender] [int] NULL,
[Src] [int] NOT NULL,
[CHARGE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NICCARDHS__CHARG__74FA042D] DEFAULT (0),
[ID] [int] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[RCV] [int] NULL,
[RCVTIME] [datetime] NULL,
[FRCCHK] [smallint] NOT NULL,
[NTYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[SAVETYPE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NICCARDHS__SAVET__1AE0814A] DEFAULT ('现金'),
[CHECKID] [int] NOT NULL CONSTRAINT [DF__NICCARDHS__CHECK__1BD4A583] DEFAULT (0),
[CHECKNO] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NICCARDHST] ADD CONSTRAINT [PK__NICCARDHST__6F412AD7] PRIMARY KEY CLUSTERED  ([ID], [Src]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
