CREATE TABLE [dbo].[MXF]
(
[NUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FROMSTORE] [int] NOT NULL,
[TOSTORE] [int] NOT NULL,
[XCHGSTORE] [int] NOT NULL,
[WRH] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__MXF__FILDATE__21A28D72] DEFAULT (getdate()),
[FILLER] [int] NOT NULL CONSTRAINT [DF__MXF__FILLER__2296B1AB] DEFAULT (1),
[FROMTOTAL] [money] NOT NULL CONSTRAINT [DF__MXF__FROMTOTAL__238AD5E4] DEFAULT (0),
[TOTOTAL] [money] NOT NULL CONSTRAINT [DF__MXF__TOTOTAL__247EFA1D] DEFAULT (0),
[FROMTAX] [money] NOT NULL CONSTRAINT [DF__MXF__FROMTAX__25731E56] DEFAULT (0),
[TOTAX] [money] NOT NULL CONSTRAINT [DF__MXF__TOTAX__2667428F] DEFAULT (0),
[FROMCOST] [money] NOT NULL CONSTRAINT [DF__MXF__FROMCOST__275B66C8] DEFAULT (0),
[TOCOST] [money] NOT NULL CONSTRAINT [DF__MXF__TOCOST__284F8B01] DEFAULT (0),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__MXF__STAT__2943AF3A] DEFAULT (0),
[SRC] [int] NOT NULL,
[RECCNT] [int] NOT NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[MODNUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NULL,
[DMDNUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MXF] ADD CONSTRAINT [PK__MXF__5BF18C9D] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
