CREATE TABLE [dbo].[WEBSFLOWNOCOMPARISON]
(
[SHOPCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SHOPFLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSID] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WEBSFLOWNOCOMPARISON] ADD CONSTRAINT [PK__WEBSFLOWNOCOMPAR__72107A4F] PRIMARY KEY CLUSTERED  ([SHOPCODE], [POSID], [FLOWNO], [SHOPFLOWNO]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [UK_WEBSFLOWNOCOMPARISON_FLOWNO] ON [dbo].[WEBSFLOWNOCOMPARISON] ([SHOPCODE], [POSID], [FLOWNO]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [UK_WEBSFLOWNOCOMPARISON_SHOPFLOWNO] ON [dbo].[WEBSFLOWNOCOMPARISON] ([SHOPCODE], [POSID], [SHOPFLOWNO]) ON [PRIMARY]
GO
