CREATE TABLE [dbo].[VOUCHER]
(
[NUM] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STATE] [int] NOT NULL CONSTRAINT [DF__VOUCHER__STATE__69D662F7] DEFAULT (0),
[PHASE] [int] NOT NULL CONSTRAINT [DF__VOUCHER__PHASE__6ACA8730] DEFAULT (0),
[CREATETIME] [datetime] NOT NULL CONSTRAINT [DF__VOUCHER__CREATET__6BBEAB69] DEFAULT (getdate()),
[CREATOR] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[AMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__VOUCHER__AMOUNT__6CB2CFA2] DEFAULT (0),
[ENCRYPTKEY] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL,
[RECEIVESTORE] [int] NULL,
[RECEIVEOPERATOR] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[RECEIVETIME] [datetime] NULL,
[RECYCLESTORE] [int] NULL,
[RECYCLEOPERATOR] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[RECYCLETIME] [datetime] NULL,
[DISPOSESTORE] [int] NULL,
[DISPOSEOPERATOR] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[DISPOSETIME] [datetime] NULL,
[VOUCHERTYPE] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL,
[SELLAMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__VOUCHER__SELLAMO__5E5B5A01] DEFAULT (0),
[SELLOPERATOR] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[SELLSTORE] [int] NULL,
[SELLTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHER] ADD CONSTRAINT [PK__VOUCHER__6DA6F3DB] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_ENNUM] ON [dbo].[VOUCHER] ([ENCRYPTKEY]) ON [PRIMARY]
GO
