CREATE TABLE [dbo].[VOUCHERACTBCKTRANSGDDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[BCKQTY] [decimal] (24, 4) NOT NULL,
[BCKPRICE] [decimal] (24, 4) NOT NULL,
[BCKTOTAL] [decimal] (24, 2) NOT NULL,
[BUYQTY] [decimal] (24, 4) NULL,
[BUYPRICE] [decimal] (24, 4) NULL,
[BUYTOTAL] [decimal] (24, 2) NULL,
[BCKEDQTY] [decimal] (24, 4) NULL,
[BCKEDPRICE] [decimal] (24, 4) NULL,
[BCKEDTOTAL] [decimal] (24, 2) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERACTBCKTRANSGDDTL] ADD CONSTRAINT [PK__VOUCHERACTBCKTRA__60879248] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_VOUCHERACTBCKTRANSGDDTL_GDGID] ON [dbo].[VOUCHERACTBCKTRANSGDDTL] ([GDGID]) ON [PRIMARY]
GO
