CREATE TABLE [dbo].[TA_RELATION]
(
[RELATIONID] [int] NOT NULL,
[OPERATIONID] [int] NOT NULL,
[DIRECTION] [smallint] NOT NULL,
[ACCOUNT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ACCOUNTNAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[BRIEF] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[TOTALMONEY] [int] NOT NULL,
[QUANTITY] [int] NULL,
[Price] [int] NULL,
[CASHCODE] [int] NULL,
[FOREINMONEY] [int] NULL,
[RATE] [int] NULL,
[SETTLETYPENAME] [int] NULL,
[SETTLENO] [int] NULL,
[SETTLEDATE] [int] NULL,
[DEPARTNAME] [int] NULL,
[PERSONNAME] [int] NULL,
[FIRMCode] [int] NULL,
[FIRMNAME] [int] NULL,
[CORCODE] [int] NULL,
[PROJECTCODE] [int] NULL,
[PROJECTNAME] [int] NULL,
[OperatorCode] [int] NULL,
[OperatorName] [int] NULL,
[OperateDate] [int] NULL,
[ISSUM] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TA_RELATION] ADD CONSTRAINT [PK__TA_RELATION__2E06CDA9] PRIMARY KEY CLUSTERED  ([RELATIONID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
