CREATE TABLE [dbo].[TMPSTKOUTDTL]
(
[SPID] [int] NOT NULL,
[SRCNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GFTGID] [int] NOT NULL,
[GFTQTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__TMPSTKOUT__GFTQT__293102A6] DEFAULT (0),
[GFTWRH] [int] NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_TMPSTKOUTDTL_SPID] ON [dbo].[TMPSTKOUTDTL] ([SPID]) ON [PRIMARY]
GO
