CREATE TABLE [dbo].[PROMOTEQTY]
(
[BILLNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PRMNO] [int] NOT NULL,
[QTY] [decimal] (24, 2) NOT NULL,
[PRMTOTAL] [decimal] (24, 2) NOT NULL,
[IFGFT] [int] NOT NULL,
[GFTQTY] [decimal] (24, 4) NOT NULL,
[PTOTAL] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PROMOTEQT__PTOTA__34E44322] DEFAULT (0),
[GDGID] [int] NOT NULL CONSTRAINT [DF__PROMOTEQT__GDGID__6FBAF02D] DEFAULT (1),
[RTLPRC] [decimal] (24, 4) NULL,
[FLAG] [int] NOT NULL CONSTRAINT [DF__PROMOTEQTY__FLAG__7E090F84] DEFAULT (1),
[PPRC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PROMOTEQTY__PPRC__7EFD33BD] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROMOTEQTY] ADD CONSTRAINT [PK__PROMOTEQTY__3247CD99] PRIMARY KEY CLUSTERED  ([BILLNUM], [CLS], [PRMNO], [GDGID], [FLAG]) ON [PRIMARY]
GO
