CREATE TABLE [dbo].[NINDRPT]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ASTORE] [int] NULL,
[ASETTLENO] [int] NULL,
[ADATE] [datetime] NULL,
[BGDGID] [int] NULL,
[BVDRGID] [int] NULL,
[BWRH] [int] NULL,
[DQ1] [money] NULL CONSTRAINT [DF__NINDRPT__DQ1__1BE8E8C5] DEFAULT (0),
[DQ2] [money] NULL CONSTRAINT [DF__NINDRPT__DQ2__1CDD0CFE] DEFAULT (0),
[DQ3] [money] NULL CONSTRAINT [DF__NINDRPT__DQ3__1DD13137] DEFAULT (0),
[DQ4] [money] NULL CONSTRAINT [DF__NINDRPT__DQ4__1EC55570] DEFAULT (0),
[DT1] [money] NULL CONSTRAINT [DF__NINDRPT__DT1__1FB979A9] DEFAULT (0),
[DT2] [money] NULL CONSTRAINT [DF__NINDRPT__DT2__20AD9DE2] DEFAULT (0),
[DT3] [money] NULL CONSTRAINT [DF__NINDRPT__DT3__21A1C21B] DEFAULT (0),
[DT4] [money] NULL CONSTRAINT [DF__NINDRPT__DT4__2295E654] DEFAULT (0),
[DI1] [money] NULL CONSTRAINT [DF__NINDRPT__DI1__238A0A8D] DEFAULT (0),
[DI2] [money] NULL CONSTRAINT [DF__NINDRPT__DI2__247E2EC6] DEFAULT (0),
[DI3] [money] NULL CONSTRAINT [DF__NINDRPT__DI3__257252FF] DEFAULT (0),
[DI4] [money] NULL CONSTRAINT [DF__NINDRPT__DI4__26667738] DEFAULT (0),
[DR1] [money] NULL CONSTRAINT [DF__NINDRPT__DR1__275A9B71] DEFAULT (0),
[DR2] [money] NULL CONSTRAINT [DF__NINDRPT__DR2__284EBFAA] DEFAULT (0),
[DR3] [money] NULL CONSTRAINT [DF__NINDRPT__DR3__2942E3E3] DEFAULT (0),
[DR4] [money] NULL CONSTRAINT [DF__NINDRPT__DR4__2A37081C] DEFAULT (0),
[NSTAT] [smallint] NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NULL,
[RCV] [int] NULL,
[SNDTIME] [datetime] NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NINDRPT] ADD CONSTRAINT [PK__NINDRPT__2D47B39A] PRIMARY KEY CLUSTERED  ([ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
