CREATE TABLE [dbo].[INPRCADJLACDTL]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STORE] [int] NOT NULL,
[STAT] [smallint] NOT NULL,
[LACTIME] [datetime] NULL,
[INADJAMT] [money] NULL,
[INVADJAMT] [money] NULL,
[OUTADJAMT] [money] NULL,
[ALCADJAMT] [money] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INPRCADJLACDTL] ADD CONSTRAINT [PK__INPRCADJLACDTL__77DFC722] PRIMARY KEY CLUSTERED  ([CLS], [NUM], [STORE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
