CREATE TABLE [dbo].[VOUCHERBCKSTGRCV]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__VOUCHERBCK__STAT__3CFA6636] DEFAULT (0),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__VOUCHERBC__FILLE__3DEE8A6F] DEFAULT ('未知[-]'),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__VOUCHERBC__FILDA__3EE2AEA8] DEFAULT (getdate()),
[CHKDATE] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__VOUCHERBC__RECCN__3FD6D2E1] DEFAULT (0),
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERBCKSTGRCV] ADD CONSTRAINT [PK__VOUCHERBCKSTGRCV__40CAF71A] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
