CREATE TABLE [dbo].[VDRAGMTDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[GDCODE] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MUNIT] [char] (6) COLLATE Chinese_PRC_CI_AS NOT NULL,
[QPCSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL,
[QPC] [decimal] (24, 4) NOT NULL,
[QTYRAT] [char] (15) COLLATE Chinese_PRC_CI_AS NULL,
[ISGFT] [smallint] NOT NULL CONSTRAINT [DF__VDRAGMTDT__ISGFT__3681A77A] DEFAULT (0),
[FROMGID] [int] NULL,
[LISTPRC] [decimal] (24, 4) NOT NULL,
[NDIS] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__VDRAGMTDTL__NDIS__3775CBB3] DEFAULT (0),
[DDIS] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__VDRAGMTDTL__DDIS__3869EFEC] DEFAULT (0),
[EDIS] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__VDRAGMTDTL__EDIS__395E1425] DEFAULT (0),
[MDIS] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__VDRAGMTDTL__MDIS__3A52385E] DEFAULT (0),
[REBATE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__VDRAGMTDT__REBAT__3B465C97] DEFAULT (0),
[BDIS] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__VDRAGMTDTL__BDIS__3C3A80D0] DEFAULT (0),
[NPDIS] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__VDRAGMTDT__NPDIS__3D2EA509] DEFAULT (0),
[ODIS] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__VDRAGMTDTL__ODIS__3E22C942] DEFAULT (0),
[PRICE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__VDRAGMTDT__PRICE__3F16ED7B] DEFAULT (0),
[OPER] [smallint] NOT NULL CONSTRAINT [DF__VDRAGMTDTL__OPER__400B11B4] DEFAULT (0),
[AMTDIS] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__VDRAGMTDT__AMTDI__40FF35ED] DEFAULT (0),
[MINORDQTY] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__VDRAGMTDT__MINOR__41F35A26] DEFAULT ('0'),
[GFTDESC] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[LACKCHGPRICE] [decimal] (24, 4) NULL,
[CALCFLAG] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__VDRAGMTDT__CALCF__42E77E5F] DEFAULT ('0001'),
[SALE] [smallint] NOT NULL CONSTRAINT [DF__VDRAGMTDTL__SALE__43DBA298] DEFAULT (1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VDRAGMTDTL] ADD CONSTRAINT [PK__VDRAGMTDTL__44CFC6D1] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
