CREATE TABLE [dbo].[NPSSORTSCORULEOPT]
(
[OPTCAPTION] [varchar] (128) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OPTVALUE] [varchar] (128) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__NPSSORTSC__LSTUP__4685671E] DEFAULT (getdate()),
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[FRCCHK] [smallint] NOT NULL,
[NTYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [char] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPSSORTSCORULEOPT] ADD CONSTRAINT [PK__NPSSORTSCORULEOP__47798B57] PRIMARY KEY CLUSTERED  ([SRC], [RCV], [OPTCAPTION]) ON [PRIMARY]
GO
