CREATE TABLE [dbo].[NFAVDRPT]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[BVDRGID] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[BGDGID] [int] NOT NULL,
[FAVTYPE] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FAVRATE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NFAVDRPT__FAVRAT__6511ADDA] DEFAULT (0),
[FAVAMOUNT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NFAVDRPT__FAVAMO__6605D213] DEFAULT (0),
[FAVPAY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NFAVDRPT__FAVPAY__66F9F64C] DEFAULT (0),
[PROMCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[PROMNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[PROMLINE] [int] NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[RCV] [int] NULL,
[SNDTIME] [datetime] NOT NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL,
[BCSTGID] [int] NOT NULL CONSTRAINT [DF__NFAVDRPT__BCSTGI__6C7DC578] DEFAULT (1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NFAVDRPT] ADD CONSTRAINT [PK__NFAVDRPT__67EE1A85] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
