CREATE TABLE [dbo].[RCPCSTCURDTL]
(
[CLS] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CURRENCY] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[AMOUNT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__RCPCSTCUR__AMOUN__5E8F98D4] DEFAULT (0),
[CARDCODE] [varchar] (128) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RCPCSTCURDTL] ADD CONSTRAINT [PK__RCPCSTCURDTL__5F83BD0D] PRIMARY KEY CLUSTERED  ([CLS], [NUM], [CURRENCY]) ON [PRIMARY]
GO
