CREATE TABLE [dbo].[NDSP]
(
[SRC] [int] NOT NULL CONSTRAINT [DF__NDSP__SRC__17C41D7D] DEFAULT (1),
[ID] [int] NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[INVNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[CREATETIME] [datetime] NULL,
[TOTAL] [money] NOT NULL CONSTRAINT [DF__NDSP__TOTAL__18B841B6] DEFAULT (0),
[RECCNT] [int] NOT NULL,
[FILLER] [int] NULL,
[OPENER] [int] NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNOCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SETTLENO] [int] NOT NULL,
[SRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[RCV] [int] NULL,
[SNDTIME] [datetime] NOT NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[STAT] [smallint] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NDSP__FILDATE__19AC65EF] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NDSP] ADD CONSTRAINT [PK__NDSP__23BE4960] PRIMARY KEY CLUSTERED  ([SRC], [ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
