CREATE TABLE [dbo].[NSETTLEAREAVDR]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[VDRGID] [int] NOT NULL,
[CODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NSETTLEAREAVDR] ADD CONSTRAINT [PK__NSETTLEAREAVDR__4686FDCC] PRIMARY KEY CLUSTERED  ([SRC], [ID], [VDRGID], [CODE]) ON [PRIMARY]
GO
