CREATE TABLE [dbo].[BCKNOTIFY]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[RECCNT] [int] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__BCKNOTIFY__FILDA__0A2AF694] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHKDATE] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[SNDDATE] [datetime] NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__BCKNOTIFY__STAT__0B1F1ACD] DEFAULT (0),
[STOREGID] [int] NOT NULL,
[PRNTIME] [datetime] NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__BCKNOTIFY__LSTUP__0C133F06] DEFAULT (getdate()),
[LOCKNUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NULL,
[EXPDATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BCKNOTIFY] ADD CONSTRAINT [PK__BCKNOTIFY__0936D25B] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
