CREATE TABLE [dbo].[NINPRCADJAINVDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[LINE] [smallint] NOT NULL,
[WRH] [int] NULL,
[SUBWRH] [int] NULL,
[QTY] [money] NOT NULL,
[COST] [money] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NINPRCADJAINVDTL] ADD CONSTRAINT [PK__NINPRCADJAINVDTL__30242045] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
