CREATE TABLE [dbo].[NPOLYPAYRATEPRM]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__NPOLYPAYRA__STAT__433D4F71] DEFAULT (0),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NPOLYPAYR__FILDA__443173AA] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NPOLYPAYR__FILLE__452597E3] DEFAULT ('未知[-]'),
[CHKDATE] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NULL,
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[TOPIC] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[PSETTLENO] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPOLYPAYRATEPRM] ADD CONSTRAINT [PK__NPOLYPAYRATEPRM__4619BC1C] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPOLYPAYRATEPRM_NUM] ON [dbo].[NPOLYPAYRATEPRM] ([NUM]) ON [PRIMARY]
GO
