CREATE TABLE [dbo].[INOUTBILL]
(
[BILL] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[INVNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[WRH] [int] NOT NULL CONSTRAINT [DF__INOUTBILL__WRH__04B14909] DEFAULT (1),
[SENDER] [int] NOT NULL,
[RECEIVER] [int] NOT NULL,
[CHECKER] [int] NOT NULL CONSTRAINT [DF__INOUTBILL__CHECK__05A56D42] DEFAULT (1),
[CHKDATE] [datetime] NULL,
[PRECHECKER] [int] NOT NULL,
[PRECHKDATE] [datetime] NOT NULL,
[BILLSTAT] [smallint] NOT NULL,
[PRNTIME] [datetime] NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__INOUTBILL__STAT__0699917B] DEFAULT (0),
[OPER] [int] NULL CONSTRAINT [DF__INOUTBILL__OPER__078DB5B4] DEFAULT (1),
[INOUTTIME] [datetime] NULL,
[GEN] [int] NULL,
[GENBILL] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[GENCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[GENNUM] [char] (12) COLLATE Chinese_PRC_CI_AS NULL,
[CREATEDATE] [datetime] NOT NULL CONSTRAINT [DF__INOUTBILL__CREAT__0881D9ED] DEFAULT (getdate()),
[SRC] [int] NOT NULL CONSTRAINT [DF__INOUTBILL__SRC__12FF6860] DEFAULT (1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INOUTBILL] WITH NOCHECK ADD CONSTRAINT [INOUTBILL_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[INOUTBILL] ADD CONSTRAINT [PK__INOUTBILL__731B1205] PRIMARY KEY CLUSTERED  ([BILL], [CLS], [NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [INOUTBILL_INVNUM] ON [dbo].[INOUTBILL] ([INVNUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
