CREATE TABLE [dbo].[RCPADJ]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NULL,
[FILDATE] [datetime] NULL,
[FILLER] [int] NULL,
[CHECKER] [int] NULL,
[WRH] [int] NULL,
[CLIENT] [int] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[STAT] [int] NULL,
[PRNTIME] [datetime] NULL,
[OCRDATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RCPADJ] WITH NOCHECK ADD CONSTRAINT [RCPADJ_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[RCPADJ] ADD CONSTRAINT [PK__RCPADJ__09C96D33] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FILDATE] ON [dbo].[RCPADJ] ([FILDATE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
