CREATE TABLE [dbo].[ORDCHKLVLEMP]
(
[ID] [int] NOT NULL,
[EMPGID] [int] NOT NULL,
[LSTUPDTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORDCHKLVLEMP] ADD CONSTRAINT [PK__ORDCHKLVLEMP__69A158CD] PRIMARY KEY CLUSTERED  ([ID], [EMPGID]) ON [PRIMARY]
GO
