CREATE TABLE [dbo].[BLPREORDDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[FLAG] [smallint] NOT NULL CONSTRAINT [DF__BLPREORDDT__FLAG__1FC5FD4F] DEFAULT (0),
[GDGID] [int] NULL,
[MINORDCases] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__BLPREORDD__MINOR__20BA2188] DEFAULT (0),
[MINORDQTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__BLPREORDD__MINOR__21AE45C1] DEFAULT (0),
[ORDPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__BLPREORDD__ORDPR__22A269FA] DEFAULT (0),
[RTLPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__BLPREORDD__RTLPR__23968E33] DEFAULT (0),
[WHSPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__BLPREORDD__WHSPR__248AB26C] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BLPREORDDTL] ADD CONSTRAINT [PK__BLPREORDDTL__1ED1D916] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
