CREATE TABLE [dbo].[FAUSERPWDLOG]
(
[USERGID] [int] NOT NULL,
[PASSWORD] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FAUSERPWDLOG] ADD CONSTRAINT [PK__FAUSERPWDLOG__206154E4] PRIMARY KEY CLUSTERED  ([USERGID], [LSTUPDTIME]) ON [PRIMARY]
GO
