CREATE TABLE [dbo].[PROMBDIS]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PROMBDIS__QTY__684D41E1] DEFAULT (1),
[RTLPRC] [decimal] (24, 4) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROMBDIS] ADD CONSTRAINT [PK__PROMBDIS__6941661A] PRIMARY KEY CLUSTERED  ([NUM], [QTY]) ON [PRIMARY]
GO
