CREATE TABLE [dbo].[CRMCARDDEPOSITCARDINFO]
(
[CARDNUM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARDTYPE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PASSWORD1] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PASSWORD2] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMCARDDEPOSITCARDINFO] ADD CONSTRAINT [PK__CRMCARDDEPOSITCA__72150C8F] PRIMARY KEY CLUSTERED  ([CARDNUM]) ON [PRIMARY]
GO
