CREATE TABLE [dbo].[PSNMKTIVGT]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__PSNMKTIVGT__STAT__690B9099] DEFAULT (0),
[RATIFIER] [int] NULL,
[SRC] [int] NOT NULL,
[Ivgtor] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__PSNMKTIVG__FILDA__69FFB4D2] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[REQOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[REQDATE] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[BEGINDATE] [datetime] NULL,
[LSTUPDTIME] [datetime] NULL CONSTRAINT [DF__PSNMKTIVG__LSTUP__6AF3D90B] DEFAULT (getdate()),
[PRNTIME] [datetime] NULL,
[SNDTIME] [datetime] NULL,
[SETTLENO] [int] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__PSNMKTIVG__RECCN__6BE7FD44] DEFAULT (0),
[OCRSTORE] [int] NULL CONSTRAINT [DF__PSNMKTIVG__OCRST__6CDC217D] DEFAULT (0),
[ADDR] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__PSNMKTIVGT__ADDR__6DD045B6] DEFAULT (0),
[ID] [int] NOT NULL,
[RCV] [int] NULL,
[RCVTIME] [datetime] NULL,
[NTYPE] [int] NULL,
[NSTAT] [int] NULL,
[NNOTE] [char] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSNMKTIVGT] ADD CONSTRAINT [PK__PSNMktIvgt__6EC469EF] PRIMARY KEY CLUSTERED  ([ID], [NUM], [SRC]) ON [PRIMARY]
GO
