CREATE TABLE [dbo].[RTLPRCADJDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[OLDRTLPRC] [money] NOT NULL,
[NEWRTLPRC] [money] NULL,
[OLDLWTPRC] [money] NULL,
[NEWLWTPRC] [money] NULL,
[OLDTOPPRC] [money] NULL,
[NEWTOPPRC] [money] NULL,
[QTY] [money] NOT NULL CONSTRAINT [DF__RTLPRCADJDT__QTY__1FA601BE] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[OLDMBRPRC] [money] NULL,
[NEWMBRPRC] [money] NULL,
[OLDWHSPRC] [money] NULL,
[NEWWHSPRC] [money] NULL,
[QPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__RTLPRCADJDT__QPC__41687EEA] DEFAULT (1),
[QPCSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__RTLPRCADJ__QPCST__425CA323] DEFAULT ('1*1')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RTLPRCADJDTL] ADD CONSTRAINT [PK__RTLPRCADJDTL__1EB1DD85] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [INDEX_RTLPRCADJDTL_GDGID] ON [dbo].[RTLPRCADJDTL] ([GDGID]) ON [PRIMARY]
GO
