CREATE TABLE [dbo].[MXFDMD]
(
[NUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__MXFDMD__STAT__5C9EC56F] DEFAULT (0),
[FROMSTORE] [int] NOT NULL,
[TOSTORE] [int] NOT NULL,
[XCHGSTORE] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__MXFDMD__FILDATE__5D92E9A8] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__MXFDMD__FILLER__5E870DE1] DEFAULT ('未知[-]'),
[DMDDATE] [datetime] NULL,
[DMDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NULL,
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRC] [int] NOT NULL,
[SRCNUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[EXPDATE] [datetime] NULL,
[FROMTOTAL] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__MXFDMD__FROMTOTA__5F7B321A] DEFAULT (0),
[FROMTAX] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__MXFDMD__FROMTAX__606F5653] DEFAULT (0),
[RCVTIME] [datetime] NULL,
[DEPT] [char] (10) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MXFDMD] ADD CONSTRAINT [PK__MXFDMD__61637A8C] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
