CREATE TABLE [dbo].[PSCSSCONFIG]
(
[CODE] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (128) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CATALOG] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CFGVALUETYPE] [smallint] NOT NULL,
[DEFAULTVALUE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[DATATYPE] [smallint] NOT NULL CONSTRAINT [DF__PSCSSCONF__DATAT__254B6329] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSCSSCONFIG] ADD CONSTRAINT [PK__PSCSSCONFIG__263F8762] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
