CREATE TABLE [dbo].[GOODSRECEIPT]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__GOODSRECEI__STAT__6B395F8E] DEFAULT (0),
[RECEIVER] [int] NOT NULL CONSTRAINT [DF__GOODSRECE__RECEI__6C2D83C7] DEFAULT (1),
[SRCORDNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__GOODSRECE__FILLE__6D21A800] DEFAULT ('未知[-]'),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__GOODSRECE__FILDA__6E15CC39] DEFAULT (getdate()),
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__GOODSRECE__RECCN__6F09F072] DEFAULT (0),
[PRNTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GOODSRECEIPT] ADD CONSTRAINT [PK__GOODSRECEIPT__6FFE14AB] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
