CREATE TABLE [dbo].[CRMCARDINV]
(
[CARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMCARDINV] ADD CONSTRAINT [PK__CRMCARDINV__6A73EAC7] PRIMARY KEY CLUSTERED  ([CARDNUM]) ON [PRIMARY]
GO
