CREATE TABLE [dbo].[PODPRINTLOG]
(
[GRP] [int] NOT NULL,
[PRINTER] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[PRINTTIME] [datetime] NULL,
[PODNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[HANDNUM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PODPRINTLOG] ADD CONSTRAINT [PK__PODPRINTLOG__533D1662] PRIMARY KEY CLUSTERED  ([GRP], [PODNUM]) ON [PRIMARY]
GO
