CREATE TABLE [dbo].[PS3_ONLINECNTR]
(
[UUID] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PLATFORM] [varchar] (80) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CNTRNO] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SHOPID] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VDRCODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLEDEPT] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[REALENDDATE] [datetime] NOT NULL,
[SIGNER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[AGENTMODE] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SALECLS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[FILETEXT] [text] COLLATE Chinese_PRC_CI_AS NOT NULL,
[RENT] [decimal] (24, 2) NULL,
[GUARDAMT] [decimal] (24, 2) NULL,
[UPGUARDRATE] [decimal] (24, 2) NULL,
[GUARDRATE] [decimal] (24, 2) NULL,
[CUSTOMDEF] [char] (50) COLLATE Chinese_PRC_CI_AS NULL,
[CUSTOMDEF1] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SALEAREA] [decimal] (24, 2) NULL,
[REALAREA] [decimal] (24, 2) NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[OPERATIONSTAT] [smallint] NOT NULL CONSTRAINT [DF__PS3_ONLIN__OPERA__69D1D0B7] DEFAULT ((0)),
[OPERATIONNOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3_ONLINECNTR] ADD CONSTRAINT [PK__PS3_ONLI__65A475E767E98845] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3_ONLINECNTR_PC] ON [dbo].[PS3_ONLINECNTR] ([PLATFORM], [CNTRNO]) ON [PRIMARY]
GO
