CREATE TABLE [dbo].[TA_RltAccDtl]
(
[RELATIONID] [int] NOT NULL,
[CorSerialNO] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TA_RltAccDtl] ADD CONSTRAINT [UQ__TA_RltAccDtl__7D79703E] UNIQUE NONCLUSTERED  ([RELATIONID], [CorSerialNO]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
