CREATE TABLE [dbo].[GFTAGM]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[VENDOR] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__GFTAGM__FILDATE__75CE2CD5] DEFAULT (getdate()),
[FILLER] [int] NOT NULL CONSTRAINT [DF__GFTAGM__FILLER__76C2510E] DEFAULT (1),
[CHECKER] [int] NOT NULL CONSTRAINT [DF__GFTAGM__CHECKER__77B67547] DEFAULT (1),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__GFTAGM__STAT__78AA9980] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__GFTAGM__RECCNT__799EBDB9] DEFAULT (0),
[SRC] [int] NOT NULL CONSTRAINT [DF__GFTAGM__SRC__7A92E1F2] DEFAULT (1),
[EON] [smallint] NOT NULL CONSTRAINT [DF__GFTAGM__EON__7B87062B] DEFAULT (1),
[SRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[FINISHED] [int] NOT NULL CONSTRAINT [DF__gftagm__FINISHED__6F170DA5] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GFTAGM] ADD CONSTRAINT [PK__GFTAGM__74DA089C] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FILDATE] ON [dbo].[GFTAGM] ([FILDATE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_FILDATE] ON [dbo].[GFTAGM] ([FILDATE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
