CREATE TABLE [dbo].[OVFDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SETTLENO] [int] NULL,
[GDGID] [int] NULL,
[QTYOVF] [money] NULL CONSTRAINT [DF__OVFDTL__QTYOVF__1AE9D794] DEFAULT (0),
[AMTOVF] [money] NULL CONSTRAINT [DF__OVFDTL__AMTOVF__1BDDFBCD] DEFAULT (0),
[INPRC] [money] NULL CONSTRAINT [DF__OVFDTL__INPRC__1CD22006] DEFAULT (0),
[RTLPRC] [money] NULL CONSTRAINT [DF__OVFDTL__RTLPRC__1DC6443F] DEFAULT (0),
[VALIDDATE] [datetime] NULL,
[subwrh] [int] NULL,
[COST] [money] NOT NULL CONSTRAINT [DF__OVFDTL__COST__3652C63E] DEFAULT (0),
[COSTPRC] [money] NOT NULL CONSTRAINT [DF__OVFDTL__COSTPRC__6681C7A4] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OVFDTL] ADD CONSTRAINT [PK__OVFDTL__63A3C44B] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ovfdtl_gdgid] ON [dbo].[OVFDTL] ([GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OVFDTL] ADD CONSTRAINT [在溢余单中商品不能重复] UNIQUE NONCLUSTERED  ([NUM], [GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
