CREATE TABLE [dbo].[NBRANDCLASS]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[GID] [int] NOT NULL,
[NAME] [varchar] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NBRANDCLASS] ADD CONSTRAINT [PK__NBRANDCLASS__526B4FBF] PRIMARY KEY CLUSTERED  ([SRC], [ID], [GID]) ON [PRIMARY]
GO
