CREATE TABLE [dbo].[NCNTRGDSCOPE]
(
[NO] [int] NOT NULL,
[NOTE] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SQL] [char] (300) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SQLTEXT] [char] (400) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCNTRGDSCOPE] ADD CONSTRAINT [PK__NCNTRGDSCOPE__47B72074] PRIMARY KEY CLUSTERED  ([SRC], [ID], [NO]) ON [PRIMARY]
GO
