CREATE TABLE [dbo].[GOODSAPPLAC]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GOODSAPPLAC] ADD CONSTRAINT [PK__GOODSAPPLAC__05E62FBB] PRIMARY KEY CLUSTERED  ([NUM], [STOREGID]) ON [PRIMARY]
GO
