CREATE TABLE [dbo].[GFTPRMRULELMTDTL]
(
[RCODE] [char] (18) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LMTNO] [int] NOT NULL,
[LINE] [int] NOT NULL,
[NAME] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VALUE] [char] (10) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GFTPRMRULELMTDTL] ADD CONSTRAINT [PK__GFTPRMRULELMTDTL__61DDD96F] PRIMARY KEY CLUSTERED  ([RCODE], [LMTNO], [LINE]) ON [PRIMARY]
GO
