CREATE TABLE [dbo].[CKCHG]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[OPTIME] [datetime] NOT NULL CONSTRAINT [DF__CKCHG__OPTIME__5B052800] DEFAULT (getdate()),
[WRH] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[OPERATOR] [int] NOT NULL,
[OLDQTY] [money] NOT NULL,
[OLDTOTAL] [money] NOT NULL,
[NEWQTY] [money] NOT NULL,
[NEWTOTAL] [money] NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[subwrh] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CKCHG] ADD CONSTRAINT [PK__CKCHG__27C3E46E] PRIMARY KEY CLUSTERED  ([ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [CKCHG_X] ON [dbo].[CKCHG] ([OPTIME], [WRH], [GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
