CREATE TABLE [dbo].[EXTRARIGHT]
(
[NO] [smallint] NOT NULL,
[NAME] [char] (40) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EXTRARIGHT] ADD CONSTRAINT [PK__EXTRARIGHT__58671BC9] PRIMARY KEY CLUSTERED  ([NO]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
