CREATE TABLE [dbo].[PRMOFFSETEFFECT]
(
[GDGID] [int] NOT NULL,
[VDRGID] [int] NOT NULL,
[STOREGID] [int] NOT NULL,
[QPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PRMOFFSETEF__QPC__0B2ECBCF] DEFAULT (1),
[QPCSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PRMOFFSET__QPCST__0C22F008] DEFAULT ('1*1'),
[OFFSETPRC] [decimal] (24, 4) NULL,
[CNTINPRC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PRMOFFSET__CNTIN__0D171441] DEFAULT (0),
[QTY] [decimal] (24, 4) NULL,
[START] [datetime] NOT NULL CONSTRAINT [DF__PRMOFFSET__START__0E0B387A] DEFAULT ('1899.12.30 00:00:00'),
[FINISH] [datetime] NOT NULL CONSTRAINT [DF__PRMOFFSET__FINIS__0EFF5CB3] DEFAULT ('9999.12.31 23:59:59'),
[ALC] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TOTAL] [decimal] (24, 4) NULL,
[AMOUNT] [decimal] (24, 4) NULL,
[TAX] [decimal] (24, 4) NULL,
[DIFFPRC] [decimal] (24, 4) NULL,
[OFFSETTYPE] [int] NOT NULL CONSTRAINT [DF__PRMOFFSET__OFFSE__0FF380EC] DEFAULT (0),
[OFFSETCALCTYPE] [int] NOT NULL CONSTRAINT [DF__PRMOFFSET__OFFSE__10E7A525] DEFAULT (0)
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [UQ_PRMOFFSETEFFECT] ON [dbo].[PRMOFFSETEFFECT] ([GDGID], [VDRGID], [STOREGID], [QPCSTR], [START], [FINISH]) ON [PRIMARY]
GO
