CREATE TABLE [dbo].[CNTRPREPAY]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VENDOR] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__CNTRPREPAY__STAT__6BF21EE5] DEFAULT (0),
[PAYER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[VDRRCVER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[OCRDATE] [datetime] NOT NULL,
[NOTE] [char] (255) COLLATE Chinese_PRC_CI_AS NULL,
[DEPT] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[PSR] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CNTRPREPA__TOTAL__6CE6431E] DEFAULT (0),
[TOTALOFF] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CNTRPREPA__TOTAL__6DDA6757] DEFAULT (0),
[CHKFLAG] [smallint] NOT NULL CONSTRAINT [DF__CNTRPREPA__CHKFL__6ECE8B90] DEFAULT (0),
[PAYFLAG] [smallint] NOT NULL CONSTRAINT [DF__CNTRPREPA__PAYFL__6FC2AFC9] DEFAULT (1),
[ABOLISHRESON] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SETTLEACCOUNTNO] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[CLECENT] [int] NULL,
[SNDTIME] [datetime] NULL,
[SRC] [int] NOT NULL CONSTRAINT [DF__CNTRPREPAY__SRC__4A9E7A17] DEFAULT (0),
[BRAND] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SORT] [varchar] (13) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CNTRPREPAY] ADD CONSTRAINT [PK__CNTRPREPAY__70B6D402] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
