CREATE TABLE [dbo].[CRMSCOREADJCAUSE]
(
[CODE] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ADJVALUE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMSCOREA__ADJVA__36F446C1] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMSCOREADJCAUSE] ADD CONSTRAINT [PK__CRMSCOREADJCAUSE__37E86AFA] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
