CREATE TABLE [dbo].[NCTCHGDATASRC]
(
[CODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DSCODE] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCTCHGDATASRC] ADD CONSTRAINT [PK__NCTCHGDATASRC__18FC318B] PRIMARY KEY CLUSTERED  ([SRC], [ID], [CODE], [DSCODE]) ON [PRIMARY]
GO
