CREATE TABLE [dbo].[FAREGISTER]
(
[FKEY] [varchar] (500) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [int] NOT NULL,
[CAPTION] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FVALUE] [char] (500) COLLATE Chinese_PRC_CI_AS NULL,
[FTYPE] [smallint] NOT NULL CONSTRAINT [DF__FAREGISTE__FTYPE__23A311D9] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FAREGISTER] ADD CONSTRAINT [PK__FAREGISTER__24973612] PRIMARY KEY CLUSTERED  ([FKEY], [CAPTION]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FAREGISTER] ADD CONSTRAINT [UK_FAREGISTER] UNIQUE NONCLUSTERED  ([FKEY], [ITEMNO], [FTYPE]) ON [PRIMARY]
GO
