CREATE TABLE [dbo].[RTLPRCADJ]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__RTLPRCADJ__FILDA__18F9042F] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__RTLPRCADJ__STAT__19ED2868] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__RTLPRCADJ__RECCN__1AE14CA1] DEFAULT (0),
[LAUNCH] [datetime] NULL,
[EON] [smallint] NOT NULL CONSTRAINT [DF__RTLPRCADJ__EON__1BD570DA] DEFAULT (1),
[SRC] [int] NOT NULL CONSTRAINT [DF__RTLPRCADJ__SRC__1CC99513] DEFAULT (1),
[SRCNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[WRH] [int] NULL,
[LSTUPDTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RTLPRCADJ] ADD CONSTRAINT [PK__RTLPRCADJ__1804DFF6] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [INDEX_RTLPRCADJ_FILDATE] ON [dbo].[RTLPRCADJ] ([FILDATE]) ON [PRIMARY]
GO
