CREATE TABLE [dbo].[NPRMOFFSETDEBIT]
(
[GDGID] [int] NOT NULL,
[STORE] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[DATE] [datetime] NOT NULL,
[SAMT] [decimal] (24, 2) NOT NULL,
[SQTY] [decimal] (24, 4) NOT NULL,
[RECAL] [int] NOT NULL CONSTRAINT [DF__NPRMOFFSE__RECAL__5E271B2E] DEFAULT (0),
[NSTAT] [smallint] NOT NULL CONSTRAINT [DF__NPRMOFFSE__NSTAT__5F1B3F67] DEFAULT (0),
[NNOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[RCV] [int] NOT NULL,
[SNDTIME] [datetime] NOT NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPRMOFFSETDEBIT] ADD CONSTRAINT [PK__NPRMOFFSETDEBIT__600F63A0] PRIMARY KEY CLUSTERED  ([GDGID], [STORE], [DATE]) ON [PRIMARY]
GO
