CREATE TABLE [dbo].[NPAYRATEPRM]
(
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LASTMODIFIER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NPAYRATEP__LASTM__0103E112] DEFAULT ('未知[-]'),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__NPAYRATEP__LSTUP__01F8054B] DEFAULT (getdate()),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NPAYRATEP__FILDA__02EC2984] DEFAULT (getdate()),
[FILLER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NPAYRATEP__FILLE__03E04DBD] DEFAULT ('未知[-]'),
[CHECKER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__NPAYRATEP__RECCN__04D471F6] DEFAULT (0),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__NPAYRATEPR__STAT__05C8962F] DEFAULT (0),
[LAUNCH] [datetime] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[RCV] [int] NOT NULL,
[SNDTIME] [datetime] NULL,
[RCVTIME] [datetime] NULL,
[FRCCHK] [smallint] NOT NULL,
[TYPE] [smallint] NOT NULL,
[PSETTLENO] [int] NULL,
[TOPIC] [char] (10) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPAYRATEPRM] ADD CONSTRAINT [PK__NPAYRATEPRM__06BCBA68] PRIMARY KEY CLUSTERED  ([ID], [SRC]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPAYRATEPRM_TYPE] ON [dbo].[NPAYRATEPRM] ([TYPE]) ON [PRIMARY]
GO
