CREATE TABLE [dbo].[EMPSALETASKDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CASHIER] [int] NOT NULL,
[TOTAL] [money] NOT NULL CONSTRAINT [DF__EMPSALETA__TOTAL__6B6B3C5C] DEFAULT (0),
[GROSSRATE] [money] NOT NULL CONSTRAINT [DF__EMPSALETA__GROSS__6C5F6095] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[CALCTOTAL] [money] NOT NULL CONSTRAINT [DF__EMPSALETA__CALCT__602F5F31] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMPSALETASKDTL] ADD CONSTRAINT [PK__EMPSALETASKDTL__6D5384CE] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
