CREATE TABLE [dbo].[rb_BUY21]
(
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[FAVTYPE] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FAVAMT] [money] NOT NULL CONSTRAINT [DF__rb_BUY21__FAVAMT__350CC9A6] DEFAULT (0),
[TAG] [smallint] NOT NULL CONSTRAINT [DF__rb_BUY21__TAG__3600EDDF] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[rb_BUY21] ADD CONSTRAINT [PK__rb_BUY21__3418A56D] PRIMARY KEY CLUSTERED  ([POSNO], [FLOWNO], [ITEMNO], [FAVTYPE]) ON [PRIMARY]
GO
