CREATE TABLE [dbo].[DISRATEAGMINV]
(
[STORE] [int] NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[DEPT] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VENDOR] [int] NULL,
[BRAND] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[DISPAYRATE] [decimal] (24, 4) NOT NULL,
[ASTART] [datetime] NOT NULL,
[AFINISH] [datetime] NOT NULL,
[STARTDIS] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__DISRATEAG__START__6E48745E] DEFAULT (0),
[FINISHDIS] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__DISRATEAG__FINIS__6F3C9897] DEFAULT (100)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DISRATEAGMINV] ADD CONSTRAINT [PK__DISRATEAGMINV__7030BCD0] PRIMARY KEY CLUSTERED  ([STORE], [CLS], [NUM], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_DISRATEAGMINV_DEPT] ON [dbo].[DISRATEAGMINV] ([DEPT]) ON [PRIMARY]
GO
