CREATE TABLE [dbo].[BL_MONTHSETTLE]
(
[ASETTLENO] [int] NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BL_MONTHSETTLE] ADD CONSTRAINT [PK__BL_MONTHSETTLE__65CCCF36] PRIMARY KEY CLUSTERED  ([ASETTLENO], [CLS]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
