CREATE TABLE [dbo].[DISTNOTIFYDTL]
(
[SETTLENO] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[CASES] [money] NULL,
[SHOULDQTY] [money] NOT NULL,
[REALQTY] [money] NOT NULL CONSTRAINT [DF__DISTNOTIF__REALQ__7FAD6821] DEFAULT (0),
[CHKINPRC] [money] NOT NULL CONSTRAINT [DF__DISTNOTIF__CHKIN__00A18C5A] DEFAULT (0),
[CHKRTLPRC] [money] NOT NULL CONSTRAINT [DF__DISTNOTIF__CHKRT__0195B093] DEFAULT (0),
[OUTINPRC] [money] NOT NULL CONSTRAINT [DF__DISTNOTIF__OUTIN__0289D4CC] DEFAULT (0),
[OUTRTLPRC] [money] NOT NULL CONSTRAINT [DF__DISTNOTIF__OUTRT__037DF905] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DISTNOTIFYDTL] ADD CONSTRAINT [实配数必须不大于应配数] CHECK (([REALQTY]<=[SHOULDQTY]))
GO
ALTER TABLE [dbo].[DISTNOTIFYDTL] ADD CONSTRAINT [PK__DISTNOTIFYDTL__7EB943E8] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [distnotifydtl_gdgid] ON [dbo].[DISTNOTIFYDTL] ([GDGID]) ON [PRIMARY]
GO
