CREATE TABLE [dbo].[NSTKINBCKDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NULL,
[CASES] [money] NULL,
[QTY] [money] NULL,
[PRICE] [money] NULL,
[TOTAL] [money] NULL,
[TAX] [money] NULL,
[VALIDDATE] [datetime] NULL,
[WRH] [int] NULL CONSTRAINT [DF__NSTKINBCKDT__WRH__487B981A] DEFAULT (1),
[SUBWRH] [int] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[COST] [money] NOT NULL CONSTRAINT [DF__NSTKINBCKD__COST__5EE0A5DC] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NSTKINBCKDTL] ADD CONSTRAINT [PK__NSTKINBCKDTL__4CC05EF3] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
