CREATE TABLE [dbo].[PAYRATEPRMLACDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAYRATEPRMLACDTL] ADD CONSTRAINT [PK__PAYRATEPRMLACDTL__749E0A2D] PRIMARY KEY CLUSTERED  ([NUM], [STOREGID]) ON [PRIMARY]
GO
