CREATE TABLE [dbo].[CQNSTKINDTL]
(
[GROUPID] [int] NOT NULL,
[RHQUUID] [char] (32) COLLATE Chinese_PRC_CI_AS NULL,
[NTYPE] [int] NOT NULL,
[NSTAT] [int] NOT NULL CONSTRAINT [DF__CQNSTKIND__NSTAT__78D7E40E] DEFAULT (0),
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[EXTIME] [datetime] NOT NULL CONSTRAINT [DF__CQNSTKIND__EXTIM__79CC0847] DEFAULT (getdate()),
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CQNSTKINDTL__CLS__7AC02C80] DEFAULT ('自营'),
[SETTLENO] [int] NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[CASES] [decimal] (24, 4) NULL,
[QTY] [decimal] (24, 4) NOT NULL,
[LOSS] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNSTKINDT__LOSS__7BB450B9] DEFAULT (0),
[PRICE] [decimal] (24, 4) NOT NULL,
[TOTAL] [decimal] (24, 4) NOT NULL,
[TAX] [decimal] (24, 4) NOT NULL,
[VALIDDATE] [datetime] NULL,
[WRH] [int] NOT NULL CONSTRAINT [DF__CQNSTKINDTL__WRH__7CA874F2] DEFAULT (1),
[BCKQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNSTKIND__BCKQT__7D9C992B] DEFAULT (0),
[PAYQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNSTKIND__PAYQT__7E90BD64] DEFAULT (0),
[INPRC] [decimal] (24, 4) NOT NULL,
[RTLPRC] [decimal] (24, 4) NOT NULL,
[PAYAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNSTKIND__PAYAM__7F84E19D] DEFAULT (0),
[BCKAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNSTKIND__BCKAM__007905D6] DEFAULT (0),
[BNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SUBWRH] [int] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[ORDLINE] [int] NOT NULL CONSTRAINT [DF__CQNSTKIND__ORDLI__016D2A0F] DEFAULT (0),
[SNEWFLAG] [int] NOT NULL CONSTRAINT [DF__CQNSTKIND__SNEWF__02614E48] DEFAULT (0),
[CHECKOUTFLAG] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CQNSTKINDTL] ADD CONSTRAINT [PK__CQNSTKINDTL__03557281] PRIMARY KEY CLUSTERED  ([GROUPID], [CLS], [NUM], [LINE]) ON [PRIMARY]
GO
