CREATE TABLE [dbo].[INVOICEREVDTL]
(
[UUID] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[INVTAG] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STARTINV] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TERMINALINV] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INVOICEREVDTL] ADD CONSTRAINT [PK__INVOICEREVDTL__6EFBD61E] PRIMARY KEY CLUSTERED  ([UUID], [STARTINV], [TERMINALINV]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[Curdeflt]', N'[dbo].[INVOICEREVDTL].[INVTAG]'
GO
