CREATE TABLE [dbo].[PS3_BASICINFOCHANGELOG]
(
[UUID] [varchar] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TABLENAME] [varchar] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[IUD] [int] NOT NULL CONSTRAINT [DF__PS3_BASICIN__IUD__73FA596F] DEFAULT ((0)),
[KEYNAME] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[KEYVALUE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDOR] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PS3_BASIC__LSTUP__74EE7DA8] DEFAULT ('未知[-]'),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__PS3_BASIC__LSTUP__75E2A1E1] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3_BASICINFOCHANGELOG] ADD CONSTRAINT [PK__PS3_BASI__65A475E777CAEA53] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
