CREATE TABLE [dbo].[LMTPRMLACDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LMTPRMLACDTL] ADD CONSTRAINT [PK__LMTPRMLACDTL__0856F164] PRIMARY KEY CLUSTERED  ([NUM], [STOREGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
