CREATE TABLE [dbo].[PREBUY1]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ASNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TSTIME] [datetime] NULL,
[RCVTIME] [datetime] NULL,
[SNDTIME] [datetime] NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__PREBUY1__STAT__2D99BDC3] DEFAULT (200),
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__PREBUY1__FILDATE__2E8DE1FC] DEFAULT (getdate()),
[CASHIER] [int] NOT NULL CONSTRAINT [DF__PREBUY1__CASHIER__2F820635] DEFAULT (1),
[WRH] [int] NOT NULL CONSTRAINT [DF__PREBUY1__WRH__30762A6E] DEFAULT (1),
[ASSISTANT] [int] NULL,
[TOTAL] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PREBUY1__TOTAL__316A4EA7] DEFAULT (0),
[REALAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PREBUY1__REALAMT__325E72E0] DEFAULT (0),
[PREVAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PREBUY1__PREVAMT__33529719] DEFAULT (0),
[GUEST] [int] NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__PREBUY1__RECCNT__3446BB52] DEFAULT (0),
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[TAG] [smallint] NOT NULL CONSTRAINT [DF__PREBUY1__TAG__353ADF8B] DEFAULT (0),
[INVNO] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SCORE] [decimal] (24, 4) NULL,
[CARDCODE] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[DEALER] [int] NULL,
[FLAG] [int] NOT NULL CONSTRAINT [DF__PREBUY1__FLAG__362F03C4] DEFAULT (0),
[PROCDATE] [datetime] NULL,
[SCOREINFO] [char] (100) COLLATE Chinese_PRC_CI_AS NULL,
[NEWPOSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[NEWFLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NULL,
[ORIGCARDCODE] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[CARDCHNGER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CARDCHNGTIME] [datetime] NULL,
[CARDCHNGREASON] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[ORIGSCORE] [decimal] (24, 4) NULL,
[ORIGSCOREINFO] [char] (100) COLLATE Chinese_PRC_CI_AS NULL,
[CANCELOPER] [int] NULL,
[CANCELDATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PREBUY1] ADD CONSTRAINT [PK__PREBUY1__372327FD] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [UK_PREBUY1_POSFLOWNO] ON [dbo].[PREBUY1] ([POSNO], [FLOWNO]) ON [PRIMARY]
GO
