CREATE TABLE [dbo].[REALEXCHGDATA]
(
[RECVDATE] [datetime] NOT NULL,
[SRC] [int] NOT NULL,
[TGT] [int] NOT NULL,
[RECCNT] [int] NOT NULL,
[LSTSNDTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REALEXCHGDATA] ADD CONSTRAINT [PK__REALEXCHGDATA__004199A7] PRIMARY KEY CLUSTERED  ([RECVDATE], [SRC], [TGT]) ON [PRIMARY]
GO
