CREATE TABLE [dbo].[PRMDIRPAY]
(
[PRMSEQ] [int] NOT NULL,
[PAYNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRMDIRPAY] ADD CONSTRAINT [PK__PRMDIRPAY__7E93EAC0] PRIMARY KEY CLUSTERED  ([PRMSEQ], [PAYNO]) ON [PRIMARY]
GO
