CREATE TABLE [dbo].[INPRCADJDTL]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SETTLENO] [int] NOT NULL,
[STORE] [int] NOT NULL,
[BILL] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLLINE] [smallint] NOT NULL,
[SUBWRH] [int] NOT NULL,
[QTY] [money] NOT NULL,
[INCOST] [money] NULL,
[OUTCOST] [money] NULL,
[AMT] [money] NULL,
[ADJINCOST] [money] NULL,
[ADJOUTCOST] [money] NULL,
[ADJAMT] [money] NULL,
[SRC] [int] NOT NULL,
[LACTIME] [datetime] NULL CONSTRAINT [DF__INPRCADJD__LACTI__0180A1FA] DEFAULT (getdate()),
[BILLSRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[PAYAMT] [money] NOT NULL CONSTRAINT [DF__INPRCADJD__PAYAM__0274C633] DEFAULT (0),
[WRH] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INPRCADJDTL] ADD CONSTRAINT [PK__INPRCADJDTL__75F77EB0] PRIMARY KEY CLUSTERED  ([CLS], [NUM], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [BILLX] ON [dbo].[INPRCADJDTL] ([STORE], [BILL], [BILLCLS], [BILLNUM], [BILLLINE], [CLS], [NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
