CREATE TABLE [dbo].[VOUCHERGIVERULEGOODSOUTDTLOCR]
(
[BILLNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLLINE] [int] NOT NULL,
[GDGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERGIVERULEGOODSOUTDTLOCR] ADD CONSTRAINT [PK__VOUCHERGIVERULEG__3938BAFD] PRIMARY KEY CLUSTERED  ([BILLNUM], [BILLLINE]) ON [PRIMARY]
GO
