CREATE TABLE [dbo].[PSCSSFILEDATA]
(
[UUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL,
[FILENAME] [varchar] (120) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILEUUID] [varchar] (80) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILECAPTION] [varchar] (80) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[LOGTIME] [datetime] NOT NULL CONSTRAINT [DF__PSCSSFILE__LOGTI__44B9ECE1] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSCSSFILEDATA] ADD CONSTRAINT [PK__PSCSSFILEDATA__45AE111A] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
