CREATE TABLE [dbo].[NLTDADJLACDTL]
(
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL,
[SRC] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NLTDADJLACDTL] ADD CONSTRAINT [PK__NLTDADJLACDTL__491C4D46] PRIMARY KEY CLUSTERED  ([SRC], [NUM], [STOREGID], [ID]) ON [PRIMARY]
GO
