CREATE TABLE [dbo].[NPROMFPRC]
(
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__NPROMFPRC__STAT__4DEFE80E] DEFAULT (0),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NPROMFPRC__FILDA__4EE40C47] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__NPROMFPRC__LSTUP__4FD83080] DEFAULT (getdate()),
[TOPIC] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[ASTART] [datetime] NOT NULL,
[AFINISH] [datetime] NOT NULL,
[CYCLE] [datetime] NULL,
[CSTART] [datetime] NULL,
[CFINISH] [datetime] NULL,
[CSPEC] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[PSETTLENO] [int] NULL,
[MONTHSETTLENO] [int] NOT NULL CONSTRAINT [DF__NPROMFPRC__MONTH__50CC54B9] DEFAULT (0),
[OCRTIME] [datetime] NULL,
[SRCNUM] [varchar] (16) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__NPROMFPRC__SRCNU__51C078F2] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPROMFPRC] ADD CONSTRAINT [PK__NPROMFPRC__52B49D2B] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPROMFPRC_TYPE] ON [dbo].[NPROMFPRC] ([TYPE]) ON [PRIMARY]
GO
