CREATE TABLE [dbo].[GOODPAYAPPORT]
(
[FLOWNO] [char] (16) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[GDGid] [int] NOT NULL,
[CURRENCY] [smallint] NOT NULL CONSTRAINT [DF__GOODPAYAP__CURRE__28034203] DEFAULT (0),
[SINGLEAMOUNT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__GOODPAYAP__SINGL__28F7663C] DEFAULT (0),
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__GOODPAYAPPO__QTY__29EB8A75] DEFAULT (0),
[AMOUNT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__GOODPAYAP__AMOUN__2ADFAEAE] DEFAULT (0),
[FAVAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__GOODPAYAP__FAVAM__2BD3D2E7] DEFAULT (0),
[PARVALUE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__GOODPAYAP__PARVA__2CC7F720] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GOODPAYAPPORT] ADD CONSTRAINT [PK__GoodPayApport__2DBC1B59] PRIMARY KEY CLUSTERED  ([FLOWNO], [POSNO], [ITEMNO]) ON [PRIMARY]
GO
