CREATE TABLE [dbo].[ICPAYTYPEDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[PAYTYPE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[AMOUNT] [decimal] (24, 2) NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ICPAYTYPEDTL] ADD CONSTRAINT [PK__ICPAYTYPEDTL__5FAC4391] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
