CREATE TABLE [dbo].[PSCONSSCORE]
(
[UUID] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARDTYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[AMOUNT] [decimal] (24, 2) NOT NULL,
[SCORE] [decimal] (24, 2) NOT NULL,
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL CONSTRAINT [DF__PSCONSSCO__ENDDA__681B6513] DEFAULT ('2099.12.31'),
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSCONSSCORE] ADD CONSTRAINT [PK__PSCONSSCORE__690F894C] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PSCONSSCORE] ON [dbo].[PSCONSSCORE] ([CARDTYPE], [BEGINDATE]) ON [PRIMARY]
GO
