CREATE TABLE [dbo].[结果]
(
[GID] [int] NOT NULL,
[CODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SHORTNAME] [char] (16) COLLATE Chinese_PRC_CI_AS NULL,
[ADDRESS] [char] (60) COLLATE Chinese_PRC_CI_AS NULL,
[TAXNO] [char] (32) COLLATE Chinese_PRC_CI_AS NULL,
[ACCOUNTNO] [char] (64) COLLATE Chinese_PRC_CI_AS NULL,
[FAX] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[ZIP] [char] (6) COLLATE Chinese_PRC_CI_AS NULL,
[TELE] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[CREATEDATE] [datetime] NOT NULL,
[PROPERTY] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[SETTLEACCOUNT] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[PAYTERM] [smallint] NULL,
[MEMO] [char] (255) COLLATE Chinese_PRC_CI_AS NULL,
[LAWREP] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[CONTACTOR] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[CTRPHONE] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[CTRBP] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[SNDTIME] [datetime] NULL,
[LSTUPDTIME] [datetime] NOT NULL,
[FILLER] [int] NOT NULL,
[MODIFIER] [int] NOT NULL,
[KEEPAMT] [money] NOT NULL,
[TAXTYPE] [smallint] NOT NULL,
[EMAILADR] [char] (50) COLLATE Chinese_PRC_CI_AS NULL,
[WWWADR] [char] (50) COLLATE Chinese_PRC_CI_AS NULL,
[CDTRATE] [money] NULL,
[ADFEE] [money] NULL,
[PRMFEE] [money] NULL,
[INVCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[REGFUND] [money] NULL,
[CTRIDCARD] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[VTM] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[OTHERSALEAREA] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[RTLPRCSTYLE] [smallint] NOT NULL,
[RTLPRCRANGE] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[COUNTER] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[COUNTERAREA] [money] NULL,
[VAREA] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[OUTTERWRHAREA] [money] NULL,
[TGTSALEAMT] [money] NULL,
[LWTSALEAMT] [money] NULL,
[DRAWRATE] [money] NULL,
[EQPUSEAMT] [money] NULL,
[ASSISTANTS] [int] NULL,
[CLOTHUSES] [int] NULL,
[ASTSALARY] [money] NULL,
[CREDITS] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[CTRBEGIN] [datetime] NULL,
[CTREND] [datetime] NULL,
[SIGNDATE] [datetime] NULL,
[hizjde] [money] NOT NULL,
[lowzjde] [money] NOT NULL,
[days] [int] NOT NULL,
[PAYCLS] [smallint] NULL,
[MVDR] [int] NOT NULL,
[ISUSETOKEN] [smallint] NOT NULL,
[SAFEAMT] [money] NULL,
[PAYLIMITED] [char] (2) COLLATE Chinese_PRC_CI_AS NULL,
[SendArea] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[PayType] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[upay] [int] NOT NULL,
[UPCTRL] [int] NOT NULL,
[SendType] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[SendLocation] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[BckCycleType] [int] NULL,
[BckBgnMon] [int] NULL,
[BckBgnDays] [int] NULL,
[BckBgnAmt] [money] NULL,
[BckExpRate] [money] NULL,
[BckExpDays] [int] NULL,
[BckLmt] [int] NOT NULL,
[MinDlvQty] [money] NULL,
[MinDlvAmt] [money] NULL,
[OrderLmt] [decimal] (24, 2) NULL
) ON [PRIMARY]
GO
