CREATE TABLE [dbo].[STKBCKIN]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[INNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[INLINE] [smallint] NULL,
[BCKNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[BCKLINE] [smallint] NULL,
[QTY] [money] NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_1] ON [dbo].[STKBCKIN] ([CLS], [INNUM], [INLINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
