CREATE TABLE [dbo].[BUY21]
(
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[FAVTYPE] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NULL,
[FAVAMT] [money] NULL CONSTRAINT [DF__BUY21__FAVAMT__1C680BB2] DEFAULT (0),
[TAG] [smallint] NULL CONSTRAINT [DF__BUY21__TAG__1D5C2FEB] DEFAULT (0),
[PROMNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[PROMCLS] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL,
[PROMLVL] [int] NULL,
[PROMGDCNT] [int] NULL,
[LSTUPDTIME] [datetime] NULL,
[PROMQTY] [decimal] (24, 4) NULL,
[PROMAMT] [decimal] (24, 2) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BUY21] ADD CONSTRAINT [PK__BUY21__1F2E9E6D] PRIMARY KEY CLUSTERED  ([POSNO], [FLOWNO], [ITEMNO], [FAVTYPE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
