CREATE TABLE [dbo].[RTLINVDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[INVQTY] [money] NULL,
[INVAMT] [money] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RTLINVDTL] ADD CONSTRAINT [PK__RTLINVDTL__40FCD3E8] PRIMARY KEY CLUSTERED  ([NUM], [POSNO], [FLOWNO], [ITEMNO]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
