CREATE TABLE [dbo].[BILLTOADJDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[OBILLTO] [int] NOT NULL,
[NBILLTO] [int] NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BILLTOADJDTL] ADD CONSTRAINT [PK__BILLTOADJDTL__585AC9ED] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
