CREATE TABLE [dbo].[CRMCARD]
(
[CARDNUM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BYTIME] [datetime] NOT NULL CONSTRAINT [DF__CRMCARD__BYTIME__72FF0F27] DEFAULT ('2001.1.1'),
[CARDTYPE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARRIER] [int] NOT NULL CONSTRAINT [DF__CRMCARD__CARRIER__73F33360] DEFAULT (1),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__CRMCARD__STAT__74E75799] DEFAULT (0),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__CRMCARD__LSTUPDT__75DB7BD2] DEFAULT (getdate()),
[VERSION] [varchar] (9) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMCARD__VERSION__76CFA00B] DEFAULT ('020000000'),
[MAKETIME] [datetime] NOT NULL,
[SNDTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMCARD] ADD CONSTRAINT [PK__CRMCARD__77C3C444] PRIMARY KEY CLUSTERED  ([CARDNUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_CRMCARD_LST] ON [dbo].[CRMCARD] ([LSTUPDTIME]) ON [PRIMARY]
GO
