CREATE TABLE [dbo].[REALEXCHGDATADTL]
(
[RECVDATE] [datetime] NOT NULL,
[SRC] [int] NOT NULL,
[TGT] [int] NOT NULL,
[CLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHECKINT1] [int] NOT NULL CONSTRAINT [DF__REALEXCHG__CHECK__031E0652] DEFAULT (0),
[CHECKINT2] [int] NOT NULL CONSTRAINT [DF__REALEXCHG__CHECK__04122A8B] DEFAULT (0),
[CHECKINT3] [int] NOT NULL CONSTRAINT [DF__REALEXCHG__CHECK__05064EC4] DEFAULT (0),
[CHECKDATA1] [decimal] (20, 2) NOT NULL CONSTRAINT [DF__REALEXCHG__CHECK__05FA72FD] DEFAULT (0),
[CHECKDATA2] [decimal] (20, 2) NOT NULL CONSTRAINT [DF__REALEXCHG__CHECK__06EE9736] DEFAULT (0),
[CHECKDATA3] [decimal] (20, 2) NOT NULL CONSTRAINT [DF__REALEXCHG__CHECK__07E2BB6F] DEFAULT (0),
[FINISHED] [int] NOT NULL CONSTRAINT [DF__REALEXCHG__FINIS__08D6DFA8] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REALEXCHGDATADTL] ADD CONSTRAINT [PK__REALEXCHGDATADTL__0229E219] PRIMARY KEY CLUSTERED  ([RECVDATE], [SRC], [TGT], [CLS], [NUM]) ON [PRIMARY]
GO
