CREATE TABLE [dbo].[PSMKTIVGTOBJ]
(
[CODE] [varchar] (6) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[TYPECODE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TYPENAME] [char] (50) COLLATE Chinese_PRC_CI_AS NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__PSMKTIVGTO__STAT__22034B7C] DEFAULT (0),
[CREATOR] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CREATETIME] [datetime] NULL CONSTRAINT [DF__PSMKTIVGT__CREAT__22F76FB5] DEFAULT (getdate()),
[SNDTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSMKTIVGTOBJ] ADD CONSTRAINT [PK__PSMKTIVGTOBJ__210F2743] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
