CREATE TABLE [dbo].[CRMFGGDPRIZEBOOK]
(
[UUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARDNUM] [varchar] (16) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STATUS] [smallint] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__CRMFGGDPR__FILDA__5A8C5FCB] DEFAULT (getdate()),
[HSTNUM] [varchar] (26) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMFGGDPR__HSTNU__5B808404] DEFAULT ('-'),
[STORE] [int] NOT NULL,
[POSNO] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLOWNO] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[CHECKDATA] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[RANDOMNUM] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[TRANSUUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMFGGDPR__TRANS__5C74A83D] DEFAULT ('-'),
[TRANSRANDOMNUM] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NULL CONSTRAINT [DF__CRMFGGDPR__LSTUP__5D68CC76] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMFGGDPRIZEBOOK] ADD CONSTRAINT [PK__CRMFGGDPRIZEBOOK__5E5CF0AF] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
