CREATE TABLE [dbo].[SCOREINV]
(
[STORE] [int] NOT NULL,
[CARRIER] [int] NOT NULL,
[SCORE] [money] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SCOREINV] ADD CONSTRAINT [PK__SCOREINV__1BE81D6E] PRIMARY KEY CLUSTERED  ([STORE], [CARRIER]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
