CREATE TABLE [dbo].[FATEMPLATEPARAMETER]
(
[TEMPLATEID] [varchar] (38) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VALUE] [varchar] (256) COLLATE Chinese_PRC_CI_AS NULL,
[MEMO] [varchar] (256) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FATEMPLATEPARAMETER] ADD CONSTRAINT [PK__FATEMPLATEPARAME__452EEE2D] PRIMARY KEY CLUSTERED  ([TEMPLATEID], [NAME]) ON [PRIMARY]
GO
