CREATE TABLE [dbo].[RTLBCKDTL2]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SUBWRH] [int] NOT NULL,
[WRH] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[QTY] [money] NOT NULL CONSTRAINT [DF__RTLBCKDTL2__QTY__33F647D7] DEFAULT (0),
[COST] [money] NOT NULL CONSTRAINT [DF__RTLBCKDTL2__COST__34EA6C10] DEFAULT (0),
[COSTADJ] [money] NOT NULL CONSTRAINT [DF__RTLBCKDTL__COSTA__35DE9049] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RTLBCKDTL2] ADD CONSTRAINT [PK__RTLBCKDTL2__3302239E] PRIMARY KEY CLUSTERED  ([SUBWRH], [NUM], [LINE]) ON [PRIMARY]
GO
