CREATE TABLE [dbo].[PSMKTIVGTOBJPROP]
(
[PROPCODE] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PROPNAME] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OBJCODE] [varchar] (6) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OBJNAME] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VALUE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSMKTIVGTOBJPROP] ADD CONSTRAINT [PK__PSMKTIVGTOBJPROP__28F10B84] PRIMARY KEY CLUSTERED  ([OBJCODE], [PROPCODE]) ON [PRIMARY]
GO
