CREATE TABLE [dbo].[CHGBOOKLOG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CHGBOOKLOG] ADD CONSTRAINT [PK__CHGBOOKLOG__5F8C4800] PRIMARY KEY CLUSTERED  ([NUM], [TIME], [STAT]) ON [PRIMARY]
GO
