CREATE TABLE [dbo].[ALCADJ]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__ALCADJ__FILDATE__5B9D5239] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[STAT] [smallint] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__ALCADJ__RECCNT__5C917672] DEFAULT (0),
[LAUNCH] [datetime] NULL,
[EON] [smallint] NOT NULL CONSTRAINT [DF__ALCADJ__EON__5D859AAB] DEFAULT (0),
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__ALCADJ__LSTUPDTI__5E79BEE4] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ALCADJ] ADD CONSTRAINT [PK__ALCADJ__5F6DE31D] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [LTDADJ_FILDATE] ON [dbo].[ALCADJ] ([FILDATE]) ON [PRIMARY]
GO
