CREATE TABLE [dbo].[CRMCHECKICBALANCELOG]
(
[STORE] [int] NOT NULL,
[OPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARDNUM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OPERTIME] [datetime] NOT NULL CONSTRAINT [DF__CRMCHECKI__OPERT__611F8AB7] DEFAULT (getdate()),
[CHECKMONEY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCHECKI__CHECK__6213AEF0] DEFAULT (0),
[BALANCE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCHECKI__BALAN__6307D329] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
