CREATE TABLE [dbo].[ONLINESALEBCKORDDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[GDCODE] [char] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDNAME] [char] (100) COLLATE Chinese_PRC_CI_AS NULL,
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__ONLINESALEB__QTY__35D23E6D] DEFAULT (0),
[PRICE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__ONLINESAL__PRICE__36C662A6] DEFAULT (0),
[REALAMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__ONLINESAL__REALA__37BA86DF] DEFAULT (0),
[TOTAL] [decimal] (24, 2) NOT NULL,
[SCORE] [decimal] (24, 4) NULL CONSTRAINT [DF__ONLINESAL__SCORE__38AEAB18] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ONLINESALEBCKORDDTL] ADD CONSTRAINT [PK__ONLINESALEBCKORD__39A2CF51] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
