CREATE TABLE [dbo].[EXGREG]
(
[CODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[FUNDLL] [varchar] (40) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EXGREG] ADD CONSTRAINT [PK__EXGREG__45CADF4F] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
