CREATE TABLE [dbo].[NPS3SPECSCOPESCOREPROMSUBJOUTDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[SUBJCODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SUBJCLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPS3SPECSCOPESCOREPROMSUBJOUTDTL] ADD CONSTRAINT [PK__NPS3SPECSCOPESCO__08FD35F1] PRIMARY KEY CLUSTERED  ([SRC], [ID], [NUM], [CLS], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPS3SPECSCOPESCOREPROMSUBJOUTDTL_1] ON [dbo].[NPS3SPECSCOPESCOREPROMSUBJOUTDTL] ([NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPS3SPECSCOPESCOREPROMSUBJOUTDTL_2] ON [dbo].[NPS3SPECSCOPESCOREPROMSUBJOUTDTL] ([SUBJCODE]) ON [PRIMARY]
GO
