CREATE TABLE [dbo].[NGOODSAPPLAC]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL,
[ID] [int] NOT NULL,
[SRC] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NGOODSAPPLAC] ADD CONSTRAINT [PK__NGOODSAPPLAC__07CE782D] PRIMARY KEY CLUSTERED  ([SRC], [ID], [STOREGID]) ON [PRIMARY]
GO
