CREATE TABLE [dbo].[TMP_IPADTL]
(
[SPID] [smallint] NOT NULL,
[ITEMNO] [int] NOT NULL IDENTITY(1, 1),
[BILL] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[WRH] [int] NOT NULL,
[QTY] [money] NOT NULL,
[ADJFLAG] [char] (3) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLCOST] [money] NOT NULL,
[A_ADJCOST] [money] NOT NULL CONSTRAINT [DF__TMP_IPADT__A_ADJ__4933BDE4] DEFAULT (0),
[ADJCOST] [money] NOT NULL CONSTRAINT [DF__TMP_IPADT__ADJCO__4A27E21D] DEFAULT (0),
[ALCSTORE] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TMP_IPADTL] ADD CONSTRAINT [PK__TMP_IPADTL__483F99AB] PRIMARY KEY CLUSTERED  ([SPID], [ITEMNO]) ON [PRIMARY]
GO
