CREATE TABLE [dbo].[PRMRTNPNTAGMLACSTORE]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRMRTNPNTAGMLACSTORE] ADD CONSTRAINT [PK__PRMRTNPNTAGMLACS__6D7E6D57] PRIMARY KEY CLUSTERED  ([NUM], [STOREGID]) ON [PRIMARY]
GO
