CREATE TABLE [dbo].[NPOLYPRCPRMDTLDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[ITEM] [int] NOT NULL,
[START] [datetime] NOT NULL CONSTRAINT [DF__NPOLYPRCP__START__5142215C] DEFAULT ('1899.12.30 00:00:00'),
[FINISH] [datetime] NOT NULL CONSTRAINT [DF__NPOLYPRCP__FINIS__52364595] DEFAULT ('9999.12.31 23:59:59'),
[RTLPRCDISCNT] [decimal] (5, 2) NOT NULL CONSTRAINT [DF__NPOLYPRCP__RTLPR__532A69CE] DEFAULT (0),
[MBRPRCDISCNT] [decimal] (5, 2) NOT NULL CONSTRAINT [DF__NPOLYPRCP__MBRPR__541E8E07] DEFAULT (0),
[PREC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPOLYPRCPR__PREC__5512B240] DEFAULT (0.01),
[ROUNDTYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NPOLYPRCP__ROUND__5606D679] DEFAULT ('四舍五入')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPOLYPRCPRMDTLDTL] ADD CONSTRAINT [PK__NPOLYPRCPRMDTLDT__56FAFAB2] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE], [ITEM]) ON [PRIMARY]
GO
