CREATE TABLE [dbo].[NBILLTOADJFEEDBCKDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[STOREGID] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__NBILLTOADJ__STAT__7D574472] DEFAULT (0),
[RTNNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NBILLTOADJFEEDBCKDTL] ADD CONSTRAINT [PK__NBILLTOADJFEEDBC__7E4B68AB] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) ON [PRIMARY]
GO
