CREATE TABLE [dbo].[CKINV]
(
[WRH] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[QTY] [money] NULL CONSTRAINT [DF__CKINV__QTY__5F94079C] DEFAULT (0),
[TOTAL] [money] NULL CONSTRAINT [DF__CKINV__TOTAL__60882BD5] DEFAULT (0),
[KEPTDATE] [datetime] NULL CONSTRAINT [DF__CKINV__KEPTDATE__617C500E] DEFAULT (getdate()),
[INPRC] [money] NULL CONSTRAINT [DF__CKINV__INPRC__62707447] DEFAULT (0),
[RTLPRC] [money] NULL CONSTRAINT [DF__CKINV__RTLPRC__63649880] DEFAULT (0),
[INVPRC] [money] NOT NULL CONSTRAINT [DF__CKINV__INVPRC__11A12FD3] DEFAULT (0),
[INVCOST] [money] NOT NULL CONSTRAINT [DF__CKINV__INVCOST__1295540C] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CKINV] ADD CONSTRAINT [PK__CKINV__29AC2CE0] PRIMARY KEY CLUSTERED  ([WRH], [GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
