CREATE TABLE [dbo].[VOUCHERBCKSTGRCVGOODS]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[GDFLAG] [int] NOT NULL CONSTRAINT [DF__VOUCHERBC__GDFLA__123003C2] DEFAULT (0),
[REALAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__VOUCHERBC__REALA__132427FB] DEFAULT (0),
[PRICE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__VOUCHERBC__PRICE__14184C34] DEFAULT (0),
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__VOUCHERBCKS__QTY__150C706D] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[ISCALC] [smallint] NOT NULL CONSTRAINT [DF__VOUCHERBC__ISCAL__74358C87] DEFAULT (0),
[NOMINALAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__VOUCHERBC__NOMIN__7529B0C0] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERBCKSTGRCVGOODS] ADD CONSTRAINT [PK__VOUCHERBCKSTGRCV__160094A6] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [VOUCHERBCKSTGRCVGOODS_GDGID] ON [dbo].[VOUCHERBCKSTGRCVGOODS] ([GDGID]) ON [PRIMARY]
GO
