CREATE TABLE [dbo].[CRMCARDCOSTRETVALUE]
(
[SETTLENO] [int] NOT NULL,
[STOREGID] [int] NOT NULL,
[CARDTYPE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMCARDCO__CARDT__01BCD233] DEFAULT ('IC会员卡'),
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CRMCARDCOST__QTY__02B0F66C] DEFAULT (0),
[AMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCARDCO__AMOUN__03A51AA5] DEFAULT (0),
[SRCBILLNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMCARDCO__SRCBI__04993EDE] DEFAULT ('-'),
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__CRMCARDCO__LSTUP__058D6317] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMCARDCOSTRETVALUE] ADD CONSTRAINT [PK__CRMCARDCOSTRETVA__06818750] PRIMARY KEY CLUSTERED  ([SETTLENO], [STOREGID], [CARDTYPE]) ON [PRIMARY]
GO
