CREATE TABLE [dbo].[POLYLTDADJ]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL,
[OCRTYPE] [smallint] NOT NULL,
[OCRTIME] [datetime] NULL,
[RECCNT] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL,
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHKTIME] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[ATYPE] [smallint] NOT NULL CONSTRAINT [DF__POLYLTDAD__ATYPE__00672499] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[POLYLTDADJ] ADD CONSTRAINT [PK__POLYLTDADJ__6E7D7E88] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
