CREATE TABLE [dbo].[PROMGOODS]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[GDCODE] [varchar] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[RTLPRC] [decimal] (24, 4) NOT NULL,
[MBRPRC] [decimal] (24, 4) NULL,
[CNTRINPRC] [decimal] (24, 4) NOT NULL,
[COST] [decimal] (24, 4) NOT NULL,
[QPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PROMGOODS__QPC__4390BE7E] DEFAULT (1),
[QPCSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PRMDIV1] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PROMGOODS__PRMDI__4484E2B7] DEFAULT (100),
[PRMDIV2] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PROMGOODS__PRMDI__457906F0] DEFAULT (0),
[PRMDIV3] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PROMGOODS__PRMDI__466D2B29] DEFAULT (0),
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PROMGOODS__QTY__47614F62] DEFAULT (1),
[FLAG] [int] NOT NULL CONSTRAINT [DF__PROMGOODS__FLAG__4855739B] DEFAULT (0),
[ISDLT] [smallint] NOT NULL CONSTRAINT [DF__PROMGOODS__ISDLT__5921A398] DEFAULT (0),
[FLAG2] [smallint] NOT NULL CONSTRAINT [DF__PROMGOODS__FLAG2__281F44E1] DEFAULT (0),
[GDCODE2] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[PREC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PROMGOODS__PREC__581C6979] DEFAULT (1.0),
[ROUNDTYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PROMGOODS__ROUND__59108DB2] DEFAULT ('四舍五入')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROMGOODS] ADD CONSTRAINT [PK__PROMGOODS__494997D4] PRIMARY KEY CLUSTERED  ([NUM], [CLS], [FLAG], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PROMGOODS_GDGID] ON [dbo].[PROMGOODS] ([GDGID]) ON [PRIMARY]
GO
