CREATE TABLE [dbo].[GFTPRMRULEMUTEX]
(
[RCODE] [char] (18) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MUTEXCODE] [char] (18) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GFTPRMRULEMUTEX] ADD CONSTRAINT [PK__GFTPRMRULEMUTEX__74F0ADE3] PRIMARY KEY CLUSTERED  ([RCODE], [MUTEXCODE]) ON [PRIMARY]
GO
