CREATE TABLE [dbo].[VDROUTADJ]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NULL,
[FILDATE] [datetime] NULL,
[FILLER] [int] NULL,
[CHECKER] [int] NULL,
[WRH] [int] NULL,
[STAT] [int] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VDROUTADJ] WITH NOCHECK ADD CONSTRAINT [VDROUTADJ_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[VDROUTADJ] ADD CONSTRAINT [PK__VDROUTADJ__3A6CA48E] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FILDATE] ON [dbo].[VDROUTADJ] ([FILDATE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
