CREATE TABLE [dbo].[CRMPOSWEBRCVDATADRPT]
(
[STORE] [int] NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[RCVDATE] [datetime] NOT NULL,
[RECCOUNT] [int] NOT NULL CONSTRAINT [DF__CRMPOSWEB__RECCO__2B4D89EB] DEFAULT (0),
[PAYTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMPOSWEB__PAYTO__2C41AE24] DEFAULT (0),
[SCOTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMPOSWEB__SCOTO__2D35D25D] DEFAULT (0),
[CHECKED] [smallint] NOT NULL CONSTRAINT [DF__CRMPOSWEB__CHECK__2E29F696] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMPOSWEBRCVDATADRPT] ADD CONSTRAINT [PK__CRMPOSWEBRCVDATA__2F1E1ACF] PRIMARY KEY CLUSTERED  ([STORE], [POSNO], [RCVDATE]) ON [PRIMARY]
GO
