CREATE TABLE [dbo].[VOUCHERGIVERULEGOODSINDTLOCR]
(
[BILLNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLLINE] [int] NOT NULL,
[GDGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERGIVERULEGOODSINDTLOCR] ADD CONSTRAINT [PK__VOUCHERGIVERULEG__3750728B] PRIMARY KEY CLUSTERED  ([BILLNUM], [BILLLINE]) ON [PRIMARY]
GO
