CREATE TABLE [dbo].[CMGDDECFACTOR]
(
[CMCODE] [char] (2) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[DECFACTORCODE] [char] (1) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DECFACTORVAL] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[DECFACTORRATE] [decimal] (24, 2) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CMGDDECFACTOR] ADD CONSTRAINT [PK__CMGDDECFACTOR__35429F27] PRIMARY KEY CLUSTERED  ([CMCODE], [GDGID], [DECFACTORCODE]) ON [PRIMARY]
GO
