CREATE TABLE [dbo].[TMPPROCEXECPOOLCOST]
(
[SPID] [int] NOT NULL,
[PROCTASKNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PSCPGID] [int] NOT NULL,
[PRODGID] [int] NULL,
[PRODQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__TMPPROCEX__PRODQ__039634FA] DEFAULT (0),
[PRODCOSTAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__TMPPROCEX__PRODC__048A5933] DEFAULT (0),
[PRODCOSTPRC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__TMPPROCEX__PRODC__057E7D6C] DEFAULT (0)
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_TMPPROCEXECPOOLCOST_SPID] ON [dbo].[TMPPROCEXECPOOLCOST] ([SPID]) ON [PRIMARY]
GO
