CREATE TABLE [dbo].[PSIVMDTL]
(
[IVCCODE] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[IVCNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDNAME] [char] (120) COLLATE Chinese_PRC_CI_AS NULL,
[SPEC] [char] (120) COLLATE Chinese_PRC_CI_AS NULL,
[MUNIT] [char] (15) COLLATE Chinese_PRC_CI_AS NULL,
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PSIVMDTL__QTY__63B5D752] DEFAULT (0),
[TOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PSIVMDTL__TOTAL__64A9FB8B] DEFAULT (0),
[GDCODE] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[NUM] [char] (20) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PSIVMDTL_CNL] ON [dbo].[PSIVMDTL] ([IVCCODE], [IVCNUM], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PSIVMDTL_NUM] ON [dbo].[PSIVMDTL] ([NUM]) ON [PRIMARY]
GO
