CREATE TABLE [dbo].[PROCTRANSFERDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[QTY] [decimal] (24, 4) NOT NULL,
[DISPATCHPRC] [decimal] (24, 2) NOT NULL,
[TOINVPRC] [decimal] (24, 2) NULL,
[TOQTY] [decimal] (24, 4) NULL,
[FROMINVPRC] [decimal] (24, 2) NULL,
[FROMQTY] [decimal] (24, 4) NULL,
[FROMWRH] [int] NULL,
[TOWRH] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROCTRANSFERDTL] ADD CONSTRAINT [PK__PROCTRANSFERDTL__2259E7E5] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
