CREATE TABLE [dbo].[CQNDIRALCDTL2]
(
[GROUPID] [int] NOT NULL,
[RHQUUID] [char] (32) COLLATE Chinese_PRC_CI_AS NULL,
[NTYPE] [int] NOT NULL,
[NSTAT] [int] NOT NULL CONSTRAINT [DF__CQNDIRALC__NSTAT__4ADC0F34] DEFAULT (0),
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[EXTIME] [datetime] NOT NULL CONSTRAINT [DF__CQNDIRALC__EXTIM__4BD0336D] DEFAULT (getdate()),
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CQNDIRALCDT__CLS__4CC457A6] DEFAULT ('直配'),
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[SUBWRH] [int] NOT NULL,
[WRH] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNDIRALCDT__QTY__4DB87BDF] DEFAULT (0),
[COST] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNDIRALCD__COST__4EACA018] DEFAULT (0),
[COSTADJ] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNDIRALC__COSTA__4FA0C451] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CQNDIRALCDTL2] ADD CONSTRAINT [PK__CQNDIRALCDTL2__5094E88A] PRIMARY KEY CLUSTERED  ([GROUPID], [CLS], [NUM], [LINE], [SUBWRH]) ON [PRIMARY]
GO
