CREATE TABLE [dbo].[PS3_ONLINECNTRGENLOG]
(
[UUID] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PLATFORM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CNTRNO] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GENCNTRNUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GENCNTRVERSION] [int] NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__PS3_ONLIN__LSTUP__28C32769] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3_ONLINECNTRGENLOG] ADD CONSTRAINT [PK__PS3_ONLI__EDB9179D2AAB6FDB] PRIMARY KEY CLUSTERED  ([UUID], [GENCNTRNUM], [GENCNTRVERSION]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_OLCNTRGENBILL_1] ON [dbo].[PS3_ONLINECNTRGENLOG] ([PLATFORM], [CNTRNO], [GENCNTRNUM], [GENCNTRVERSION]) ON [PRIMARY]
GO
