CREATE TABLE [dbo].[PS3_ONLINEORDPAYMENT]
(
[PLATFORM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ORDNO] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CURRENCY] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PAYAMOUNT] [decimal] (24, 2) NOT NULL,
[UUID] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3_ONLINEORDPAYMENT] ADD CONSTRAINT [PK__PS3_OnLineOrdPay__06E2455A] PRIMARY KEY CLUSTERED  ([UUID], [ITEMNO]) ON [PRIMARY]
GO
