CREATE TABLE [dbo].[BUY2]
(
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[SETTLENO] [int] NULL,
[GID] [int] NULL,
[QTY] [money] NULL CONSTRAINT [DF__BUY2__QTY__14C6E9EA] DEFAULT (0),
[INPRC] [money] NULL CONSTRAINT [DF__BUY2__INPRC__15BB0E23] DEFAULT (0),
[PRICE] [money] NULL CONSTRAINT [DF__BUY2__PRICE__16AF325C] DEFAULT (0),
[REALAMT] [money] NULL CONSTRAINT [DF__BUY2__REALAMT__17A35695] DEFAULT (0),
[FAVAMT] [money] NULL CONSTRAINT [DF__BUY2__FAVAMT__18977ACE] DEFAULT (0),
[TAG] [smallint] NULL CONSTRAINT [DF__BUY2__TAG__198B9F07] DEFAULT (0),
[QpcGid] [int] NULL,
[PRMTAG] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[ASSISTANT] [int] NULL,
[WRH] [int] NULL CONSTRAINT [DF__buy2__WRH__46B41690] DEFAULT (1),
[INVNO] [char] (13) COLLATE Chinese_PRC_CI_AS NULL,
[COST] [money] NOT NULL CONSTRAINT [DF__BUY2__COST__33765993] DEFAULT (0),
[DEALER] [int] NULL,
[iqty] [money] NULL,
[gdcode] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[score] [money] NULL,
[SCOREINFO] [char] (100) COLLATE Chinese_PRC_CI_AS NULL,
[GIFTSALE] [smallint] NOT NULL CONSTRAINT [DF__BUY2__GIFTSALE__4F872378] DEFAULT (0),
[LSTUPDTIME] [datetime] NULL,
[PDTDATE] [datetime] NULL,
[DeviceGUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NULL,
[BillNum] [varchar] (32) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BUY2] ADD CONSTRAINT [PK__BUY2__1E3A7A34] PRIMARY KEY CLUSTERED  ([POSNO], [FLOWNO], [ITEMNO]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
