CREATE TABLE [dbo].[CstPayBill]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ASETTLENO] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLIENT] [int] NOT NULL CONSTRAINT [DF__CstPayBil__CLIEN__6A5C7A29] DEFAULT (1),
[OUTNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TOTAL] [money] NOT NULL,
[RCPNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CstPayBill] ADD CONSTRAINT [PK__CstPayBill__696855F0] PRIMARY KEY CLUSTERED  ([ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [cstPayBill_cls_num] ON [dbo].[CstPayBill] ([CLS], [OUTNUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
