CREATE TABLE [dbo].[WORKSTATION]
(
[NO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (32) COLLATE Chinese_PRC_CI_AS NULL,
[COMPUTERNAME] [char] (15) COLLATE Chinese_PRC_CI_AS NULL,
[STYLE] [smallint] NULL CONSTRAINT [DF__WORKSTATI__STYLE__6A7BAA63] DEFAULT (0),
[MEMO] [char] (255) COLLATE Chinese_PRC_CI_AS NULL,
[NPCNT] [int] NULL CONSTRAINT [DF__WORKSTATI__NPCNT__6B6FCE9C] DEFAULT (0),
[NPOPCNT] [int] NULL CONSTRAINT [DF__WORKSTATI__NPOPC__6C63F2D5] DEFAULT (0),
[CNT] [int] NULL CONSTRAINT [DF__WORKSTATION__CNT__6D58170E] DEFAULT (0),
[AMT] [money] NULL CONSTRAINT [DF__WORKSTATION__AMT__6E4C3B47] DEFAULT (0),
[OPCNT] [int] NULL CONSTRAINT [DF__WORKSTATI__OPCNT__6F405F80] DEFAULT (0),
[ERRCNT] [int] NULL CONSTRAINT [DF__WORKSTATI__ERRCN__703483B9] DEFAULT (0),
[RTLPROC] [smallint] NULL CONSTRAINT [DF__WORKSTATI__RTLPR__7128A7F2] DEFAULT (0),
[TODAYCNT] [int] NULL CONSTRAINT [DF__WORKSTATI__TODAY__721CCC2B] DEFAULT (0),
[TODAYAMT] [money] NULL CONSTRAINT [DF__WORKSTATI__TODAY__7310F064] DEFAULT (0),
[storegid] [int] NULL,
[phone] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[syspath] [char] (50) COLLATE Chinese_PRC_CI_AS NULL,
[LASTEXCHANGEDATETIME] [datetime] NULL,
[LASTEXCHANGETIME] [datetime] NULL,
[LICENSE] [char] (32) COLLATE Chinese_PRC_CI_AS NULL,
[IPADDR] [char] (15) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__WORKSTATI__IPADD__09801FC7] DEFAULT ('196.168.0.3'),
[CKTIMEFLAG] [datetime] NULL,
[ISGEN] [smallint] NOT NULL CONSTRAINT [DF__WORKSTATI__ISGEN__58992A61] DEFAULT (0),
[PARADOXDBPATH] [varchar] (4000) COLLATE Chinese_PRC_CI_AS NULL,
[WRHCODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WORKSTATION] ADD CONSTRAINT [PK__WORKSTATION__4301EA8F] PRIMARY KEY CLUSTERED  ([NO]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
