CREATE TABLE [dbo].[CNTR_GENVDRLESSEE]
(
[CNTRNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VERSION] [smallint] NOT NULL,
[CHGCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VDRGID] [int] NOT NULL,
[BUYER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CNTR_GENV__BUYER__276D79CF] DEFAULT ('未知[-]'),
[ORGVISER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[ORIPAYRATE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CNTR_GENV__ORIPA__28619E08] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CNTR_GENVDRLESSEE] ADD CONSTRAINT [PK__CNTR_GENVDRLESSE__2955C241] PRIMARY KEY CLUSTERED  ([CNTRNUM], [VERSION], [CHGCODE], [VDRGID]) ON [PRIMARY]
GO
