CREATE TABLE [dbo].[PREBUY2]
(
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[SETTLENO] [int] NOT NULL,
[GID] [int] NOT NULL,
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PREBUY2__QTY__3FB86DFE] DEFAULT (0),
[INPRC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PREBUY2__INPRC__40AC9237] DEFAULT (0),
[PRICE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PREBUY2__PRICE__41A0B670] DEFAULT (0),
[REALAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PREBUY2__REALAMT__4294DAA9] DEFAULT (0),
[FAVAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PREBUY2__FAVAMT__4388FEE2] DEFAULT (0),
[TAG] [smallint] NOT NULL CONSTRAINT [DF__PREBUY2__TAG__447D231B] DEFAULT (0),
[QPCGID] [int] NULL,
[PRMTAG] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[ASSISTANT] [int] NULL,
[WRH] [int] NULL CONSTRAINT [DF__PREBUY2__WRH__45714754] DEFAULT (1),
[INVNO] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[COST] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PREBUY2__COST__46656B8D] DEFAULT (0),
[DEALER] [int] NULL,
[IQTY] [decimal] (24, 2) NULL,
[GDCODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[SCRPRICE] [decimal] (24, 4) NULL,
[SCRFAVRATE] [decimal] (24, 4) NULL,
[LSTUPDTIME] [datetime] NULL,
[PDTDATE] [datetime] NULL,
[SCOREINFO] [char] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SCORE] [decimal] (24, 4) NULL,
[ORIGSCORE] [decimal] (24, 4) NULL,
[ORIGSCOREINFO] [char] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PREBUY2] ADD CONSTRAINT [PK__PREBUY2__47598FC6] PRIMARY KEY CLUSTERED  ([FLOWNO], [POSNO], [ITEMNO]) ON [PRIMARY]
GO
