CREATE TABLE [dbo].[VOUCHERSELLDTL2]
(
[NUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SCOPEFLAG] [smallint] NOT NULL,
[SCOPECODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SCOPENAME] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERSELLDTL2] ADD CONSTRAINT [PK__VOUCHERSELLDTL2__58F851BD] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_VOUCHERSELLDTL2_NUMLINE] ON [dbo].[VOUCHERSELLDTL2] ([NUM], [LINE]) ON [PRIMARY]
GO
