CREATE TABLE [dbo].[FAFLOWOBJ]
(
[UUID] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [int] NOT NULL,
[FLEFT] [int] NOT NULL,
[FTOP] [int] NOT NULL,
[FWIDTH] [int] NOT NULL,
[FHEIGHT] [int] NOT NULL,
[FEDGE] [int] NOT NULL,
[FBORDER] [int] NOT NULL,
[FHTPOS] [int] NOT NULL,
[FVTPOS] [int] NOT NULL,
[FHIPOS] [int] NOT NULL,
[FVIPOS] [int] NOT NULL,
[FBKCOLOR] [int] NOT NULL,
[FSHCOLOR] [int] NOT NULL,
[FTAG] [int] NOT NULL CONSTRAINT [DF__FAFLOWOBJ__FTAG__1C2CD89A] DEFAULT (0),
[FOBJCNT] [int] NOT NULL CONSTRAINT [DF__FAFLOWOBJ__FOBJC__1D20FCD3] DEFAULT (0),
[FIMAGE] [int] NOT NULL CONSTRAINT [DF__FAFLOWOBJ__FIMAG__1E15210C] DEFAULT (0),
[FSHAPE] [int] NOT NULL,
[FSHWIDTH] [int] NOT NULL,
[FPARFONT] [int] NOT NULL CONSTRAINT [DF__FAFLOWOBJ__FPARF__1F094545] DEFAULT (0),
[FTRANSPARENT] [int] NOT NULL CONSTRAINT [DF__FAFLOWOBJ__FTRAN__1FFD697E] DEFAULT (0),
[FTEXT] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[FCUSTOMDATA] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[MODULETYPE] [int] NOT NULL CONSTRAINT [DF__FAFLOWOBJ__MODUL__20F18DB7] DEFAULT (0),
[MODULEID] [varchar] (128) COLLATE Chinese_PRC_CI_AS NULL,
[MODULENOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (1024) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FAFLOWOBJ] ADD CONSTRAINT [PK__FAFLOWOBJ__21E5B1F0] PRIMARY KEY CLUSTERED  ([UUID], [ITEMNO]) ON [PRIMARY]
GO
