CREATE TABLE [dbo].[MOUTDRPT]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[BGDGID] [int] NOT NULL,
[DQ1] [money] NULL CONSTRAINT [DF__MOUTDRPT__DQ1__5FD3FEBE] DEFAULT (0),
[DQ5] [money] NULL CONSTRAINT [DF__MOUTDRPT__DQ5__60C822F7] DEFAULT (0),
[DT1] [money] NULL CONSTRAINT [DF__MOUTDRPT__DT1__61BC4730] DEFAULT (0),
[DT5] [money] NULL CONSTRAINT [DF__MOUTDRPT__DT5__62B06B69] DEFAULT (0),
[DT92] [money] NULL CONSTRAINT [DF__MOUTDRPT__DT92__63A48FA2] DEFAULT (0),
[DI1] [money] NULL CONSTRAINT [DF__MOUTDRPT__DI1__6498B3DB] DEFAULT (0),
[DI5] [money] NULL CONSTRAINT [DF__MOUTDRPT__DI5__658CD814] DEFAULT (0),
[DR1] [money] NULL CONSTRAINT [DF__MOUTDRPT__DR1__6680FC4D] DEFAULT (0),
[DR5] [money] NULL CONSTRAINT [DF__MOUTDRPT__DR5__67752086] DEFAULT (0),
[FLAG] [int] NULL CONSTRAINT [DF__MOUTDRPT__FLAG__4AEEBBC8] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MOUTDRPT] ADD CONSTRAINT [PK__MOUTDRPT__119F9925] PRIMARY KEY CLUSTERED  ([ASTORE], [ADATE], [BGDGID], [ASETTLENO]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
