CREATE TABLE [dbo].[RGDWRH]
(
[GDGID] [int] NOT NULL,
[WRH] [int] NOT NULL,
[qty] [money] NOT NULL,
[INVPRC] [money] NOT NULL CONSTRAINT [DF__RGDWRH__INVPRC__103A6C53] DEFAULT (0),
[INVCOST] [money] NOT NULL CONSTRAINT [DF__RGDWRH__INVCOST__112E908C] DEFAULT (0),
[FILDATE] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RGDWRH] ADD CONSTRAINT [PK__RGDWRH__0F46481A] PRIMARY KEY CLUSTERED  ([GDGID], [WRH], [FILDATE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [rgdwrh_date] ON [dbo].[RGDWRH] ([FILDATE]) ON [PRIMARY]
GO
