CREATE TABLE [dbo].[SORTSORT]
(
[ACODE] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SCODE] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GID] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__SORTSORT__LSTUPD__62DCEAA0] DEFAULT (getdate()),
[SORTTARGET1] [money] NOT NULL CONSTRAINT [DF__SORTSORT__SORTTA__5876CCCB] DEFAULT ((-1))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SORTSORT] ADD CONSTRAINT [PK__SORTSORT__63D10ED9] PRIMARY KEY CLUSTERED  ([ACODE], [SCODE], [GID]) ON [PRIMARY]
GO
