CREATE TABLE [dbo].[NATIVEPRODUCTGOODS]
(
[GID] [int] NOT NULL,
[TOURGUIDEDIS] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NATIVEPRO__TOURG__111B18A1] DEFAULT (0),
[TOURGUIDESPECDIS] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NATIVEPRO__TOURG__120F3CDA] DEFAULT (0),
[EMPRATE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NATIVEPRO__EMPRA__13036113] DEFAULT (0),
[SHOPGUIDERATE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NATIVEPRO__SHOPG__13F7854C] DEFAULT (0),
[CREATOR] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NATIVEPRO__CREAT__14EBA985] DEFAULT ('未知[-]'),
[CREATETIME] [datetime] NOT NULL CONSTRAINT [DF__NATIVEPRO__CREAT__15DFCDBE] DEFAULT (getdate()),
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NATIVEPRO__LSTUP__16D3F1F7] DEFAULT ('未知[-]'),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__NATIVEPRO__LSTUP__17C81630] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NATIVEPRODUCTGOODS] ADD CONSTRAINT [PK__NATIVEPRODUCTGOO__18BC3A69] PRIMARY KEY CLUSTERED  ([GID]) ON [PRIMARY]
GO
