CREATE TABLE [dbo].[TA_YYFACE]
(
[OPERATCODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PRODUCEDATE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VOUCHERTYPENAME] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TICKETNUMBER] [varchar] (3) COLLATE Chinese_PRC_CI_AS NULL,
[BRIEF] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ACCOUNT] [varchar] (15) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DIRECTION] [varchar] (1) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TOTALMONEY] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[QUANTITY] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[FOREINMONEY] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[RATE] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[SETTLETYPENAME] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[SETTLENO] [varchar] (5) COLLATE Chinese_PRC_CI_AS NULL,
[SETTLEDATE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[DEPARTNAME] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[PERSONNAME] [varchar] (8) COLLATE Chinese_PRC_CI_AS NULL,
[FIRMNAME] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[TICKETCODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[OPERATORNAME] [varchar] (8) COLLATE Chinese_PRC_CI_AS NULL,
[PROJECTNAME] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
