CREATE TABLE [dbo].[TMPALCGFTGOODS]
(
[SPID] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[QTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__TMPALCGFTGO__QTY__265495FB] DEFAULT (0)
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_TMPALCGFTGOODS_SPID] ON [dbo].[TMPALCGFTGOODS] ([SPID]) ON [PRIMARY]
GO
