CREATE TABLE [dbo].[CNTRPREPAYCHKLOG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHKFLAG] [int] NOT NULL,
[OPER] [int] NOT NULL,
[ATIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CNTRPREPAYCHKLOG] ADD CONSTRAINT [PK__CNTRPREPAYCHKLOG__729F1C74] PRIMARY KEY CLUSTERED  ([ATIME], [NUM], [CHKFLAG]) ON [PRIMARY]
GO
