CREATE TABLE [dbo].[NPROCEXEC]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BOCLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NPROCEXEC__BOCLS__4306AE99] DEFAULT ('一般'),
[TASKNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL,
[BGNTIME] [datetime] NULL,
[ENDTIME] [datetime] NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NPROCEXEC__FILDA__43FAD2D2] DEFAULT (getdate()),
[CHKTIME] [datetime] NULL,
[CHKEMP] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[SUBJECT] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[ALGAVGTAG] [varchar] (255) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[SRC] [int] NOT NULL CONSTRAINT [DF__NPROCEXEC__SRC__44EEF70B] DEFAULT (1),
[PRNTIME] [datetime] NULL,
[MODE] [smallint] NOT NULL,
[ID] [int] NOT NULL,
[SNDTIME] [datetime] NOT NULL CONSTRAINT [DF__NPROCEXEC__SNDTI__45E31B44] DEFAULT (getdate()),
[RCV] [int] NULL,
[RCVTIME] [datetime] NULL,
[FRCCHK] [smallint] NOT NULL,
[NTYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [char] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPROCEXEC] ADD CONSTRAINT [PK__NPROCEXEC__46D73F7D] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
