CREATE TABLE [dbo].[PRMBANLAN]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[BGDGID] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[BCSTGID] [int] NOT NULL,
[DQ1] [money] NOT NULL CONSTRAINT [DF__PRMBANLAN__DQ1__4555DE03] DEFAULT (0),
[DQ2] [money] NOT NULL CONSTRAINT [DF__PRMBANLAN__DQ2__464A023C] DEFAULT (0),
[DQ3] [money] NOT NULL CONSTRAINT [DF__PRMBANLAN__DQ3__473E2675] DEFAULT (0),
[DQ4] [money] NOT NULL CONSTRAINT [DF__PRMBANLAN__DQ4__48324AAE] DEFAULT (0),
[DP1] [money] NOT NULL CONSTRAINT [DF__PRMBANLAN__DP1__49266EE7] DEFAULT (0),
[DP2] [money] NOT NULL CONSTRAINT [DF__PRMBANLAN__DP2__4A1A9320] DEFAULT (0),
[DP3] [money] NOT NULL CONSTRAINT [DF__PRMBANLAN__DP3__4B0EB759] DEFAULT (0),
[DP4] [money] NOT NULL CONSTRAINT [DF__PRMBANLAN__DP4__4C02DB92] DEFAULT (0),
[DI1] [money] NOT NULL CONSTRAINT [DF__PRMBANLAN__DI1__4CF6FFCB] DEFAULT (0),
[DI2] [money] NOT NULL CONSTRAINT [DF__PRMBANLAN__DI2__4DEB2404] DEFAULT (0),
[DI3] [money] NOT NULL CONSTRAINT [DF__PRMBANLAN__DI3__4EDF483D] DEFAULT (0),
[DI4] [money] NOT NULL CONSTRAINT [DF__PRMBANLAN__DI4__4FD36C76] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRMBANLAN] ADD CONSTRAINT [PK__PRMBANLAN__4461B9CA] PRIMARY KEY CLUSTERED  ([ADATE], [BGDGID], [BCSTGID], [BWRH], [ASETTLENO], [ASTORE]) ON [PRIMARY]
GO
