CREATE TABLE [dbo].[PS3SPECSCOPESCOREINV]
(
[UUID] [varchar] (36) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DEPT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[VENDOR] [int] NULL,
[SORT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[BRAND] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[MINAMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3SPECSC__MINAM__6064695B] DEFAULT (0),
[AMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3SPECSC__AMOUN__61588D94] DEFAULT (0),
[SCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3SPECSC__SCORE__624CB1CD] DEFAULT (0),
[MAXDISCOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3SPECSC__MAXDI__6340D606] DEFAULT (100),
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[SRCNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PS3SPECSC__SRCNU__31747048] DEFAULT ('-'),
[SRCCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PS3SPECSC__SRCCL__32689481] DEFAULT ('-'),
[SCORESORT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PS3SPECSC__SCORE__0422A6E4] DEFAULT ('-'),
[NSCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3SPECSC__NSCOR__2E18E0B0] DEFAULT (1),
[DISCOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3SPECSC__DISCO__6F884808] DEFAULT (0),
[DISMAXDIS] [decimal] (24, 2) NULL,
[DISPREC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PS3SPECSC__DISPR__707C6C41] DEFAULT (0.01)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3SPECSCOPESCOREINV] ADD CONSTRAINT [PK__PS3SPECSCOPESCOR__6434FA3F] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3SPECSCOPESCOREINV_4] ON [dbo].[PS3SPECSCOPESCOREINV] ([BRAND]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3SPECSCOPESCOREINV_1] ON [dbo].[PS3SPECSCOPESCOREINV] ([DEPT]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3SPECSCOPESCOREINV_3] ON [dbo].[PS3SPECSCOPESCOREINV] ([SORT]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3SPECSCOPESCOREINV_5] ON [dbo].[PS3SPECSCOPESCOREINV] ([SRCNUM], [SRCCLS]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3SPECSCOPESCOREINV_2] ON [dbo].[PS3SPECSCOPESCOREINV] ([VENDOR]) ON [PRIMARY]
GO
