CREATE TABLE [dbo].[NVDRBCKDMD]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[VENDOR] [int] NULL,
[RECCNT] [int] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NVDRBCKDM__FILDA__49122BA5] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHKDATE] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CACLDATE] [datetime] NULL,
[CANCELER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[SNDDATE] [datetime] NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__NVDRBCKDMD__STAT__4A064FDE] DEFAULT (0),
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[NTYPE] [smallint] NOT NULL,
[NSTAT] [int] NOT NULL,
[NNOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__NVDRBCKDM__LSTUP__4AFA7417] DEFAULT (getdate()),
[PSR] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[EXPDATE] [datetime] NULL,
[DMDSTORE] [int] NOT NULL CONSTRAINT [DF__nvdrbckdm__DMDST__5EB75401] DEFAULT ((-1)),
[SRCNUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NULL,
[SRCCLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[BCKCLS] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[BEGINDATE] [datetime] NULL,
[PSRGID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVDRBCKDMD] ADD CONSTRAINT [PK__NVDRBCKDMD__481E076C] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
