CREATE TABLE [dbo].[NPSBRANDSORT]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[BRANDCODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SORTCODE] [varchar] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[AGENTNAME] [varchar] (200) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NPSBRANDS__AGENT__2C392331] DEFAULT ('未知[-]'),
[MANUFACTURENAME] [varchar] (200) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NPSBRANDS__MANUF__2D2D476A] DEFAULT ('未知[-]'),
[CLIENTDESC] [varchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[CLIENTSEX] [int] NOT NULL CONSTRAINT [DF__NPSBRANDS__CLIEN__2E216BA3] DEFAULT (0),
[INTRODUCEEMP] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[INTRODUCEDATE] [datetime] NULL,
[CREATOR] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NPSBRANDS__CREAT__2F158FDC] DEFAULT ('未知[-]'),
[CREATETIME] [datetime] NOT NULL CONSTRAINT [DF__NPSBRANDS__CREAT__3009B415] DEFAULT (getdate()),
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NPSBRANDS__LSTUP__30FDD84E] DEFAULT ('未知[-]'),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__NPSBRANDS__LSTUP__31F1FC87] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPSBRANDSORT] ADD CONSTRAINT [PK__NPSBRANDSORT__32E620C0] PRIMARY KEY CLUSTERED  ([SRC], [ID], [BRANDCODE], [SORTCODE]) ON [PRIMARY]
GO
