CREATE TABLE [dbo].[PAYOUT]
(
[PAYNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PAYLINE] [smallint] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[QTY] [money] NULL,
[PRC] [money] NULL,
[STOTAL] [money] NULL,
[NPQTY] [money] NULL,
[NPSTOTAL] [money] NULL,
[NPTOTAL] [money] NULL,
[TOTAL] [money] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAYOUT] ADD CONSTRAINT [PK__PAYOUT__6B44E613] PRIMARY KEY CLUSTERED  ([PAYNUM], [PAYLINE], [ASETTLENO], [ADATE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
