CREATE TABLE [dbo].[CLIENTPRERCVHST]
(
[CLIENT] [int] NOT NULL,
[ITEMNO] [int] NOT NULL,
[OPERDATE] [datetime] NOT NULL,
[AMT] [money] NOT NULL,
[BALANCE] [money] NOT NULL,
[CLS] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NULL,
[OPER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENTPRERCVHST] ADD CONSTRAINT [PK__CLIENTPRERCVHST__161C9784] PRIMARY KEY CLUSTERED  ([CLIENT], [ITEMNO]) ON [PRIMARY]
GO
