CREATE TABLE [dbo].[RFBILLPOOL]
(
[RFNUM] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILLER] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__RFBILLPOO__RECCN__4ABCDEFA] DEFAULT (0),
[TOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__RFBILLPOO__TOTAL__4BB10333] DEFAULT (0),
[MBRTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__RFBILLPOO__MBRTO__4CA5276C] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RFBILLPOOL] ADD CONSTRAINT [PK__RFBILLPOOL__4D994BA5] PRIMARY KEY CLUSTERED  ([RFNUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_RFBILLPOOL_FILLER] ON [dbo].[RFBILLPOOL] ([FILLER]) ON [PRIMARY]
GO
