CREATE TABLE [dbo].[TAXSORTADJDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[OLDTAXSORT] [int] NULL,
[NEWTAXSORT] [int] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TAXSORTADJDTL] ADD CONSTRAINT [PK__TAXSORTA__91DB7AAD5F2959BB] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
