CREATE TABLE [dbo].[GOODSRECEIPTDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[GDQTY] [decimal] (24, 4) NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[PRDDATE] [datetime] NULL,
[PRICE] [decimal] (24, 4) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GOODSRECEIPTDTL] ADD CONSTRAINT [PK__GOODSRECEIPTDTL__71E65D1D] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [GOODSRECEIPTDTL_GDGID] ON [dbo].[GOODSRECEIPTDTL] ([GDGID]) ON [PRIMARY]
GO
