CREATE TABLE [dbo].[PS3NOTSCOREGDSCOPE]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__PS3NOTSCOR__STAT__2AFC7CE3] DEFAULT (0),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__PS3NOTSCO__FILDA__2BF0A11C] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[CHKDATE] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__PS3NOTSCO__LSTUP__2CE4C555] DEFAULT (getdate()),
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PS3NOTSCO__LSTUP__2DD8E98E] DEFAULT ('未知[-]'),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SETTLENO] [int] NOT NULL CONSTRAINT [DF__PS3NOTSCO__SETTL__2ECD0DC7] DEFAULT (0),
[RECCNT] [int] NOT NULL,
[ABORTDATE] [datetime] NULL,
[ABORTER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3NOTSCOREGDSCOPE] ADD CONSTRAINT [PK__PS3NOTSCOREGDSCO__2FC13200] PRIMARY KEY CLUSTERED  ([NUM], [CLS]) ON [PRIMARY]
GO
