CREATE TABLE [dbo].[TMPSUBJECTSCORE]
(
[spid] [int] NOT NULL,
[SORT] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SUBJECT] [char] (3) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SCORE] [decimal] (24, 2) NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx_TMPSUBJECTSCORE_spid] ON [dbo].[TMPSUBJECTSCORE] ([spid]) ON [PRIMARY]
GO
