CREATE TABLE [dbo].[CMSTOREGRADE]
(
[CODE] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CMCODE] [char] (2) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DISPLAYPICNAME] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[DISPLAYPICNAME2] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[MAXGDCOUNT] [int] NOT NULL CONSTRAINT [DF__CMSTOREGR__MAXGD__213BA67A] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[CREATETIME] [datetime] NOT NULL,
[CREATEOPER] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LASTMODIFYTIME] [datetime] NOT NULL,
[LASTMODIFYOPER] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILE1] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[FILE2] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[FILE2_2] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[DISPLAYPCP] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CMSTOREGRADE] ADD CONSTRAINT [PK__CMSTOREGRADE__222FCAB3] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_CMSTOREGRADE_C] ON [dbo].[CMSTOREGRADE] ([CMCODE]) ON [PRIMARY]
GO
