CREATE TABLE [dbo].[PS3NOTSCOREGDSCOPEDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[DEPT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[VENDOR] [int] NULL,
[SORT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[BRAND] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[GDGID] [int] NULL,
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3NOTSCOREGDSCOPEDTL] ADD CONSTRAINT [PK__PS3NOTSCOREGDSCO__31A97A72] PRIMARY KEY CLUSTERED  ([NUM], [CLS], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3NOTSCOREGDSCOPEDTL_4] ON [dbo].[PS3NOTSCOREGDSCOPEDTL] ([BRAND]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3NOTSCOREGDSCOPEDTL_1] ON [dbo].[PS3NOTSCOREGDSCOPEDTL] ([DEPT]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3NOTSCOREGDSCOPEDTL_5] ON [dbo].[PS3NOTSCOREGDSCOPEDTL] ([GDGID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3NOTSCOREGDSCOPEDTL_3] ON [dbo].[PS3NOTSCOREGDSCOPEDTL] ([SORT]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3NOTSCOREGDSCOPEDTL_2] ON [dbo].[PS3NOTSCOREGDSCOPEDTL] ([VENDOR]) ON [PRIMARY]
GO
