CREATE TABLE [dbo].[OVFDTL2]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SUBWRH] [int] NOT NULL,
[WRH] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[QTY] [money] NOT NULL CONSTRAINT [DF__OVFDTL2__QTY__3C8B8DD8] DEFAULT (0),
[COST] [money] NOT NULL CONSTRAINT [DF__OVFDTL2__COST__3D7FB211] DEFAULT (0),
[COSTADJ] [money] NOT NULL CONSTRAINT [DF__OVFDTL2__COSTADJ__3E73D64A] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OVFDTL2] ADD CONSTRAINT [PK__OVFDTL2__3B97699F] PRIMARY KEY CLUSTERED  ([SUBWRH], [NUM], [LINE]) ON [PRIMARY]
GO
