CREATE TABLE [dbo].[NALCBYSTORE]
(
[ID] [int] NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [smallint] NOT NULL,
[STAT] [smallint] NOT NULL,
[FILLER] [int] NOT NULL CONSTRAINT [DF__NALCBYSTO__FILLE__690D2747] DEFAULT (1),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NALCBYSTO__FILDA__6A014B80] DEFAULT (getdate()),
[CHECKER] [int] NOT NULL CONSTRAINT [DF__NALCBYSTO__CHECK__6AF56FB9] DEFAULT (1),
[DMDDATE] [datetime] NOT NULL,
[TOTAL] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NALCBYSTO__TOTAL__6BE993F2] DEFAULT (0),
[TAX] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NALCBYSTORE__TAX__6CDDB82B] DEFAULT (0),
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NALCBYSTORE__QTY__6DD1DC64] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[CLS] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NALCBYSTORE__CLS__6EC6009D] DEFAULT ('采购配货'),
[SRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[DESRCTYPE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[DESRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[NSTAT] [int] NULL,
[RCV] [int] NULL,
[SRC] [int] NOT NULL,
[TYPE] [smallint] NOT NULL,
[SNDTIME] [datetime] NULL,
[RCVTIME] [datetime] NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NALCBYSTORE] ADD CONSTRAINT [PK__NALCBYSTORE__6FBA24D6] PRIMARY KEY CLUSTERED  ([ID], [SRC]) ON [PRIMARY]
GO
