CREATE TABLE [dbo].[CRMSEND]
(
[NUM] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SENDTOWEB] [smallint] NOT NULL CONSTRAINT [DF__CRMSEND__SENDTOW__229D0C63] DEFAULT (0),
[SYSUUID] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMSEND__SYSUUID__2391309C] DEFAULT ('-'),
[POSNO] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMSEND__POSNO__248554D5] DEFAULT ('-'),
[RCVPOSDATATIME] [datetime] NOT NULL CONSTRAINT [DF__CRMSEND__RCVPOSD__2579790E] DEFAULT (getdate()),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__CRMSEND__LSTUPDT__266D9D47] DEFAULT (getdate()),
[ISONLINE] [smallint] NOT NULL CONSTRAINT [DF__CRMSEND__ISONLIN__1D0FE6ED] DEFAULT (1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMSEND] ADD CONSTRAINT [PK__CRMSEND__2761C180] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_CRMSEND_SENDTOWEB] ON [dbo].[CRMSEND] ([SENDTOWEB]) ON [PRIMARY]
GO
