CREATE TABLE [dbo].[NICBUY11]
(
[STORE] [int] NOT NULL,
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[SETTLENO] [int] NOT NULL,
[CURRENCY] [smallint] NOT NULL CONSTRAINT [DF__NICBUY11__CURREN__4BC2E470] DEFAULT (0),
[AMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NICBUY11__AMOUNT__4CB708A9] DEFAULT (0),
[CARDCODE] [char] (128) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NICBUY11] ADD CONSTRAINT [PK__NICBUY11__4ACEC037] PRIMARY KEY CLUSTERED  ([SRC], [ID], [ITEMNO]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
