CREATE TABLE [dbo].[PSTASKMANDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [int] NOT NULL,
[STAT] [smallint] NOT NULL,
[BGNTIME] [datetime] NOT NULL,
[ENDTIME] [datetime] NOT NULL,
[EXESTAT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PSTASKMAN__EXEST__60571A5E] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSTASKMANDTL] ADD CONSTRAINT [PK__PSTASKMANDTL__614B3E97] PRIMARY KEY CLUSTERED  ([NUM], [ITEMNO]) ON [PRIMARY]
GO
