CREATE TABLE [dbo].[FAGADGETLIST]
(
[MODULEID] [int] NOT NULL,
[GADGETID] [varchar] (38) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TEMPLATEID] [varchar] (38) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FAGADGETLIST] ADD CONSTRAINT [PK__FAGADGETLIST__3BA583F3] PRIMARY KEY CLUSTERED  ([MODULEID], [GADGETID], [TEMPLATEID]) ON [PRIMARY]
GO
