CREATE TABLE [dbo].[KWHMETERRECORDLOG]
(
[KWHMETER] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[YEARMONTH] [char] (6) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MODIFIER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[TIME] [datetime] NULL CONSTRAINT [DF__KWHMETERRE__TIME__6833A108] DEFAULT (getdate())
) ON [PRIMARY]
GO
