CREATE TABLE [dbo].[CSHDRPT]
(
[PosNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ADATE] [datetime] NOT NULL,
[CASHIER] [int] NOT NULL,
[DN1] [int] NULL CONSTRAINT [DF__CSHDRPT__DN1__573EB8BD] DEFAULT (0),
[DN2] [int] NULL CONSTRAINT [DF__CSHDRPT__DN2__5832DCF6] DEFAULT (0),
[DQ1] [money] NULL CONSTRAINT [DF__CSHDRPT__DQ1__5927012F] DEFAULT (0),
[DQ2] [money] NULL CONSTRAINT [DF__CSHDRPT__DQ2__5A1B2568] DEFAULT (0),
[DT1] [money] NULL CONSTRAINT [DF__CSHDRPT__DT1__5B0F49A1] DEFAULT (0),
[DT2] [money] NULL CONSTRAINT [DF__CSHDRPT__DT2__5C036DDA] DEFAULT (0),
[DT3] [money] NULL CONSTRAINT [DF__CSHDRPT__DT3__5CF79213] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CSHDRPT] ADD CONSTRAINT [PK__CSHDRPT__351DDF8C] PRIMARY KEY CLUSTERED  ([PosNO], [ADATE], [CASHIER]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
