CREATE TABLE [dbo].[SPVOUCHER]
(
[SN] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__SPVOUCHER__SN__0024001B] DEFAULT (''),
[STAT] [int] NOT NULL CONSTRAINT [DF__SPVOUCHER__STAT__01182454] DEFAULT (0),
[PHASE] [int] NOT NULL CONSTRAINT [DF__SPVOUCHER__PHASE__020C488D] DEFAULT (0),
[FILDATE] [datetime] NOT NULL,
[SALEAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__SPVOUCHER__SALEA__03006CC6] DEFAULT (0),
[ENSN] [char] (64) COLLATE Chinese_PRC_CI_AS NULL,
[RCVTIME] [datetime] NULL,
[SNDTIME] [datetime] NULL,
[BESOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[BESSRC] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[HANDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[HANDSRC] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[HANDTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SPVOUCHER] ADD CONSTRAINT [PK__SPVOUCHER__7F2FDBE2] PRIMARY KEY CLUSTERED  ([SN]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FILDATE] ON [dbo].[SPVOUCHER] ([ENSN]) ON [PRIMARY]
GO
