CREATE TABLE [dbo].[PSFLOWNOHSTNUM]
(
[STORE] [int] NOT NULL,
[CONDATE] [datetime] NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (26) COLLATE Chinese_PRC_CI_AS NULL,
[CARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARRIER] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSFLOWNOHSTNUM] ADD CONSTRAINT [PK__PSFLOWNOHSTNUM__7D1681F9] PRIMARY KEY CLUSTERED  ([STORE], [POSNO], [FLOWNO]) ON [PRIMARY]
GO
