CREATE TABLE [dbo].[routdrpt]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[BGDGID] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[BCSTGID] [int] NOT NULL,
[DQ1] [money] NULL,
[DQ2] [money] NULL,
[DQ3] [money] NULL,
[DQ4] [money] NULL,
[DQ5] [money] NULL,
[DQ6] [money] NULL,
[DQ7] [money] NULL,
[DT1] [money] NULL,
[DT2] [money] NULL,
[DT3] [money] NULL,
[DT4] [money] NULL,
[DT5] [money] NULL,
[DT6] [money] NULL,
[DT7] [money] NULL,
[DT91] [money] NULL,
[DT92] [money] NULL,
[DI1] [money] NULL,
[DI2] [money] NULL,
[DI3] [money] NULL,
[DI4] [money] NULL,
[DI5] [money] NULL,
[DI6] [money] NULL,
[DI7] [money] NULL,
[DR1] [money] NULL,
[DR2] [money] NULL,
[DR3] [money] NULL,
[DR4] [money] NULL,
[DR5] [money] NULL,
[DR6] [money] NULL,
[DR7] [money] NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx1] ON [dbo].[routdrpt] ([ADATE], [ASETTLENO], [ASTORE]) ON [PRIMARY]
GO
