CREATE TABLE [dbo].[NPROM]
(
[ID] [int] NOT NULL,
[NO] [smallint] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__NPROM__STAT__6E7B1C83] DEFAULT (0),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NPROM__FILDATE__6F6F40BC] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__NPROM__LSTUPDTIM__706364F5] DEFAULT (getdate()),
[TOPIC] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STORESCOPE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[ASTART] [datetime] NOT NULL,
[AFINISH] [datetime] NOT NULL,
[CYCLE] [datetime] NULL,
[CSTART] [datetime] NULL,
[CFINISH] [datetime] NULL,
[CSPEC] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[FRCCHK] [smallint] NOT NULL CONSTRAINT [DF__NPROM__FRCCHK__7157892E] DEFAULT (0),
[PSETTLENO] [int] NULL,
[OCRTIME] [datetime] NOT NULL,
[FIXRATIO] [decimal] (24, 4) NULL,
[GFTRATIO] [decimal] (24, 4) NULL,
[HASCOND] [int] NOT NULL,
[MONTHSETTLENO] [int] NOT NULL CONSTRAINT [DF__NPROM__MONTHSETT__43326279] DEFAULT (0),
[DLTPRICEPROM] [smallint] NOT NULL CONSTRAINT [DF__NPROM__DLTPRICEP__5FCEA127] DEFAULT (0),
[OVERWRITERULE] [smallint] NOT NULL CONSTRAINT [DF__NPROM__OVERWRITE__2834537A] DEFAULT (0),
[EXPROM] [int] NOT NULL CONSTRAINT [DF__NPROM__EXPROM__6260F50F] DEFAULT (0),
[ONLYMEMBER] [tinyint] NOT NULL CONSTRAINT [DF__NPROM__ONLYMEMBE__28FF25D8] DEFAULT (0),
[PRIORITY] [int] NOT NULL CONSTRAINT [DF__NPROM__PRIORITY__1E0D6170] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPROM] ADD CONSTRAINT [PK__NPROM__724BAD67] PRIMARY KEY CLUSTERED  ([SRC], [ID], [NO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPROM_TYPE] ON [dbo].[NPROM] ([TYPE]) ON [PRIMARY]
GO
