CREATE TABLE [dbo].[PS3_ONLINEORDGENBILLS]
(
[PLATFORM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ORDNO] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GENBILLNAME] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GENBILLNUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[UUID] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SYNSTATE] [smallint] NOT NULL CONSTRAINT [DF__PS3_ONLIN__SYNST__020881A4] DEFAULT ((0)),
[lstUpdTime] [date] NOT NULL CONSTRAINT [DF__PS3_ONLIN__lstUp__02FCA5DD] DEFAULT ('2018-03-08 10:17:33.710')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3_ONLINEORDGENBILLS] ADD CONSTRAINT [PK__PS3_OnLineOrdGen__08CA8DCC] PRIMARY KEY CLUSTERED  ([UUID], [GENBILLNAME]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_OlOrdGenBill_Po] ON [dbo].[PS3_ONLINEORDGENBILLS] ([PLATFORM], [ORDNO], [GENBILLNAME]) ON [PRIMARY]
GO
