CREATE TABLE [dbo].[PCKS]
(
[LINE] [int] NOT NULL IDENTITY(1, 1),
[SETTLENO] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[WRH] [int] NOT NULL,
[SUBWRH] [int] NOT NULL CONSTRAINT [DF__PCKS__SUBWRH__4DCB2873] DEFAULT (0),
[ACNTQTY] [money] NOT NULL CONSTRAINT [DF__PCKS__ACNTQTY__4EBF4CAC] DEFAULT (0),
[QTY] [money] NOT NULL CONSTRAINT [DF__PCKS__QTY__4FB370E5] DEFAULT (0),
[ACNTTL] [money] NOT NULL CONSTRAINT [DF__PCKS__ACNTTL__50A7951E] DEFAULT (0),
[TOTAL] [money] NOT NULL CONSTRAINT [DF__PCKS__TOTAL__519BB957] DEFAULT (0),
[OVFAMT] [money] NOT NULL CONSTRAINT [DF__PCKS__OVFAMT__528FDD90] DEFAULT (0),
[LOSAMT] [money] NOT NULL CONSTRAINT [DF__PCKS__LOSAMT__538401C9] DEFAULT (0),
[INPRC] [money] NOT NULL CONSTRAINT [DF__PCKS__INPRC__54782602] DEFAULT (0),
[RTLPRC] [money] NOT NULL CONSTRAINT [DF__PCKS__RTLPRC__556C4A3B] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PCKS] ADD CONSTRAINT [PK__PCKS__6F1576F7] PRIMARY KEY CLUSTERED  ([GDGID], [WRH], [SUBWRH]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PCKSLINE] ON [dbo].[PCKS] ([LINE]) ON [PRIMARY]
GO
