CREATE TABLE [dbo].[PS3REDBLUECARD]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__PS3REDBLUE__STAT__7F667CBA] DEFAULT (0),
[SRC] [int] NOT NULL,
[VENDOR] [int] NOT NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__PS3REDBLU__FILDA__005AA0F3] DEFAULT (getdate()),
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[PRINT] [datetime] NULL CONSTRAINT [DF__PS3REDBLU__PRINT__014EC52C] DEFAULT (null),
[SNDTIME] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[EON] [smallint] NOT NULL CONSTRAINT [DF__PS3REDBLUEC__EON__0242E965] DEFAULT (1),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__PS3REDBLU__LSTUP__03370D9E] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3REDBLUECARD] ADD CONSTRAINT [PK__PS3REDBLUECARD__042B31D7] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
