CREATE TABLE [dbo].[FABPLVERSIONINFO]
(
[NAME] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VERSION] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLAG] [smallint] NOT NULL CONSTRAINT [DF__FABPLVERSI__FLAG__2C28D8A2] DEFAULT (1),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[LSTMODIFYTIME] [datetime] NOT NULL CONSTRAINT [DF__FABPLVERS__LSTMO__2D1CFCDB] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FABPLVERSIONINFO] ADD CONSTRAINT [PK__FABPLVERSIONINFO__2E112114] PRIMARY KEY CLUSTERED  ([NAME]) ON [PRIMARY]
GO
