CREATE TABLE [dbo].[MXFDMDDTL]
(
[NUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[CONFIRM] [int] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__MXFDMDDTL__QTY__634BC2FE] DEFAULT (0),
[FROMPRC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__MXFDMDDTL__FROMP__643FE737] DEFAULT (0),
[FROMTOTAL] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__MXFDMDDTL__FROMT__65340B70] DEFAULT (0),
[WRH] [int] NOT NULL CONSTRAINT [DF__MXFDMDDTL__WRH__66282FA9] DEFAULT (0),
[FROMTAX] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__MXFDMDDTL__FROMT__671C53E2] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MXFDMDDTL] ADD CONSTRAINT [PK__MXFDMDDTL__6810781B] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
