CREATE TABLE [dbo].[POLYPROMTOTALSCHMDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[LOWAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__POLYPROMT__LOWAM__53B479B3] DEFAULT (0),
[HIGHAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__POLYPROMT__HIGHA__54A89DEC] DEFAULT (99999999),
[DISCOUNT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__POLYPROMT__DISCO__559CC225] DEFAULT (0),
[FAVAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__POLYPROMT__FAVAM__5690E65E] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[POLYPROMTOTALSCHMDTL] ADD CONSTRAINT [PK__POLYPROMTOTALSCH__57850A97] PRIMARY KEY CLUSTERED  ([NUM], [CLS], [LINE]) ON [PRIMARY]
GO
