CREATE TABLE [dbo].[WAREHOUSEH]
(
[GID] [int] NOT NULL,
[CODE] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[NAME] [char] (50) COLLATE Chinese_PRC_CI_AS NULL,
[MEMO] [char] (255) COLLATE Chinese_PRC_CI_AS NULL,
[CHKVD] [smallint] NULL CONSTRAINT [DF__WAREHOUSE__CHKVD__108C44B2] DEFAULT (0),
[AUTOORD] [smallint] NULL CONSTRAINT [DF__WAREHOUSE__AUTOO__118068EB] DEFAULT (0),
[ALLOWNEG] [smallint] NULL CONSTRAINT [DF__WAREHOUSE__ALLOW__12748D24] DEFAULT (1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WAREHOUSEH] ADD CONSTRAINT [PK__WAREHOUSEH__0F982079] PRIMARY KEY CLUSTERED  ([GID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
