CREATE TABLE [dbo].[CASHCLTDTLPOOL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[CURRENCY] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[AMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CASHCLTDT__AMOUN__002596C9] DEFAULT (0),
[REALAMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CASHCLTDT__REALA__0119BB02] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CASHCLTDTLPOOL] ADD CONSTRAINT [PK__CASHCLTDTLPOOL__020DDF3B] PRIMARY KEY CLUSTERED  ([POSNO], [NUM], [LINE]) ON [PRIMARY]
GO
