CREATE TABLE [dbo].[BARCODELEN]
(
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLAG] [char] (1) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__BARCODELEN__FLAG__0FAD2F12] DEFAULT ('2'),
[CODELEN] [smallint] NULL CONSTRAINT [DF__BARCODELE__CODEL__10A1534B] DEFAULT (7),
[QTYLEN] [smallint] NOT NULL CONSTRAINT [DF__barcodele__QTYLE__3AF84B21] DEFAULT (5),
[AMTLEN] [smallint] NOT NULL CONSTRAINT [DF__barcodele__AMTLE__3BEC6F5A] DEFAULT (5)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BARCODELEN] ADD CONSTRAINT [PK__BARCODELEN__13BCEBC1] PRIMARY KEY CLUSTERED  ([POSNO], [FLAG]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
