CREATE TABLE [dbo].[PRMOFFSETAGMLACSTORE]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRMOFFSETAGMLACSTORE] ADD CONSTRAINT [PK__PRMOFFSETAGMLACS__4096B847] PRIMARY KEY CLUSTERED  ([NUM], [STOREGID]) ON [PRIMARY]
GO
