CREATE TABLE [dbo].[NGDQPC]
(
[GID] [int] NOT NULL,
[QPCSTR] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NGDQPC__QPCSTR__20FBAF58] DEFAULT ('1*1'),
[QPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NGDQPC__QPC__21EFD391] DEFAULT (1),
[MUNIT] [char] (6) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NGDQPC__MUNIT__22E3F7CA] DEFAULT ('个'),
[VOL] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[WEIGHT] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[ISDU] [smallint] NOT NULL CONSTRAINT [DF__NGDQPC__ISDU__23D81C03] DEFAULT (1),
[ISPU] [smallint] NOT NULL CONSTRAINT [DF__NGDQPC__ISPU__24CC403C] DEFAULT (1),
[ISWU] [smallint] NOT NULL CONSTRAINT [DF__NGDQPC__ISWU__25C06475] DEFAULT (1),
[ISRU] [smallint] NOT NULL CONSTRAINT [DF__NGDQPC__ISRU__26B488AE] DEFAULT (1),
[RTLPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NGDQPC__RTLPRC__27A8ACE7] DEFAULT (0),
[WHSPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NGDQPC__WHSPRC__289CD120] DEFAULT (0),
[MBRPRC] [decimal] (24, 2) NULL,
[LWTRTLPRC] [decimal] (24, 4) NULL,
[TOPRTLPRC] [decimal] (24, 4) NULL,
[BQTYPRC] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[PROMOTE] [smallint] NOT NULL CONSTRAINT [DF__NGDQPC__PROMOTE__2990F559] DEFAULT ((-1)),
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[FRCUPD] [smallint] NOT NULL,
[TYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[TEAMID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NGDQPC] ADD CONSTRAINT [PK__NGDQPC__2A851992] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NGDQPC_GIDX] ON [dbo].[NGDQPC] ([GID], [QPC]) ON [PRIMARY]
GO
