CREATE TABLE [dbo].[CQNPRCADJDTL]
(
[GROUPID] [int] NOT NULL,
[RHQUUID] [char] (32) COLLATE Chinese_PRC_CI_AS NULL,
[NTYPE] [int] NOT NULL,
[NSTAT] [int] NOT NULL CONSTRAINT [DF__CQNPRCADJ__NSTAT__5AC85E3A] DEFAULT (0),
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[EXTIME] [datetime] NOT NULL CONSTRAINT [DF__CQNPRCADJ__EXTIM__5BBC8273] DEFAULT (getdate()),
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[OLDPRC] [decimal] (24, 4) NOT NULL,
[NEWPRC] [decimal] (24, 4) NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CQNPRCADJDTL] ADD CONSTRAINT [PK__CQNPRCADJDTL__59D43A01] PRIMARY KEY CLUSTERED  ([NTYPE], [GROUPID], [LINE]) ON [PRIMARY]
GO
