CREATE TABLE [dbo].[NSTOREORDAPPLY]
(
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL,
[VENDORGID] [int] NOT NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__NSTOREORD__RECCN__12D8788A] DEFAULT (0),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__NSTOREORDA__STAT__13CC9CC3] DEFAULT (0),
[FILLER] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILLDATE] [datetime] NOT NULL CONSTRAINT [DF__NSTOREORD__FILLD__14C0C0FC] DEFAULT (getdate()),
[OPDATE] [datetime] NULL,
[GENNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[MEMO] [varchar] (256) COLLATE Chinese_PRC_CI_AS NULL,
[RCV] [int] NULL,
[TYPE] [int] NOT NULL CONSTRAINT [DF__NSTOREORDA__TYPE__15B4E535] DEFAULT (0),
[TAXRATELMT] [decimal] (24, 4) NULL,
[DEPTLMT] [varchar] (13) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NULL,
[NTYPE] [int] NOT NULL CONSTRAINT [DF__NSTOREORD__NTYPE__16A9096E] DEFAULT (0),
[SNDTIME] [datetime] NULL,
[RCVTIME] [datetime] NULL,
[CHECKER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[GENNUM2] [varchar] (14) COLLATE Chinese_PRC_CI_AS NULL,
[SETTLENO] [int] NULL,
[APPLYDGID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NSTOREORDAPPLY] ADD CONSTRAINT [PK__NStoreOrdApply__179D2DA7] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
