CREATE TABLE [dbo].[CLRINVDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NULL,
[WRH] [int] NULL,
[QTY] [money] NULL,
[TOTAL] [money] NULL,
[VALIDDATE] [datetime] NULL,
[ORDNUM] [money] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLRINVDTL] ADD CONSTRAINT [PK__CLRINVDTL__30592A6F] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
