CREATE TABLE [dbo].[EQUPMENT]
(
[CODE] [varchar] (15) COLLATE Chinese_PRC_CI_AS NULL,
[NAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [UQ_EQUPMENT] ON [dbo].[EQUPMENT] ([CODE]) ON [PRIMARY]
GO
