CREATE TABLE [dbo].[NSTKOUTBCK]
(
[ID] [int] NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[CLIENT] [int] NULL CONSTRAINT [DF__NSTKOUTBC__CLIEN__0C66AE13] DEFAULT (1),
[BILLTO] [int] NULL CONSTRAINT [DF__NSTKOUTBC__BILLT__0D5AD24C] DEFAULT (1),
[OCRDATE] [datetime] NULL,
[TOTAL] [money] NULL,
[TAX] [money] NULL,
[FILDATE] [datetime] NULL,
[CHECKER] [int] NULL CONSTRAINT [DF__NSTKOUTBC__CHECK__0E4EF685] DEFAULT (1),
[STAT] [smallint] NULL CONSTRAINT [DF__NSTKOUTBCK__STAT__0F431ABE] DEFAULT (0),
[MODNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NULL,
[NSTAT] [smallint] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[RCV] [int] NULL,
[SNDTIME] [datetime] NULL,
[RCVTIME] [datetime] NULL,
[FRCCHK] [smallint] NULL,
[TYPE] [smallint] NULL,
[gencls] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[gennum] [varchar] (14) COLLATE Chinese_PRC_CI_AS NULL,
[PayDate] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NSTKOUTBCK] ADD CONSTRAINT [PK__NSTKOUTBCK__4F9CCB9E] PRIMARY KEY CLUSTERED  ([SRC], [ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NSTKOUTBCK_TYPE] ON [dbo].[NSTKOUTBCK] ([TYPE]) ON [PRIMARY]
GO
