CREATE TABLE [dbo].[NCstMize]
(
[ID] [int] NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[VENDOR] [int] NOT NULL CONSTRAINT [DF__NCstMize__VENDOR__6A731F70] DEFAULT (1),
[CLIENT] [int] NOT NULL CONSTRAINT [DF__NCstMize__CLIENT__6B6743A9] DEFAULT (1),
[BILLTO] [int] NOT NULL CONSTRAINT [DF__NCstMize__BILLTO__6C5B67E2] DEFAULT (1),
[TOTAL] [money] NOT NULL CONSTRAINT [DF__NCstMize__TOTAL__6D4F8C1B] DEFAULT (0),
[TAX] [money] NOT NULL CONSTRAINT [DF__NCstMize__TAX__6E43B054] DEFAULT (0),
[GTOTAL] [money] NOT NULL CONSTRAINT [DF__NCstMize__GTOTAL__6F37D48D] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NCstMize__FILDAT__702BF8C6] DEFAULT (getdate()),
[CHKDATE] [datetime] NOT NULL CONSTRAINT [DF__NCstMize__CHKDAT__71201CFF] DEFAULT (getdate()),
[CFMDATE] [datetime] NULL,
[PREPAY] [money] NULL,
[FILLER] [int] NOT NULL CONSTRAINT [DF__NCstMize__FILLER__72144138] DEFAULT (1),
[CHECKER] [int] NOT NULL CONSTRAINT [DF__NCstMize__CHECKE__73086571] DEFAULT (1),
[CONFIRMER] [int] NOT NULL CONSTRAINT [DF__NCstMize__CONFIR__73FC89AA] DEFAULT (1),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__NCstMize__STAT__74F0ADE3] DEFAULT (0),
[SLR] [int] NOT NULL CONSTRAINT [DF__NCstMize__SLR__75E4D21C] DEFAULT (1),
[MODNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[RECEIVER] [int] NOT NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__NCstMize__RECCNT__76D8F655] DEFAULT (0),
[NSTAT] [int] NOT NULL,
[SRC] [int] NOT NULL,
[SRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[FINISHED] [int] NOT NULL CONSTRAINT [DF__NCstMize__FINISH__77CD1A8E] DEFAULT (0),
[RCV] [int] NOT NULL,
[SNDTIME] [datetime] NOT NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCstMize] ADD CONSTRAINT [PK__NCstMize__1B29035F] PRIMARY KEY CLUSTERED  ([SRC], [ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
