CREATE TABLE [dbo].[BPCKPOOL]
(
[GCODE] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SUBWRHCODE] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[WRHCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[EMPCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
