CREATE TABLE [dbo].[NDMDPRMDTLDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[LINE] [smallint] NOT NULL,
[ITEM] [smallint] NOT NULL,
[START] [datetime] NOT NULL CONSTRAINT [DF__NDMDPRMDT__START__4635BEFA] DEFAULT ('1899.12.30 00:00:00'),
[FINISH] [datetime] NOT NULL CONSTRAINT [DF__NDMDPRMDT__FINIS__4729E333] DEFAULT ('9999.12.31 23:59:59'),
[CYCLE] [datetime] NOT NULL CONSTRAINT [DF__NDMDPRMDT__CYCLE__481E076C] DEFAULT ('1899.12.30 00:00:00'),
[CSTART] [datetime] NOT NULL CONSTRAINT [DF__NDMDPRMDT__CSTAR__49122BA5] DEFAULT ('1899.12.30 00:00:00'),
[CFINISH] [datetime] NOT NULL CONSTRAINT [DF__NDMDPRMDT__CFINI__4A064FDE] DEFAULT ('9999.12.31 23:59:59'),
[CSPEC] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[QTYLO] [money] NOT NULL CONSTRAINT [DF__NDMDPRMDT__QTYLO__4AFA7417] DEFAULT (0),
[QTYHI] [money] NOT NULL CONSTRAINT [DF__NDMDPRMDT__QTYHI__4BEE9850] DEFAULT (99999999),
[PRICE] [money] NULL,
[DISCOUNT] [decimal] (5, 2) NULL,
[GFTGID] [int] NULL,
[GFTQTY] [money] NULL,
[GFTPER] [money] NULL,
[GFTTYPE] [smallint] NULL,
[INPRC] [money] NULL,
[PRMTAG] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[MBRPRC] [money] NULL,
[PRMLWTPRC] [decimal] (24, 4) NULL,
[CONFIRM] [smallint] NULL CONSTRAINT [DF__NDMDPRMDT__CONFI__73BE2936] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NDMDPRMDTLDTL] ADD CONSTRAINT [PK__NDMDPRMDTLDTL__21D600EE] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE], [ITEM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
