CREATE TABLE [dbo].[PAYADJDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SETTLENO] [int] NULL,
[GDGID] [int] NULL,
[OQTY] [money] NULL,
[OTOTAL] [money] NULL,
[OSTOTAL] [money] NULL,
[NQTY] [money] NULL,
[NTOTAL] [money] NULL,
[NSTOTAL] [money] NULL,
[INPRC] [money] NULL,
[RTLPRC] [money] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAYADJDTL] ADD CONSTRAINT [PK__PAYADJDTL__668030F6] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [payadjdtl_gdgid] ON [dbo].[PAYADJDTL] ([GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
