CREATE TABLE [dbo].[GDINVCHGNOTIFYGENDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GENBILL] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GENNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GENLINE] [int] NOT NULL
) ON [PRIMARY]
GO
