CREATE TABLE [dbo].[NCRMCARDBLKLST]
(
[CARDNUM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GRADE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NCRMCARDB__GRADE__1146012A] DEFAULT ('正常处理'),
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[SNDTIME] [datetime] NOT NULL CONSTRAINT [DF__NCRMCARDB__SNDTI__123A2563] DEFAULT (getdate()),
[RCV] [int] NULL,
[RCVTIME] [datetime] NULL,
[FRCCHK] [int] NOT NULL,
[NTYPE] [int] NOT NULL,
[NSTAT] [int] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SYSUUID] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NCRMCARDB__SYSUU__132E499C] DEFAULT ('-')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCRMCARDBLKLST] ADD CONSTRAINT [PK__NCRMCARDBLKLST__14226DD5] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
