CREATE TABLE [dbo].[MODULE]
(
[NO] [smallint] NOT NULL,
[NAME] [char] (255) COLLATE Chinese_PRC_CI_AS NULL,
[TYPE] [smallint] NULL CONSTRAINT [DF__MODULE__TYPE__4BF72343] DEFAULT (1),
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[PROCNAME] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[PKGNAME] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL,
[UNITNAME] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL,
[CATALOG] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MODULE] ADD CONSTRAINT [PK__MODULE__0EC32C7A] PRIMARY KEY CLUSTERED  ([NO]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MODULE] ADD CONSTRAINT [UQ__MODULE__62EF9734] UNIQUE NONCLUSTERED  ([NAME]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
