CREATE TABLE [dbo].[CRMCARDSTOREINV]
(
[CARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STORE] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMCARDSTOREINV] ADD CONSTRAINT [PK__CRMCARDSTOREINV__76D9C1AC] PRIMARY KEY CLUSTERED  ([CARDNUM]) ON [PRIMARY]
GO
