CREATE TABLE [dbo].[NPSTASKRESULTDTLPOOL]
(
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL,
[ITEMNO] [int] NOT NULL,
[EXESTAT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NPSTASKRE__EXEST__745E130B] DEFAULT (0),
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL,
[SUBTIME] [datetime] NOT NULL,
[SUBEMP] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[TAG] [int] NOT NULL CONSTRAINT [DF__NPSTASKRESU__TAG__75523744] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPSTASKRESULTDTLPOOL] ADD CONSTRAINT [PK__NPSTASKRESULTDTL__76465B7D] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
