CREATE TABLE [dbo].[GOODSRECEIPTLOG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [int] NOT NULL,
[ACTION] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GOODSRECEIPTLOG] ADD CONSTRAINT [PK__GOODSRECEIPTLOG__2530F6F9] PRIMARY KEY CLUSTERED  ([NUM], [STAT], [ACTION], [TIME]) ON [PRIMARY]
GO
