CREATE TABLE [dbo].[CASHIEROPERATE]
(
[CASHIERCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[CASHIERNAME] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[MONTHSETTLENO] [int] NULL,
[OPERATE] [char] (24) COLLATE Chinese_PRC_CI_AS NULL,
[TIME] [datetime] NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MEMO] [text] COLLATE Chinese_PRC_CI_AS NULL,
[note] [varchar] (4000) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
CREATE CLUSTERED INDEX [idx_posnotime] ON [dbo].[CASHIEROPERATE] ([POSNO], [TIME]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
