CREATE TABLE [dbo].[PROCTRANSFER]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__PROCTRANSF__STAT__1E895701] DEFAULT (0),
[TASKNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL,
[TOTAL] [decimal] (24, 2) NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__PROCTRANS__FILDA__1F7D7B3A] DEFAULT (getdate()),
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NULL,
[SRC] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROCTRANSFER] ADD CONSTRAINT [PK__PROCTRANSFER__20719F73] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
