CREATE TABLE [dbo].[POLYPROM]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL,
[FILDATE] [datetime] NOT NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL,
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHKDATE] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__POLYPROM__RECCNT__474EA2CE] DEFAULT (0),
[EXGDRECCNT] [int] NOT NULL CONSTRAINT [DF__POLYPROM__EXGDRE__4842C707] DEFAULT (0),
[SCHMRECCNT] [int] NOT NULL CONSTRAINT [DF__POLYPROM__SCHMRE__4936EB40] DEFAULT (0),
[DLTPRICEPROM] [smallint] NOT NULL CONSTRAINT [DF__POLYPROM__DLTPRI__4A2B0F79] DEFAULT (0),
[CALBYRTLPRC] [smallint] NOT NULL CONSTRAINT [DF__POLYPROM__CALBYR__4B1F33B2] DEFAULT (0),
[TOPIC] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[PSETTLENO] [int] NULL,
[PRIORITY] [int] NOT NULL CONSTRAINT [DF__POLYPROM__PRIORI__2F37ED72] DEFAULT (0),
[EXPROM] [int] NOT NULL CONSTRAINT [DF__POLYPROM__EXPROM__75CA65EC] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[POLYPROM] ADD CONSTRAINT [PK__POLYPROM__4C1357EB] PRIMARY KEY CLUSTERED  ([NUM], [CLS]) ON [PRIMARY]
GO
