CREATE TABLE [dbo].[TERMPOOL]
(
[ID] [int] NOT NULL,
[TERMNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[WRHCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[INPUTER] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[GCODE] [varchar] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__TERMPOOL__FILDAT__471E2AE4] DEFAULT (getdate()),
[QTY] [money] NOT NULL CONSTRAINT [DF__TERMPOOL__QTY__48124F1D] DEFAULT (0),
[PRICE] [money] NOT NULL CONSTRAINT [DF__TERMPOOL__PRICE__49067356] DEFAULT (0),
[AMOUNT] [money] NOT NULL CONSTRAINT [DF__TERMPOOL__AMOUNT__49FA978F] DEFAULT (0),
[SUBWRHCODE] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__TERMPOOL__SUBWRH__17E7466A] DEFAULT (1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TERMPOOL] ADD CONSTRAINT [PK__TERMPOOL__2FEF161B] PRIMARY KEY CLUSTERED  ([ID], [LINE], [TERMNO]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
