CREATE TABLE [dbo].[CHECKINDTLPOOLS]
(
[ID] [int] NOT NULL,
[STORENO] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CASHIER] [int] NOT NULL,
[THEDATE] [datetime] NOT NULL,
[FROMDATE] [datetime] NOT NULL,
[CURRENCY] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[AMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CHECKINDT__AMOUN__2184F3E6] DEFAULT (0),
[REALAMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CHECKINDT__REALA__2279181F] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CHECKINDTLPOOLS] ADD CONSTRAINT [PK__CHECKINDTLPOOLS__2090CFAD] PRIMARY KEY CLUSTERED  ([ID], [STORENO], [THEDATE], [CASHIER], [CURRENCY]) ON [PRIMARY]
GO
