CREATE TABLE [dbo].[PS3SCONOTSCORECURRENCY]
(
[CURCODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3SCONOTSCORECURRENCY] ADD CONSTRAINT [PK__PS3SCONOTSCORECU__295B1FD8] PRIMARY KEY CLUSTERED  ([CURCODE]) ON [PRIMARY]
GO
