CREATE TABLE [dbo].[NBCKNOTIFYDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[note] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NBCKNOTIFYDTL] ADD CONSTRAINT [PK__NBCKNOTIFYDTL__210E5BEC] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) ON [PRIMARY]
GO
