CREATE TABLE [dbo].[PURCHASEORDERDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[ORDQTY] [decimal] (24, 4) NOT NULL,
[PRICE] [decimal] (24, 4) NOT NULL,
[TOTAL] [decimal] (24, 4) NOT NULL,
[TAX] [decimal] (24, 4) NOT NULL,
[WRH] [int] NOT NULL CONSTRAINT [DF__PURCHASEORD__WRH__669A0399] DEFAULT (1),
[INVQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PURCHASEO__INVQT__678E27D2] DEFAULT (0),
[ARVQTY] [decimal] (24, 4) NULL CONSTRAINT [DF__PURCHASEO__ARVQT__68824C0B] DEFAULT (0),
[BCKQTY] [decimal] (24, 4) NULL CONSTRAINT [DF__PURCHASEO__BCKQT__69767044] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[RTLQTY] [decimal] (24, 4) NULL CONSTRAINT [DF__PURCHASEO__RTLQT__6A6A947D] DEFAULT (0),
[RTLBCKQTY] [decimal] (24, 4) NULL CONSTRAINT [DF__PURCHASEO__RTLBC__6B5EB8B6] DEFAULT (0),
[RTLPRC] [decimal] (24, 4) NULL CONSTRAINT [DF__PURCHASEO__RTLPR__6C52DCEF] DEFAULT (0),
[RTLTOTAL] [decimal] (24, 4) NULL CONSTRAINT [DF__PURCHASEO__RTLTO__6D470128] DEFAULT (0),
[PRNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[PAYQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PURCHASEO__PAYQT__6E3B2561] DEFAULT (0),
[PAYAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PURCHASEO__PAYAM__6F2F499A] DEFAULT (0),
[ORDPRC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PURCHASEO__ORDPR__70236DD3] DEFAULT (0),
[ORDAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PURCHASEO__ORDAM__7117920C] DEFAULT (0),
[INPRC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PURCHASEO__INPRC__720BB645] DEFAULT (0),
[INPRCAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PURCHASEO__INPRC__72FFDA7E] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PURCHASEORDERDTL] ADD CONSTRAINT [PK__PURCHASEORDERDTL__73F3FEB7] PRIMARY KEY CLUSTERED  ([NUM], [CLS], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [podtl_gdgid] ON [dbo].[PURCHASEORDERDTL] ([GDGID]) ON [PRIMARY]
GO
