CREATE TABLE [dbo].[WEBSBUY21RECORD]
(
[UUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SHOPCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSID] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[FAVTYPE] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FAVAMOUNT] [decimal] (24, 4) NOT NULL,
[BILL] [varchar] (32) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WEBSBUY21RECORD] ADD CONSTRAINT [PK__WEBSBUY21RECORD__6A6F5887] PRIMARY KEY CLUSTERED  ([SHOPCODE], [FLOWNO], [POSID], [ITEMNO], [FAVTYPE]) ON [PRIMARY]
GO
