CREATE TABLE [dbo].[FATOOLBARDTL]
(
[FGID] [int] NOT NULL,
[FINDEX] [int] NOT NULL,
[FITEMNO] [int] NOT NULL,
[FMODULE] [int] NOT NULL,
[FCAPTION] [varchar] (120) COLLATE Chinese_PRC_CI_AS NULL,
[FNEWGRP] [int] NOT NULL CONSTRAINT [DF__FATOOLBAR__FNEWG__1708FC21] DEFAULT (0),
[ICONID] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FATOOLBARDTL] ADD CONSTRAINT [PK__FATOOLBARDTL__17FD205A] PRIMARY KEY CLUSTERED  ([FGID], [FINDEX], [FITEMNO]) ON [PRIMARY]
GO
