CREATE TABLE [dbo].[GDINPRCADJDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[OLDPRC] [decimal] (24, 4) NOT NULL,
[NEWPRC] [decimal] (24, 4) NOT NULL,
[QTY] [decimal] (24, 4) NOT NULL,
[INVQTY] [decimal] (24, 4) NOT NULL,
[DIFFPRC] [decimal] (24, 4) NOT NULL,
[DIFFAMT] [decimal] (24, 4) NOT NULL,
[PREPRO] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__GDINPRCAD__PREPR__1F728E42] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[WRH] [int] NOT NULL CONSTRAINT [DF__GDINPRCADJD__WRH__1CABFB87] DEFAULT ((-1)),
[CNTAMT] [money] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GDINPRCADJDTL] ADD CONSTRAINT [PK__GDINPRCADJDTL__2066B27B] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
