CREATE TABLE [dbo].[CNTRDPTBILL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VENDOR] [int] NOT NULL,
[TOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CNTRDPTBI__TOTAL__468B900C] DEFAULT (0),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__CNTRDPTBIL__STAT__477FB445] DEFAULT (0),
[VDROPER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[OPER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CNTRDPTBI__CHECK__4873D87E] DEFAULT (1),
[NOTE] [char] (255) COLLATE Chinese_PRC_CI_AS NULL,
[DEPT] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[PSR] [int] NOT NULL CONSTRAINT [DF__CNTRDPTBILL__PSR__4967FCB7] DEFAULT (1),
[PAYER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[TOTALOFF] [money] NOT NULL CONSTRAINT [DF__CNTRDPTBI__TOTAL__53C7F19E] DEFAULT (0),
[STSTORE] [int] NULL,
[CLECENT] [int] NULL,
[SNDTIME] [datetime] NULL,
[SRC] [int] NOT NULL CONSTRAINT [DF__CNTRDPTBILL__SRC__59E0BDA7] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CNTRDPTBILL] ADD CONSTRAINT [PK__CNTRDPTBILL__4A5C20F0] PRIMARY KEY CLUSTERED  ([NUM], [CLS]) ON [PRIMARY]
GO
