CREATE TABLE [dbo].[STOREORDAPPLYDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[GDCODE] [varchar] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[QPC] [int] NOT NULL,
[QPCSTR] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[QTY] [decimal] (24, 4) NOT NULL,
[APPLYQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__STOREORDA__APPLY__0F07E7A6] DEFAULT ((-1)),
[EXCGQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__STOREORDA__EXCGQ__0FFC0BDF] DEFAULT ((-1)),
[NOTE] [varchar] (256) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STOREORDAPPLYDTL] ADD CONSTRAINT [PK__StoreOrdApplyDtl__10F03018] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
