CREATE TABLE [dbo].[ALCBYGOODSDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[STOREGID] [int] NOT NULL,
[CASES] [money] NULL,
[QTY] [money] NOT NULL CONSTRAINT [DF__ALCBYGOODSD__QTY__77E15DD0] DEFAULT (0),
[TOTAL] [money] NOT NULL CONSTRAINT [DF__ALCBYGOOD__TOTAL__78D58209] DEFAULT (0),
[TAX] [money] NOT NULL CONSTRAINT [DF__ALCBYGOODSD__TAX__79C9A642] DEFAULT (0),
[ASNQTY] [money] NULL CONSTRAINT [DF__alcbygood__ASNQT__301173B1] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ALCBYGOODSDTL] ADD CONSTRAINT [PK__ALCBYGOODSDTL__76ED3997] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
