CREATE TABLE [dbo].[NPROCMRPT]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[BGDGID] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[CQ1] [money] NOT NULL CONSTRAINT [DF__NPROCMRPT__CQ1__550DEE36] DEFAULT (0),
[CT1] [money] NOT NULL CONSTRAINT [DF__NPROCMRPT__CT1__5602126F] DEFAULT (0),
[CI1] [money] NOT NULL CONSTRAINT [DF__NPROCMRPT__CI1__56F636A8] DEFAULT (0),
[CR1] [money] NOT NULL CONSTRAINT [DF__NPROCMRPT__CR1__57EA5AE1] DEFAULT (0),
[CD1] [money] NOT NULL CONSTRAINT [DF__NPROCMRPT__CD1__58DE7F1A] DEFAULT (0),
[DQ1] [money] NOT NULL CONSTRAINT [DF__NPROCMRPT__DQ1__59D2A353] DEFAULT (0),
[DT1] [money] NOT NULL CONSTRAINT [DF__NPROCMRPT__DT1__5AC6C78C] DEFAULT (0),
[DI1] [money] NOT NULL CONSTRAINT [DF__NPROCMRPT__DI1__5BBAEBC5] DEFAULT (0),
[DR1] [money] NOT NULL CONSTRAINT [DF__NPROCMRPT__DR1__5CAF0FFE] DEFAULT (0),
[DD1] [money] NOT NULL CONSTRAINT [DF__NPROCMRPT__DD1__5DA33437] DEFAULT (0),
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[RCV] [int] NULL,
[SNDTIME] [datetime] NOT NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPROCMRPT] ADD CONSTRAINT [PK__NPROCMRPT__451F3D2B] PRIMARY KEY CLUSTERED  ([ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
