CREATE TABLE [dbo].[PRMRTNPNTAGMDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[DEPT] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BRAND] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRMRTNPNTAGMDTL] ADD CONSTRAINT [PK__PRMRTNPNTAGMDTL__64E92756] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
