CREATE TABLE [dbo].[CRMSTAMPSCORULELOG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[STAT] [int] NOT NULL,
[ACTION] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_CRMSTAMPSCORULELOG_1] ON [dbo].[CRMSTAMPSCORULELOG] ([NUM]) ON [PRIMARY]
GO
