CREATE TABLE [dbo].[PS3_ONLINEGOODS]
(
[PLATFORM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDCODE] [varchar] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[GDNAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[AVLINVQTY] [decimal] (24, 4) NOT NULL,
[PRICE] [decimal] (24, 4) NOT NULL,
[LSTUPDTIMEINV] [datetime] NOT NULL,
[LSTUPDTIMEPRC] [datetime] NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__PS3_ONLIN__LSTUP__66A05E51] DEFAULT (getdate()),
[BARCODE] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PS3_ONLIN__BARCO__6794828A] DEFAULT ('-'),
[CREATETIME] [datetime] NOT NULL CONSTRAINT [DF__PS3_ONLIN__CREAT__6888A6C3] DEFAULT (getdate()),
[STOREGID] [int] NOT NULL,
[goodsInfoUrl] [varchar] (512) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3_ONLINEGOODS] ADD CONSTRAINT [PK__PS3_ONLI__161103B76A70EF35] PRIMARY KEY CLUSTERED  ([PLATFORM], [STOREGID], [GDCODE]) ON [PRIMARY]
GO
