CREATE TABLE [dbo].[DIRALCDTL]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SETTLENO] [int] NULL,
[GDGID] [int] NULL,
[WRH] [int] NULL,
[CASES] [money] NULL,
[QTY] [money] NULL,
[LOSS] [money] NULL CONSTRAINT [DF__DIRALCDTL__LOSS__1C9D15DC] DEFAULT (0),
[PRICE] [money] NULL,
[TOTAL] [money] NULL,
[TAX] [money] NULL,
[ALCPRC] [money] NULL,
[ALCAMT] [money] NULL,
[WSPRC] [money] NULL,
[INPRC] [money] NULL,
[RTLPRC] [money] NULL,
[VALIDDATE] [datetime] NULL,
[BCKQTY] [money] NULL CONSTRAINT [DF__DIRALCDTL__BCKQT__1D913A15] DEFAULT (0),
[PAYQTY] [money] NULL CONSTRAINT [DF__DIRALCDTL__PAYQT__1E855E4E] DEFAULT (0),
[BCKAMT] [money] NULL CONSTRAINT [DF__DIRALCDTL__BCKAM__1F798287] DEFAULT (0),
[PAYAMT] [money] NULL CONSTRAINT [DF__DIRALCDTL__PAYAM__206DA6C0] DEFAULT (0),
[BNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SUBWRH] [int] NULL,
[OUTTAX] [money] NOT NULL CONSTRAINT [DF__DIRALCDTL__OUTTA__120B4427] DEFAULT (0),
[RCPQTY] [money] NOT NULL CONSTRAINT [DF__DIRALCDTL__RCPQT__316EE0E7] DEFAULT (0),
[RCPAMT] [money] NOT NULL CONSTRAINT [DF__DIRALCDTL__RCPAM__32630520] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[COST] [money] NOT NULL CONSTRAINT [DF__DIRALCDTL__COST__346A7DCC] DEFAULT (0),
[COSTPRC] [money] NOT NULL CONSTRAINT [DF__DIRALCDTL__COSTP__686A1016] DEFAULT (0),
[ORDLINE] [int] NOT NULL CONSTRAINT [DF__DIRALCDTL__ORDLI__2A97C626] DEFAULT (0),
[snewflag] [int] NOT NULL CONSTRAINT [DF__diralcdtl__snewf__09B6C09F] DEFAULT (0),
[DecOrdQty] [money] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DIRALCDTL] ADD CONSTRAINT [PK__DIRALCDTL__45544755] PRIMARY KEY CLUSTERED  ([CLS], [NUM], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [diralcdtl_gdgid] ON [dbo].[DIRALCDTL] ([GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
