CREATE TABLE [dbo].[PROMBGOODS]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[GDCODE] [varchar] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[RTLPRC] [decimal] (24, 4) NOT NULL,
[MBRPRC] [decimal] (24, 4) NULL,
[CNTRINPRC] [decimal] (24, 4) NOT NULL,
[COST] [decimal] (24, 4) NOT NULL,
[QPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PROMBGOODS__QPC__6294688B] DEFAULT (1),
[QPCSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PRMDIV1] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PROMBGOOD__PRMDI__63888CC4] DEFAULT (100),
[PRMDIV2] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PROMBGOOD__PRMDI__647CB0FD] DEFAULT (0),
[PRMDIV3] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PROMBGOOD__PRMDI__6570D536] DEFAULT (0),
[ISDLT] [smallint] NOT NULL CONSTRAINT [DF__PROMBGOOD__ISDLT__5A15C7D1] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROMBGOODS] ADD CONSTRAINT [PK__PROMBGOODS__6664F96F] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PROMBGOODS_GDGID] ON [dbo].[PROMBGOODS] ([GDGID]) ON [PRIMARY]
GO
