CREATE TABLE [dbo].[EMPMACLOG]
(
[EMPCODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLIENTNAME] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MACADDR] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LOGTIME] [datetime] NOT NULL,
[OPERATION] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OPERCODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMPMACLOG] ADD CONSTRAINT [PK__EMPMACLOG__40CE2476] PRIMARY KEY CLUSTERED  ([EMPCODE], [MACADDR], [LOGTIME]) ON [PRIMARY]
GO
