CREATE TABLE [dbo].[RFPCKGENBILLS]
(
[SPID] [int] NOT NULL,
[BILLNAME] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_RFPCKGENBILLS_SPID] ON [dbo].[RFPCKGENBILLS] ([SPID]) ON [PRIMARY]
GO
