CREATE TABLE [dbo].[STKOUTGFTDTL]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LISTNO] [int] NOT NULL,
[AGANUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MATCHTIME] [int] NOT NULL,
[GDGID] [int] NULL,
[ALCQTY] [decimal] (24, 2) NULL,
[GFTGID] [int] NULL,
[GFTQTY] [decimal] (24, 2) NULL,
[GFTWRH] [int] NULL,
[FLAG] [smallint] NOT NULL,
[INVTAG] [smallint] NOT NULL CONSTRAINT [DF__STKOUTGFT__INVTA__23782950] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STKOUTGFTDTL] ADD CONSTRAINT [PK__STKOUTGFTDTL__246C4D89] PRIMARY KEY CLUSTERED  ([CLS], [NUM], [LISTNO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [STKOUTGFTDTL_GDGID] ON [dbo].[STKOUTGFTDTL] ([GDGID]) ON [PRIMARY]
GO
