CREATE TABLE [dbo].[NPRMRTNPNTAGMEXGDDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPRMRTNPNTAGMEXGDDTL] ADD CONSTRAINT [PK__NPRMRTNPNTAGMEXG__258DBC50] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) ON [PRIMARY]
GO
