CREATE TABLE [dbo].[TAXSORTH]
(
[GID] [int] NOT NULL,
[CODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PROVINCE] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TAXSORTH] ADD CONSTRAINT [PK__TAXSORTH__C51F0F3E7F96294D] PRIMARY KEY CLUSTERED  ([GID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_TAXSORTH_TYPE] ON [dbo].[TAXSORTH] ([CODE]) ON [PRIMARY]
GO
