CREATE TABLE [dbo].[POLYPRCPRMDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[DEPT] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VENDOR] [int] NULL,
[BRAND] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[POLYPRCPRMDTL] ADD CONSTRAINT [PK__POLYPRCPRMDTL__359A06E7] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_POLYPRCPRMDTL_SCOPE] ON [dbo].[POLYPRCPRMDTL] ([NUM], [DEPT], [VENDOR], [BRAND]) ON [PRIMARY]
GO
