CREATE TABLE [dbo].[VOUCHERACTBCKVOUUSEDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[VOUCHERNUM] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VOUCHERAMT] [decimal] (24, 2) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERACTBCKVOUUSEDTL] ADD CONSTRAINT [PK__VOUCHERACTBCKVOU__6828B410] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
