CREATE TABLE [dbo].[FAPRODUCTS]
(
[PDCODE] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PDNAME] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PDVERSION] [varchar] (24) COLLATE Chinese_PRC_CI_AS NULL,
[PDRELEASE] [varchar] (36) COLLATE Chinese_PRC_CI_AS NULL,
[PDNOTE] [varchar] (200) COLLATE Chinese_PRC_CI_AS NULL,
[PDIMAGE] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NULL,
[PDVISIBLE] [int] NOT NULL CONSTRAINT [DF__FAPRODUCT__PDVIS__04554F09] DEFAULT (1),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FAPRODUCTS] ADD CONSTRAINT [PK__FAPRODUCTS__05497342] PRIMARY KEY CLUSTERED  ([PDCODE]) ON [PRIMARY]
GO
