CREATE TABLE [dbo].[NPS3NOTSTAMPSCOGOODS]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[CLS] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GOODS] [int] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[OPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OPERTIME] [datetime] NOT NULL CONSTRAINT [DF__NPS3NOTST__OPERT__355ADB1C] DEFAULT (getdate()),
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPS3NOTSTAMPSCOGOODS] ADD CONSTRAINT [PK__NPS3NOTSTAMPSCOG__364EFF55] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
