CREATE TABLE [dbo].[NPROCDRPT]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[BWRH] [int] NOT NULL,
[BGDGID] [int] NOT NULL,
[DQ1] [money] NOT NULL CONSTRAINT [DF__NPROCDRPT__DQ1__4E60F0A7] DEFAULT (0),
[DT1] [money] NOT NULL CONSTRAINT [DF__NPROCDRPT__DT1__4F5514E0] DEFAULT (0),
[DI1] [money] NOT NULL CONSTRAINT [DF__NPROCDRPT__DI1__50493919] DEFAULT (0),
[DR1] [money] NOT NULL CONSTRAINT [DF__NPROCDRPT__DR1__513D5D52] DEFAULT (0),
[DD1] [money] NOT NULL CONSTRAINT [DF__NPROCDRPT__DD1__5231818B] DEFAULT (0),
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[RCV] [int] NOT NULL,
[SNDTIME] [datetime] NOT NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPROCDRPT] ADD CONSTRAINT [PK__NPROCDRPT__442B18F2] PRIMARY KEY CLUSTERED  ([ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
