CREATE TABLE [dbo].[ADVANCESALES]
(
[ASNUM] [int] NOT NULL,
[ASSTART] [datetime] NOT NULL,
[ASFINISH] [datetime] NOT NULL,
[TSSTART] [datetime] NULL,
[TSFINISH] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[NEEDTWICEBUY] [smallint] NOT NULL CONSTRAINT [DF__ADVANCESA__NEEDT__3763EA76] DEFAULT (1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ADVANCESALES] ADD CONSTRAINT [PK__ADVANCESALES__7BB8496C] PRIMARY KEY CLUSTERED  ([ASNUM]) ON [PRIMARY]
GO
