CREATE TABLE [dbo].[CRMDATAEXGWEBSERVERADDR]
(
[ADDR] [varchar] (200) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL CONSTRAINT [DF__CRMDATAEXGW__SRC__348F3D67] DEFAULT (1),
[SNDTIME] [datetime] NULL,
[CREATETIME] [datetime] NOT NULL CONSTRAINT [DF__CRMDATAEX__CREAT__358361A0] DEFAULT (getdate()),
[CREATOR] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__CRMDATAEX__LSTUP__367785D9] DEFAULT (getdate()),
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMDATAEX__LSTUP__376BAA12] DEFAULT ('未知[-]'),
[FLAG] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SYSUUID] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMDATAEX__SYSUU__385FCE4B] DEFAULT ('-'),
[FSENDTIME] [datetime] NOT NULL,
[FSRCORG] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FDESTORG] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMDATAEXGWEBSERVERADDR] ADD CONSTRAINT [PK__CRMDATAEXGWEBSER__3953F284] PRIMARY KEY CLUSTERED  ([FSRCORG], [FDESTORG], [FSENDTIME], [ADDR]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_CRMDATAEXGWEBADDR_FST] ON [dbo].[CRMDATAEXGWEBSERVERADDR] ([FSENDTIME]) ON [PRIMARY]
GO
