CREATE TABLE [dbo].[REPORTMODIFYLOG]
(
[TIME] [datetime] NOT NULL,
[EMPLOYEE] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[REPORTNAME] [varchar] (128) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ACTION] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CONTENT] [varchar] (200) COLLATE Chinese_PRC_CI_AS NULL,
[CONDITION] [varchar] (400) COLLATE Chinese_PRC_CI_AS NULL,
[QUERYTIME] [char] (20) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_LOG_TIME] ON [dbo].[REPORTMODIFYLOG] ([TIME]) ON [PRIMARY]
GO
