CREATE TABLE [dbo].[TA_LOG]
(
[LOGID] [int] NOT NULL IDENTITY(1, 1),
[OPERATIONID] [int] NOT NULL,
[HAPPENDATE] [datetime] NOT NULL,
[OPERATOR] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MEMO] [char] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TA_LOG] ADD CONSTRAINT [PK__TA_LOG__2C1E8537] PRIMARY KEY CLUSTERED  ([LOGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
