CREATE TABLE [dbo].[ORDERCOUNTERPLAN]
(
[NUM] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL,
[LASTMODIFYOPER] [char] (64) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__ORDERCOUN__LASTM__17A74F48] DEFAULT ('未知[-]'),
[LASTMODIFYTIME] [datetime] NOT NULL CONSTRAINT [DF__ORDERCOUN__LASTM__189B7381] DEFAULT (getdate()),
[GDGID] [int] NOT NULL,
[QTY1] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__ORDERCOUNT__QTY1__198F97BA] DEFAULT (0),
[QTY2] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__ORDERCOUNT__QTY2__1A83BBF3] DEFAULT (0),
[QTY3] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__ORDERCOUNT__QTY3__1B77E02C] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
