CREATE TABLE [dbo].[NSTOREORDQTY]
(
[ID] [int] NOT NULL,
[STOREGID] [int] NOT NULL,
[WRH] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[ORDQTY] [money] NOT NULL,
[RCV] [int] NOT NULL,
[TYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NSTOREORDQTY] ADD CONSTRAINT [PK__NSTOREORDQTY__436373F0] PRIMARY KEY CLUSTERED  ([ID], [STOREGID], [WRH], [GDGID]) ON [PRIMARY]
GO
