CREATE TABLE [dbo].[PROMPIR]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PRMNAME] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PRIORITY] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROMPIR] ADD CONSTRAINT [PK__PROMPIR__479986E8] PRIMARY KEY CLUSTERED  ([PRMNAME], [NUM]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [UQ_PROMPIR] ON [dbo].[PROMPIR] ([CLS], [PRIORITY]) ON [PRIMARY]
GO
