CREATE TABLE [dbo].[CNTRCHEQUELOG]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OPER] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ATIME] [datetime] NOT NULL,
[LINE] [int] NOT NULL,
[CONTENT] [char] (1000) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_CNTRCHEQUELOG_CML] ON [dbo].[CNTRCHEQUELOG] ([CLS], [NUM], [LINE]) ON [PRIMARY]
GO
