CREATE TABLE [dbo].[PSCARDDISCEFFECT]
(
[CARDTYPE] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BGNTIME] [datetime] NOT NULL,
[ENDTIME] [datetime] NOT NULL,
[ACTIVE] [smallint] NOT NULL CONSTRAINT [DF__PSCARDDIS__ACTIV__7A3A154E] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSCARDDISCEFFECT] ADD CONSTRAINT [PK__PSCARDDISCEFFECT__7B2E3987] PRIMARY KEY CLUSTERED  ([CARDTYPE], [BGNTIME], [ACTIVE]) ON [PRIMARY]
GO
