CREATE TABLE [dbo].[CMSTOREGRADEST]
(
[CMSCODE] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CMSTOREGRADEST] ADD CONSTRAINT [PK__CMSTOREGRADEST__2BB934ED] PRIMARY KEY CLUSTERED  ([CMSCODE], [STOREGID]) ON [PRIMARY]
GO
