CREATE TABLE [dbo].[FAFLOW]
(
[UUID] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL,
[PARENTUUID] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL,
[FOBJECTCOUNT] [int] NOT NULL,
[FCONNECTIONCOUNT] [int] NOT NULL,
[AORDER] [int] NOT NULL CONSTRAINT [DF__FAFLOW__AORDER__1768237D] DEFAULT (0),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__FAFLOW__LSTUPDTI__185C47B6] DEFAULT (getdate()),
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[STAT] [int] NOT NULL CONSTRAINT [DF__FAFLOW__STAT__19506BEF] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FAFLOW] ADD CONSTRAINT [PK__FAFLOW__1A449028] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
