CREATE TABLE [dbo].[FAFLOWLINEPOINTS]
(
[UUID] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [int] NOT NULL,
[LINE] [int] NOT NULL,
[FPX] [int] NOT NULL,
[FPY] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FAFLOWLINEPOINTS] ADD CONSTRAINT [PK__FAFLOWLINEPOINTS__2F3FAD0E] PRIMARY KEY CLUSTERED  ([UUID], [ITEMNO], [LINE]) ON [PRIMARY]
GO
