CREATE TABLE [dbo].[ORIPOSPRNMODULESET]
(
[MODULE] [smallint] NOT NULL,
[LINE] [smallint] NOT NULL,
[BLOCK] [smallint] NOT NULL,
[ALEFT] [smallint] NOT NULL,
[WIDTH] [smallint] NOT NULL,
[ALIGNMENT] [char] (1) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FONTSIZE] [smallint] NOT NULL,
[COLOR] [smallint] NOT NULL,
[EOL] [smallint] NOT NULL,
[CONTENT] [smallint] NOT NULL,
[FIXEDSTRING] [char] (255) COLLATE Chinese_PRC_CI_AS NULL,
[MODULESETCODE] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORIPOSPRNMODULESET] ADD CONSTRAINT [PK__ORIPOSPRNMODULES__5B0E7E4A] PRIMARY KEY CLUSTERED  ([MODULESETCODE], [MODULE], [LINE], [BLOCK]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
