CREATE TABLE [dbo].[STOREPRCSCHEME]
(
[STOREGID] [int] NOT NULL,
[CLS] [char] (8) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__STOREPRCSCH__CLS__5DAD55D8] DEFAULT ('核算售价'),
[CODE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SNDDATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STOREPRCSCHEME] ADD CONSTRAINT [PK__STOREPRCSCHEME__5CB9319F] PRIMARY KEY CLUSTERED  ([STOREGID], [CLS]) ON [PRIMARY]
GO
