CREATE TABLE [dbo].[PSCRMCONSCOREDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[POSNO] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLOWNO] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[AMOUNT] [decimal] (24, 2) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSCRMCONSCOREDTL] ADD CONSTRAINT [PK__PSCRMCONSCOREDTL__01DB3716] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
