CREATE TABLE [dbo].[GFTPRMSNDSALE]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[FLOWNO] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[QTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMSNDSA__QTY__0062608F] DEFAULT (0),
[AMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMSNDSA__AMT__015684C8] DEFAULT (0),
[BCKQTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMSND__BCKQT__024AA901] DEFAULT (0),
[BCKAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMSND__BCKAM__033ECD3A] DEFAULT (0),
[ADDQTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMSND__ADDQT__0432F173] DEFAULT (0),
[ADDAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMSND__ADDAM__052715AC] DEFAULT (0),
[SALETIME] [datetime] NOT NULL,
[DEDUCTAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__GFTPRMSND__DEDUC__061B39E5] DEFAULT (0),
[PRMTAG] [char] (10) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GFTPRMSNDSALE] ADD CONSTRAINT [PK__GFTPRMSNDSALE__7F6E3C56] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
