CREATE TABLE [dbo].[PayedDtl]
(
[ASETTLENO] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[WRH] [int] NOT NULL,
[BVDRGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PayedDtl] ADD CONSTRAINT [PK__PayedDtl__41C478EA] PRIMARY KEY CLUSTERED  ([ASETTLENO], [GDGID], [ADATE], [WRH], [BVDRGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
