CREATE TABLE [dbo].[NPRMTOPIC]
(
[RCV] [int] NOT NULL,
[ID] [int] NOT NULL,
[CODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [char] (255) COLLATE Chinese_PRC_CI_AS NULL,
[CREATOR] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NPRMTOPIC__CREAT__6E660DEA] DEFAULT ('未知[-]'),
[CREATETIME] [datetime] NOT NULL CONSTRAINT [DF__NPRMTOPIC__CREAT__6F5A3223] DEFAULT (getdate()),
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NPRMTOPIC__MODIF__704E565C] DEFAULT ('未知[-]'),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__NPRMTOPIC__LSTUP__71427A95] DEFAULT (getdate()),
[PRI] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPRMTOPIC__PRI__72369ECE] DEFAULT (0),
[TYPE] [smallint] NOT NULL,
[SRC] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPRMTOPIC] ADD CONSTRAINT [PK__NPRMTOPIC__732AC307] PRIMARY KEY CLUSTERED  ([ID], [SRC], [CODE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPRMTOPIC_TYPE] ON [dbo].[NPRMTOPIC] ([TYPE]) ON [PRIMARY]
GO
