CREATE TABLE [dbo].[NGFTPRMRULEMUTEX]
(
[RCV] [int] NOT NULL,
[ID] [int] NOT NULL,
[RCODE] [char] (18) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MUTEXCODE] [char] (18) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NGFTPRMRULEMUTEX] ADD CONSTRAINT [PK__NGFTPRMRULEMUTEX__5A886718] PRIMARY KEY CLUSTERED  ([RCV], [ID], [RCODE], [MUTEXCODE]) ON [PRIMARY]
GO
