CREATE TABLE [dbo].[WRTASKLOG]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[TASKID] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CATEGORY] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BEGINTIME] [datetime] NOT NULL,
[ENDTIME] [datetime] NULL,
[FILENAME] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[ERRCODE] [int] NOT NULL CONSTRAINT [DF__WRTASKLOG__ERRCO__45D5CC47] DEFAULT (0),
[ERRMSG] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WRTASKLOG] ADD CONSTRAINT [PK__WRTASKLOG__44E1A80E] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
