CREATE TABLE [dbo].[ALCPOOLGENBILLS]
(
[BILLNAME] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DTLCNT] [smallint] NOT NULL CONSTRAINT [DF__ALCPOOLGE__DTLCN__0CDC7AB6] DEFAULT (0),
[FLAG] [smallint] NOT NULL CONSTRAINT [DF__ALCPOOLGEN__FLAG__0DD09EEF] DEFAULT (0)
) ON [PRIMARY]
GO
