CREATE TABLE [dbo].[VDRLESSEEINV]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VDRGID] [int] NOT NULL,
[PAYRATE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__VDRLESSEE__PAYRA__76514875] DEFAULT (0),
[SHOPNO] [char] (30) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VDRLESSEEINV] ADD CONSTRAINT [PK__VDRLESSEEINV__77456CAE] PRIMARY KEY CLUSTERED  ([VDRGID]) ON [PRIMARY]
GO
