CREATE TABLE [dbo].[PSCTGDDISRULELOG]
(
[CARDTYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[GDQPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PSCTGDDIS__GDQPC__002E21BC] DEFAULT (1),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[OPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OPERTIME] [datetime] NOT NULL CONSTRAINT [DF__PSCTGDDIS__OPERT__012245F5] DEFAULT (getdate())
) ON [PRIMARY]
GO
