CREATE TABLE [dbo].[ALCBYSTOREDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[CASES] [money] NULL,
[QTY] [money] NOT NULL CONSTRAINT [DF__ALCBYSTORED__QTY__044734B5] DEFAULT (0),
[INVQTY] [money] NOT NULL,
[TOTAL] [money] NOT NULL CONSTRAINT [DF__ALCBYSTOR__TOTAL__053B58EE] DEFAULT (0),
[TAX] [money] NOT NULL CONSTRAINT [DF__ALCBYSTORED__TAX__062F7D27] DEFAULT (0),
[ASNQTY] [money] NULL CONSTRAINT [DF__alcbystor__ASNQT__310597EA] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ALCBYSTOREDTL] ADD CONSTRAINT [PK__AlcByStoreDtl__4CAF490D] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
