CREATE TABLE [dbo].[POSCONFIG]
(
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PRTMODE] [smallint] NULL CONSTRAINT [DF__POSCONFIG__PRTMO__006AEB82] DEFAULT (1),
[PRTSIDE] [smallint] NULL CONSTRAINT [DF__POSCONFIG__PRTSI__015F0FBB] DEFAULT (3),
[PRTHEAD] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[PRTMARK] [text] COLLATE Chinese_PRC_CI_AS NULL,
[PRTTAIL] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[PEQUIP] [smallint] NULL CONSTRAINT [DF__POSCONFIG__PEQUI__025333F4] DEFAULT (511),
[OTHERFLAG] [smallint] NULL,
[GOTONXTLINE] [smallint] NULL CONSTRAINT [DF__POSCONFIG__GOTON__0347582D] DEFAULT (1),
[BAKINTERVAL] [smallint] NULL CONSTRAINT [DF__POSCONFIG__BAKIN__043B7C66] DEFAULT (7),
[MAXQTTY] [money] NULL CONSTRAINT [DF__POSCONFIG__MAXQT__052FA09F] DEFAULT (500),
[COM1PARA] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[COM2PARA] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[COM3PARA] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[COM4PARA] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[COM5PARA] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[COM6PARA] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[PREC] [money] NULL CONSTRAINT [DF__POSCONFIG__PREC__0623C4D8] DEFAULT (0.01),
[ROUND] [money] NULL CONSTRAINT [DF__POSCONFIG__ROUND__0717E911] DEFAULT (0.005),
[POSITION] [smallint] NULL CONSTRAINT [DF__POSCONFIG__POSIT__080C0D4A] DEFAULT (2),
[WRH] [int] NULL CONSTRAINT [DF__POSCONFIG__WRH__09003183] DEFAULT (0),
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[HIGHDISCOUNT] [decimal] (5, 2) NOT NULL CONSTRAINT [DF__POSCONFIG__HIGHD__1F1E53DE] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[POSCONFIG] ADD CONSTRAINT [PK__POSCONFIG__70FDBF69] PRIMARY KEY CLUSTERED  ([POSNO]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
