CREATE TABLE [dbo].[pStaff]
(
[code] [char] (6) COLLATE Chinese_PRC_CI_AS NOT NULL,
[emptype] [char] (1) COLLATE Chinese_PRC_CI_AS NULL,
[cid] [char] (15) COLLATE Chinese_PRC_CI_AS NULL,
[name] [char] (8) COLLATE Chinese_PRC_CI_AS NULL,
[oldname] [char] (8) COLLATE Chinese_PRC_CI_AS NULL,
[evername] [char] (8) COLLATE Chinese_PRC_CI_AS NULL,
[sex] [char] (1) COLLATE Chinese_PRC_CI_AS NULL,
[birthday] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[home] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[haddr] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[naddr] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[zjxy] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[nation] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[cf] [char] (4) COLLATE Chinese_PRC_CI_AS NULL,
[nwh] [char] (2) COLLATE Chinese_PRC_CI_AS NULL,
[owh] [char] (2) COLLATE Chinese_PRC_CI_AS NULL,
[school] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[techan] [char] (60) COLLATE Chinese_PRC_CI_AS NULL,
[schdate] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[indate] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[grpno] [char] (6) COLLATE Chinese_PRC_CI_AS NULL,
[dptno] [char] (6) COLLATE Chinese_PRC_CI_AS NULL,
[wrkno] [char] (2) COLLATE Chinese_PRC_CI_AS NULL,
[prfno] [char] (2) COLLATE Chinese_PRC_CI_AS NULL,
[payno] [char] (2) COLLATE Chinese_PRC_CI_AS NULL,
[marry] [char] (1) COLLATE Chinese_PRC_CI_AS NULL,
[signdate] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[phone] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[armysrv] [char] (1) COLLATE Chinese_PRC_CI_AS NULL,
[deldate] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[notes] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[image] [image] NULL
) ON [PRIMARY]
GO
