CREATE TABLE [dbo].[NSALEORDER]
(
[ID] [int] NOT NULL,
[CLS] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SENDER] [int] NOT NULL,
[VENDOR] [int] NOT NULL CONSTRAINT [DF__NSALEORDE__VENDO__7351B2DD] DEFAULT (1),
[TOTAL] [money] NOT NULL CONSTRAINT [DF__NSALEORDE__TOTAL__7445D716] DEFAULT (0),
[TAX] [money] NOT NULL CONSTRAINT [DF__NSALEORDER__TAX__7539FB4F] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NSALEORDE__FILDA__762E1F88] DEFAULT (getdate()),
[PAYDATE] [datetime] NULL,
[PREPAY] [money] NULL,
[CHECKER] [int] NOT NULL CONSTRAINT [DF__NSALEORDE__CHECK__772243C1] DEFAULT (1),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__NSALEORDER__STAT__781667FA] DEFAULT (0),
[MODNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[RECEIVER] [int] NOT NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__NSALEORDE__RECCN__790A8C33] DEFAULT (0),
[NSTAT] [int] NOT NULL,
[SRC] [int] NOT NULL,
[RCV] [int] NOT NULL,
[SNDTIME] [datetime] NOT NULL,
[RCVTIME] [datetime] NULL,
[FRCCHK] [smallint] NOT NULL,
[TYPE] [smallint] NOT NULL,
[ALCCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[EXPDATE] [datetime] NULL,
[DLVBDATE] [datetime] NULL,
[DLVEDATE] [datetime] NULL,
[DLVADDR] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NSALEORDER] ADD CONSTRAINT [PK__NSALEORDER__725D8EA4] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NSALEORDER_TYPE] ON [dbo].[NSALEORDER] ([TYPE]) ON [PRIMARY]
GO
