CREATE TABLE [dbo].[SETTLEDEPT]
(
[CODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SETTLEDEPT] ADD CONSTRAINT [PK__SETTLEDEPT__0AABB02F] PRIMARY KEY CLUSTERED  ([CODE], [NAME]) ON [PRIMARY]
GO
