CREATE TABLE [dbo].[CSTMRPT]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[BCSTGID] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[BGDGID] [int] NOT NULL,
[CQ1] [money] NULL CONSTRAINT [DF__CSTMRPT__CQ1__595C0B59] DEFAULT (0),
[CQ2] [money] NULL CONSTRAINT [DF__CSTMRPT__CQ2__5A502F92] DEFAULT (0),
[CQ3] [money] NULL CONSTRAINT [DF__CSTMRPT__CQ3__5B4453CB] DEFAULT (0),
[CT1] [money] NULL CONSTRAINT [DF__CSTMRPT__CT1__5C387804] DEFAULT (0),
[CT2] [money] NULL CONSTRAINT [DF__CSTMRPT__CT2__5D2C9C3D] DEFAULT (0),
[CT3] [money] NULL CONSTRAINT [DF__CSTMRPT__CT3__5E20C076] DEFAULT (0),
[CT4] [money] NULL CONSTRAINT [DF__CSTMRPT__CT4__5F14E4AF] DEFAULT (0),
[DQ1] [money] NULL CONSTRAINT [DF__CSTMRPT__DQ1__600908E8] DEFAULT (0),
[DQ2] [money] NULL CONSTRAINT [DF__CSTMRPT__DQ2__60FD2D21] DEFAULT (0),
[DQ3] [money] NULL CONSTRAINT [DF__CSTMRPT__DQ3__61F1515A] DEFAULT (0),
[DT1] [money] NULL CONSTRAINT [DF__CSTMRPT__DT1__62E57593] DEFAULT (0),
[DT2] [money] NULL CONSTRAINT [DF__CSTMRPT__DT2__63D999CC] DEFAULT (0),
[DT3] [money] NULL CONSTRAINT [DF__CSTMRPT__DT3__64CDBE05] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CSTMRPT] ADD CONSTRAINT [PK__CSTMRPT__3BCADD1B] PRIMARY KEY CLUSTERED  ([ASETTLENO], [BCSTGID], [BGDGID], [BWRH], [ASTORE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
