CREATE TABLE [dbo].[PS3_ONLINECNTRRATESTORE]
(
[UUID] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PLATFORM] [varchar] (80) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CNTRNO] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DLINE] [smallint] NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3_ONLINECNTRRATESTORE] ADD CONSTRAINT [PK__PS3_ONLI__0C2ECB373CFF2A40] PRIMARY KEY CLUSTERED  ([UUID], [DLINE], [ITEMNO]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IDX_OLCNTRSTORE_STOREGID] ON [dbo].[PS3_ONLINECNTRRATESTORE] ([PLATFORM], [CNTRNO], [DLINE], [STOREGID]) ON [PRIMARY]
GO
