CREATE TABLE [dbo].[POLYPROMRANGEDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[DEPT] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VENDOR] [int] NULL,
[BRAND] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[ASTART] [datetime] NOT NULL CONSTRAINT [DF__POLYPROMR__ASTAR__4DFBA05D] DEFAULT ('1899.12.30 00:00:00'),
[AFINISH] [datetime] NOT NULL CONSTRAINT [DF__POLYPROMR__AFINI__4EEFC496] DEFAULT ('9999.12.31 23:59:59'),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[PREC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__POLYPROMRA__PREC__5A04B1EB] DEFAULT (1.0),
[ROUNDTYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__POLYPROMR__ROUND__5AF8D624] DEFAULT ('四舍五入')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[POLYPROMRANGEDTL] ADD CONSTRAINT [PK__POLYPROMRANGEDTL__4FE3E8CF] PRIMARY KEY CLUSTERED  ([NUM], [CLS], [LINE]) ON [PRIMARY]
GO
