CREATE TABLE [dbo].[COUPONEXCHANGE]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL,
[RECCNT] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL,
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHKDATE] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[PRNTIME] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[EXCHANGETIME] [datetime] NULL,
[COUABORTTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COUPONEXCHANGE] ADD CONSTRAINT [PK__COUPONEX__C7D1B76B00CA44A8] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
