CREATE TABLE [dbo].[VOUCHERCASHSTORETEMP]
(
[SPID] [int] NOT NULL,
[UUID] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERCASHSTORETEMP] ADD CONSTRAINT [PK__VOUCHERCASHSTORE__0A39DC3F] PRIMARY KEY CLUSTERED  ([SPID], [UUID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_VOUCHERCASHSTORETEMP_NUM] ON [dbo].[VOUCHERCASHSTORETEMP] ([SPID], [NUM]) ON [PRIMARY]
GO
