CREATE TABLE [dbo].[NGDINVCHGNOTIFYDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[OUTGDGID] [int] NOT NULL,
[INGDGID] [int] NOT NULL,
[RELQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NGDINVCHG__RELQT__409F433A] DEFAULT (1),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NGDINVCHGNOTIFYDTL] ADD CONSTRAINT [PK__NGDINVCHGNOTIFYD__41936773] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) ON [PRIMARY]
GO
