CREATE TABLE [dbo].[SVITCDTL]
(
[CLS] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[TCCLS] [char] (16) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TCCODE] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[TCTOTAL] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__SVITCDTL__TCTOTA__7349F341] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SVITCDTL] ADD CONSTRAINT [PK__SVITCDTL__60FDF878] PRIMARY KEY CLUSTERED  ([CLS], [NUM], [LINE]) ON [PRIMARY]
GO
