CREATE TABLE [dbo].[PSSORTSCORULELOG]
(
[CARDTYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SORTCODE] [varchar] (16) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[OPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OPERTIME] [datetime] NOT NULL CONSTRAINT [DF__PSSORTSCO__OPERT__3CFBFCE4] DEFAULT (getdate())
) ON [PRIMARY]
GO
