CREATE TABLE [dbo].[CRMMBRPROMSUBJINVDTL]
(
[RULEUUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MBRGID] [int] NOT NULL,
[CARDNUM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMMBRPROMSUBJINVDTL] ADD CONSTRAINT [PK__CRMMBRPROMSUBJIN__235CF1C9] PRIMARY KEY CLUSTERED  ([RULEUUID], [MBRGID], [CARDNUM]) ON [PRIMARY]
GO
