CREATE TABLE [dbo].[VDRYRPTLOG]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[BVDRGID] [int] NOT NULL,
[MWRH] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[BGDGID] [int] NOT NULL,
[SALE] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VDRYRPTLOG] ADD CONSTRAINT [PK__VDRYRPTLOG__3E3D3572] PRIMARY KEY CLUSTERED  ([ASTORE], [ASETTLENO], [MWRH], [BGDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
