CREATE TABLE [dbo].[PURCHASEORDERTRANSDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[REALAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PURCHASEO__REALA__75DC4729] DEFAULT (0),
[RECCNT] [int] NOT NULL CONSTRAINT [DF__PURCHASEO__RECCN__76D06B62] DEFAULT (0),
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PURCHASEORD__QTY__77C48F9B] DEFAULT (0),
[GUEST] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PURCHASEORDERTRANSDTL] ADD CONSTRAINT [PK__PURCHASEORDERTRA__78B8B3D4] PRIMARY KEY CLUSTERED  ([NUM], [CLS], [FLOWNO], [POSNO]) ON [PRIMARY]
GO
