CREATE TABLE [dbo].[SORTGOODS]
(
[ACODE] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SCODE] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GID] [int] NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__SORTGOODS__LSTUP__5A47A49F] DEFAULT (getdate()),
[SORTTARGET1] [money] NOT NULL CONSTRAINT [DF__SORTGOODS__SORTT__559A6020] DEFAULT ((-1))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SORTGOODS] ADD CONSTRAINT [PK__SORTGOODS__5B3BC8D8] PRIMARY KEY CLUSTERED  ([ACODE], [SCODE], [GID]) ON [PRIMARY]
GO
