CREATE TABLE [dbo].[CNTRDPTBILLLOG]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CNTRDPTBILLLOG] ADD CONSTRAINT [PK__CNTRDPTBILLLOG__4C446962] PRIMARY KEY CLUSTERED  ([TIME], [NUM], [CLS], [STAT]) ON [PRIMARY]
GO
