CREATE TABLE [dbo].[RTLBCKCURDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[CURRENCY] [smallint] NOT NULL,
[AMOUNT] [money] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RTLBCKCURDTL] ADD CONSTRAINT [PK__RTLBCKCURDTL__116A8EFB] PRIMARY KEY CLUSTERED  ([NUM], [ITEMNO]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
