CREATE TABLE [dbo].[PS3SCOREGOODSSTOREDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3SCOREGOODSSTOREDTL] ADD CONSTRAINT [PK__PS3SCOREGOODSSTO__56BBCEE7] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
