CREATE TABLE [dbo].[COLAMTRATE]
(
[ADATE] [datetime] NOT NULL,
[CURRENCYCODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[COLAMTRATE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__COLAMTRAT__COLAM__212697E1] DEFAULT (1.0000)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COLAMTRATE] ADD CONSTRAINT [PK__COLAMTRATE__221ABC1A] PRIMARY KEY CLUSTERED  ([ADATE], [CURRENCYCODE]) ON [PRIMARY]
GO
