CREATE TABLE [dbo].[GENFEE]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[GENCLS] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FEECLS] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[EXPLAIN] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL,
[CHARGEFLAG] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GENFEE] ADD CONSTRAINT [PK__GENFEE__5ADD6CD3] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
