CREATE TABLE [dbo].[PSNMKTIVGTDTLDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[ITEMNO] [int] NOT NULL,
[PROPCODE] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PROPNAME] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VALUE] [char] (255) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ID] [int] NOT NULL,
[RCV] [int] NULL,
[SRC] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSNMKTIVGTDTLDTL] ADD CONSTRAINT [PK__PSNMktIvgtDtlDtl__73891F0C] PRIMARY KEY CLUSTERED  ([NUM], [LINE], [ID], [ITEMNO], [SRC]) ON [PRIMARY]
GO
