CREATE TABLE [dbo].[LMTPRICE]
(
[LSTID] [char] (16) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL,
[LMTCLS] [smallint] NOT NULL CONSTRAINT [DF__LMTPRICE__LMTCLS__1F3A56BC] DEFAULT (0),
[GDGID] [int] NOT NULL,
[ASTART] [datetime] NOT NULL CONSTRAINT [DF__LMTPRICE__ASTART__202E7AF5] DEFAULT (getdate()),
[AFINISH] [datetime] NOT NULL CONSTRAINT [DF__LMTPRICE__AFINIS__21229F2E] DEFAULT ('9999.12.31 23:59:59'),
[QTYLMT] [money] NOT NULL CONSTRAINT [DF__LMTPRICE__QTYLMT__2216C367] DEFAULT (0),
[PRICE] [money] NOT NULL,
[SRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRCLINE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CardTypeCode] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__LMTPRICE__CardTy__0F4D6E29] DEFAULT ('-'),
[Launch] [datetime] NOT NULL CONSTRAINT [DF__LMTPRICE__Launch__10419262] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LMTPRICE] ADD CONSTRAINT [PK__LMTPRICE__1E463283] PRIMARY KEY NONCLUSTERED  ([LSTID], [STOREGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LMTPRICE] ADD CONSTRAINT [UQ__LMTPRICE__1D520E4A] UNIQUE NONCLUSTERED  ([STOREGID], [GDGID], [ASTART], [AFINISH]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
