CREATE TABLE [dbo].[PS3DISPROMDISCOUNT]
(
[UUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARDTYPE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DISCOUNTORIG] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3DISPRO__DISCO__35C0F6BD] DEFAULT (0),
[PROMGDDISCOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3DISPRO__PROMG__36B51AF6] DEFAULT (0),
[MINPROMDISCOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3DISPRO__MINPR__37A93F2F] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3DISPROMDISCOUNT] ADD CONSTRAINT [PK__PS3DISPROMDISCOU__389D6368] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3PROMDISCOUNT] ON [dbo].[PS3DISPROMDISCOUNT] ([CARDTYPE]) ON [PRIMARY]
GO
