CREATE TABLE [dbo].[CSTDRPT]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[BCSTGID] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[BGDGID] [int] NOT NULL,
[DQ1] [money] NULL CONSTRAINT [DF__CSTDRPT__DQ1__51BAE991] DEFAULT (0),
[DQ2] [money] NULL CONSTRAINT [DF__CSTDRPT__DQ2__52AF0DCA] DEFAULT (0),
[DQ3] [money] NULL CONSTRAINT [DF__CSTDRPT__DQ3__53A33203] DEFAULT (0),
[DT1] [money] NULL CONSTRAINT [DF__CSTDRPT__DT1__5497563C] DEFAULT (0),
[DT2] [money] NULL CONSTRAINT [DF__CSTDRPT__DT2__558B7A75] DEFAULT (0),
[DT3] [money] NULL CONSTRAINT [DF__CSTDRPT__DT3__567F9EAE] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CSTDRPT] ADD CONSTRAINT [PK__CSTDRPT__37FA4C37] PRIMARY KEY CLUSTERED  ([ASETTLENO], [ADATE], [BCSTGID], [BGDGID], [BWRH], [ASTORE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
