CREATE TABLE [dbo].[ALCGFTDTL]
(
[SRCNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL CONSTRAINT [DF__ALCGFTDTL__GDGID__1DBF4FFA] DEFAULT (0),
[ALCQTY] [decimal] (24, 2) NULL,
[GFTGID] [int] NOT NULL CONSTRAINT [DF__ALCGFTDTL__GFTGI__1EB37433] DEFAULT (0),
[GFTQTY] [decimal] (24, 2) NULL,
[GFTWRH] [int] NOT NULL CONSTRAINT [DF__ALCGFTDTL__GFTWR__1FA7986C] DEFAULT (0),
[GFTLMTQTY] [decimal] (24, 2) NULL,
[FLAG] [smallint] NOT NULL CONSTRAINT [DF__ALCGFTDTL__FLAG__209BBCA5] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ALCGFTDTL] ADD CONSTRAINT [PK__ALCGFTDTL__218FE0DE] PRIMARY KEY CLUSTERED  ([SRCNUM], [GDGID], [GFTGID], [FLAG]) ON [PRIMARY]
GO
