CREATE TABLE [dbo].[NCRMWEBEMP]
(
[GID] [int] NOT NULL,
[ISWEBUSER] [smallint] NOT NULL CONSTRAINT [DF__NCRMWEBEM__ISWEB__55311723] DEFAULT (0),
[WEBPWD] [varchar] (32) COLLATE Chinese_PRC_CI_AS NULL,
[STARTDATE] [datetime] NULL,
[ENDDATE] [datetime] NULL,
[INEFFECT] [smallint] NOT NULL CONSTRAINT [DF__NCRMWEBEM__INEFF__56253B5C] DEFAULT (0),
[STORE] [varchar] (32) COLLATE Chinese_PRC_CI_AS NULL,
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL CONSTRAINT [DF__NCRMWEBEMP__SRC__57195F95] DEFAULT (1),
[SNDTIME] [datetime] NULL,
[CREATETIME] [datetime] NOT NULL CONSTRAINT [DF__NCRMWEBEM__CREAT__580D83CE] DEFAULT (getdate()),
[CREATOR] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__NCRMWEBEM__LSTUP__5901A807] DEFAULT (getdate()),
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NCRMWEBEM__LSTUP__59F5CC40] DEFAULT ('未知[-]'),
[ID] [int] NOT NULL,
[RCV] [int] NULL,
[RCVTIME] [datetime] NULL,
[FRCCHK] [smallint] NOT NULL,
[NTYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SYSUUID] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NCRMWEBEM__SYSUU__5AE9F079] DEFAULT ('-')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCRMWEBEMP] ADD CONSTRAINT [PK__NCRMWEBEMP__5BDE14B2] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
