CREATE TABLE [dbo].[PS3SCORERULETOTALLOG]
(
[UUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OPER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OPERTIME] [datetime] NOT NULL CONSTRAINT [DF__PS3SCORER__OPERT__0F1F5844] DEFAULT (getdate()),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3SCORERULETOTALLOG] ADD CONSTRAINT [PK__PS3SCORERULETOTA__10137C7D] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
