CREATE TABLE [dbo].[CRMSCORECLEARSORTDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[CARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SORT] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SCORE] [decimal] (24, 2) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMSCORECLEARSORTDTL] ADD CONSTRAINT [PK__CRMSCORECLEARSOR__4CE387E0] PRIMARY KEY CLUSTERED  ([NUM], [LINE], [CARDNUM], [SORT]) ON [PRIMARY]
GO
