CREATE TABLE [dbo].[PRMDIRPRMOFFSET]
(
[PRMSEQ] [int] NOT NULL,
[PRMOFFSETNO] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRMDIRPRMOFFSET] ADD CONSTRAINT [PK__PRMDIRPRMOFFSET__7AC359DC] PRIMARY KEY CLUSTERED  ([PRMSEQ], [PRMOFFSETNO]) ON [PRIMARY]
GO
