CREATE TABLE [dbo].[NetFTPGROUP]
(
[GRPID] [int] NOT NULL,
[GrpName] [varchar] (60) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLSID] [int] NOT NULL CONSTRAINT [DF__NetFTPGRO__CLSID__692AC0D3] DEFAULT (0),
[RCVSelect] [text] COLLATE Chinese_PRC_CI_AS NULL,
[AutoRCVSPName] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[AutoRcvSelect] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[AutoRcvErrUpd] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SEQNO] [int] NULL,
[GRPDEALCHECK] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NetFTPGROUP] ADD CONSTRAINT [PK__NetFTPGROUP__68369C9A] PRIMARY KEY CLUSTERED  ([GRPID]) ON [PRIMARY]
GO
