CREATE TABLE [dbo].[PRMOFFSETDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SETTLENO] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[QPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PRMOFFSETDT__QPC__21F23596] DEFAULT (1),
[QPCSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PRMOFFSET__QPCST__22E659CF] DEFAULT ('1*1'),
[AGMNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PRMOFFSET__AGMNU__23DA7E08] DEFAULT (''),
[AGMLINE] [int] NULL,
[SAMT] [decimal] (24, 2) NULL,
[RAMT] [decimal] (24, 2) NULL,
[OFFSETPRC] [decimal] (24, 4) NULL,
[CNTINPRC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PRMOFFSET__CNTIN__24CEA241] DEFAULT (0),
[QTY] [decimal] (24, 4) NULL,
[START] [datetime] NOT NULL CONSTRAINT [DF__PRMOFFSET__START__25C2C67A] DEFAULT ('1899.12.30 00:00:00'),
[FINISH] [datetime] NOT NULL CONSTRAINT [DF__PRMOFFSET__FINIS__26B6EAB3] DEFAULT ('9999.12.31 23:59:59'),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[ALC] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PRMOFFSETDT__ALC__27AB0EEC] DEFAULT (0),
[TOTAL] [decimal] (24, 4) NULL,
[AMOUNT] [decimal] (24, 4) NULL,
[TAX] [decimal] (24, 4) NULL,
[DIFFPRC] [decimal] (24, 4) NULL,
[PAYQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PRMOFFSET__PAYQT__289F3325] DEFAULT (0),
[PAYAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PRMOFFSET__PAYAM__2993575E] DEFAULT (0),
[SQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PRMOFFSETD__SQTY__2A877B97] DEFAULT (0),
[AGMTABLENAME] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PRMOFFSET__AGMTA__2B7B9FD0] DEFAULT ('PRMOFFSETAGM')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRMOFFSETDTL] ADD CONSTRAINT [PK__PRMOFFSETDTL__2C6FC409] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PrmOffSetDtl_GdGid] ON [dbo].[PRMOFFSETDTL] ([GDGID]) ON [PRIMARY]
GO
