CREATE TABLE [dbo].[AVTBILLDTL2]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRCCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRCPOSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SRCNUM] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [INX_AVTBILLDTL2] ON [dbo].[AVTBILLDTL2] ([SRCCLS], [SRCNUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
