CREATE TABLE [dbo].[VDRAGMT]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[AGMTNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VDRGID] [int] NOT NULL,
[STARTDATE] [datetime] NOT NULL CONSTRAINT [DF__VDRAGMT__STARTDA__2DEC6179] DEFAULT (getdate()),
[FINISHDATE] [datetime] NOT NULL CONSTRAINT [DF__VDRAGMT__FINISHD__2EE085B2] DEFAULT (getdate()),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__VDRAGMT__FILDATE__2FD4A9EB] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__VDRAGMT__FILLER__30C8CE24] DEFAULT ('未知[-]'),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__VDRAGMT__STAT__31BCF25D] DEFAULT (0),
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[BUYER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__VDRAGMT__BUYER__32B11696] DEFAULT ('未知[-]'),
[ORGVISER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__VDRAGMT__RECCNT__33A53ACF] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VDRAGMT] ADD CONSTRAINT [PK__VDRAGMT__34995F08] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
