CREATE TABLE [dbo].[STOREBUY2]
(
[STOREGID] [int] NOT NULL,
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[SETTLENO] [int] NOT NULL,
[GID] [int] NOT NULL,
[QTY] [money] NOT NULL CONSTRAINT [DF__STOREBUY2__QTY__1A6B7FFE] DEFAULT (0),
[INPRC] [money] NOT NULL CONSTRAINT [DF__STOREBUY2__INPRC__1B5FA437] DEFAULT (0),
[PRICE] [money] NOT NULL CONSTRAINT [DF__STOREBUY2__PRICE__1C53C870] DEFAULT (0),
[REALAMT] [money] NOT NULL CONSTRAINT [DF__STOREBUY2__REALA__1D47ECA9] DEFAULT (0),
[FAVAMT] [money] NOT NULL CONSTRAINT [DF__STOREBUY2__FAVAM__1E3C10E2] DEFAULT (0),
[TAG] [smallint] NOT NULL CONSTRAINT [DF__STOREBUY2__TAG__1F30351B] DEFAULT (0),
[QPCGID] [int] NULL,
[PRMTAG] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[ASSISTANT] [int] NULL,
[WRH] [int] NULL CONSTRAINT [DF__STOREBUY2__WRH__20245954] DEFAULT (1),
[INVNO] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[COST] [money] NOT NULL CONSTRAINT [DF__STOREBUY2__COST__21187D8D] DEFAULT (0),
[DEALER] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STOREBUY2] ADD CONSTRAINT [PK__STOREBUY2__19775BC5] PRIMARY KEY CLUSTERED  ([STOREGID], [POSNO], [FLOWNO], [ITEMNO]) ON [PRIMARY]
GO
