CREATE TABLE [dbo].[CRMCARDSCOREH]
(
[CARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARRIER] [int] NOT NULL CONSTRAINT [DF__CRMCARDSC__CARRI__4853DCED] DEFAULT (1),
[SCORESORT] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMCARDSC__SCORE__49480126] DEFAULT ('-'),
[SCORESUBJECT] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCARDSC__SCORE__4A3C255F] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMCARDSCOREH] ADD CONSTRAINT [PK__CRMCARDSCOREH__4B304998] PRIMARY KEY CLUSTERED  ([CARDNUM], [CARRIER], [SCORESORT], [SCORESUBJECT]) ON [PRIMARY]
GO
