CREATE TABLE [dbo].[PS3SPECGDSCORE]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__PS3SPECGDS__STAT__44BC4EE6] DEFAULT (0),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__PS3SPECGD__FILDA__45B0731F] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[CHKDATE] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__PS3SPECGD__LSTUP__46A49758] DEFAULT (getdate()),
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PS3SPECGD__LSTUP__4798BB91] DEFAULT ('未知[-]'),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SETTLENO] [int] NOT NULL CONSTRAINT [DF__PS3SPECGD__SETTL__488CDFCA] DEFAULT (0),
[RECCNT] [int] NOT NULL,
[ABORTDATE] [datetime] NULL,
[ABORTER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[modnum] [char] (14) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3SPECGDSCORE] ADD CONSTRAINT [PK__PS3SPECGDSCORE__49810403] PRIMARY KEY CLUSTERED  ([NUM], [CLS]) ON [PRIMARY]
GO
