CREATE TABLE [dbo].[TOURSCONSUMELOG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [int] NOT NULL,
[FROMSTAT] [smallint] NULL,
[TOSTAT] [smallint] NOT NULL,
[OPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OPERTIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TOURSCONSUMELOG] ADD CONSTRAINT [PK__TOURSCONSUMELOG__5F4EB2E3] PRIMARY KEY CLUSTERED  ([NUM], [ITEMNO]) ON [PRIMARY]
GO
