CREATE TABLE [dbo].[ALCGFTAGM]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[ALCGID] [int] NOT NULL,
[STAT] [int] NOT NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__ALCGFTAGM__RECCN__0E7D0C6A] DEFAULT (0),
[START] [datetime] NOT NULL,
[FINISH] [datetime] NOT NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[CANCELER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CACLDATE] [datetime] NULL,
[LSTMODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ALCGFTAGM] ADD CONSTRAINT [PK__ALCGFTAGM__0F7130A3] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
