CREATE TABLE [dbo].[NIPA2]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[VENDOR] [int] NULL,
[CLIENT] [int] NULL,
[ADJCOST] [money] NOT NULL CONSTRAINT [DF__NIPA2__ADJCOST__786B6DB5] DEFAULT (0),
[ADJINCOST] [money] NOT NULL CONSTRAINT [DF__NIPA2__ADJINCOST__795F91EE] DEFAULT (0),
[ADJINVCOST] [money] NOT NULL CONSTRAINT [DF__NIPA2__ADJINVCOS__7A53B627] DEFAULT (0),
[ADJOUTCOST] [money] NOT NULL CONSTRAINT [DF__NIPA2__ADJOUTCOS__7B47DA60] DEFAULT (0),
[ADJALCAMT] [money] NOT NULL CONSTRAINT [DF__NIPA2__ADJALCAMT__7C3BFE99] DEFAULT (0),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NIPA2__FILDATE__7D3022D2] DEFAULT (getdate()),
[FILLER] [int] NOT NULL CONSTRAINT [DF__NIPA2__FILLER__7E24470B] DEFAULT (1),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__NIPA2__STAT__7F186B44] DEFAULT (0),
[CHECKER] [int] NULL,
[CHKDATE] [datetime] NULL,
[CAUSE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NIPA2__CAUSE__000C8F7D] DEFAULT ('供应商返利'),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NOT NULL,
[RCV] [int] NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[FRCFLAG] [smallint] NOT NULL CONSTRAINT [DF__NIPA2__FRCFLAG__0100B3B6] DEFAULT (1),
[NNOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NIPA2] ADD CONSTRAINT [PK__NIPA2__7777497C] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
