CREATE TABLE [dbo].[INVOICEDTL]
(
[NUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SHOULDPAYCLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SHOULDPAYNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SHOULDPAYINVTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__INVOICEDT__SHOUL__4A28AD74] DEFAULT (0),
[PYTOTAL] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__INVOICEDT__PYTOT__4B1CD1AD] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INVOICEDTL] ADD CONSTRAINT [PK__INVOICEDTL__4C10F5E6] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
