CREATE TABLE [dbo].[DEPT_STORE_GEOG_SHOP]
(
[BUILDING] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLOOR] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STORE] [int] NOT NULL,
[BUILDINGAREA] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__DEPT_STOR__BUILD__39CCEC83] DEFAULT (0),
[USABLEAREA] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__DEPT_STOR__USABL__3AC110BC] DEFAULT (0),
[RENTALAREA] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__DEPT_STOR__RENTA__3BB534F5] DEFAULT (0),
[CREATOR] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CREATIONTIME] [datetime] NOT NULL CONSTRAINT [DF__DEPT_STOR__CREAT__3CA9592E] DEFAULT (getdate()),
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__DEPT_STOR__LSTUP__3D9D7D67] DEFAULT (getdate()),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPT_STORE_GEOG_SHOP] ADD CONSTRAINT [PK__DEPT_STORE_GEOG___3E91A1A0] PRIMARY KEY CLUSTERED  ([BUILDING], [FLOOR], [CODE]) ON [PRIMARY]
GO
