CREATE TABLE [dbo].[PSMKTIVGTPROP]
(
[TYPECODE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TYPENAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[CODE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PROPCLS] [smallint] NOT NULL CONSTRAINT [DF__PSMKTIVGT__PROPC__1D3E965F] DEFAULT (0),
[PROPTYPE] [smallint] NOT NULL CONSTRAINT [DF__PSMKTIVGT__PROPT__1E32BA98] DEFAULT (0),
[NAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CREATOR] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CREATETIME] [datetime] NULL CONSTRAINT [DF__PSMKTIVGT__CREAT__1F26DED1] DEFAULT (getdate()),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSMKTIVGTPROP] ADD CONSTRAINT [PK__PSMKTIVGTPROP__1C4A7226] PRIMARY KEY CLUSTERED  ([TYPECODE], [CODE]) ON [PRIMARY]
GO
