CREATE TABLE [dbo].[GIFT]
(
[LSTID] [char] (16) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL,
[VENDOR] [int] NOT NULL,
[START] [datetime] NOT NULL CONSTRAINT [DF__GIFT__START__1176474A] DEFAULT ('1899.12.30 00:00:00'),
[FINISH] [datetime] NOT NULL CONSTRAINT [DF__GIFT__FINISH__126A6B83] DEFAULT ('9999.12.31 23:59:59'),
[GDGID] [int] NOT NULL,
[INQTY] [money] NOT NULL,
[GFTGID] [int] NOT NULL,
[GFTQTY] [money] NOT NULL,
[SRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRCLINE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GFTWRH] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GIFT] ADD CONSTRAINT [PK__GIFT__10822311] PRIMARY KEY CLUSTERED  ([LSTID], [STOREGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [gift_gdgid] ON [dbo].[GIFT] ([GDGID], [GFTGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
