CREATE TABLE [dbo].[CRMMBRPROMTYPEBILLDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[CARDNUM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARDTYPE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARRIER] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMMBRPROMTYPEBILLDTL] ADD CONSTRAINT [PK__CRMMBRPROMTYPEBI__1ABCBED0] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
