CREATE TABLE [dbo].[PS3_BAASEXCHGSTATE]
(
[ZIPFILENAME] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SYNSTATE] [varchar] (60) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CPNTNAME] [varchar] (60) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SYNTIME] [datetime] NOT NULL,
[FINISHED] [smallint] NOT NULL CONSTRAINT [DF__PS3_BAASE__FINIS__6339E1C1] DEFAULT ((0)),
[LSTUPDTIME] [datetime] NULL CONSTRAINT [DF__PS3_BAASE__LSTUP__642E05FA] DEFAULT (getdate()),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_BaasExchgState_Zfn] ON [dbo].[PS3_BAASEXCHGSTATE] ([ZIPFILENAME]) ON [PRIMARY]
GO
