CREATE TABLE [dbo].[CRMSCOREADJDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[CARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MEMBER] [int] NOT NULL,
[REVSCORE] [decimal] (24, 2) NOT NULL,
[SCOREADJ] [decimal] (24, 2) NOT NULL,
[ADJCAUSE] [char] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SCORESORT] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMSCOREA__SCORE__322F91A4] DEFAULT ('-')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMSCOREADJDTL] ADD CONSTRAINT [PK__CRMSCOREADJDTL__3323B5DD] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
