CREATE TABLE [dbo].[RETURNREASONS]
(
[CODE] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DESCRIPTION] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RETURNREASONS] ADD CONSTRAINT [PK__RETURNREASONS__2FA463CB] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
