CREATE TABLE [dbo].[CRMSTAMPSCORULELACSTORE]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMSTAMPSCORULELACSTORE] ADD CONSTRAINT [PK__CRMSTAMPSCORULEL__422AC655] PRIMARY KEY CLUSTERED  ([NUM], [STOREGID]) ON [PRIMARY]
GO
