CREATE TABLE [dbo].[NREALEXCHGDATA]
(
[RECVDATE] [datetime] NOT NULL,
[RCV] [int] NOT NULL,
[SRC] [int] NOT NULL,
[TGT] [int] NOT NULL,
[RECCNT] [int] NOT NULL,
[NTYPE] [int] NOT NULL,
[SENDTIME] [datetime] NULL,
[RECVTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NREALEXCHGDATA] ADD CONSTRAINT [PK__NREALEXCHGDATA__14489254] PRIMARY KEY CLUSTERED  ([RECVDATE], [RCV], [SRC], [TGT]) ON [PRIMARY]
GO
