CREATE TABLE [dbo].[BILLTOADJLOG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TIME] [datetime] NOT NULL,
[STAT] [int] NOT NULL,
[ACTION] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BILLTOADJLOG] ADD CONSTRAINT [PK__BILLTOADJLOG__6B6D9E61] PRIMARY KEY CLUSTERED  ([NUM], [TIME], [ACTION]) ON [PRIMARY]
GO
