CREATE TABLE [dbo].[POLYPROMTOTALSCHMDTLOCR]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLLINE] [int] NOT NULL,
[LOWAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__POLYPROMT__LOWAM__6202990A] DEFAULT (0),
[HIGHAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__POLYPROMT__HIGHA__62F6BD43] DEFAULT (99999999),
[DISCOUNT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__POLYPROMT__DISCO__63EAE17C] DEFAULT (0),
[FAVAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__POLYPROMT__FAVAM__64DF05B5] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[POLYPROMTOTALSCHMDTLOCR] ADD CONSTRAINT [PK__POLYPROMTOTALSCH__65D329EE] PRIMARY KEY CLUSTERED  ([CLS], [BILLNUM], [BILLLINE]) ON [PRIMARY]
GO
