CREATE TABLE [dbo].[EPSTASKCYCLE]
(
[ID] [int] NOT NULL,
[FLAG] [int] NOT NULL CONSTRAINT [DF__EPSTASKCYC__FLAG__7275CA99] DEFAULT (0),
[SNDTIME] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
