CREATE TABLE [dbo].[FAOPTIONS]
(
[OPTIONS] [varchar] (255) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OPTNAME] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[OPTPRIORITY] [int] NOT NULL CONSTRAINT [DF__FAOPTIONS__OPTPR__0B974975] DEFAULT (0),
[OPTLOCK] [int] NOT NULL CONSTRAINT [DF__FAOPTIONS__OPTLO__0C8B6DAE] DEFAULT (0),
[OPTMODULE] [int] NOT NULL CONSTRAINT [DF__FAOPTIONS__OPTMO__0D7F91E7] DEFAULT (0),
[OPTNOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FAOPTIONS] ADD CONSTRAINT [PK__FAOPTIONS__0E73B620] PRIMARY KEY CLUSTERED  ([OPTIONS]) ON [PRIMARY]
GO
