CREATE TABLE [dbo].[NDMDPRMLACDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NDMDPRMLACDTL] ADD CONSTRAINT [PK__NDMDPRMLACDTL__22CA2527] PRIMARY KEY CLUSTERED  ([SRC], [ID], [STOREGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
