CREATE TABLE [dbo].[VOUCHERGIVEDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[FLOWNO] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[EXAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__VOUCHERGI__EXAMT__50512A7F] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERGIVEDTL] ADD CONSTRAINT [PK__VOUCHERGIVEDTL__51454EB8] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [VOUCHERGIVEDTL_FLOWNO] ON [dbo].[VOUCHERGIVEDTL] ([FLOWNO]) ON [PRIMARY]
GO
