CREATE TABLE [dbo].[PSTASKMANSORTDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SORT] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSTASKMANSORTDTL] ADD CONSTRAINT [PK__PSTASKMANSORTDTL__14CAE29D] PRIMARY KEY CLUSTERED  ([NUM], [SORT]) ON [PRIMARY]
GO
