CREATE TABLE [dbo].[NGDBIND]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[BINDGID] [int] NOT NULL,
[EGID] [int] NOT NULL,
[QTY] [money] NOT NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[FRCUPD] [smallint] NOT NULL,
[TYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[TEAMID] [int] NULL,
[EQPCSTR] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NGDBIND__EQPCSTR__35C1C214] DEFAULT ('1*1')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NGDBIND] ADD CONSTRAINT [PK__NGDBIND__2882FE7D] PRIMARY KEY CLUSTERED  ([SRC], [ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
