CREATE TABLE [dbo].[NPROMGOODS]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[NO] [smallint] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[GDCODE] [varchar] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[RTLPRC] [decimal] (24, 4) NOT NULL,
[MBRPRC] [decimal] (24, 4) NULL,
[CNTRINPRC] [decimal] (24, 4) NOT NULL,
[COST] [decimal] (24, 4) NOT NULL,
[QPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPROMGOODS__QPC__7433F5D9] DEFAULT (1),
[QPCSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PRMDIV1] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPROMGOOD__PRMDI__75281A12] DEFAULT (100),
[PRMDIV2] [decimal] (24, 4) NOT NULL,
[PRMDIV3] [decimal] (24, 4) NOT NULL,
[QTY] [decimal] (24, 4) NOT NULL,
[FLAG] [int] NOT NULL,
[ISDLT] [smallint] NOT NULL CONSTRAINT [DF__NPROMGOOD__ISDLT__5CF2347C] DEFAULT (0),
[PREC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPROMGOODS__PREC__5FBD8B41] DEFAULT (1.0),
[ROUNDTYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NPROMGOOD__ROUND__60B1AF7A] DEFAULT ('四舍五入')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPROMGOODS] ADD CONSTRAINT [PK__NPROMGOODS__761C3E4B] PRIMARY KEY CLUSTERED  ([SRC], [ID], [NO], [FLAG], [LINE]) ON [PRIMARY]
GO
