CREATE TABLE [dbo].[LTDADJ]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__LTDADJ__FILDATE__7EEE4E12] DEFAULT (getdate()),
[FILLER] [int] NOT NULL CONSTRAINT [DF__LTDADJ__FILLER__7FE2724B] DEFAULT (1),
[CHECKER] [int] NOT NULL CONSTRAINT [DF__LTDADJ__CHECKER__00D69684] DEFAULT (1),
[ATYPE] [int] NOT NULL CONSTRAINT [DF__LTDADJ__ATYPE__01CABABD] DEFAULT (1),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__LTDADJ__STAT__02BEDEF6] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__LTDADJ__RECCNT__03B3032F] DEFAULT (0),
[LAUNCH] [datetime] NULL,
[EON] [smallint] NOT NULL CONSTRAINT [DF__LTDADJ__EON__04A72768] DEFAULT (1),
[SRC] [int] NOT NULL CONSTRAINT [DF__LTDADJ__SRC__059B4BA1] DEFAULT (1),
[SRCNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[KEEPATYPE] [int] NOT NULL CONSTRAINT [DF__LTDADJ__KEEPATYP__1B82CD24] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LTDADJ] ADD CONSTRAINT [PK__LTDADJ__7DFA29D9] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [LTDADJ_FILDATE] ON [dbo].[LTDADJ] ([FILDATE]) ON [PRIMARY]
GO
