CREATE TABLE [dbo].[PS3SCONSCORE]
(
[UUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BGNDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[NSCORE] [int] NOT NULL CONSTRAINT [DF__PS3SCONSC__NSCOR__2B43684A] DEFAULT (1),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3SCONSCORE] ADD CONSTRAINT [PK__PS3SCONSCORE__2C378C83] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
