CREATE TABLE [dbo].[NCTCNTRRATEGUARDCHG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VERSION] [smallint] NOT NULL,
[LINE] [smallint] NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[OTHERCNTRNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OTHERCHGCODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCTCNTRRATEGUARDCHG] ADD CONSTRAINT [PK__NCTCNTRRATEGUARD__41FE471E] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE], [ITEMNO]) ON [PRIMARY]
GO
