CREATE TABLE [dbo].[NGOODSAPPFIELD]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[FIELDNAME] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NGOODSAPPFIELD] ADD CONSTRAINT [PK__NGOODSAPPFIELD__03FDE749] PRIMARY KEY CLUSTERED  ([SRC], [ID], [FIELDNAME]) ON [PRIMARY]
GO
