CREATE TABLE [dbo].[NCURRENCY]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[CODE] [smallint] NOT NULL,
[NAME] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FAVRATE] [decimal] (24, 4) NOT NULL,
[CASHIER] [smallint] NOT NULL CONSTRAINT [DF__NCURRENCY__CASHI__45C8AF14] DEFAULT (1),
[CHANGE] [smallint] NOT NULL CONSTRAINT [DF__NCURRENCY__CHANG__46BCD34D] DEFAULT (1),
[ByDevice] [smallint] NOT NULL CONSTRAINT [DF__NCURRENCY__ByDev__47B0F786] DEFAULT (0),
[SndtoFg] [smallint] NOT NULL CONSTRAINT [DF__NCURRENCY__Sndto__48A51BBF] DEFAULT (1),
[FAVRPTRATE] [decimal] (9, 4) NOT NULL CONSTRAINT [DF__NCURRENCY__FAVRP__49993FF8] DEFAULT (0),
[FAVRPTRATEDENO] [decimal] (9, 4) NOT NULL CONSTRAINT [DF__NCURRENCY__FAVRP__4A8D6431] DEFAULT (100),
[HighLmtDis] [decimal] (5, 2) NOT NULL CONSTRAINT [DF__NCURRENCY__HighL__4B81886A] DEFAULT (0),
[PayByCash] [smallint] NOT NULL CONSTRAINT [DF__NCURRENCY__PayBy__4C75ACA3] DEFAULT (1),
[BEGINDATE] [datetime] NOT NULL CONSTRAINT [DF__NCURRENCY__BEGIN__4D69D0DC] DEFAULT (getdate()),
[ENDDATE] [datetime] NOT NULL CONSTRAINT [DF__NCURRENCY__ENDDA__4E5DF515] DEFAULT ('2099.12.31 23:59:59'),
[DisUseAcnt] [smallint] NOT NULL CONSTRAINT [DF__NCURRENCY__DisUs__33C9FA6A] DEFAULT (0),
[IsInSumTotal] [smallint] NOT NULL CONSTRAINT [DF__NCURRENCY__IsInS__3C2A3641] DEFAULT (1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCURRENCY] ADD CONSTRAINT [PK__NCURRENCY__4F52194E] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
