CREATE TABLE [dbo].[NINPRCADJNOTIFYDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[DEFPRC] [decimal] (24, 4) NULL,
[DIFFPRC] [decimal] (24, 4) NULL,
[PLANQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NINPRCADJ__PLANQ__16DD4841] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[OLDINPRC] [money] NOT NULL CONSTRAINT [DF__NINPRCADJ__OLDIN__31F13130] DEFAULT (0),
[OLDRTLPRC] [money] NOT NULL CONSTRAINT [DF__NINPRCADJ__OLDRT__32E55569] DEFAULT (0),
[OLDCNTINPRC] [money] NOT NULL CONSTRAINT [DF__NINPRCADJ__OLDCN__33D979A2] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NINPRCADJNOTIFYDTL] ADD CONSTRAINT [PK__NINPRCADJNOTIFYD__17D16C7A] PRIMARY KEY CLUSTERED  ([LINE], [SRC], [ID]) ON [PRIMARY]
GO
