CREATE TABLE [dbo].[PSTALLYAREA]
(
[CODE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[AREACODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSTALLYAREA] ADD CONSTRAINT [PK__PSTALLYAREA__036B4C71] PRIMARY KEY CLUSTERED  ([CODE], [AREACODE]) ON [PRIMARY]
GO
