CREATE TABLE [dbo].[PSRESOURCECATEGORY]
(
[NAME] [char] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ISPREDEF] [smallint] NOT NULL CONSTRAINT [DF__PSRESOURC__ISPRE__73B40795] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSRESOURCECATEGORY] ADD CONSTRAINT [PK__PSRESOURCECATEGO__74A82BCE] PRIMARY KEY CLUSTERED  ([NAME]) ON [PRIMARY]
GO
