CREATE TABLE [dbo].[CRMCARDDESDTL]
(
[CARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BALANCE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCARDDE__BALAN__1C755AAF] DEFAULT (0),
[CONSUME] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCARDDE__CONSU__1D697EE8] DEFAULT (0),
[BANTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCARDDE__BANTO__1E5DA321] DEFAULT (0),
[ADJMONEY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCARDDE__ADJMO__1F51C75A] DEFAULT (0),
[ADJMONEYTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMCARDDESDTL] ADD CONSTRAINT [PK__CRMCARDDESDTL__2045EB93] PRIMARY KEY CLUSTERED  ([CARDNUM]) ON [PRIMARY]
GO
