CREATE TABLE [dbo].[STORECERT]
(
[STOREGID] [int] NOT NULL,
[SHOPCARD] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[ACCREDITNO] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[LTAXACCOUNT] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[TOBACCOCARD] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[NTAXACCOUNT] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[TABCER] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STORECERT] ADD CONSTRAINT [PK__STORECERT__24F728C5] PRIMARY KEY CLUSTERED  ([STOREGID]) ON [PRIMARY]
GO
