CREATE TABLE [dbo].[PSGDLISTTYPE]
(
[TYPEDES] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[IMAGEINDEX] [int] NOT NULL CONSTRAINT [DF__PSGDLISTT__IMAGE__393D4D3D] DEFAULT (0),
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__PSGDLISTT__LSTUP__3A317176] DEFAULT (getdate()),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSGDLISTTYPE] ADD CONSTRAINT [PK__PSGDLISTTYPE__3B2595AF] PRIMARY KEY CLUSTERED  ([TYPEDES]) ON [PRIMARY]
GO
