CREATE TABLE [dbo].[NCRMCARDHST]
(
[ACTION] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NCRMCARDH__FILDA__00CD403A] DEFAULT (getdate()),
[STORE] [int] NOT NULL,
[CARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OLDCARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[OLDBYDATE] [datetime] NULL,
[NEWBYDATE] [datetime] NULL,
[OPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[CARRIER] [int] NOT NULL CONSTRAINT [DF__NCRMCARDH__CARRI__01C16473] DEFAULT (1),
[CARDCOST] [decimal] (24, 2) NULL,
[CARDTYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[LSTSNDTIME] [datetime] NULL,
[SENDER] [int] NULL,
[CHARGE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCRMCARDH__CHARG__02B588AC] DEFAULT (0),
[SAVETYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NCRMCARDH__SAVET__03A9ACE5] DEFAULT ('现金'),
[CHECKNO] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHECKID] [int] NOT NULL CONSTRAINT [DF__NCRMCARDH__CHECK__049DD11E] DEFAULT (0),
[VERSION] [char] (9) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NCRMCARDH__VERSI__0591F557] DEFAULT ('030000000'),
[NUM] [char] (26) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[SNDTIME] [datetime] NOT NULL CONSTRAINT [DF__NCRMCARDH__SNDTI__06861990] DEFAULT (getdate()),
[RCV] [int] NULL,
[RCVTIME] [datetime] NULL,
[FRCCHK] [smallint] NOT NULL,
[NTYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [char] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCRMCARDHST] ADD CONSTRAINT [PK__NCRMCARDHST__077A3DC9] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
