CREATE TABLE [dbo].[PSSUMSORT]
(
[CODE] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLAG] [int] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSSUMSORT] ADD CONSTRAINT [PK__PSSUMSORT__03C37F88] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
