CREATE TABLE [dbo].[STORESTAT]
(
[UUID] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL,
[BEGINDATE] [datetime] NOT NULL,
[STATTYPENAME] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOPDAYS] [smallint] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STORESTAT] ADD CONSTRAINT [PK__STORESTAT__50A302DE] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_STORESTATSTORE] ON [dbo].[STORESTAT] ([STOREGID]) ON [PRIMARY]
GO
