CREATE TABLE [dbo].[EPSSENDDIRALC]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STORE] [int] NOT NULL,
[FLAG] [int] NOT NULL CONSTRAINT [DF__EPSSENDDIR__FLAG__199A84B2] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EPSSENDDIRALC] ADD CONSTRAINT [PK__EPSSENDDIRALC__1A8EA8EB] PRIMARY KEY CLUSTERED  ([NUM], [STORE]) ON [PRIMARY]
GO
