CREATE TABLE [dbo].[MXFPOOL]
(
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[POSNO] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__MXFPOOL__FILDATE__2831F175] DEFAULT (getdate()),
[OPER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[OCRDATE] [datetime] NOT NULL CONSTRAINT [DF__MXFPOOL__OCRDATE__292615AE] DEFAULT (getdate()),
[TOSTORE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OPPNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[GDCODE] [varchar] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__MXFPOOL__QTY__2A1A39E7] DEFAULT (0),
[PRICE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__MXFPOOL__PRICE__2B0E5E20] DEFAULT (0),
[TOID] [int] NULL,
[TONUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[TOCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[bPosNo2StoreCode] [int] NOT NULL CONSTRAINT [DF__MXFPOOL__bPosNo2__2C028259] DEFAULT (0)
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_MXFP_ID] ON [dbo].[MXFPOOL] ([ID], [NUM], [LINE]) ON [PRIMARY]
GO
