CREATE TABLE [dbo].[ZHLEASE]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__ZHLEASE__NUM__18784A94] DEFAULT (' '),
[CLIENT] [int] NOT NULL CONSTRAINT [DF__ZHLEASE__CLIENT__196C6ECD] DEFAULT (1),
[PROJECT] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__ZHLEASE__PROJECT__1A609306] DEFAULT (' '),
[PLACE] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[SQUARE] [money] NOT NULL CONSTRAINT [DF__ZHLEASE__SQUARE__1B54B73F] DEFAULT (0),
[SIGNDATE] [datetime] NOT NULL,
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[YEARTOTAL] [money] NOT NULL CONSTRAINT [DF__ZHLEASE__YEARTOT__1C48DB78] DEFAULT (0),
[PAYDATE] [datetime] NOT NULL,
[TOTAL] [money] NOT NULL CONSTRAINT [DF__ZHLEASE__TOTAL__1D3CFFB1] DEFAULT (0),
[ALLTOTAL] [money] NOT NULL CONSTRAINT [DF__ZHLEASE__ALLTOTA__1E3123EA] DEFAULT (0),
[FILLER] [int] NOT NULL CONSTRAINT [DF__ZHLEASE__FILLER__1F254823] DEFAULT (1),
[MODIFIER] [int] NOT NULL CONSTRAINT [DF__ZHLEASE__MODIFIE__20196C5C] DEFAULT (1),
[UPDATETIME] [datetime] NOT NULL,
[MEMO] [char] (50) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ZHLEASE] ADD CONSTRAINT [PK__ZHLEASE__1784265B] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
