CREATE TABLE [dbo].[OUTMRPTX]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[BGDGID] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[BCSTGID] [int] NOT NULL,
[DTN1] [money] NOT NULL CONSTRAINT [DF__OUTMRPTX__DTN1__2D2A1A0E] DEFAULT (0),
[DTN2] [money] NOT NULL CONSTRAINT [DF__OUTMRPTX__DTN2__2E1E3E47] DEFAULT (0),
[DTN3] [money] NOT NULL CONSTRAINT [DF__OUTMRPTX__DTN3__2F126280] DEFAULT (0),
[DTN4] [money] NOT NULL CONSTRAINT [DF__OUTMRPTX__DTN4__300686B9] DEFAULT (0),
[DTN5] [money] NOT NULL CONSTRAINT [DF__OUTMRPTX__DTN5__30FAAAF2] DEFAULT (0),
[DTN6] [money] NOT NULL CONSTRAINT [DF__OUTMRPTX__DTN6__31EECF2B] DEFAULT (0),
[DTN7] [money] NOT NULL CONSTRAINT [DF__OUTMRPTX__DTN7__32E2F364] DEFAULT (0),
[DTN8] [money] NOT NULL CONSTRAINT [DF__OUTMRPTX__DTN8__33D7179D] DEFAULT (0),
[DTN9] [money] NOT NULL CONSTRAINT [DF__OUTMRPTX__DTN9__34CB3BD6] DEFAULT (0),
[DTX1] [money] NOT NULL CONSTRAINT [DF__OUTMRPTX__DTX1__35BF600F] DEFAULT (0),
[DTX2] [money] NOT NULL CONSTRAINT [DF__OUTMRPTX__DTX2__36B38448] DEFAULT (0),
[DTX3] [money] NOT NULL CONSTRAINT [DF__OUTMRPTX__DTX3__37A7A881] DEFAULT (0),
[DTX4] [money] NOT NULL CONSTRAINT [DF__OUTMRPTX__DTX4__389BCCBA] DEFAULT (0),
[DTX5] [money] NOT NULL CONSTRAINT [DF__OUTMRPTX__DTX5__398FF0F3] DEFAULT (0),
[DTX6] [money] NOT NULL CONSTRAINT [DF__OUTMRPTX__DTX6__3A84152C] DEFAULT (0),
[DTX7] [money] NOT NULL CONSTRAINT [DF__OUTMRPTX__DTX7__3B783965] DEFAULT (0),
[DTX8] [money] NOT NULL CONSTRAINT [DF__OUTMRPTX__DTX8__3C6C5D9E] DEFAULT (0),
[DTX9] [money] NOT NULL CONSTRAINT [DF__OUTMRPTX__DTX9__3D6081D7] DEFAULT (0),
[DIN1] [money] NOT NULL CONSTRAINT [DF__OUTMRPTX__DIN1__3E54A610] DEFAULT (0),
[DIN2] [money] NOT NULL CONSTRAINT [DF__OUTMRPTX__DIN2__3F48CA49] DEFAULT (0),
[DIN3] [money] NOT NULL CONSTRAINT [DF__OUTMRPTX__DIN3__403CEE82] DEFAULT (0),
[DIN4] [money] NOT NULL CONSTRAINT [DF__OUTMRPTX__DIN4__413112BB] DEFAULT (0),
[DIN5] [money] NOT NULL CONSTRAINT [DF__OUTMRPTX__DIN5__422536F4] DEFAULT (0),
[DIN6] [money] NOT NULL CONSTRAINT [DF__OUTMRPTX__DIN6__43195B2D] DEFAULT (0),
[DIN7] [money] NOT NULL CONSTRAINT [DF__OUTMRPTX__DIN7__440D7F66] DEFAULT (0),
[DIN8] [money] NOT NULL CONSTRAINT [DF__OUTMRPTX__DIN8__4501A39F] DEFAULT (0),
[DIN9] [money] NOT NULL CONSTRAINT [DF__OUTMRPTX__DIN9__45F5C7D8] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OUTMRPTX] ADD CONSTRAINT [PK__OUTMRPTX__5FD33367] PRIMARY KEY CLUSTERED  ([ASETTLENO], [BGDGID], [BCSTGID], [BWRH], [ASTORE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
