CREATE TABLE [dbo].[FAQUERYSERVER]
(
[CODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SERVERADDR] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DBNAME] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[CREATOR] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__FAQUERYSE__CREAT__2092665B] DEFAULT ('未知[-]'),
[CREATETIME] [datetime] NOT NULL CONSTRAINT [DF__FAQUERYSE__CREAT__21868A94] DEFAULT (getdate()),
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__FAQUERYSE__LSTUP__227AAECD] DEFAULT ('未知[-]'),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__FAQUERYSE__LSTUP__236ED306] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FAQUERYSERVER] ADD CONSTRAINT [PK__FAQUERYSERVER__2462F73F] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
