CREATE TABLE [dbo].[CRMPRESENTSCORULELOG]
(
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[OPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OPERTIME] [datetime] NOT NULL CONSTRAINT [DF__CRMPRESEN__OPERT__1C8F2D52] DEFAULT (getdate())
) ON [PRIMARY]
GO
