CREATE TABLE [dbo].[VDRCERTF]
(
[VDRCODE] [char] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CERTFNAME] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[START] [datetime] NOT NULL,
[FINISH] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VDRCERTF] ADD CONSTRAINT [PK__VDRCERTF__0004CFE1] PRIMARY KEY CLUSTERED  ([VDRCODE], [CERTFNAME]) ON [PRIMARY]
GO
