CREATE TABLE [dbo].[STOREOPERSCHEMELOG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TIME] [datetime] NOT NULL,
[STAT] [int] NOT NULL,
[ACTION] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STOREOPERSCHEMELOG] ADD CONSTRAINT [PK__STOREOPERSCHEMEL__287515F3] PRIMARY KEY CLUSTERED  ([NUM], [TIME], [ACTION]) ON [PRIMARY]
GO
