CREATE TABLE [dbo].[RTLDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SETTLENO] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[CASES] [money] NULL,
[QTY] [money] NOT NULL,
[PRICE] [money] NOT NULL,
[DISCOUNT] [money] NOT NULL CONSTRAINT [DF__RTLDTL__DISCOUNT__26B226A9] DEFAULT (100),
[INPRICE] [money] NULL,
[ALCPRC] [money] NULL,
[AMOUNT] [money] NOT NULL,
[RTLPRC] [money] NOT NULL,
[INPRC] [money] NOT NULL,
[SUBWRH] [int] NULL,
[DSPSUBWRH] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[TAX] [money] NOT NULL,
[LXGDNAME] [char] (50) COLLATE Chinese_PRC_CI_AS NULL,
[LXGDSPEC] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[LXGDMUNIT] [char] (6) COLLATE Chinese_PRC_CI_AS NULL,
[LXGDTM] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[INVAMT] [money] NULL,
[COST] [money] NOT NULL CONSTRAINT [DF__RTLDTL__COST__63A55AF9] DEFAULT (0),
[CURINPRC] [decimal] (14, 4) NOT NULL CONSTRAINT [DF__RtlDtl__CURINPRC__2773A2BD] DEFAULT (0),
[REDCARDCOST] [decimal] (24, 4) NULL,
[BLUECARDCOST] [decimal] (24, 4) NULL,
[VOUAMT] [money] NULL,
[GFTFLAG] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RTLDTL] ADD CONSTRAINT [PK__RTLDTL__1446FBA6] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
