CREATE TABLE [dbo].[CKINVSCHEME]
(
[NUM] [int] NOT NULL,
[NAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[WRHCODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SORTCODE] [varchar] (13) COLLATE Chinese_PRC_CI_AS NULL,
[VDRCODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[F2FROM] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL,
[F2TO] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL,
[SUBWRHCODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[F3] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL,
[TM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[CKALL] [smallint] NOT NULL CONSTRAINT [DF__CKINVSCHE__CKALL__4EEE2DE8] DEFAULT (0),
[FILERSTR] [varchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[FILERSQL] [varchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[CKBLANKUM] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CKINVSCHEME] ADD CONSTRAINT [PK__CKINVSCHEME__4DFA09AF] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
