CREATE TABLE [dbo].[NGFTPRMDTL]
(
[RCV] [int] NOT NULL,
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[RULECODE] [char] (18) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NGFTPRMDTL] ADD CONSTRAINT [PK__NGFTPRMDTL__3DEC286A] PRIMARY KEY CLUSTERED  ([RCV], [ID], [LINE]) ON [PRIMARY]
GO
