CREATE TABLE [dbo].[SCOPRIZE]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__SCOPRIZE__FILDAT__434E6557] DEFAULT (getdate()),
[FILLER] [int] NOT NULL,
[CHKDATE] [datetime] NULL,
[CHECKER] [int] NULL,
[CARRIER] [int] NOT NULL,
[CARD] [int] NULL,
[OLDSCORE] [money] NOT NULL,
[PRZSCORE] [money] NOT NULL,
[PRIZE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__SCOPRIZE__STAT__44428990] DEFAULT (0),
[MODNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SCOPRIZE] WITH NOCHECK ADD CONSTRAINT [SCOPRIZE_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[SCOPRIZE] ADD CONSTRAINT [PK__SCOPRIZE__1AF3F935] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
