CREATE TABLE [dbo].[PSTASKRESULTDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL,
[ITEMNO] [int] NOT NULL,
[LINE] [int] NOT NULL,
[EXESTAT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PSTASKRES__EXEST__6AD4A8D1] DEFAULT (0),
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL,
[SUBTIME] [datetime] NOT NULL,
[SUBEMP] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[RCVTIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSTASKRESULTDTL] ADD CONSTRAINT [PK__PSTASKRESULTDTL__6BC8CD0A] PRIMARY KEY CLUSTERED  ([NUM], [STOREGID], [ITEMNO], [LINE]) ON [PRIMARY]
GO
