CREATE TABLE [dbo].[ASBUY2_002]
(
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[SETTLENO] [int] NOT NULL,
[GID] [int] NOT NULL,
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__ASBUY2_002__QTY__36EE1DD3] DEFAULT (0),
[INPRC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__ASBUY2_00__INPRC__37E2420C] DEFAULT (0),
[PRICE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__ASBUY2_00__PRICE__38D66645] DEFAULT (0),
[REALAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__ASBUY2_00__REALA__39CA8A7E] DEFAULT (0),
[FAVAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__ASBUY2_00__FAVAM__3ABEAEB7] DEFAULT (0),
[TAG] [smallint] NOT NULL CONSTRAINT [DF__ASBUY2_002__TAG__3BB2D2F0] DEFAULT (0),
[QPCGID] [int] NULL,
[PRMTAG] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[ASSISTANT] [int] NULL,
[WRH] [int] NULL CONSTRAINT [DF__ASBUY2_002__WRH__3CA6F729] DEFAULT (1),
[INVNO] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[COST] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__ASBUY2_002__COST__3D9B1B62] DEFAULT (0),
[DEALER] [int] NULL,
[IQTY] [decimal] (24, 2) NULL,
[GDCODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[SCOREINFO] [char] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ASBUY2_002] ADD CONSTRAINT [PK__ASBUY2_002__3E8F3F9B] PRIMARY KEY CLUSTERED  ([FLOWNO], [POSNO], [ITEMNO]) ON [PRIMARY]
GO
