CREATE TABLE [dbo].[NPS3SPECSCOPESCOREDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[DEPT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[VENDOR] [int] NULL,
[SORT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[BRAND] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[MINAMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NPS3SPECS__MINAM__7C0C83D0] DEFAULT (0),
[AMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NPS3SPECS__AMOUN__7D00A809] DEFAULT (0),
[SCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NPS3SPECS__SCORE__7DF4CC42] DEFAULT (0),
[MAXDISCOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NPS3SPECS__MAXDI__7EE8F07B] DEFAULT (100),
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SCORESORT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NPS3SPECS__SCORE__060AEF56] DEFAULT ('-'),
[NSCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NPS3SPECS__NSCOR__30012922] DEFAULT (1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPS3SPECSCOPESCOREDTL] ADD CONSTRAINT [PK__NPS3SPECSCOPESCO__3D1BF875] PRIMARY KEY CLUSTERED  ([SRC], [ID], [NUM], [CLS], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPS3SPECSCOPESCOREDTL_5] ON [dbo].[NPS3SPECSCOPESCOREDTL] ([BRAND]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPS3SPECSCOPESCOREDTL_2] ON [dbo].[NPS3SPECSCOPESCOREDTL] ([DEPT]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPS3SPECSCOPESCOREDTL_1] ON [dbo].[NPS3SPECSCOPESCOREDTL] ([NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPS3SPECSCOPESCOREDTL_4] ON [dbo].[NPS3SPECSCOPESCOREDTL] ([SORT]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPS3SPECSCOPESCOREDTL_3] ON [dbo].[NPS3SPECSCOPESCOREDTL] ([VENDOR]) ON [PRIMARY]
GO
