CREATE TABLE [dbo].[PRCSCHEMEDTLHST]
(
[CODE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[GDQPCSTR] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PRCSCHEME__GDQPC__3E57D36C] DEFAULT ('1*1'),
[PRCCLS] [char] (8) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PRCSCHEME__PRCCL__3F4BF7A5] DEFAULT ('核算售价'),
[CTRMODE] [int] NOT NULL CONSTRAINT [DF__PRCSCHEME__CTRMO__40401BDE] DEFAULT (0),
[LaunchByStore] [smallint] NOT NULL CONSTRAINT [DF__PRCSCHEME__Launc__41344017] DEFAULT (0),
[TOPPRC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PRCSCHEME__TOPPR__42286450] DEFAULT (0),
[LOWPRC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PRCSCHEME__LOWPR__431C8889] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[DATE] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRCSCHEMEDTLHST] ADD CONSTRAINT [PK__PRCSCHEMEDTLHST__4410ACC2] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
