CREATE TABLE [dbo].[STKOUTDTL]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SETTLENO] [int] NULL,
[GDGID] [int] NULL,
[CASES] [money] NULL,
[QTY] [money] NULL,
[WSPRC] [money] NULL,
[PRICE] [money] NULL,
[TOTAL] [money] NULL,
[TAX] [money] NULL,
[INPRC] [money] NULL,
[RTLPRC] [money] NULL,
[VALIDDATE] [datetime] NULL,
[WRH] [int] NULL CONSTRAINT [DF__STKOUTDTL__WRH__748F2482] DEFAULT (1),
[INVQTY] [money] NULL CONSTRAINT [DF__STKOUTDTL__INVQT__758348BB] DEFAULT (0),
[subwrh] [int] NULL,
[subqty] [money] NULL CONSTRAINT [DF__stkoutdtl__subqt__34DF7F18] DEFAULT (0),
[RCPQTY] [money] NOT NULL CONSTRAINT [DF__STKOUTDTL__RCPQT__54B81D24] DEFAULT (0),
[RCPAMT] [money] NOT NULL CONSTRAINT [DF__STKOUTDTL__RCPAM__55AC415D] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[COST] [money] NOT NULL CONSTRAINT [DF__STKOUTDTL__COST__3099ECE8] DEFAULT (0),
[GFTFLAG] [int] NULL,
[GFTID] [int] NULL,
[GFTLINE] [int] NULL,
[SRCAGANUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NULL,
[RSVALCQTY] [decimal] (24, 4) NULL CONSTRAINT [DF__STKOUTDTL__RSVAL__28E6E9E3] DEFAULT (0),
[BckQty] [decimal] (24, 4) NULL,
[FIRSTQTY] [decimal] (24, 4) NULL,
[ALLOCQTY] [decimal] (24, 4) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STKOUTDTL] ADD CONSTRAINT [PK__STKOUTDTL__2665ABE1] PRIMARY KEY CLUSTERED  ([CLS], [NUM], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [stkoutdtl_gdgid] ON [dbo].[STKOUTDTL] ([GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
