CREATE TABLE [dbo].[FAFAVORITEDTL]
(
[EMPGID] [int] NOT NULL,
[ID] [int] NOT NULL,
[MODULEID] [int] NOT NULL,
[NAME] [varchar] (120) COLLATE Chinese_PRC_CI_AS NULL,
[ITEMNO] [int] NOT NULL CONSTRAINT [DF__FAFAVORIT__ITEMN__07C6B891] DEFAULT (0),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__FAFAVORIT__LSTUP__08BADCCA] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FAFAVORITEDTL] ADD CONSTRAINT [PK__FAFAVORITEDTL__09AF0103] PRIMARY KEY CLUSTERED  ([EMPGID], [ID], [MODULEID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_FAFAVORITEDTL_ITEM] ON [dbo].[FAFAVORITEDTL] ([ID], [ITEMNO]) ON [PRIMARY]
GO
