CREATE TABLE [dbo].[CRMCARDALERT]
(
[OPERTIME] [datetime] NOT NULL CONSTRAINT [DF__CRMCARDAL__OPERT__31066341] DEFAULT (getdate()),
[OPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ALERTTYPE] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PARA1] [char] (50) COLLATE Chinese_PRC_CI_AS NULL,
[PARA2] [char] (50) COLLATE Chinese_PRC_CI_AS NULL,
[PARA3] [char] (50) COLLATE Chinese_PRC_CI_AS NULL,
[PARA4] [char] (50) COLLATE Chinese_PRC_CI_AS NULL,
[PARA5] [char] (50) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[STAT] [int] NOT NULL CONSTRAINT [DF__CRMCARDALE__STAT__31FA877A] DEFAULT (0),
[STORE] [int] NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_CRMCARDALERT_POSNO] ON [dbo].[CRMCARDALERT] ([POSNO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_CRMCARDALERT_STORE] ON [dbo].[CRMCARDALERT] ([STORE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_CRMCARDALERT_STOREPOSNO] ON [dbo].[CRMCARDALERT] ([STORE], [POSNO]) ON [PRIMARY]
GO
