CREATE TABLE [dbo].[PAYTCDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[TCCLS] [char] (16) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TCCODE] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[TCTOTAL] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PAYTCDTL__TCTOTA__7255CF08] DEFAULT (0),
[TCCRTTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAYTCDTL] ADD CONSTRAINT [PK__PAYTCDTL__5F15B006] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
