CREATE TABLE [dbo].[NGFTPRMGOODS]
(
[RCV] [int] NOT NULL,
[ID] [int] NOT NULL,
[RCODE] [char] (18) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDCOND] [text] COLLATE Chinese_PRC_CI_AS NULL,
[GDCONDTEXT] [text] COLLATE Chinese_PRC_CI_AS NULL,
[FILTERCNSTR] [text] COLLATE Chinese_PRC_CI_AS NOT NULL,
[QTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NGFTPRMGOOD__QTY__495DDB16] DEFAULT (0),
[AMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NGFTPRMGOOD__AMT__4A51FF4F] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NGFTPRMGOODS] ADD CONSTRAINT [PK__NGFTPRMGOODS__4B462388] PRIMARY KEY CLUSTERED  ([RCV], [ID], [RCODE], [LINE]) ON [PRIMARY]
GO
