CREATE TABLE [dbo].[IPA2LACDTL]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SUBWRH] [int] NOT NULL,
[STORE] [int] NOT NULL,
[STAT] [smallint] NOT NULL,
[LACTIME] [datetime] NULL,
[ADJCOST] [money] NOT NULL CONSTRAINT [DF__IPA2LACDT__ADJCO__6CF9BB09] DEFAULT (0),
[ADJINCOST] [money] NOT NULL CONSTRAINT [DF__IPA2LACDT__ADJIN__6DEDDF42] DEFAULT (0),
[ADJINVCOST] [money] NOT NULL CONSTRAINT [DF__IPA2LACDT__ADJIN__6EE2037B] DEFAULT (0),
[ADJOUTCOST] [money] NOT NULL CONSTRAINT [DF__IPA2LACDT__ADJOU__6FD627B4] DEFAULT (0),
[ADJALCAMT] [money] NOT NULL CONSTRAINT [DF__IPA2LACDT__ADJAL__70CA4BED] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IPA2LACDTL] ADD CONSTRAINT [PK__IPA2LACDTL__6C0596D0] PRIMARY KEY CLUSTERED  ([CLS], [NUM], [SUBWRH], [STORE]) ON [PRIMARY]
GO
