CREATE TABLE [dbo].[INVCHGDRPTI]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[BGDGID] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[CQ1] [money] NULL CONSTRAINT [DF__INVCHGDRPTI__CQ1__3A4D7454] DEFAULT (0),
[CQ2] [money] NULL CONSTRAINT [DF__INVCHGDRPTI__CQ2__3B41988D] DEFAULT (0),
[CQ4] [money] NULL CONSTRAINT [DF__INVCHGDRPTI__CQ4__3C35BCC6] DEFAULT (0),
[CQ5] [money] NULL CONSTRAINT [DF__INVCHGDRPTI__CQ5__3D29E0FF] DEFAULT (0),
[CI1] [money] NULL CONSTRAINT [DF__INVCHGDRPTI__CI1__3E1E0538] DEFAULT (0),
[CI2] [money] NULL CONSTRAINT [DF__INVCHGDRPTI__CI2__3F122971] DEFAULT (0),
[CI3] [money] NULL CONSTRAINT [DF__INVCHGDRPTI__CI3__40064DAA] DEFAULT (0),
[CI4] [money] NULL CONSTRAINT [DF__INVCHGDRPTI__CI4__40FA71E3] DEFAULT (0),
[CI5] [money] NULL CONSTRAINT [DF__INVCHGDRPTI__CI5__41EE961C] DEFAULT (0),
[CR1] [money] NULL CONSTRAINT [DF__INVCHGDRPTI__CR1__42E2BA55] DEFAULT (0),
[CR2] [money] NULL CONSTRAINT [DF__INVCHGDRPTI__CR2__43D6DE8E] DEFAULT (0),
[CR3] [money] NULL CONSTRAINT [DF__INVCHGDRPTI__CR3__44CB02C7] DEFAULT (0),
[CR4] [money] NULL CONSTRAINT [DF__INVCHGDRPTI__CR4__45BF2700] DEFAULT (0),
[CR5] [money] NULL CONSTRAINT [DF__INVCHGDRPTI__CR5__46B34B39] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INVCHGDRPTI] ADD CONSTRAINT [PK__INVCHGDRPTI__79C80F94] PRIMARY KEY CLUSTERED  ([ADATE], [BGDGID], [BWRH], [ASETTLENO], [ASTORE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
