CREATE TABLE [dbo].[INDRPT]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[BGDGID] [int] NOT NULL,
[BVDRGID] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[DQ1] [money] NULL CONSTRAINT [DF__INDRPT__DQ1__4317C47F] DEFAULT (0),
[DQ2] [money] NULL CONSTRAINT [DF__INDRPT__DQ2__440BE8B8] DEFAULT (0),
[DQ3] [money] NULL CONSTRAINT [DF__INDRPT__DQ3__45000CF1] DEFAULT (0),
[DQ4] [money] NULL CONSTRAINT [DF__INDRPT__DQ4__45F4312A] DEFAULT (0),
[DT1] [money] NULL CONSTRAINT [DF__INDRPT__DT1__46E85563] DEFAULT (0),
[DT2] [money] NULL CONSTRAINT [DF__INDRPT__DT2__47DC799C] DEFAULT (0),
[DT3] [money] NULL CONSTRAINT [DF__INDRPT__DT3__48D09DD5] DEFAULT (0),
[DT4] [money] NULL CONSTRAINT [DF__INDRPT__DT4__49C4C20E] DEFAULT (0),
[DI1] [money] NULL CONSTRAINT [DF__INDRPT__DI1__4AB8E647] DEFAULT (0),
[DI2] [money] NULL CONSTRAINT [DF__INDRPT__DI2__4BAD0A80] DEFAULT (0),
[DI3] [money] NULL CONSTRAINT [DF__INDRPT__DI3__4CA12EB9] DEFAULT (0),
[DI4] [money] NULL CONSTRAINT [DF__INDRPT__DI4__4D9552F2] DEFAULT (0),
[DR1] [money] NULL CONSTRAINT [DF__INDRPT__DR1__4E89772B] DEFAULT (0),
[DR2] [money] NULL CONSTRAINT [DF__INDRPT__DR2__4F7D9B64] DEFAULT (0),
[DR3] [money] NULL CONSTRAINT [DF__INDRPT__DR3__5071BF9D] DEFAULT (0),
[DR4] [money] NULL CONSTRAINT [DF__INDRPT__DR4__5165E3D6] DEFAULT (0),
[LSTUPDTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INDRPT] ADD CONSTRAINT [PK__INDRPT__6E565CE8] PRIMARY KEY CLUSTERED  ([ADATE], [BGDGID], [BVDRGID], [BWRH], [ASETTLENO], [ASTORE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [gddatewrh] ON [dbo].[INDRPT] ([BGDGID], [ADATE], [BWRH]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
