CREATE TABLE [dbo].[PS3SPECSCOPESCOREDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[DEPT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[VENDOR] [int] NULL,
[SORT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[BRAND] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[MINAMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3SPECSC__MINAM__6CCA4040] DEFAULT (0),
[AMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3SPECSC__AMOUN__6DBE6479] DEFAULT (0),
[SCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3SPECSC__SCORE__6EB288B2] DEFAULT (0),
[MAXDISCOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3SPECSC__MAXDI__6FA6ACEB] DEFAULT (100),
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SCORESORT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PS3SPECSC__SCORE__0516CB1D] DEFAULT ('-'),
[NSCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3SPECSC__NSCOR__2F0D04E9] DEFAULT (1),
[DISCOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3SPECSC__DISCO__7170907A] DEFAULT (0),
[DISMAXDIS] [decimal] (24, 2) NULL,
[DISPREC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PS3SPECSC__DISPR__7264B4B3] DEFAULT (0.01)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3SPECSCOPESCOREDTL] ADD CONSTRAINT [PK__PS3SPECSCOPESCOR__709AD124] PRIMARY KEY CLUSTERED  ([NUM], [CLS], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3SPECSCOPESCOREDTL_4] ON [dbo].[PS3SPECSCOPESCOREDTL] ([BRAND]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3SPECSCOPESCOREDTL_1] ON [dbo].[PS3SPECSCOPESCOREDTL] ([DEPT]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3SPECSCOPESCOREDTL_3] ON [dbo].[PS3SPECSCOPESCOREDTL] ([SORT]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3SPECSCOPESCOREDTL_2] ON [dbo].[PS3SPECSCOPESCOREDTL] ([VENDOR]) ON [PRIMARY]
GO
