CREATE TABLE [dbo].[NSHOULDEXCHGDATADTL]
(
[SENDDATE] [datetime] NOT NULL,
[RCV] [int] NOT NULL,
[SRC] [int] NOT NULL,
[TGT] [int] NOT NULL,
[CLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHECKINT1] [int] NOT NULL CONSTRAINT [DF__NSHOULDEX__CHECK__0D9B94C5] DEFAULT (0),
[CHECKINT2] [int] NOT NULL CONSTRAINT [DF__NSHOULDEX__CHECK__0E8FB8FE] DEFAULT (0),
[CHECKINT3] [int] NOT NULL CONSTRAINT [DF__NSHOULDEX__CHECK__0F83DD37] DEFAULT (0),
[CHECKDATA1] [decimal] (20, 2) NOT NULL CONSTRAINT [DF__NSHOULDEX__CHECK__10780170] DEFAULT (0),
[CHECKDATA2] [decimal] (20, 2) NOT NULL CONSTRAINT [DF__NSHOULDEX__CHECK__116C25A9] DEFAULT (0),
[CHECKDATA3] [decimal] (20, 2) NOT NULL CONSTRAINT [DF__NSHOULDEX__CHECK__126049E2] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NSHOULDEXCHGDATADTL] ADD CONSTRAINT [PK__NSHOULDEXCHGDATA__0CA7708C] PRIMARY KEY CLUSTERED  ([SENDDATE], [RCV], [SRC], [TGT], [CLS], [NUM]) ON [PRIMARY]
GO
