CREATE TABLE [dbo].[REGPOSKEY]
(
[DEVICEINDEX] [smallint] NOT NULL,
[SPEC] [char] (255) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DEVICEFILE] [char] (255) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REGPOSKEY] ADD CONSTRAINT [PK__REGPOSKEY__0D99FE17] PRIMARY KEY CLUSTERED  ([DEVICEINDEX]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
