CREATE TABLE [dbo].[NPSCPDTL]
(
[ID] [int] NOT NULL,
[GID] [int] NOT NULL,
[RAW] [smallint] NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[QTY] [money] NOT NULL,
[SRC] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPSCPDTL] ADD CONSTRAINT [PK__NPSCPDTL__47FBA9D6] PRIMARY KEY CLUSTERED  ([ID], [SRC], [RAW], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
