CREATE TABLE [dbo].[EMPSHOP]
(
[EMPGID] [int] NOT NULL,
[SHOPNO] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMPSHOP] ADD CONSTRAINT [PK__EMPSHOP__CDB08C0B21A1288E] PRIMARY KEY CLUSTERED  ([SHOPNO], [EMPGID]) ON [PRIMARY]
GO
