CREATE TABLE [dbo].[CRMCARDSALEDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[CARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARDTYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BALANCE] [decimal] (24, 2) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMCARDSALEDTL] ADD CONSTRAINT [PK__CRMCARDSALEDTL__688BA255] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
