CREATE TABLE [dbo].[INVOICE]
(
[NUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[INVOICENUM] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLTO] [int] NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__INVOICE__STAT__437BAFE5] DEFAULT (0),
[FILLER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__INVOICE__FILLER__446FD41E] DEFAULT ('未知[-]'),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__INVOICE__FILDATE__4563F857] DEFAULT (getdate()),
[PRECHECKER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[PRECHKDATE] [datetime] NULL,
[CHECKER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[VERIFIER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[VERIFYDATE] [datetime] NULL,
[PAYER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[PAYDATE] [datetime] NULL,
[INVTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__INVOICE__INVTOTA__46581C90] DEFAULT (0),
[INVTAXAMT] [decimal] (24, 2) NULL,
[TYPE] [smallint] NOT NULL,
[INVTAXRATE] [decimal] (24, 4) NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[INVPAIDAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__INVOICE__INVPAID__474C40C9] DEFAULT (0),
[LSTUPDTIME] [datetime] NULL,
[MODNUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INVOICE] ADD CONSTRAINT [PK__INVOICE__48406502] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
