CREATE TABLE [dbo].[NPRCADJDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NULL,
[OLDPRC] [money] NULL,
[NEWPRC] [money] NULL,
[QTY] [money] NULL,
[QPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPRCADJDTL__QPC__2A9A282B] DEFAULT (1),
[QPCSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NPRCADJDT__QPCST__2B8E4C64] DEFAULT ('1*1')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPRCADJDTL] ADD CONSTRAINT [PK__NPRCADJDTL__405A880E] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
