CREATE TABLE [dbo].[VOUCHERCASHAUTHORTEMP]
(
[ID] [int] NOT NULL,
[LINE] [int] NOT NULL,
[CODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLAG] [int] NOT NULL,
[CODE2] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[FLAG2] [smallint] NOT NULL CONSTRAINT [DF__VOUCHERCA__FLAG2__2AFBB18C] DEFAULT (0),
[GDGID] [int] NOT NULL CONSTRAINT [DF__VOUCHERCA__GDGID__429E30F3] DEFAULT ((-1))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERCASHAUTHORTEMP] ADD CONSTRAINT [PK__VOUCHERCASHAUTHO__466EC1D7] PRIMARY KEY CLUSTERED  ([ID], [LINE], [GDGID]) ON [PRIMARY]
GO
