CREATE TABLE [dbo].[PS3_ONLINECNTRBRAND]
(
[UUID] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PLATFORM] [varchar] (80) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CNTRNO] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[CODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TYPE] [smallint] NOT NULL,
[STATUS] [smallint] NOT NULL,
[STARTDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3_ONLINECNTRBRAND] ADD CONSTRAINT [PK__PS3_ONLI__33AEB8216CAE3D62] PRIMARY KEY CLUSTERED  ([UUID], [LINE]) ON [PRIMARY]
GO
