CREATE TABLE [dbo].[ITEMREGDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[NAMESPEC] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[QTY] [int] NOT NULL CONSTRAINT [DF__ITEMREGDTL__QTY__59EA13F1] DEFAULT (0),
[MEMO] [varchar] (256) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ITEMREGDTL] ADD CONSTRAINT [PK__ITEMREGDTL__5ADE382A] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
