CREATE TABLE [dbo].[INPRCADJAINVDTL]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[STORE] [int] NOT NULL,
[WRH] [int] NULL,
[SUBWRH] [int] NULL,
[QTY] [money] NOT NULL,
[COST] [money] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INPRCADJAINVDTL] ADD CONSTRAINT [PK__INPRCADJAINVDTL__6BEEF189] PRIMARY KEY NONCLUSTERED  ([CLS], [NUM], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INPRCADJAINVDTL] ADD CONSTRAINT [UQ__INPRCADJAINVDTL__75035A77] UNIQUE CLUSTERED  ([STORE], [WRH], [SUBWRH], [CLS], [NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
