CREATE TABLE [dbo].[TK_OWNERINFO]
(
[CLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OWNERGID] [int] NOT NULL,
[SERIALNO] [varchar] (16) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PIN] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TK_OWNERINFO] ADD CONSTRAINT [PK__TK_OWNERINFO__3DDFA4C4] PRIMARY KEY CLUSTERED  ([CLS], [OWNERGID]) ON [PRIMARY]
GO
