CREATE TABLE [dbo].[GFTPRMBCKLOG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [int] NOT NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GFTPRMBCKLOG] ADD CONSTRAINT [PK__GFTPRMBCKLOG__2593E53E] PRIMARY KEY CLUSTERED  ([NUM], [STAT], [TIME]) ON [PRIMARY]
GO
