CREATE TABLE [dbo].[INVMRPTX]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[BGDGID] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[CIN] [money] NOT NULL CONSTRAINT [DF__INVMRPTX__CIN__6A33284E] DEFAULT (0),
[FIN] [money] NOT NULL CONSTRAINT [DF__INVMRPTX__FIN__6B274C87] DEFAULT (0),
[FTAXRATE] [money] NOT NULL CONSTRAINT [DF__INVMRPTX__FTAXRA__6C1B70C0] DEFAULT (17),
[FSALETAX] [money] NOT NULL CONSTRAINT [DF__INVMRPTX__FSALET__6D0F94F9] DEFAULT (17)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INVMRPTX] ADD CONSTRAINT [PK__INVMRPTX__025D5595] PRIMARY KEY CLUSTERED  ([ASETTLENO], [BGDGID], [BWRH], [ASTORE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
