CREATE TABLE [dbo].[NPRMOFFSETDTL]
(
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SETTLENO] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[QPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPRMOFFSETD__QPC__1C5957D1] DEFAULT (1),
[QPCSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NPRMOFFSE__QPCST__1D4D7C0A] DEFAULT ('1*1'),
[OFFSETPRC] [decimal] (24, 4) NULL,
[CNTINPRC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPRMOFFSE__CNTIN__1E41A043] DEFAULT (0),
[QTY] [decimal] (24, 4) NULL,
[START] [datetime] NOT NULL CONSTRAINT [DF__NPRMOFFSE__START__1F35C47C] DEFAULT ('1899.12.30 00:00:00'),
[FINISH] [datetime] NOT NULL CONSTRAINT [DF__NPRMOFFSE__FINIS__2029E8B5] DEFAULT ('9999.12.31 23:59:59'),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[ALC] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[TOTAL] [decimal] (24, 4) NULL,
[AMOUNT] [decimal] (24, 4) NULL,
[TAX] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPRMOFFSETD__TAX__211E0CEE] DEFAULT (0),
[DIFFPRC] [decimal] (24, 4) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPRMOFFSETDTL] ADD CONSTRAINT [PK__NPRMOFFSETDTL__22123127] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
