CREATE TABLE [dbo].[TALLYPRINTRPT]
(
[STOREGID] [int] NOT NULL,
[PRINTTIME] [datetime] NOT NULL,
[TALLYTYPE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[QTY] [int] NOT NULL CONSTRAINT [DF__TALLYPRINTR__QTY__40DE6F05] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TALLYPRINTRPT] ADD CONSTRAINT [PK__TALLYPRINTRPT__41D2933E] PRIMARY KEY CLUSTERED  ([STOREGID], [PRINTTIME], [TALLYTYPE]) ON [PRIMARY]
GO
