CREATE TABLE [dbo].[NCNTRDPTOUTSRCDTL]
(
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[SRCCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRCNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRCTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCNTRDPTO__SRCTO__7BCBC157] DEFAULT (0),
[PAYEDAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCNTRDPTO__PAYED__7CBFE590] DEFAULT (0),
[CANPAYAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCNTRDPTO__CANPA__7DB409C9] DEFAULT (0),
[TOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCNTRDPTO__TOTAL__7EA82E02] DEFAULT (0),
[NOTE] [char] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL CONSTRAINT [DF__NCNTRDPTOUT__SRC__7F9C523B] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCNTRDPTOUTSRCDTL] ADD CONSTRAINT [PK__NCNTRDPTOUTSRCDT__00907674] PRIMARY KEY CLUSTERED  ([ID], [SRC]) ON [PRIMARY]
GO
