CREATE TABLE [dbo].[NPRCPRM]
(
[ID] [int] NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[FILDATE] [datetime] NULL CONSTRAINT [DF__NPRCPRM__FILDATE__76AC771E] DEFAULT (getdate()),
[CHECKER] [int] NULL CONSTRAINT [DF__NPRCPRM__CHECKER__77A09B57] DEFAULT (1),
[RECCNT] [int] NULL CONSTRAINT [DF__NPRCPRM__RECCNT__7894BF90] DEFAULT (0),
[NSTAT] [smallint] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[RCV] [int] NULL,
[SNDTIME] [datetime] NULL,
[RCVTIME] [datetime] NULL,
[FRCCHK] [smallint] NULL,
[TYPE] [smallint] NULL,
[LAUNCH] [datetime] NULL,
[TOPIC] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[OVERWRITERULE] [smallint] NULL,
[PSETTLENO] [int] NULL,
[STAT] [smallint] NULL,
[PRIORITY] [int] NOT NULL CONSTRAINT [DF__NPRCPRM__PRIORIT__3E7A3102] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPRCPRM] ADD CONSTRAINT [PK__NPRCPRM__414EAC47] PRIMARY KEY CLUSTERED  ([SRC], [ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPRCPRM_TYPE] ON [dbo].[NPRCPRM] ([TYPE]) ON [PRIMARY]
GO
