CREATE TABLE [dbo].[CRMCARDAPPLY]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__CRMCARDAPP__STAT__5D19EFA9] DEFAULT (0),
[STORE] [int] NOT NULL,
[COUNT] [int] NOT NULL,
[TOTALBALANCE] [decimal] (24, 2) NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__CRMCARDAP__FILDA__5E0E13E2] DEFAULT (getdate()),
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NULL,
[TOTALCARDCOST] [decimal] (24, 2) NOT NULL,
[SRC] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMCARDAPPLY] ADD CONSTRAINT [PK__CRMCARDAPPLY__5F02381B] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
