CREATE TABLE [dbo].[PSSAVSCORE]
(
[AMOUNT] [decimal] (24, 2) NOT NULL,
[SCORE] [decimal] (24, 2) NOT NULL,
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSSAVSCORE] ADD CONSTRAINT [PK__PSSAVSCORE__75756031] PRIMARY KEY CLUSTERED  ([AMOUNT]) ON [PRIMARY]
GO
