CREATE TABLE [dbo].[GOODSUPGRADEGENBILLS]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GENCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GENNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GOODSUPGRADEGENBILLS] ADD CONSTRAINT [PK__GOODSUPGRADEGENB__7AC68738] PRIMARY KEY CLUSTERED  ([NUM], [GENCLS], [GENNUM]) ON [PRIMARY]
GO
