CREATE TABLE [dbo].[PSTASKATTACH]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [int] NOT NULL,
[ATTACHMENT] [varchar] (60) COLLATE Chinese_PRC_CI_AS NULL,
[CAPTION] [varchar] (80) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILENAME] [varchar] (120) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ATTACHSIZE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PSTASKATT__ATTAC__63338709] DEFAULT (0),
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSTASKATTACH] ADD CONSTRAINT [PK__PSTASKATTACH__6427AB42] PRIMARY KEY CLUSTERED  ([NUM], [ITEMNO]) ON [PRIMARY]
GO
