CREATE TABLE [dbo].[CRMDATAEXGRECVLOG]
(
[FRECVTIME] [datetime] NOT NULL,
[FCLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FUUID] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[FSRCUUID] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[FACTION] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FNOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[FSENDTIME] [datetime] NULL,
[FSRCORG] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FDESTORG] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_DATAEXGRECVLOG] ON [dbo].[CRMDATAEXGRECVLOG] ([FRECVTIME], [FACTION]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_DATAEXGRECVLOG_CLS] ON [dbo].[CRMDATAEXGRECVLOG] ([FSRCORG], [FCLS], [FSRCUUID], [FACTION], [FRECVTIME]) ON [PRIMARY]
GO
