CREATE TABLE [dbo].[VOUCHERBCKSTGRCVDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[BILLNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[EXAMT] [decimal] (24, 2) NULL CONSTRAINT [DF__VOUCHERBC__EXAMT__7341684E] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERBCKSTGRCVDTL] ADD CONSTRAINT [PK__VOUCHERBCKSTGRCV__42B33F8C] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [VOUCHERBCKSTGRCVDTL_FLOWNO] ON [dbo].[VOUCHERBCKSTGRCVDTL] ([FLOWNO]) ON [PRIMARY]
GO
