CREATE TABLE [dbo].[NSTOREORDAPPLYDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[GDCODE] [varchar] (13) COLLATE Chinese_PRC_CI_AS NOT NULL,
[QPC] [int] NOT NULL,
[QPCSTR] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[QTY] [decimal] (24, 4) NOT NULL,
[APPLYQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NSTOREORD__APPLY__19857619] DEFAULT ((-1)),
[EXCGQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NSTOREORD__EXCGQ__1A799A52] DEFAULT ((-1)),
[NOTE] [varchar] (256) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NSTOREORDAPPLYDTL] ADD CONSTRAINT [PK__NStoreOrdApplyDt__1B6DBE8B] PRIMARY KEY CLUSTERED  ([NUM], [SRC], [LINE]) ON [PRIMARY]
GO
