CREATE TABLE [dbo].[NPROMFPRCQTY]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLAG] [int] NOT NULL CONSTRAINT [DF__NPROMFPRCQ__FLAG__5D322B9E] DEFAULT (0),
[LINE] [int] NOT NULL CONSTRAINT [DF__NPROMFPRCQ__LINE__5E264FD7] DEFAULT (0),
[PRMNO] [int] NOT NULL,
[QTY] [decimal] (24, 4) NOT NULL,
[PRMTOTAL] [decimal] (24, 4) NOT NULL,
[PPRC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPROMFPRCQ__PPRC__5F1A7410] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPROMFPRCQTY] ADD CONSTRAINT [PK__NPROMFPRCQTY__600E9849] PRIMARY KEY CLUSTERED  ([SRC], [ID], [NUM], [CLS], [LINE], [FLAG], [PRMNO]) ON [PRIMARY]
GO
