CREATE TABLE [dbo].[PRMRTNPNTAGMRATEDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[LOWAMT] [money] NOT NULL CONSTRAINT [DF__PRMRTNPNT__LOWAM__68B9B83A] DEFAULT (0),
[HIGHAMT] [money] NOT NULL CONSTRAINT [DF__PRMRTNPNT__HIGHA__69ADDC73] DEFAULT (99999999),
[RATE] [money] NOT NULL CONSTRAINT [DF__PRMRTNPNTA__RATE__6AA200AC] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRMRTNPNTAGMRATEDTL] ADD CONSTRAINT [PK__PRMRTNPNTAGMRATE__6B9624E5] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
