CREATE TABLE [dbo].[FAPROMPT]
(
[UUID] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[RECEIVER] [int] NOT NULL,
[TITLE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FTEXT] [text] COLLATE Chinese_PRC_CI_AS NULL,
[FLAG] [varchar] (16) COLLATE Chinese_PRC_CI_AS NULL,
[FLEVEL] [int] NULL,
[SENDERID] [varchar] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SENDERCLASSNAME] [varchar] (128) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FTIME] [datetime] NOT NULL,
[MODULENO] [int] NULL,
[PKGNAME] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL,
[PROCNAME] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL,
[PARAMS] [varchar] (2000) COLLATE Chinese_PRC_CI_AS NULL,
[LASTMODIFITIME] [datetime] NOT NULL CONSTRAINT [DF__FAPROMPT__LASTMO__03C11D83] DEFAULT (getdate()),
[LASTMODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__FAPROMPT__LASTMO__04B541BC] DEFAULT ('-[未知]')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FAPROMPT] ADD CONSTRAINT [PK__FAPROMPT__05A965F5] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx_FAPROMPT_1] ON [dbo].[FAPROMPT] ([RECEIVER]) ON [PRIMARY]
GO
