CREATE TABLE [dbo].[PRMOFFSETXLSGENNUM]
(
[spid] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx_PRMOFFSETXLSGENNUM_spid] ON [dbo].[PRMOFFSETXLSGENNUM] ([spid]) ON [PRIMARY]
GO
