CREATE TABLE [dbo].[CRMCARDSCOHSTWEBPOOL]
(
[CARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARRIER] [int] NOT NULL CONSTRAINT [DF__CRMCARDSC__CARRI__24A08C5C] DEFAULT (1),
[SCORESUBJECT] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMCARDSC__SCORE__2594B095] DEFAULT ('未知'),
[OLDSCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCARDSC__OLDSC__2688D4CE] DEFAULT (0),
[SCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCARDSC__SCORE__277CF907] DEFAULT (0),
[FGSTAT] [smallint] NOT NULL CONSTRAINT [DF__CRMCARDSC__FGSTA__28711D40] DEFAULT (0),
[NUM] [char] (26) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SCORESORT] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMCARDSC__SCORE__29654179] DEFAULT ('-')
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_CRMCARDSCOHSTWEBPOOL_NUM] ON [dbo].[CRMCARDSCOHSTWEBPOOL] ([NUM]) ON [PRIMARY]
GO
