CREATE TABLE [dbo].[NMXFDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[WRH] [int] NOT NULL,
[QTY] [money] NOT NULL CONSTRAINT [DF__NMXFDTL__QTY__48BC5A93] DEFAULT (0),
[FROMPRICE] [money] NOT NULL CONSTRAINT [DF__NMXFDTL__FROMPRI__49B07ECC] DEFAULT (0),
[FROMTOTAL] [money] NOT NULL CONSTRAINT [DF__NMXFDTL__FROMTOT__4AA4A305] DEFAULT (0),
[FROMTAX] [money] NOT NULL CONSTRAINT [DF__NMXFDTL__FROMTAX__4B98C73E] DEFAULT (0),
[TOPRICE] [money] NOT NULL CONSTRAINT [DF__NMXFDTL__TOPRICE__4C8CEB77] DEFAULT (0),
[TOTOTAL] [money] NOT NULL CONSTRAINT [DF__NMXFDTL__TOTOTAL__4D810FB0] DEFAULT (0),
[TOTAX] [money] NOT NULL CONSTRAINT [DF__NMXFDTL__TOTAX__4E7533E9] DEFAULT (0),
[FROMCOST] [money] NOT NULL CONSTRAINT [DF__NMXFDTL__FROMCOS__4F695822] DEFAULT (0),
[TOCOST] [money] NOT NULL CONSTRAINT [DF__NMXFDTL__TOCOST__505D7C5B] DEFAULT (0),
[SUBWRH] [int] NULL,
[INPRC] [money] NOT NULL CONSTRAINT [DF__NMXFDTL__INPRC__5151A094] DEFAULT (0),
[RTLPRC] [money] NOT NULL CONSTRAINT [DF__NMXFDTL__RTLPRC__5245C4CD] DEFAULT (0),
[CASES] [decimal] (24, 4) NULL CONSTRAINT [DF__NMXFDTL__CASES__0D082E96] DEFAULT (0),
[BNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[FROMGDVDR] [int] NULL,
[FROMGDALC] [char] (10) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NMXFDTL] ADD CONSTRAINT [PK__NMXFDTL__47C8365A] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) ON [PRIMARY]
GO
