CREATE TABLE [dbo].[NPRCADJ]
(
[ID] [int] NOT NULL,
[CLS] [char] (8) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__NPRCADJ__CLS__5733CBC5] DEFAULT ('核算售价'),
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[FILDATE] [datetime] NULL CONSTRAINT [DF__NPRCADJ__FILDATE__5827EFFE] DEFAULT (getdate()),
[CHECKER] [int] NULL CONSTRAINT [DF__NPRCADJ__CHECKER__591C1437] DEFAULT (1),
[RECCNT] [int] NULL CONSTRAINT [DF__NPRCADJ__RECCNT__5A103870] DEFAULT (0),
[LAUNCH] [datetime] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[NSTAT] [smallint] NULL CONSTRAINT [DF__NPRCADJ__NSTAT__5B045CA9] DEFAULT (0),
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[RCV] [int] NULL,
[SNDTIME] [datetime] NULL,
[RCVTIME] [datetime] NULL,
[FRCCHK] [smallint] NULL,
[TYPE] [smallint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPRCADJ] ADD CONSTRAINT [PK__NPRCADJ__3F6663D5] PRIMARY KEY CLUSTERED  ([SRC], [ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPRCADJ_TYPE] ON [dbo].[NPRCADJ] ([TYPE]) ON [PRIMARY]
GO
