CREATE TABLE [dbo].[PS3CRMPROMSUBJECTDTL]
(
[SUBJUUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SUBJCODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARDTYPE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARDTYPENAME] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3CRMPROMSUBJECTDTL] ADD CONSTRAINT [PK__PS3CRMPROMSUBJEC__127BB333] PRIMARY KEY CLUSTERED  ([SUBJUUID], [CARDTYPE]) ON [PRIMARY]
GO
