CREATE TABLE [dbo].[PRMOFFSETDRPT]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[GDGID] [int] NOT NULL,
[VDRGID] [int] NOT NULL,
[CNTINPRC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PRMOFFSET__CNTIN__23FA7999] DEFAULT (0),
[OFFSETPRC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PRMOFFSET__OFFSE__24EE9DD2] DEFAULT (0),
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PRMOFFSETDR__QTY__25E2C20B] DEFAULT (0),
[OFFSETAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PRMOFFSET__OFFSE__26D6E644] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRMOFFSETDRPT] ADD CONSTRAINT [PK__PRMOFFSETDRPT__27CB0A7D] PRIMARY KEY CLUSTERED  ([ASTORE], [ASETTLENO], [ADATE], [GDGID], [VDRGID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PRMOFFSETDRPT] ON [dbo].[PRMOFFSETDRPT] ([ADATE], [GDGID], [VDRGID]) ON [PRIMARY]
GO
