CREATE TABLE [dbo].[BROKER]
(
[CODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GENDER] [varchar] (2) COLLATE Chinese_PRC_CI_AS NULL,
[UNIT] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[POSITION] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BROKER] ADD CONSTRAINT [PK__BROKER__702FF179] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
