CREATE TABLE [dbo].[CASHCLTDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PAYCODE] [smallint] NOT NULL,
[TOTAL] [money] NOT NULL,
[REALAMT] [money] NOT NULL,
[NOTE] [varchar] (80) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CASHCLTDTL] ADD CONSTRAINT [PK__CASHCLTDTL__22FF2F51] PRIMARY KEY CLUSTERED  ([NUM], [PAYCODE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
