CREATE TABLE [dbo].[EMPSALETASK]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__EMPSALETAS__STAT__63CA1A94] DEFAULT (0),
[SETTLENO] [int] NOT NULL CONSTRAINT [DF__EMPSALETA__SETTL__64BE3ECD] DEFAULT (0),
[RECCNT] [int] NOT NULL CONSTRAINT [DF__EMPSALETA__RECCN__65B26306] DEFAULT (0),
[BROKERCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STORE] [int] NOT NULL,
[MANAGER] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__EMPSALETA__FILDA__66A6873F] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHKDATE] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__EMPSALETA__LSTUP__679AAB78] DEFAULT (getdate()),
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__EMPSALETA__LSTUP__688ECFB1] DEFAULT ('未知[-]'),
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMPSALETASK] ADD CONSTRAINT [PK__EMPSALETASK__6982F3EA] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
