CREATE TABLE [dbo].[STORERETAILCURDTL]
(
[Num] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[Cls] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ItemNo] [smallint] NOT NULL,
[Tag] [smallint] NOT NULL CONSTRAINT [DF__STORERETAIL__Tag__11053EB1] DEFAULT (0),
[CURRENCY] [smallint] NOT NULL CONSTRAINT [DF__STORERETA__CURRE__11F962EA] DEFAULT (0),
[CardNum] [varchar] (128) COLLATE Chinese_PRC_CI_AS NULL,
[Amount] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__STORERETA__Amoun__12ED8723] DEFAULT (0),
[Remark] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STORERETAILCURDTL] ADD CONSTRAINT [PK__StoreRetailCurDt__13E1AB5C] PRIMARY KEY CLUSTERED  ([Num], [Cls], [ItemNo]) ON [PRIMARY]
GO
