CREATE TABLE [dbo].[CANCELAUTOMBRPRCLIMITSLOG]
(
[ACTION] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TIME] [datetime] NOT NULL,
[ERRORMSG] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[GUID] [char] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DETAILINFO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_CancelAutoMbrPrcLimitsLog_GUID] ON [dbo].[CANCELAUTOMBRPRCLIMITSLOG] ([GUID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_CancelAutoMbrPrcLimitsLog_MODIFIER] ON [dbo].[CANCELAUTOMBRPRCLIMITSLOG] ([MODIFIER]) ON [PRIMARY]
GO
