CREATE TABLE [dbo].[GFTPRMDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[RULECODE] [char] (18) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GFTPRMDTL] ADD CONSTRAINT [PK__GFTPRMDTL__5483DE51] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
