CREATE TABLE [dbo].[CANCELAUTOMBRPRCLIMITS]
(
[VENDORGID] [int] NOT NULL,
[DEPTCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BRANDCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__CANCELAUT__LSTUP__1B5024FF] DEFAULT (getdate()),
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GUID] [char] (64) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CANCELAUTOMBRPRCLIMITS] ADD CONSTRAINT [PK__CancelAutoMbrPrc__1C444938] PRIMARY KEY CLUSTERED  ([VENDORGID], [DEPTCODE], [BRANDCODE]) ON [PRIMARY]
GO
