CREATE TABLE [dbo].[DEPT_STORE_GEOG_FLOOR]
(
[BUILDING] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BUILDINGAREA] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__DEPT_STOR__BUILD__331FEEF4] DEFAULT (0),
[USABLEAREA] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__DEPT_STOR__USABL__3414132D] DEFAULT (0),
[RENTALAREA] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__DEPT_STOR__RENTA__35083766] DEFAULT (0),
[CREATOR] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CREATIONTIME] [datetime] NOT NULL CONSTRAINT [DF__DEPT_STOR__CREAT__35FC5B9F] DEFAULT (getdate()),
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__DEPT_STOR__LSTUP__36F07FD8] DEFAULT (getdate()),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPT_STORE_GEOG_FLOOR] ADD CONSTRAINT [PK__DEPT_STORE_GEOG___37E4A411] PRIMARY KEY CLUSTERED  ([BUILDING], [CODE]) ON [PRIMARY]
GO
