CREATE TABLE [dbo].[PRMDIRPRMOFFSETAGM]
(
[PRMSEQ] [int] NOT NULL,
[PRMOFFSETAGMNO] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRMDIRPRMOFFSETAGM] ADD CONSTRAINT [PK__PRMDIRPRMOFFSETA__78DB116A] PRIMARY KEY CLUSTERED  ([PRMSEQ], [PRMOFFSETAGMNO]) ON [PRIMARY]
GO
