CREATE TABLE [dbo].[NPROMGFT]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[NO] [smallint] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PRMNO] [int] NOT NULL,
[LINE] [int] NOT NULL,
[GFTGID] [int] NULL,
[GFTCODE] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[RTLPRC] [decimal] (24, 4) NOT NULL,
[MBRPRC] [decimal] (24, 4) NULL,
[CNTRINPRC] [decimal] (24, 4) NOT NULL,
[COST] [decimal] (24, 4) NOT NULL,
[QPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPROMGFT__QPC__7DBD6013] DEFAULT (1),
[QPCSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PRMDIV1] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPROMGFT__PRMDIV__7EB1844C] DEFAULT (100),
[PRMDIV2] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPROMGFT__PRMDIV__7FA5A885] DEFAULT (0),
[PRMDIV3] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPROMGFT__PRMDIV__0099CCBE] DEFAULT (0),
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPROMGFT__QTY__018DF0F7] DEFAULT (1),
[FLAG] [int] NOT NULL,
[ISDLT] [smallint] NOT NULL CONSTRAINT [DF__NPROMGFT__ISDLT__639F320B] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPROMGFT] ADD CONSTRAINT [PK__NPROMGFT__02821530] PRIMARY KEY CLUSTERED  ([SRC], [ID], [NO], [NUM], [CLS], [PRMNO], [LINE]) ON [PRIMARY]
GO
