CREATE TABLE [dbo].[EPSSENDSTKOUT]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STORE] [int] NOT NULL,
[FLAG] [int] NOT NULL CONSTRAINT [DF__EPSSENDSTK__FLAG__5CC6809C] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EPSSENDSTKOUT] ADD CONSTRAINT [PK__EPSSENDSTKOUT__5DBAA4D5] PRIMARY KEY CLUSTERED  ([NUM], [STORE]) ON [PRIMARY]
GO
