CREATE TABLE [dbo].[GDSORT]
(
[SORT] [varchar] (8) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GDSORT] ADD CONSTRAINT [PK__GDSORT__62E4AA3C] PRIMARY KEY CLUSTERED  ([SORT], [GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
