CREATE TABLE [dbo].[STORESCOSCHEMEDTL]
(
[CODE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[GDQPCSTR] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__STORESCOS__GDQPC__3144C3B5] DEFAULT ('1*1'),
[SCORATE] [money] NOT NULL CONSTRAINT [DF__STORESCOS__SCORA__3238E7EE] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STORESCOSCHEMEDTL] ADD CONSTRAINT [PK__STORESCOSCHEMEDT__30509F7C] PRIMARY KEY CLUSTERED  ([CODE], [GDGID], [GDQPCSTR]) ON [PRIMARY]
GO
