CREATE TABLE [dbo].[NEMPGRPRIGHT]
(
[ID] [int] NOT NULL,
[SRC] [int] NOT NULL CONSTRAINT [DF__NEMPGRPRIGH__SRC__516B7337] DEFAULT (1),
[EMPGRPGID] [int] NOT NULL,
[ARIGHT] [int] NOT NULL,
[ARIGHT2] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NEMPGRPRI__ARIGH__525F9770] DEFAULT ('-')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NEMPGRPRIGHT] ADD CONSTRAINT [PK__NEMPGRPRIGHT__5353BBA9] PRIMARY KEY CLUSTERED  ([ID], [SRC], [EMPGRPGID], [ARIGHT], [ARIGHT2]) ON [PRIMARY]
GO
