CREATE TABLE [dbo].[CSTClearDtl]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[Line] [int] NOT NULL,
[RCPAdjNum] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CSTClearDtl] ADD CONSTRAINT [PK__CSTClearDtl__370627FE] PRIMARY KEY CLUSTERED  ([NUM], [Line], [RCPAdjNum]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
