CREATE TABLE [dbo].[ALCBYSTOREDTL2]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ALCBYSTOREDTL2] ADD CONSTRAINT [PK__ALCBYSTOREDTL2__0817C599] PRIMARY KEY CLUSTERED  ([NUM], [STOREGID]) ON [PRIMARY]
GO
