CREATE TABLE [dbo].[DSPREG]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__DSPREG__FILDATE__4E9F511B] DEFAULT (getdate()),
[FILLER] [int] NOT NULL CONSTRAINT [DF__DSPREG__FILLER__4F937554] DEFAULT (1),
[WRH] [int] NOT NULL,
[INVNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[ACPTIME] [datetime] NULL,
[ACPEMP] [int] NULL,
[OPER] [int] NULL,
[RECCNT] [int] NOT NULL,
[DSPNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL CONSTRAINT [DF__DSPREG__SRC__251E189B] DEFAULT (1),
[SRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DSPREG] WITH NOCHECK ADD CONSTRAINT [DSPREG_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[DSPREG] ADD CONSTRAINT [PK__DSPREG__4EDDB18F] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
