CREATE TABLE [dbo].[ADJVD]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NULL,
[FILLER] [int] NULL,
[FILDATE] [datetime] NULL,
[WRH] [int] NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[PRNTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ADJVD] WITH NOCHECK ADD CONSTRAINT [ADJVD_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[ADJVD] ADD CONSTRAINT [PK__ADJVD__0D0FEE32] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FILDATE] ON [dbo].[ADJVD] ([FILDATE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
