CREATE TABLE [dbo].[SETTLEDEPTDEPT]
(
[DEPTCODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[oldCode] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[newCode] [char] (10) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SETTLEDEPTDEPT] ADD CONSTRAINT [PK__SETTLEDEPTDEPT__10648985] PRIMARY KEY CLUSTERED  ([CODE], [DEPTCODE]) ON [PRIMARY]
GO
