CREATE TABLE [dbo].[SPECIFYCARDS]
(
[NAME] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TYPE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SPECIFYCARDS] ADD CONSTRAINT [PK__SPECIFYCARDS__07DE292F] PRIMARY KEY CLUSTERED  ([NAME], [NOTE]) ON [PRIMARY]
GO
