CREATE TABLE [dbo].[PROCYRPT]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[BGDGID] [int] NOT NULL,
[CQ1] [money] NOT NULL CONSTRAINT [DF__PROCYRPT__CQ1__3E2A88DE] DEFAULT (0),
[CT1] [money] NOT NULL CONSTRAINT [DF__PROCYRPT__CT1__3F1EAD17] DEFAULT (0),
[CI1] [money] NOT NULL CONSTRAINT [DF__PROCYRPT__CI1__4012D150] DEFAULT (0),
[CR1] [money] NOT NULL CONSTRAINT [DF__PROCYRPT__CR1__4106F589] DEFAULT (0),
[CD1] [money] NOT NULL CONSTRAINT [DF__PROCYRPT__CD1__41FB19C2] DEFAULT (0),
[DQ1] [money] NOT NULL CONSTRAINT [DF__PROCYRPT__DQ1__42EF3DFB] DEFAULT (0),
[DT1] [money] NOT NULL CONSTRAINT [DF__PROCYRPT__DT1__43E36234] DEFAULT (0),
[DI1] [money] NOT NULL CONSTRAINT [DF__PROCYRPT__DI1__44D7866D] DEFAULT (0),
[DR1] [money] NOT NULL CONSTRAINT [DF__PROCYRPT__DR1__45CBAAA6] DEFAULT (0),
[DD1] [money] NOT NULL CONSTRAINT [DF__PROCYRPT__DD1__46BFCEDF] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROCYRPT] ADD CONSTRAINT [PK__PROCYRPT__7E57BA87] PRIMARY KEY CLUSTERED  ([ASETTLENO], [BGDGID], [BWRH], [ASTORE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
