CREATE TABLE [dbo].[SHOULDPAYRPT]
(
[VDRGID] [int] NULL,
[SETTLENO] [int] NOT NULL,
[CLS] [int] NOT NULL CONSTRAINT [DF__SHOULDPAYRP__CLS__4FE186CA] DEFAULT (0),
[NUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[SHOULDPAYCLS] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SHOULDPAYNUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TOTAL] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__SHOULDPAY__TOTAL__50D5AB03] DEFAULT (0),
[PYTOTAL] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__SHOULDPAY__PYTOT__51C9CF3C] DEFAULT (0),
[PAYTAG] [smallint] NOT NULL CONSTRAINT [DF__SHOULDPAY__PAYTA__52BDF375] DEFAULT (0)
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_SHOULDPAYRPT_NUM] ON [dbo].[SHOULDPAYRPT] ([NUM]) ON [PRIMARY]
GO
