CREATE TABLE [dbo].[PS3SPECGDSCORELACSTORE]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3SPECGDSCORELACSTORE] ADD CONSTRAINT [PK__PS3SPECGDSCORELA__52164A04] PRIMARY KEY CLUSTERED  ([NUM], [CLS], [STOREGID]) ON [PRIMARY]
GO
