CREATE TABLE [dbo].[NIPA2DTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[SUBWRH] [int] NOT NULL,
[LINE] [smallint] NOT NULL,
[STORE] [int] NOT NULL,
[BILL] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLLINE] [smallint] NOT NULL,
[BILLSRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[WRH] [int] NOT NULL,
[QTY] [money] NOT NULL,
[ADJFLAG] [char] (3) COLLATE Chinese_PRC_CI_AS NOT NULL,
[INCOST] [money] NOT NULL,
[OUTCOST] [money] NOT NULL,
[ALCAMT] [money] NOT NULL,
[ADJINCOST] [money] NOT NULL,
[ADJOUTCOST] [money] NOT NULL,
[ADJALCAMT] [money] NOT NULL,
[ALCSTORE] [int] NULL,
[LACTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NIPA2DTL] ADD CONSTRAINT [PK__NIPA2DTL__05C568D3] PRIMARY KEY CLUSTERED  ([SRC], [ID], [SUBWRH], [LINE]) ON [PRIMARY]
GO
