CREATE TABLE [dbo].[DSP]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[WRH] [int] NOT NULL,
[INVNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[CREATETIME] [datetime] NULL,
[TOTAL] [money] NOT NULL CONSTRAINT [DF__DSP__TOTAL__4ACEC037] DEFAULT (0),
[RECCNT] [int] NOT NULL,
[FILLER] [int] NULL,
[OPENER] [int] NULL,
[LSTDSPTIME] [datetime] NULL,
[LSTDSPEMP] [int] NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNOCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DEF_DSP_STAT] DEFAULT (0),
[DSPDATE] [datetime] NOT NULL CONSTRAINT [DF__dsp__DSPDATE__5F7FC45A] DEFAULT (getdate()),
[DSPMODE] [smallint] NOT NULL CONSTRAINT [DF__dsp__DSPMODE__6073E893] DEFAULT (0),
[BUYERNAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[TEL] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[ADDR] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[NEARBY] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL CONSTRAINT [DF__DSP__SRC__13F38C99] DEFAULT (1),
[SRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__DSP__FILDATE__14E7B0D2] DEFAULT (getdate()),
[PRNTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DSP] WITH NOCHECK ADD CONSTRAINT [DSP_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[DSP] ADD CONSTRAINT [PK__DSP__4CF5691D] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_CPF] ON [dbo].[DSP] ([CLS], [POSNOCLS], [FLOWNO]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
