CREATE TABLE [dbo].[RPTSNDFLAG]
(
[SUBJECT] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ASETTLENO] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[FLAG] [smallint] NOT NULL CONSTRAINT [DF__RPTSNDFLAG__FLAG__7F1A01F2] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RPTSNDFLAG] ADD CONSTRAINT [PK__RPTSNDFLAG__7E25DDB9] PRIMARY KEY CLUSTERED  ([SUBJECT], [ASETTLENO], [ADATE]) ON [PRIMARY]
GO
