CREATE TABLE [dbo].[TMPGFTSNDHINT]
(
[spid] [int] NOT NULL,
[ATIME] [datetime] NULL,
[RCODE] [char] (18) COLLATE Chinese_PRC_CI_AS NULL,
[CONTENT] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx_TMPGFTSNDHINT_spid] ON [dbo].[TMPGFTSNDHINT] ([spid]) ON [PRIMARY]
GO
