CREATE TABLE [dbo].[GDINPUT]
(
[CODE] [varchar] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CODETYPE] [smallint] NULL CONSTRAINT [DF__GDINPUT__CODETYP__4440F2E2] DEFAULT (0),
[GID] [int] NULL,
[FLAGS] [int] NOT NULL CONSTRAINT [DF__GDINPUT__FLAGS__102D1D56] DEFAULT (0),
[QPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__GDINPUT__QPC__0DFDE97D] DEFAULT (1),
[QPCSTR] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__GDINPUT__QPCSTR__0EF20DB6] DEFAULT ('1*1')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GDINPUT] ADD CONSTRAINT [PK__GDINPUT__6589112B] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [GID] ON [dbo].[GDINPUT] ([GID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
