CREATE TABLE [dbo].[ALCBYSTORE]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [smallint] NOT NULL,
[STAT] [smallint] NOT NULL,
[FILLER] [int] NOT NULL CONSTRAINT [DF__ALCBYSTOR__FILLE__7CA612ED] DEFAULT (1),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__ALCBYSTOR__FILDA__7D9A3726] DEFAULT (getdate()),
[CHECKER] [int] NOT NULL CONSTRAINT [DF__ALCBYSTOR__CHECK__7E8E5B5F] DEFAULT (1),
[DMDDATE] [datetime] NOT NULL,
[TOTAL] [money] NOT NULL CONSTRAINT [DF__ALCBYSTOR__TOTAL__7F827F98] DEFAULT (0),
[TAX] [money] NOT NULL CONSTRAINT [DF__ALCBYSTORE__TAX__0076A3D1] DEFAULT (0),
[QTY] [money] NOT NULL CONSTRAINT [DF__ALCBYSTORE__QTY__016AC80A] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[CLS] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__AlcByStore__CLS__30DAAF61] DEFAULT ('采购配货'),
[srcnum] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[desrctype] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[desrcnum] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[sndtime] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ALCBYSTORE] ADD CONSTRAINT [PK__ALCBYSTORE__7BB1EEB4] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
