CREATE TABLE [dbo].[LEAGUESTOREALCACCOUNTPAY]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL,
[ACCOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__LEAGUESTO__ACCOU__613564A7] DEFAULT (0),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SHOULDPAY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__LEAGUESTO__SHOUL__45390FCE] DEFAULT (0),
[PAY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__LEAGUESTORE__PAY__462D3407] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LEAGUESTOREALCACCOUNTPAY] ADD CONSTRAINT [PK__LEAGUESTOREALCAC__622988E0] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
