CREATE TABLE [dbo].[CRMCARDACCUCON]
(
[CARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARRIER] [int] NOT NULL,
[CONDATE] [datetime] NOT NULL,
[CONSUME] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMCARDAC__CONSU__5E431E0C] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMCARDACCUCON] ADD CONSTRAINT [PK__CRMCARDACCUCON__5F374245] PRIMARY KEY CLUSTERED  ([CARDNUM], [CARRIER], [CONDATE]) ON [PRIMARY]
GO
