CREATE TABLE [dbo].[NCTPREPAYRTN]
(
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VENDOR] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__NCTPREPAYR__STAT__6E71C639] DEFAULT (0),
[FILLER] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL,
[CHECKER] [int] NULL,
[CHKDATE] [datetime] NULL,
[OCRDATE] [datetime] NOT NULL,
[DEPT] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[PSR] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[TOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCTPREPAY__TOTAL__6F65EA72] DEFAULT (0),
[PREPAYNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__NCTPREPAY__LSTUP__705A0EAB] DEFAULT (getdate()),
[LASTMODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CLECENT] [int] NULL,
[SNDTIME] [datetime] NULL,
[SRC] [int] NOT NULL CONSTRAINT [DF__NCTPREPAYRT__SRC__714E32E4] DEFAULT (0),
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[RCV] [int] NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL,
[CFLAG] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCTPREPAYRTN] ADD CONSTRAINT [PK__NCTPREPAYRTN__7242571D] PRIMARY KEY CLUSTERED  ([ID], [SRC]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NCTPREPAYRTN_TYPE] ON [dbo].[NCTPREPAYRTN] ([TYPE]) ON [PRIMARY]
GO
