CREATE TABLE [dbo].[POSVOUCHERLOG]
(
[UUID] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STORE] [int] NOT NULL,
[VOUCODE] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[RECYCLETIME] [datetime] NOT NULL CONSTRAINT [DF__POSVOUCHE__RECYC__67E4C43B] DEFAULT (getdate()),
[POSNO] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLOWNO] [varchar] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILLER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[recycleFlag] [int] NULL CONSTRAINT [DF__POSVOUCHE__recyc__68D8E874] DEFAULT (1),
[netFlag] [int] NULL CONSTRAINT [DF__POSVOUCHE__netFl__69CD0CAD] DEFAULT (1),
[realAmt] [decimal] (24, 2) NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[VOUCHERTYPE] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[POSVOUCHERLOG] ADD CONSTRAINT [PK__POSVOUCHERLOG__6AC130E6] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
