CREATE TABLE [dbo].[COUPONEXCHANGETRANS]
(
[TRANID] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[XID] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[RECORDTIME] [datetime] NOT NULL,
[TRANRESULT] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ERRORMESSAGE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COUPONEXCHANGETRANS] ADD CONSTRAINT [PK__COUPONEX__6EF725E713DD191C] PRIMARY KEY CLUSTERED  ([TRANID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_COUPONEXCHANGETRANS_XID] ON [dbo].[COUPONEXCHANGETRANS] ([XID]) ON [PRIMARY]
GO
