CREATE TABLE [dbo].[PS3DISNOTDISCOUNTBRAND]
(
[BRAND] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3DISNOTDISCOUNTBRAND] ADD CONSTRAINT [PK__PS3DISNOTDISCOUN__30081D67] PRIMARY KEY CLUSTERED  ([BRAND]) ON [PRIMARY]
GO
