CREATE TABLE [dbo].[BCKDMDDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[CASES] [decimal] (24, 4) NULL,
[QTY] [decimal] (24, 4) NULL,
[DMDCASES] [decimal] (24, 4) NULL,
[DMDQTY] [decimal] (24, 4) NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[INV] [money] NOT NULL CONSTRAINT [DF__BCKDMDDTL__INV__49A65D2B] DEFAULT (0),
[CHECKED] [smallint] NULL,
[bckedqty] [decimal] (24, 4) NULL CONSTRAINT [DF__bckdmddtl__bcked__0DFC52CF] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BCKDMDDTL] ADD CONSTRAINT [PK__BCKDMDDTL__187915EB] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
