CREATE TABLE [dbo].[SETTLEDAYRUNRESULT]
(
[SETTLEDAY] [datetime] NOT NULL,
[PROCNAME] [char] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NRESULT] [smallint] NOT NULL CONSTRAINT [DF__SETTLEDAY__NRESU__38D4CF97] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SETTLEDAYRUNRESULT] ADD CONSTRAINT [PK__SETTLEDAYRUNRESU__39C8F3D0] PRIMARY KEY CLUSTERED  ([SETTLEDAY], [PROCNAME]) ON [PRIMARY]
GO
