CREATE TABLE [dbo].[GDSALEADJ]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__GDSALEADJ__STAT__421B1553] DEFAULT (0),
[SETTLENO] [int] NULL,
[SRC] [int] NOT NULL,
[PSR] [int] NOT NULL CONSTRAINT [DF__GDSALEADJ__PSR__430F398C] DEFAULT (1),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__GDSALEADJ__FILDA__44035DC5] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[LAUNCH] [datetime] NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__GDSALEADJ__LSTUP__44F781FE] DEFAULT (getdate()),
[PRNTIME] [datetime] NULL,
[SNDTIME] [datetime] NULL,
[EON] [smallint] NOT NULL CONSTRAINT [DF__GDSALEADJ__EON__45EBA637] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__GDSALEADJ__RECCN__46DFCA70] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GDSALEADJ] ADD CONSTRAINT [PK__GDSALEADJ__4126F11A] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_GDSALEADJ_FILDATE] ON [dbo].[GDSALEADJ] ([FILDATE]) ON [PRIMARY]
GO
