CREATE TABLE [dbo].[NBILLAPDX]
(
[SRC] [int] NOT NULL CONSTRAINT [DF__NBILLAPDX__SRC__1F653F45] DEFAULT (1),
[BILL] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ID] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NBILLAPDX__FILDA__2059637E] DEFAULT (getdate()),
[DSPMODE] [smallint] NOT NULL CONSTRAINT [DF__NBILLAPDX__DSPMO__214D87B7] DEFAULT (0),
[DSPDATE] [datetime] NULL,
[OUTCTR] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[OUTCTRPHONE] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[OUTADDR] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[OUTNEARBY] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[INCTR] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[INCTRPHONE] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[INADDR] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[INNEARBY] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[INSTDATE] [datetime] NOT NULL CONSTRAINT [DF__NBILLAPDX__INSTD__2241ABF0] DEFAULT (getdate()),
[DBGDATE] [datetime] NOT NULL CONSTRAINT [DF__NBILLAPDX__DBGDA__2335D029] DEFAULT (getdate()),
[FILLER] [int] NOT NULL CONSTRAINT [DF__NBILLAPDX__FILLE__2429F462] DEFAULT (1),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[TYPE] [smallint] NOT NULL,
[RCV] [int] NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[HDBILLNUM] [varchar] (16) COLLATE Chinese_PRC_CI_AS NULL,
[INUNIT] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE2] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SRCNUM] [char] (12) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NBILLAPDX] ADD CONSTRAINT [PK__NBILLAPDX__16644E42] PRIMARY KEY CLUSTERED  ([SRC], [BILL], [ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
