CREATE TABLE [dbo].[PRCSCHEME]
(
[CODE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[PRCCLS] [char] (8) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PRCSCHEME__PRCCL__4D76EE0F] DEFAULT ('核算售价'),
[CTRMODE] [int] NOT NULL CONSTRAINT [DF__PRCSCHEME__CTRMO__4E6B1248] DEFAULT (0),
[MODIFIER] [int] NOT NULL CONSTRAINT [DF__PRCSCHEME__MODIF__4F5F3681] DEFAULT (1),
[SNDDATE] [datetime] NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__PRCSCHEME__LSTUP__50535ABA] DEFAULT (getdate()),
[LaunchByStore] [smallint] NOT NULL CONSTRAINT [DF__PRCSCHEME__Launc__4B9BF49A] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRCSCHEME] ADD CONSTRAINT [PK__PRCSCHEME__4C82C9D6] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
