CREATE TABLE [dbo].[NCTCNTRFIXDATE]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VERSION] [smallint] NOT NULL,
[LINE] [smallint] NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[GENDATE] [datetime] NOT NULL,
[TOTAL] [decimal] (24, 2) NOT NULL,
[CHGBOOKNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCTCNTRFIXDATE] ADD CONSTRAINT [PK__NCTCNTRFIXDATE__2A26BD8D] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE], [ITEMNO]) ON [PRIMARY]
GO
