CREATE TABLE [dbo].[GFTPRMSNDLOG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [int] NOT NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GFTPRMSNDLOG] ADD CONSTRAINT [PK__GFTPRMSNDLOG__118CEC91] PRIMARY KEY CLUSTERED  ([NUM], [STAT], [TIME]) ON [PRIMARY]
GO
