CREATE TABLE [dbo].[REGPOSMODULESET]
(
[MODULESETCODE] [smallint] NOT NULL,
[SPEC] [char] (255) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DEVICEFILE] [char] (255) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REGPOSMODULESET] ADD CONSTRAINT [PK__REGPOSMODULESET__0E8E2250] PRIMARY KEY CLUSTERED  ([MODULESETCODE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
