CREATE TABLE [dbo].[DISTRICT]
(
[CODE] [int] NOT NULL,
[NAME] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DISTRICT] ADD CONSTRAINT [PK__DISTRICT__AA1D437877F50785] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
