CREATE TABLE [dbo].[ALCPOOLFIFOZL]
(
[STOREGID] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[RQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__ALCPOOLFIF__RQTY__7C536F37] DEFAULT (0),
[ALLQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__ALCPOOLFI__ALLQT__7D479370] DEFAULT (0)
) ON [PRIMARY]
GO
