CREATE TABLE [dbo].[PRMOFFSETLEND]
(
[GDGID] [int] NOT NULL,
[STORE] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[DATE] [datetime] NOT NULL,
[RAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PRMOFFSETL__RAMT__59626611] DEFAULT (0),
[RQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PRMOFFSETL__RQTY__5A568A4A] DEFAULT (0),
[RECAL] [int] NOT NULL CONSTRAINT [DF__PRMOFFSET__RECAL__5B4AAE83] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRMOFFSETLEND] ADD CONSTRAINT [PK__PRMOFFSETLEND__5C3ED2BC] PRIMARY KEY CLUSTERED  ([GDGID], [STORE], [DATE], [NUM]) ON [PRIMARY]
GO
