CREATE TABLE [dbo].[CRMDEVDECLARE]
(
[DEVNAME] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DEVUUID] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__CRMDEVDEC__LSTUP__48CB403E] DEFAULT (getdate())
) ON [PRIMARY]
GO
