CREATE TABLE [dbo].[PROCTASKLOG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[STAT] [smallint] NOT NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ACT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[TIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROCTASKLOG] ADD CONSTRAINT [PK__PROCTASKLOG__2ABA23BC] PRIMARY KEY CLUSTERED  ([TIME], [STAT], [NUM]) ON [PRIMARY]
GO
