CREATE TABLE [dbo].[CQNGOODSAPPFIELD]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[FIELDNAME] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GROUPID] [int] NOT NULL,
[RHQUUID] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NTYPE] [int] NOT NULL,
[NSTAT] [int] NOT NULL CONSTRAINT [DF__CQNGOODSA__NSTAT__69AB7A6E] DEFAULT (0),
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[EXTIME] [datetime] NOT NULL CONSTRAINT [DF__CQNGOODSA__EXTIM__6A9F9EA7] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CQNGOODSAPPFIELD] ADD CONSTRAINT [PK__CQNGOODSAPPFIELD__68B75635] PRIMARY KEY CLUSTERED  ([GROUPID], [RHQUUID], [FIELDNAME]) ON [PRIMARY]
GO
