CREATE TABLE [dbo].[NBCKDMDDTLDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[CASENUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[CASES] [decimal] (24, 4) NULL,
[QTY] [decimal] (24, 4) NULL,
[ID] [int] NOT NULL,
[SRC] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NBCKDMDDTLDTL] ADD CONSTRAINT [PK__NBCKDMDDTLDTL__3EC11C69] PRIMARY KEY CLUSTERED  ([SRC], [LINE], [ID]) ON [PRIMARY]
GO
