CREATE TABLE [dbo].[PSNMKTIVGTOBJ]
(
[CODE] [varchar] (6) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TYPECODE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TYPENAME] [char] (50) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__PSNMKTIVGT__STAT__491D189D] DEFAULT (0),
[CREATOR] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CREATETIME] [datetime] NULL CONSTRAINT [DF__PSNMKTIVG__CREAT__4A113CD6] DEFAULT (getdate()),
[ID] [int] NOT NULL,
[RCV] [int] NULL,
[SNDTIME] [datetime] NULL,
[SRC] [int] NOT NULL,
[NTYPE] [int] NULL,
[NSTAT] [int] NULL,
[NNOTE] [char] (255) COLLATE Chinese_PRC_CI_AS NULL,
[RCVTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSNMKTIVGTOBJ] ADD CONSTRAINT [PK__PSNMKTIVGTOBJ__4828F464] PRIMARY KEY CLUSTERED  ([CODE], [ID], [SRC]) ON [PRIMARY]
GO
