CREATE TABLE [dbo].[PAYIN]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STKINNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STKINLINE] [smallint] NOT NULL,
[PAYNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PAYLINE] [smallint] NOT NULL,
[QTY] [money] NULL,
[PRC] [money] NULL,
[NPQTY] [money] NULL,
[NPTOTAL] [money] NULL,
[TOTAL] [money] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAYIN] ADD CONSTRAINT [PK__PAYIN__6A50C1DA] PRIMARY KEY CLUSTERED  ([CLS], [STKINNUM], [STKINLINE], [PAYNUM], [PAYLINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
