CREATE TABLE [dbo].[PROMB]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__PROMB__STAT__59FF228A] DEFAULT (0),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__PROMB__FILDATE__5AF346C3] DEFAULT (getdate()),
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__PROMB__LSTUPDTIM__5BE76AFC] DEFAULT (getdate()),
[TOPIC] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STORESCOPE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[ASTART] [datetime] NOT NULL,
[AFINISH] [datetime] NOT NULL,
[CYCLE] [datetime] NULL,
[CSTART] [datetime] NULL,
[CFINISH] [datetime] NULL,
[CSPEC] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__PROMB__RECCNT__5CDB8F35] DEFAULT (0),
[PSETTLENO] [int] NULL,
[OCRTIME] [datetime] NOT NULL CONSTRAINT [DF__PROMB__OCRTIME__5DCFB36E] DEFAULT (getdate()),
[DLTPRICEPROM] [smallint] NOT NULL CONSTRAINT [DF__PROMB__DLTPRICEP__60C2C560] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROMB] ADD CONSTRAINT [PK__PROMB__5EC3D7A7] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PROMB_TOPIC] ON [dbo].[PROMB] ([TOPIC]) ON [PRIMARY]
GO
