CREATE TABLE [dbo].[PSCTDISEFFECTLOG]
(
[CARDTYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[OPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OPERTIME] [datetime] NOT NULL CONSTRAINT [DF__PSCTDISEF__OPERT__04F2D6D9] DEFAULT (getdate())
) ON [PRIMARY]
GO
