CREATE TABLE [dbo].[PRMDIRINPRCPRM]
(
[PRMSEQ] [int] NOT NULL,
[INPRCPRMNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRMDIRINPRCPRM] ADD CONSTRAINT [PK__PRMDIRINPRCPRM__76F2C8F8] PRIMARY KEY CLUSTERED  ([PRMSEQ], [INPRCPRMNO]) ON [PRIMARY]
GO
