CREATE TABLE [dbo].[EMPIMPTASK]
(
[EMPGID] [int] NOT NULL,
[IMPTASKCODE] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMPIMPTASK] ADD CONSTRAINT [PK__EMPIMPTASK__66AA7FF2] PRIMARY KEY CLUSTERED  ([EMPGID], [IMPTASKCODE]) ON [PRIMARY]
GO
