CREATE TABLE [dbo].[CRMDATAEXGCARDBLKLST]
(
[CARDNUM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GRADE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMDATAEX__GRADE__43D180F7] DEFAULT ('正常处理'),
[SNDTIME] [datetime] NULL,
[LSTUPDTIME] [datetime] NULL CONSTRAINT [DF__CRMDATAEX__LSTUP__44C5A530] DEFAULT (getdate()),
[SYSUUID] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMDATAEX__SYSUU__45B9C969] DEFAULT ('-'),
[FSENDTIME] [datetime] NOT NULL,
[FSRCORG] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FDESTORG] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMDATAEXGCARDBLKLST] ADD CONSTRAINT [PK__CRMDATAEXGCARDBL__46ADEDA2] PRIMARY KEY CLUSTERED  ([FSRCORG], [FDESTORG], [FSENDTIME], [CARDNUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_CRMDATAEXGCARDBLKLST_FST] ON [dbo].[CRMDATAEXGCARDBLKLST] ([FSENDTIME]) ON [PRIMARY]
GO
