CREATE TABLE [dbo].[VOUCHERACTBCK]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL,
[RECCNT] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL,
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHKDATE] [datetime] NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[BUYBCKNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VOUCHERGIVENUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[PROMPTRECYCLE] [text] COLLATE Chinese_PRC_CI_AS NULL,
[PROMPTSELL] [text] COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERACTBCK] ADD CONSTRAINT [PK__VOUCHERACTBCK__5E9F49D6] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_VOUCHERACTBCK_TRANSNO] ON [dbo].[VOUCHERACTBCK] ([POSNO], [FLOWNO]) ON [PRIMARY]
GO
