CREATE TABLE [dbo].[PS3_OTHERBUY]
(
[POSNO] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLOWNO] [varchar] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STORECODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CASHIER] [int] NOT NULL CONSTRAINT [DF__PS3_OTHER__CASHI__744F5F2A] DEFAULT ((1)),
[MEMBERCODE] [varchar] (32) COLLATE Chinese_PRC_CI_AS NULL,
[TOTAL] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PS3_OTHER__TOTAL__75438363] DEFAULT ((0)),
[REALAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PS3_OTHER__REALA__7637A79C] DEFAULT ((0)),
[CARDCODE] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[FILLER] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__PS3_OTHER__FILDA__772BCBD5] DEFAULT (getdate()),
[LSTMODIFIER] [int] NOT NULL,
[LSTUPDDATE] [datetime] NOT NULL CONSTRAINT [DF__PS3_OTHER__LSTUP__781FF00E] DEFAULT (getdate()),
[REMARK] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[UUID] [varchar] (38) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3_OTHERBUY] ADD CONSTRAINT [PK__PS3_OTHE__65A475E77A083880] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_OTHERBUY_PF] ON [dbo].[PS3_OTHERBUY] ([POSNO], [FLOWNO]) ON [PRIMARY]
GO
