CREATE TABLE [dbo].[PSCONSSCORELOG]
(
[CARDTYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[OPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OPERTIME] [datetime] NOT NULL CONSTRAINT [DF__PSCONSSCO__OPERT__6AF7D1BE] DEFAULT (getdate())
) ON [PRIMARY]
GO
