CREATE TABLE [dbo].[CNTRPAYCASHOTHERINFO]
(
[VCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[INVTOAL] [decimal] (24, 2) NULL,
[PAYBAL] [decimal] (24, 2) NULL,
[LOCKTOTAL] [decimal] (24, 2) NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IDX_CNTRPAYCASHOTHERINFO] ON [dbo].[CNTRPAYCASHOTHERINFO] ([VCODE]) ON [PRIMARY]
GO
