CREATE TABLE [dbo].[PRCCSTGDADJGRPLOG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [int] NOT NULL,
[ACT] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRCCSTGDADJGRPLOG] ADD CONSTRAINT [PK__PRCCSTGDADJGRPLO__7E1C876F] PRIMARY KEY CLUSTERED  ([NUM], [STAT], [ACT], [TIME]) ON [PRIMARY]
GO
