CREATE TABLE [dbo].[EMPRIGHT]
(
[EMPGID] [int] NOT NULL,
[ARIGHT] [int] NOT NULL,
[ARIGHT2] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__EMPRIGHT__ARIGHT__3A3AC7C0] DEFAULT ('-')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMPRIGHT] ADD CONSTRAINT [PK__EMPRIGHT__5DB9D97E] PRIMARY KEY CLUSTERED  ([EMPGID], [ARIGHT], [ARIGHT2]) ON [PRIMARY]
GO
