CREATE TABLE [dbo].[NGFTPRMRULE]
(
[RCV] [int] NOT NULL,
[ID] [int] NOT NULL,
[CODE] [char] (18) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (200) COLLATE Chinese_PRC_CI_AS NULL,
[STAT] [int] NOT NULL CONSTRAINT [DF__NGFTPRMRUL__STAT__3FD470DC] DEFAULT (0),
[BEGINTIME] [datetime] NOT NULL,
[ENDTIME] [datetime] NOT NULL,
[QTY] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NGFTPRMRULE__QTY__40C89515] DEFAULT (0),
[AMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NGFTPRMRULE__AMT__41BCB94E] DEFAULT (0),
[NOTE] [text] COLLATE Chinese_PRC_CI_AS NULL,
[TOPIC] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NGFTPRMRU__TOPIC__42B0DD87] DEFAULT ('-'),
[REPORT] [text] COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NGFTPRMRULE] ADD CONSTRAINT [PK__NGFTPRMRULE__43A501C0] PRIMARY KEY CLUSTERED  ([RCV], [ID], [CODE]) ON [PRIMARY]
GO
