CREATE TABLE [dbo].[NGDINPUT]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[CODE] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[CODETYPE] [smallint] NULL CONSTRAINT [DF__NGDINPUT__CODETY__471D5F8D] DEFAULT (0),
[GID] [int] NULL,
[RCV] [int] NULL,
[RCVTIME] [datetime] NULL,
[FRCUPD] [smallint] NULL,
[TYPE] [smallint] NULL,
[NSTAT] [smallint] NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[TEAMID] [int] NULL,
[QPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NGDINPUT__QPC__26C99747] DEFAULT (1),
[QPCSTR] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NGDINPUT__QPCSTR__27BDBB80] DEFAULT ('1*1')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NGDINPUT] ADD CONSTRAINT [PK__NGDINPUT__297722B6] PRIMARY KEY CLUSTERED  ([SRC], [ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [GIDX] ON [dbo].[NGDINPUT] ([GID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
