CREATE TABLE [dbo].[POLYPAYRATEPRMLACSTORE]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[POLYPAYRATEPRMLACSTORE] ADD CONSTRAINT [PK__POLYPAYRATEPRMLA__415506FF] PRIMARY KEY CLUSTERED  ([NUM], [CLS], [STOREGID]) ON [PRIMARY]
GO
