CREATE TABLE [dbo].[VDRBKR]
(
[VDRGID] [int] NOT NULL,
[AMT1] [money] NOT NULL,
[AMT2] [money] NOT NULL,
[RATE] [money] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VDRBKR] ADD CONSTRAINT [PK__VDRBKR__30E33A54] PRIMARY KEY CLUSTERED  ([VDRGID], [AMT1], [AMT2]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
