CREATE TABLE [dbo].[COUPONEXCHANGEPRINTDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[PRINTDATA] [varchar] (8000) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COUPONEXCHANGEPRINTDTL] ADD CONSTRAINT [PK__COUPONEX__91DB7AAD0C3BF754] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
