CREATE TABLE [dbo].[CRMMODIFYMONEYDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[ADJMONEY] [decimal] (24, 2) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMMODIFYMONEYDTL] ADD CONSTRAINT [PK__CRMMODIFYMONEYDT__57611653] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
