CREATE TABLE [dbo].[CASHCLTPOOL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILLTIME] [datetime] NOT NULL,
[OPERATOR] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CASHIER] [int] NOT NULL,
[POSNO] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BDATE] [datetime] NOT NULL,
[EDATE] [datetime] NOT NULL,
[AMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CASHCLTPO__AMOUN__7B60E1AC] DEFAULT (0),
[REALAMOUNT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CASHCLTPO__REALA__7C5505E5] DEFAULT (0),
[BILLCOUNT] [int] NOT NULL CONSTRAINT [DF__CASHCLTPO__BILLC__7D492A1E] DEFAULT (0),
[LSTUPDTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CASHCLTPOOL] ADD CONSTRAINT [PK__CASHCLTPOOL__7E3D4E57] PRIMARY KEY CLUSTERED  ([POSNO], [NUM]) ON [PRIMARY]
GO
