CREATE TABLE [dbo].[PURCHASEORDERLOG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [int] NOT NULL,
[ACT] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PURCHASEORDERLOG] ADD CONSTRAINT [PK__PURCHASEORDERLOG__7AA0FC46] PRIMARY KEY CLUSTERED  ([NUM], [CLS], [STAT], [ACT], [TIME]) ON [PRIMARY]
GO
