CREATE TABLE [dbo].[PSIVM]
(
[IVCCODE] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[IVCNUM] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OCRDATE] [datetime] NOT NULL,
[TOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PSIVM__TOTAL__5FE5466E] DEFAULT (0),
[STATE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PSIVM__STATE__60D96AA7] DEFAULT ('02'),
[BALDATE] [datetime] NULL,
[SALEDATE] [datetime] NULL,
[PAYMODE] [smallint] NULL,
[MACNO] [char] (64) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [char] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[ENGADDR] [char] (255) COLLATE Chinese_PRC_CI_AS NULL,
[MTYPE] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[CALCDATE] [datetime] NULL,
[IVCTYPECODE] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[RCVCODE] [char] (200) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__PSIVM__RECCNT__61CD8EE0] DEFAULT (0),
[NUM] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[INVAMT] [decimal] (24, 2) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSIVM] ADD CONSTRAINT [IDX_PSIVM_PK] PRIMARY KEY CLUSTERED  ([IVCCODE], [IVCNUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PSIVM_NUM] ON [dbo].[PSIVM] ([NUM]) ON [PRIMARY]
GO
