CREATE TABLE [dbo].[STOREORDQTY]
(
[STOREGID] [int] NOT NULL,
[WRH] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[ORDQTY] [money] NOT NULL CONSTRAINT [DF__STOREORDQ__ORDQT__3E9EBED3] DEFAULT (0),
[ORDQTY2] [money] NOT NULL CONSTRAINT [DF__STOREORDQ__ORDQT__3F92E30C] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STOREORDQTY] ADD CONSTRAINT [PK__STOREORDQTY__3DAA9A9A] PRIMARY KEY CLUSTERED  ([STOREGID], [WRH], [GDGID]) ON [PRIMARY]
GO
