CREATE TABLE [dbo].[LEAGUESTOREALCLOG]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[DATE] [datetime] NOT NULL,
[STORE] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VAL] [decimal] (24, 2) NOT NULL,
[ORITOTAL] [decimal] (24, 2) NOT NULL,
[SORT] [smallint] NOT NULL,
[OPER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LEAGUESTOREALCLOG] ADD CONSTRAINT [PK__LEAGUESTOREALCLO__533C4B0B] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
