CREATE TABLE [dbo].[FAMODULEREFDEFFILE]
(
[NO] [int] NOT NULL,
[ITEMNO] [int] NOT NULL,
[FILECAPTION] [varchar] (120) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILENAME] [varchar] (1024) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VISIBLE] [int] NOT NULL CONSTRAINT [DF__FAMODULER__VISIB__775B469E] DEFAULT (1),
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FAMODULEREFDEFFILE] ADD CONSTRAINT [PK__FAMODULEREFDEFFI__784F6AD7] PRIMARY KEY CLUSTERED  ([NO], [ITEMNO]) ON [PRIMARY]
GO
