CREATE TABLE [dbo].[BCKDMDLOG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TIME] [datetime] NOT NULL,
[ACT] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BCKDMDLOG] ADD CONSTRAINT [PK__BCKDMDLOG__4DE1CDBA] PRIMARY KEY CLUSTERED  ([NUM], [STAT], [TIME], [ACT]) ON [PRIMARY]
GO
