CREATE TABLE [dbo].[CTSCOPE]
(
[CATEGORY] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CODE] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SQLCOND] [varchar] (255) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SQLTEXT] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CTSCOPE] ADD CONSTRAINT [PK__CTSCOPE__39D31571] PRIMARY KEY CLUSTERED  ([CATEGORY], [CODE]) ON [PRIMARY]
GO
