CREATE TABLE [dbo].[GFTPRMLOG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [int] NOT NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GFTPRMLOG] ADD CONSTRAINT [PK__GFTPRMLOG__58546F35] PRIMARY KEY CLUSTERED  ([NUM], [STAT], [TIME]) ON [PRIMARY]
GO
