CREATE TABLE [dbo].[ORDERPOOLGENBILLS]
(
[BILLNAME] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DTLCNT] [smallint] NOT NULL,
[FLAG] [smallint] NOT NULL,
[VDRGID] [int] NULL,
[WRH] [int] NULL,
[COMBINETYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SENDDATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORDERPOOLGENBILLS] ADD CONSTRAINT [PK__ORDERPOOLGENBILL__7F40583B] PRIMARY KEY CLUSTERED  ([BILLNAME], [NUM]) ON [PRIMARY]
GO
