CREATE TABLE [dbo].[TOURSCONSUME]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__TOURSCONSU__STAT__495F71C4] DEFAULT (0),
[CONTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__TOURSCONS__CONTO__4A5395FD] DEFAULT (0),
[TOURFEETYPE] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TOURFEEMON] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__TOURSCONS__TOURF__4B47BA36] DEFAULT (0),
[PLEDGEMON] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__TOURSCONS__PLEDG__4C3BDE6F] DEFAULT (0),
[SETTLEMON] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__TOURSCONS__SETTL__4D3002A8] DEFAULT (0),
[INNERFEEMON] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__TOURSCONS__INNER__4E2426E1] DEFAULT (0),
[CUSTOMERS] [int] NOT NULL CONSTRAINT [DF__TOURSCONS__CUSTO__4F184B1A] DEFAULT (1),
[TOURGUIDES] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CUSTOMERSORIGIN] [char] (50) COLLATE Chinese_PRC_CI_AS NULL,
[TRAVELBUREAU] [char] (100) COLLATE Chinese_PRC_CI_AS NULL,
[CARDNUM] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRC] [int] NOT NULL,
[CREATOR] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__TOURSCONS__CREAT__500C6F53] DEFAULT ('未知[-]'),
[CREATETIME] [datetime] NOT NULL CONSTRAINT [DF__TOURSCONS__CREAT__5100938C] DEFAULT (getdate()),
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__TOURSCONS__LSTUP__51F4B7C5] DEFAULT ('未知[-]'),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__TOURSCONS__LSTUP__52E8DBFE] DEFAULT (getdate()),
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[PRNTIME] [datetime] NULL,
[DISTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__TOURSCONS__DISTO__622B1F8E] DEFAULT (0),
[CUSTOMERSTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__TOURSCONS__CUSTO__631F43C7] DEFAULT (0),
[CUSTOMERSPRC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__TOURSCONS__CUSTO__64136800] DEFAULT (0)
) ON [PRIMARY]
GO
