CREATE TABLE [dbo].[PSGDCONSSCORE]
(
[UUID] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARDTYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL CONSTRAINT [DF__PSGDCONSS__ENDDA__6CE01A30] DEFAULT ('2099.12.31'),
[AMOUNT] [decimal] (24, 2) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSGDCONSSCORE] ADD CONSTRAINT [PK__PSGDCONSSCORE__6DD43E69] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PSGDCONSSCORE] ON [dbo].[PSGDCONSSCORE] ([CARDTYPE], [GDGID], [BEGINDATE]) ON [PRIMARY]
GO
