CREATE TABLE [dbo].[NPROMBDIS]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[QTY] [decimal] (24, 4) NOT NULL,
[RTLPRC] [decimal] (24, 4) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPROMBDIS] ADD CONSTRAINT [PK__NPROMBDIS__05DDA4C8] PRIMARY KEY CLUSTERED  ([SRC], [ID], [NUM], [QTY]) ON [PRIMARY]
GO
