CREATE TABLE [dbo].[PRMOFFSETAGMLAC]
(
[GDGID] [int] NOT NULL,
[STORE] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[BDATE] [datetime] NOT NULL,
[EDATE] [datetime] NOT NULL,
[RBDATE] [datetime] NOT NULL,
[REDATE] [datetime] NOT NULL,
[DIFFPRC] [decimal] (24, 4) NOT NULL,
[TOPQTY] [decimal] (24, 4) NULL,
[TOPAMT] [decimal] (24, 2) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRMOFFSETAGMLAC] ADD CONSTRAINT [PK__PRMOFFSETAGMLAC__52B56882] PRIMARY KEY CLUSTERED  ([GDGID], [STORE], [RBDATE]) ON [PRIMARY]
GO
