CREATE TABLE [dbo].[GDSALEADJLOG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [int] NOT NULL,
[ACT] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__GDSALEADJLO__ACT__4E80EC38] DEFAULT (''),
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GDSALEADJLOG] ADD CONSTRAINT [PK__GDSALEADJLOG__4D8CC7FF] PRIMARY KEY CLUSTERED  ([NUM], [STAT], [TIME], [ACT]) ON [PRIMARY]
GO
