CREATE TABLE [dbo].[ASBUY11_002]
(
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[SETTLENO] [int] NOT NULL,
[CURRENCY] [smallint] NOT NULL CONSTRAINT [DF__ASBUY11_0__CURRE__30412044] DEFAULT (0),
[AMOUNT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__ASBUY11_0__AMOUN__3135447D] DEFAULT (0),
[TAG] [smallint] NOT NULL CONSTRAINT [DF__ASBUY11_002__TAG__322968B6] DEFAULT (0),
[CARDCODE] [varchar] (128) COLLATE Chinese_PRC_CI_AS NULL,
[FAVTYPE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NULL,
[FAVAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__ASBUY11_0__FAVAM__331D8CEF] DEFAULT (0),
[PARVALUE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__ASBUY11_0__PARVA__3411B128] DEFAULT (0),
[CURRENCYTYPE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[ORIGINALAMT] [decimal] (24, 4) NULL,
[PARITIES] [decimal] (24, 4) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ASBUY11_002] ADD CONSTRAINT [PK__ASBUY11_002__3505D561] PRIMARY KEY CLUSTERED  ([FLOWNO], [POSNO], [ITEMNO]) ON [PRIMARY]
GO
