CREATE TABLE [dbo].[PCK]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NULL,
[FILDATE] [datetime] NULL CONSTRAINT [DF__PCK__FILDATE__30D918B3] DEFAULT (getdate()),
[FILLER] [int] NULL,
[WRH] [int] NULL,
[STAT] [smallint] NULL CONSTRAINT [DF__PCK__STAT__31CD3CEC] DEFAULT (0),
[RECCNT] [smallint] NULL CONSTRAINT [DF__PCK__RECCNT__32C16125] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PCK] WITH NOCHECK ADD CONSTRAINT [PCK_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[PCK] ADD CONSTRAINT [PK__PCK__6D2D2E85] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
