CREATE TABLE [dbo].[NCNTRGROUP]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VERSION] [int] NOT NULL,
[VENDOR] [int] NOT NULL,
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[REALENDDATE] [datetime] NULL,
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__NCNTRGROUP__STAT__499F68E6] DEFAULT (0),
[TAG] [int] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCNTRGROUP] ADD CONSTRAINT [PK__NCNTRGROUP__4A938D1F] PRIMARY KEY CLUSTERED  ([SRC], [ID], [NUM], [VERSION]) ON [PRIMARY]
GO
