CREATE TABLE [dbo].[VDRLOCK]
(
[ID] [int] NOT NULL,
[VDRGID] [int] NOT NULL,
[STAT] [int] NOT NULL,
[LOCKTYPE] [int] NOT NULL,
[OCRDATE] [datetime] NOT NULL,
[NOTE] [varchar] (200) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VDRLOCK] ADD CONSTRAINT [PK__VDRLOCK__635CD8E4] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
