CREATE TABLE [dbo].[CTCNTRRATERPT]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VERSION] [smallint] NOT NULL,
[CHGCODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FEEDATE] [datetime] NOT NULL,
[GENDATE] [datetime] NOT NULL,
[BASETOTAL] [decimal] (24, 2) NOT NULL,
[RATETOTAL] [decimal] (24, 2) NOT NULL,
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_CTCNTRRATERPT_NCF] ON [dbo].[CTCNTRRATERPT] ([NUM], [CHGCODE], [FEEDATE]) ON [PRIMARY]
GO
