CREATE TABLE [dbo].[VOUCHERACTBCKVOUSELLDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[VOUCHERNUM] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VOUCHERAMT] [decimal] (24, 2) NOT NULL,
[CALCTYPE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VOUCHERACTIVITY] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERACTBCKVOUSELLDTL] ADD CONSTRAINT [PK__VOUCHERACTBCKVOU__6BF944F4] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
