CREATE TABLE [dbo].[NINVYRPT]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ASTORE] [int] NULL,
[ASETTLENO] [int] NULL,
[BGDGID] [int] NULL,
[BWRH] [int] NULL,
[CQ] [money] NULL CONSTRAINT [DF__NINVYRPT__CQ__26316D0E] DEFAULT (0),
[CT] [money] NULL CONSTRAINT [DF__NINVYRPT__CT__27259147] DEFAULT (0),
[FQ] [money] NULL CONSTRAINT [DF__NINVYRPT__FQ__2819B580] DEFAULT (0),
[FT] [money] NULL CONSTRAINT [DF__NINVYRPT__FT__290DD9B9] DEFAULT (0),
[FINPRC] [money] NULL CONSTRAINT [DF__NINVYRPT__FINPRC__2A01FDF2] DEFAULT (0),
[FRTLPRC] [money] NULL CONSTRAINT [DF__NINVYRPT__FRTLPR__2AF6222B] DEFAULT (0),
[FDXPRC] [money] NULL CONSTRAINT [DF__NINVYRPT__FDXPRC__2BEA4664] DEFAULT (0),
[FPAYRATE] [money] NULL CONSTRAINT [DF__NINVYRPT__FPAYRA__2CDE6A9D] DEFAULT (0),
[FINVPRC] [money] NULL CONSTRAINT [DF__NINVYRPT__FINVPR__2DD28ED6] DEFAULT (0),
[FLSTINPRC] [money] NULL CONSTRAINT [DF__NINVYRPT__FLSTIN__2EC6B30F] DEFAULT (0),
[NSTAT] [smallint] NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NULL,
[RCV] [int] NULL,
[SNDTIME] [datetime] NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NULL,
[FINVCOST] [money] NOT NULL CONSTRAINT [DF__NINVYRPT__FINVCO__3DF3E806] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NINVYRPT] ADD CONSTRAINT [PK__NINVYRPT__37C5420D] PRIMARY KEY CLUSTERED  ([ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
