CREATE TABLE [dbo].[ALCGFTAGMLACDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STOREGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ALCGFTAGMLACDTL] ADD CONSTRAINT [PK__ALCGFTAGMLACDTL__11597915] PRIMARY KEY CLUSTERED  ([NUM], [STOREGID]) ON [PRIMARY]
GO
