CREATE TABLE [dbo].[NSTKOUTBCKDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NULL,
[CASES] [money] NULL,
[QTY] [money] NULL,
[PRICE] [money] NULL,
[TOTAL] [money] NULL,
[TAX] [money] NULL,
[VALIDDATE] [datetime] NULL,
[WRH] [int] NULL CONSTRAINT [DF__NSTKOUTBCKD__WRH__121F8769] DEFAULT (1),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[COST] [money] NOT NULL CONSTRAINT [DF__NSTKOUTBCK__COST__5FD4CA15] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NSTKOUTBCKDTL] ADD CONSTRAINT [PK__NSTKOUTBCKDTL__5090EFD7] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
