CREATE TABLE [dbo].[PREBUY21]
(
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[FAVTYPE] [char] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FAVAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PREBUY21__FAVAMT__4941D838] DEFAULT (0),
[TAG] [smallint] NOT NULL CONSTRAINT [DF__PREBUY21__TAG__4A35FC71] DEFAULT (0),
[PROMNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[PROMCLS] [varchar] (64) COLLATE Chinese_PRC_CI_AS NULL,
[PROMLVL] [int] NULL,
[PROMGDCNT] [int] NULL,
[LSTUPDTIME] [datetime] NULL,
[PROMQTY] [decimal] (24, 4) NULL,
[PROMAMT] [decimal] (24, 2) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PREBUY21] ADD CONSTRAINT [PK__PREBUY21__4B2A20AA] PRIMARY KEY CLUSTERED  ([FLOWNO], [POSNO], [ITEMNO], [FAVTYPE]) ON [PRIMARY]
GO
