CREATE TABLE [dbo].[mem]
(
[GID] [int] NOT NULL,
[CODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ADDRESS] [char] (50) COLLATE Chinese_PRC_CI_AS NULL,
[ZIP] [char] (6) COLLATE Chinese_PRC_CI_AS NULL,
[TELE] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[EMAILADR] [char] (50) COLLATE Chinese_PRC_CI_AS NULL,
[WWWADR] [char] (50) COLLATE Chinese_PRC_CI_AS NULL,
[CDTLMT] [decimal] (24, 2) NULL,
[IDCARD] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LASTTIME] [datetime] NULL,
[TOTAL] [decimal] (24, 2) NOT NULL,
[FAVAMT] [decimal] (24, 2) NOT NULL,
[TLCNT] [decimal] (24, 4) NOT NULL,
[TLGD] [decimal] (24, 4) NOT NULL,
[ADDR2] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[SEX] [smallint] NULL,
[COMPANY] [char] (50) COLLATE Chinese_PRC_CI_AS NULL,
[BUSINESS] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[FAMILIES] [int] NULL,
[INCOME] [decimal] (24, 2) NULL,
[HOBBY] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[TRAFFIC] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[TRANSACTOR] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[WEDDINGDAY] [datetime] NULL,
[FAVCOLOR] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[OTHER] [char] (60) COLLATE Chinese_PRC_CI_AS NULL,
[MOBILEPHONE] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[BP] [char] (40) COLLATE Chinese_PRC_CI_AS NULL,
[BALANCE] [decimal] (24, 2) NOT NULL,
[MAXOVERDRAFT] [decimal] (24, 2) NOT NULL,
[DETAILLEVEL] [smallint] NOT NULL,
[CREDIT] [smallint] NOT NULL,
[MASTERCLN] [int] NULL,
[BACKBUYTOTAL] [decimal] (24, 2) NULL,
[AGE] [int] NULL,
[CREATEDATE] [datetime] NOT NULL,
[MEMO] [varchar] (200) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[SNDTIME] [datetime] NULL,
[LSTUPDTIME] [datetime] NOT NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
