CREATE TABLE [dbo].[NPAY]
(
[ID] [int] NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL,
[FILLER] [int] NOT NULL,
[CHECKER] [int] NOT NULL,
[WRH] [int] NOT NULL,
[BILLTO] [int] NOT NULL,
[AMT] [decimal] (24, 4) NOT NULL,
[STAT] [smallint] NOT NULL,
[MODNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[FROMCLS] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[PYTOTAL] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPAY__PYTOTAL__620BEF54] DEFAULT (0),
[PRNTIME] [datetime] NULL,
[FROMNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[PSR] [int] NOT NULL CONSTRAINT [DF__NPAY__PSR__6300138D] DEFAULT (1),
[ChkTag] [smallint] NOT NULL CONSTRAINT [DF__NPAY__ChkTag__63F437C6] DEFAULT (0),
[OCRDATE] [datetime] NULL,
[TAXRATELMT] [decimal] (24, 4) NULL,
[DEPT] [varchar] (13) COLLATE Chinese_PRC_CI_AS NULL,
[CLECENT] [int] NULL,
[SNDTIME] [datetime] NULL,
[SRC] [int] NOT NULL,
[SRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[RCV] [int] NULL,
[RCVTIME] [datetime] NULL,
[TYPE] [smallint] NOT NULL,
[CFLAG] [smallint] NOT NULL,
[SETTLEDEPT] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPAY] ADD CONSTRAINT [PK__NPAY__64E85BFF] PRIMARY KEY CLUSTERED  ([ID], [SRC]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPAY_TYPE] ON [dbo].[NPAY] ([TYPE]) ON [PRIMARY]
GO
