CREATE TABLE [dbo].[NDSPREGDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[LINE] [int] NOT NULL,
[SETTLENO] [int] NOT NULL,
[DSPLINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[AVAQTY] [money] NOT NULL,
[QTY] [money] NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NDSPREGDTL] ADD CONSTRAINT [PK__NDSPREGDTL__269AB60B] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
