CREATE TABLE [dbo].[FAMSCBNOTIFY]
(
[UUID] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DOMAINCODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SUBJECTCLASS] [varchar] (128) COLLATE Chinese_PRC_CI_AS NOT NULL,
[EVENT] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DICT] [text] COLLATE Chinese_PRC_CI_AS NULL,
[PMPTCTX] [text] COLLATE Chinese_PRC_CI_AS NULL,
[OPERTIME] [datetime] NOT NULL CONSTRAINT [DF__FAMSCBNOT__OPERT__0791AE67] DEFAULT (getdate()),
[OPERID] [int] NOT NULL CONSTRAINT [DF__FAMSCBNOT__OPERI__0885D2A0] DEFAULT (1),
[OPERCODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__FAMSCBNOT__OPERC__0979F6D9] DEFAULT ('-'),
[OPERNAME] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__FAMSCBNOT__OPERN__0A6E1B12] DEFAULT ('未知')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FAMSCBNOTIFY] ADD CONSTRAINT [PK__FAMSCBNOTIFY__0B623F4B] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx_FAMSCBNOTIFY_1] ON [dbo].[FAMSCBNOTIFY] ([OPERTIME]) ON [PRIMARY]
GO
