CREATE TABLE [dbo].[CRMPRIZE]
(
[NAME] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CRMPRIZE__SCORE__299A4BA3] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMPRIZE] ADD CONSTRAINT [PK__CRMPRIZE__2A8E6FDC] PRIMARY KEY CLUSTERED  ([NAME]) ON [PRIMARY]
GO
