CREATE TABLE [dbo].[CQNINDRPT]
(
[GROUPID] [int] NOT NULL,
[RHQUUID] [char] (32) COLLATE Chinese_PRC_CI_AS NULL,
[NTYPE] [int] NOT NULL,
[NSTAT] [int] NOT NULL CONSTRAINT [DF__CQNINDRPT__NSTAT__527D30FC] DEFAULT (0),
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[EXTIME] [datetime] NOT NULL CONSTRAINT [DF__CQNINDRPT__EXTIM__53715535] DEFAULT (getdate()),
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[BGDGID] [int] NOT NULL,
[BVDRGID] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[DQ1] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNINDRPT__DQ1__5465796E] DEFAULT (0),
[DQ2] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNINDRPT__DQ2__55599DA7] DEFAULT (0),
[DQ3] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNINDRPT__DQ3__564DC1E0] DEFAULT (0),
[DQ4] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNINDRPT__DQ4__5741E619] DEFAULT (0),
[DT1] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNINDRPT__DT1__58360A52] DEFAULT (0),
[DT2] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNINDRPT__DT2__592A2E8B] DEFAULT (0),
[DT3] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNINDRPT__DT3__5A1E52C4] DEFAULT (0),
[DT4] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNINDRPT__DT4__5B1276FD] DEFAULT (0),
[DI1] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNINDRPT__DI1__5C069B36] DEFAULT (0),
[DI2] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNINDRPT__DI2__5CFABF6F] DEFAULT (0),
[DI3] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNINDRPT__DI3__5DEEE3A8] DEFAULT (0),
[DI4] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNINDRPT__DI4__5EE307E1] DEFAULT (0),
[DR1] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNINDRPT__DR1__5FD72C1A] DEFAULT (0),
[DR2] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNINDRPT__DR2__60CB5053] DEFAULT (0),
[DR3] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNINDRPT__DR3__61BF748C] DEFAULT (0),
[DR4] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNINDRPT__DR4__62B398C5] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CQNINDRPT] ADD CONSTRAINT [PK__CQNINDRPT__63A7BCFE] PRIMARY KEY CLUSTERED  ([ASTORE], [ASETTLENO], [ADATE], [BGDGID], [BVDRGID], [BWRH]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [gddatewrh] ON [dbo].[CQNINDRPT] ([ADATE], [BGDGID], [BWRH]) ON [PRIMARY]
GO
