CREATE TABLE [dbo].[CNTRDPT]
(
[VENDOR] [int] NOT NULL,
[TOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__CNTRDPT__TOTAL__43AF2361] DEFAULT (0),
[LSTUPDTIME] [datetime] NULL,
[LSTUPDCLS] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[LSTUPDNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CNTRDPT] ADD CONSTRAINT [PK__CNTRDPT__44A3479A] PRIMARY KEY CLUSTERED  ([VENDOR]) ON [PRIMARY]
GO
