CREATE TABLE [dbo].[INVXFLOG]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[STAT] [smallint] NOT NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INVXFLOG] ADD CONSTRAINT [PK__INVXFLOG__57E10497] PRIMARY KEY CLUSTERED  ([NUM], [CLS], [STAT], [TIME]) ON [PRIMARY]
GO
