CREATE TABLE [dbo].[RtlInvDtltmp]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RtlInvDtltmp] ADD CONSTRAINT [PK__RTLINVDTLtmp__3F148B76] PRIMARY KEY CLUSTERED  ([NUM], [POSNO], [FLOWNO], [ITEMNO]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
