CREATE TABLE [dbo].[EMPSALETASKNONCALCCURRENCY]
(
[CURRENCY] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMPSALETASKNONCALCCURRENCY] ADD CONSTRAINT [PK__EMPSALETASKNONCA__65E83887] PRIMARY KEY CLUSTERED  ([CURRENCY]) ON [PRIMARY]
GO
