CREATE TABLE [dbo].[NPROMBGOODS]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[GDCODE] [varchar] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[RTLPRC] [decimal] (24, 4) NOT NULL,
[MBRPRC] [decimal] (24, 4) NULL,
[CNTRINPRC] [decimal] (24, 4) NOT NULL,
[COST] [decimal] (24, 4) NOT NULL,
[GFTFLG] [char] (1) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NPROMBGOO__GFTFL__0118EFAB] DEFAULT ('N'),
[QPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPROMBGOODS__QPC__020D13E4] DEFAULT (1),
[QPCSTR] [char] (15) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PRMDIV1] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NPROMBGOO__PRMDI__0301381D] DEFAULT (100),
[PRMDIV2] [decimal] (24, 4) NOT NULL,
[PRMDIV3] [decimal] (24, 4) NOT NULL,
[ISDLT] [smallint] NOT NULL CONSTRAINT [DF__NPROMBGOO__ISDLT__5DE658B5] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPROMBGOODS] ADD CONSTRAINT [PK__NPROMBGOODS__03F55C56] PRIMARY KEY CLUSTERED  ([SRC], [ID], [NUM], [LINE]) ON [PRIMARY]
GO
