CREATE TABLE [dbo].[NPSSORTSCORULE]
(
[UUID] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARDTYPE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SORTCODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL CONSTRAINT [DF__NPSSORTSC__ENDDA__3EE44556] DEFAULT ('2099.12.31'),
[AMOUNT] [decimal] (24, 2) NOT NULL,
[SCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NPSSORTSC__SCORE__3FD8698F] DEFAULT (0),
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__NPSSORTSC__LSTUP__40CC8DC8] DEFAULT (getdate()),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[RCV] [int] NOT NULL,
[RCVTIME] [datetime] NULL,
[FRCCHK] [smallint] NOT NULL,
[NTYPE] [smallint] NOT NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [char] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NPSSORTSCORULE] ADD CONSTRAINT [PK__NPSSORTSCORULE__41C0B201] PRIMARY KEY CLUSTERED  ([SRC], [RCV], [UUID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPSSORTSCORULE_IDX1] ON [dbo].[NPSSORTSCORULE] ([CARDTYPE], [SORTCODE], [BEGINDATE]) ON [PRIMARY]
GO
