CREATE TABLE [dbo].[MSTOREPLAN]
(
[YEAR] [decimal] (4, 0) NOT NULL,
[MONTH] [decimal] (2, 0) NOT NULL,
[STORE] [int] NOT NULL,
[TOTAL] [money] NOT NULL,
[GP] [money] NOT NULL,
[GPRATE] [money] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MSTOREPLAN] ADD CONSTRAINT [PK__MSTOREPLAN__6C6FAB24] PRIMARY KEY CLUSTERED  ([YEAR], [MONTH], [STORE]) ON [PRIMARY]
GO
