CREATE TABLE [dbo].[CTCNTRBRANDKWHMETER]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VERSION] [smallint] NOT NULL,
[PARENTITEMNO] [smallint] NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[NO] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CTCNTRBRANDKWHMETER] ADD CONSTRAINT [PK__CTCNTRBR__5EA7D741542CA85B] PRIMARY KEY CLUSTERED  ([NUM], [VERSION], [PARENTITEMNO], [ITEMNO]) ON [PRIMARY]
GO
