CREATE TABLE [dbo].[NALCDIFFDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[SRCNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CASES] [decimal] (24, 4) NOT NULL,
[QTY] [decimal] (24, 4) NOT NULL,
[WRH] [int] NOT NULL CONSTRAINT [DF__NALCDIFFDTL__WRH__2338322E] DEFAULT (1),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NALCDIFFDTL] ADD CONSTRAINT [PK__NALCDIFFDTL__242C5667] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) ON [PRIMARY]
GO
