CREATE TABLE [dbo].[JMCONTRACT]
(
[STOREGID] [int] NOT NULL,
[NAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[IDCARDNO] [varchar] (18) COLLATE Chinese_PRC_CI_AS NOT NULL,
[IDCARDADDR] [varchar] (256) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PHONE] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SIGNDATE] [datetime] NOT NULL,
[STARTDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[JMFEE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__JMCONTRAC__JMFEE__7F3AC8DA] DEFAULT (0),
[MANAGEFEE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__JMCONTRAC__MANAG__002EED13] DEFAULT (0),
[BAIL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__JMCONTRACT__BAIL__0123114C] DEFAULT (0),
[CONTRACTFEE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__JMCONTRAC__CONTR__02173585] DEFAULT (0),
[AFFIXNAME] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[CONTRACTKIND] [varchar] (255) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CONTRACTSTAT] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[AMDRCD] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[JMCONTRACT] ADD CONSTRAINT [PK__JMCONTRACT__030B59BE] PRIMARY KEY CLUSTERED  ([STOREGID]) ON [PRIMARY]
GO
