CREATE TABLE [dbo].[NCRMCARDTYPE]
(
[CODE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARDTYPE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NCRMCARDT__CARDT__7B56C00B] DEFAULT ('0000000000'),
[PARVALUE] [decimal] (24, 2) NULL,
[DISCOUNT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__NCRMCARDT__DISCO__7C4AE444] DEFAULT (100),
[CARDCOST] [decimal] (24, 4) NULL,
[CARDUSAGE] [int] NOT NULL CONSTRAINT [DF__NCRMCARDT__CARDU__7D3F087D] DEFAULT (0),
[MEDIUM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MSPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCRMCARDT__MSPRC__7E332CB6] DEFAULT (0),
[MPPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCRMCARDT__MPPRC__7F2750EF] DEFAULT (0),
[MCPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCRMCARDT__MCPRC__001B7528] DEFAULT (0),
[VALIDPRD] [int] NULL,
[ABORTPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCRMCARDT__ABORT__010F9961] DEFAULT (0),
[RESUMEPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCRMCARDT__RESUM__0203BD9A] DEFAULT (0),
[BACKPRC] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCRMCARDT__BACKP__02F7E1D3] DEFAULT (0),
[TRANRATE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCRMCARDT__TRANR__03EC060C] DEFAULT (0),
[CREATOR] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NCRMCARDT__CREAT__04E02A45] DEFAULT ('未知[-]'),
[CREATETIME] [datetime] NOT NULL CONSTRAINT [DF__NCRMCARDT__CREAT__05D44E7E] DEFAULT (getdate()),
[LSTUPDOPER] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NCRMCARDT__LSTUP__06C872B7] DEFAULT ('未知[-]'),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__NCRMCARDT__LSTUP__07BC96F0] DEFAULT (getdate()),
[SNDTIME] [datetime] NOT NULL CONSTRAINT [DF__NCRMCARDT__SNDTI__08B0BB29] DEFAULT (getdate()),
[SYSUUID] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MBRGENMODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__NCRMCARDT__MBRGE__09A4DF62] DEFAULT ('-'),
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[RCV] [int] NULL,
[RCVTIME] [datetime] NULL,
[FRCCHK] [int] NOT NULL,
[NTYPE] [int] NOT NULL,
[NSTAT] [int] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[MINBAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__NCRMCARDT__MINBA__0A99039B] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCRMCARDTYPE] ADD CONSTRAINT [PK__NCRMCARDTYPE__0B8D27D4] PRIMARY KEY CLUSTERED  ([SRC], [ID]) ON [PRIMARY]
GO
