CREATE TABLE [dbo].[POLYPROMQTYSCHMDTLOCR]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BILLLINE] [int] NOT NULL,
[LOWQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__POLYPROMQ__LOWQT__62EC9BA2] DEFAULT (0),
[HIGHQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__POLYPROMQ__HIGHQ__63E0BFDB] DEFAULT (99999999),
[DISCOUNT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__POLYPROMQ__DISCO__64D4E414] DEFAULT (0),
[FAVAMT] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__POLYPROMQ__FAVAM__65C9084D] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[POLYPROMQTYSCHMDTLOCR] ADD CONSTRAINT [PK__POLYPROMQTYSCHMD__66BD2C86] PRIMARY KEY CLUSTERED  ([CLS], [BILLNUM], [BILLLINE]) ON [PRIMARY]
GO
