CREATE TABLE [dbo].[INVDRPT]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[BGDGID] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[CQ] [money] NULL CONSTRAINT [DF__INVDRPT__CQ__17F85C50] DEFAULT (0),
[CT] [money] NULL CONSTRAINT [DF__INVDRPT__CT__18EC8089] DEFAULT (0),
[FQ] [money] NULL CONSTRAINT [DF__INVDRPT__FQ__19E0A4C2] DEFAULT (0),
[FT] [money] NULL CONSTRAINT [DF__INVDRPT__FT__1AD4C8FB] DEFAULT (0),
[FINPRC] [money] NULL CONSTRAINT [DF__INVDRPT__FINPRC__1BC8ED34] DEFAULT (0),
[FRTLPRC] [money] NULL CONSTRAINT [DF__INVDRPT__FRTLPRC__1CBD116D] DEFAULT (0),
[FDXPRC] [money] NULL CONSTRAINT [DF__INVDRPT__FDXPRC__1DB135A6] DEFAULT (0),
[FPAYRATE] [money] NULL CONSTRAINT [DF__INVDRPT__FPAYRAT__1EA559DF] DEFAULT (0),
[FINVPRC] [money] NULL CONSTRAINT [DF__INVDRPT__FINVPRC__1F997E18] DEFAULT (0),
[FLSTINPRC] [money] NULL CONSTRAINT [DF__INVDRPT__FLSTINP__208DA251] DEFAULT (0),
[FINVCOST] [money] NOT NULL CONSTRAINT [DF__INVDRPT__FINVCOS__392F32E9] DEFAULT (0),
[LSTUPDTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INVDRPT] ADD CONSTRAINT [PK__INVDRPT__7F80E8EA] PRIMARY KEY CLUSTERED  ([ADATE], [BGDGID], [BWRH], [ASETTLENO], [ASTORE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_indrpt] ON [dbo].[INVDRPT] ([ADATE] DESC) WITH (FILLFACTOR=80, PAD_INDEX=ON) ON [PRIMARY]
GO
