CREATE TABLE [dbo].[INPRCPRM]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[VDRGID] [int] NOT NULL CONSTRAINT [DF__INPRCPRM__VDRGID__13098A01] DEFAULT (0),
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__INPRCPRM__FILDAT__13FDAE3A] DEFAULT (getdate()),
[FILLER] [int] NOT NULL CONSTRAINT [DF__INPRCPRM__FILLER__14F1D273] DEFAULT (1),
[CHECKER] [int] NOT NULL CONSTRAINT [DF__INPRCPRM__CHECKE__15E5F6AC] DEFAULT (1),
[RECCNT] [int] NOT NULL CONSTRAINT [DF__INPRCPRM__RECCNT__16DA1AE5] DEFAULT (0),
[STAT] [smallint] NOT NULL CONSTRAINT [DF__INPRCPRM__STAT__17CE3F1E] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[EON] [smallint] NOT NULL CONSTRAINT [DF__INPRCPRM__EON__18C26357] DEFAULT (1),
[SRC] [int] NOT NULL CONSTRAINT [DF__INPRCPRM__SRC__19B68790] DEFAULT (1),
[SRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INPRCPRM] WITH NOCHECK ADD CONSTRAINT [INPRCPRM_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[INPRCPRM] ADD CONSTRAINT [PK__INPRCPRM__121565C8] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
