CREATE TABLE [dbo].[EMPSPECRIGHT]
(
[EMPID] [int] NOT NULL,
[SPECRIGHTNO] [int] NOT NULL,
[RIGHTLEVEL] [int] NOT NULL,
[SPECRIGHTNO2] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__EMPSPECRI__SPECR__366A36DC] DEFAULT ('-')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMPSPECRIGHT] ADD CONSTRAINT [PK__EMPSPECRIGHT__65FA19C4] PRIMARY KEY CLUSTERED  ([EMPID], [SPECRIGHTNO], [SPECRIGHTNO2]) ON [PRIMARY]
GO
