CREATE TABLE [dbo].[CNTRACNTINFO]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NO] [int] NOT NULL,
[SUBJECT] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VALUE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CNTRACNTINFO] ADD CONSTRAINT [PK__CNTRACNTINFO__3B19DD60] PRIMARY KEY CLUSTERED  ([NUM], [NO]) ON [PRIMARY]
GO
