CREATE TABLE [dbo].[BUY1_yushou]
(
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (8) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__BUY1_yush__FILDA__59B9027A] DEFAULT (getdate()),
[CASHIER] [int] NOT NULL CONSTRAINT [DF__BUY1_yush__CASHI__5AAD26B3] DEFAULT (1),
[WRH] [int] NOT NULL CONSTRAINT [DF__BUY1_yushou__WRH__5BA14AEC] DEFAULT (1),
[ASSISTANT] [int] NULL,
[TOTAL] [money] NOT NULL CONSTRAINT [DF__BUY1_yush__TOTAL__5C956F25] DEFAULT (0),
[REALAMT] [money] NOT NULL CONSTRAINT [DF__BUY1_yush__REALA__5D89935E] DEFAULT (0),
[PREVAMT] [money] NOT NULL CONSTRAINT [DF__BUY1_yush__PREVA__5E7DB797] DEFAULT (0),
[GUEST] [int] NULL,
[RECCNT] [int] NOT NULL CONSTRAINT [DF__BUY1_yush__RECCN__5F71DBD0] DEFAULT (0),
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[TAG] [smallint] NOT NULL CONSTRAINT [DF__BUY1_yushou__TAG__60660009] DEFAULT (0),
[INVNO] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SCORE] [money] NULL,
[CARDCODE] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[DEALER] [int] NULL,
[FLAG] [int] NULL,
[SCOREINFO] [char] (100) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BUY1_yushou] ADD CONSTRAINT [PK__BUY1_yushou__58C4DE41] PRIMARY KEY CLUSTERED  ([POSNO], [FLOWNO]) ON [PRIMARY]
GO
