CREATE TABLE [dbo].[ECGDVDRSEND]
(
[STOREGID] [int] NOT NULL,
[GDGID] [int] NOT NULL,
[VDRGID] [int] NOT NULL,
[ACT] [smallint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ECGDVDRSEND] ADD CONSTRAINT [PK__ECGDVDRSEND__6C87E719] PRIMARY KEY CLUSTERED  ([STOREGID], [VDRGID], [GDGID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_ECGDVDRSEND_GDGID] ON [dbo].[ECGDVDRSEND] ([GDGID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_ECGDVDRSEND_STOREGID] ON [dbo].[ECGDVDRSEND] ([STOREGID]) ON [PRIMARY]
GO
