CREATE TABLE [dbo].[PSCTGDDISRULESETDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[UUID] [char] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CARDTYPE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[GDQPC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PSCTGDDIS__GDQPC__6D063EAF] DEFAULT (1),
[DISCOUNT] [decimal] (24, 4) NOT NULL,
[EXDIS] [int] NOT NULL CONSTRAINT [DF__PSCTGDDIS__EXDIS__6DFA62E8] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF_PSCTGDDISRULESETDTL_NOTE] DEFAULT ('-')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSCTGDDISRULESETDTL] ADD CONSTRAINT [PK__PSCTGDDISRULESET__6EEE8721] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
