CREATE TABLE [dbo].[PS3SPECSCOPESCOREPROMSUBJOUTDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[SUBJCODE] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SUBJCLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[Flag] [int] NOT NULL CONSTRAINT [DF__PS3SPECSCO__Flag__07B66E02] DEFAULT (0),
[FlagName] [char] (2) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PS3SPECSC__FlagN__099EB674] DEFAULT ('否')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3SPECSCOPESCOREPROMSUBJOUTDTL] ADD CONSTRAINT [PK__PS3SPECSCOPESCOR__60EF4497] PRIMARY KEY CLUSTERED  ([NUM], [CLS], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PS3SPECSCOPESCOREPROMSUBJOUTDTL_1] ON [dbo].[PS3SPECSCOPESCOREPROMSUBJOUTDTL] ([SUBJCODE]) ON [PRIMARY]
GO
