CREATE TABLE [dbo].[BUY11]
(
[FLOWNO] [char] (12) COLLATE Chinese_PRC_CI_AS NOT NULL,
[POSNO] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[SETTLENO] [int] NULL,
[CURRENCY] [smallint] NULL CONSTRAINT [DF__BUY11__CURRENCY__100234CD] DEFAULT (0),
[AMOUNT] [money] NULL CONSTRAINT [DF__BUY11__AMOUNT__10F65906] DEFAULT (0),
[TAG] [smallint] NULL CONSTRAINT [DF__BUY11__TAG__11EA7D3F] DEFAULT (0),
[CARDCODE] [varchar] (128) COLLATE Chinese_PRC_CI_AS NULL,
[FAVTYPE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NULL,
[FAVAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__BUY11__FAVAMT__20127817] DEFAULT (0),
[PARVALUE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__BUY11__PARVALUE__21069C50] DEFAULT (0),
[CURRENCYTYPE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[ORIGINALAMT] [decimal] (24, 4) NULL,
[PARITIES] [decimal] (24, 4) NULL,
[LSTUPDTIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BUY11] ADD CONSTRAINT [PK__BUY11__1D4655FB] PRIMARY KEY CLUSTERED  ([POSNO], [FLOWNO], [ITEMNO]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
