CREATE TABLE [dbo].[NINPRCPRM]
(
[ID] [int] NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VDRGID] [int] NOT NULL,
[FILDATE] [datetime] NOT NULL CONSTRAINT [DF__NINPRCPRM__FILDA__271082AE] DEFAULT (getdate()),
[FILLER] [int] NOT NULL CONSTRAINT [DF__NINPRCPRM__FILLE__2804A6E7] DEFAULT (1),
[CHECKER] [int] NOT NULL CONSTRAINT [DF__NINPRCPRM__CHECK__28F8CB20] DEFAULT (1),
[RECCNT] [int] NOT NULL CONSTRAINT [DF__NINPRCPRM__RECCN__29ECEF59] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[NSTAT] [smallint] NOT NULL,
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SRC] [int] NOT NULL,
[RCV] [int] NOT NULL,
[SNDTIME] [datetime] NULL,
[RCVTIME] [datetime] NULL,
[FRCCHK] [smallint] NOT NULL,
[TYPE] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NINPRCPRM] ADD CONSTRAINT [PK__NINPRCPRM__261C5E75] PRIMARY KEY CLUSTERED  ([SRC], [ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NINPRCPRM_TYPE] ON [dbo].[NINPRCPRM] ([TYPE]) ON [PRIMARY]
GO
