CREATE TABLE [dbo].[NMXFDTL2]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[LINE] [smallint] NOT NULL,
[SUBWRH] [int] NOT NULL,
[FROMTO] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[WRH] [int] NOT NULL,
[QTY] [money] NOT NULL CONSTRAINT [DF__NMXFDTL2__QTY__55223178] DEFAULT (0),
[COST] [money] NOT NULL CONSTRAINT [DF__NMXFDTL2__COST__561655B1] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NMXFDTL2] ADD CONSTRAINT [PK__NMXFDTL2__542E0D3F] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE], [SUBWRH], [FROMTO]) ON [PRIMARY]
GO
