CREATE TABLE [dbo].[COUPONEXCHANGETRANDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[XID] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[XCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COUPONEXCHANGETRANDTL] ADD CONSTRAINT [PK__COUPONEX__91DB7AAD100C8838] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
