CREATE TABLE [dbo].[POSDBGENITEMS]
(
[CLSNAME] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DBNAME] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DISPLAYNAME] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ISVISIBLE] [smallint] NOT NULL CONSTRAINT [DF__POSDBGENI__ISVIS__436A99FF] DEFAULT (1)
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PDIS_] ON [dbo].[POSDBGENITEMS] ([CLSNAME]) ON [PRIMARY]
GO
