CREATE TABLE [dbo].[PRCSCHEMEDTL]
(
[CODE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[GDGID] [int] NOT NULL,
[GDQPCSTR] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PRCSCHEME__GDQPC__532FC765] DEFAULT ('1*1'),
[PRCCLS] [char] (8) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__PRCSCHEME__PRCCL__5423EB9E] DEFAULT ('核算售价'),
[CTRMODE] [int] NOT NULL CONSTRAINT [DF__PRCSCHEME__CTRMO__55180FD7] DEFAULT (0),
[LaunchByStore] [smallint] NOT NULL CONSTRAINT [DF__PRCSCHEME__Launc__4C9018D3] DEFAULT (0),
[TOPPRC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PRCSCHEME__TOPPR__4D843D0C] DEFAULT (0),
[LOWPRC] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__PRCSCHEME__LOWPR__4E786145] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRCSCHEMEDTL] ADD CONSTRAINT [PK__PRCSCHEMEDTL__523BA32C] PRIMARY KEY CLUSTERED  ([CODE], [GDGID], [GDQPCSTR]) ON [PRIMARY]
GO
