CREATE TABLE [dbo].[PS3_ONLINERETURNORDGOODSDTL]
(
[PLATFORM] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ORDNO] [varchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [int] NOT NULL,
[GDCODE] [varchar] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[QTY] [decimal] (24, 4) NOT NULL,
[RATIO] [decimal] (24, 4) NOT NULL,
[PRICE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3_ONLIN__PRICE__60B27AD1] DEFAULT ((0)),
[TOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3_ONLIN__TOTAL__61A69F0A] DEFAULT ((0)),
[UUID] [varchar] (100) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3_ONLINERETURNORDGOODSDTL] ADD CONSTRAINT [PK__PS3_ONLI__87A446EF638EE77C] PRIMARY KEY CLUSTERED  ([UUID], [ITEMNO], [GDCODE]) ON [PRIMARY]
GO
