CREATE TABLE [dbo].[RFEMPLOCKORD]
(
[ORDNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[EMPGID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RFEMPLOCKORD] ADD CONSTRAINT [PK__RFEMPLOCKORD__288264F0] PRIMARY KEY CLUSTERED  ([ORDNUM]) ON [PRIMARY]
GO
