CREATE TABLE [dbo].[PROCDRPT]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[BWRH] [int] NOT NULL,
[BGDGID] [int] NOT NULL,
[DQ1] [money] NOT NULL CONSTRAINT [DF__PROCDRPT__DQ1__2C0BD8A3] DEFAULT (0),
[DT1] [money] NOT NULL CONSTRAINT [DF__PROCDRPT__DT1__2CFFFCDC] DEFAULT (0),
[DI1] [money] NOT NULL CONSTRAINT [DF__PROCDRPT__DI1__2DF42115] DEFAULT (0),
[DR1] [money] NOT NULL CONSTRAINT [DF__PROCDRPT__DR1__2EE8454E] DEFAULT (0),
[DD1] [money] NOT NULL CONSTRAINT [DF__PROCDRPT__DD1__2FDC6987] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROCDRPT] ADD CONSTRAINT [PK__PROCDRPT__7A8729A3] PRIMARY KEY CLUSTERED  ([ADATE], [BGDGID], [BWRH], [ASTORE], [ASETTLENO]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
