CREATE TABLE [dbo].[INVCHGMRPTX]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[BGDGID] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[DIN1] [money] NOT NULL CONSTRAINT [DF__INVCHGMRPT__DIN1__79756BDE] DEFAULT (0),
[DIN2] [money] NOT NULL CONSTRAINT [DF__INVCHGMRPT__DIN2__7A699017] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INVCHGMRPTX] ADD CONSTRAINT [PK__INVCHGMRPTX__7CA47C3F] PRIMARY KEY CLUSTERED  ([ASETTLENO], [BGDGID], [BWRH], [ASTORE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
