CREATE TABLE [dbo].[FATOOLBAR]
(
[FGID] [int] NOT NULL,
[FINDEX] [int] NOT NULL,
[FCAPTION] [varchar] (64) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FMULTILINE] [int] NOT NULL CONSTRAINT [DF__FATOOLBAR__FMULT__13386B3D] DEFAULT (1),
[FITEMSTYLE] [int] NOT NULL CONSTRAINT [DF__FATOOLBAR__FITEM__142C8F76] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FATOOLBAR] ADD CONSTRAINT [PK__FATOOLBAR__1520B3AF] PRIMARY KEY CLUSTERED  ([FGID], [FINDEX]) ON [PRIMARY]
GO
