CREATE TABLE [dbo].[BILLSTAT]
(
[NO] [int] NOT NULL,
[NAME] [char] (16) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BILLSTAT] ADD CONSTRAINT [PK__BILLSTAT__1881A0DE] PRIMARY KEY CLUSTERED  ([NO]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
