CREATE TABLE [dbo].[DMDPRMLOG]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CHKFLAG] [smallint] NOT NULL,
[OPER] [int] NOT NULL,
[ATIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DMDPRMLOG] ADD CONSTRAINT [PK__DMDPRMLOG__4C0144E4] PRIMARY KEY CLUSTERED  ([NUM], [CHKFLAG], [ATIME]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
