CREATE TABLE [dbo].[CQNORDDTL]
(
[GROUPID] [int] NOT NULL,
[RHQUUID] [char] (32) COLLATE Chinese_PRC_CI_AS NULL,
[NTYPE] [int] NOT NULL,
[NSTAT] [int] NOT NULL CONSTRAINT [DF__CQNORDDTL__NSTAT__5C3BA560] DEFAULT (0),
[NNOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[EXTIME] [datetime] NOT NULL CONSTRAINT [DF__CQNORDDTL__EXTIM__5D2FC999] DEFAULT (getdate()),
[SETTLENO] [int] NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[CASES] [decimal] (24, 4) NULL,
[QTY] [decimal] (24, 4) NOT NULL,
[PRICE] [decimal] (24, 4) NOT NULL,
[TOTAL] [decimal] (24, 4) NOT NULL,
[TAX] [decimal] (24, 4) NOT NULL,
[VALIDDATE] [datetime] NULL,
[WRH] [int] NOT NULL CONSTRAINT [DF__CQNORDDTL__WRH__5E23EDD2] DEFAULT (1),
[INVQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNORDDTL__INVQT__5F18120B] DEFAULT (0),
[ARVQTY] [decimal] (24, 4) NULL CONSTRAINT [DF__CQNORDDTL__ARVQT__600C3644] DEFAULT (0),
[ASNQTY] [decimal] (24, 4) NULL CONSTRAINT [DF__CQNORDDTL__ASNQT__61005A7D] DEFAULT (0),
[ALLINVQTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__CQNORDDTL__ALLIN__61F47EB6] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[FROMGID] [int] NOT NULL CONSTRAINT [DF__CQNORDDTL__FROMG__62E8A2EF] DEFAULT (1),
[FLAG] [int] NOT NULL CONSTRAINT [DF__CQNORDDTL__FLAG__63DCC728] DEFAULT (0),
[INUSE] [smallint] NOT NULL CONSTRAINT [DF__CQNORDDTL__INUSE__64D0EB61] DEFAULT (0),
[LOCKNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[LOCKCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SUBWRH] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CQNORDDTL] ADD CONSTRAINT [PK__CQNORDDTL__65C50F9A] PRIMARY KEY CLUSTERED  ([GROUPID], [NUM], [LINE]) ON [PRIMARY]
GO
