CREATE TABLE [dbo].[PSMKTIVGTDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[FLAG] [smallint] NULL CONSTRAINT [DF__PSMKTIVGTD__FLAG__625E930A] DEFAULT (0),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[OBJCODE] [char] (6) COLLATE Chinese_PRC_CI_AS NOT NULL,
[OBJNAME] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TYPECODE] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL,
[TYPENAME] [char] (50) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSMKTIVGTDTL] ADD CONSTRAINT [PK__PSMktIvgtDtl__6352B743] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
