CREATE TABLE [dbo].[VOUCHERACTBCKVOUGETDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[ITEM] [int] NOT NULL,
[CALCTYPE] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VOUCHERNUM] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VOUCHERAMT] [decimal] (24, 2) NOT NULL,
[VOUCHERACTIVITY] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VOUCHERGIVERULE] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VOUCHERUSERULE] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHERACTBCKVOUGETDTL] ADD CONSTRAINT [PK__VOUCHERACTBCKVOU__626FDABA] PRIMARY KEY CLUSTERED  ([NUM], [LINE], [ITEM]) ON [PRIMARY]
GO
