CREATE TABLE [dbo].[GDINPRCADJ]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SRC] [int] NOT NULL,
[STAT] [smallint] NOT NULL,
[LAUNCH] [datetime] NOT NULL,
[FILLER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FILLDATE] [datetime] NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL,
[CHECKER] [char] (30) COLLATE Chinese_PRC_CI_AS NULL,
[CHKDATE] [datetime] NULL,
[SRCBILL] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[SRCNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NULL,
[SRCCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GDINPRCADJ] ADD CONSTRAINT [PK__GDINPRCADJ__1D8A45D0] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
