CREATE TABLE [dbo].[STKOUTBCK]
(
[CLS] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NULL,
[CLIENT] [int] NULL CONSTRAINT [DF__STKOUTBCK__CLIEN__00F4FB67] DEFAULT (1),
[BILLTO] [int] NULL CONSTRAINT [DF__STKOUTBCK__BILLT__01E91FA0] DEFAULT (1),
[OCRDATE] [datetime] NULL,
[TOTAL] [money] NULL,
[TAX] [money] NULL,
[WRH] [int] NULL,
[FILDATE] [datetime] NULL,
[FILLER] [int] NULL CONSTRAINT [DF__STKOUTBCK__FILLE__02DD43D9] DEFAULT (1),
[CHECKER] [int] NULL CONSTRAINT [DF__STKOUTBCK__CHECK__03D16812] DEFAULT (1),
[STAT] [smallint] NULL CONSTRAINT [DF__STKOUTBCK__STAT__04C58C4B] DEFAULT (0),
[MODNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SLR] [int] NULL CONSTRAINT [DF__STKOUTBCK__SLR__05B9B084] DEFAULT (1),
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[RECCNT] [int] NULL,
[SRC] [int] NULL,
[SRCNUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[PRNTIME] [datetime] NULL,
[PAYMODE] [char] (20) COLLATE Chinese_PRC_CI_AS NULL,
[CAUSE] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__stkoutbck__CAUSE__3F12F4C8] DEFAULT ('不明'),
[PRECHECKER] [int] NULL CONSTRAINT [DF__stkoutbck__PRECH__6FB62C23] DEFAULT (0),
[PRECHKDATE] [datetime] NULL,
[GEN] [int] NULL,
[GENBILL] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[GENCLS] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[GENNUM] [varchar] (14) COLLATE Chinese_PRC_CI_AS NULL,
[FINISHED] [smallint] NOT NULL CONSTRAINT [DF__STKOUTBCK__FINIS__56A06596] DEFAULT (0),
[BCKTYPE] [varchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[PayDate] [datetime] NULL,
[FromNum] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SCORE] [money] NULL,
[ReCheckDate] [datetime] NULL,
[GFTTOTAL] [decimal] (24, 4) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STKOUTBCK] WITH NOCHECK ADD CONSTRAINT [STKOUTBCK_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[STKOUTBCK] ADD CONSTRAINT [PK__STKOUTBCK__23893F36] PRIMARY KEY CLUSTERED  ([CLS], [NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FILDATE] ON [dbo].[STKOUTBCK] ([FILDATE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
