CREATE TABLE [dbo].[INVDRPTX]
(
[ASTORE] [int] NOT NULL,
[ASETTLENO] [int] NOT NULL,
[ADATE] [datetime] NOT NULL,
[BGDGID] [int] NOT NULL,
[BWRH] [int] NOT NULL,
[CIN] [money] NOT NULL CONSTRAINT [DF__INVDRPTX__CIN__647A4EF8] DEFAULT (0),
[FIN] [money] NOT NULL CONSTRAINT [DF__INVDRPTX__FIN__656E7331] DEFAULT (0),
[FTAXRATE] [money] NOT NULL CONSTRAINT [DF__INVDRPTX__FTAXRA__6662976A] DEFAULT (17),
[FSALETAX] [money] NOT NULL CONSTRAINT [DF__INVDRPTX__FSALET__6756BBA3] DEFAULT (17)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INVDRPTX] ADD CONSTRAINT [PK__INVDRPTX__00750D23] PRIMARY KEY CLUSTERED  ([ADATE], [BGDGID], [BWRH], [ASETTLENO], [ASTORE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
