CREATE TABLE [dbo].[BRAND]
(
[CODE] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (40) COLLATE Chinese_PRC_CI_AS NOT NULL,
[AREA] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__BRAND__AREA__372AE799] DEFAULT (1),
[TEMPLATEGID] [int] NULL,
[CREATOR] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__BRAND__CREATOR__2A65E958] DEFAULT ('未知[-]'),
[CREATETIME] [datetime] NOT NULL CONSTRAINT [DF__BRAND__CREATETIM__2B5A0D91] DEFAULT (getdate()),
[LSTUPDOPER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__BRAND__LSTUPDOPE__2C4E31CA] DEFAULT ('未知[-]'),
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__BRAND__LSTUPDTIM__2D425603] DEFAULT (getdate()),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[INTRODUCETIME] [datetime] NULL,
[INTRODUCEOPER] [int] NULL,
[BUSINESSSTAT] [smallint] NOT NULL CONSTRAINT [DF__BRAND__BUSINESSS__7EB31AFA] DEFAULT (1),
[ELIMINATETIME] [datetime] NULL,
[BRANDCLASS] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BRAND] ADD CONSTRAINT [PK_BRAND] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
