CREATE TABLE [dbo].[THDUpdSqlhst]
(
[FID] [int] NOT NULL IDENTITY(1, 1),
[FVersionNo] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FType] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__THDUpdSql__FType__1D33A967] DEFAULT (''),
[FFileName] [char] (255) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FFlag] [int] NOT NULL CONSTRAINT [DF__THDUpdSql__FFlag__1E27CDA0] DEFAULT (0),
[FBLineNo] [int] NOT NULL CONSTRAINT [DF__THDUpdSql__FBLin__1F1BF1D9] DEFAULT (0),
[FELineNo] [int] NOT NULL CONSTRAINT [DF__THDUpdSql__FELin__20101612] DEFAULT (0),
[FINSERTDATETIME] [datetime] NOT NULL CONSTRAINT [DF__THDUpdSql__FINSE__21043A4B] DEFAULT (getdate()),
[FUPDATEDATETIME] [datetime] NULL,
[FEXECTIME] [datetime] NULL,
[FSENDDATETIME] [datetime] NULL,
[FTM] [timestamp] NOT NULL,
[FNote] [varchar] (1000) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__THDUpdSql__FNote__21F85E84] DEFAULT (''),
[FSQLLEN] [int] NOT NULL CONSTRAINT [DF__THDUpdSql__FSQLL__22EC82BD] DEFAULT (0),
[FSQLTEXT] [text] COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[THDUpdSqlhst] ADD CONSTRAINT [PK__THDUpdSqlhst__1C3F852E] PRIMARY KEY CLUSTERED  ([FID]) ON [PRIMARY]
GO
