CREATE TABLE [dbo].[GROUPCNTR]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VERSION] [int] NOT NULL,
[CNTRNUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CNTRVERSION] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GROUPCNTR] ADD CONSTRAINT [PK__GROUPCNTR__4F55E037] PRIMARY KEY CLUSTERED  ([NUM], [VERSION], [CNTRNUM], [CNTRVERSION]) ON [PRIMARY]
GO
