CREATE TABLE [dbo].[CRMCONSCORESCODTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[SORT] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMCONSCOR__SORT__4265F96D] DEFAULT ('-'),
[SUBJECT] [char] (3) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SCORE] [decimal] (24, 2) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMCONSCORESCODTL] ADD CONSTRAINT [PK__CRMCONSCORESCODT__435A1DA6] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
