CREATE TABLE [dbo].[EORD]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLAG] [smallint] NOT NULL CONSTRAINT [DF__EORD__FLAG__1BB4A9F2] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EORD] ADD CONSTRAINT [PK__EORD__1AC085B9] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
