CREATE TABLE [dbo].[CRMVALUE]
(
[CATALOG] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[CODE] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NAME] [char] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMVALUE] ADD CONSTRAINT [PK__CRMVALUE__177B9B68] PRIMARY KEY CLUSTERED  ([CATALOG], [CODE]) ON [PRIMARY]
GO
