CREATE TABLE [dbo].[DTSREG]
(
[PACKAGENAME] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MEMO] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[INUSE] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DTSREG] ADD CONSTRAINT [PK__DTSREG__1EDF2813] PRIMARY KEY CLUSTERED  ([PACKAGENAME]) ON [PRIMARY]
GO
