CREATE TABLE [dbo].[TOURSCONSUMEDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[POSNO] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FLOWNO] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ITEMNO] [smallint] NOT NULL,
[GID] [int] NOT NULL,
[QTY] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__TOURSCONSUM__QTY__57AD911B] DEFAULT (0),
[REALAMT] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__TOURSCONS__REALA__58A1B554] DEFAULT (0),
[TOURGUIDEDIS] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__TOURSCONS__TOURG__5995D98D] DEFAULT (0),
[TOURGUIDESPECDIS] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__TOURSCONS__TOURG__5A89FDC6] DEFAULT (0),
[EMPRATE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__TOURSCONS__EMPRA__5B7E21FF] DEFAULT (0),
[SHOPGUIDERATE] [decimal] (24, 4) NOT NULL CONSTRAINT [DF__TOURSCONS__SHOPG__5C724638] DEFAULT (0),
[DISTOTAL] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__TOURSCONS__DISTO__65078C39] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TOURSCONSUMEDTL] ADD CONSTRAINT [PK__TOURSCONSUMEDTL__5D666A71] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_TSD_POS2] ON [dbo].[TOURSCONSUMEDTL] ([POSNO], [FLOWNO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_TSD_POS] ON [dbo].[TOURSCONSUMEDTL] ([POSNO], [FLOWNO], [ITEMNO]) ON [PRIMARY]
GO
