CREATE TABLE [dbo].[PSSUMSCOREDTL]
(
[UUID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BEGINAMOUNT] [decimal] (24, 2) NOT NULL,
[ENDAMOUNT] [decimal] (24, 2) NOT NULL,
[SORT] [varchar] (50) COLLATE Chinese_PRC_CI_AS NOT NULL,
[AMOUNT] [decimal] (24, 2) NOT NULL,
[SCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PSSUMSCOR__SCORE__0B64A150] DEFAULT (1),
[BEGINDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSSUMSCOREDTL] ADD CONSTRAINT [PK__PSSUMSCOREDTL__0C58C589] PRIMARY KEY CLUSTERED  ([UUID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_PSSUMSCOREDTL_SORT] ON [dbo].[PSSUMSCOREDTL] ([SORT]) ON [PRIMARY]
GO
