CREATE TABLE [dbo].[ADJVDDTL]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NULL,
[QTY] [money] NULL,
[TOTAL] [money] NULL,
[VALIDDATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ADJVDDTL] ADD CONSTRAINT [PK__ADJVDDTL__0E04126B] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [adjvddtl_gdgid] ON [dbo].[ADJVDDTL] ([GDGID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
