CREATE TABLE [dbo].[CRMSCOREPRIZE]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NOT NULL,
[STAT] [smallint] NOT NULL CONSTRAINT [DF__CRMSCOREPR__STAT__1963E3DA] DEFAULT (0),
[MEMBER] [int] NOT NULL,
[REVSCORE] [decimal] (24, 2) NOT NULL,
[SCORE] [decimal] (24, 2) NOT NULL,
[MODIFIER] [char] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LSTUPDTIME] [datetime] NOT NULL CONSTRAINT [DF__CRMSCOREP__LSTUP__1A580813] DEFAULT (getdate()),
[PRNTIME] [datetime] NULL,
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[PRIZEMODE] [char] (20) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__CRMSCOREP__PRIZE__1B4C2C4C] DEFAULT ('单类别')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRMSCOREPRIZE] ADD CONSTRAINT [PK__CRMSCOREPRIZE__1C405085] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
