CREATE TABLE [dbo].[PS3SCOREGOODSDTL]
(
[NUM] [char] (14) COLLATE Chinese_PRC_CI_AS NOT NULL,
[LINE] [int] NOT NULL,
[GID] [int] NOT NULL,
[SCORE] [decimal] (24, 2) NOT NULL CONSTRAINT [DF__PS3SCOREG__SCORE__53DF623C] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PS3SCOREGOODSDTL] ADD CONSTRAINT [PK__PS3SCOREGOODSDTL__54D38675] PRIMARY KEY CLUSTERED  ([NUM], [LINE]) ON [PRIMARY]
GO
