CREATE TABLE [dbo].[NLTDADJDTL]
(
[SRC] [int] NOT NULL,
[ID] [int] NOT NULL,
[LINE] [smallint] NOT NULL,
[GDGID] [int] NOT NULL,
[OLDVALUE] [int] NOT NULL,
[NEWVALUE] [int] NOT NULL,
[NOTE] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[OLDSALE] [int] NULL,
[NEWSALE] [int] NULL,
[FINISHDATE] [datetime] NOT NULL CONSTRAINT [DF__NLTDADJDT__FINIS__1D6B1596] DEFAULT ('9999.12.31 23:59:59')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NLTDADJDTL] ADD CONSTRAINT [PK__NLTDADJDTL__12F546BF] PRIMARY KEY CLUSTERED  ([SRC], [ID], [LINE]) ON [PRIMARY]
GO
