CREATE TABLE [dbo].[BCKEXPPRINTLOG]
(
[ORDNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[PRINTDATE] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BCKEXPPRINTLOG] ADD CONSTRAINT [PK__BCKEXPPRINTLOG__0FD12356] PRIMARY KEY CLUSTERED  ([ORDNUM]) ON [PRIMARY]
GO
