CREATE TABLE [dbo].[ORD]
(
[NUM] [char] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[SETTLENO] [int] NULL,
[VENDOR] [int] NULL CONSTRAINT [DF__ORD__VENDOR__4B5804C5] DEFAULT (1),
[TOTAL] [money] NULL CONSTRAINT [DF__ORD__TOTAL__4C4C28FE] DEFAULT (0),
[TAX] [money] NULL CONSTRAINT [DF__ORD__TAX__4D404D37] DEFAULT (0),
[NOTE] [varchar] (255) COLLATE Chinese_PRC_CI_AS NULL,
[FILDATE] [datetime] NULL CONSTRAINT [DF__ORD__FILDATE__4E347170] DEFAULT (getdate()),
[PAYDATE] [datetime] NULL,
[PREPAY] [money] NULL CONSTRAINT [DF__ORD__PREPAY__4F2895A9] DEFAULT (0),
[FILLER] [int] NULL CONSTRAINT [DF__ORD__FILLER__501CB9E2] DEFAULT (1),
[CHECKER] [int] NULL CONSTRAINT [DF__ORD__CHECKER__5110DE1B] DEFAULT (1),
[PSR] [int] NULL CONSTRAINT [DF__ORD__PSR__52050254] DEFAULT (1),
[STAT] [smallint] NULL CONSTRAINT [DF__ORD__STAT__52F9268D] DEFAULT (0),
[MODNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[WRH] [int] NULL CONSTRAINT [DF__ORD__WRH__53ED4AC6] DEFAULT (1),
[RECCNT] [int] NULL CONSTRAINT [DF__ORD__RECCNT__54E16EFF] DEFAULT (0),
[SRC] [int] NULL,
[SRCNUM] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[SNDTIME] [datetime] NULL,
[RECEIVER] [int] NULL,
[PRNTIME] [datetime] NULL,
[FINISHED] [smallint] NULL CONSTRAINT [DF__ORD__FINISHED__55D59338] DEFAULT (0),
[AUTO] [smallint] NULL CONSTRAINT [DF__ORD__AUTO__56C9B771] DEFAULT (0),
[ALCCLS] [char] (10) COLLATE Chinese_PRC_CI_AS NULL,
[EXPDATE] [datetime] NULL,
[PRECHECKER] [int] NULL CONSTRAINT [DF__ord__PRECHECKER__0C5C8C72] DEFAULT (0),
[PRECHKDATE] [datetime] NULL,
[DLVBDATE] [datetime] NULL,
[DLVEDATE] [datetime] NULL,
[IMPFLAG] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[ALCGID] [int] NULL,
[TAXRATELMT] [money] NULL,
[DEPT] [varchar] (13) COLLATE Chinese_PRC_CI_AS NULL,
[STAT2] [int] NOT NULL CONSTRAINT [DF__ORD__STAT2__6E853E24] DEFAULT ((-1))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORD] WITH NOCHECK ADD CONSTRAINT [ORD_单号长度限制10位] CHECK ((len([NUM])=(10)))
GO
ALTER TABLE [dbo].[ORD] ADD CONSTRAINT [PK__ORD__4A63E08C] PRIMARY KEY CLUSTERED  ([NUM]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [EXPDATE] ON [dbo].[ORD] ([EXPDATE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FILDATE] ON [dbo].[ORD] ([FILDATE]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
